import json
import os

all_updates = {
    "Ksamil": {
        "Simple": {"description": "Ksamil sahilinin en minimalist ve şık mekanlarından biri olan Simple, adından da anlaşılacağı gibi sadelikle gelen bir şıklık sunar. Turkuaz denize bakan geniş terası ve kentin taze deniz havasını hissettiren atmosferiyle huzurlu bir duraktır.", "description_en": "One of Ksamil's most minimalist and stylish venues, Simple offers an elegance that comes with simplicity. With its large terrace overlooking the turquoise sea and atmosphere reflecting the city's fresh sea air, it's a peaceful stop.", "tips": "Özellikle kahvaltı tabağı ve taze sıkılmış meyve suları çok başarılıdır; kafa dinlemek için sabah saatlerinde gidin.", "tips_en": "The breakfast platter and fresh juices are very successful; go in the morning for some peace of mind.", "category": "Sosyal"},
        "Cunat e Ullirit": {"description": "Zeytin ağaçları gölgesinde otantik bir Arnavut mutfağı deneyimi sunan Cunat e Ullirit, kentin geleneksel lezzet duraklarından biridir. Samimi aile işletmesi atmosferi ve yerel malzemelerle hazırlanan yemekleriyle kentin ruhunu yansıtır.", "description_en": "Offering an authentic Albanian culinary experience in the shade of olive trees, Cunat e Ullirit is one of the city's traditional flavor stops. It reflects the city's soul with its sincere family-run atmosphere and meals prepared with local ingredients.", "tips": "Kuzu tandır ve yerel zeytinyağlıları mutlaka deneyin; bahçedeki zeytin ağaçlarının altında oturmak çok keyiflidir.", "tips_en": "Try the lamb tandoori and local olive oil dishes; sitting under the olive trees in the garden is very pleasant.", "category": "Restoran"},
        "Blue Pool Bar-Coffe": {"description": "Ksamil'in en ferah havuz barlarından biri olan Blue Pool, masmavi suyu ve enerjik atmosferiyle kentin yaz neşesini yansıtır. Gün boyu çalan hafif müzikler ve serinletici içeceklerle kentsel sıcaktan kaçmak için ideal bir noktadır.", "description_en": "One of Ksamil's freshest pool bars, Blue Pool reflects the city's summer joy with its deep blue water and energetic atmosphere. It's an ideal spot to escape urban heat with light music and refreshing drinks playing all day.", "tips": "Happy hour saatlerini kaçırmayın; havuz kenarındaki localarda dinlenmek için önceden rezervasyon yapabilirsiniz.", "tips_en": "Don't miss the happy hour; you can pre-book the cabanas by the pool for relaxation.", "category": "Sosyal"},
        "Hello Créperie": {"description": "Ksamil sokaklarında taze pişmiş krep kokusuyla sizi karşılayan Hello Créperie, kentin en tatlı mola duraklarından biridir. Hem tatlı hem tuzlu krep seçenekleriyle kentsel keşiflerinize lezzetli bir ara vermenizi sağlar.", "description_en": "Greeting you with the scent of freshly baked crepes on the streets of Ksamil, Hello Créperie is one of the city's sweetest break stops. It allows you to take a delicious break from your urban explorations with both sweet and savory crepe options.", "tips": "Çikolatalı ve yerel meyveli krepleri favoridir; hızlı bir atıştırmalık için en doğru adrestir.", "tips_en": "Chocolate and local fruit crepes are favorites; it's the right address for a quick snack.", "category": "Sosyal"},
        "Traditional restaurant&pizza Veliaj": {"description": "Ksamil'in en köklü aile restoranlarından biri olan Veliaj, geleneksel Arnavut yemeklerini taş fırın pizzalarıyla harmanlar. Samimi servisi ve kentin yerel dokusunu yansıtan sıcak atmosferiyle akşam yemeklerinin favori adresidir.", "description_en": "One of Ksamil's most established family restaurants, Veliaj blends traditional Albanian dishes with stone oven pizzas. With its sincere service and warm atmosphere reflecting the city's local texture, it's a favorite address for dinners.", "tips": "Ev yapımı şaraplarını ve kuzu çevirmeyi mutlaka tadın; porsiyonlar oldukça büyüktür.", "tips_en": "Be sure to taste their homemade wines and spit-roasted lamb; portions are quite large.", "category": "Restoran"},
        "Pizza Zone Ksamil": {"description": "Ksamil'in en hızlı ve lezzetli pizzalarını sunan Pizza Zone, kentin enerjik temposuna ayak uyduran popüler bir duraktır. Taze malzemeleri ve çıtır hamuruyla kentsel keşifler arasında pratik bir lezzet şöleni sunar.", "description_en": "Offering Ksamil's fastest and most delicious pizzas, Pizza Zone is a popular stop keeping up with the city's energetic pace. It offers a practical flavor feast between urban explorations with its fresh ingredients and crispy dough.", "tips": "Paket servis seçeneği çok hızlıdır; sahil dönüşü hızlı bir akşam yemeği için tercih edilebilir.", "tips_en": "The delivery option is very fast; it can be preferred for a quick dinner after returning from the beach.", "category": "Restoran"},
        "Mom": {"description": "Adı gibi 'anne eli değmiş' lezzetler sunan Mom, Ksamil'in en samimi ve ev yapımı yemek odaklı restoranıdır. Kentsel modernliğin içinde geleneksel bir sığınak gibi duran bu mekan, yerel Arnavut mutfağının en saf halini sunar.", "description_en": "Offering 'home-cooked' flavors like its name, Mom is Ksamil's most sincere and home-cooked meal-oriented restaurant. Standing like a traditional refuge within urban modernity, this place offers local Albanian cuisine in its purest form.", "tips": "Günlük değişen 'Günün Yemeği' menüsünü mutlaka sorun; ev yapımı börekleri kentin en iyisidir.", "tips_en": "Be sure to ask for the daily changing 'Dish of the Day' menu; their homemade borek is the best in town.", "category": "Restoran"},
        "Foga Pirates Lounge Bar": {"description": "Korsan temalı dekorasyonu ve Ksamil'in masmavi denizine bakan konumuyla Foga Pirates, kentin en eğlenceli ve tematik barlarından biridir. Kentin gece hayatına havadar bir soluk getiren mekan, egzotik kokteylleriyle ünlüdür.", "description_en": "With its pirate-themed decoration and location overlooking Ksamil's deep blue sea, Foga Pirates is one of the city's most fun and thematic bars. Bringing an airy breath to the city's nightlife, the venue is famous for its exotic cocktails.", "tips": "Gece ilerledikçe artan müzik ritmine ayak uydurun; korsan temalı dekorlar önünde fotoğraf çekmek için harika bir yerdir.", "tips_en": "Keep up with the music rhythm that increases as the night progresses; it's a great place to take photos in front of pirate-themed decor.", "category": "Sosyal"}
    },
    "Bari": {
        "Torre Balzano": {"description": "Bari'nin zengin tarihini yansıtan bu tarihi kule, kentin sahil savunma mimarisinin önemli bir parçasıdır. Antik taş duvarları ve Adriyatik'e bakan stratejik konumuyla kentin geçmişine ışık tutan görkemli bir mirastır.", "description_en": "Reflecting Bari's rich history, this historical tower is an important part of the city's coastal defense architecture. With its ancient stone walls and strategic location overlooking the Adriatic, it is a magnificent heritage shedding light on the city's past.", "tips": "Kule çevresindeki yürüyüş yollarını kullanın; denizden gelen esintiyle kentin tarihini hissetmek için gün batımında gidin.", "tips_en": "Use the walking paths around the tower; go at sunset to feel the city's history with the breeze coming from the sea.", "category": "Tarihi"},
        "Dea Cafè": {"description": "Bari'nin zarif sokaklarından birinde yer alan Dea Cafè, modern kentsel yaşamın içinde huzurlu bir mola noktasıdır. Taze kavrulmuş İtalyan kahveleri ve kentin en iyi pastane ürünleriyle kentsel ritmin tadını çıkarabileceğiniz şık bir duraktır.", "description_en": "Located in one of Bari's elegant streets, Dea Cafè is a peaceful break point in modern urban life. It's a stylish stop where you can enjoy the urban rhythm with freshly roasted Italian coffees and the city's best pastry products.", "tips": "Sabah espressosu ve yanında gelen minik ikramları deneyin; dışarıdaki masalarda kentin hareketliliğini izleyin.", "tips_en": "Try the morning espresso and the tiny treats that come with it; watch the city's bustle from the outdoor tables.", "category": "Sosyal"},
        "Rosalba cafè": {"description": "Bari'nin samimi ve yerel atmosferini yansıtan Rosalba Cafè, kentin en sevilen mahalle duraklarından biridir. Kentsel dostlukların pekiştiği bu kafe, geleneksel Puglia tatlıları ve güler yüzlü servisiyle ünlüdür.", "description_en": "Reflecting Bari's sincere and local atmosphere, Rosalba Cafè is one of the city's most beloved neighborhood stops. This cafe, where urban friendships are strengthened, is famous for its traditional Puglia sweets and friendly service.", "tips": "Pasticciotto tatlısını mutlaka deneyin; yerel halkla sohbet etmek için en doğru yerdir.", "tips_en": "Be sure to try the Pasticciotto sweet; it's the right place to chat with locals.", "category": "Sosyal"},
        "Le Jardin Cafè": {"description": "Bari'nin kalbinde adeta gizli bir bahçe gibi duran Le Jardin Cafè, kentsel karmaşadan kaçmak isteyenler için yemyeşil bir sığınaktır. Zarif tasarımı ve kentin en kaliteli çay seçkisiyle kentsel zarafetin adresidir.", "description_en": "Standing like a hidden garden in the heart of Bari, Le Jardin Cafè is a lush green sanctuary for those wanting to escape urban chaos. With its elegant design and the city's highest quality tea selection, it's the address for urban elegance.", "tips": "Beş çayı saati için rezervasyon yapın; bahçedeki kuş sesleri eşliğinde kitabınızı okumak için idealdir.", "tips_en": "Book for afternoon tea; it's ideal for reading your book accompanied by bird sounds in the garden.", "category": "Sosyal"},
        "Petriella al Teatro": {"description": "Bari'nin meşhur Petruzzelli Tiyatrosu'nun hemen yanında yer alan bu prestijli pastane ve kafe, kentin sanatsal ruhuyla gastronomi şıklığını birleştirir. Tiyatro öncesi ve sonrası kentin en seçkin buluşma noktasıdır.", "description_en": "Located right next to Bari's famous Petruzzelli Theatre, this prestigious pastry shop and cafe combines the city's artistic soul with gastronomic elegance. It is the city's most exclusive meeting point before and after the theater.", "tips": "Vitrindeki el yapımı çikolataları ve şık sunumlu pastaları inceleyin; tiyatro kostümü giymiş gibi şık giden yerel halkı izlemek keyiflidir.", "tips_en": "Examine the handmade chocolates and elegantly presented cakes in the window; it's pleasant to watch the locals going there dressed elegantly like theater costumes.", "category": "Sosyal"},
        "Bialetti": {"description": "İtalyan kahve kültürünün dünyaca ünlü markası Bialetti'nin Bari'deki bu şık mağazası, kentsel yaşamda kahve sanatını temsil eder. Moka potların her çeşidini ve kentin en iyi kahve aksesuarlarını bulabileceğiniz bir tasarım merkezidir.", "description_en": "This stylish Bialetti store in Bari, a world-famous brand of Italian coffee culture, represents the art of coffee in urban life. It is a design center where you can find all kinds of Moka pots and the city's best coffee accessories.", "tips": "Yeni çıkan moka pot modellerini inceleyin ve hediye olarak klasik bir cezve satın alın; kahve demleme teknikleri hakkında personelden bilgi alabilirsiniz.", "tips_en": "Check out the newly released moka pot models and buy a classic pot as a gift; you can get information from the staff about coffee brewing techniques.", "category": "Alışveriş"},
        "Greco Coffee & Food": {"description": "Bari'nin gastronomi haritasında modern bir durak olan Greco, taze sandviçleri ve gurme kahve seçenekleriyle kentsel enerjiyi yansıtır. Hızlı ama kaliteli bir kentsel öğle yemeği için kentin en popüler adreslerinden biridir.", "description_en": "A modern stop on Bari's gastronomic map, Greco reflects urban energy with its fresh sandwiches and gourmet coffee options. It's one of the city's most popular addresses for a fast but high-quality urban lunch.", "tips": "Focaccia barese ile hazırlanan sandviçleri çok lezzetlidir; kenti keşfederken pratik bir mola için tercih edin.", "tips_en": "Their sandwiches prepared with Focaccia barese are very delicious; prefer it for a practical break while exploring the city.", "category": "Restoran"},
        "Famila": {"description": "Bari'nin yerel yaşamına tanıklık edebileceğiniz bu büyük market, kentin taze ürün ve gastronomi kültürünü bir arada sunar. Yerel Puglia peynirlerinden zeytinyağlarına kadar kentin en geniş ürün seçkisine sahiptir.", "description_en": "This large market where you can witness Bari's local life offers the city's fresh products and gastronomic culture together. It has the city's widest product selection, from local Puglia cheeses to olive oils.", "tips": "Şarküteri bölümünden taze burrata peyniri ve yerel şaraplar satın alın; gerçek bir Bari alışveriş deneyimi yaşayın.", "tips_en": "Buy fresh burrata cheese and local wines from the deli section; experience a true Bari shopping experience.", "category": "Alışveriş"},
        "Panacea Ristorante": {"description": "Bari'nin deniz ürünleri mutfağındaki ustalığını yansıtan Panacea, kentin en sofistike ve kaliteli restoranlarından biridir. Adriyatik'in en taze avlarını modern sunumlarla buluşturan mekan, kentsel lüksün gastronomiyle buluştuğu noktadır.", "description_en": "Reflecting Bari's mastery in seafood cuisine, Panacea is one of the city's most sophisticated and high-quality restaurants. Bringing the freshest catches of the Adriatic together with modern presentations, it is where urban luxury meets gastronomy.", "tips": "Deniz mahsüllü tadım menüsünü mutlaka deneyin; şık bir akşam yemeği için önceden rezervasyon yaptırın.", "tips_en": "Be sure to try the seafood tasting menu; make a reservation in advance for an elegant dinner.", "category": "Restoran"},
        "Il Priscio - Bari Drinks & Food": {"description": "Bari'nin dinamik ve neşeli akşam hayatını simgeleyen Il Priscio, kentin en popüler aperitivo duraklarından biridir. Yerel içecekler ve yanında sunulan Puglia atıştırmalıklarıyla kentsel sosyalleşmenin kalbindedir.", "description_en": "Symbolizing Bari's dynamic and joyful evening life, Il Priscio is one of the city's most popular aperitivo stops. With local drinks and Puglia snacks served alongside, it's at the heart of urban socialization.", "tips": "Akşamüstü saatlerinde yerel halkın en sevdiği buluşma noktasıdır; yanına getirilen 'taralli'lerin tadına mutlaka bakın.", "tips_en": "It's the locals' favorite meeting point in the late afternoon; be sure to taste the 'taralli' served alongside.", "category": "Sosyal"}
    },
    "Budva": {
        "Hotel Kuc": {"description": "Budva'nın Becici sahilinde yer alan Hotel Kuc, Adriyatik'in masmavi manzarasına bakan konumuyla kentsel huzurun adresidir. Modern odaları ve denize sıfır terasıyla kentin yaz turizmindeki en samimi konaklama duraklarından biridir.", "description_en": "Located on Budva's Becici coast, Hotel Kuc is the address for urban peace with its location overlooking the deep blue view of the Adriatic. With its modern rooms and beachfront terrace, it's one of the city's most sincere accommodation stops in summer tourism.", "tips": "Deniz manzaralı odaları tercih edin; otelin restoranında taze Adriyatik balıklarını tadabilirsiniz.", "tips_en": "Prefer rooms with a sea view; you can taste fresh Adriatic fish at the hotel's restaurant.", "category": "Deneyim"},
        "Sova Bakery": {"description": "Budva'nın sokaklarını taze pişmiş ekmek kokusuyla donatan Sova Bakery, kentin en iyi fırın ve pastane duraklarından biridir. Geleneksel Balkan hamur işlerini modern kentsel dokuyla buluşturan bu mekan, kentin en lezzetli mola noktasıdır.", "description_en": "Equipping Budva's streets with the scent of freshly baked bread, Sova Bakery is one of the city's best bakery and pastry stops. This place, bringing traditional Balkan pastries together with modern urban texture, is the city's most delicious break point.", "tips": "Sıcak burek ve kruvasanlarını mutlaka deneyin; kenti keşfetmeye başlamadan önce lezzetli bir kahvaltı için idealdir.", "tips_en": "Be sure to try their hot burek and croissants; ideal for a delicious breakfast before starting to explore the city.", "category": "Sosyal"},
        "Cascada Club": {"description": "Budva'nın enerjik gece hayatını simgeleyen Cascada Club, Adriyatik kıyısında açık hava eğlencesinin kentsel merkezidir. Ünlü DJ performansları ve kentin yaz gecelerine havadar bir soluk getiren atmosferiyle kentin en popüler eğlence durağıdır.", "description_en": "Symbolizing Budva's energetic nightlife, Cascada Club is the urban center of open-air entertainment on the Adriatic coast. With famous DJ performances and an atmosphere bringing an airy breath to the city's summer nights, it is the city's most popular entertainment stop.", "tips": "Yaz aylarında programı çok yoğundur, gitmeden önce rezervasyon yaptırın; denize sıfır VIP masalar en iyi manzaraya sahiptir.", "tips_en": "The schedule is very busy in summer, make a reservation before going; the beachfront VIP tables have the best view.", "category": "Sosyal"}
    }
}

def apply_updates(city_file, city_updates):
    if not os.path.exists(city_file): return
    with open(city_file, 'r') as f:
        data = json.load(f)
    
    changed = False
    highlights = data if isinstance(data, list) else data.get('highlights', [])
        
    for h in highlights:
        name = h.get('name')
        if name in city_updates:
            upd = city_updates[name]
            h['description'] = upd['description']
            h['description_en'] = upd['description_en']
            h['tips'] = upd['tips']
            h['tips_en'] = upd['tips_en']
            h['category'] = upd['category']
            changed = True
            
    if changed:
        with open(city_file, 'w') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"Updated {city_file}")

# Apply updates
apply_updates('assets/cities/ksamil.json', all_updates['Ksamil'])
apply_updates('assets/cities/bari.json', all_updates['Bari'])
apply_updates('assets/cities/budva.json', all_updates['Budva'])
