import json
import requests
import time
import urllib.parse

API_KEY = 'AIzaSyBOXbf-5v4aXyEYgciwX4EfPYAGXX6Yy9g'

def get_google_photo_url(place_name):
    queries = [f"{place_name} Antalya", place_name]
    for query in queries:
        try:
            url = f"https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input={urllib.parse.quote(query)}&inputtype=textquery&fields=place_id,photos&key={API_KEY}&locationbias=circle:30000@36.8841,30.7056"
            r = requests.get(url)
            data = r.json()
            if data['status'] == 'OK' and data['candidates']:
                if 'photos' in data['candidates'][0]:
                    ref = data['candidates'][0]['photos'][0]['photo_reference']
                    print(f"  ✓ {place_name}")
                    return f"https://maps.googleapis.com/maps/api/place/photo?maxwidth=800&photoreference={ref}&key={API_KEY}"
        except:
            continue
    print(f"  ✗ {place_name}")
    return None

# BATCH 1: Kaleiçi & Merkez Detayları
batch_1 = [
    {"name": "Kaleiçi Marina (Yat Limanı)", "name_en": "Kaleici Marina", "area": "Kaleiçi", "category": "Manzara", "tags": ["liman", "tekne", "manzara"], "distanceFromCenter": 0.2, "lat": 36.8830, "lng": 30.7040, "price": "free", "rating": 4.7, "description": "Tarihi surların içinde, yatların demirlediği pitoresk liman. Gün batımı manzarası muhteşem.", "description_en": "Picturesque harbor with anchored yachts inside historic walls. Amazing sunset view.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Akşam yemeği için liman restoranlarını deneyin.", "tips_en": "Try harbor restaurants for dinner."},
    {"name": "Kaleiçi Sokakları Yürüyüşü", "name_en": "Kaleici Streets Walk", "area": "Kaleiçi", "category": "Deneyim", "tags": ["yürüyüş", "tarihi", "sokak"], "distanceFromCenter": 0.1, "lat": 36.8825, "lng": 30.7060, "price": "free", "rating": 4.8, "description": "Osmanlı dönemi evleri, butik oteller ve kafelerle dolu dar sokaklar.", "description_en": "Narrow streets full of Ottoman-era houses, boutique hotels and cafes.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Sabah erken saatlerde daha az kalabalık.", "tips_en": "Less crowded early morning."},
    {"name": "Saat Kulesi", "name_en": "Clock Tower", "area": "Kaleiçi", "category": "Tarihi", "tags": ["kule", "tarihi", "merkez"], "distanceFromCenter": 0.1, "lat": 36.8865, "lng": 30.7050, "price": "free", "rating": 4.5, "description": "Kale girişindeki tarihi saat kulesi, buluşma noktası.", "description_en": "Historic clock tower at castle entrance, meeting point.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Fotoğraf için güzel bir nokta.", "tips_en": "Nice spot for photos."},
    {"name": "Karaali Parkı", "name_en": "Karaali Park", "area": "Kaleiçi", "category": "Park", "tags": ["park", "deniz", "manzara"], "distanceFromCenter": 0.3, "lat": 36.8810, "lng": 30.7020, "price": "free", "rating": 4.6, "description": "Falezler üzerinde, deniz manzaralı huzurlu park.", "description_en": "Peaceful park on cliffs with sea view.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Gün batımı izlemek için ideal.", "tips_en": "Ideal for watching sunset."},
    {"name": "Atatürk Evi Müzesi", "name_en": "Ataturk House Museum", "area": "Kaleiçi", "category": "Müze", "tags": ["müze", "tarih", "atatürk"], "distanceFromCenter": 0.2, "lat": 36.8835, "lng": 30.7055, "price": "low", "rating": 4.4, "description": "Atatürk'ün Antalya ziyaretinde kaldığı tarihi ev.", "description_en": "Historic house where Ataturk stayed during Antalya visit.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Giriş ücretsiz.", "tips_en": "Free entry."},
    {"name": "Mermerli Plajı", "name_en": "Mermerli Beach", "area": "Kaleiçi", "category": "Plaj", "tags": ["plaj", "deniz", "merkez"], "distanceFromCenter": 0.2, "lat": 36.8820, "lng": 30.7055, "price": "medium", "rating": 4.3, "description": "Kaleiçi'nin hemen altındaki küçük ama şirin plaj.", "description_en": "Small but charming beach just below Kaleici.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Erken gidin, çabuk doluyor.", "tips_en": "Go early, fills up quickly."},
    {"name": "Tekeli Mehmet Paşa Camii", "name_en": "Tekeli Mehmet Pasa Mosque", "area": "Kaleiçi", "category": "Tarihi", "tags": ["cami", "osmanlı", "tarihi"], "distanceFromCenter": 0.1, "lat": 36.8855, "lng": 30.7070, "price": "free", "rating": 4.5, "description": "18. yüzyıldan kalma Osmanlı camisi, güzel çini işçiliği.", "description_en": "18th century Ottoman mosque with beautiful tilework.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Namaz vakitlerinde ziyaret etmeyin.", "tips_en": "Don't visit during prayer times."}
]

# BATCH 2: Daha Fazla Antik Kent & Tarihi Yerler
batch_2 = [
    {"name": "Side Antik Kenti", "name_en": "Side Ancient City", "area": "Manavgat", "category": "Tarihi", "tags": ["antik", "roma", "deniz"], "distanceFromCenter": 75.0, "lat": 36.7675, "lng": 31.3900, "price": "low", "rating": 4.7, "description": "Deniz kenarında antik tiyatro, Apollo Tapınağı ve antik sokaklar.", "description_en": "Ancient theater, Apollo Temple and ancient streets by the sea.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Apollo Tapınağı'nda gün batımı muhteşem.", "tips_en": "Sunset at Apollo Temple is stunning."},
    {"name": "Side Arkeoloji Müzesi", "name_en": "Side Archaeology Museum", "area": "Manavgat", "category": "Müze", "tags": ["müze", "arkeoloji", "roma"], "distanceFromCenter": 75.0, "lat": 36.7680, "lng": 31.3910, "price": "low", "rating": 4.5, "description": "Roma dönemi hamamında kurulan müze, antik heykeller.", "description_en": "Museum established in Roman period baths, ancient sculptures.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Antik tiyatronun hemen yanında.", "tips_en": "Right next to ancient theater."},
    {"name": "Myra Antik Kenti", "name_en": "Myra Ancient City", "area": "Demre", "category": "Tarihi", "tags": ["antik", "likya", "kaya mezarları"], "distanceFromCenter": 150.0, "lat": 36.2590, "lng": 29.9830, "price": "low", "rating": 4.7, "description": "Etkileyici Likya kaya mezarları ve Roma tiyatrosu.", "description_en": "Impressive Lycian rock tombs and Roman theater.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Noel Baba Kilisesi ile birlikte gezin.", "tips_en": "Visit with St. Nicholas Church."},
    {"name": "Noel Baba Kilisesi", "name_en": "St. Nicholas Church", "area": "Demre", "category": "Tarihi", "tags": ["kilise", "bizans", "noel baba"], "distanceFromCenter": 150.0, "lat": 36.2450, "lng": 29.9870, "price": "low", "rating": 4.6, "description": "Aziz Nikolaos'un (Noel Baba) gömüldüğü Bizans kilisesi.", "description_en": "Byzantine church where St. Nicholas (Santa Claus) was buried.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Aralık ayında özel etkinlikler var.", "tips_en": "Special events in December."},
    {"name": "Simena (Kaleköy)", "name_en": "Simena Kalekoy", "area": "Demre", "category": "Tarihi", "tags": ["antik", "batık şehir", "tekne"], "distanceFromCenter": 160.0, "lat": 36.1970, "lng": 29.8550, "price": "medium", "rating": 4.8, "description": "Tekneyle ulaşılan, suyun altında Roma kalıntıları bulunan köy.", "description_en": "Village reached by boat with Roman remains underwater.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Kekova tekne turlarıyla birlikte.", "tips_en": "Combined with Kekova boat tours."},
    {"name": "Kekova Adası", "name_en": "Kekova Island", "area": "Demre", "category": "Deneyim", "tags": ["batık şehir", "tekne", "şnorkel"], "distanceFromCenter": 160.0, "lat": 36.1880, "lng": 29.8650, "price": "medium", "rating": 4.9, "description": "Denizin altındaki batık Likya şehrini görebileceğiniz ada.", "description_en": "Island where you can see the sunken Lycian city underwater.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Cam tabanlı tekne turunu tercih edin.", "tips_en": "Choose glass-bottom boat tour."},
    {"name": "Xanthos Antik Kenti", "name_en": "Xanthos Ancient City", "area": "Kaş", "category": "Tarihi", "tags": ["antik", "likya", "unesco"], "distanceFromCenter": 200.0, "lat": 36.3570, "lng": 29.3170, "price": "low", "rating": 4.6, "description": "UNESCO listesindeki Likya başkenti, anıt mezarlar.", "description_en": "UNESCO-listed Lycian capital, monumental tombs.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Letoon ile birlikte gezin.", "tips_en": "Visit with Letoon."}
]

# BATCH 3: Plajlar & Doğal Güzellikler
batch_3 = [
    {"name": "Çıralı Plajı", "name_en": "Cirali Beach", "area": "Kemer", "category": "Plaj", "tags": ["plaj", "doğal", "caretta"], "distanceFromCenter": 80.0, "lat": 36.4130, "lng": 30.4750, "price": "free", "rating": 4.8, "description": "Caretta carettaların yumurtladığı korunan doğal plaj.", "description_en": "Protected natural beach where loggerhead turtles nest.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Haziran-Ağustos caretta yumurtlama sezonu.", "tips_en": "June-August is turtle nesting season."},
    {"name": "Patara Plajı", "name_en": "Patara Beach", "area": "Kaş", "category": "Plaj", "tags": ["plaj", "uzun", "doğal"], "distanceFromCenter": 200.0, "lat": 36.2740, "lng": 29.2980, "price": "low", "rating": 4.9, "description": "Türkiye'nin en uzun plajı, 18 km altın kum.", "description_en": "Turkey's longest beach, 18 km of golden sand.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Antik kent ile aynı bilet.", "tips_en": "Same ticket with ancient city."},
    {"name": "Kleopatra Plajı (Alanya)", "name_en": "Cleopatra Beach", "area": "Alanya", "category": "Plaj", "tags": ["plaj", "mavi bayrak", "kumsal"], "distanceFromCenter": 130.0, "lat": 36.5450, "lng": 31.9900, "price": "free", "rating": 4.7, "description": "Mavi bayraklı, altın kumlu ünlü plaj.", "description_en": "Blue flag beach with famous golden sand.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Mısır'dan getirtildiği söylenen kum.", "tips_en": "Sand said to be brought from Egypt."},
    {"name": "Dim Çayı", "name_en": "Dim River", "area": "Alanya", "category": "Doğa", "tags": ["nehir", "piknik", "doğa"], "distanceFromCenter": 140.0, "lat": 36.5440, "lng": 32.0950, "price": "low", "rating": 4.6, "description": "Nehir kenarında platformlarda yemek yiyebileceğiniz doğa cenneti.", "description_en": "Nature paradise where you can dine on platforms by the river.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Alabalık restoranları harika.", "tips_en": "Trout restaurants are great."},
    {"name": "Sapadere Kanyonu", "name_en": "Sapadere Canyon", "area": "Alanya", "category": "Doğa", "tags": ["kanyon", "yürüyüş", "şelale"], "distanceFromCenter": 155.0, "lat": 36.5480, "lng": 32.1750, "price": "low", "rating": 4.5, "description": "360 metre uzunluğunda yürüyüş parkuru ve şelaleler.", "description_en": "360-meter walking trail and waterfalls.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Yaz aylarında serinlemek için ideal.", "tips_en": "Ideal for cooling off in summer."},
    {"name": "Güver Uçurumu", "name_en": "Guver Cliff", "area": "Döşemealtı", "category": "Manzara", "tags": ["manzara", "uçurum", "doğa"], "distanceFromCenter": 25.0, "lat": 37.0150, "lng": 30.5120, "price": "free", "rating": 4.4, "description": "115 metre yüksekliğinde etkileyici uçurum ve orman manzarası.", "description_en": "Impressive 115-meter cliff with forest view.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sabahları sis olabilir, muhteşem görünüm.", "tips_en": "Morning fog can be spectacular."},
    {"name": "Güllük Dağı Milli Parkı", "name_en": "Gulluk Mountain National Park", "area": "Döşemealtı", "category": "Doğa", "tags": ["milli park", "doğa", "yürüyüş"], "distanceFromCenter": 30.0, "lat": 36.9800, "lng": 30.4600, "price": "low", "rating": 4.7, "description": "Termessos'u çevreleyen milli park, zengin flora/fauna.", "description_en": "National park surrounding Termessos, rich flora/fauna.", "bestTime": "İlkbahar", "bestTime_en": "Spring", "tips": "Termessos ile birlikte gezin.", "tips_en": "Visit with Termessos."}
]

# BATCH 4: Restoranlar & Yeme-İçme
batch_4 = [
    {"name": "Konyaaltı Balıkçıları", "name_en": "Konyaalti Fishermen", "area": "Konyaaltı", "category": "Restoran", "tags": ["balık", "deniz ürünleri", "liman"], "distanceFromCenter": 3.0, "lat": 36.8660, "lng": 30.6450, "price": "medium", "rating": 4.5, "description": "Balıkçı barınaklarında taze deniz ürünleri restoranları.", "description_en": "Fresh seafood restaurants at fishing shelters.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Günün taze balığını sorun.", "tips_en": "Ask for today's fresh catch."},
    {"name": "Kaleiçi Meyhane Sokağı", "name_en": "Kaleici Tavern Street", "area": "Kaleiçi", "category": "Restoran", "tags": ["meyhane", "meze", "canlı müzik"], "distanceFromCenter": 0.2, "lat": 36.8845, "lng": 30.7065, "price": "medium", "rating": 4.4, "description": "Canlı müzik ve meze eşliğinde akşam keyfi.", "description_en": "Evening enjoyment with live music and meze.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Hafta sonu canlı fasıl var.", "tips_en": "Live fasil music on weekends."},
    {"name": "Parlak Restaurant", "name_en": "Parlak Restaurant", "area": "Konyaaltı", "category": "Restoran", "tags": ["türk mutfağı", "kahvaltı", "yerel"], "distanceFromCenter": 2.5, "lat": 36.8700, "lng": 30.6550, "price": "low", "rating": 4.6, "description": "Serpme kahvaltı ve geleneksel Türk mutfağı.", "description_en": "Spread breakfast and traditional Turkish cuisine.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Serpme kahvaltıları meşhur.", "tips_en": "Their spread breakfasts are famous."},
    {"name": "Asmani", "name_en": "Asmani", "area": "Kaleiçi", "category": "Restoran", "tags": ["fine dining", "osmanlı", "tarihi"], "distanceFromCenter": 0.2, "lat": 36.8840, "lng": 30.7050, "price": "high", "rating": 4.7, "description": "Tarihi Osmanlı konağında fine dining deneyimi.", "description_en": "Fine dining experience in historic Ottoman mansion.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Rezervasyon şart.", "tips_en": "Reservation required."},
    {"name": "Lara Tantuni", "name_en": "Lara Tantuni", "area": "Lara", "category": "Sokak Lezzeti", "tags": ["tantuni", "dürüm", "hızlı"], "distanceFromCenter": 8.0, "lat": 36.8520, "lng": 30.8100, "price": "low", "rating": 4.5, "description": "Yerel halkın favorisi tantuni ve dürümler.", "description_en": "Local favorite tantuni and wraps.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Acılı isteyin, tadı daha güzel.", "tips_en": "Ask for spicy, tastes better."},
    {"name": "Piyaz Evi", "name_en": "Piyaz House", "area": "Merkez", "category": "Restoran", "tags": ["piyaz", "geleneksel", "yerel"], "distanceFromCenter": 1.0, "lat": 36.8850, "lng": 30.7100, "price": "low", "rating": 4.6, "description": "Antalya'nın meşhur piyazı ve tahin tatlısı.", "description_en": "Antalya's famous piyaz and tahini dessert.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Piyaz yanında şiş köfte mutlaka alın.", "tips_en": "Get shish kofte with piyaz."},
    {"name": "Şiş Köfteci Müdürüm", "name_en": "Sis Kofteci Mudurum", "area": "Merkez", "category": "Restoran", "tags": ["şiş köfte", "yerel", "geleneksel"], "distanceFromCenter": 0.8, "lat": 36.8855, "lng": 30.7095, "price": "low", "rating": 4.7, "description": "Antalya'nın meşhur şiş köftesinin en iyi adresi.", "description_en": "Best address for Antalya's famous shish kofte.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Öğle saatlerinde sıra oluyor.", "tips_en": "Queue forms at lunch times."}
]

# BATCH 5: Kafeler & Beach Clublar
batch_5 = [
    {"name": "Falez Kafeleri", "name_en": "Cliff Cafes", "area": "Konyaaltı", "category": "Kafe", "tags": ["kafe", "manzara", "falez"], "distanceFromCenter": 2.5, "lat": 36.8680, "lng": 30.6500, "price": "medium", "rating": 4.5, "description": "Akdeniz manzaralı, falezler üzerindeki kafeler.", "description_en": "Cafes on cliffs with Mediterranean view.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Gün batımı için erken gidin.", "tips_en": "Go early for sunset."},
    {"name": "Beach Park Konyaaltı", "name_en": "Beach Park Konyaalti", "area": "Konyaaltı", "category": "Deneyim", "tags": ["plaj", "eğlence", "gece hayatı"], "distanceFromCenter": 3.0, "lat": 36.8650, "lng": 30.6400, "price": "medium", "rating": 4.4, "description": "Gündüz plaj, akşam eğlence mekanları.", "description_en": "Beach by day, entertainment venues by night.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Yaz akşamları çok canlı.", "tips_en": "Very lively summer evenings."},
    {"name": "Su Antalya", "name_en": "Su Antalya", "area": "Lara", "category": "Bar", "tags": ["beach club", "gece hayatı", "lüks"], "distanceFromCenter": 10.0, "lat": 36.8500, "lng": 30.8200, "price": "high", "rating": 4.6, "description": "Lüks beach club, gündüz havuz akşam parti.", "description_en": "Luxury beach club, pool by day party by night.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Rezervasyon yapın.", "tips_en": "Make reservation."},
    {"name": "Lara Beach Barlar", "name_en": "Lara Beach Bars", "area": "Lara", "category": "Bar", "tags": ["bar", "plaj", "gece"], "distanceFromCenter": 10.0, "lat": 36.8515, "lng": 30.8150, "price": "medium", "rating": 4.3, "description": "Lara sahilinde gece eğlence mekanları.", "description_en": "Nightlife venues on Lara beach.", "bestTime": "Gece", "bestTime_en": "Night", "tips": "Hafta sonları daha kalabalık.", "tips_en": "More crowded on weekends."},
    {"name": "Kaleiçi Çay Bahçesi", "name_en": "Kaleici Tea Garden", "area": "Kaleiçi", "category": "Kafe", "tags": ["çay", "geleneksel", "manzara"], "distanceFromCenter": 0.2, "lat": 36.8820, "lng": 30.7035, "price": "low", "rating": 4.5, "description": "Tarihi atmosferde çay içme keyfi.", "description_en": "Tea enjoyment in historic atmosphere.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Türk kahvesi de deneyin.", "tips_en": "Try Turkish coffee too."},
    {"name": "Aura Club Kemer", "name_en": "Aura Club Kemer", "area": "Kemer", "category": "Bar", "tags": ["gece kulübü", "parti", "dans"], "distanceFromCenter": 45.0, "lat": 36.6000, "lng": 30.5600, "price": "high", "rating": 4.4, "description": "Kemer'in en popüler gece kulübü.", "description_en": "Kemer's most popular nightclub.", "bestTime": "Gece", "bestTime_en": "Night", "tips": "Hafta sonları açık hava partileri.", "tips_en": "Open air parties on weekends."}
]

# BATCH 6: Alışveriş & Pazarlar
batch_6 = [
    {"name": "Kaleiçi Tarihi Çarşı", "name_en": "Kaleici Historic Bazaar", "area": "Kaleiçi", "category": "Alışveriş", "tags": ["çarşı", "hediyelik", "el işi"], "distanceFromCenter": 0.1, "lat": 36.8860, "lng": 30.7065, "price": "variable", "rating": 4.4, "description": "El yapımı hediyelikler, takılar ve antikalar.", "description_en": "Handmade souvenirs, jewelry and antiques.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Pazarlık yapabilirsiniz.", "tips_en": "You can bargain."},
    {"name": "Mark Antalya AVM", "name_en": "Mark Antalya Mall", "area": "Konyaaltı", "category": "Alışveriş", "tags": ["avm", "modern", "sinema"], "distanceFromCenter": 2.5, "lat": 36.8720, "lng": 30.6650, "price": "variable", "rating": 4.3, "description": "Modern alışveriş merkezi, markalar ve sinema.", "description_en": "Modern shopping center, brands and cinema.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sıcak günlerde serinlemek için ideal.", "tips_en": "Ideal for cooling off on hot days."},
    {"name": "TerraCity AVM", "name_en": "TerraCity Mall", "area": "Lara", "category": "Alışveriş", "tags": ["avm", "lüks", "restoran"], "distanceFromCenter": 8.0, "lat": 36.8600, "lng": 30.7800, "price": "high", "rating": 4.5, "description": "Lüks markalar ve kaliteli restoranlar.", "description_en": "Luxury brands and quality restaurants.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Üst katta güzel view restoranları var.", "tips_en": "Nice view restaurants on top floor."},
    {"name": "Pazartesi Pazarı (Yerli Pazarı)", "name_en": "Monday Market", "area": "Merkez", "category": "Alışveriş", "tags": ["pazar", "taze", "yerel"], "distanceFromCenter": 2.0, "lat": 36.8750, "lng": 30.7200, "price": "low", "rating": 4.5, "description": "Taze meyve sebze ve yerel ürünler.", "description_en": "Fresh fruits vegetables and local products.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Pazartesi günleri kuruluyor.", "tips_en": "Set up on Mondays."},
    {"name": "Muratpaşa Semt Pazarı", "name_en": "Muratpasa District Market", "area": "Muratpaşa", "category": "Alışveriş", "tags": ["pazar", "yerel", "ekonomik"], "distanceFromCenter": 3.0, "lat": 36.8800, "lng": 30.7300, "price": "low", "rating": 4.4, "description": "Yerel halkın alışveriş yaptığı semt pazarı.", "description_en": "District market where locals shop.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Fiyatlar turistik yerlerden daha uygun.", "tips_en": "Prices better than tourist areas."}
]

# BATCH 7: Müzeler & Kültür
batch_7 = [
    {"name": "Suna-İnan Kıraç Kaleiçi Müzesi", "name_en": "Suna Inan Kirac Kaleici Museum", "area": "Kaleiçi", "category": "Müze", "tags": ["müze", "etnografya", "osmanlı"], "distanceFromCenter": 0.2, "lat": 36.8840, "lng": 30.7055, "price": "low", "rating": 4.6, "description": "Osmanlı dönemi yaşantısını anlatan etnografya müzesi.", "description_en": "Ethnography museum depicting Ottoman period life.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Giriş ücreti çok uygun.", "tips_en": "Entry fee very affordable."},
    {"name": "Antalya Oyuncak Müzesi", "name_en": "Antalya Toy Museum", "area": "Muratpaşa", "category": "Müze", "tags": ["müze", "oyuncak", "aile"], "distanceFromCenter": 1.5, "lat": 36.8880, "lng": 30.7150, "price": "low", "rating": 4.4, "description": "Nostaljik oyuncaklar sergisi, çocuklar için eğlenceli.", "description_en": "Nostalgic toys exhibition, fun for children.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Çocuklu aileler için ideal.", "tips_en": "Ideal for families with children."},
    {"name": "Cam Piramit Antalya", "name_en": "Glass Pyramid Antalya", "area": "Konyaaltı", "category": "Müze", "tags": ["müze", "fuar", "sergi"], "distanceFromCenter": 2.5, "lat": 36.8690, "lng": 30.6600, "price": "variable", "rating": 4.2, "description": "Kongre merkezi ve sergiler, modern mimari.", "description_en": "Congress center and exhibitions, modern architecture.", "bestTime": "Etkinliğe göre", "bestTime_en": "Depending on event", "tips": "Etkinlik programını kontrol edin.", "tips_en": "Check event program."},
    {"name": "Alanya Arkeoloji Müzesi", "name_en": "Alanya Archaeology Museum", "area": "Alanya", "category": "Müze", "tags": ["müze", "arkeoloji", "tarih"], "distanceFromCenter": 130.0, "lat": 36.5450, "lng": 31.9920, "price": "low", "rating": 4.4, "description": "Alanya ve çevresinden çıkan antik eserler.", "description_en": "Ancient artifacts from Alanya and surroundings.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Kale ile birlikte gezin.", "tips_en": "Visit with the castle."},
    {"name": "Side Müzesi ve Açık Hava Müzesi", "name_en": "Side Museum Open Air", "area": "Manavgat", "category": "Müze", "tags": ["müze", "açık hava", "heykel"], "distanceFromCenter": 75.0, "lat": 36.7685, "lng": 31.3905, "price": "low", "rating": 4.5, "description": "Roma dönemi hamam binasında heykeller ve açık hava sergisi.", "description_en": "Sculptures in Roman bath building and open air exhibition.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Antik kent biletine dahil.", "tips_en": "Included in ancient city ticket."}
]

# BATCH 8: Aktiviteler & Deneyimler
batch_8 = [
    {"name": "Rafting (Köprülü Kanyon)", "name_en": "Rafting Koprulu Canyon", "area": "Manavgat", "category": "Deneyim", "tags": ["rafting", "macera", "adrenalin"], "distanceFromCenter": 90.0, "lat": 37.1900, "lng": 31.1800, "price": "medium", "rating": 4.8, "description": "14 km rafting parkuru, adrenalin dolu macera.", "description_en": "14 km rafting course, adrenaline-filled adventure.", "bestTime": "Yaz", "bestTime_en": "Summer", "tips": "Suya dayanıklı kılıf alın telefonunuza.", "tips_en": "Get waterproof case for your phone."},
    {"name": "Paraşüt (Ölüdeniz)", "name_en": "Paragliding Oludeniz", "area": "Fethiye", "category": "Deneyim", "tags": ["paraşüt", "macera", "manzara"], "distanceFromCenter": 220.0, "lat": 36.5490, "lng": 29.1150, "price": "high", "rating": 4.9, "description": "Babadağ'dan atlayış, Ölüdeniz manzarası.", "description_en": "Take off from Babadag, Oludeniz view.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sabah rüzgarı daha sakin.", "tips_en": "Morning wind is calmer."},
    {"name": "Scuba Diving Kaş", "name_en": "Scuba Diving Kas", "area": "Kaş", "category": "Deneyim", "tags": ["dalış", "deniz", "macera"], "distanceFromCenter": 180.0, "lat": 36.2020, "lng": 29.6400, "price": "high", "rating": 4.8, "description": "Batık uçak ve zengin deniz yaşamı dalışı.", "description_en": "Sunken plane and rich marine life diving.", "bestTime": "Yaz", "bestTime_en": "Summer", "tips": "Sertifikalı dalış kursları mevcut.", "tips_en": "Certified diving courses available."},
    {"name": "Jeep Safari Toros Dağları", "name_en": "Jeep Safari Taurus Mountains", "area": "Kemer", "category": "Deneyim", "tags": ["safari", "doğa", "macera"], "distanceFromCenter": 50.0, "lat": 36.6500, "lng": 30.5000, "price": "medium", "rating": 4.5, "description": "Toros Dağları'nda off-road macerası.", "description_en": "Off-road adventure in Taurus Mountains.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Toz için bandana alın.", "tips_en": "Bring bandana for dust."},
    {"name": "Tekne Turu Antalya", "name_en": "Boat Tour Antalya", "area": "Kaleiçi", "category": "Deneyim", "tags": ["tekne", "deniz", "manzara"], "distanceFromCenter": 0.2, "lat": 36.8830, "lng": 30.7040, "price": "medium", "rating": 4.6, "description": "Kaleiçi limanından hareket eden günlük tekne turları.", "description_en": "Daily boat tours departing from Kaleici harbor.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Güneş kremi unutmayın.", "tips_en": "Don't forget sunscreen."},
    {"name": "Teleferik Tunektepe", "name_en": "Cable Car Tunektepe", "area": "Konyaaltı", "category": "Deneyim", "tags": ["teleferik", "manzara", "panorama"], "distanceFromCenter": 5.0, "lat": 36.8900, "lng": 30.6200, "price": "medium", "rating": 4.7, "description": "Panoramik şehir ve deniz manzarası için teleferik.", "description_en": "Cable car for panoramic city and sea view.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Gün batımı için en iyi zaman.", "tips_en": "Best time for sunset."}
]

def enrich():
    filepath = 'assets/cities/antalya.json'
    all_new = batch_1 + batch_2 + batch_3 + batch_4 + batch_5 + batch_6 + batch_7 + batch_8
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    print(f"Loaded {len(data['highlights'])} existing places.")
    
    existing_names = {p['name'].lower() for p in data['highlights']}
    places_to_add = []
    
    for place in all_new:
        if place['name'].lower() in existing_names:
            print(f"Skip: {place['name']}")
            continue
        print(f"Processing: {place['name']}")
        place['id'] = place['name'].lower().replace(' ', '-').replace('ç', 'c').replace('ğ', 'g').replace('ı', 'i').replace('ö', 'o').replace('ş', 's').replace('ü', 'u').replace('(', '').replace(')', '').replace('&', 'and')
        photo_url = get_google_photo_url(place['name'])
        place['imageUrl'] = photo_url or "https://images.unsplash.com/photo-1555990538-dca68da33989?q=80&w=800"
        place['source'] = 'google' if photo_url else 'unsplash_fallback'
        places_to_add.append(place)
        time.sleep(0.3)
    
    data['highlights'].extend(places_to_add)
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\n✅ Added {len(places_to_add)} new places. Total: {len(data['highlights'])}")

if __name__ == "__main__":
    enrich()
