import json
import os

new_rome_batch2 = [
    {
        "name": "Sistine Chapel (Cappella Sistina)",
        "name_en": "Sistine Chapel",
        "area": "Vatikan",
        "category": "Müze",
        "tags": ["sanat", "michelangelo", "rönesans", "dini"],
        "distanceFromCenter": 3.5,
        "lat": 41.9029,
        "lng": 12.4545,
        "price": "high",
        "rating": 5.0,
        "description": "Vatikan Müzeleri'nin tacı. Michelangelo'nun dünyanın en ünlü tavan fresklerini ve 'Son Yargı' başyapıtını barındıran kutsal mekan.",
        "description_en": "The crown of the Vatican Museums. A sacred space housing Michelangelo's world-famous ceiling frescoes and the 'Last Judgment' masterpiece.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Sabah (Vatikan turları ile erken giriş)",
        "bestTime_en": "Morning (Early entry via Vatican tours)",
        "tips": "İçeride konuşmak ve fotoğraf çekmek kesinlikle yasaktır.",
        "tips_en": "Talking and taking photos are strictly forbidden inside."
    },
    {
        "name": "Baths of Caracalla (Terme di Caracalla)",
        "name_en": "Baths of Caracalla",
        "area": "San Saba",
        "category": "Tarihi",
        "tags": ["antik", "hamam", "roma mimarisi", "muazzam"],
        "distanceFromCenter": 1.8,
        "lat": 41.8788,
        "lng": 12.4922,
        "price": "medium",
        "rating": 4.8,
        "description": "Antik Roma'nın en büyük ve en iyi korunmuş hamam komplekslerinden biri. Bir zamanlar 1600 kişiyi ağırlayabilen muazzam yapısı bugün hala büyüleyicidir.",
        "description_en": "One of the largest and best-preserved bath complexes of Ancient Rome. Its massive structure, which could once accommodate 1600 people, is still fascinating today.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Sanal gerçeklik (VR) turlarıyla hamamın antik dönemdeki ihtişamlı halini görebilirsiniz.",
        "tips_en": "You can see the bath's ancient splendor with virtual reality (VR) tours."
    },
    {
        "name": "Jewish Ghetto (Quartiere Ebraico)",
        "name_en": "Jewish Ghetto",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["kültür", "mutfak", "antik kalıntılar", "yahudi tarihi"],
        "distanceFromCenter": 0.5,
        "lat": 41.8922,
        "lng": 12.4772,
        "price": "free",
        "rating": 4.7,
        "description": "Roma'nın en eski mahallelerinden biri. Antik Roma tiyatrosu (Teatro di Marcello) ve harika 'Yahudi-Roma' mutfağıyla bilinen karakteristik bir bölge.",
        "description_en": "One of Rome's oldest neighborhoods. A characteristic area known for its ancient Roman theater (Theatre of Marcellus) and wonderful 'Jewish-Roman' cuisine.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Buradaki restoranlarda kızarmış enginar (Carciofi alla Giudia) mutlaka denenmesi gereken bir lezzettir.",
        "tips_en": "Fried artichokes (Carciofi alla Giudia) are a must-try delicacy in the restaurants here."
    },
    {
        "name": "Gianicolo Hill (Gianicolo Tepesi)",
        "name_en": "Janiculum Hill",
        "area": "Trastevere",
        "category": "Manzara",
        "tags": ["panaroma", "manzara", "ücretsiz", "park"],
        "distanceFromCenter": 2.2,
        "lat": 41.8911,
        "lng": 12.4608,
        "price": "free",
        "rating": 4.9,
        "description": "Roma'nın yedi tepesinden biri olmamasına rağmen, şehrin en iyi panoramik manzarasını sunan yüksek nokta.",
        "description_en": "Although not one of the seven hills of Rome, it's the high point offering the best panoramic view of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Her gün tam öğle vaktinde tepedeki topla yapılan geleneksel atışı izleyebilir veya duyabilirsiniz.",
        "tips_en": "You can watch or hear the traditional cannon shot from the hill every day at exactly noon."
    },
    {
        "name": "Fontana dell'Acqua Paola",
        "name_en": "Fontana dell'Acqua Paola",
        "area": "Gianicolo",
        "category": "Tarihi",
        "tags": ["çeşme", "barok", "manzara", "film karesi"],
        "distanceFromCenter": 2.0,
        "lat": 41.8892,
        "lng": 12.4658,
        "price": "free",
        "rating": 4.8,
        "description": "Gianicolo Tepesi'nde yer alan devasa barok çeşme. 'La Grande Bellezza' filminin açılış sahnesiyle daha da ünlenmiştir.",
        "description_en": "A massive baroque fountain on Janiculum Hill, further popularized by the opening scene of the film 'The Great Beauty'.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "Çeşmenin hemen yanındaki terastan Trastevere ve tüm Roma ayağınızın altındadır.",
        "tips_en": "The terrace right next to the fountain puts Trastevere and all of Rome at your feet."
    },
    {
        "name": "Largo di Torre Argentina",
        "name_en": "Largo di Torre Argentina",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["antik", "kedi sığınağı", "sezar", "tarih"],
        "distanceFromCenter": 0.5,
        "lat": 41.8953,
        "lng": 12.4769,
        "price": "free",
        "rating": 4.6,
        "description": "Julius Sezar'ın suikaste uğradığı yer olarak bilinen dört antik Roma tapınağının kalıntısı. Bugün aynı zamanda ünlü bir kedi sığınağına ev sahipliği yapar.",
        "description_en": "Remains of four ancient Roman temples, known as the site where Julius Caesar was assassinated. Today it also houses a famous cat sanctuary.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kalıntılar arasında dolaşan onlarca kediyi izlemek çok keyiflidir.",
        "tips_en": "It's very pleasant to watch the dozens of cats wandering among the ruins."
    },
    {
        "name": "Bocca della Verità (Gerçeğin Ağzı)",
        "name_en": "The Mouth of Truth",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["efsane", "heykel", "film mekanı", "test"],
        "distanceFromCenter": 1.2,
        "lat": 41.8881,
        "lng": 12.4814,
        "price": "low",
        "rating": 4.3,
        "description": "Yalan söyleyenlerin elini ısırdığına inanılan dev antik mermer rölyef. 'Roman Holiday' filmiyle dünya çapında popüler olmuştur.",
        "description_en": "A giant ancient marble relief believed to bite the hand of anyone who tells a lie. Popularized worldwide by the film 'Roman Holiday'.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kuyrukta bekleyip elinizi ağza sokarak klasik bir Roma fotoğrafı çektirin.",
        "tips_en": "Wait in line and get a classic Rome photo by putting your hand in the mouth."
    },
    {
        "name": "Isola Tiberina (Tiber Adası)",
        "name_en": "Tiber Island",
        "area": "Tuna (Tevere)",
        "category": "Deneyim",
        "tags": ["ada", "nehir", "tarihi", "huzur"],
        "distanceFromCenter": 1.0,
        "lat": 41.8911,
        "lng": 12.4783,
        "price": "free",
        "rating": 4.7,
        "description": "Tiber Nehri üzerindeki tek ada. Antik çağlardan beri şifa merkezi olarak bilinir, bugün ise nehir havası almak için en huzurlu noktalardan biridir.",
        "description_en": "The only island in the Tiber River. Known as a healing center since ancient times, it's now one of the most peaceful spots to enjoy the river air.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Yaz akşamları",
        "bestTime_en": "Summer evenings",
        "tips": "Yazın ada üzerinde açıkhava sineması ve festivaller kurulur.",
        "tips_en": "Outdoor cinemas and festivals are held on the island during summer."
    },
    {
        "name": "Santa Maria in Trastevere Bazilikası",
        "name_en": "Basilica of Santa Maria in Trastevere",
        "area": "Trastevere",
        "category": "Tarihi",
        "tags": ["mozaik", "kilise", "tarih", "meydan"],
        "distanceFromCenter": 2.0,
        "lat": 41.8894,
        "lng": 12.4708,
        "price": "free",
        "rating": 4.8,
        "description": "Roma'nın en eski kiliselerinden biri. İçerideki 12. yüzyıla ait altın varaklı mozaikler nefes kesicidir.",
        "description_en": "One of the oldest churches in Rome. The 12th-century gold-leaf mosaics inside are breathtaking.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Güneş battıktan sonra mozaiklerin ışıklandırması çok daha belirgin ve güzel görünür.",
        "tips_en": "After sunset, the mosaic lighting looks much more prominent and beautiful."
    },
    {
        "name": "Catacombs of San Callisto (San Callisto Yeraltı Mezarları)",
        "name_en": "Catacombs of St. Callixtus",
        "area": "Appio Latino",
        "category": "Tarihi",
        "tags": ["catacomb", "yeraltı", "hristiyanlık", "tarih"],
        "distanceFromCenter": 5.0,
        "lat": 41.8608,
        "lng": 12.5089,
        "price": "medium",
        "rating": 4.7,
        "description": "Erken Hristiyanlık dönemine ait devasa yeraltı mezarlık ağı. Yarım milyondan fazla mezar ve değerli freskler barındırır.",
        "description_en": "A massive underground burial network from the early Christian period, housing over half a million tombs and valuable frescoes.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sadece rehberli turlar ile gezilebilir, içerisi her zaman serindir.",
        "tips_en": "Can only be visited with guided tours; it's always cool inside."
    },
    {
        "name": "MAXXI - National Museum of 21st Century Arts",
        "name_en": "MAXXI",
        "area": "Flaminio",
        "category": "Müze",
        "tags": ["modern sanat", "mimari", "zaha hadid", "tasarım"],
        "distanceFromCenter": 4.0,
        "lat": 41.9281,
        "lng": 12.4667,
        "price": "medium",
        "rating": 4.6,
        "description": "Ünlü mimar Zaha Hadid tarafından tasarlanan çağdaş sanat ve mimarlık müzesi. Binanın kendisi bile bir sanat eseridir.",
        "description_en": "A contemporary art and architecture museum designed by the famous architect Zaha Hadid. The building itself is a work of art.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Fütüristik merdivenleri ve tavan pencereleri fotoğraf çekmek için harikadır.",
        "tips_en": "The futuristic staircases and skylights are great for photography."
    },
    {
        "name": "Pyramid of Cestius (Cestius Piramidi)",
        "name_en": "Pyramid of Cestius",
        "area": "Testaccio",
        "category": "Tarihi",
        "tags": ["piramit", "mısır etkisi", "antik", "mezar"],
        "distanceFromCenter": 3.0,
        "lat": 41.8764,
        "lng": 12.4808,
        "price": "free",
        "rating": 4.5,
        "description": "M.Ö. 12 yılında inşa edilmiş antik bir Roma piramidi. Roma'nın ortasında bir Mısır esintisi sunan sıradışı bir yapıdır.",
        "description_en": "An ancient Roman pyramid built in 12 BC. An unusual structure providing an Egyptian touch in the middle of Rome.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Piramidin hemen yanındaki Non-Catholic Cemetery'de (Şairler Mezarlığı) Keats ve Shelley'nin mezarlarını görebilirsiniz.",
        "tips_en": "In the Non-Catholic Cemetery (Poets' Cemetery) right next to the pyramid, you can see the graves of Keats and Shelley."
    },
    {
        "name": "Ponte Sant'Angelo (Kutsal Melek Köprüsü)",
        "name_en": "Ponte Sant'Angelo",
        "area": "Borgo",
        "category": "Tarihi",
        "tags": ["köprü", "heykel", "bernini", "manzara"],
        "distanceFromCenter": 2.5,
        "lat": 41.9021,
        "lng": 12.4664,
        "price": "free",
        "rating": 4.9,
        "description": "Castel Sant'Angelo'ya çıkan, Bernini tarafından tasarlanan muazzam melek heykelleriyle süslü Roma'nın en güzel köprüsü.",
        "description_en": "Rome's most beautiful bridge, leading to Castel Sant'Angelo and adorned with magnificent angel statues designed by Bernini.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Meleklerin her biri İsa'nın çilesine ait farklı bir sembol taşır.",
        "tips_en": "Each of the angels carries a different symbol of the Passion of Christ."
    },
    {
        "name": "Piazza del Popolo (Halk Meydanı)",
        "name_en": "Piazza del Popolo",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["meydan", "obelisk", "ikiz kiliseler", "manzara"],
        "distanceFromCenter": 1.5,
        "lat": 41.9107,
        "lng": 12.4764,
        "price": "free",
        "rating": 4.7,
        "description": "Kuzeyden Roma'ya girişi simgeleyen devasa meydan. Ortasındaki dev Mısır obeliski ve birbirinin aynısı gibi duran ikiz kiliseleriyle ünlüdür.",
        "description_en": "A massive square symbolizing the northern entry to Rome. Famous for the giant Egyptian obelisk in its center and the identical-looking twin churches.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Meydandan Pincio Tepesi'ne çıkan basamakları takip ederek şehrin en iyi manzaralarından birine ulaşabilirsiniz.",
        "tips_en": "Follow the steps from the square to Pincio Hill for one of the city's best views."
    },
    {
        "name": "Basilica di San Pietro in Vincoli (Zincirli Aziz Petrus)",
        "name_en": "San Pietro in Vincoli",
        "area": "Monti",
        "category": "Tarihi",
        "tags": ["heykel", "michelangelo", "musa", "tarihi"],
        "distanceFromCenter": 1.0,
        "lat": 41.8939,
        "lng": 12.4931,
        "price": "free",
        "rating": 4.8,
        "description": "Michelangelo'nun ünlü 'Musa' heykelini ve Aziz Petrus'u bağlayan kutsal zincirleri barındıran heybetli bir bazilika.",
        "description_en": "An imposing basilica housing Michelangelo's famous 'Moses' statue and the holy chains said to have bound St. Peter.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Girişi biraz gizlidir; Kolezyum'un yukarısındaki merdivenlerden ulaşılır.",
        "tips_en": "The entrance is a bit hidden; accessible via the stairs above the Colosseum."
    },
    {
        "name": "Chiesa di San Luigi dei Francesi",
        "name_en": "San Luigi dei Francesi",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["sanat", "caravaggio", "barok", "ücretsiz"],
        "distanceFromCenter": 0.5,
        "lat": 41.8997,
        "lng": 12.4747,
        "price": "free",
        "rating": 4.8,
        "description": "Caravaggio'nun Aziz Matta'nın hayatını anlatan üç başyapıtını (Contarelli Şapeli) barındıran muhteşem bir Fransız kilisesi.",
        "description_en": "A magnificent French church housing three masterpieces by Caravaggio depicting the life of Saint Matthew (Contarelli Chapel).",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Öğleden önce",
        "bestTime_en": "Before noon",
        "tips": "Caravaggio tablolarının ışığını yakmak için yanınızda birkaç Bozuk para bulundurun.",
        "tips_en": "Have a few coins with you to trigger the coin-operated light for the Caravaggio paintings."
    },
    {
        "name": "Mercato di Testaccio",
        "name_en": "Testaccio Market",
        "area": "Testaccio",
        "category": "Deneyim",
        "tags": ["pazar", "gurme", "lokal", "sokak lezzeti"],
        "distanceFromCenter": 3.0,
        "lat": 41.8763,
        "lng": 12.4756,
        "price": "low",
        "rating": 4.8,
        "description": "Roma'nın en iyi yerel pazarı. Gurme sandviçlerden taze makarnalara kadar şehrin en otantik mutfak deneyimini sunar.",
        "description_en": "Rome's best local market. Offers the city's most authentic culinary experience, from gourmet sandwiches to fresh pasta.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "Mordi e Vai standından klasik Roma sandviçlerini mutlaka deneyin.",
        "tips_en": "Be sure to try classic Roman sandwiches from the Mordi e Vai stall."
    },
    {
        "name": "Basilica of San Clemente",
        "name_en": "Basilica of San Clemente",
        "area": "Çevresi",
        "category": "Tarihi",
        "tags": ["katmanlar", "tarih", "yeraltı", "antik roma"],
        "distanceFromCenter": 1.0,
        "lat": 41.8894,
        "lng": 12.4975,
        "price": "medium",
        "rating": 4.9,
        "description": "Roma tarihinin katmanlarını tek bir yerde görebileceğiniz sıradışı bazilika. 12. yüzyıl kilisesinin altında 4. yüzyıl bazilikası, onun altında ise antik bir Mithras tapınağı yer alır.",
        "description_en": "An extraordinary basilica where you can see the layers of Roman history in one place. A 12th-century church sits atop a 4th-century basilica, which itself sits atop an ancient Mithraic temple.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yeraltı katlarına indikçe zaman yolculuğuna çıkmış gibi hissedeceksiniz, suyun sesini duyabilirsiniz.",
        "tips_en": "As you descend to the lower levels, you'll feel like you're traveling back in time; you can hear the sound of running water."
    },
    {
        "name": "Palazzo Barberini",
        "name_en": "Palazzo Barberini",
        "area": "Centro Storico",
        "category": "Müze",
        "tags": ["resim", "barok", "raphael", "caravaggio"],
        "distanceFromCenter": 1.5,
        "lat": 41.9031,
        "lng": 12.4903,
        "price": "medium",
        "rating": 4.7,
        "description": "Ulusal Antik Sanat Galerisi'ne ev sahipliği yapan muhteşem barok saray. Raphael'in 'La Fornarina'sı ve Caravaggio'nun 'Judith ve Holofernes'i burada sergilenir.",
        "description_en": "A magnificent Baroque palace housing the National Gallery of Ancient Art. Raphael's 'La Fornarina' and Caravaggio's 'Judith Beheading Holofernes' are exhibited here.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Bernini ve Borromini tarafından tasarlanan iki farklı merdiveni mutlaka görün.",
        "tips_en": "Be sure to see the two different staircases designed by Bernini and Borromini."
    },
    {
        "name": "Ponte Sisto",
        "name_en": "Ponte Sisto",
        "area": "Tevere",
        "category": "Tarihi",
        "tags": ["köprü", "trastevere", "nehir", "gün batımı"],
        "distanceFromCenter": 0.8,
        "lat": 41.8925,
        "lng": 12.4706,
        "price": "free",
        "rating": 4.8,
        "description": "Trastevere ile Centro Storico'yu birbirine bağlayan, Roma'nın en fotojenik ve popüler yaya köprüsü.",
        "description_en": "Rome's most photogenic and popular pedestrian bridge, connecting Trastevere with the Centro Storico.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Akşamları sokak müzisyenlerinin eşliğinde nehir manzarasını izlemek için mükemmeldir.",
        "tips_en": "Perfect for watching the river view accompanied by street musicians in the evenings."
    }
]

def enrich_rome_batch2():
    filepath = 'assets/cities/roma.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_rome_batch2:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    # I'll add more in a final batch to hit ~100.
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_rome_batch2()
print(f"Rome now has {count} highlights.")
