import json
import os

new_kopenhag_batch2 = [
    {
        "name": "Copenhagen Opera House (Operaen)",
        "name_en": "Copenhagen Opera House",
        "area": "Holmen",
        "category": "Tarihi",
        "tags": ["opera", "mimari", "modern", "sahne"],
        "distanceFromCenter": 1.5,
        "lat": 55.6819,
        "lng": 12.6006,
        "price": "high",
        "rating": 4.8,
        "description": "Dünyanın en modern ve pahalı opera binalarından biri. Henning Larsen tarafından tasarlanan bina, liman kıyısındaki ikonik duruşuyla dikkat çeker.",
        "description_en": "One of the most modern and expensive opera houses in the world. Designed by Henning Larsen, the building is iconic for its position on the harbor front.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Binanın içindeki ışıklandırma ve tavan süslemeleri büyüleyicidir; bir temsil izlemeseniz bile dışarıdan görmeye değer.",
        "tips_en": "The interior lighting and ceiling decorations are enchanting; even if you don't attend a performance, it's worth seeing from the outside."
    },
    {
        "name": "National Museum of Denmark",
        "name_en": "National Museum of Denmark",
        "area": "Centrum",
        "category": "Müze",
        "tags": ["tarih", "vikingler", "kültür", "egitici"],
        "distanceFromCenter": 0.5,
        "lat": 55.6745,
        "lng": 12.5745,
        "price": "high",
        "rating": 4.6,
        "description": "Danimarka'nın tarih öncesi çağlardan günümüze kadar olan hikayesini anlatan en büyük müzesi. Viking hazineleri ve Rün taşları buranın en önemli parçalarıdır.",
        "description_en": "Denmark's largest museum telling the country's story from prehistoric times to the present. Viking treasures and runestones are among its highlights.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Vikingler bölümündeki orijinal savaş gemilerini ve takıları mutlaka görün.",
        "tips_en": "Be sure to see the original warships and jewelry in the Viking section."
    },
    {
        "name": "Thorvaldsens Museum",
        "name_en": "Thorvaldsens Museum",
        "area": "Slotsholmen",
        "category": "Müze",
        "tags": ["heykel", "klasik", "mimari", "sanat"],
        "distanceFromCenter": 0.5,
        "lat": 55.6767,
        "lng": 12.5783,
        "price": "medium",
        "rating": 4.7,
        "description": "Danimarkalı heykeltıraş Bertel Thorvaldsen'e adanmış, büyüleyici bir mimariye ve renk paletine sahip olan müze.",
        "description_en": "A museum dedicated to the Danish sculptor Bertel Thorvaldsen, featuring captivating architecture and a distinct color palette.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın zeminlerindeki mozaikler ve her odanın farklı tavan süslemeleri fotoğrafçılar için bir hazinedir.",
        "tips_en": "The mosaic floors and unique ceiling decorations in every room are a treasure for photographers."
    },
    {
        "name": "Danish Architecture Center (DAC)",
        "name_en": "Danish Architecture Center",
        "area": "Liman Bölgesi",
        "category": "Müze",
        "tags": ["mimari", "modern", "inovasyon", "sergi"],
        "distanceFromCenter": 0.8,
        "lat": 55.6722,
        "lng": 12.5794,
        "price": "medium",
        "rating": 4.5,
        "description": "BLOX binasının içinde yer alan, Danimarka mimarisinin ve kentsel gelişiminin sergilendiği vizyoner bir merkez.",
        "description_en": "Located within the BLOX building, this visionary center showcases Danish architecture and urban development.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze içindeki dev kaydıraktan aşağı inmeyi unutmayın!",
        "tips_en": "Don't forget to take a ride down the giant slide within the museum!"
    },
    {
        "name": "Copenhagen Contemporary",
        "name_en": "Copenhagen Contemporary",
        "area": "Refshaleøen",
        "category": "Müze",
        "tags": ["modern sanat", "enstalasyon", "endüstriyel", "büyük ölçekli"],
        "distanceFromCenter": 3.0,
        "lat": 55.6925,
        "lng": 12.6130,
        "price": "medium",
        "rating": 4.6,
        "description": "Eski bir kaynak atölyesinde yer alan, dünyanın en ünlü sanatçılarının devasa enstalasyonlarına ev sahipliği yapan modern sanat merkezi.",
        "description_en": "A contemporary art center housed in a former welding workshop, host to massive installations by world-renowned artists.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Sanat merkezini gezdikten sonra hemen yanındaki Reffen'de sokak yemeği yiyebilirsiniz.",
        "tips_en": "After exploring the art center, you can enjoy street food at the neighboring Reffen."
    },
    {
        "name": "Royal Danish Playhouse (Skuespilhuset)",
        "name_en": "Royal Danish Playhouse",
        "area": "Nyhavn Yakını",
        "category": "Tarihi",
        "tags": ["tiyatro", "sahne sanatları", "mimari", "deniz manzara"],
        "distanceFromCenter": 1.2,
        "lat": 55.6811,
        "lng": 12.5939,
        "price": "medium",
        "rating": 4.7,
        "description": "Limanın hemen üzerinde yer alan, cam ve tuğla mimarisiyle modern Danimarka tiyatro sahnesinin kalbi.",
        "description_en": "A hub of the modern Danish theater scene, featuring glass and brick architecture situated right on the harbor.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz veya akşam",
        "bestTime_en": "Day or evening",
        "tips": "Binanın dışındaki ahşap iskelede oturup Nyhavn manzarasını izlemek ücretsiz ve çok huzurludur.",
        "tips_en": "Sitting on the wooden pier outside the building and watching the view of Nyhavn is free and very peaceful."
    },
    {
        "name": "Islands Brygge Harbour Bath",
        "name_en": "Islands Brygge Harbour Bath",
        "area": "Amager",
        "category": "Deneyim",
        "tags": ["yüzme", "açık hava", "yaz", "yerel"],
        "distanceFromCenter": 1.5,
        "lat": 55.6689,
        "lng": 12.5783,
        "price": "free",
        "rating": 4.6,
        "description": "Kopenhag limanının temiz sularında yüzmek için tasarlanmış, şehre çok yakın olan popüler açık hava havuzu.",
        "description_en": "A popular open-air swimming facility, very close to the city center, designed for swimming in the clean waters of Copenhagen's harbor.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Yaz günleri",
        "bestTime_en": "Summer days",
        "tips": "Danimarkalılar kışın da buz gibi suya girmeyi sever; cesaretiniz varsa 'kış yüzücülerini' izleyin.",
        "tips_en": "Danes love to swim in icy waters even in winter; if you're brave enough, watch the 'winter swimmers'."
    },
    {
        "name": "Frederiksberg Have (Bahçesi)",
        "name_en": "Frederiksberg Gardens",
        "area": "Frederiksberg",
        "category": "Park",
        "tags": ["saray bahçesi", "göl", "piknik", "romantik"],
        "distanceFromCenter": 2.5,
        "lat": 55.6744,
        "lng": 12.5256,
        "price": "free",
        "rating": 4.8,
        "description": "Danimarka'nın en büyük ve en romantik parklarından biri. Frederiksberg Sarayı manzaralı göletleri ve yürüyüş yollarıyla ünlüdür.",
        "description_en": "One of Denmark's largest and most romantic parks. Famous for its ponds and walking trails with views of Frederiksberg Palace.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Parkın içinden Kopenhag Hayvanat Bahçesi'ndeki filleri ücretsiz olarak uzaktan görebilirsiniz.",
        "tips_en": "You can catch a free glimpse of the elephants in the Copenhagen Zoo from within the park."
    },
    {
        "name": "8 House (8 Tallet)",
        "name_en": "8 House",
        "area": "Ørestad",
        "category": "Tarihi",
        "tags": ["mimari", "big", "modern yaşam", "sürdürülebilir"],
        "distanceFromCenter": 6.0,
        "lat": 55.5925,
        "lng": 12.5719,
        "price": "free",
        "rating": 4.6,
        "description": "Bjarke Ingels Grubu (BIG) tarafından tasarlanan, 8 rakamı şeklindeki ödüllü konut projesi. Modern mimari turlarının vazgeçilmez durağıdır.",
        "description_en": "The award-winning housing project designed by Bjarke Ingels Group (BIG) in the shape of the number 8. A staple on any modern architecture tour.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın üzerindeki bisiklet rampasında yürüp üst katlardaki kafede manzara izleyebilirsiniz.",
        "tips_en": "You can walk along the building's bicycle ramp and enjoy the view from the cafe on the upper floors."
    },
    {
        "name": "La Banchina",
        "name_en": "La Banchina",
        "area": "Refshaleøen",
        "category": "Kafe",
        "tags": ["sauna", "yüzme", "doğal şarap", "bohem"],
        "distanceFromCenter": 3.2,
        "lat": 55.6889,
        "lng": 12.6105,
        "price": "medium",
        "rating": 4.7,
        "description": "Kendi iskelesi ve saunası olan küçük bir kafe ve şarap barı. Yazın yüzmek, kışın ise saunadan çıkıp buz gibi denize atlamak için ideal.",
        "description_en": "A small cafe and wine bar with its own pier and sauna. Perfect for swimming in summer or jumping from the sauna into the icy sea in winter.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Öğleden sonra ve akşam",
        "bestTime_en": "Afternoon and evening",
        "tips": "Sauna için internet sitesinden önceden randevu almanız gerekebilir.",
        "tips_en": "You may need to book the sauna in advance via their website."
    },
    {
        "name": "Arken Museum of Modern Art",
        "name_en": "Arken Museum",
        "area": "Ishøj (Dış bölge)",
        "category": "Müze",
        "tags": ["modern sanat", "mimari", "deniz kıyısı", "sergi"],
        "distanceFromCenter": 18.0,
        "lat": 55.6062,
        "lng": 12.3876,
        "price": "medium",
        "rating": 4.5,
        "description": "Kum tepeleri ve deniz arasında dev bir gemiyi andıran mimarisiyle modern sanat müzesi.",
        "description_en": "A modern art museum with architecture resembling a giant ship between the sand dunes and the sea.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Müzenin içindeki Damien Hirst koleksiyonunu mutlaka inceleyin.",
        "tips_en": "Be sure to check out the Damien Hirst collection within the museum."
    },
    {
        "name": "Vesterbro'nun Sakin Sokakları (Værnedamsvej)",
        "name_en": "Værnedamsvej",
        "area": "Vesterbro",
        "category": "Alışveriş",
        "tags": ["butik", "gastronomi", "fransız ruhu", "lokal"],
        "distanceFromCenter": 2.0,
        "lat": 55.6728,
        "lng": 12.5539,
        "price": "medium",
        "rating": 4.8,
        "description": "Kopenhag'ın 'Küçük Paris'i olarak bilinen, şık butikleri, peynir dükkanları ve kafeleriyle ünlü çok keyifli bir sokak.",
        "description_en": "Known as Copenhagen's 'Little Paris', a delightful street famous for its chic boutiques, cheese shops, and cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Cumartesi sabah",
        "bestTime_en": "Saturday morning",
        "tips": "Granola'da harika bir kahvaltı yapıp sokağın tadına varabilirsiniz.",
        "tips_en": "Enjoy a wonderful breakfast at Granola and soak in the street's atmosphere."
    },
    {
        "name": "Roskilde Viking Ship Museum",
        "name_en": "Viking Ship Museum",
        "area": "Roskilde (Günübirlik)",
        "category": "Müze",
        "tags": ["viking", "gemi", "tarih", "denizcilik"],
        "distanceFromCenter": 30.0,
        "lat": 55.6508,
        "lng": 12.0801,
        "price": "medium",
        "rating": 4.6,
        "description": "11. yüzyıldan kalma beş orijinal Viking gemisinin sergilendiği ve hala geleneksel yöntemlerle gemi yapımının sürdürüldüğü benzersiz müze.",
        "description_en": "A unique museum displaying five original 11th-century Viking ships and where traditional shipbuilding methods are still practiced today.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yaz aylarında fiyord üzerinde gerçek Viking gemisi kopyalarıyla yelken açma şansınız olabilir.",
        "tips_en": "During summer months, you might have the opportunity to go sailing on the fjord in authentic Viking ship replicas."
    },
    {
        "name": "Roskilde Cathedral",
        "name_en": "Roskilde Cathedral",
        "area": "Roskilde (Günübirlik)",
        "category": "Tarihi",
        "tags": ["unesco", "kraliyet mezarları", "gotik", "tarih"],
        "distanceFromCenter": 30.0,
        "lat": 55.6426,
        "lng": 12.0804,
        "price": "medium",
        "rating": 4.7,
        "description": "Danimarka kralları ve kraliçelerinin son dinlenme yeri olan, UNESCO Dünya Mirası Listesi'ndeki görkemli gotik katedral.",
        "description_en": "The final resting place of Danish kings and queens, this magnificent Gothic cathedral is a UNESCO World Heritage site.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Katedralin içindeki kralları simgeleyen muhteşem lahiteri incelemek için sesli rehber kullanın.",
        "tips_en": "Use an audio guide to fully appreciate the magnificent sarcophagi of the kings inside the cathedral."
    },
    {
        "name": "Copenhagen Food Tours",
        "name_en": "Copenhagen Food Tours",
        "area": "Kopenhag Geneli",
        "category": "Deneyim",
        "tags": ["gastronomi", "tadımlık", "kültür", "tur"],
        "distanceFromCenter": 0.5,
        "lat": 55.6835,
        "lng": 12.5701,
        "price": "high",
        "rating": 4.9,
        "description": "Kopenhag'ın Yeni İskandinav mutfağından sokak lezzetlerine kadar uzanan gastronomi dünyasını keşfedebileceğiniz profesyonel yürüyüş turları.",
        "description_en": "Professional walking tours where you can explore Copenhagen's gastronomic world, ranging from New Nordic cuisine to local street foods.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "Aç gelin! Tur sırasında birçok yerel peynir, bira ve unlu mamul tadacaksınız.",
        "tips_en": "Come hungry! You'll sample many local cheeses, beers, and pastries during the tour."
    }
]

def enrich_kopenhag_batch2():
    filepath = 'assets/cities/kopenhag.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_kopenhag_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_kopenhag_batch2()
print(f"Kopenhag reached {count} highlights.")
