import json
import os

new_paris_batch2 = [
    {
        "name": "Musée Nissim de Camondo",
        "name_en": "Nissim de Camondo Museum",
        "area": "8. Bölge",
        "category": "Müze",
        "tags": ["saray", "dekorasyon", "tarihi", "koleksiyon"],
        "distanceFromCenter": 3.2,
        "lat": 48.8794,
        "lng": 2.3125,
        "price": "medium",
        "rating": 4.8,
        "description": "18. yüzyıl Fransız mobilya ve dekoratif sanatlarının en iyi korunan koleksiyonlarından birine ev sahipliği yapan görkemli bir ev-müze.",
        "description_en": "A majestic house-museum housing one of the best-preserved collections of 18th-century French furniture and decorative arts.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Parc Monceau'nun hemen yanında yer alan bu müze, dönemin aristokrat yaşamını mükemmel bir şekilde yansıtır.",
        "tips_en": "Located right next to Parc Monceau, this museum perfectly reflects the aristocratic life of the era."
    },
    {
        "name": "Musée Jacquemart-André",
        "name_en": "Jacquemart-Andre Museum",
        "area": "8. Bölge",
        "category": "Müze",
        "tags": ["sanat", "saray", "koleksiyon", "mimari"],
        "distanceFromCenter": 3.0,
        "lat": 48.8752,
        "lng": 2.3106,
        "price": "medium",
        "rating": 4.7,
        "description": "İtalyan Rönesansı ve 18. yüzyıl Fransız sanatının şaheserleriyle dolu, Paris'in en şık malikanelerinden birinde yer alan özel müze.",
        "description_en": "A private museum in one of Paris' most elegant mansions, filled with masterpieces of the Italian Renaissance and 18th-century French art.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin çay salonu, tavan resimleri ve zarif dekoruyla Paris'in en güzellerinden biridir.",
        "tips_en": "The museum's tea room is one of Paris' most beautiful, with its ceiling paintings and elegant decor."
    },
    {
        "name": "Musée de la Vie Romantique",
        "name_en": "Museum of Romantic Life",
        "area": "9. Bölge",
        "category": "Müze",
        "tags": ["romantik", "bahçe", "sanat", "gizli"],
        "distanceFromCenter": 3.5,
        "lat": 48.8817,
        "lng": 2.3333,
        "price": "free",
        "rating": 4.6,
        "description": "Montmartre eteklerinde, pembe panjurlu ve gül bahçeli bu ev, 19. yüzyılın romantik sanat ve edebiyat dünyasına kapı aralar.",
        "description_en": "At the foot of Montmartre, this house with pink shutters and a rose garden opens a door into the romantic art and literature world of the 19th century.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Bahar",
        "bestTime_en": "Spring",
        "tips": "Bahçedeki küçük serada yer alan 'Rose Bakery' kafede, şehir gürültüsünden uzak bir çay molası verin.",
        "tips_en": "Take a tea break away from city noise at the 'Rose Bakery' cafe in the small garden greenhouse."
    },
    {
        "name": "Hôtel de la Marine",
        "name_en": "Hotel de la Marine",
        "area": "Place de la Concorde",
        "category": "Tarihi",
        "tags": ["saray", "lüks", "mimari", "tarihi"],
        "distanceFromCenter": 1.5,
        "lat": 48.8669,
        "lng": 2.3228,
        "price": "medium",
        "rating": 4.8,
        "description": "Place de la Concorde'un görkemli silüetini tamamlayan, Fransız saray hayatının lüksünü ve devletin gücünü yansıtan tarihi bina.",
        "description_en": "A historic building that completes the grand silhouette of Place de la Concorde, reflecting the luxury of French court life and state power.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Locataire terasından Place de la Concorde manzarası muhteşemdir.",
        "tips_en": "The view of Place de la Concorde from the Locataire terrace is magnificent."
    },
    {
        "name": "Île aux Cygnes",
        "name_en": "Swan Island",
        "area": "15. Bölge",
        "category": "Manzara",
        "tags": ["ada", "özgürlük heykeli", "yürüyüş", "nehir"],
        "distanceFromCenter": 4.5,
        "lat": 48.8514,
        "lng": 2.2797,
        "price": "free",
        "rating": 4.6,
        "description": "Seine Nehri'nin ortasında yer alan ince uzun yapay ada. Ucunda New York'taki heykelin küçük bir kopyası (Statue of Liberty) bulunur.",
        "description_en": "A long, narrow artificial island in the middle of the Seine. At its tip stands a smaller replica of the Statue of Liberty in New York.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Adanın boydan boya uzanan ağaçlıklı yolu 'Allée des Cygnes', koşanlar ve yürüyüş yapanlar için favori bir noktadır.",
        "tips_en": "The wooded path running the length of the island, 'Allée des Cygnes', is a favorite spot for runners and walkers."
    },
    {
        "name": "Parc Monceau",
        "name_en": "Parc Monceau",
        "area": "8. Bölge",
        "category": "Park",
        "tags": ["park", "romantik", "mimari", "zarif"],
        "distanceFromCenter": 2.5,
        "lat": 48.8796,
        "lng": 2.3089,
        "price": "free",
        "rating": 4.8,
        "description": "Paris'in en zarif parklarından biri. Sahte antik kalıntılar (folies), köprüler ve çocukların oyun oynadığı geniş çimenleriyle ünlüdür.",
        "description_en": "One of Paris' most elegant parks, famous for its mock ancient ruins (folies), bridges, and large lawns where children play.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Parkın etrafındaki görkemli demir kapılar ve malikaneler bölgenin zengin tarihini yansıtır.",
        "tips_en": "The grand iron gates and mansions surrounding the park reflect the area's wealthy history."
    },
    {
        "name": "59 Rivoli",
        "name_en": "59 Rivoli",
        "area": "1. Bölge",
        "category": "Deneyim",
        "tags": ["sanat", "galeri", "alternatif", "atölye"],
        "distanceFromCenter": 0.5,
        "lat": 48.8594,
        "lng": 2.3469,
        "price": "low",
        "rating": 4.6,
        "description": "Eski bir 'squat' (işgal evi) olan bu bina, şimdi 30 sanatçının atölyesini barındıran rengarenk ve alternatif bir sanat merkezi.",
        "description_en": "A former 'squat', this building is now a colorful and alternative art center housing the studios of 30 artists.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Sanatçıları çalışırken görebilir ve onlarla doğrudan sohbet edebilirsiniz.",
        "tips_en": "You can see the artists at work and chat with them directly."
    },
    {
        "name": "Le Comptoir Général",
        "name_en": "Le Comptoir General",
        "area": "Canal Saint-Martin",
        "category": "Bar",
        "tags": ["alternatif", "egzotik", "bar", "kültür"],
        "distanceFromCenter": 2.8,
        "lat": 48.8733,
        "lng": 2.3644,
        "price": "medium",
        "rating": 4.5,
        "description": "Canal Saint-Martin yakınında, egzotik bitkiler ve antikalarla dolu, Afrika kültürü esintili çok ilginç ve popüler bir bar/mekan.",
        "description_en": "An intriguing and popular bar/venue near Canal Saint-Martin, inspired by African culture and filled with exotic plants and antiques.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "İçerideki gizli bahçesi ve retro dekorasyonuyla kendinizi başka bir dünyada hissedeceksiniz.",
        "tips_en": "With its hidden inner garden and retro decor, you'll feel like you've entered another world."
    },
    {
        "name": "Station F",
        "name_en": "Station F",
        "area": "13. Bölge",
        "category": "Deneyim",
        "tags": ["teknoloji", "start-up", "modern", "yemek merkezi"],
        "distanceFromCenter": 3.8,
        "lat": 48.8344,
        "lng": 2.3708,
        "price": "low",
        "rating": 4.6,
        "description": "Dünyanın en büyük start-up kampüsü. Eski bir tren istasyonu deposunun devasa ve modern bir teknoloji merkezine dönüşümü.",
        "description_en": "The world's largest start-up campus. A transformation of a former railway freight station into a massive and modern tech hub.",
        "imageUrl": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800",
        "bestTime": "Öğle veya Akşam",
        "bestTime_en": "Noon or Evening",
        "tips": "İçindeki devasa yemek alanı 'La Felicita' (Big Mamma grubu), Paris'in en havalı yemek noktalarından biridir.",
        "tips_en": "The massive food hall inside, 'La Felicita' (by Big Mamma group), is one of Paris' coolest dining spots."
    },
    {
        "name": "Le Louxor - Palais du Cinéma",
        "name_en": "Le Louxor Cinema",
        "area": "10. Bölge",
        "category": "Tarihi",
        "tags": ["sinema", "mimari", "mısır temalı", "art deco"],
        "distanceFromCenter": 3.2,
        "lat": 48.8833,
        "lng": 2.3503,
        "price": "medium",
        "rating": 4.6,
        "description": "1921'den kalma, Mısır temalı mimarisi ve art deco detaylarıyla Paris'in en ikonik ve en güzel sinemalarından biri.",
        "description_en": "One of Paris' most iconic and beautiful cinemas from 1921, featuring Egyptian-style architecture and Art Deco details.",
        "imageUrl": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "En üst kattaki teras barı, Sacré-Cœur manzarası eşliğinde bir içki içmek için harikadır.",
        "tips_en": "The rooftop terrace bar is a great spot for a drink with a view of Sacré-Cœur."
    },
    {
        "name": "Bibliothèque Richelieu - Salle Ovale",
        "name_en": "Richelieu Library - Oval Room",
        "area": "2. Bölge",
        "category": "Tarihi",
        "tags": ["kütüphane", "mimari", "bilgi", "huzur"],
        "distanceFromCenter": 0.8,
        "lat": 48.8678,
        "lng": 2.3378,
        "price": "free",
        "rating": 4.9,
        "description": "Fransa Ulusal Kütüphanesi'nin yeni restore edilmiş Salle Ovale salonu, nefes kesen mimarisiyle her kitapseverin hayalini süsleyen bir mekan.",
        "description_en": "The newly restored Salle Ovale of the National Library of France is an architectural masterpiece that is a dream for any book lover.",
        "imageUrl": "https://images.unsplash.com/photo-1521587760476-6c12a71048ca?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçeri girmek ücretsizdir, sessizliği koruyarak bu mimari şaheserin tadını çıkarın.",
        "tips_en": "Entrance is free; enjoy this architectural masterpiece while maintaining silence."
    },
    {
        "name": "Musée des Arts et Métiers",
        "name_en": "Museum of Arts and Crafts",
        "area": "3. Bölge",
        "category": "Müze",
        "tags": ["teknoloji", "bilim", "ikonik", "deney"],
        "distanceFromCenter": 1.2,
        "lat": 48.8664,
        "lng": 2.3551,
        "price": "medium",
        "rating": 4.7,
        "description": "Avrupa'nın en eski bilim ve teknoloji müzesi. Foucault Sarkacı'nın orijinal yeridir ve binlerce teknik icadı barındırır.",
        "description_en": "Europe's oldest science and technology museum. The original home of Foucault's Pendulum, housing thousands of technical inventions.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Müzenin yanındaki Arts et Métiers metro durağı, Jules Verne gemisi (steampunk) tarzındaki tasarımıyla görülmeye değerdir.",
        "tips_en": "The Arts et Métiers metro station next to the museum is worth seeing for its steampunk, Jules Verne-inspired design."
    },
    {
        "name": "Ground Control Paris",
        "name_en": "Ground Control Paris",
        "area": "12. Bölge",
        "category": "Deneyim",
        "tags": ["yemek", "etkinlik", "alternatif", "sosyal"],
        "distanceFromCenter": 3.2,
        "lat": 48.8442,
        "lng": 2.3739,
        "price": "low",
        "rating": 4.5,
        "description": "Eski bir demiryolu binasında yer alan çok amaçlı bir yaşam alanı. Yemek tezgahları, barlar, sergiler ve bahçesiyle lokallerin favorisi.",
        "description_en": "A multipurpose lifestyle space in a former railway warehouse. A local favorite with food stalls, bars, exhibitions, and a garden.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Hafta sonu akşam",
        "bestTime_en": "Weekend evening",
        "tips": "Rayların üzerindeki eski uçak ve trenleri görebilir, yaz akşamları dışarıdaki masalarda oturabilirsiniz.",
        "tips_en": "You can see old planes and trains on the tracks and sit at outdoor tables on summer evenings."
    },
    {
        "name": "Place Vendôme",
        "name_en": "Place Vendome",
        "area": "1. Bölge",
        "category": "Tarihi",
        "tags": ["meydan", "mücevher", "lüks", "napolyon"],
        "distanceFromCenter": 1.2,
        "lat": 48.8675,
        "lng": 2.3294,
        "price": "free",
        "rating": 4.7,
        "description": "Paris'in en prestijli meydanı. Dünyaca ünlü mücevher evleri, Ritz Paris oteli ve ortasındaki Napolyon sütunuyla lüksün adresidir.",
        "description_en": "The most prestigious square in Paris, home to world-class jewelry houses, the Ritz Paris, and a central Napoleonic column.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meydandaki vitrinler birer mücevher sergisi gibidir, gece ışıklandırması büyüleyicidir.",
        "tips_en": "The window displays in the square are like jewelry exhibitions, and the night lighting is magical."
    },
    {
        "name": "Place de la Bastille",
        "name_en": "Place de la Bastille",
        "area": "11. Bölge",
        "category": "Tarihi",
        "tags": ["meydan", "devrim", "opera", "tarihi"],
        "distanceFromCenter": 1.8,
        "lat": 48.8533,
        "lng": 2.3700,
        "price": "free",
        "rating": 4.4,
        "description": "Fransız Devrimi'nin başladığı sembolik meydan. Şimdi ise Temmuz Sütunu, modern Operâ Bastille ve canlı gece hayatıyla bilinir.",
        "description_en": "The symbolic square where the French Revolution began. Now known for the July Column, the modern Opéra Bastille, and its lively nightlife.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Meydanın hemen yakınındaki Rue de la Roquette ve Rue de Lappe barlar sokağı lokallerin uğrak yeridir.",
        "tips_en": "The nearby Rue de la Roquette and Rue de Lappe bar streets are popular local haunts."
    },
    {
        "name": "Iles aux Cygnes (Grenelle)",
        "name_en": "Isle of Swans",
        "area": "15. Bölge",
        "category": "Manzara",
        "tags": ["nehir", "yürüyüş", "heykel", "fotoğraf"],
        "distanceFromCenter": 4.2,
        "lat": 48.8504,
        "lng": 2.2797,
        "price": "free",
        "rating": 4.6,
        "description": "Eyfel Kulesi ve Statue of Liberty (Özgürlük Heykeli) kopyasını aynı karede görebileceğiniz nehir ortasındaki huzurlu yapay ada.",
        "description_en": "A peaceful artificial island in the river where you can see the Eiffel Tower and the replica Statue of Liberty in the same frame.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Ağaçlıklı yolda yürüyüş yapıp Eyfel Kulesi'nin farklı bir açısını yakalayın.",
        "tips_en": "Walk along the tree-lined path to capture a different angle of the Eiffel Tower."
    },
    {
        "name": "Pont des Arts",
        "name_en": "Pont des Arts",
        "area": "6. Bölge",
        "category": "Tarihi",
        "tags": ["köprü", "sanat", "nehir", "piknik"],
        "distanceFromCenter": 0.8,
        "lat": 48.8585,
        "lng": 2.3375,
        "price": "free",
        "rating": 4.7,
        "description": "Louvre Müzesi ile Institut de France'ı birbirine bağlayan, bir zamanlar aşıkların kilit asmasıyla ünlü olan Paris'in ilk demir köprüsü.",
        "description_en": "Paris' first iron bridge, connecting the Louvre to the Institut de France and once famous for the 'love locks' hung by couples.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Köprü üzerindeki banklarda oturup Seine Nehri'ni izleyen ressamları ve geçen tekneleri seyretmek tam bir Paris klasiğidir.",
        "tips_en": "Sitting on the bridge benches to watch the riverside painters and passing boats is a classic Paris experience."
    },
    {
        "name": "Pont Marie",
        "name_en": "Pont Marie",
        "area": "Île Saint-Louis",
        "category": "Tarihi",
        "tags": ["köprü", "romantik", "nehir", "efsane"],
        "distanceFromCenter": 0.8,
        "lat": 48.8525,
        "lng": 2.3561,
        "price": "free",
        "rating": 4.5,
        "description": "Île Saint-Louis'i sağ yakaya bağlayan, 'Aşıklar Köprüsü' olarak da bilinen gizemli ve zarif bir Orta Çağ tarzı köprü.",
        "description_en": "A mysterious and elegant medieval-style bridge connecting Île Saint-Louis to the right bank, also known as the 'Lovers' Bridge'.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Efsaneye göre köprünün altından geçerken öpüşen ve bir dilek tutan aşıkların dileği gerçek olur.",
        "tips_en": "Legend has it that lovers who kiss and make a wish while passing under the bridge will have their wish come true."
    },
    {
        "name": "Mémorial de la Shoah",
        "name_en": "Shoah Memorial",
        "area": "Marais",
        "category": "Tarihi",
        "tags": ["history", "yad vashem", "memorial", "marais"],
        "distanceFromCenter": 0.8,
        "lat": 48.8550,
        "lng": 2.3561,
        "price": "free",
        "rating": 4.8,
        "description": "Holokost kurbanlarına adanmış etkileyici bir anıt ve müze. Dışarıdaki 'Adlar Duvarı'nda 76.000 kurbanın adı yazılıdır.",
        "description_en": "A moving memorial and museum dedicated to the Holocaust victims, with a 'Wall of Names' listing 76,000 victims outside.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Sessiz ve saygılı bir ziyaret gerektiren çok duygusal bir yerdir.",
        "tips_en": "A very emotional site that requires a quiet and respectful visit."
    },
    {
        "name": "Passage de l'Ancre",
        "name_en": "Passage de l'Ancre",
        "area": "3. Bölge",
        "category": "Manzara",
        "tags": ["gizli", "sokak", "renkli", "bitki"],
        "distanceFromCenter": 1.0,
        "lat": 48.8637,
        "lng": 2.3537,
        "price": "free",
        "rating": 4.7,
        "description": "Paris'in en eski pasalarından biri olan ve saksılardaki bitkileri, renkli dükkanlarıyla gizli bir bahçeyi andıran huzurlu geçit.",
        "description_en": "One of Paris' oldest passages, resembling a hidden garden with its potted plants and colorful shops; a very peaceful retreat.",
        "imageUrl": "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=600",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçinde şemsiye tamircisi gibi çok eski ve nadir dükkanlara rastlayabilirsiniz.",
        "tips_en": "You can find very old and rare shops inside, such as an umbrella repair shop."
    },
    {
        "name": "Square du Temple-Elie Wiesel",
        "name_en": "Square du Temple",
        "area": "Marais",
        "category": "Park",
        "tags": ["park", "marais", "göl", "lokal"],
        "distanceFromCenter": 1.1,
        "lat": 48.8647,
        "lng": 2.3601,
        "price": "free",
        "rating": 4.6,
        "description": "Marais'nin göbeğinde, içinde küçük bir şelale, gölet ve nadir ağaçları barındıran huzur dolu yerel park.",
        "description_en": "A peaceful local park in the heart of the Marais, featuring a small waterfall, a pond, and rare trees.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Yan taraftaki Marche des Enfants Rouges'tan yemek alıp burada piknik yapanları görebilirsiniz.",
        "tips_en": "You might see people who bought food from the nearby Marche des Enfants Rouges having a picnic here."
    },
    {
        "name": "MK2 Bibliothèque",
        "name_en": "MK2 Bibliotheque",
        "area": "13. Bölge",
        "category": "Deneyim",
        "tags": ["sinema", "modern", "nehir", "kitap"],
        "distanceFromCenter": 4.0,
        "lat": 48.8317,
        "lng": 2.3783,
        "price": "medium",
        "rating": 4.5,
        "description": "BnF kütüphanesinin hemen yanında, nehir kıyısında yer alan modern, şık ve geniş bir sinema ve yaşam kompleksi.",
        "description_en": "A modern, chic, and large cinema and lifestyle complex located by the river next to the BnF library.",
        "imageUrl": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Nehir üzerine demirlemiş teknelerde yer alan diğer MK2 salonlarına da bir göz atın.",
        "tips_en": "Also check out the other MK2 screens located on boats moored along the river."
    }
]

def enrich_paris_batch2():
    filepath = 'assets/cities/paris.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_paris_batch2:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_paris_batch2()
print(f"Paris now has {count} highlights.")
