import json
import os

new_stockholm_batch2 = [
    {
        "name": "Nobel Prize Museum",
        "name_en": "Nobel Prize Museum",
        "area": "Gamla Stan",
        "category": "Müze",
        "tags": ["nobel", "bilim", "tarih", "ilham"],
        "distanceFromCenter": 0.0,
        "lat": 59.3253,
        "lng": 18.0708,
        "price": "medium",
        "rating": 4.5,
        "description": "Nobel Ödülü'ne ve kurucusu Alfred Nobel'e adanmış ilgi çekici bir müze. İnsanlığı değiştiren fikirlerin ve ödül kazananların hikayelerini keşfedebilirsiniz.",
        "description_en": "A museum dedicated to the Nobel Prize and its founder, Alfred Nobel. Explore stories of ideas that changed the world and the winners who conceived them.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze içindeki kafede, sandalyelerin altına bakmayı unutmayın; Nobel kazananlarının imzaları orada bulunabilir.",
        "tips_en": "Don't forget to check under the chairs in the museum cafe; you might find signatures of Nobel laureates."
    },
    {
        "name": "Junibacken (Masal Dünyası)",
        "name_en": "Junibacken",
        "area": "Djurgården",
        "category": "Deneyim",
        "tags": ["çocuk", "masal", "pippi uzunçorap", "eğlence"],
        "distanceFromCenter": 2.2,
        "lat": 59.3283,
        "lng": 18.09,
        "price": "high",
        "rating": 4.7,
        "description": "Astrid Lindgren'in masal dünyasına, özellikle Pippi Uzunçorap'a adanmış harika bir çocuk kültür merkezi. 'Masal Treni' ile büyülü bir yolculuğa çıkabilirsiniz.",
        "description_en": "A children's cultural center dedicated to Astrid Lindgren's stories, especially Pippi Longstocking. Features the magical 'Story Train' ride.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Sabah (aileler için)",
        "bestTime_en": "Morning (for families)",
        "tips": "Hafta sonları çok kalabalık olur, hafta içi ziyaret etmek daha huzurlu bir deneyim sunar.",
        "tips_en": "Can get very crowded on weekends; visiting during the week is more peaceful."
    },
    {
        "name": "Chokladkoppen",
        "name_en": "Chokladkoppen",
        "area": "Gamla Stan",
        "category": "Kafe",
        "tags": ["sıcak çikolata", "pasta", "lgbti dostu", "meydan"],
        "distanceFromCenter": 0.0,
        "lat": 59.3251,
        "lng": 18.0705,
        "price": "medium",
        "rating": 4.6,
        "description": "Stortorget meydanında, dev kasede servis edilen sıcak çikolatasıyla ünlü, çok sıcak ve samimi bir kafe.",
        "description_en": "A cozy cafe on Stortorget square, famous for its giant bowls of hot chocolate and welcoming atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Kış öğleden sonrası",
        "bestTime_en": "Winter afternoon",
        "tips": "Özellikle kış aylarında iç ısıtan atmosferi ve beyaz çikolatalı keki mutlaka denenmeli.",
        "tips_en": "The cozy atmosphere is perfect for winter; try their white chocolate cake."
    },
    {
        "name": "Under Kastanjen",
        "name_en": "Under Kastanjen",
        "area": "Gamla Stan",
        "category": "Kafe",
        "tags": ["fika", "meydan", "gizli", "pasta"],
        "distanceFromCenter": 0.2,
        "lat": 59.3248,
        "lng": 18.0722,
        "price": "medium",
        "rating": 4.7,
        "description": "Dev bir kestane ağacının altındaki Brända Tomten meydanında yer alan, masalsı bir fika noktası. Hem pastanesi hem de yandaki restoranı çok başarılıdır.",
        "description_en": "An idyllic fika spot located on the Brända Tomten square under a massive chestnut tree. Both the bakery and restaurant are excellent.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Güneşli öğleden sonra",
        "bestTime_en": "Sunny afternoon",
        "tips": "Dışarıdaki masalarda oturup meydanın huzurlu atmosferinin tadını çıkarın.",
        "tips_en": "Sit at the outdoor tables to enjoy the square's peaceful atmosphere."
    },
    {
        "name": "Vete-Katten",
        "name_en": "Vete-Katten",
        "area": "Norrmalm",
        "category": "Kafe",
        "tags": ["geleneksel", "fırın", "tarihi", "fika"],
        "distanceFromCenter": 0.2,
        "lat": 59.3339,
        "lng": 18.0617,
        "price": "medium",
        "rating": 4.5,
        "description": "1928'den beri hizmet veren, Stockholm'ün en klasik pastanelerinden biri. Birçok küçük odadan oluşan iç mekanıyla zamanda yolculuk gibi bir fika deneyimi sunar.",
        "description_en": "One of Stockholm's most classic patisseries since 1928, offering an authentic fika experience in its labyrinth of cozy rooms.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Danimarka ve İsveç'in meşhur tarçınlı ve kakuleli çörekleri (bullar) burada en iyi örneklerindendir.",
        "tips_en": "Their cinnamon and cardamom buns (bullar) are among the best in the city."
    },
    {
        "name": "Fabrique (Taş Fırın)",
        "name_en": "Fabrique",
        "area": "Çeşitli Bölgeler",
        "category": "Kafe",
        "tags": ["fırın", "ekşi maya", "bullar", "yerel"],
        "distanceFromCenter": 0.5,
        "lat": 59.333,
        "lng": 18.068,
        "price": "medium",
        "rating": 4.7,
        "description": "Taş fırında pişen ekşi mayalı ekmekleri ve devasa kakuleli çörekleri (kardemummabullar) ile ünlü butik bir fırın zinciri.",
        "description_en": "An artisanal stone-oven bakery famous for its sourdough bread and massive, delicious cardamom buns.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Özellikle Södermalm ve Gamla Stan şubeleri çok karakterli iç mekanlara sahiptir.",
        "tips_en": "The Södermalm and Gamla Stan locations have particularly charming interiors."
    },
    {
        "name": "Hermans (Manzaralı Vejetaryen)",
        "name_en": "Hermans",
        "area": "Södermalm",
        "category": "Restoran",
        "tags": ["vejetaryen", "büfe", "manzara", "bahçe"],
        "distanceFromCenter": 1.5,
        "lat": 59.3175,
        "lng": 18.0872,
        "price": "medium",
        "rating": 4.7,
        "description": "Stockholm'ün en iyi vejetaryen açık büfesi. Sadece yemekleri için değil, bahçesinden sunduğu muhteşem şehir ve deniz manzarası için de mutlaka gidilmeli.",
        "description_en": "One of the best vegetarian buffet restaurants in the city, famous for both its varied food and its stunning garden views over the harbor.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Güneşli öğle veya akşam",
        "bestTime_en": "Sunny lunch or dinner",
        "tips": "Öğrencilere (ve bazen belirli saatlerde) indirim uygulanır, bahçedeki hamaklarda dinlenmeyi unutmayın.",
        "tips_en": "Offers student discounts; don't miss relaxing in the garden hammocks."
    },
    {
        "name": "Tak Stockholm (Rooftop Bar)",
        "name_en": "Tak",
        "area": "Norrmalm",
        "category": "Manzara",
        "tags": ["rooftop", "kokteyl", "iskandinav-japon", "gece hayatı"],
        "distanceFromCenter": 0.3,
        "lat": 59.3308,
        "lng": 18.0658,
        "price": "high",
        "rating": 4.6,
        "description": "Şık bir otelin tepesinde yer alan, İskandinav ve Japon mutfaklarını modern bir şekilde birleştiren restoran ve devasa teras bar. 360 derece şehir manzarası sunar.",
        "description_en": "A sleek rooftop venue combining Nordic and Japanese elements, offering 360-degree views and some of the city's best cocktails.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Akşam (gün batımı)",
        "bestTime_en": "Evening (sunset)",
        "tips": "Hafta sonları akşamları oldukça kalabalık ve 'cool' bir kitleye sahiptir, şık giyinmeniz önerilir.",
        "tips_en": "Expect a trendy crowd on weekends; dressing up is recommended."
    },
    {
        "name": "Urban Deli (Nytorget)",
        "name_en": "Urban Deli",
        "area": "Södermalm / SoFo",
        "category": "Restoran",
        "tags": ["gurme market", "trendy", "deniz ürünü", "yerel"],
        "distanceFromCenter": 1.2,
        "lat": 59.3128,
        "lng": 18.0831,
        "price": "high",
        "rating": 4.5,
        "description": "Södermalm'ın 'hipster' bölgesi SoFo'da yer alan restoran, bar ve gurme market karışımı çok popüler bir mekan.",
        "description_en": "A trendy mix of restaurant, bar, and gourmet market in Södermalm's hip SoFo district. A great place to experience modern Stockholm vibes.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Hafta sonu brunch veya akşam",
        "bestTime_en": "Weekend brunch or evening",
        "tips": "Yemekten sonra yanındaki gurme marketinden yerel peynirler ve İsveç lezzetleri alabilirsiniz.",
        "tips_en": "Pick up local cheeses and Swedish delicacies from the attached market after your meal."
    },
    {
        "name": "Medeltidsmuseet (Orta Çağ Müzesi)",
        "name_en": "The Medieval Museum",
        "area": "Helgeandsholmen",
        "category": "Müze",
        "tags": ["ortaçağ", "yeraltı", "sur", "tarih", "ücretsiz"],
        "distanceFromCenter": 0.2,
        "lat": 59.3283,
        "lng": 18.0706,
        "price": "free",
        "rating": 4.7,
        "description": "Kraliyet Sarayı'nın hemen önündeki yer altında bulunan, Stockholm'ün Orta Çağ surlarının keşfi üzerine kurulmuş etkileyici müze.",
        "description_en": "An underground museum built around the discovery of Stockholm's medieval city wall, showing life in the middle ages.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Giriş tamamen ücretsizdir ve Orta Çağ Stockholm'ünü canlandıran sokak tasarımları çok gerçekçidir.",
        "tips_en": "Entrance is free, and the life-sized recreations of medieval street scenes are very impressive."
    },
    {
        "name": "Hellasgården (Sauna ve Doğa)",
        "name_en": "Hellasgården",
        "area": "Nacka (Şehir yakını)",
        "category": "Deneyim",
        "tags": ["sauna", "yüzme", "doğa", "kış banyosu", "yerel"],
        "distanceFromCenter": 6.0,
        "lat": 59.2897,
        "lng": 18.1583,
        "price": "low",
        "rating": 4.8,
        "description": "Gerçek bir İsveç deneyimi: Şehir merkezine kısa bir mesafede, göl kenarında sauna ve sonrasında gölde yüzme imkanı sunan bir doğa alanı.",
        "description_en": "The quintessential Swedish experience: lakeside saunas followed by a swim (or ice plunge in winter) in the nature reserve nearby.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Hafta sonu sabah veya kışın akşam",
        "bestTime_en": "Weekend morning or winter evening",
        "tips": "Kışın gidiyorsanız göldeki buzun içinde açılan delikte (ice dipping) yüzmek cesaret ister ama unutulmazdır.",
        "tips_en": "In winter, taking an 'ice dip' in the hole cut in the frozen lake is unforgettable."
    },
    {
        "name": "Avicii Experience",
        "name_en": "Avicii Experience",
        "area": "Centrum",
        "category": "Müze",
        "tags": ["müzik", "dj", "modern", "interaktif", "avicii"],
        "distanceFromCenter": 0.5,
        "lat": 59.3344,
        "lng": 18.0722,
        "price": "high",
        "rating": 4.8,
        "description": "Dünyaca ünlü İsveçli DJ Tim 'Avicii' Bergling'in hayatına ve müziğine adanmış duygusal ve interaktif bir müze.",
        "description_en": "An emotional and interactive museum dedicated to the life and music of legendary Swedish DJ Tim 'Avicii' Bergling.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kendi müziğinizi miksleyebileceğiniz ve sanatçının yayınlanmamış eserlerini duyabileceğiniz bölümler bulunur.",
        "tips_en": "Features interactive music-making sections and never-before-heard or seen archives."
    },
    {
        "name": "Tekniska Museet (Teknoloji Müzesi)",
        "name_en": "Museum of Science and Technology",
        "area": "Gärdet",
        "category": "Müze",
        "tags": ["teknoloji", "bilim", "inovasyon", "çocuk dostu"],
        "distanceFromCenter": 3.0,
        "lat": 59.3325,
        "lng": 18.1189,
        "price": "medium",
        "rating": 4.6,
        "description": "Danimarka ve İsveç'in teknolojik dehasını keşfedebileceğiniz, her yaştan ziyaretçi için interaktif deneyimler sunan büyük teknoloji müzesi.",
        "description_en": "An interactive and engaging museum exploring Swedish innovation and engineering, with many hands-on exhibits for all ages.",
        "imageUrl": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yeni açılan 'Wisdome' adındaki devasa ahşap kubbeli sinema salonu mutlaka görülmesi gereken bir mimari harikadır.",
        "tips_en": "Be sure to visit 'Wisdome', a massive new wooden dome offering immersive cinematic experiences."
    },
    {
        "name": "Museum of Far Eastern Antiquities",
        "name_en": "Museum of Far Eastern Antiquities",
        "area": "Skeppsholmen",
        "category": "Müze",
        "tags": ["asya sanatı", "tarih", "arkeoloji", "sakin"],
        "distanceFromCenter": 1.2,
        "lat": 59.3275,
        "lng": 18.0831,
        "price": "low",
        "rating": 4.4,
        "description": "Çin, Japonya ve Kore gibi Uzak Doğu ülkelerinin antik eserlerini barındıran, adanın en sakin ve şık müzelerinden biri.",
        "description_en": "A tranquil museum on Skeppsholmen island showcasing ancient art and archaeological finds from China, Japan, and Korea.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Müze bahçesinden Stockholm kıyılarını izlemek oldukça huzur vericidir, kalabalıktan kaçmak için idealdir.",
        "tips_en": "The museum gardens offer a peaceful escape with lovely views over the water."
    },
    {
        "name": "Paradox Museum Stockholm",
        "name_en": "Paradox Museum",
        "area": "Norrmalm",
        "category": "Deneyim",
        "tags": ["illüzyon", "eğlence", "fotoğraf", "interaktif"],
        "distanceFromCenter": 0.5,
        "lat": 59.3346,
        "lng": 18.0625,
        "price": "medium",
        "rating": 4.6,
        "description": "Bakış açınızı zorlayan 70'den fazla interaktif illüzyon ve fotoğraf noktasıyla dolu, her yaştan ziyaretçi için çok eğlenceli bir müze.",
        "description_en": "A highly interactive and fun destination featuring over 70 paradox-based exhibits that challenge your perspective.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Hafta içi sabahlar",
        "bestTime_en": "Weekday mornings",
        "tips": "Fotoğraf çekmeyi sevenler için cennettir; personelden fotoğraf çekim teknikleri hakkında yardım alabilirsiniz.",
        "tips_en": "A photographer's heaven; don't hesitate to ask staff for help with taking the best shots."
    },
    {
        "name": "Rosendal Palace (Slott)",
        "name_en": "Rosendal Palace",
        "area": "Djurgården",
        "category": "Tarihi",
        "tags": ["saray", "kraliyet", "mimari", "park"],
        "distanceFromCenter": 3.2,
        "lat": 59.3292,
        "lng": 18.1186,
        "price": "medium",
        "rating": 4.5,
        "description": "Djurgården adasında bulunan, Kral XIV. Karl Johan için inşa edilmiş zarif bir yazlık saray. İsveç İmparatorluk stilinin en güzel örneklerinden biridir.",
        "description_en": "An elegant royal summer palace built for King Karl XIV Johan, showcasing the best of Swedish Empire style.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Yaz ayları",
        "bestTime_en": "Summer months",
        "tips": "Sadece yaz aylarında rehberli turlarla içini gezebilirsiniz; o ünlü devasa 'Rosendal Vazosu'nu mutlaka görün.",
        "tips_en": "Tours are only available in summer; don't miss the enormous Rosendal Vase in the park."
    },
    {
        "name": "Vaxholm (Takımadaların Kapısı)",
        "name_en": "Vaxholm",
        "area": "Takımadalar",
        "category": "Deneyim",
        "tags": ["ada", "kale", "tekne", "sahil", "balık"],
        "distanceFromCenter": 20.0,
        "lat": 59.4031,
        "lng": 18.3532,
        "price": "low",
        "rating": 4.7,
        "description": "Stockholm Takımadaları'nın 'başkenti' sayılan şirin sahil kasabası. Tarihi kalesi, butik dükkanları ve ahşap evleriyle tam bir yaz rüyasıdır.",
        "description_en": "The 'capital' of the Stockholm archipelago, an idyllic seaside town known for its fortress, wooden houses, and cozy atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Yaz günleri",
        "bestTime_en": "Summer days",
        "tips": "Vaxholms Hembygdsgårds Café'nin devasa açık büfe tatlı sofrası (fika) tüm bölgede efsanedir.",
        "tips_en": "The legendary cake buffet at Vaxholms Hembygdsgårds Café is a must for any fika lover."
    },
    {
        "name": "SkyView (Globen Panorama)",
        "name_en": "SkyView",
        "area": "Johanneshov",
        "category": "Manzara",
        "tags": ["manzara", "gondol", "arena", "küre"],
        "distanceFromCenter": 4.5,
        "lat": 59.2935,
        "lng": 18.0821,
        "price": "high",
        "rating": 4.4,
        "description": "Dünyanın en büyük küresel binası olan Ericsson Globe'un dış cephesinde, cam bir gondolla 130 metre yüksekliğe çıkıp şehri izleyebilirsiniz.",
        "description_en": "Ride glass gondolas along the outside of the world's largest spherical building, the Ericsson Globe, for spectacular city views.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Açık hava güneşli gün",
        "bestTime_en": "Clear sunny day",
        "tips": "Gondol yolculuğu yaklaşık 20 dakika sürer; her 10 dakikada bir yeni bir gondol kalkar.",
        "tips_en": "The ride takes about 20 minutes; gondolas depart every 10 minutes."
    },
    {
        "name": "Prins Eugens Waldemarsudde",
        "name_en": "Prins Eugens Waldemarsudde",
        "area": "Djurgården",
        "category": "Müze",
        "tags": ["sanat", "malikane", "bahçe", "deniz manzara"],
        "distanceFromCenter": 3.0,
        "lat": 59.3206,
        "lng": 18.1158,
        "price": "medium",
        "rating": 4.8,
        "description": "Prens Eugen'in eski evi olan bu muhteşem sanat müzesi, hem prensin kendi eserlerini hem de geniş koleksiyonunu harika deniz manzaralı bir bahçede sunar.",
        "description_en": "The former home of Prince Eugen, now one of Sweden's most beautiful art museums, featuring his work and collections in a stunning garden setting.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Güneşli öğleden sonra",
        "bestTime_en": "Sunny afternoon",
        "tips": "Müzenin çiçek bahçeleri İsveç'in en iyilerinden biri olarak kabul edilir; çiçeklerin açtığı bahar-yaz aylarında kaçırılmamalıdır.",
        "tips_en": "The museum's flower gardens are renowned; don't visit without walking through them in spring or summer."
    },
    {
        "name": "Katarinahissen (Katarina Asansörü)",
        "name_en": "Katarina Elevator",
        "area": "Södermalm",
        "category": "Manzara",
        "tags": ["manzara", "tarihi", "asansör", "ücretsiz"],
        "distanceFromCenter": 0.5,
        "lat": 59.3192,
        "lng": 18.0737,
        "price": "free",
        "rating": 4.4,
        "description": "Slussen bölgesinde yer alan, Gamla Stan ve Stockholm limanına yukarıdan bakan tarihi çelik asansör ve yürüyüş platformu.",
        "description_en": "A historic iron structure in the Slussen area, providing a high-level viewing platform with iconic vistas over Gamla Stan and the water.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Akşam (şehir ışıkları)",
        "bestTime_en": "Evening (city lights)",
        "tips": "Asansör bazen bakımda olabilir ancak platforma arka sokaklardaki merdivenlerden yürüyerek de ulaşabilirsiniz.",
        "tips_en": "If the elevator is closed, you can still reach the platform via the walkways from the higher streets of Södermalm."
    }
]

def enrich_stockholm_batch2():
    filepath = 'assets/cities/stockholm.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_stockholm_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_stockholm_batch2()
print(f"Stockholm now has {count} highlights.")
