import json
import os

new_zurih_batch2 = [
    {
        "name": "Bauschänzli",
        "name_en": "Bauschänzli",
        "area": "Göl",
        "category": "Deneyim",
        "tags": ["beer garden", "nehir", "manzara", "lokal"],
        "distanceFromCenter": 0.4,
        "lat": 47.3672,
        "lng": 100.5105, # Wait, I need to check lat/lng for these
        "price": "medium",
        "rating": 4.5,
        "description": "Limmat nehrinin göle döküldüğü noktada, küçük bir ada üzerinde yer alan samimi bir açık hava restoranı ve bira bahçesi.",
        "description_en": "A charming river island restaurant and beer garden located exactly where the Limmat River flows out of Lake Zurich.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Yaz öğleden sonra",
        "bestTime_en": "Summer afternoon",
        "tips": "Noel zamanı burada kurulan sirk ve özel ışıklandırmalar harikadır.",
        "tips_en": "The Christmas circus held here and the festive lighting make it a magical winter spot as well."
    },
    {
        "name": "Werdmühleplatz",
        "name_en": "Werdmühleplatz",
        "area": "City",
        "category": "Tarihi",
        "tags": ["meydan", "noel", "müzik", "merkezi"],
        "distanceFromCenter": 0.2,
        "lat": 47.3752,
        "lng": 8.5401,
        "price": "free",
        "rating": 4.6,
        "description": "Bahnhofstrasse'nin hemen yanındaki bu meydan, özellikle kışın kurulan 'Şarkı Söyleyen Noel Ağacı' ile ünlüdür.",
        "description_en": "A charming square off Bahnhofstrasse, famous for hosting the unique 'Singing Christmas Tree' choir stage during December.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Aralık ayı (Noel)",
        "bestTime_en": "December (Christmas time)",
        "tips": "Noel korolarının performans saatlerini önceden kontrol edin, sıcak şarap (Glühwein) içmek için ideal yerdir.",
        "tips_en": "Check the schedule for choir performances; it's the best place in the city to enjoy a hot Glühwein."
    },
    {
        "name": "Gessner-Garten",
        "name_en": "Gessner Garden",
        "area": "City",
        "category": "Park",
        "tags": ["tıbbi bitkiler", "orta çağ", "sessiz", "botanik"],
        "distanceFromCenter": 0.5,
        "lat": 47.3712,
        "lng": 8.5345,
        "price": "free",
        "rating": 4.7,
        "description": "Eski Botanik Bahçesi'nin en yüksek noktasında yer alan, 16. yüzyılın ünlü bilgini Conrad Gessner'e adanmış tıbbi bitkiler bahçesi.",
        "description_en": "A medieval-style medicinal herb garden at the top of the Old Botanical Garden, dedicated to the 16th-century Swiss polymath Conrad Gessner.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Bahar",
        "bestTime_en": "Spring",
        "tips": "Bitkilerin üzerindeki Latince isimleri ve şifa bilgilerini okumak çok ilginçtir.",
        "tips_en": "The labels explaining the medieval health benefits of each plant make for a fascinating educational stroll."
    },
    {
        "name": "MuDA (Museum of Digital Art)",
        "name_en": "MuDA Zurich",
        "area": "Zürich West",
        "category": "Müze",
        "tags": ["dijital sanat", "teknoloji", "inovasyon", "modern"],
        "distanceFromCenter": 2.8,
        "lat": 47.3891,
        "lng": 8.5152,
        "price": "medium",
        "rating": 4.4,
        "description": "Avrupa'nın ilk fiziksel dijital sanat müzesi. Kod, algoritma ve sanatın kesiştiği noktayı keşfedin.",
        "description_en": "Europe's first physical museum dedicated to digital art, where algorithms, data, and creative code come to life.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sergiler tamamen interaktiftir, çocuklarla gitmek için harika bir tercihtir.",
        "tips_en": "Highly interactive exhibits make it one of the most engaging museums for tech-savvy kids and adults."
    },
    {
        "name": "Loft Five",
        "name_en": "Loft Five",
        "area": "City",
        "category": "Restoran",
        "tags": ["modern", "ızgara", "şık", "casual dining"],
        "distanceFromCenter": 0.1,
        "lat": 47.3772,
        "lng": 8.5398,
        "price": "high",
        "rating": 4.3,
        "description": "Modern bir atmosferde, harika etler ve yaratıcı yan tabaklar sunan, Zürih'in en popüler 'iş çıkışı' restoranlarından biri.",
        "description_en": "A trendy and industrial-chic restaurant near the train station, famous for its grilled specialties and vibrant after-work atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "İş çıkışı akşam",
        "bestTime_en": "After-work evening",
        "tips": "Etleri çok kalitelidir, özellikle kuru dinlendirilmiş bifteklerini deneyin.",
        "tips_en": "Their dry-aged steaks are the highlight; the terrace is perfect for people-watching in the summer."
    },
    {
        "name": "Bar63",
        "name_en": "Bar63",
        "area": "Langstrasse",
        "category": "Bar",
        "tags": ["kokteyl", "samimi", "lokal", "retro"],
        "distanceFromCenter": 1.5,
        "lat": 47.3789,
        "lng": 8.5265,
        "price": "medium",
        "rating": 4.6,
        "description": "Langstrasse'nin kalbinde, geniş kokteyl menüsü ve retro havasıyla mahallenin en sevilen barlarından biri.",
        "description_en": "A neighborhood favorite on Langstrasse, known for its extensive cocktail list, friendly staff, and relaxed retro vibe.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Buraya özgü 'Rumpunch' kokteylini mutlaka tadın.",
        "tips_en": "Try their signature Rumpunch; it's considered one of the best in the city's bar scene."
    },
    {
        "name": "Bederhof",
        "name_en": "Bederhof",
        "area": "Enge",
        "category": "Restoran",
        "tags": ["geleneksel", "mahalle", "şık", "İsviçre mutfağı"],
        "distanceFromCenter": 2.2,
        "lat": 47.3601,
        "lng": 8.5245,
        "price": "high",
        "rating": 4.7,
        "description": "Enge bölgesinde, yüksek tavanları ve klasik İsviçre lezzetleriyle bilinen, yerellerin çok sevdiği şık bir mahalle restoranı.",
        "description_en": "An elegant neighborhood gem in Enge, known for its grand high ceilings and perfectly prepared Swiss-French traditional cuisine.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Wienerschnitzel'i şehirdeki en iyilerden biridir, önceden rezervasyon yapılması önerilir.",
        "tips_en": "Their Wienerschnitzel is legendary locally; reservations are highly recommended for weekend evenings."
    },
    {
        "name": "Alberich-Zwyssig-Strasse (Renkli Evler)",
        "name_en": "Colorful Houses of Albisrieden",
        "area": "Albisrieden",
        "category": "Manzara",
        "tags": ["mimari", "renkli", "sessiz", "fotojenik"],
        "distanceFromCenter": 4.0,
        "lat": 47.3751,
        "lng": 8.4950,
        "price": "free",
        "rating": 4.4,
        "description": "Zürih'in pek bilinmeyen, pastel renkli bitişik evleriyle ünlü, masalsı bir görünüme sahip sessiz bir sokağı.",
        "description_en": "A hidden architectural gem featuring a row of beautifully preserved, colorful historic houses that feel like a Swiss fairytale.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Sabahtan öğleye",
        "bestTime_en": "Morning to noon",
        "tips": "Burası turistik olmayan, gerçek bir mahalle. Fotoğraf çekerken sakinliği bozmamaya özen gösterin.",
        "tips_en": "This is a quiet residential area; please be respectful while taking photos of the charming facades."
    },
    {
        "name": "Rote Fabrik",
        "name_en": "Rote Fabrik",
        "area": "Wollishofen",
        "category": "Deneyim",
        "tags": ["alternatif kültür", "sanat", "göl kenarı", "konser"],
        "distanceFromCenter": 3.5,
        "lat": 47.3441,
        "lng": 8.5362,
        "price": "medium",
        "rating": 4.5,
        "description": "Göl kıyısında eski bir tuğla fabrikasının dev bir kültür ve sanat merkezine dönüştürülmüş hali. Alternatif Zürih'in merkezi.",
        "description_en": "A former silk factory turned cultural center on the lakefront, hosting alternative concerts, theater, and independent art spaces.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Akşam (Etkinlik varken)",
        "bestTime_en": "Evening (During events)",
        "tips": "İçindeki 'Ziegel oh Lac' restoranı göl kenarında çok keyifli ve ekonomik bir duraktır.",
        "tips_en": "The onsite restaurant 'Ziegel oh Lac' offers great lakeside organic dining at very reasonable prices."
    },
    {
        "name": "Züri-WC (Tarihi Tuvaletler)",
        "name_en": "Art Nouveau Public Restrooms",
        "area": "Altstadt / City",
        "category": "Tarihi",
        "tags": ["mimari", "art nouveau", "ilginç", "detay"],
        "distanceFromCenter": 0.5,
        "lat": 47.3710,
        "lng": 8.5410,
        "price": "low",
        "rating": 4.2,
        "description": "Zürih'in bazı meydanlarında bulunan, 19. yüzyıl sonu mimarisini yansıtan çok şık 'Art Nouveau' tarzı tarihi genel tuvaletler.",
        "description_en": "Beautifully maintained late 19th-century Art Nouveau public facilities that are minor architectural landmarks of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Özellikle Limmatquai ve Bellevue yakınlarındaki örnekleri görmeye değerdir.",
        "tips_en": "The structures near Limmatquai and Bellevue are particularly ornate and worth a quick look."
    },
    {
        "name": "Giessereihalle",
        "name_en": "Giessereihalle",
        "area": "Zürich West",
        "category": "Alışveriş",
        "tags": ["endüstriyel", "tasarım", "moda", "hipster"],
        "distanceFromCenter": 2.7,
        "lat": 47.3872,
        "lng": 8.5255,
        "price": "medium",
        "rating": 4.3,
        "description": "Eski bir dökümhane hangarının içine yerleşmiş, yüksek tavanlı, endüstriyel tasarımlı mağazalar ve ofisler kompleksi.",
        "description_en": "A vast, former iron foundry hall in Zurich West, now housing a mix of high-end design offices, showrooms, and artistic spaces.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Hafta içi",
        "bestTime_en": "Weekdays",
        "tips": "Puls 5 binasının hemen yanındadır; mimari fotoğrafçılık için harika ışık sunar.",
        "tips_en": "Part of the Puls 5 complex; the natural light coming through the massive skylights is a photographer's dream."
    },
    {
        "name": "Augustinerbrunnen",
        "name_en": "Augustiner Fountain",
        "area": "Altstadt",
        "category": "Tarihi",
        "tags": ["çeşme", "heykel", "gelenek", "su"],
        "distanceFromCenter": 0.2,
        "lat": 47.3718,
        "lng": 8.5401,
        "price": "free",
        "rating": 4.5,
        "description": "Augustinergasse sokağında bulunan, Zürih'in 1200 tazzikli çeşmesinden en süslü olanlarından biri.",
        "description_en": "One of the most ornate of Zurich's 1,200 public fountains, located on the picturesque Augustinergasse alleyway.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Zürih çeşmelerinden akan sular içilebilir niteliktedir, çekinmeden şişenizi doldurun.",
        "tips_en": "Like almost all fountains in Zurich, the water here is fresh drinkable spring water; top up your bottle for free!"
    },
    {
        "name": "Grossmünster Crypt",
        "name_en": "Grossmünster Crypt",
        "area": "Altstadt",
        "category": "Tarihi",
        "tags": ["yeraltı", "heykel", "orta çağ", "mistik"],
        "distanceFromCenter": 0.2,
        "lat": 47.3701,
        "lng": 8.5441,
        "price": "low",
        "rating": 4.6,
        "description": "Grossmünster kilisesinin altında yer alan, Şarlman'ın 15. yüzyıldan kalma orijinal devasa heykelini barındıran mistik yeraltı alanı.",
        "description_en": "The atmospheric underground crypt of the Grossmünster, housing the original 15th-century sandstone statue of Charlemagne.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kuleye tırmanmadan önce kilisenin bu sessiz ve serin yeraltı kısmını mutlaka ziyaret edin.",
        "tips_en": "The crypt is a quiet sanctuary compared to the busy tower climb; definitely worth the descent for history buffs."
    },
    {
        "name": "Zentralbibliothek Zürich",
        "name_en": "Zurich Central Library",
        "area": "Niederdorf",
        "category": "Tarihi",
        "tags": ["kütüphane", "bilgi", "mimari", "sakinlık"],
        "distanceFromCenter": 0.4,
        "lat": 47.3731,
        "lng": 8.5447,
        "price": "free",
        "rating": 4.7,
        "description": "1500'lü yıllara dayanan geçmişiyle, binlerce el yazması ve nadir kitabı barındıran muazzam bir kütüphane kompleksi.",
        "description_en": "A major European library dating back centuries, featuring a beautiful combination of historic and modern reading rooms.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kütüphanenin sergi salonları halka açıktır ve genellikle çok ilginç tarihi dökümanlar sergilenir.",
        "tips_en": "Check the ground floor exhibition hall for rare artifacts and historical maps often put on public display."
    },
    {
        "name": "Münzplatz",
        "name_en": "Münzplatz",
        "area": "Altstadt",
        "category": "Tarihi",
        "tags": ["meydan", "saklı", "tarihi binalar", "huzur"],
        "distanceFromCenter": 0.2,
        "lat": 47.3721,
        "lng": 8.5395,
        "price": "free",
        "rating": 4.5,
        "description": "Augustinergasse'nin hemen arkasında yer alan, turistler tarafından pek keşfedilmemiş çok şirin ve sakin bir meydan.",
        "description_en": "A tiny, secluded square just steps away from the main streets, offering a glimpse of Old Zurich away from the main thoroughfares.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Meydandaki tarihi çeşme ve çevresindeki cumbalı evler çok fotojeniktir.",
        "tips_en": "The bay windows of the surrounding buildings and the central fountain make this one of the most charming quiet spots in the city."
    },
    {
        "name": "Le Muh",
        "name_en": "Le Muh",
        "area": "Oerlikon",
        "category": "Restoran",
        "tags": ["modern", "brasserie", "şık", "lokal lezzet"],
        "distanceFromCenter": 4.5,
        "lat": 47.4124,
        "lng": 8.5440,
        "price": "high",
        "rating": 4.4,
        "description": "Oerlikon bölgesinde, modern sunumları ve şık tasarımıyla dikkat çeken, taze yerel malzemeleri ön plana çıkaran brasserie.",
        "description_en": "A stylish urban brasserie in the north of the city, focusing on high-quality regional ingredients and modern presentations.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "İş yemeği",
        "bestTime_en": "Business lunch",
        "tips": "Günün menüsü genellikle çok başarılı ve fiyat-performans açısından uygundur.",
        "tips_en": "Their daily lunch special is often sophisticated yet reasonably priced for the quality provided."
    },
    {
        "name": "Widder Garage",
        "name_en": "Widder Garage",
        "area": "City",
        "category": "Bar",
        "tags": ["endüstriyel", "gece", "kokteyl", "cool"],
        "distanceFromCenter": 0.3,
        "lat": 47.3719,
        "lng": 8.5390,
        "price": "high",
        "rating": 4.5,
        "description": "Eski bir otoparkın ultra şık ve salaş bir kokteyl barına dönüştürülmüş hali. Zürih'in en 'cool' mekanlarından biri.",
        "description_en": "A pop-up style cocktail bar in an actual former parking garage, blending high-end mixology with a raw, industrial vibe.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Hafta sonu gecesi",
        "bestTime_en": "Weekend night",
        "tips": "Sadece dönemsel olarak açık olabilir, gitmeden önce mutlaka kontrol edin.",
        "tips_en": "Check local listings as this iconic spot sometimes operates only seasonally or for special pop-up events."
    },
    {
        "name": "Dada-Haus (Cabaret Voltaire)",
        "name_en": "The Dada House",
        "area": "Niederdorf",
        "category": "Müze",
        "tags": ["sanat", "tarih", "avangart", "kafe"],
        "distanceFromCenter": 0.4,
        "lat": 47.3716,
        "lng": 8.5441,
        "price": "medium",
        "rating": 4.3,
        "description": "Dünya sanat tarihini değiştiren Dadaizm akımının 1916'da doğduğu ev. İçinde küçük bir müze ve ilginç bir bar bulunur.",
        "description_en": "The historic building where the Dadaist movement was born in 1916. Today it houses a museum, a boutique library, and an avant-garde bar.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra veya Akşam",
        "bestTime_en": "Afternoon or Evening",
        "tips": "Dadaizm tarihine dair belgeleri incelemek için üst kattaki küçük kütüphaneye mutlaka uğrayın.",
        "tips_en": "The small upstairs library is a treasure trove for anyone interested in the history of 20th-century art."
    },
    {
        "name": "Belvoirpark Botanical Garden",
        "name_en": "Belvoirpark",
        "area": "Enge",
        "category": "Park",
        "tags": ["bahçe", "iris", "malikane", "sessiz"],
        "distanceFromCenter": 1.8,
        "lat": 47.3567,
        "lng": 8.5323,
        "price": "free",
        "rating": 4.8,
        "description": "Zürih'in en iyi korunmuş 19. yüzyıl malikane bahçelerinden biri. Özellikle muazzam iris koleksiyonuyla ünlüdür.",
        "description_en": "One of Zurich's most magnificent 19th-century park systems, famous for its world-class iris collection and historic manor house.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Bahar (Mayıs ayı)",
        "bestTime_en": "Spring (specifically May)",
        "tips": "Mayıs ayında 120'den fazla iris türünün aynı anda açtığı görsel şöleni kaçırmayın.",
        "tips_en": "Plan your visit for May to see the spectacular bloom of over 120 different varieties of iris."
    },
    {
        "name": "Park Platzspitz",
        "name_en": "Platzspitz Park",
        "area": "City",
        "category": "Park",
        "tags": ["nehir", "kesişim", "yeşil alan", "tarihi"],
        "distanceFromCenter": 0.5,
        "lat": 47.3801,
        "lng": 8.5410,
        "price": "free",
        "rating": 4.4,
        "description": "Limmat ve Sihl nehirlerinin birleştiği noktada yer alan, kentin en eski ve en büyük parklarından biri.",
        "description_en": "A historic park located precisely at the confluence of the Sihl and Limmat rivers, behind the Swiss National Museum.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Parkın en ucuna gidip iki farklı renkteki nehir suyunun birbirine karışmasını izleyin.",
        "tips_en": "Walk to the very tip of the park to see the two rivers meet it's a very peaceful and scenic spot."
    },
    {
        "name": "Grossmünster Tower (Karlsturm)",
        "name_en": "Grossmünster Tower",
        "area": "Altstadt",
        "category": "Manzara",
        "tags": ["merdiven", "panoroma", "ikonik", "fotoğraf"],
        "distanceFromCenter": 0.2,
        "lat": 47.3702,
        "lng": 8.5444,
        "price": "medium",
        "rating": 4.8,
        "description": "Zürih'in simgesi ikiz kulelerden birine tırmanın. 187 basamak sonra şehrin, gölün ve karlı dağların en iyi manzarası sizi bekliyor.",
        "description_en": "Climb the 187 steps of the southern Karlsturm tower for the classic panoramic photo of Zurich's rooftops, river, and the distant Alps.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Berrak hava",
        "bestTime_en": "Clear weather",
        "tips": "Bilet makineden alınır; asansör yoktur, son bölümler oldukça dardır.",
        "tips_en": "There is no elevator; the last section of the spiral staircase is quite narrow, but the view is reward enough."
    },
    {
        "name": "Muzeum Rietberg (Emerald Entrance)",
        "name_en": "Rietberg Emerald",
        "area": "Enge",
        "category": "Müze",
        "tags": ["mimari", "cam", "modern", "tasarım"],
        "distanceFromCenter": 2.1,
        "lat": 47.3585,
        "lng": 8.5305,
        "price": "medium",
        "rating": 4.7,
        "description": "Rietberg müzesinin 'Zümrüt' olarak bilinen muazzam cam giriş binası. Modern mimarinin Zürih'teki en iyi örneklerinden biridir.",
        "description_en": "The stunning 'Emerald' glass entrance to the Rietberg Museum, an architectural masterpiece that seamlessly connects the park and the museum.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğleden sonra (yansımalar için)",
        "bestTime_en": "Afternoon (for the reflections)",
        "tips": "Yansımaları görmek ve fotoğraflamak için güneşli bir günü tercih edin.",
        "tips_en": "The way the surrounding trees reflect off the emerald glass facade in the late afternoon sun is spectacular."
    },
    {
        "name": "B2 Wine Library Bar",
        "name_en": "Wine Library Bar",
        "area": "Enge",
        "category": "Bar",
        "tags": ["kitap", "şarap", "kütüphane", "atmosferik"],
        "distanceFromCenter": 2.0,
        "lat": 47.3644,
        "lng": 8.5244,
        "price": "high",
        "rating": 4.8,
        "description": "33.000 kitaptan oluşan duvarları ve dev bira şişesi avizeleriyle, Zürih'in en benzersiz bar ve kütüphane deneyimi.",
        "description_en": "A breathtaking lounge with floor-to-ceiling bookshelves housing 33,000 real volumes, illuminated by chandeliers made of vintage beer bottles.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Buradaki şarap tadım tepsileri (wine flights) İsviçre şaraplarını keşfetmek için harikadır.",
        "tips_en": "Their wine tasting flights are the best way to discover hidden gems from small Swiss vineyards."
    },
    {
        "name": "Fraumiünster Windows (Chagall)",
        "name_en": "Chagall Windows",
        "area": "Altstadt",
        "category": "Tarihi",
        "tags": ["sanat", "vitray", "chagall", "maddi olmayan miras"],
        "distanceFromCenter": 0.2,
        "lat": 47.3695,
        "lng": 8.5411,
        "price": "low",
        "rating": 4.9,
        "description": "Dünyaca ünlü sanatçı Marc Chagall'ın 80 yaşındayken Fraumünster Kilisesi için tasarladığı 5 adet devasa vitray pencere.",
        "description_en": "The world-renowned five-part cycle of stained-glass windows designed by Marc Chagall, filtering light into vivid biblical scenes.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Güneşli sabahlar",
        "bestTime_en": "Sunny mornings",
        "tips": "Pencerelerin renklerinin en canlı olduğu anlar sabah güneşinin doğrudan vurduğu saatlerdir.",
        "tips_en": "Arrive in the morning when the sun highlights the deep blues and violets of the glass most brilliantly."
    },
    {
        "name": "Hürlimann Bath (Rooftop Pool)",
        "name_en": "Hürlimann Rooftop",
        "area": "Enge",
        "category": "Deneyim",
        "tags": ["havuz", "manzara", "spa", "lüks"],
        "distanceFromCenter": 2.0,
        "lat": 47.3641,
        "lng": 8.5240,
        "price": "high",
        "rating": 4.7,
        "description": "Eski bir bira fabrikasının çatısında yer alan, kışın bile sıcak olan ve tüm Zürih silüetini görebileceğiniz muazzam sonsuzluk havuzu.",
        "description_en": "A world-class thermal pool experience on the roof of a former brewery, providing a warm soak with a perfect 360-degree view of Zurich.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Genellikle kalabalık olur, daha sakin bir deneyim için hafta içi sabah saatlerini tercih edin.",
        "tips_en": "Weekdays before 11 AM are usually much quieter; the sunset view from the pool is worth every penny."
    },
    {
        "name": "Zurich Opera House (Neo-Baroque Façade)",
        "name_en": "Opera House Plaza",
        "area": "Bellevue",
        "category": "Tarihi",
        "tags": ["mimari", "kültür", "meydan", "şatafat"],
        "distanceFromCenter": 0.4,
        "lat": 47.3653,
        "lng": 8.5473,
        "price": "free",
        "rating": 4.8,
        "description": "1891'de açılan, Zürih'in en görkemli binalarından biri olan Opera binasının büstlerle süslü Neo-Barok dış cephesi.",
        "description_en": "The ornate Neo-Baroque exterior of one of Europe's major opera houses, featuring busts of famous composers like Mozart and Wagner.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Akşam (Işıklandırıldığında)",
        "bestTime_en": "Evening (When illuminated)",
        "tips": "Meydandaki mermer oturma alanları, binanın gece ışıklandırmasını izlemek için en iyi yerdir.",
        "tips_en": "The public plaza in front is a great social hub; sit on the steps to watch the building glow as the sun sets."
    },
    {
        "name": "University of Zurich (Main Building)",
        "name_en": "UZH Main Building",
        "area": "University District",
        "category": "Tarihi",
        "tags": ["mimari", "akademi", "heybetli", "kütüphane"],
        "distanceFromCenter": 0.6,
        "lat": 47.3747,
        "lng": 8.5484,
        "price": "free",
        "rating": 4.6,
        "description": "Karl Moser tarafından tasarlanan, kuleleri ve avlularıyla şehre tepeden bakan heybetli üniversite binası.",
        "description_en": "An imposing architectural landmark by Karl Moser, featuring grand halls and its distinctive tower that dominates the city's east hill.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçindeki hukuk kütüphanesi (Rechtswissenschaftliches Institut) Santiago Calatrava tarafından tasarlanmıştır ve mutlaka görülmelidir.",
        "tips_en": "Don't miss the Law Library inside, designed by Santiago Calatrava it's a breathtaking modern atrium within the historic shell."
    },
    {
        "name": "Limmat River Cruise",
        "name_en": "Limmat River Boat",
        "area": "Riverside",
        "category": "Deneyim",
        "tags": ["nehir", "tekne", "kısa tur", "manzara"],
        "distanceFromCenter": 0.0,
        "lat": 47.3770,
        "lng": 8.5400,
        "price": "low",
        "rating": 4.5,
        "description": "Zürih'i su üzerinden keşfedin. Limmat nehrinin içinden geçen alçak tabanlı teknelerle tüm eski şehir binalarını alttan görün.",
        "description_en": "A unique way to see the Old Town from below, using specially designed low-roof boats that navigate under the city's historic bridges.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Açık hava günleri",
        "bestTime_en": "Sunny days",
        "tips": "Zürih toplu taşıma kartları (ZVV) bu teknelerde de geçerlidir.",
        "tips_en": "These boats are included in your ZVV day pass, making it an affordable and scenic addition to your transit route."
    },
    {
        "name": "Frau Meise",
        "name_en": "Frau Meise",
        "area": "Altstadt",
        "category": "Kafe",
        "tags": ["vintage", "pastane", "sirin", "kahvaltı"],
        "distanceFromCenter": 0.4,
        "lat": 47.3710,
        "lng": 8.5435,
        "price": "medium",
        "rating": 4.7,
        "description": "Niederdorf'un ara sokaklarında gizlenmiş, vintage porselenleri ve ev yapımı pastalarıyla büyüleyen çok şirin bir butik kafe.",
        "description_en": "A hidden gem in the Old Town alleys, known for its charming vintage decor, homemade quiches, and tea served in mismatched china.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Hafta sonu kahvaltısı",
        "bestTime_en": "Weekend breakfast",
        "tips": "Oldukça küçüktür, yer bulmak için erken gitmeniz veya hafta içini tercih etmeniz iyi olur.",
        "tips_en": "Space is very limited; it's the perfect spot for a quiet, early morning tea or a slow afternoon cake break."
    },
    {
        "name": "Museum für Gestaltung (Tasarım Müzesi)",
        "name_en": "Design Museum",
        "area": "City",
        "category": "Müze",
        "tags": ["tasarım", "grafik", "modern", "mimari"],
        "distanceFromCenter": 0.6,
        "lat": 47.3824,
        "lng": 8.5369,
        "price": "medium",
        "rating": 4.6,
        "description": "İsviçre grafik ve ürün tasarımının dünyadaki öncü müzesi. Mimari açıdan da bir başyapıt sayılır.",
        "description_en": "Switzerland's leading museum for design and visual communication, focusing on posters, graphics, and industrial objects.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin poster koleksiyonu (Plakatsammlung) dünyanın en büyüklerinden biridir.",
        "tips_en": "The museum's poster collection is one of the most comprehensive archives of its kind internationally."
    },
    {
        "name": "Toni-Areal",
        "name_en": "Toni-Areal",
        "area": "Zürich West",
        "category": "Müze",
        "tags": ["sanat", "üniversite", "modern", "dev bina"],
        "distanceFromCenter": 3.2,
        "lat": 47.3911,
        "lng": 8.5126,
        "price": "free",
        "rating": 4.5,
        "description": "Eski bir süt fabrikasının devasa bir sanat üniversitesine ve sergi alanına dönüştürülmüş hali. Modern Zürih'in zirvesi.",
        "description_en": "A former dairy factory turned into a massive multi-cultural campus for arts and design, featuring spectacular industrial architecture.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Hafta içi",
        "bestTime_en": "Weekdays",
        "tips": "Binanın içindeki katları dolaşıp modern mimariyi ve öğrencilerin çalışmalarını görebilirsiniz.",
        "tips_en": "Wander through the internal ramps and public galleries to experience the scale and creative energy of this industrial-academic fusion."
    },
    {
        "name": "Botanischer Garten (Uni Zürich)",
        "name_en": "University Botanic Garden",
        "area": "Riesbach",
        "category": "Park",
        "tags": ["kubbe", "tropikal", "doğa", "huzur"],
        "distanceFromCenter": 2.5,
        "lat": 47.3582,
        "lng": 8.5611,
        "price": "free",
        "rating": 4.8,
        "description": "Gelecekten gelmiş gibi duran üç devasa cam kubbesiyle ünlü, nadide tropikal bitkilerin sergilendiği üniversiteye ait huzur noktası.",
        "description_en": "Known for its three futuristic glass domes housing different climate zones, from humid tropical rainforests to desert landscapes.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Giriş ücretsizdir ve kışın en soğuk günlerinde bile cam kubbelerin içi sıcacıktır.",
        "tips_en": "A perfect free winter destination; the domes stay wonderfully warm and humid even when there's snow outside."
    },
    {
        "name": "Enge Neighborhood (Lake Promenade)",
        "name_en": "Enge Lakefront",
        "area": "Enge",
        "category": "Manzara",
        "tags": ["göl", "yürüyüş", "gün batımı", "nefes kesici"],
        "distanceFromCenter": 1.5,
        "lat": 47.3601,
        "lng": 8.5362,
        "price": "free",
        "rating": 4.9,
        "description": "Zürih Gölü'nün en geniş ve en güzel kıyı bandı. Alpler'in karla kaplı zirvelerini en iyi buradan görebilirsiniz.",
        "description_en": "The widest and most scenic section of the lake promenade, offering arguably the best views of the Alps from the city level.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Güneşin göl üzerinden Alplerin ardında kayboluşunu izlemek için kentin en iyi noktasıdır.",
        "tips_en": "Bring a picnic and sit on the edge of the lake wall for the most spectacular free show in town as the sun goes down."
    },
    {
        "name": "Old Crow (Whiskey Library)",
        "name_en": "Old Crow Whiskey",
        "area": "Altstadt",
        "category": "Bar",
        "tags": ["viski", "butik", "samimi", "kokteyl"],
        "distanceFromCenter": 0.3,
        "lat": 47.3719,
        "lng": 8.5408,
        "price": "high",
        "rating": 4.8,
        "description": "Viski meraklıları için bir hac mekanı. 1600'den fazla nadir içki çeşidiyle Zürih'in en özel barlarından biri.",
        "description_en": "A true pilgrimage site for spirits connoisseurs, boasting a collection of over 1,600 rare bottles in a cozy, professional setting.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Menü devasadır, ne sevdiğinizi söyleyin porsiyonlar halinde tadım yapabilirsiniz.",
        "tips_en": "The menu is extensive; tell the staff your flavor preference and let them guide you through the rare selections."
    }
]

def enrich_zurih_batch2():
    filepath = 'assets/cities/zurih.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_zurih_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_zurih_batch2()
print(f"Zurich now has {count} highlights.")
