import json
import os

# Data for Sevilla Enrichment
new_highlights = [
    {
        "name": "Museo de Artes y Costumbres Populares",
        "name_en": "Museum of Arts and Popular Customs",
        "area": "María Luisa",
        "category": "Müze",
        "tags": ["kültür", "gelenek", "mimari"],
        "distanceFromCenter": 1.2,
        "lat": 37.372032,
        "lng": -5.987795,
        "price": "low",
        "rating": 4.6,
        "description": "Sevilla'nın geleneksel yaşamını, kıyafetlerini ve el sanatlarını sergileyen muhteşem bir müze. Maria Luisa Parkı'ndaki Mudéjar Köşkü'nde yer alıyor.",
        "description_en": "A beautiful museum showcasing traditional Sevillian life, costumes, and crafts, located in the Mudéjar Pavilion of Maria Luisa Park.",
        "imageUrl": "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Binanın dış mimarisi de en az içindekiler kadar etkileyici.",
        "tips_en": "The exterior architecture of the building is as impressive as the collection inside."
    },
    {
        "name": "Pabellón de la Navegación",
        "name_en": "Navigation Pavilion",
        "area": "Cartuja",
        "category": "Müze",
        "tags": ["denizcilik", "tarih", "modern"],
        "distanceFromCenter": 1.8,
        "lat": 37.394506,
        "lng": -6.007893,
        "price": "medium",
        "rating": 4.5,
        "description": "Sevilla'nın denizcilik tarihini interaktif sergilerle anlatan modern müze. Expo '92 için inşa edilmiş ve nehir kenarında harika bir konuma sahip.",
        "description_en": "A modern museum telling Seville's maritime history through interactive exhibits, built for Expo '92 and set in a great riverside location.",
        "imageUrl": "https://images.unsplash.com/photo-1550522433-281b37494cc1?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Schindler Kulesi'ne çıkıp nehir manzarasını seyredin.",
        "tips_en": "Climb the Schindler Tower for great views of the river."
    },
    {
        "name": "Castillo de San Jorge",
        "name_en": "Castle of San Jorge",
        "area": "Triana",
        "category": "Müze",
        "tags": ["engizisyon", "tarih", "yeraltı"],
        "distanceFromCenter": 1.0,
        "lat": 37.385677,
        "lng": -6.003112,
        "price": "free",
        "rating": 4.4,
        "description": "İspanyol Engizisyonu'nun eski karargahı olan bu kale kalıntıları, şimdi hoşgörüsüzlük tarihini anlatan etkileyici bir yer altı müzesi.",
        "description_en": "The ruins of the former headquarters of the Spanish Inquisition, now an evocative underground museum reflecting on the history of intolerance.",
        "imageUrl": "https://images.unsplash.com/photo-1610444583713-397a66699ec7?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Triana Pazarı'nın hemen altında yer alıyor. Giriş ücretsiz.",
        "tips_en": "Located right beneath the Triana Market. Entrance is free."
    },
    {
        "name": "Centro Cerámica Triana",
        "name_en": "Triana Ceramics Center",
        "area": "Triana",
        "category": "Müze",
        "tags": ["seramik", "sanat", "gelenek"],
        "distanceFromCenter": 1.1,
        "lat": 37.385655,
        "lng": -6.004613,
        "price": "low",
        "rating": 4.5,
        "description": "Triana'nın ünlü çini ve seramik geleneğini eski bir fabrikada yaşatan müze. Geleneksel fırınları ve teknikleri görebilirsiniz.",
        "description_en": "A museum in a former factory showcasing Triana's famous tile and ceramic tradition. You can see traditional kilns and techniques.",
        "imageUrl": "https://images.unsplash.com/photo-1598911515286-6ea432657801?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Triana sokaklarını gezerken bu müzeye uğramak seramiklerin hikayesini anlamanızı sağlar.",
        "tips_en": "Visiting this museum while exploring Triana helps you understand the story behind the neighborhood's ceramics."
    },
    {
        "name": "Palacio de San Telmo",
        "name_en": "San Telmo Palace",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["saray", "barok", "hükümet"],
        "distanceFromCenter": 0.5,
        "lat": 37.380852,
        "lng": -5.993192,
        "price": "medium",
        "rating": 4.6,
        "description": "Sevilla Barok mimarisinin en görkemli örneklerinden biri. Şimdi Endülüs Hükümet Merkezi olarak kullanılan sarayın girişi muhteşem taş işçiliğine sahip.",
        "description_en": "One of the most magnificent examples of Seville Baroque architecture. Now the seat of the Andalusian Government, it features a stunning portal.",
        "imageUrl": "https://images.unsplash.com/photo-1598449419142-2d1033069315?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Rezervasyonlu turlarla içini gezmek mümkün, ancak dışarıdan görmek bile yeterli.",
        "tips_en": "Interior tours are possible with reservation, but even viewing it from the outside is plenty."
    },
    {
        "name": "Antigua Fábrica de Tabacos",
        "name_en": "Old Tobacco Factory",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["üniversite", "tarih", "opera"],
        "distanceFromCenter": 0.4,
        "lat": 37.381226,
        "lng": -5.990623,
        "price": "free",
        "rating": 4.7,
        "description": "Bir zamanlar Avrupa'nın en büyük tütün fabrikası olan bu devasa bina, şimdi Sevilla Üniversitesi'ne ev sahipliği yapıyor. Carmen operasının geçtiği yer.",
        "description_en": "Once the largest tobacco factory in Europe, this massive building now houses the University of Seville and is the setting for the opera Carmen.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Avlularını ve koridorlarını ücretsiz olarak gezebilirsiniz; kendinizi bir film setinde gibi hissedeceksiniz.",
        "tips_en": "You can wander through its courtyards and corridors for free; it feels like being on a movie set."
    },
    {
        "name": "Convento de Santa Paula",
        "name_en": "Santa Paula Convent",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["manastır", "reçel", "huzur"],
        "distanceFromCenter": 0.8,
        "lat": 37.396286,
        "lng": -5.985489,
        "price": "low",
        "rating": 4.6,
        "description": "500 yıllık bu manastır, muhteşem avlusu ve rahibelerin yaptığı ünlü reçelleriyle biliniyor. Hem müze hem de ruhani bir sığınak.",
        "description_en": "This 500-year-old convent is known for its beautiful courtyard and the famous jams made by the nuns. Both a museum and a spiritual sanctuary.",
        "imageUrl": "https://images.unsplash.com/photo-1605333161099-6f9172281862?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Manastırın kendi üretimi olan portakal reçellerinden (mermelada) mutlaka alın.",
        "tips_en": "Be sure to buy some of the orange marmalade made right there in the convent."
    },
    {
        "name": "Torre de los Perdigones",
        "name_en": "Perdigones Tower",
        "area": "Macarena",
        "category": "Manzara",
        "tags": ["kule", "camera obscura", "manzara"],
        "distanceFromCenter": 1.5,
        "lat": 37.403564,
        "lng": -5.992371,
        "price": "low",
        "rating": 4.5,
        "description": "Eski bir kurşun fabrikası kulesi. En tepesinde bulunan Camera Obscura ile şehri canlı ve gerçek zamanlı olarak kuş bakışı izleyebilirsiniz.",
        "description_en": "An old lead factory tower. At the top, a Camera Obscura lets you view a live, real-time bird's-eye perspective of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1549463599-299f2a08da0e?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Camera Obscura seansları sınırlı kapasitededir, geldiğinizde hemen isim yazdırın.",
        "tips_en": "Camera Obscura sessions have limited capacity, so sign up as soon as you arrive."
    },
    {
        "name": "Az-Zait",
        "name_en": "Az-Zait",
        "area": "San Lorenzo",
        "category": "Restoran",
        "tags": ["gastronomi", "gurme", "michelin"],
        "distanceFromCenter": 1.1,
        "lat": 37.3971,
        "lng": -5.9965,
        "price": "high",
        "rating": 4.8,
        "description": "Plaza de San Lorenzo'da yer alan ve Michelin rehberinde bulunan şık restoran. Geleneksel Endülüs mutfağına modern ve sanatsal bir yorum getiriyor.",
        "description_en": "An elegant restaurant in Plaza de San Lorenzo featured in the Michelin guide, offering a modern and artistic take on traditional Andalusian cuisine.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Tadım menüsü (Menu degustación) harika bir deneyim sunuyor. Rezervasyon şart.",
        "tips_en": "The tasting menu offers a fantastic experience. Booking is essential."
    },
    {
        "name": "Cañabota",
        "name_en": "Cañabota",
        "area": "Centro",
        "category": "Restoran",
        "tags": ["deniz ürünleri", "taze", "gurme"],
        "distanceFromCenter": 0.6,
        "lat": 37.3934,
        "lng": -5.9936,
        "price": "high",
        "rating": 4.7,
        "description": "Sevilla'nın en iyi deniz ürünlerini sunan restoranı. Balık pazarını andıran tezgahları ve açık mutfağı ile hem görsel hem lezzetsel bir şölen sunuyor.",
        "description_en": "Seville's premier seafood restaurant. With its market-style counter and open kitchen, it offers both a visual and culinary feast.",
        "imageUrl": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Barda oturup balıkların nasıl hazırlandığını izleyebilirsiniz. Izgara ahtapotu efsane.",
        "tips_en": "Sit at the bar to watch the fish being prepared. The grilled octopus is legendary."
    },
    {
        "name": "El Pintón",
        "name_en": "El Pinton",
        "area": "Centro",
        "category": "Restoran",
        "tags": ["modern tapas", "şık", "tasarım"],
        "distanceFromCenter": 0.3,
        "lat": 37.3875,
        "lng": -5.9934,
        "price": "medium",
        "rating": 4.6,
        "description": "Geleneksel bir Sevilla avlusunda modern tasarımı ve yenilikçi tapasları birleştiren mekan. Hem göze hem damağa hitap ediyor.",
        "description_en": "A venue combining modern design and innovative tapas in a traditional Sevillian courtyard, appealing to both the eyes and the palate.",
        "imageUrl": "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "İç mekandaki avlu tasarımı harika fotoğraf kareleri sunuyor. Risotto tapasını deneyin.",
        "tips_en": "The interior courtyard design offers great photo ops. Try the risotto tapas."
    },
    {
        "name": "Vega 10",
        "name_en": "Vega 10",
        "area": "Triana",
        "category": "Restoran",
        "tags": ["tapas", "lokal", "triana"],
        "distanceFromCenter": 1.2,
        "lat": 37.3822,
        "lng": -6.0025,
        "price": "medium",
        "rating": 4.6,
        "description": "Triana'nın kalbinde yer alan, modern dokunuşlu geleneksel tapaslar sunan samimi bir restoran. Yerel halkın favorilerinden.",
        "description_en": "An intimate restaurant in the heart of Triana serving traditional tapas with modern touches, a favorite among locals.",
        "imageUrl": "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Ördek konfit ve ev yapımı tatlıları mutlaka deneyin.",
        "tips_en": "The duck confit and homemade desserts are a must-try."
    },
    {
        "name": "Virgin Coffee",
        "name_en": "Virgin Coffee",
        "area": "Centro",
        "category": "Kafe",
        "tags": ["kahve", "nitelikli kahve", "küçük"],
        "distanceFromCenter": 0.5,
        "lat": 37.3942,
        "lng": -5.9928,
        "price": "low",
        "rating": 4.8,
        "description": "Sevilla'nın nitelikli kahve akımının öncüsü. Küçük ama çok kaliteli kahveler sunan bu dükkan, gerçek kahve tutkunları için bir durak noktası.",
        "description_en": "A pioneer of the specialty coffee movement in Seville. This tiny shop serves high-quality coffee and is a must-visit for coffee enthusiasts.",
        "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Mekan çok küçük, kahvenizi alıp Metropol Parasol'da yürüyüş yapabilirsiniz.",
        "tips_en": "The place is tiny, so grab your coffee and take a walk around Metropol Parasol."
    },
    {
        "name": "Torch Coffee Roasters",
        "name_en": "Torch Coffee Roasters",
        "area": "Arenal",
        "category": "Kafe",
        "tags": ["kahve", "modern", "nehir"],
        "distanceFromCenter": 0.6,
        "lat": 37.381886,
        "lng": -5.995265,
        "price": "low",
        "rating": 4.7,
        "description": "Nehir kenarında modern bir atmosfere sahip geniş bir kahveci. Kendi kavurdukları çekirdeklerle hazırladıkları kahveler ve lezzetli kahvaltı seçenekleri var.",
        "description_en": "A spacious, modern coffee shop by the river with beans roasted in-house and delicious breakfast options.",
        "imageUrl": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Avokadolu tostları ve filtre kahveleri harika. Çalışmak için de uygun bir ortamı var.",
        "tips_en": "Their avocado toast and filter coffee are great. It also has a good atmosphere for working."
    },
    {
        "name": "Bar Garlochí",
        "name_en": "Bar Garlochi",
        "area": "Centro",
        "category": "Bar",
        "tags": ["dini", "kitsch", "deneyim"],
        "distanceFromCenter": 0.7,
        "lat": 37.3915,
        "lng": -5.9898,
        "price": "medium",
        "rating": 4.6,
        "description": "Sevilla'nın en sıra dışı barlarından biri. Kutsal hafta (Semana Santa) temalı dekorasyonu, tütsü kokusu ve özgün kokteylleriyle gerçek bir deneyim sunuyor.",
        "description_en": "One of Seville's most unusual bars. With its Holy Week themed decor, incense aroma, and original cocktails, it offers a truly unique experience.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Meşhur 'Sangre de Cristo' (Mesih'in Kanı) kokteylini mutlaka deneyin.",
        "tips_en": "Be sure to try their famous 'Sangre de Cristo' (Blood of Christ) cocktail."
    },
    {
        "name": "Bar Alfalfa",
        "name_en": "Bar Alfalfa",
        "area": "Centro",
        "category": "Bar",
        "tags": ["tapas", "lokal", "şarap"],
        "distanceFromCenter": 0.4,
        "lat": 37.3905,
        "lng": -5.9902,
        "price": "low",
        "rating": 4.5,
        "description": "Küçük, samimi ve her zaman dolu bir mahalle barı. Harika bruschettaları ve İspanyol şarapları ile tam bir Sevilla klasiği.",
        "description_en": "A small, intimate, and always crowded neighborhood bar. A Seville classic with great bruschettas and Spanish wines.",
        "imageUrl": "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "Boş yer bulmak zor olabilir ama tezgah başında ayakta durup ortamın tadını çıkarmak da bir o kadar keyifli.",
        "tips_en": "Finding a seat can be hard, but standing at the counter and soaking in the atmosphere is just as enjoyable."
    },
    {
        "name": "Casa Morales",
        "name_en": "Casa Morales",
        "area": "Arenal",
        "category": "Bar",
        "tags": ["tarihi", "şarap", "tapas"],
        "distanceFromCenter": 0.3,
        "lat": 37.386574,
        "lng": -5.994662,
        "price": "low",
        "rating": 4.6,
        "description": "1850'den beri hizmet veren tarihi şarap evi. Duvarlardaki devasa şarap küpleri ve geleneksel tapasları ile zamanda yolculuğa çıkarıyor.",
        "description_en": "A historic wine house serving since 1850. With its massive clay wine jars on the walls and traditional tapas, it feels like a journey back in time.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Montaditos (küçük sandviçler) ve yerel şaraplarını mutlaka deneyin. İkinci oda (küplerin olduğu oda) daha otantiktir.",
        "tips_en": "Be sure to try their montaditos (small sandwiches) and local wines. The second room with the jars is more authentic."
    },
    {
        "name": "Las Teresas",
        "name_en": "Las Teresas",
        "area": "Santa Cruz",
        "category": "Bar",
        "tags": ["jamón", "tapas", "geleneksel"],
        "distanceFromCenter": 0.2,
        "lat": 37.3858,
        "lng": -5.9908,
        "price": "medium",
        "rating": 4.7,
        "description": "Santa Cruz'un en eski barlarından biri. Tavandan sarkan jamónları ve eski okul atmosferiyle gerçek bir Sevilla deneyimi sunuyor.",
        "description_en": "One of Santa Cruz's oldest bars. Offering an old-school atmosphere with hams hanging from the ceiling, it's an authentic Seville experience.",
        "imageUrl": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
        "bestTime": "Öğleden sonra veya akşam",
        "bestTime_en": "Afternoon or evening",
        "tips": "Jamón Ibérico de Bellota denemek için en iyi yerlerden biri. Yanında bir kadeh Fino şarabı söyleyin.",
        "tips_en": "One of the best places to try Jamón Ibérico de Bellota. Order it with a glass of Fino wine."
    },
    {
        "name": "Basílica de Jesús del Gran Poder",
        "name_en": "Gran Poder Basilica",
        "area": "San Lorenzo",
        "category": "Tarihi",
        "tags": ["dini", "heykel", "gelenek"],
        "distanceFromCenter": 1.1,
        "lat": 37.3973,
        "lng": -5.9968,
        "price": "free",
        "rating": 4.8,
        "description": "Sevilla'nın en çok saygı duyulan İsa heykelinin (El Gran Poder) bulunduğu kilise. Yerel halkın inancını ve kültürel dokusunu anlamak için önemli bir nokta.",
        "description_en": "The church housing Seville's most revered statue of Christ (El Gran Poder). An important spot for understanding local devotion and cultural heritage.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kilise sessiz ve huzurludur, yerel halk ibadet ederken saygılı olun.",
        "tips_en": "The church is quiet and peaceful; please be respectful while locals are praying."
    },
    {
        "name": "Convento de Santa Inés",
        "name_en": "Santa Inés Convent",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["manastır", "tatlı", "efsane"],
        "distanceFromCenter": 0.6,
        "lat": 37.3922,
        "lng": -5.9905,
        "price": "low",
        "rating": 4.5,
        "description": "Dona Maria Coronel'in efsanesine ev sahipliği yapan tarihi manastır. Rahibeler tarafından satılan 'bollitos' tatlıları çok meşhurdur.",
        "description_en": "A historic convent home to the legend of Dona Maria Coronel. Their 'bollitos' sweets sold by the nuns are very famous.",
        "imageUrl": "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Tatlı almak için zile basın ve 'Ave Maria Purissima' diyerek selam verin.",
        "tips_en": "Ring the bell to buy sweets and greet them by saying 'Ave Maria Purissima'."
    },
    {
        "name": "Jardines de Murillo",
        "name_en": "Murillo Gardens",
        "area": "Santa Cruz",
        "category": "Park",
        "tags": ["bahçe", "yürüyüş", "tarih"],
        "distanceFromCenter": 0.3,
        "lat": 37.3845,
        "lng": -5.9865,
        "price": "free",
        "rating": 4.6,
        "description": "Santa Cruz'un kenarında, devasa fikus ağaçları ve seramik döşeli banklarıyla huzurlu bir bahçe. Ünlü ressam Murillo'nun adını taşıyor.",
        "description_en": "A peaceful garden on the edge of Santa Cruz with giant ficus trees and tile-clad benches, named after the famous painter Murillo.",
        "imageUrl": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Alcázar çıkışında buraya uğrayıp dev ağaçların gölgesinde dinlenin.",
        "tips_en": "Stop by here after leaving the Alcázar to rest in the shade of the giant trees."
    },
    {
        "name": "Calle Sierpes",
        "name_en": "Sierpes Street",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["alışveriş", "cadde", "tarihi"],
        "distanceFromCenter": 0.2,
        "lat": 37.3912,
        "lng": -5.9942,
        "price": "low",
        "rating": 4.4,
        "description": "Sevilla'nın en ünlü ve tarihi alışveriş caddesi. Geleneksel yelpaze dükkanlarından (abánicos) modern mağazalara kadar her şeyi bulabilirsiniz.",
        "description_en": "Seville's most famous and historic shopping street. You can find everything from traditional fan shops to modern stores.",
        "imageUrl": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Yazın güneşten korunmak için cadde üzerine gerilen devasa gölgelikler (toldos) çok karakteristik bir manzara sunar.",
        "tips_en": "The giant canopies (toldos) stretched over the street in summer to shade it provide a very characteristic view."
    },
    {
        "name": "Papelería Ferrer",
        "name_en": "Ferrer Stationery",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["kırtasiye", "tarihi", "dükkan"],
        "distanceFromCenter": 0.3,
        "lat": 37.3915,
        "lng": -5.9938,
        "price": "low",
        "rating": 4.7,
        "description": "1856'da kurulan ve İspanya'nın en eski kırtasiyesi olan bu dükkan, antika mobilyaları ve özel kalemleri ile bir müze gibi.",
        "description_en": "Founded in 1856 and the oldest stationery shop in Spain, this store is like a museum with its antique furniture and specialty pens.",
        "imageUrl": "https://images.unsplash.com/photo-1544816153-12ad5d714304?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Özel tasarlanmış mühürlerini ve kaliteli kağıt ürünlerini inceleyin.",
        "tips_en": "Check out their custom-designed seals and high-quality paper products."
    },
    {
        "name": "Mercado de la Encarnación",
        "name_en": "Encarnación Market",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["taze", "pazar", "gurme"],
        "distanceFromCenter": 0.5,
        "lat": 37.3933,
        "lng": -5.9918,
        "price": "low",
        "rating": 4.4,
        "description": "Metropol Parasol'un hemen altında yer alan modern pazar yeri. Taze sebze, meyve ve deniz ürünlerinin yanı sıra küçük tapas durakları da var.",
        "description_en": "A modern marketplace located right under the Metropol Parasol, featuring fresh produce and seafood along with small tapas stalls.",
        "imageUrl": "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Yerel peynir ve zeytinlerden taze tadım yapabilirsiniz.",
        "tips_en": "You can sample fresh local cheeses and olives."
    },
    {
        "name": "Calle Regina",
        "name_en": "Regina Street",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["bağımsız", "butik", "hipster"],
        "distanceFromCenter": 0.6,
        "lat": 37.3945,
        "lng": -5.9925,
        "price": "low",
        "rating": 4.5,
        "description": "Metropol Parasol'un arkasında yer alan, bağımsız butikleri, vintage mağazaları ve küçük kafeleriyle Sevilla'nın daha alternatif yüzünü gösteren cadde.",
        "description_en": "Located behind Metropol Parasol, this street showcases the more alternative side of Seville with its independent boutiques, vintage shops, and small cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Yerel tasarımcıların ürünlerini bulmak için en iyi yerlerden biri.",
        "tips_en": "One of the best places to find products from local designers."
    }
]

# Filler descriptions to fix
filler_descriptions_fix = {
    "Real Alcázar": {
        "description": "UNESCO Listesi'ndeki bu kraliyet sarayı, Mudejar mimarisinin dünyadaki en iyi örneğidir. Game of Thrones'un Dorne sahnelerinin çekildiği yer olarak da tanınır.",
        "description_en": "This UNESCO-listed royal palace is the best example of Mudejar architecture in the world. It’s also famous as the filming location for Dorne in Game of Thrones."
    },
    "Catedral & Giralda": {
        "description": "Dünyanın en büyük Gotik katedrali ve eskiden cami olan çan kulesi Giralda. Kristof Kolomb'un mezarı burada bulunur.",
        "description_en": "The world's largest Gothic cathedral and its former minaret bell tower, the Giralda. It houses the tomb of Christopher Columbus."
    },
    "Plaza de España": {
        "description": "İspanya'nın her ilini temsil eden çini panolarıyla süslü devasa meydan. Sandal kiralayabilir veya mimarinin tadını çıkarabilirsiniz.",
        "description_en": "A massive square decorated with tiled alcoves representing every province of Spain. You can rent a boat or just enjoy the architecture."
    },
    "Triana": {
        "description": "Flamenkonun kalbi olan denizci mahallesi. Seramikleri, nehir kenarındaki barları ve otantik atmosferiyle bilinir.",
        "description_en": "The traditional sailors' district and the heart of flamenco. Known for its ceramics, riverside bars, and authentic atmosphere."
    },
    "Flamenko Gösterisi": {
        "description": "Endülüs'ün ruhu olan flamenko dansını canlı izleyebileceğiniz tablaolar. Tutku, ritim ve duygunun harmanı.",
        "description_en": "Tablaos where you can witness the soul of Andalusia: live flamenco dancing. A blend of passion, rhythm, and emotion."
    },
    "Barrio Santa Cruz": {
        "description": "Eski Yahudi mahallesi olan bu dar sokaklar labirenti, Sevilla'nın en fotojenik ve romantik kısmıdır.",
        "description_en": "This labyrinth of narrow streets, the former Jewish quarter, is the most photogenic and romantic part of Seville."
    },
    "Metropol Parasol (Las Setas)": {
        "description": "Dünyanın en büyük ahşap yapısı. Terasından Sevilla'nın 360 derecelik muhteşem manzarasını izleyebilirsiniz.",
        "description_en": "The world's largest wooden structure. Its rooftop walkway offers a stunning 360-degree view of Seville."
    },
    "Maria Luisa Park": {
        "description": "Sevilla'nın ana parkı. Egzotik bitkiler, çeşmeler ve Plaza de España'yı içinde barındıran yeşil vaha.",
        "description_en": "Seville's main public park. A green oasis containing exotic plants, fountains, and the Plaza de España."
    },
    "Mercado de Triana": {
        "description": "Eski bir kale kalıntıları üzerine kurulu, taze ürünler ve tapas duraklarıyla dolu otantik mahalle pazarı.",
        "description_en": "An authentic neighborhood market built over the ruins of an old castle, full of fresh produce and tapas stalls."
    },
    "Isla de la Cartuja": {
        "description": "92 Expo alanı. Şimdi sanat müzeleri, tematik parklar ve teknoloji merkezlerine ev sahipliği yapan yer.",
        "description_en": "The site of Expo '92, now home to art museums, theme parks, and technology centers."
    }
}

def enrich_city(city_file):
    filepath = os.path.join('assets/cities', city_file)
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 1. Update existing fillers
    for highlight in data.get('highlights', []):
        if highlight['name'] in filler_descriptions_fix:
            fix = filler_descriptions_fix[highlight['name']]
            highlight['description'] = fix['description']
            highlight['description_en'] = fix['description_en']

    # 2. Add new highlights
    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_highlights:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

new_count = enrich_city('sevilla.json')
print(f"Sevilla now has {new_count} highlights.")
