import json
import os

new_stockholm_batch3 = [
    {
        "name": "Operakällaren",
        "name_en": "Operakällaren",
        "area": "Norrmalm",
        "category": "Restoran",
        "tags": ["fine dining", "kraliyet", "tarihi", "lüks"],
        "distanceFromCenter": 0.5,
        "lat": 59.3300,
        "lng": 18.0710,
        "price": "high",
        "rating": 4.7,
        "description": "1787'den beri hizmet veren, Kraliyet Opera Binası'nın içinde yer alan İsveç'in en görkemli ve tarihi restoranlarından biri.",
        "description_en": "One of Sweden's most legendary and historic restaurants, located inside the Royal Opera House since 1787.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Özellikle Noel dönemindeki 'Julbord' (Noel açık büfesi) tüm dünyada ünlüdür; aylar öncesinden rezervasyon gerekir.",
        "tips_en": "Their Christmas 'Julbord' is world-famous; books months in advance."
    },
    {
        "name": "Lilla Ego",
        "name_en": "Lilla Ego",
        "area": "Vasastan",
        "category": "Restoran",
        "tags": ["bistro", "gurme", "lokal", "popüler"],
        "distanceFromCenter": 1.5,
        "lat": 59.3400,
        "lng": 18.0400,
        "price": "high",
        "rating": 4.8,
        "description": "İsveç'in 'Yılın Şefi' ödüllü şefleri tarafından kurulan, mütevazı görünümlü ama tabakları sanat eseri olan devasa popülerlikte bir bistro.",
        "description_en": "A wildly popular bistro in Vasastan run by award-winning chefs, focusing on incredible food in a laid-back atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Rezervasyon yaptırmak neredeyse imkansız gibidir; bar kısmında oturmak için kapı açılmadan bekleyebilirsiniz.",
        "tips_en": "Reservations are hard to get; try arriving early for a spot at the bar."
    },
    {
        "name": "Sturehof",
        "name_en": "Sturehof",
        "area": "Östermalm",
        "category": "Restoran",
        "tags": ["deniz ürünü", "klasik", "brasserie", "popüler"],
        "distanceFromCenter": 0.5,
        "lat": 59.3350,
        "lng": 18.0730,
        "price": "high",
        "rating": 4.5,
        "description": "Stureplan meydanında, Stockholm'ün 'gör ve görül' mekanı. Taze deniz ürünleri ve İsveç klasikleri için en iyi adreslerden biridir.",
        "description_en": "A legendary brasserie on Stureplan, the heart of Stockholm's social scene. Excellent for fresh seafood and people-watching.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Karides sanviçi (Räksmörgås) buranın en ünlü tabağıdır.",
        "tips_en": "Their shrimp sandwich (Räksmörgås) is an absolute classic."
    },
    {
        "name": "Riche",
        "name_en": "Riche",
        "area": "Östermalm",
        "category": "Restoran",
        "tags": ["klasik", "bar", "sanat", "popüler"],
        "distanceFromCenter": 0.6,
        "lat": 59.3330,
        "lng": 18.0760,
        "price": "high",
        "rating": 4.4,
        "description": "Stockholm'ün sosyal hayatının kalbinde, Paris brasserie stiliyle İsveç modernliğini birleştiren ikonik bir mekan.",
        "description_en": "An iconic meeting place combining Parisian brasserie vibes with Swedish modernity in the heart of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam yemeği veya gece",
        "bestTime_en": "Dinner or late night",
        "tips": "Wallenbergare (geleneksel dana eti yemeği) denemek için en iyi yerlerden biridir.",
        "tips_en": "One of the best places to try Wallenbergare, a classic Swedish veal dish."
    },
    {
        "name": "Hantverket",
        "name_en": "Hantverket",
        "area": "Östermalm",
        "category": "Restoran",
        "tags": ["modern", "yaratıcı", "iskandinav", "sosyal"],
        "distanceFromCenter": 0.8,
        "lat": 59.3360,
        "lng": 18.0770,
        "price": "high",
        "rating": 4.7,
        "description": "İsveçce 'Zanaat' anlamına gelen, yaratıcı küçük tabaklar sunan ve şık tasarımıyla dikkat çeken bir restoran.",
        "description_en": "Meaning 'The Craft' in Swedish, this restaurant offers creative small plates and a stunningly designed interior.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Peynir dolgulu çıtır soğanlı krakerleri (Hasselback potatoes versiyonu) mutlaka denenmeli.",
        "tips_en": "Their unique Hasselback potato-inspired snacks are a must-try."
    },
    {
        "name": "Drop Coffee",
        "name_en": "Drop Coffee",
        "area": "Södermalm",
        "category": "Kafe",
        "tags": ["3. dalga kahve", "roastery", "odüllü", "lokal"],
        "distanceFromCenter": 1.2,
        "lat": 59.3170,
        "lng": 18.0620,
        "price": "medium",
        "rating": 4.7,
        "description": "Stockholm'ün ödüllü 3. dalga kahvecisi. Södermalm'da kahve severlerin hac noktası sayılır.",
        "description_en": "An award-winning specialty coffee roaster in Södermalm, a must-visit for any serious coffee lover.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Filtre kahvelerini ve kendi kavurdukları çekirdekleri deneyin.",
        "tips_en": "Try their pour-over filter coffees and take home some of their roasted beans."
    },
    {
        "name": "Johan & Nyström",
        "name_en": "Johan & Nyström",
        "area": "Södermalm",
        "category": "Kafe",
        "tags": ["kahve", "konsept mağaza", "fika", "popüler"],
        "distanceFromCenter": 1.0,
        "lat": 59.3180,
        "lng": 18.0650,
        "price": "medium",
        "rating": 4.6,
        "description": "İsveç'in kahve devrimini başlatan öncü markalardan. Mariatorget'teki kafesi oldukça şık ve geniş bir kahve menüsü sunar.",
        "description_en": "A pioneer of the Swedish coffee revolution, offering a wide range of specialty teas and coffees in a stylish setting.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra fika",
        "bestTime_en": "Afternoon fika",
        "tips": "Kahve tadım atölyelerine denk gelirseniz kaçırmayın.",
        "tips_en": "Keep an eye out for their coffee tasting workshops."
    },
    {
        "name": "Snickarbacken 7",
        "name_en": "Snickarbacken 7",
        "area": "Östermalm",
        "category": "Kafe",
        "tags": ["konsept dükkan", "sanat galeri", "gizli", "tasarım"],
        "distanceFromCenter": 0.3,
        "lat": 59.3360,
        "lng": 18.0680,
        "price": "medium",
        "rating": 4.5,
        "description": "Eski bir ahırın içine kurulmuş; kafe, sanat galerisi ve konsept mağazayı birleştiren Stockholm'ün en gizli ve havalı noktalarından biri.",
        "description_en": "A hidden gem in an old stable, combining a cafe, art gallery, and concept store under high vaulted ceilings.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Giriş sokağın içinde saklı gibidir, ama içeride sizi dev tavanlı büyüleyici bir atmosfer bekler.",
        "tips_en": "The entrance is tucked away, but inside you'll find a stunning space with high ceilings."
    },
    {
        "name": "Woodstockholm",
        "name_en": "Woodstockholm",
        "area": "Södermalm",
        "category": "Restoran",
        "tags": ["modern", "sürdürülebilir", "tasarım", "gurme"],
        "distanceFromCenter": 1.1,
        "lat": 59.3120,
        "lng": 18.0830,
        "price": "high",
        "rating": 4.6,
        "description": "Nytorget meydanında, ahşap tasarımıyla öne çıkan ve sürekli değişen tematik menüler sunan ödüllü bir bistro.",
        "description_en": "Award-winning bistro on Nytorget offering thematic menus and sustainable dining in a beautifully crafted wooden interior.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Menüleri her birkaç ayda bir tamamen değişir (sinema teması, orman teması gibi).",
        "tips_en": "The menu changes completely every few months based on a new theme."
    },
    {
        "name": "Pelikan (Tarihi Meyhane)",
        "name_en": "Pelikan",
        "area": "Södermalm",
        "category": "Restoran",
        "tags": ["klasik", "isveç mutfağı", "atmosfer", "tarihi"],
        "distanceFromCenter": 1.8,
        "lat": 59.3107,
        "lng": 18.0759,
        "price": "high",
        "rating": 4.5,
        "description": "1904'ten beri tavanları resimli devasa salonunda klasik İsveç 'Husmanskost' yemekleri sunan efsanevi mekan.",
        "description_en": "A legendary beer hall and restaurant serving classic Swedish 'Husmanskost' since 1904 in a grand, high-ceilinged room.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "SOS tabağı (Şeker, Peynir ve Ringa Balığı) gerçek bir Stockholm klasiğidir.",
        "tips_en": "Their SOS platter (Butter, Cheese, and Herring) is a true Stockholm classic."
    },
    {
        "name": "Surfers Stockholm",
        "name_en": "Surfers",
        "area": "Norrmalm",
        "category": "Restoran",
        "tags": ["çin mutfağı", "szechuan", "trendy", "kokteyl"],
        "distanceFromCenter": 0.4,
        "lat": 59.3361,
        "lng": 18.0645,
        "price": "high",
        "rating": 4.7,
        "description": "Stockholm'de Szechuan (Çin) mutfağını 'cool' ve trendy bir atmosferde sunan, inanılmaz baharatlı ve lezzetli tabaklarıyla ünlü mekan.",
        "description_en": "Spicy and delicious Szechuan dishes served in a trendy, vibrant atmosphere. One of the city's most exciting dining spots.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Zencefilli domuz eti ve susamlı karidesleri mutlaka paylaşarak deneyin.",
        "tips_en": "Share the ginger pork and sesame shrimp; it's the best way to eat here."
    },
    {
        "name": "Cadier Baren (Grand Hôtel)",
        "name_en": "Cadier Baren",
        "area": "Norrmalm",
        "category": "Bar",
        "tags": ["lüks", "bar", "manzara", "saray"],
        "distanceFromCenter": 0.8,
        "lat": 59.3300,
        "lng": 18.0750,
        "price": "high",
        "rating": 4.7,
        "description": "Dünyanın en iyi otellerinden Grand Hôtel bünyesinde, Kraliyet Sarayı manzaralı, Stockholm'ün en şık ve klasik barı.",
        "description_en": "Stockholm's most elegant bar, located in the Grand Hôtel, offering classic cocktails and views of the Royal Palace.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Akşamüstü kokteyli",
        "bestTime_en": "Afternoon cocktail",
        "tips": "Geleneksel 'Afternoon Tea' deneyimi için de şehrin en iyi adresidir.",
        "tips_en": "The best place in the city for a traditional high-end Afternoon Tea."
    },
    {
        "name": "Gondolen (Manzara Restoran)",
        "name_en": "Gondolen",
        "area": "Södermalm",
        "category": "Manzara",
        "tags": ["panoramik", "lüks", "ikonik", "deniz"],
        "distanceFromCenter": 1.0,
        "lat": 59.3190,
        "lng": 18.0740,
        "price": "high",
        "rating": 4.6,
        "description": "Slussen'de suyun üzerinde asılı duran bir platformda, Stockholm'ün en ikonik ve en güzel manzaralı restoranlarından biri.",
        "description_en": "Suspended high above the water at Slussen, offering one of Stockholm's most spectacular and iconic dining views.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Sadece bir kokteyl içmek için bar kısmına da gidebilirsiniz, manzaraya değer.",
        "tips_en": "You can visit the bar area just for a cocktail to enjoy the view."
    },
    {
        "name": "Stureplan (Merkez)",
        "name_en": "Stureplan",
        "area": "Östermalm",
        "category": "Deneyim",
        "tags": ["gece hayatı", "meydan", "moda", "lüks"],
        "distanceFromCenter": 0.5,
        "lat": 59.3360,
        "lng": 18.0730,
        "price": "medium",
        "rating": 4.3,
        "description": "Stockholm'ün lüks gece hayatının, moda dükkanlarının ve iş dünyasının kalbi olan ünlü meydan.",
        "description_en": "The heart of Stockholm's upscale nightlife, fashion, and business districts. The place to see and be seen.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Meydanın ortasındaki 'Mantar' (Svampen) yapısı geleneksel bir buluşma noktasıdır.",
        "tips_en": "The 'Mushroom' (Svampen) structure in the center is the city's most common meeting point."
    },
    {
        "name": "Nytorget (SoFo Kalbi)",
        "name_en": "Nytorget",
        "area": "Södermalm",
        "category": "Manzara",
        "tags": ["hipster", "meydan", "kafe", "park"],
        "distanceFromCenter": 1.3,
        "lat": 59.3120,
        "lng": 18.0830,
        "price": "low",
        "rating": 4.6,
        "description": "Stockholm'ün en havalı mahallesi SoFo'nun merkezi. Etrafı harika kafeteryalar ve butiklerle çevrili, yerel halkın sosyalleşme noktası.",
        "description_en": "The heart of the trendy SoFo neighborhood, surrounded by some of the city's coolest cafes and independent boutiques.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Yazın çimlere yayılıp Urban Deli'den aldığınız atıştırmalıklarla piknik yapın.",
        "tips_en": "In summer, grab some snacks from Urban Deli and enjoy a picnic on the grass."
    },
    {
        "name": "Kungliga Dramatiska Teatern (Dramaten)",
        "name_en": "The Royal Dramatic Theatre",
        "area": "Östermalm",
        "category": "Tarihi",
        "tags": ["tiyatro", "mimari", "altın", "sanat"],
        "distanceFromCenter": 0.7,
        "lat": 59.3330,
        "lng": 18.0770,
        "price": "medium",
        "rating": 4.6,
        "description": "İsveç'in ulusal tiyatrosu. Art Nouveau tarzı beyaz binası ve altın yaldızlı detaylarıyla sahil şeridinin en güzel yapılarından biridir.",
        "description_en": "Sweden's national theater, housed in a magnificent Art Nouveau building with white marble and gold details.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz veya Akşam",
        "bestTime_en": "Daytime or Evening",
        "tips": "Tiyatro binasının dışındaki merdivenlerde oturup limanı izlemek bir Stockholm klasiğidir.",
        "tips_en": "Sitting on the theater steps and watching the harbor is a local favorite."
    },
    {
        "name": "Skeppsholmen Adası",
        "name_en": "Skeppsholmen",
        "area": "Skeppsholmen",
        "category": "Manzara",
        "tags": ["ada", "yürüyüş", "deniz", "sakin"],
        "distanceFromCenter": 1.0,
        "lat": 59.3250,
        "lng": 18.0850,
        "price": "free",
        "rating": 4.7,
        "description": "Şehir merkezinin ortasında ama bir o kadar sakin, müzeler odası olarak bilinen huzurlu ada.",
        "description_en": "A peaceful island in the heart of the city, known for its museums, quiet walking paths, and beautiful views of the Royal Palace.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Güneşli gün",
        "bestTime_en": "Sunny day",
        "tips": "Adayı karaya bağlayan altın taçlı köprü (Skeppsholmsbron) en popüler fotoğraf noktasıdır.",
        "tips_en": "The bridge leading to the island with its gold crown (Skeppsholmsbron) is a famous photo spot."
    }
]

def enrich_stockholm_batch3():
    filepath = 'assets/cities/stockholm.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_stockholm_batch3:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    # Filter out any generic fillers that might have slipped through
    data['highlights'] = [h for h in data['highlights'] if not h['name'].startswith('Highlight') and not h['name'].startswith('Place')]

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_stockholm_batch3()
print(f"Stockholm now has {count} highlights.")
