import json
import os

new_cenevre_batch2 = [
    {
        "name": "Le Kiosque des Bastions",
        "name_en": "Le Kiosque des Bastions",
        "area": "Plainpalais",
        "category": "Kafe",
        "tags": ["park", "cam bina", "şık", "brunch"],
        "distanceFromCenter": 0.5,
        "lat": 46.2008,
        "lng": 6.1452,
        "price": "high",
        "rating": 4.5,
        "description": "Bastions Parkı'nın içinde, rüya gibi bir cam yapı içinde yer alan, özellikle brunchları ve şık atmosferiyle ünlü restoran.",
        "description_en": "A stunning glass-enclosed restaurant located in the heart of Bastions Park, famous for its elegant ambiance and high-quality Sunday brunch.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Hafta sonu sabah",
        "bestTime_en": "Weekend morning",
        "tips": "Rezervasyonsuz yer bulmak imkansız gibidir, mutlaka önceden arayın.",
        "tips_en": "Practically impossible to get a table without a reservation, especially for their popular weekend brunch; book well in advance."
    },
    {
        "name": "Boreal Coffee Shop (Stand)",
        "name_en": "Boreal Coffee Shop",
        "area": "Merkez",
        "category": "Kafe",
        "tags": ["nitelikli kahve", "lokal", "hipster", "wifi"],
        "distanceFromCenter": 0.3,
        "lat": 46.2052,
        "lng": 6.1425,
        "price": "medium",
        "rating": 4.6,
        "description": "Cenevre'nin en iyi nitelikli kahve kavurucularından biri. Şehrin yerel ve genç nüfusunun favori buluşma noktası.",
        "description_en": "One of Geneva's premier specialty coffee roasters, offering a vibrant atmosphere and some of the best beans in the city.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Buradaki Flat White şehirdeki en iyilerden biridir.",
        "tips_en": "Their Flat White is considered one of the best in town; it's a great spot to catch up on work or people-watch."
    },
    {
        "name": "Chez ma Cousine (Bourg-de-Four)",
        "name_en": "Chez ma Cousine",
        "area": "Vieille Ville",
        "category": "Restoran",
        "tags": ["tavuk", "ekonomik", "lokal", "merkezi"],
        "distanceFromCenter": 0.1,
        "lat": 46.2001,
        "lng": 6.1488,
        "price": "medium",
        "rating": 4.4,
        "description": "Cenevre'nin belki de en meşhur ekonomik restoranı. Sadece tavuk yemekleri üzerine uzmanlaşmış, her zaman kalabalık ve canlı.",
        "description_en": "A local institution famous for its simple but delicious roasted chicken menu. One of the best value meals in expensive Geneva.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Öğle / Akşam",
        "bestTime_en": "Lunch / Dinner",
        "tips": "Kapıda her zaman sıra olur, ama hızlı akar. Porsiyonları oldukça doyurucudur.",
        "tips_en": "Expect a queue as they don't take reservations, but the turnover is fast and the signature roasted chicken is worth the wait."
    },
    {
        "name": "Rue de l'Hôtel-de-Ville",
        "name_en": "Rue de l'Hotel-de-Ville",
        "area": "Vieille Ville",
        "category": "Tarihi",
        "tags": ["belediye", "ortaçağ", "mimari", "merkez"],
        "distanceFromCenter": 0.1,
        "lat": 46.2015,
        "lng": 6.1462,
        "price": "free",
        "rating": 4.6,
        "description": "Belediye binasının bulunduğu, Cenevre tarihinin en önemli siyasi kararlarının alındığı, asil görünümlü bir sokak.",
        "description_en": "The historic street housing the City Hall, where many of Geneva's most significant political decisions have been made over the centuries.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Belediye binasının avlusuna girmek serbesttir, oradaki devasa rampayı mutlaka görün.",
        "tips_en": "The internal courtyard of the Hotel-de-Ville is usually open to the public; check out the massive stone ramp designed for horses."
    },
    {
        "name": "Cité du Temps",
        "name_en": "Cite du Temps",
        "area": "Limmat",
        "category": "Müze",
        "tags": ["saat", "swatch", "modern", "nehir"],
        "distanceFromCenter": 0.2,
        "lat": 46.2055,
        "lng": 6.1458,
        "price": "free",
        "rating": 4.3,
        "description": "Limmat nehrinin ortasında yer alan, Swatch ve Omega saatlerinin tarihini sergileyen modern ve interaktif bir merkez.",
        "description_en": "A modern cultural center located on a bridge across the Rhône, dedicated to the world of timekeeping and housing the Swatch and Omega museums.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Yağmurlu gün",
        "bestTime_en": "Rainy day",
        "tips": "Binanın mimarisi ve nehir üzerindeki konumu fotoğraf ekmek için harikadır.",
        "tips_en": "The building's location directly over the rushing river provides a unique urban backdrop for photography."
    },
    {
        "name": "Bain des Dames",
        "name_en": "The Ladies' Bath",
        "area": "Göl",
        "category": "Deneyim",
        "tags": ["plaj", "gelenek", "göl", "sakinlık"],
        "distanceFromCenter": 1.2,
        "lat": 46.2085,
        "lng": 6.1620,
        "price": "low",
        "rating": 4.4,
        "description": "Eaux-Vives parkının altında yer alan, sadece kadınlara özel tarihi bir yüzme ve güneşlenme alanı.",
        "description_en": "A historic, ladies-only swimming and sunbathing area located on the lakefront below the Parc des Eaux-Vives.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Yaz sabahı",
        "bestTime_en": "Summer morning",
        "tips": "Cenevre'nin en huzurlu ve korunaklı yüzme noktalarından biridir.",
        "tips_en": "Known for its peaceful atmosphere, it's a great place for a quiet morning swim away from the busier public beaches."
    },
    {
        "name": "Parc de Mon Repos",
        "name_en": "Mon Repos Park",
        "area": "Pâquis",
        "category": "Park",
        "tags": ["göl", "yürüyüş", "heykel", "sakinlık"],
        "distanceFromCenter": 1.8,
        "lat": 46.2215,
        "lng": 6.1511,
        "price": "free",
        "rating": 4.7,
        "description": "Adı gibi 'Huzurum' olan, göl kenarında devasa ağaçları ve şık malikaneleriyle kentin en elit parklarından biri.",
        "description_en": "Living up to its name which means 'My Rest,' this lakeside park features giant century-old trees and elegant historic villas.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Hafta sonu öğleden sonra",
        "bestTime_en": "Weekend afternoon",
        "tips": "Buradan göl üzerindeki sarı taksileri (Mouettes) izlemek çok keyiflidir.",
        "tips_en": "A perfect spot for a picnic with a direct view of the boat traffic and the distant snowy peaks."
    },
    {
        "name": "Cave de l'Hôtel de Ville",
        "name_en": "The City Hall Cellar",
        "area": "Vieille Ville",
        "category": "Restoran",
        "tags": ["şarap", "yerel lezzet", "tarihi", "fondü"],
        "distanceFromCenter": 0.1,
        "lat": 46.2014,
        "lng": 6.1465,
        "price": "high",
        "rating": 4.5,
        "description": "Belediye binasının hemen altında, tarihi bir mahzende yer alan, yerel Cenevre şaraplarını ve fondü çeşitlerini deneyebileceğiniz çok otantik bir mekan.",
        "description_en": "An authentic restaurant located in a historic cellar beneath the City Hall, specializing in local Geneva wines and traditional Swiss specialties.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Burada mutlaka 'Perch Fillets' (göl balığı) denemelisiniz, yerel bir spesiyalitedir.",
        "tips_en": "Try their 'Filets de Perche du Lac' for a truly local dining experience in an atmospheric underground setting."
    },
    {
        "name": "Bongénie Grieder",
        "name_en": "Bongenie Grieder",
        "area": "Merkez",
        "category": "Alışveriş",
        "tags": ["lüks", "moda", "tasarım", "gurme kahvaltı"],
        "distanceFromCenter": 0.2,
        "lat": 46.2038,
        "lng": 6.1495,
        "price": "high",
        "rating": 4.4,
        "description": "Cenevre'nin en lüks ve seçkin çok katlı mağazası. İçinde en ünlü moda evlerinin koleksiyonları bulunur.",
        "description_en": "A high-end luxury fashion department store, featuring a curated selection of world-class designer brands and an elegant rooftop cafe.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "En üst kattaki teras kafesi, alışveriş yorgunluğunu atmak ve şehri izlemek için harika bir yerdir.",
        "tips_en": "The rooftop tea room is one of the most sophisticated spots in the city for a light lunch or afternoon tea."
    },
    {
        "name": "Auberge de Savièse",
        "name_en": "Auberge de Saviese",
        "area": "Pâquis",
        "category": "Restoran",
        "tags": ["raclette", "fondü", "geleneksel", "ahşap"],
        "distanceFromCenter": 0.7,
        "lat": 46.2112,
        "lng": 6.1492,
        "price": "high",
        "rating": 4.7,
        "description": "Geleneksel bir dağ evi (chalet) atmosferinde, en iyi raclette ve fondü çeşitlerini sunan çok popüler bir restoran.",
        "description_en": "A cozy Swiss chalet-style restaurant in the city center, renowned for its excellent raclette and diverse variety of cheese fondues.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Soğuk akşamlar",
        "bestTime_en": "Cold evenings",
        "tips": "Rezervasyon yapmadan gitmeyin, özellikle turistlerin ve yerellerin ortak favorisidir.",
        "tips_en": "Highly recommended to book a table; it's one of the few places in the city that consistently delivers a perfect 'mountain hut' dining vibe."
    },
    {
        "name": "Little Barrel",
        "name_en": "Little Barrel",
        "area": "Pâquis",
        "category": "Bar",
        "tags": ["rom", "kokteyl", "şık", "gece hayatı"],
        "distanceFromCenter": 0.8,
        "lat": 46.2120,
        "lng": 6.1485,
        "price": "high",
        "rating": 4.6,
        "description": "Dünyanın en geniş rom koleksiyonlarından birine sahip, çok şık ve uzman barmenlerin olduğu butik bir bar.",
        "description_en": "A specialized rum bar with an incredible selection from around the world, offering expert mixology in a sophisticated industrial setting.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam geç saatler",
        "bestTime_en": "Late evening",
        "tips": "Kendi damak tadınızı tarif edin, barmenlerin hazırladığı özel karışımlara güvenin.",
        "tips_en": "Let the bartenders create a personalized cocktail based on your flavor profile; their knowledge of spirits is impressive."
    },
    {
        "name": "Mr. Pickwick Pub",
        "name_en": "Mr. Pickwick Pub",
        "area": "Pâquis",
        "category": "Bar",
        "tags": ["pub", "bira", "canlı maç", "lokal"],
        "distanceFromCenter": 0.6,
        "lat": 46.2088,
        "lng": 6.1478,
        "price": "medium",
        "rating": 4.2,
        "description": "Cenevre'nin en eski ve en sevilen İngiliz pubı. Her zaman canlı, gürültülü ve samimi.",
        "description_en": "The oldest English pub in Geneva, providing a classic atmosphere with British beers, pub food, and live sports screenings.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Hafta sonu akşamı",
        "bestTime_en": "Weekend evening",
        "tips": "Önemli maç günlerinde yer bulmak zordur, erken gidip biranızı almanız iyi olur.",
        "tips_en": "The place to be for international rugby or football matches; expect a lively crowd and a true pub experience."
    },
    {
        "name": "Parc de la Perle du Lac (Yürüyüş Yolu)",
        "name_en": "Perle du Lac Shoreline",
        "area": "Pâquis",
        "category": "Manzara",
        "tags": ["göl", "bisiklet", "koşu", "manzara"],
        "distanceFromCenter": 2.2,
        "lat": 46.2225,
        "lng": 6.1530,
        "price": "free",
        "rating": 4.9,
        "description": "Gölün en uç noktasında, Alplerin karlı zirvelerini doğrudan gören muazzam bir yürüyüş ve bisiklet yolu.",
        "description_en": "The scenic lakeshore path through the Perle du Lac park, widely considered the most beautiful stretch for walking and cycling in the city.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Güneşli öğleden sonra",
        "bestTime_en": "Sunny afternoon",
        "tips": "Yol üzerindeki Bilim Tarihi müzesinin önündeki banklar en iyi manzaraya sahiptir.",
        "tips_en": "Stop at the benches in front of the Villa Barton for the classic 'postcard' view of Lake Geneva and the mountains."
    },
    {
        "name": "Musée d'Histoire des Sciences",
        "name_en": "History of Science Museum",
        "area": "Pâquis",
        "category": "Müze",
        "tags": ["bilim", "tarihi cihazlar", "malikane", "ücretsiz"],
        "distanceFromCenter": 2.1,
        "lat": 46.2218,
        "lng": 6.1528,
        "price": "free",
        "rating": 4.5,
        "description": "Göl kenarındaki muazzam bir malikanede yer alan, astronomiden fiziğe tarihi bilimsel araçların sergilendiği çok şık bir müze.",
        "description_en": "Housed in a beautiful 19th-century villa, this museum displays a fascinating collection of historical scientific instruments from Geneva's golden age of discovery.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin bahçesi ve manzarası tek başına bile ziyaret etmeye değer, giriş de ücretsizdir.",
        "tips_en": "The villa itself is an architectural gem, and its lakefront setting makes it one of the most serene museum visits in Switzerland."
    },
    {
        "name": "Buvette des Eaux-Vives",
        "name_en": "Eaux-Vives Waterfront",
        "area": "Eaux-Vives",
        "category": "Deneyim",
        "tags": ["göl", "lokal", "açık hava", "rahat"],
        "distanceFromCenter": 1.4,
        "lat": 46.2088,
        "lng": 6.1645,
        "price": "low",
        "rating": 4.6,
        "description": "Eaux-Vives sahilinde yer alan, yerlilerin güneşlenip göle girdiği, salaş ve çok popüler bir açık hava mekanı.",
        "description_en": "A casual local hangout on the Eaux-Vives lakeshore, perfect for a drink and a light snack while watching the sun set over the water.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Yaz akşamüzeri",
        "bestTime_en": "Summer late afternoon",
        "tips": "Yazın yapılan yeni kumsal alanına çok yakındır, akşam saatlerinde çok canlı olur.",
        "tips_en": "Just steps away from the newly created public beach, it's the heart of Geneva's lakeside social life in the warmer months."
    },
    {
        "name": "L'Epicentre",
        "name_en": "L'Epicentre",
        "area": "Eaux-Vives",
        "category": "Bar",
        "tags": ["nitelikli bira", "hipster", "lokal", "canlı"],
        "distanceFromCenter": 1.2,
        "lat": 46.2045,
        "lng": 6.1555,
        "price": "medium",
        "rating": 4.4,
        "description": "Eaux-Vives bölgesinin en sevilen butik bira (craft beer) barı. Genç ve enerjik bir kitlesi var.",
        "description_en": "A premier craft beer destination in the Eaux-Vives district, known for its rotating tap list and vibrant neighborhood atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Perşembe-Cuma akşamı",
        "bestTime_en": "Thursday-Friday evening",
        "tips": "İsviçre'nin küçük yerel üreticilerinin biralarını denemek için en iyi adreslerden biridir.",
        "tips_en": "Ask for recommendations on Swiss micro-breweries; they often have rare local gems on tap."
    },
    {
        "name": "Théâtre de Carouge",
        "name_en": "Theatre de Carouge",
        "area": "Carouge",
        "category": "Tarihi",
        "tags": ["kültür", "sanat", "mimari", "modern"],
        "distanceFromCenter": 2.2,
        "lat": 46.1835,
        "lng": 6.1388,
        "price": "high",
        "rating": 4.6,
        "description": "Carouge'un kalbinde, modern mimarisiyle ödül almış, Cenevre'nin en prestijli tiyatro sahnelerinden biri.",
        "description_en": "An award-winning contemporary theater building in the heart of historic Carouge, showcasing high-quality French-language productions.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Akşam (Oyun varken)",
        "bestTime_en": "Evening (During plays)",
        "tips": "Binanın gece ışıklandırması ve çevresindeki restoranlar akşam yemeği için harika bir atmosfer sunar.",
        "tips_en": "The plaza in front of the theater is a great social hub; combine a show with dinner in one of the nearby Italian-style bistros."
    },
    {
        "name": "Le Flacon",
        "name_en": "Le Flacon",
        "area": "Carouge",
        "category": "Restoran",
        "tags": ["michelin yıldızı", "gurme", "modern", "açık mutfak"],
        "distanceFromCenter": 2.1,
        "lat": 46.1845,
        "lng": 6.1395,
        "price": "high",
        "rating": 4.8,
        "description": "Carouge'un bohem sokaklarında, Michelin yıldızlı olmasına rağmen rahat ve modern bir havada gurme lezzetler sunan restoran.",
        "description_en": "A Michelin-starred restaurant in Carouge that breaks away from formal traditions, offering innovative cuisine in a relaxed, open-kitchen environment.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Özel akşam yemekleri",
        "bestTime_en": "Special occasion dinner",
        "tips": "Öğle menüsü fiyat-performans açısından muazzamdır, gurme lezzetleri daha uygun fiyata tadabilirsiniz.",
        "tips_en": "Their lunch business menu is an incredible secret value, offering high-end gastronomy at a fraction of the dinner price."
    },
    {
        "name": "Rond-Point de Rive (Pazar)",
        "name_en": "Rive Farmers Market",
        "area": "Merkez",
        "category": "Deneyim",
        "tags": ["pazar", "taze ürün", "gurme", "lokal"],
        "distanceFromCenter": 0.4,
        "lat": 46.2030,
        "lng": 6.1535,
        "price": "medium",
        "rating": 4.5,
        "description": "Haftada iki kez kurulan, İsviçre'nin en kaliteli peynirlerini, şaraplarını ve taze ürünlerini bulabileceğiniz lüks bir açık hava pazarı.",
        "description_en": "A vibrant open-air market occurring twice a week, where upscale locals buy top-quality Swiss cheeses, wines, and artisanal products.",
        "imageUrl": "https://images.unsplash.com/photo-1543333346-bf0375179462?w=800",
        "bestTime": "Cumartesi sabah",
        "bestTime_en": "Saturday morning",
        "tips": "Buradaki taze ekmek ve peynirlerle kendinize harika bir piknik çantası hazırlayabilirsiniz.",
        "tips_en": "The best place to assemble a gourmet picnic basket for an afternoon by the lake; the variety of local cheeses is unparalleled."
    },
    {
        "name": "Smala (Shopping)",
        "name_en": "Smala Concept Store",
        "area": "Eaux-Vives",
        "category": "Alışveriş",
        "tags": ["tasarım", "konsept", "lokal üreticiler", "ev dekorasyonu"],
        "distanceFromCenter": 1.1,
        "lat": 46.2040,
        "lng": 6.1565,
        "price": "high",
        "rating": 4.6,
        "description": "Cenevre'nin en trend konsept mağazalarından biri. Yerel tasarımcıların ürünleri ve eşsiz ev dekorasyon eşyaları bulunur.",
        "description_en": "A trendy concept store in Eaux-Vives showcasing unique interior decor, fashion, and artisanal goods from independent Swiss and European designers.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Özgün bir hediye arıyorsanız şehirdeki en doğru adreslerden biridir.",
        "tips_en": "If you are looking for a gift that isn't a typical tourist souvenir, this is the place to find something truly unique."
    },
    {
        "name": "Plaine de Plainpalais (Aktivite Alanı)",
        "name_en": "Plainpalais Plaza",
        "area": "Plainpalais",
        "category": "Deneyim",
        "tags": ["kaykay", "pazar", "etkinlik", "dev alan"],
        "distanceFromCenter": 0.9,
        "lat": 46.1975,
        "lng": 6.1415,
        "price": "free",
        "rating": 4.3,
        "description": "Şehrin en büyük açık alanı. Kaykay parkı, dev bit pazarı ve sirk alanıyla Cenevre'nin enerjisinin en yüksek olduğu yer.",
        "description_en": "A massive diamond-shaped public space used for world-class flea markets, skate parks, and hosting the national circus 'Knie' annually.",
        "imageUrl": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800",
        "bestTime": "Cumartesi (Pazar varken)",
        "bestTime_en": "Saturday (Market day)",
        "tips": "Buradaki kaykay parkı Avrupa'nın en iyilerinden biri kabul edilir, izlemesi çok eğlencelidir.",
        "tips_en": "The skate park at the southern end is always buzzing with energy; it's a great spot for urban photography."
    },
    {
        "name": "Ethno (Bar)",
        "name_en": "Ethno Bar",
        "area": "Plainpalais",
        "category": "Bar",
        "tags": ["alternatif", "lokal", "gece", "öğrenci"],
        "distanceFromCenter": 1.0,
        "lat": 46.1965,
        "lng": 6.1405,
        "price": "medium",
        "rating": 4.5,
        "description": "Plainpalais'nın en popüler mahalle barlarından biri. Rahat atmosferi ve uygun fiyatlı kokteylleriyle bilinir.",
        "description_en": "A beloved neighborhood bar in Plainpalais, popular for its eclectic decor, friendly service, and relaxed alternative vibe.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Hafta içi akşam",
        "bestTime_en": "Weekday evening",
        "tips": "Genellikle öğrenciler ve genç profesyonellerin tercihidir, Cenevre'nin pahalı havasından uzaktır.",
        "tips_en": "A great escape from Geneva's formal side; simple, honest drinks and a very welcoming crowd."
    },
    {
        "name": "Boreal Coffee (Eaux-Vives)",
        "name_en": "Boreal Eaux-Vives",
        "area": "Eaux-Vives",
        "category": "Kafe",
        "tags": ["kahve", "modern", "çalışma alanı", "popüler"],
        "distanceFromCenter": 1.1,
        "lat": 46.2055,
        "lng": 6.1585,
        "price": "medium",
        "rating": 4.7,
        "description": "Boreal'in göl tarafındaki şubesi. Daha geniş oturma alanı ve modern tasarımıyla ön planda.",
        "description_en": "The lakeside branch of the famous Boreal roasters, offering high-quality caffeine in a bright, spacious, and modern setting.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Hafta içi öğle",
        "bestTime_en": "Weekday noon",
        "tips": "Bilgisayarını alıp çalışmak isteyenler için Cenevre'deki en uygun kafelereden biridir.",
        "tips_en": "Very digital-nomad friendly with plenty of power outlets and excellent Wi-Fi, paired with top-tier specialty coffee."
    },
    {
        "name": "La Clémence (Teras)",
        "name_en": "La Clemence Terrace",
        "area": "Vieille Ville",
        "category": "Kafe",
        "tags": ["insan izleme", "tarihi meydan", "ikonik", "güneş"],
        "distanceFromCenter": 0.1,
        "lat": 46.2001,
        "lng": 6.1490,
        "price": "high",
        "rating": 4.6,
        "description": "Bourg-de-Four meydanının en ikonik terası. Cenevre'de 'görülmek ve görmek' için en popüler yer.",
        "description_en": "The most iconic terrace in Geneva's Old Town, located on the historic Place du Bourg-de-Four. The ultimate spot for people-watching.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Güneşli öğleden sonra",
        "bestTime_en": "Sunny afternoon",
        "tips": "Güneş açtığı an tüm Cenevre buraya akar, yer bulmak için sabırlı olmanız gerekebilir.",
        "tips_en": "In summer, people stand for their drinks just to enjoy the atmosphere; it's the beating heart of the old town social scene."
    },
    {
        "name": "Pâquis Waterfront (Sarı İskeleler)",
        "name_en": "Paquis Jetty",
        "area": "Pâquis",
        "category": "Manzara",
        "tags": ["göl", "gün batımı", "ıslanma", "jet d'eau"],
        "distanceFromCenter": 0.9,
        "lat": 46.2110,
        "lng": 6.1555,
        "price": "free",
        "rating": 4.8,
        "description": "Jet d'Eau'ya en çok yaklaştığınız yer olan bu iskele yolu, gölün içinde yürüyormuşsunuz hissi verir.",
        "description_en": "The long jetty leading into the lake, offering the closest safe public view of the powerful Jet d'Eau water column.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Fırtınasız gün",
        "bestTime_en": "Calm day",
        "tips": "Rüzgarın yönüne dikkat edin! Bir anda Jet d'Eau'nun sularıyla tamamen ıslanabilirsiniz.",
        "tips_en": "Watch the wind direction carefully; it can shift in seconds and soak everyone on the jetty with lake spray."
    },
    {
        "name": "Chocolaterie Favarger",
        "name_en": "Favarger Chocolate",
        "area": "Merkez / Quai des Bergues",
        "category": "Alışveriş",
        "tags": ["çikolata", "tarihi", "hediyelik", "gelenek"],
        "distanceFromCenter": 0.3,
        "lat": 46.2065,
        "lng": 6.1455,
        "price": "high",
        "rating": 4.7,
        "description": "1826'dan beri üretim yapan, Cenevre'nin en eski butik çikolata üreticisi. Gerçek sanatkarlık eserleri üretirler.",
        "description_en": "One of Geneva's oldest and most prestigious chocolatiers, making exquisite artisanal Swiss chocolate since 1826.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Buradaki 'Avelines' çeşitleri çikolata severler için bir zorunluluktur.",
        "tips_en": "Their signature 'Avelines' pralines are legendary and make for an elegant, authentic Swiss souvenir."
    },
    {
        "name": "L'Adresse (Boutique & Café)",
        "name_en": "L'Adresse Boutique & Cafe",
        "area": "Eaux-Vives",
        "category": "Kafe",
        "tags": ["gizli teras", "şık", "bohem", "moda"],
        "distanceFromCenter": 1.2,
        "lat": 46.2045,
        "lng": 6.1560,
        "price": "high",
        "rating": 4.6,
        "description": "Bir binanın üst katında gizlenmiş, hem butik bir mağaza hem de muazzam bir teras kafesi olan şehirli ve cool bir mekan.",
        "description_en": "A hidden rooftop gem in Eaux-Vives combining a multi-brand fashion boutique with a vibrant urban terrace cafe.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Binanın kapısına dikkatli bakın, sokaktaki tabela oldukça küçüktür, Cenevre'nin gerçek saklı hazinelerinden biridir.",
        "tips_en": "Look for the small sign on the door; once inside, the lift takes you to a bohemian paradise above the busy streets."
    },
    {
        "name": "La Buvette des Bains (Kahvaltı)",
        "name_en": "Bains des Paquis Breakfast",
        "area": "Pâquis",
        "category": "Kafe",
        "tags": ["kahvaltı", "göl manzarası", "lokal", "basit"],
        "distanceFromCenter": 0.8,
        "lat": 46.2100,
        "lng": 6.1578,
        "price": "low",
        "rating": 4.8,
        "description": "Günün başladığı yer. Gölün üstünde martılar eşliğinde yapacağınız en ekonomik ve en Cenevreli kahvaltı.",
        "description_en": "The most authentic way to start a Geneva day. A simple, affordable breakfast with a 360-degree view of the lake and the waking city.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "Güneşin doğuşunu izlemek için kentin en iyi noktası burasıdır.",
        "tips_en": "Arrive as the sun rises to watch the light change over the water; it's a magical and very affordable gourmet moment."
    },
    {
        "name": "Bottle Brothers (Cocktail Bar)",
        "name_en": "Bottle Brothers",
        "area": "Eaux-Vives",
        "category": "Bar",
        "tags": ["kokteyl", "yemek", "enerjik", "trend"],
        "distanceFromCenter": 1.1,
        "lat": 46.2040,
        "lng": 6.1565,
        "price": "high",
        "rating": 4.4,
        "description": "Eaux-Vives'ın en popüler modern kokteyl barı. Yaratıcı sunumları ve kaliteli atıştırmalıklarıyla tanınır.",
        "description_en": "A vibrant and creative cocktail bar in Eaux-Vives, famous for its innovative mixology and sophisticated 'tapas-style' dining.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Hafta sonu akşam",
        "bestTime_en": "Weekend evening",
        "tips": "Hemen yanındaki 'Grand Bottle' kısmına da göz atın, atmosfer biraz daha sakin olabilir.",
        "tips_en": "Known for its high energy and excellent music; it's a staple of Geneva's modern nightlife scene."
    },
    {
        "name": "Le Chat-Botté",
        "name_en": "Le Chat-Botte",
        "area": "Göl Kenarı",
        "category": "Restoran",
        "tags": ["michelin", "lüks", "fine dining", "otel"],
        "distanceFromCenter": 0.5,
        "lat": 46.2075,
        "lng": 6.1505,
        "price": "high",
        "rating": 4.9,
        "description": "Beau-Rivage otelinin içinde, Michelin yıldızlı, Cenevre'nin klasik fine dining ve mutfak sanatları zirvesi.",
        "description_en": "A legendary Michelin-starred temple of French gastronomy located inside the Beau-Rivage hotel, overlooking the lake.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Kutlama yemeği",
        "bestTime_en": "Celebration dinner",
        "tips": "Ceketli katılım (smart-casual) beklenir, önceden rezervasyon çok önemsenir.",
        "tips_en": "One of the most prestigious dining rooms in Europe; expect impeccable service and a world-class wine list."
    }
]

def enrich_cenevre_batch2():
    filepath = 'assets/cities/cenevre.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_cenevre_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_cenevre_batch2()
print(f"Geneva now has {count} highlights.")
# Add wait time to allow writing before next tool
