import json
import os

new_berlin_batch2 = [
    {
        "name": "Viktoriapark",
        "name_en": "Viktoriapark",
        "area": "Kreuzberg",
        "category": "Park",
        "tags": ["selale", "manzara", "piknik", "tepe"],
        "distanceFromCenter": 2.5,
        "lat": 52.4882,
        "lng": 13.3798,
        "price": "free",
        "rating": 4.7,
        "description": "Kreuzberg'in en yüksek noktasında yer alan, yapay bir şelaleye ve Berlin manzarasını ayaklar altına seren bir anıta sahip huzurlu park.",
        "description_en": "A peaceful park located at the highest point of Kreuzberg, featuring an artificial waterfall and a monument offering panoramic views of Berlin.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Şelalenin en üstüne çıkıp Berlin panoramasının tadını çıkarın.",
        "tips_en": "Climb to the top of the waterfall to enjoy the panoramic view of Berlin."
    },
    {
        "name": "Landwehrkanal",
        "name_en": "Landwehr Canal",
        "area": "Kreuzberg",
        "category": "Manzara",
        "tags": ["kanal", "yürüyüş", "nehir", "lokal"],
        "distanceFromCenter": 2.8,
        "lat": 52.4978,
        "lng": 13.3911,
        "price": "free",
        "rating": 4.6,
        "description": "Berlin'in içinden geçen, kıyısındaki salkım söğütler ve teknelerle şehre Venedik havası katan huzurlu su yolu.",
        "description_en": "A peaceful waterway passing through Berlin, adding a Venetian vibe to the city with its weeping willows and canal boats.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Kanal kenarındaki Paul-Lincke-Ufer'de bir yürüyüş yapıp oradaki kafelerden birinde mola verin.",
        "tips_en": "Take a walk along the Paul-Lincke-Ufer and take a break at one of the riverside cafes."
    },
    {
        "name": "Boxhagener Platz",
        "name_en": "Boxhagener Platz",
        "area": "Friedrichshain",
        "category": "Park",
        "tags": ["pazar", "bit pazarı", "lokal", "meydan"],
        "distanceFromCenter": 3.8,
        "lat": 52.5117,
        "lng": 13.4566,
        "price": "free",
        "rating": 4.5,
        "description": "Friedrichshain'ın kalbi. Cumartesi taze gıda pazarı, Pazar ise efsanevi bit pazarı ile her daim canlı.",
        "description_en": "The heart of Friedrichshain. Always a lively spot with a fresh food market on Saturdays and a legendary flea market on Sundays.",
        "imageUrl": "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800",
        "bestTime": "Pazar sabahı",
        "bestTime_en": "Sunday morning",
        "tips": "Bit pazarını gezdikten sonra meydanı çevreleyen sayısız kafeden birinde brunch yapın.",
        "tips_en": "After browsing the flea market, have brunch at one of the many cafes surrounding the square."
    },
    {
        "name": "Arminius-Markthalle",
        "name_en": "Arminius Market Hall",
        "area": "Moabit",
        "category": "Deneyim",
        "tags": ["yemek", "pazar", "mimari", "tarihi"],
        "distanceFromCenter": 3.5,
        "lat": 52.5277,
        "lng": 13.3384,
        "price": "medium",
        "rating": 4.6,
        "description": "1891'den kalma tarihi pazar yeri. Şimdilerde gurme lezzetlerin, şarap barlarının ve el sanatlarının buluşma noktası.",
        "description_en": "A historic market hall from 1891, now a hotspot for gourmet food, wine bars, and local handicrafts.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Mekanın içindeki muhteşem ışıklandırma akşamları harika bir atmosfer sunuyor.",
        "tips_en": "The hall's magnificent indoor lighting creates a fantastic atmosphere in the evening."
    },
    {
        "name": "Liquidrom",
        "name_en": "Liquidrom",
        "area": "Kreuzberg",
        "category": "Deneyim",
        "tags": ["spa", "yüzme", "müzik", "rahatlama"],
        "distanceFromCenter": 1.2,
        "lat": 52.5030,
        "lng": 13.3814,
        "price": "high",
        "rating": 4.4,
        "description": "Modern bir termal banyo deneyimi. Tuzlu su havuzunda suyun altında çalan klasik veya elektronik müzikle derin bir rahatlama sunuyor.",
        "description_en": "A modern thermal bath experience. Offers deep relaxation in a saltwater pool with classical or electronic music playing underwater.",
        "imageUrl": "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Özellikle kışın dondurucu Berlin havalarında iç mekanın sıcaklığı ve ambiyansı paha biçilemez.",
        "tips_en": "The indoor warmth and ambiance are priceless, especially during freezing Berlin winters."
    },
    {
        "name": "Vabali Spa",
        "name_en": "Vabali Spa",
        "area": "Mitte / Moabit",
        "category": "Deneyim",
        "tags": ["bali", "spa", "sauna", "lüks"],
        "distanceFromCenter": 2.0,
        "lat": 52.5270,
        "lng": 13.3615,
        "price": "high",
        "rating": 4.8,
        "description": "Berlin'in ortasında Bali esintili bir vaha. Sayısız saunası, havuzları ve huzurlu bahçeleriyle 20.000 metrekarelik devasa bir yaşam alanı.",
        "description_en": "A Bali-inspired oasis in the middle of Berlin. A massive 20,000 sqm wellness area with numerous saunas, pools, and peaceful gardens.",
        "imageUrl": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
        "bestTime": "Tam gün",
        "bestTime_en": "Full day",
        "tips": "Mekanda kıyafet kısıtlamaları (FKK - çıplaklık kültürü) olduğunu unutmayın, saunalarda bornoz kullanımı zorunludur.",
        "tips_en": "Be aware of the venue's clothing-optional (FKK) guidelines; bathrobes are mandatory outside the saunas."
    },
    {
        "name": "Computerspielemuseum",
        "name_en": "Computer Games Museum",
        "area": "Friedrichshain",
        "category": "Müze",
        "tags": ["oyun", "nostalji", "retro", "bilgisayar"],
        "distanceFromCenter": 3.0,
        "lat": 52.5178,
        "lng": 13.4420,
        "price": "medium",
        "rating": 4.5,
        "description": "60 yıllık dijital eğlence tarihini kapsayan, nadir oyun makinelerinden efsanevi konsollara kadar her şeyi barındıran nostaljik bir müze.",
        "description_en": "A nostalgic museum covering 60 years of digital entertainment history, featuring everything from rare arcade machines to legendary consoles.",
        "imageUrl": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Pek çok oyunu bizzat oynamanıza izin veriliyor, en sevdiğiniz retro oyunu burada bulabilirsiniz.",
        "tips_en": "You're allowed to play many of the games yourself; you're likely to find your favorite retro game here."
    },
    {
        "name": "David Bowie's Flat",
        "name_en": "David Bowie's Flat",
        "area": "Schöneberg",
        "category": "Tarihi",
        "tags": ["müzik", "sanat", "ikon", "bowie"],
        "distanceFromCenter": 4.5,
        "lat": 52.4862,
        "lng": 13.3514,
        "price": "free",
        "rating": 4.3,
        "description": "David Bowie'nin 1970'lerin sonunda ünlü Berlin üçlemesini hazırlarken yaşadığı apartman. Hayranları tarafından kapısının önüne sürekli çiçek bırakılır.",
        "description_en": "The apartment building where David Bowie lived in the late 1970s while creating his famous Berlin Trilogy. Fans often leave flowers at the doorstep.",
        "imageUrl": "https://images.unsplash.com/photo-1514595213605-72120db55060?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Binanın hemen yanındaki kafede oturup Bowie'nin buralarda yürüdüğünü hayal edebilirsiniz.",
        "tips_en": "You can sit in the cafe right next to the building and imagine Bowie walking these very streets."
    },
    {
        "name": "Savignyplatz",
        "name_en": "Savignyplatz",
        "area": "Charlottenburg",
        "category": "Tarihi",
        "tags": ["meydan", "kitapçı", "kafe", "burjuva"],
        "distanceFromCenter": 5.0,
        "lat": 52.5061,
        "lng": 13.3228,
        "price": "low",
        "rating": 4.6,
        "description": "Batı Berlin'in entelektüel merkezi. Etrafı seçkin kitapçılar, şık kafeler ve asırlık çınar ağaçlarıyla çevrili çok zarif bir meydan.",
        "description_en": "The intellectual heart of West Berlin. A very elegant square surrounded by select bookstores, chic cafes, and century-old planetrees.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "Meydandaki Bücherbogen kitapçısında sanat ve mimari üzerine harika eserler bulabilirsiniz.",
        "tips_en": "You can find great works on art and architecture at the Bücherbogen bookstore in the square."
    },
    {
        "name": "Körnerpark",
        "name_en": "Körnerpark",
        "area": "Neukölln",
        "category": "Park",
        "tags": ["bahçe", "neo-barok", "gizli", "huzur"],
        "distanceFromCenter": 6.5,
        "lat": 52.4720,
        "lng": 13.4365,
        "price": "free",
        "rating": 4.7,
        "description": "Bir kireç kuyusu üzerine inşa edilmiş, neo-barok tarzındaki bu gizli bahçe, su kanalları ve şık serasıyla Neukölln'ün ortasında bir masal diyarı.",
        "description_en": "Built on a former lime pit, this hidden Neo-Baroque garden is a fairytale spot in the middle of Neukölln with its canals and elegant greenhouse.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Yaz aylarında parkın içindeki galeride ve kafette ücretsiz açık hava konserleri düzenlenir.",
        "tips_en": "During the summer, the gallery and cafe in the park host free open-air concerts."
    },
    {
        "name": "Modulor",
        "name_en": "Modulor",
        "area": "Kreuzberg",
        "category": "Alışveriş",
        "tags": ["kırtasiye", "tasarım", "sanat", "malzeme"],
        "distanceFromCenter": 1.5,
        "lat": 52.5028,
        "lng": 13.4111,
        "price": "low",
        "rating": 4.8,
        "description": "Sanatçılar, mimarlar ve tasarım meraklıları için bir hac yeri. Binlerce çeşit kağıt, malzeme ve yaratıcı gereçle dolu devasa bir mağaza.",
        "description_en": "A pilgrimage site for artists, architects, and design enthusiasts. A massive store filled with thousands of types of paper, materials, and creative tools.",
        "imageUrl": "https://images.unsplash.com/photo-1544816153-12ad5d714304?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Moritzplatz durağının hemen önündeki bu binada sadece alışveriş yapmayıp atölyeleri de gezebilirsiniz.",
        "tips_en": "Located right at the Moritzplatz station, you can visit workshops here in addition to shopping."
    },
    {
        "name": "Dussmann das KulturKaufhaus",
        "name_en": "Dussmann",
        "area": "Mitte",
        "category": "Alışveriş",
        "tags": ["kitap", "plak", "müzik", "gece"],
        "distanceFromCenter": 0.5,
        "lat": 52.5186,
        "lng": 13.3891,
        "price": "low",
        "rating": 4.7,
        "description": "Gece geç saatlere kadar açık olan devasa bir kültür mağazası. Her dilden kitaplar, dev bir plak koleksiyonu ve huzurlu dikey bahçesiyle ünlü.",
        "description_en": "A massive culture store open late into the night, famous for its books in many languages, huge vinyl collection, and peaceful vertical garden.",
        "imageUrl": "https://images.unsplash.com/photo-1521587760476-6c12a71048ca?w=800",
        "bestTime": "Gece geç",
        "bestTime_en": "Late night",
        "tips": "İçeride Patrick Blanc tarafından tasarlanan muazzam dikey bahçeyi (Vertical Garden) mutlaka görün.",
        "tips_en": "Be sure to see the incredible vertical garden inside designed by Patrick Blanc."
    },
    {
        "name": "Schwarzes Café",
        "name_en": "Schwarzes Cafe",
        "area": "Charlottenburg",
        "category": "Kafe",
        "tags": ["tarihi", "bohem", "gece", "yemek"],
        "distanceFromCenter": 5.0,
        "lat": 52.5065,
        "lng": 13.3285,
        "price": "medium",
        "rating": 4.4,
        "description": "Pazartesi hariç 24 saat açık olmasıyla ünlü, Berlin'in bohem tarihini en iyi yansıtan, iki katlı otantik bir kafe-restoran.",
        "description_en": "Famous for being open 24 hours (except Mondays), an authentic two-story cafe-restaurant that perfectly captures Berlin's bohemian history.",
        "imageUrl": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Üst kattaki küçük balkonda oturup Kantstrasse'yi izlemek çok keyiflidir.",
        "tips_en": "Sitting on the small upstairs balcony and watching Kantstrasse is very enjoyable."
    },
    {
        "name": "Buck and Breck",
        "name_en": "Buck and Breck",
        "area": "Mitte",
        "category": "Bar",
        "tags": ["kokteyl", "gizli", "özel", "şık"],
        "distanceFromCenter": 1.0,
        "lat": 52.5312,
        "lng": 13.4022,
        "price": "high",
        "rating": 4.6,
        "description": "Bir polis karakolunun yanındaki gizli bir kapının arkasında yer alan, dünyanın en iyi barları listesine giren çok özel bir kokteyl barı.",
        "description_en": "A very exclusive cocktail bar located behind a hidden door next to a police station, consistently ranked among the best bars in the world.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Mekan çok küçük (sadece tek bir masa var) ve fotoğraf çekmek yasak, rezervasyon şart.",
        "tips_en": "The venue is tiny (there's only one main table) and photography is forbidden; booking is essential."
    },
    {
        "name": "Bar Tausend",
        "name_en": "Bar Tausend",
        "area": "Mitte",
        "category": "Bar",
        "tags": ["gizli", "lüks", "müzik", "gece"],
        "distanceFromCenter": 0.8,
        "lat": 52.5205,
        "lng": 13.3891,
        "price": "high",
        "rating": 4.3,
        "description": "Friedrichstrasse üzerindeki bir demiryolu köprüsünün altındaki isimsiz bir çelik kapının ardındaki çok şık ve havalı speakeasy bar.",
        "description_en": "A very chic and cool speakeasy bar hidden behind an unmarked steel door under a railway bridge on Friedrichstrasse.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Kapıdaki zili basın ve içeri girebilmek için şık giyinmeye özen gösterin.",
        "tips_en": "Ring the bell at the door and make sure to dress elegantly to gain entry."
    },
    {
        "name": "Schlachtensee",
        "name_en": "Schlachtensee",
        "area": "Zehlendorf",
        "category": "Manzara",
        "tags": ["göl", "orman", "yüzme", "doğa"],
        "distanceFromCenter": 15.0,
        "lat": 52.4420,
        "lng": 13.2140,
        "price": "free",
        "rating": 4.8,
        "description": "Berlin'in en temiz ve en güzel göllerinden biri. Çevresi devasa ağaçlarla kaplı orman yoluyla çevrilidir; yürüyüş ve yüzme için ideal.",
        "description_en": "One of Berlin's cleanest and most beautiful lakes, surrounded by a forested path with giant trees; ideal for walking and swimming.",
        "imageUrl": "https://images.unsplash.com/photo-1444464666168-49d633b867ad?w=800",
        "bestTime": "Yaz günü",
        "bestTime_en": "Summer day",
        "tips": "Göl kenarındaki tarihi balıkçı evi Fischerhütte'de biralarınızı yudumlayabilirsiniz.",
        "tips_en": "You can enjoy beers at the Fischerhütte, a historic fisherman's lodge by the lake."
    },
    {
        "name": "Pfaueninsel",
        "name_en": "Peacock Island",
        "area": "Wannsee",
        "category": "Park",
        "tags": ["ada", "şato", "tavus kuşu", "UNESCO"],
        "distanceFromCenter": 18.0,
        "lat": 52.4349,
        "lng": 13.1265,
        "price": "low",
        "rating": 4.6,
        "description": "Wannsee üzerinde, içinde serbestçe dolaşan tavus kuşları ve masalsı bir beyaz şatosu olan UNESCO listesindeki doğa koruma alanı.",
        "description_en": "A UNESCO-listed nature reserve on Wannsee, featuring freely roaming peacocks and a fairytale white castle.",
        "imageUrl": "https://images.unsplash.com/photo-1598449419142-2d1033069315?w=800",
        "bestTime": "Bahar",
        "bestTime_en": "Spring",
        "tips": "Adaya sadece küçük bir feribotla geçiliyor, bisiklet veya evcil hayvan yasak.",
        "tips_en": "The island is only accessible by a small ferry; bicycles and pets are not allowed."
    },
    {
        "name": "Heilandskirche Sacrow",
        "name_en": "Heilandskirche Sacrow",
        "area": "Potsdam / Sacrow",
        "category": "Tarihi",
        "tags": ["kilise", "nehir", "mimari", "romantik"],
        "distanceFromCenter": 20.0,
        "lat": 52.4247,
        "lng": 13.0965,
        "price": "free",
        "rating": 4.8,
        "description": "Havel Nehri kıyısında, suyun hemen üstünde duran muhteşem bir İtalyan tarzı bazilika. Berlin Duvarı zamanında ulaşılamaz bir 'ölüm şeridinde' kalmıştı.",
        "description_en": "A magnificent Italian-style basilica standing right over the Havel River. During the Berlin Wall era, it was trapped in the inaccessible 'death strip'.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Nehir kenarından kilisenin manzarası özellikle altın saatlerde (golden hour) büyüleyicidir.",
        "tips_en": "The view of the church from the riverside is particularly enchanting during the golden hour."
    },
    {
        "name": "Andreas Murkudis",
        "name_en": "Andreas Murkudis",
        "area": "Schöneberg",
        "category": "Alışveriş",
        "tags": ["moda", "tasarım", "konsept", "lüks"],
        "distanceFromCenter": 3.0,
        "lat": 52.5065,
        "lng": 13.3615,
        "price": "high",
        "rating": 4.5,
        "description": "Berlin'in en prestijli konsept mağazası. Eski bir gazete binasının devasa galerisinde yer alan, giyimden mobilyaya en seçkin tasarımların sergilendiği bir alan.",
        "description_en": "Berlin's most prestigious concept store, set in the massive gallery of a former newspaper building and showcasing elite designs from fashion to furniture.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Mağaza içi düzenleme o kadar minimal ve şıktır ki kendinizi bir sanat galerisinde gibi hissedersiniz.",
        "tips_en": "The interior layout is so minimal and chic you'll feel like you're in an art gallery."
    },
    {
        "name": "Yaam",
        "name_en": "Yaam",
        "area": "Friedrichshain",
        "category": "Deneyim",
        "tags": ["plaj", "reggae", "alternatif", "bar"],
        "distanceFromCenter": 2.2,
        "lat": 52.5100,
        "lng": 13.4350,
        "price": "low",
        "rating": 4.1,
        "description": "Young African Art Market (YAAM), Spree Nehri kıyısında kumlu plajları, Karayip yemekleri ve reggae müziğiyle Berlin'in en renkli ve özgür yeri.",
        "description_en": "Young African Art Market (YAAM) is Berlin's most colorful and liberal spot, featuring sandy beaches, Caribbean food, and reggae music by the Spree.",
        "imageUrl": "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800",
        "bestTime": "Yaz öğleden sonra",
        "bestTime_en": "Summer afternoon",
        "tips": "Afrika mutfağından lezzetler deneyip nehir kenarında basketbol oynayanları izleyebilirsiniz.",
        "tips_en": "Try African food and watch people play basketball by the river."
    },
    {
        "name": "Ramones Museum",
        "name_en": "Ramones Museum",
        "area": "Friedrichshain",
        "category": "Müze",
        "tags": ["müzik", "punk", "rock", "sergi"],
        "distanceFromCenter": 3.5,
        "lat": 52.5298,
        "lng": 13.3888,
        "price": "low",
        "rating": 4.6,
        "description": "Dünyanın tek Ramones müzesi. Efsanevi punk grubunun binlerce parçalık anısı ve eşyası küçük ama samimi bir kafede sergileniyor.",
        "description_en": "The world's only Ramones museum. Personal effects and memorabilia from the legendary punk band are on display in a cozy cafe-museum.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee8718a300c?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Bilet yerine geçen bir pin alıyorsunuz ve bu pin size ömür boyu giriş sağlıyor.",
        "tips_en": "You buy a pin that serves as your ticket, giving you lifetime entry to the museum."
    },
    {
        "name": "C/O Berlin",
        "name_en": "C/O Berlin",
        "area": "Charlottenburg",
        "category": "Müze",
        "tags": ["fotoğraf", "sanat", "galeri", "modern"],
        "distanceFromCenter": 4.2,
        "lat": 52.5067,
        "lng": 13.3306,
        "price": "medium",
        "rating": 4.7,
        "description": "Uluslararası düzeyde tanınmış bir fotoğraf galerisi. Hem efsanevi fotoğrafçıların hem de yetenekli genç sanatçıların sergilerine ev sahipliği yapar.",
        "description_en": "An internationally acclaimed photography gallery, hosting exhibitions by both legendary photographers and talented emerging artists.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "Hayvanat bahçesi durağının hemen yanındaki bu galeriyi gezdikten sonra çevredeki kitapçılara uğrayabilirsiniz.",
        "tips_en": "Visit this gallery next to the Zoo station, then explore the nearby bookstores."
    },
    {
        "name": "Berlin Story Bunker",
        "name_en": "Berlin Story Bunker",
        "area": "Mitte",
        "category": "Müze",
        "tags": ["hitler", "tarih", "bunker", "soğuk savaş"],
        "distanceFromCenter": 1.2,
        "lat": 52.5050,
        "lng": 13.3815,
        "price": "medium",
        "rating": 4.5,
        "description": "II. Dünya Savaşı'ndan kalma devasa bir sığınakta yer alan müze. Özellikle 'Hitler - How could it happen' sergisiyle şehrin karanlık tarihine ışık tutuyor.",
        "description_en": "A museum in a massive WWII bunker. It sheds light on the city's dark history, particularly through its 'Hitler - How could it happen' exhibition.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sergi çok detaylı olduğu için en az 2-3 saat ayırmanız önerilir.",
        "tips_en": "The exhibition is very detailed, so allow at least 2-3 hours for your visit."
    },
    {
        "name": "Stasi Museum",
        "name_en": "Stasi Museum",
        "area": "Lichtenberg",
        "category": "Müze",
        "tags": ["DDR", "casus", "tarih", "soğuk savaş"],
        "distanceFromCenter": 5.5,
        "lat": 52.5145,
        "lng": 13.4875,
        "price": "medium",
        "rating": 4.6,
        "description": "Eski Doğu Alman Gizli Polisi'nin (Stasi) gerçek karargahı. Erich Mielke'nin ofisi olduğu gibi korunmuştur; gerçek casusluk yöntemlerini görebilirsiniz.",
        "description_en": "The actual headquarters of the former East German Secret Police (Stasi). Erich Mielke's office is preserved as it was, showcasing real espionage methods.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Müze kentin biraz dışında ama gerçek tarihe dokunmak isteyenler için kesinlikle gidilmeye değer.",
        "tips_en": "The museum is slightly outside the city center but well worth the trip for those wanting to touch real history."
    },
    {
        "name": "Botanischer Garten",
        "name_en": "Botanical Garden",
        "area": "Steglitz / Dahlem",
        "category": "Park",
        "tags": ["botanik", "sera", "doğa", "yürüyüş"],
        "distanceFromCenter": 8.5,
        "lat": 52.4544,
        "lng": 13.3055,
        "price": "medium",
        "rating": 4.7,
        "description": "Dünyanın en büyük ve en önemli botanik bahçelerinden biri. Dev cam seraları, tropik bitkileri ve devasa açık hava bahçeleriyle huzur dolu.",
        "description_en": "One of the world's largest and most important botanical gardens. A peaceful site with giant glasshouses, tropical plants, and vast outdoor gardens.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Art Nouveau tarzındaki ana büyük sera (Große Tropenhaus) mimari açıdan muazzamdır.",
        "tips_en": "The Art Nouveau-style Grand Pavilion (Große Tropenhaus) is an architectural marvel."
    },
    {
        "name": "Molecule Man",
        "name_en": "Molecule Man",
        "area": "Treptow",
        "category": "Manzara",
        "tags": ["heykel", "nehir", "sanat", "ikonik"],
        "distanceFromCenter": 4.5,
        "lat": 52.4970,
        "lng": 13.4591,
        "price": "free",
        "rating": 4.5,
        "description": "Spree Nehri üzerinde yükselen, Jonathan Borofsky tarafından yapılan 30 metre boyundaki üç dev delikli metal heykel.",
        "description_en": "Three 30-meter-tall perforated aluminum figures by Jonathan Borofsky, rising out of the Spree River.",
        "imageUrl": "https://images.unsplash.com/photo-1552566626-dca3f37494cc1?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Köprü üzerinden veya nehir turları sırasında en iyi fotoğraf açılarını yakalayabilirsiniz.",
        "tips_en": "The best photo angles are from the bridge or during a river cruise."
    },
    {
        "name": "HKW Berlin",
        "name_en": "HKW Berlin",
        "area": "Mitte / Tiergarten",
        "category": "Deneyim",
        "tags": ["sanat", "kültür", "mimari", "nehir"],
        "distanceFromCenter": 1.5,
        "lat": 52.5186,
        "lng": 13.3615,
        "price": "low",
        "rating": 4.6,
        "description": "Haus der Kulturen der Welt, ilginç mimarisi (İstiridye kabuğu gibi) ve çağdaş sanat sergileriyle nehir kenarında şık bir kültür merkezi.",
        "description_en": "Haus der Kulturen der Welt is an elegant riverside cultural center known for its striking 'oyster shell' architecture and contemporary art exhibitions.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Nehir kenarındaki teras kafesinde oturup Spree'yi izlemek çok keyiflidir.",
        "tips_en": "Sitting in the riverside terrace cafe and watching the Spree is very pleasant."
    },
    {
        "name": "Humboldthain Flak Tower",
        "name_en": "Humboldthain Flak Tower",
        "area": "Wedding",
        "category": "Manzara",
        "tags": ["bunker", "manzara", "tarih", "grafiti"],
        "distanceFromCenter": 4.0,
        "lat": 52.5445,
        "lng": 13.3850,
        "price": "free",
        "rating": 4.7,
        "description": "II. Dünya Savaşı'ndan kalma devasa bir uçaksavar kulesinin kalıntıları. Şimdi parkın içinde bir tepe ve Berlin-Kuzey manzarası için harika bir nokta.",
        "description_en": "The remains of a massive WWII anti-aircraft tower, now a hill within a park and a great spot for views across North Berlin.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Yaz aylarında buralarda düzenlenen rehberli yeraltı turlarına katılabilirsiniz.",
        "tips_en": "In summer, you can join guided underground tours organized here."
    },
    {
        "name": "Park am Gleisdreieck",
        "name_en": "Park am Gleisdreieck",
        "area": "Kreuzberg / Schöneberg",
        "category": "Park",
        "tags": ["modern", "kaykay", "spor", "yürüyüş"],
        "distanceFromCenter": 2.0,
        "lat": 52.4969,
        "lng": 13.3738,
        "price": "free",
        "rating": 4.7,
        "description": "Eski bir demiryolu kavşağının üzerine inşa edilmiş ödüllü modern park. Kaykay pistleri, spor alanları ve geniş yürüyüş yollarıyla çok popüler.",
        "description_en": "An award-winning modern park built over former railway junctions. Very popular for its skate parks, sports areas, and wide walking paths.",
        "imageUrl": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Pazar günleri buradaki Birlot kraft bira fabrikasına uğrayabilirsiniz.",
        "tips_en": "On Sundays, you can visit the Birlot craft brewery located within the park."
    },
    {
        "name": "Klunkerkranich",
        "name_en": "Klunkerkranich",
        "area": "Neukölln",
        "category": "Bar",
        "tags": ["rooftop", "manzara", "alternatif", "gün batımı"],
        "distanceFromCenter": 5.0,
        "lat": 52.4823,
        "lng": 13.4319,
        "price": "low",
        "rating": 4.6,
        "description": "Neukölln Arkaden AVM'sinin otopark çatı katında yer alan, meyve bahçeleri ve DJ performanslarıyla dolu alternatif bir rooftop bar.",
        "description_en": "An alternative rooftop bar located on the parking deck of the Neukölln Arkaden mall, featuring fruit gardens and DJ performances.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Giriş için AVM içinden asansörle 5. kata çıkıp otopark rampasını yürüyerek en tepeye ulaşın.",
        "tips_en": "To enter, take the mall elevator to the 5th floor and then walk up the parking ramp to the very top."
    }
]

def enrich_berlin_batch2():
    filepath = 'assets/cities/berlin.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_berlin_batch2:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_berlin_batch2()
print(f"Berlin now has {count} highlights.")
