import json
import os

new_bangkok_batch2 = [
    {
        "name": "Wat Phra Kaew (Emerald Buddha)",
        "name_en": "Temple of the Emerald Buddha",
        "area": "Grand Palace",
        "category": "Tarihi",
        "tags": ["saray", "tapınak", "zümrüt buda", "kutsal"],
        "distanceFromCenter": 0.1,
        "lat": 13.7514,
        "lng": 100.4925,
        "price": "high",
        "rating": 4.9,
        "description": "Tayland'ın en kutsal tapınağı. Tek bir yeşim taşından oyulmuş Zümrüt Buda heykeli burada yer alır. Görkemli mimarisiyle büyüleyicidir.",
        "description_en": "The most sacred Buddhist temple in Thailand, housing the meticulously carved Emerald Buddha, the palladium of Thai society.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "Grand Palace bileti burayı da kapsar. Kıyafet kodu çok katıdır.",
        "tips_en": "Included with the Grand Palace entrance ticket. Strict dress code applies."
    },
    {
        "name": "Khlong Lat Mayom Floating Market",
        "name_en": "Khlong Lat Mayom",
        "area": "Taling Chan",
        "category": "Deneyim",
        "tags": ["yüzen pazar", "lokal", "yemek", "nehir"],
        "distanceFromCenter": 12.0,
        "lat": 13.7619,
        "lng": 100.4156,
        "price": "low",
        "rating": 4.6,
        "description": "Turistik kalabalıktan uzak, yerli halkın hafta sonu favorisi olan gerçek bir yüzen pazar. Olağanüstü sokak yemekleri bulabilirsiniz.",
        "description_en": "A charming and authentic floating market popular with locals. Offers some of the best and most diverse food options on the outskirts of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Cumartesi/Pazar 10:00 - 14:00",
        "bestTime_en": "Saturday/Sunday 10:00 AM - 2:00 PM",
        "tips": "Fırınlanmış dev karidesleri ve nehir levreğini mutlaka tadın.",
        "tips_en": "Try the salt-crusted grilled fish and the jumbo river prawns."
    },
    {
        "name": "Samsen Nai (Craft Beer Scene)",
        "name_en": "Samsen Nai Neighborhood",
        "area": "Phaya Thai",
        "category": "Bar",
        "tags": ["butik bira", "lokal", "trendy", "gece hayatı"],
        "distanceFromCenter": 6.0,
        "lat": 13.7797,
        "lng": 100.5446,
        "price": "medium",
        "rating": 4.5,
        "description": "Bangkok'un butik bira kültürünün kalbi. Ari bölgesine yakın bu mahalle, yerli üretim biralar sunan küçük butik barlarla dolu.",
        "description_en": "A rising star of Bangkok's craft beer scene, featuring numerous small, independent bars serving locally brewed craft beers.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Özellikle hafta sonları çok canlı olur, bar gezintisi için idealdir.",
        "tips_en": "Perfect for a bar-hopping experience, especially on Friday and Saturday nights."
    },
    {
        "name": "Wat Traimit (Golden Buddha)",
        "name_en": "Temple of Golden Buddha",
        "area": "Chinatown",
        "category": "Tarihi",
        "tags": ["altın", "buda", "tapınak", "paha biçilemez"],
        "distanceFromCenter": 2.2,
        "lat": 13.7376,
        "lng": 100.5135,
        "price": "low",
        "rating": 4.7,
        "description": "5.5 ton ağırlığında, saf altından yapılmış dünyanın en büyük Buda heykeline ev sahipliği yapan tapınak.",
        "description_en": "Houses the world's largest solid gold Buddha statue, weighing an incredible 5.5 tons and dating back to the 13th century.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Heykelin asıl kimliği 1950'lerde üzerine kaplanan alçı çatlayınca ortaya çıkmıştır, müzesini de gezin.",
        "tips_en": "The statue's gold identity was rediscovered in the 50s when it accidentally fell and the surrounding plaster cracked."
    },
    {
        "name": "Queen Sirikit Park",
        "name_en": "Queen Sirikit Park",
        "area": "Chatuchak",
        "category": "Park",
        "tags": ["bahçe", "botanik", "sessiz", "doğa"],
        "distanceFromCenter": 10.0,
        "lat": 13.8052,
        "lng": 100.5501,
        "price": "free",
        "rating": 4.6,
        "description": "Chatuchak pazarının gürültüsünden kaçmak için mükemmel bir botanik bahçesi. Her mevsim farklı çiçekler açar.",
        "description_en": "A beautifully manicured botanical park next to Chatuchak Market, offering a quiet escape with diverse plant species and fountains.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Sabah veya Geç öğleden sonra",
        "bestTime_en": "Morning or late afternoon",
        "tips": "Pazarın hemen yanındaki diğer park (Vachirabenjathat) ile karıştırmayın, burası daha sessiz ve özenlidir.",
        "tips_en": "Much quieter than the neighboring Rod Fai park, ideal for plant lovers and flower enthusiasts."
    },
    {
        "name": "National Museum Bangkok",
        "name_en": "National Museum",
        "area": "Old City",
        "category": "Müze",
        "tags": ["tarih", "sanat", "saray", "kültür"],
        "distanceFromCenter": 1.0,
        "lat": 13.7545,
        "lng": 100.4887,
        "price": "medium",
        "rating": 4.6,
        "description": "Güneydoğu Asya'nın en büyük müzelerinden biri. Eski bir saray kompleksinde Tayland'ın binlerce yıllık tarihini keşfedin.",
        "description_en": "One of Southeast Asia's largest museums, showcasing a comprehensive collection of Thai art and artifacts in a former 18th-century palace.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Çarşamba ve Perşembe sabahları ücretsiz İngilizce rehberli turlar düzenlenir.",
        "tips_en": "Join the free English-language guided tours held on Wednesday and Thursday mornings (usually at 9:30 AM)."
    },
    {
        "name": "Paste Bangkok (Michelin Star)",
        "name_en": "Paste Restaurant",
        "area": "Siam/Ratchaprasong",
        "category": "Restoran",
        "tags": ["fine dining", "lezzet", "lüks", "tay mutfağı"],
        "distanceFromCenter": 2.5,
        "lat": 13.7441,
        "lng": 100.5406,
        "price": "high",
        "rating": 4.7,
        "description": "Antik Tay yemek tariflerini modern sunumlarla birleştiren Michelin yıldızlı bir gastronomi deneyimi.",
        "description_en": "A Michelin-starred restaurant redefining traditional Thai recipes with modern techniques and stunning artistic presentations.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Gaysorn Village alışveriş merkezinin içindedir, tadım menüleri inanılmazdır.",
        "tips_en": "Located within Gaysorn Village; their tasting menus are a journey through refined Thai flavors."
    },
    {
        "name": "Sorn Bangkok (Two Michelin Stars)",
        "name_en": "Sorn",
        "area": "Sukhumvit",
        "category": "Restoran",
        "tags": ["güney tay mutfağı", "fine dining", "özel", "michelin"],
        "distanceFromCenter": 6.0,
        "lat": 13.7259,
        "lng": 100.5744,
        "price": "high",
        "rating": 4.9,
        "description": "Güney Tayland mutfağının en üst düzey temsilcisi. İki Michelin yıldızlı, rezervasyonun imkansız olduğu efsanevi restoran.",
        "description_en": "A legendary two-Michelin-starred restaurant specializing in southern Thai cuisine using traditional charcoal techniques and local ingredients.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Özel akşam",
        "bestTime_en": "Special Dinner",
        "tips": "Rezervasyonlar her ayın başında açılır ve saniyeler içinde tükenir.",
        "tips_en": "Booking is notoriously difficult; applications open at the start of the month for the following month."
    },
    {
        "name": "Ba Hao (Yao Bar & Chinese Eats)",
        "name_en": "Ba Hao",
        "area": "Chinatown",
        "category": "Bar",
        "tags": ["speakeasy", "bağımlılık", "çin stili", "kokteyl"],
        "distanceFromCenter": 2.2,
        "lat": 13.7380,
        "lng": 100.5110,
        "price": "medium",
        "rating": 4.6,
        "description": "Chinatown'un en şık barlarından biri. Eski bir Çin evinin retro-cool bir speakeasy bara dönüştürülmüş hali.",
        "description_en": "A super-cool Chinese-themed speakeasy bar in an old shophouse, offering creative cocktails and elevated Chinese bar food.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Özellikle Çin tıbbından ilham alan kokteyllerini mutlaka deneyin.",
        "tips_en": "Try their cocktails inspired by Chinese traditional medicine and herbs."
    },
    {
        "name": "Bamboo Bar (The Mandarin Oriental)",
        "name_en": "The Bamboo Bar",
        "area": "Riverside",
        "category": "Bar",
        "tags": ["caz", "tarihi", "kokteyl", "efsanevi"],
        "distanceFromCenter": 3.5,
        "lat": 13.7235,
        "lng": 100.5140,
        "price": "high",
        "rating": 4.8,
        "description": "Tayland'ın en eski ve en iyi caz barı. Mandarin Oriental otelinin içinde, aristokratik bir hava taşıyan, ödüllü bir mekan.",
        "description_en": "Thailand's oldest and most prestigious jazz bar, offering world-class cocktails and live jazz in a sophisticated, colonial-style setting.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam (Caz müziği varken)",
        "bestTime_en": "Evening (During live jazz)",
        "tips": "Kıyafet kodu geçerlidir (Smart casual), lüks bir deneyim için idealdir.",
        "tips_en": "Proper attire is required; expect a high-end experience and impeccable service."
    },
    {
        "name": "Iron Fairies (Dragonfly)",
        "name_en": "The Iron Fairies",
        "area": "Phrom Phong",
        "category": "Bar",
        "tags": ["steampunk", "canlı müzik", "karakteristik", "burgers"],
        "distanceFromCenter": 6.5,
        "lat": 13.7290,
        "lng": 100.5700,
        "price": "high",
        "rating": 4.6,
        "description": "Bir demir atölyesi gibi tasarlanmış, büyülü ve steampunk bir atmosfere sahip, harika burgerler ve canlı müzik sunan eşsiz bir bar.",
        "description_en": "A magical, Victorian steampunk-themed bar that looks like an old iron foundry, famous for its intense design, jazz, and fantastic burgers.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Küçük peri tozları ve demir heykellerle dolu rafları incelemekten kendinizi alamayacaksınız.",
        "tips_en": "Explore the multi-level space filled with tiny iron fairy statues; the attention to detail is mind-blowing."
    },
    {
        "name": "Sing Sing Theater",
        "name_en": "Sing Sing Theater",
        "area": "Phrom Phong",
        "category": "Bar",
        "tags": ["gece kulübü", "tasarım", "uzak doğu", "party"],
        "distanceFromCenter": 6.0,
        "lat": 13.7285,
        "lng": 100.5705,
        "price": "high",
        "rating": 4.5,
        "description": "Eski bir Çin tiyatrosu konseptiyle tasarlanmış, Bangkok'un en şık ve görsel olarak büyüleyici gece kulüplerinden biri.",
        "description_en": "A visually stunning nightclub designed like a futuristic Chinese theater, featuring intricate woodwork, birdcages, and high-energy electronic music.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Gece yarısı",
        "bestTime_en": "Midnight",
        "tips": "Tasarım detayları her köşede sizi şaşırtacak, fotoğrafçılar için rüya gibi bir mekan.",
        "tips_en": "The incredible lighting and decor make it a paradise for photographers during the early hours."
    },
    {
        "name": "Klong Tours (Khlong Saen Saep)",
        "name_en": "Canal Boat Ride",
        "area": "City Center",
        "category": "Deneyim",
        "tags": ["tekne", "ulaşım", "lokal", "hızlı"],
        "distanceFromCenter": 1.0,
        "lat": 13.7480,
        "lng": 100.5350,
        "price": "low",
        "rating": 4.3,
        "description": "Turistik olmayan, gerçek bir yerel deneyim. Bangkok kanallarında hızla süzülen teknelerle şehri bir uçtan bir uca uygun fiyata geçin.",
        "description_en": "A thrilling and authentic local commute through Bangkok's canal system, far away from the tourist crowds and very budget-friendly.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Hafta içi sabah veya akşamüzeri",
        "bestTime_en": "Weekday rush hour (for the vibe)",
        "tips": "Duraklarda inerken ve binerken çok hızlı olmalısınız, sular sıçrayabilir ama çok eğlencelidir.",
        "tips_en": "Be quick when boarding and jumping off at stops; it's fast-paced and truly Local (careful of the canal water splash!)."
    },
    {
        "name": "Ekkamai Neighborhood (Coffee & Vintage)",
        "name_en": "Ekkamai Neighborhood",
        "area": "Sukhumvit",
        "category": "Deneyim",
        "tags": ["vintage", "kafe", "plak dükkanı", "hipster"],
        "distanceFromCenter": 8.0,
        "lat": 13.7215,
        "lng": 100.5847,
        "price": "medium",
        "rating": 4.6,
        "description": "Bangkok'un hipster kalbi. Vintage giyim dükkanları, plakçılar ve sofistike kahve kavurma atölyeleriyle dolu bir mahalle.",
        "description_en": "The hipster heart of Sukhumvit, known for its curated vintage shops, record stores, and high-end specialty coffee roasters.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Gizli avlulardaki plak dükkanlarını bulmak için yan sokakları mutlaka keşfedin.",
        "tips_en": "Explore the hidden backsois for the best independent record and design shops."
    },
    {
        "name": "Wichit Mukda (Amulet Market)",
        "name_en": "Amulet Market",
        "area": "Old City",
        "category": "Deneyim",
        "tags": ["muska", "mistik", "budizm", "tarihi market"],
        "distanceFromCenter": 0.5,
        "lat": 13.7540,
        "lng": 100.4890,
        "price": "low",
        "rating": 4.2,
        "description": "Binlerce farklı büyüklükte tılsım ve muskanın satıldığı, Bangkok'un en mistik ve en yaşlı pazarlarından biri.",
        "description_en": "A fascinating riverside market where thousands of sacred Buddhist amulets, talismans, and charms are traded by collectors and practitioners.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yerlilerin ellerinde büyüteçlerle küçük muskaları saatlerce incelemesini izlemek benzersiz bir kültürel deneyimdir.",
        "tips_en": "Watch the experts use magnifying glasses to inspect tiny details; value is in the perceived spiritual power."
    },
    {
        "name": "Museum Siam (Interactive)",
        "name_en": "Museum Siam",
        "area": "Old City",
        "category": "Müze",
        "tags": ["interaktif", "tay kültürü", "eğitici", "modern"],
        "distanceFromCenter": 1.0,
        "lat": 13.7442,
        "lng": 100.4940,
        "price": "medium",
        "rating": 4.5,
        "description": "Geleneksel müzelerden sıkılanlar için. 'Tay olmak ne demektir?' sorusunu interaktif ve eğlenceli bir şekilde cevaplayan bir merkez.",
        "description_en": "A highly interactive museum exploring the concept of 'Thainess' through creative digital displays and engaging storytelling.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Wat Pho'dan sadece 10 dakika yürüme mesafesindedir, çocuklar için de harikadır.",
        "tips_en": "Only a short walk from Wat Pho, and incredibly engaging for children and adults alike."
    },
    {
        "name": "Patpong Night Market",
        "name_en": "Patpong Market",
        "area": "Silom",
        "category": "Alışveriş",
        "tags": ["gece pazarı", "kopya ürün", "silom", "turistik"],
        "distanceFromCenter": 3.0,
        "lat": 13.7290,
        "lng": 100.5315,
        "price": "medium",
        "rating": 3.6,
        "description": "Bangkok'un en meşhur ama aynı zamanda en karmaşık gece pazarı. Kopya saatlerden tekstil ürünlerine kadar her şeyi bulabilirsiniz.",
        "description_en": "One of Bangkok's oldest night markets, located in the middle of a famous nightlife district, focused on souvenirs and copy products.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gece (21:00 - 24:00)",
        "bestTime_en": "Night (9:00 PM - Midnight)",
        "tips": "Pazarlık burada bir kuraldır, söylenen fiyatın en az yarısıyla başlayın.",
        "tips_en": "Haggling is mandatory; beware of the nearby entertainment scams if you're not a seasoned traveler."
    },
    {
        "name": "Thip Samai (Pad Thai Original)",
        "name_en": "Thip Samai Pad Thai",
        "area": "Old City",
        "category": "Restoran",
        "tags": ["pad thai", "efsanevi", "yemek", "favori"],
        "distanceFromCenter": 1.5,
        "lat": 13.7533,
        "lng": 100.5011,
        "price": "low",
        "rating": 4.4,
        "description": "Tayland'ın en iyi Pad Thai'sini yaptığı söylenen, her zaman önünde uzun kuyruklar olan tarihi bir lokanta.",
        "description_en": "Widely known as the best place for Pad Thai in Thailand. Served in a signature paper thin egg wrap to lock in the flavor.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meşhur taze sıkılmış portakal sularını Pad Thai ile mutlaka birlikte sipariş edin.",
        "tips_en": "Their fresh orange juice is equally famous and worth the premium price to pair with your noodles."
    },
    {
        "name": "Bangkok City Library",
        "name_en": "Bangkok City Library",
        "area": "Old City",
        "category": "Deneyim",
        "tags": ["kütüphane", "modern", "mimari", "sakinlık"],
        "distanceFromCenter": 1.2,
        "lat": 13.7570,
        "lng": 100.4990,
        "price": "free",
        "rating": 4.7,
        "description": "Old City'nin kalbinde, modern ve devasa bir kütüphane. Sıcak Bangkok havasından kaçıp sessiz bir mola vermek için mükemmel.",
        "description_en": "A multi-story modern public library in a grand heritage building, offering a serene environment and cool air away from the city heat.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kütüphaneye girmek için pasaportunuzu (veya fotokopisini) göstermeniz gerekebilir.",
        "tips_en": "You may need to show ID (passport or copy) to register for temporary access at the door."
    },
    {
        "name": "Siam Discovery (Design Mall)",
        "name_en": "Siam Discovery",
        "area": "Siam",
        "category": "Alışveriş",
        "tags": ["tasarım", "konsept", "lüks", "mimari"],
        "distanceFromCenter": 2.2,
        "lat": 13.7465,
        "lng": 100.5310,
        "price": "high",
        "rating": 4.7,
        "description": "Alışılagelmiş AVM'lerden farklı, her katı devasa bir sanat enstalasyonu gibi tasarlanmış yüksek tasarım ürünleri merkezi.",
        "description_en": "A uniquely designed 'concept mall' where products are displayed in lifestyle labs rather than individual shops.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gün içi",
        "bestTime_en": "Daytime",
        "tips": "Nendo tarafından tasarlanan iç mimarisi tek başına görülmeye değerdir.",
        "tips_en": "The interior by Japanese design studio Nendo is an architectural masterpiece explore every level."
    },
    {
        "name": "Sky Bar (Lebua State Tower)",
        "name_en": "Lebua Sky Bar",
        "area": "Silom",
        "category": "Bar",
        "tags": ["hangover", "manzara", "lüks", "rooftop"],
        "distanceFromCenter": 3.0,
        "lat": 13.7214,
        "lng": 100.5167,
        "price": "high",
        "rating": 4.5,
        "description": "'The Hangover 2' filmiyle ünlenen, Bangkok'un en yüksek ve en ikonik (ve pahalı) rooftop barlarından biri.",
        "description_en": "One of the highest rooftop bars in the world, made globally famous by the movie 'The Hangover Part II' it offers vertiginous river views.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Fiyatlar çok yüksektir ve kıyafet kuralı çok katıdır (Şort, parmak arası terlik yasak).",
        "tips_en": "Be prepared for high prices and a very strict dress code; reservations are highly recommended."
    },
    {
        "name": "Vertigo & Moon Bar (Banyan Tree)",
        "name_en": "Vertigo Moon Bar",
        "area": "Sathorn",
        "category": "Bar",
        "tags": ["rooftop", "manzara", "silom", "lüks"],
        "distanceFromCenter": 3.2,
        "lat": 13.7237,
        "lng": 100.5398,
        "price": "high",
        "rating": 4.7,
        "description": "Bir gemi güvertesi gibi tasarlanmış, 61. katta uç uçaymış hissi veren büyüleyici bir manzara noktası.",
        "description_en": "Located on the 61st floor, this open-air bar and restaurant feels like an ocean liner adrift in the clouds above Sathorn.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Mavi saat (Gün batımı sonrası)",
        "bestTime_en": "The Blue Hour (Post-sunset)",
        "tips": "Moon Bar'da bir içecek alıp manzarayı izlemek, 360 derece şehir ışıklarını görmek için en iyi yoldur.",
        "tips_en": "Arrive early if you want a seat; it gets very packed due to its reputation for one of the city's cleanest panoramas."
    },
    {
        "name": "Baan Silapin (Artist's House)",
        "name_en": "Artist's House",
        "area": "Thonburi",
        "category": "Deneyim",
        "tags": ["kukla şovu", "geleneksel", "nehir", "sanat"],
        "distanceFromCenter": 10.0,
        "lat": 13.7314,
        "lng": 100.4635,
        "price": "low",
        "rating": 4.7,
        "description": "200 yıllık bir nehir evinde yer alan, gelenetsek Tay kukla şovlarını izleyebileceğiniz gizli bir sanatçı topluluğu evi.",
        "description_en": "A 200-year-old traditional Thai house converted into a community art space and gallery for traditional puppet shows.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra 14:00 (Kukla şovu saatleri)",
        "bestTime_en": "Afternoon around 2 PM (for the puppet show)",
        "tips": "Kukla şovları her gün olmayabilir, gitmeden önce takvimi kontrol edin.",
        "tips_en": "The puppet shows are based on volunteers and don't occur every day; check the local schedule first."
    },
    {
        "name": "Museum of Floral Culture",
        "name_en": "Floral Culture Museum",
        "area": "Dusit",
        "category": "Müze",
        "tags": ["çiçek", "bahçe", "tarihi ev", "huzur"],
        "distanceFromCenter": 4.5,
        "lat": 13.7850,
        "lng": 100.5120,
        "price": "medium",
        "rating": 4.8,
        "description": "Görkemli bir sömürge tarzı evde, çiçek sanatı ve düzenlemesinin tarihini sunan çok zarif ve huzurlu bir müze.",
        "description_en": "A beautiful colonial-style teak mansion dedicated to the floral culture of Asia, set within a lush tropical garden.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin arkasındaki çay salonunda (Salon du Thé) çiçek aromalı çayların tadına bakın.",
        "tips_en": "Don't skip the afternoon tea service in the garden; it's one of the city's most elegant experiences."
    },
    {
        "name": "Vigan Art (Antique & Collectibles)",
        "name_en": "River City Bangkok",
        "area": "Riverside",
        "category": "Müze",
        "tags": ["antika", "sanat", "nehir kıyısı", "açık artırma"],
        "distanceFromCenter": 2.5,
        "lat": 13.7297,
        "lng": 100.5135,
        "price": "medium",
        "rating": 4.4,
        "description": "Nehir kıyısında yer alan, antikalar ve Asya sanatı üzerine uzmanlaşmış büyük bir ticaret ve sergi merkezi.",
        "description_en": "Bangkok's premier center for art and antiques, hosting several galleries and regular high-end collectibles auctions.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Burada düzenlenen geçici sanat sergileri genellikle çok kalitelidir, üst katları mutlaka gezin.",
        "tips_en": "The temporary art exhibitions on the upper floors are often world-class and free to enter."
    },
    {
        "name": "Ancient City (Miniature Thailand)",
        "name_en": "Ancient Siam",
        "area": "Samut Prakan",
        "category": "Müze",
        "tags": ["açık hava", "tayland turu", "mimari", "kültür"],
        "distanceFromCenter": 25.0,
        "lat": 13.5392,
        "lng": 100.6230,
        "price": "high",
        "rating": 4.8,
        "description": "Dünyanın en büyük açık hava müzesi. Tayland haritası şeklinde tasarlanmış bu dev alanda ülkenin tüm ikonik yapılarını bir günde görebilirsiniz.",
        "description_en": "The world's largest open-air museum, spanning 200 acres designed like the map of Thailand with replicas of its famous monuments.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Tüm gün",
        "bestTime_en": "Full day",
        "tips": "Alan çok büyüktür, girişte mutlaka golf arabası kiralayın, bisikletle gezmek çok yorucu olabilir.",
        "tips_en": "The park is enormous; rent an electric golf cart to cover the vast territory comfortably in the heat."
    },
    {
        "name": "Talad Noi (Street Art & Alleys)",
        "name_en": "Talad Noi Alleys",
        "area": "Riverside",
        "category": "Deneyim",
        "tags": ["sokak sanatı", "nostalji", "nehir", "fotojenik"],
        "distanceFromCenter": 2.0,
        "lat": 13.7345,
        "lng": 100.5130,
        "price": "free",
        "rating": 4.6,
        "description": "Eski demir parçaları ve motor aksamlarıyla dolu tamirhanelerin arasına gizlenmiş modern duvar resimleri ve şık kafelerin bulunduğu mahalle.",
        "description_en": "A historic neighborhood where gritty industrial scrap shops meet colorful street art and stylish riverside cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Paslı motor parçalarından yapılmış devasa açık hava galerisini andıran ara sokakları mutlaka kadrajınıza alın.",
        "tips_en": "Be sure to photograph the iconic 'So Heng Tai' mansion and the rusted car engine piles that define the area's look."
    },
    {
        "name": "Pratunam Wholesale Market",
        "name_en": "Pratunam Market",
        "area": "Pratunam",
        "category": "Alışveriş",
        "tags": ["toptan", "kıyafet", "ucuz", "kaotik"],
        "distanceFromCenter": 3.0,
        "lat": 13.7512,
        "lng": 100.5408,
        "price": "low",
        "rating": 4.1,
        "description": "Giyimden aksesuara her türlü tekstil ürününün toptan fiyatına satıldığı labirent gibi bir alışveriş dünyası.",
        "description_en": "A dense, maze-like market selling everything in fashion at wholesale prices it's the heart of Bangkok's garment industry.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Sabah erken (10:00 - 13:00)",
        "bestTime_en": "Late morning (10:00 AM - 1:00 PM)",
        "tips": "Genellikle 3 adetten fazla alımda büyük indirimler yapılır, arkadaşlarınızla alışveriş yapın.",
        "tips_en": "Wholesale prices kick in when you buy three or more items from the same category."
    },
    {
        "name": "MBK Center (Electronic Floor)",
        "name_en": "MBK Center",
        "area": "Siam",
        "category": "Alışveriş",
        "tags": ["elektronik", "gadgets", "hediyelik", "ikonik"],
        "distanceFromCenter": 2.0,
        "lat": 13.7445,
        "lng": 100.5299,
        "price": "low",
        "rating": 4.2,
        "description": "Bangkok'un en meşhur AVM'lerinden biri, özellikle 4. kattaki cep telefonu ve elektronik ürünler deniziyle ünlüdür.",
        "description_en": "A world-famous mall that is a haven for bargain seekers, especially on the 4th floor which is dedicated to mobile phones and tech accessories.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Cihaz tamiri veya aksesuarlar için en iyi adrestir, pazarlık hala mümkündür.",
        "tips_en": "The best place to get phone repairs or cheap accessories; don't be afraid to ask for a small discount."
    },
    {
        "name": "CentralWorld (Lifestyle Mall)",
        "name_en": "CentralWorld",
        "area": "Siam",
        "category": "Alışveriş",
        "tags": ["büyük", "küresel markalar", "buz pisti", "etkinlik"],
        "distanceFromCenter": 2.5,
        "lat": 13.7469,
        "lng": 100.5397,
        "price": "medium",
        "rating": 4.5,
        "description": "Tayland'ın en büyük, dünyanın ise sayılı alışveriş merkezlerinden biri. İçinde buz pistinden devasa kütüphanelere kadar her şey bulunur.",
        "description_en": "One of the largest shopping complexes in the world, featuring global brands, luxury department stores, and even an indoor ice skating rink.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gün boyu",
        "bestTime_en": "All day",
        "tips": "Özel günlerde dışarıdaki meydanda büyük konserler ve etkinlikler düzenlenir.",
        "tips_en": "Be sure to visit during major celebrations (like New Year or Songkran) when the front square hosts massive public events."
    },
    {
        "name": "Skywalk at Siam (Connected Walk)",
        "name_en": "Siam Skywalk",
        "area": "Siam",
        "category": "Manzara",
        "tags": ["şehir yürüyüşü", "bağlantı yolu", "modern", "ücretsiz"],
        "distanceFromCenter": 2.1,
        "lat": 13.7460,
        "lng": 100.5330,
        "price": "free",
        "rating": 4.4,
        "description": "Siam meydanındaki tüm lüks AVM'leri birbirine bağlayan, trafikten uzak ve klimalı geçişlere sahip modern yürüyüş platformu.",
        "description_en": "A clean, modern elevated walkway connecting all the major Siam malls, offering great views of the famous traffic crossroads and skyscrapers.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Akşam (Şehir ışıklarıyla)",
        "bestTime_en": "Evening (with the city lights)",
        "tips": "MBK'den Siam Paragon'a trafik stresine girmeden en hızlı ve ferah geçiş yoludur.",
        "tips_en": "A perfect, traffic-free way to walk between MBK, Siam Discovery, and Siam Paragon in comfortable shade."
    },
    {
        "name": "Jim Thompson House - Traditional Teak",
        "name_en": "Jim Thompson House",
        "area": "Pathum Wan",
        "category": "Müze",
        "tags": ["ipek", "tarihi ev", "bahçe", "tay mimarisi"],
        "distanceFromCenter": 3.0,
        "lat": 13.7428,
        "lng": 100.5237,
        "price": "medium",
        "rating": 4.4,
        "description": "Amerikalı bir iş adamı ve sanat koleksiyoneri tarafından 6 antik Tay evinin birleştirilmesiyle kurulmuş, tropikal bir cenne müzesi.",
        "description_en": "A lush, tropical oasis in the city center featuring a collection of historic Thai houses filled with Southeast Asian art and antiquities.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sadece zorunlu rehberli turlarla gezilir; bahçedeki ipek üretim gösterisini kaçırmayın.",
        "tips_en": "Entry is only via compulsory guided tours; don't miss the traditional silk-weaving exhibition in the courtyard."
    },
    {
        "name": "Baan Krua (Silk Weaving Community)",
        "name_en": "Baan Krua Community",
        "area": "Pathum Wan",
        "category": "Deneyim",
        "tags": ["ipek", "zanaat", "kanal kenarı", "gizli mücevher"],
        "distanceFromCenter": 3.2,
        "lat": 13.7500,
        "lng": 100.5280,
        "price": "low",
        "rating": 4.4,
        "description": "Jim Thompson'ın efsanevi ipeklerini dokuyan topluluğun hala yaşadığı ve el tezgahlarında ipek üretmeye devam ettiği gizli mahalle.",
        "description_en": "A historic Muslim community on the canal that once produced the world-famous silks for Jim Thompson. You can still find artisans weaving on old looms.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Hafta içi gündüz",
        "bestTime_en": "Weekday mornings",
        "tips": "Modern ipek mağazalarından çok daha uygun fiyata gerçek el dokuması ipekler alabilir, atölyeleri görebilirsiniz.",
        "tips_en": "Visit the weaving workshops to buy authentic, high-quality silk directly from the producers for much less than in retail shops."
    },
    {
        "name": "Princess Mother Memorial Park",
        "name_en": "Princess Mother Park",
        "area": "Thonburi",
        "category": "Park",
        "tags": ["miras", "huzur", "bahçe", "tarihi evler"],
        "distanceFromCenter": 1.5,
        "lat": 13.7370,
        "lng": 100.4930,
        "price": "free",
        "rating": 4.8,
        "description": "Eski Kral'ın annesinin çocukluğunu geçirdiği evin bahçesinde kurulmuş, antik binalar ve dev ağaçlarla dolu şaşırtıcı bir huzur noktası.",
        "description_en": "A meticulously maintained memorial park in a former royal residence, offering tranquil gardens and restored period houses away from the crowds.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçindeki küçük müze ve sanat galerisi, Tay kraliyet tarihine çok samimi bir bakış açısı sunar.",
        "tips_en": "Visit the museum inside for an intimate look at the life of the Princess Mother and local community history."
    },
    {
        "name": "Wang Lang Market (Food Heaven)",
        "name_en": "Wang Lang Market",
        "area": "Riverside (Thonburi Side)",
        "category": "Deneyim",
        "tags": ["yemek", "ikinci el", "lokal", "pazar"],
        "distanceFromCenter": 1.2,
        "lat": 13.7560,
        "lng": 100.4850,
        "price": "low",
        "rating": 4.6,
        "description": "Nehrin karşı tarafında, hastane çalışanları ve öğrenciler arasında popüler olan, en iyi yerel atıştırmalıkların ve ikinci el kıyafetlerin bulunduğu pazar.",
        "description_en": "A bustling riverside market famous for its incredible local street snacks, cheap second-hand fashion, and authentic non-touristy vibe.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Öğle yemeği saati",
        "bestTime_en": "Lunch hours (11:00 AM - 2:00 PM)",
        "tips": "Kızarmış tavuğunu ve meşhur 'Wang Lang Bakery' çöreklerini tatmadan dönmeyin.",
        "tips_en": "Grab a bag of famous pastries from Wang Lang Bakery it's an institution for locals."
    }
]

def enrich_bangkok_batch2():
    filepath = 'assets/cities/bangkok.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_bangkok_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_bangkok_batch2()
print(f"Bangkok now has {count} highlights.")
