import json
import os

new_budapest_batch4 = [
    {
        "name": "M1 Metro Hattı",
        "name_en": "M1 Metro Line",
        "area": "Andrássy - Pest",
        "category": "Deneyim",
        "tags": ["metro", "tarihi", "unesco", "nostalji"],
        "distanceFromCenter": 0.5,
        "lat": 47.5000,
        "lng": 19.0500,
        "price": "low",
        "rating": 4.7,
        "description": "Londra'dan sonra dünyanın en eski ikinci metrosu. UNESCO Dünya Mirası listesindeki bu hat, ahşap istasyonları ve nostaljik vagonlarıyla bir zaman makinesi gibidir.",
        "description_en": "The second oldest metro in the world after London. This line, a UNESCO site, is like a time machine with its wooden stations and nostalgic carriages.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sarı hat olarak da bilinir; Vörösmarty Meydanı ile Kahramanlar Meydanı arasında yolculuk yapın.",
        "tips_en": "Also known as the yellow line; travel between Vörösmarty Square and Heroes' Square."
    },
    {
        "name": "A38 Hajó",
        "name_en": "A38 Ship",
        "area": "Tuna",
        "category": "Bar",
        "tags": ["gemi", "konser", "gece hayatı", "nehir"],
        "distanceFromCenter": 2.5,
        "lat": 47.4764,
        "lng": 19.0631,
        "price": "medium",
        "rating": 4.8,
        "description": "Eski bir Ukrayna yük gemisinden dönüştürülmüş, nehir üzerinde demirli dünyaca ünlü bir konser ve etkinlik mekanı.",
        "description_en": "A world-renowned concert and event venue moored on the river, converted from an old Ukrainian cargo ship.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Lonely Planet tarafından dünyanın en iyi barı seçilmiştir; programına mutlaka göz atın.",
        "tips_en": "Voted the best bar in the world by Lonely Planet; be sure to check their program."
    },
    {
        "name": "Szemlő-hegyi Cave",
        "name_en": "Szemlo-hegyi Cave",
        "area": "Buda",
        "category": "Deneyim",
        "tags": ["mağara", "doğa", "temiz hava", "terapi"],
        "distanceFromCenter": 4.0,
        "lat": 47.5300,
        "lng": 19.0200,
        "price": "medium",
        "rating": 4.7,
        "description": "Budapeşte'nin yeraltı 'çiçek bahçesi' olarak bilinir. Nadir kristal ve kalsiyum oluşumlarıyla süslü, havası solunum yollarına iyi gelen bir mağara.",
        "description_en": "Known as Budapest's underground 'flower garden'. A cave adorned with rare crystal and calcium formations, with air beneficial for the respiratory system.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Pálvölgyi mağarasına çok yakındır, ikisini aynı gün gezebilirsiniz.",
        "tips_en": "Very close to Pálvölgyi cave; you can visit both in the same day."
    },
    {
        "name": "Budapest Zoo & Botanical Garden",
        "name_en": "Budapest Zoo",
        "area": "Városliget",
        "category": "Park",
        "tags": ["hayvanat bahçesi", "mimari", "tarihi", "aile"],
        "distanceFromCenter": 3.0,
        "lat": 47.5186,
        "lng": 19.0769,
        "price": "medium",
        "rating": 4.7,
        "description": "Dünyanın en eski hayvanat bahçelerinden biri. Sadece hayvanlarıyla değil, Art Nouveau tarzı binalarıyla (Fil Evi gibi) mimari bir hazinedir.",
        "description_en": "One of the oldest zoos in the world. An architectural treasure not just for its animals but for its Art Nouveau buildings (like the Elephant House).",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın üzerindeki seramik süslemelere ve ikonik giriş kapısına dikkat edin.",
        "tips_en": "Pay attention to the ceramic decorations on the building and the iconic entrance gate."
    },
    {
        "name": "Fine Arts Museum (Szépművészeti Múzeum)",
        "name_en": "Museum of Fine Arts",
        "area": "Kahramanlar Meydanı",
        "category": "Müze",
        "tags": ["sanat", "klasik", "mısır", "rönesans"],
        "distanceFromCenter": 2.2,
        "lat": 47.5150,
        "lng": 19.0767,
        "price": "medium",
        "rating": 4.8,
        "description": "Macaristan'ın en önemli sanat müzesi. Mısır koleksiyonundan Rönesans ustalarına kadar Avrupa sanatının dev eserlerini barındırır.",
        "description_en": "Hungary's most important art museum, housing major European art works from Egyptian collections to Renaissance masters.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Özellikle yeni restore edilen 'Roma Salonu' (Roman Hall) tek başına dahi görmeye değerdir.",
        "tips_en": "The newly restored 'Roman Hall' (Roman Hall) alone is worth the visit."
    },
    {
        "name": "János-hegy & Elisabeth Lookout",
        "name_en": "Janos Hill",
        "area": "Buda Hills",
        "category": "Manzara",
        "tags": ["tepe", "yürüyüş", "manzara", "en yüksek"],
        "distanceFromCenter": 9.0,
        "lat": 47.5181,
        "lng": 18.9594,
        "price": "free",
        "rating": 4.9,
        "description": "Budapeşte'nin en yüksek noktası. Zirvesindeki Erzsébet Gözlem Kulesi'nden şehrin ve çevre tepelerin nefes kesen manzarasını izleyebilirsiniz.",
        "description_en": "The highest point in Budapest. From the Erzsébet Lookout at its summit, you can enjoy breathtaking views of the city and surrounding hills.",
        "imageUrl": "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=1200",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Oraya telesiyej (Libegő) ile çıkmak maceranın eylenceli bir parçasıdır.",
        "tips_en": "Taking the chairlift (Libegő) to the top is a fun part of the adventure."
    },
    {
        "name": "Robert Capa Photography Center",
        "name_en": "Robert Capa Center",
        "area": "Pest",
        "category": "Müze",
        "tags": ["fotoğraf", "sanat", "robert capa", "çağdaş"],
        "distanceFromCenter": 0.8,
        "lat": 47.5033,
        "lng": 19.0617,
        "price": "medium",
        "rating": 4.7,
        "description": "Dünyanın en ünlü savaş fotoğrafçılarından Macar asıllı Robert Capa'ya ve çağdaş fotoğraf sanatına adanmış modern bir merkez.",
        "description_en": "A modern center dedicated to the Hungarian-born Robert Capa, one of the world's most famous war photographers, and contemporary photography art.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Hemen yanındaki Mai Tirano Hız (Fotoğrafçı Evi) binasını da mutlaka görün.",
        "tips_en": "Be sure to also see the nearby Mai Tirano Hız (House of Photographers) building."
    },
    {
        "name": "Akvarium Klub",
        "name_en": "Akvarium Klub",
        "area": "Deák Ferenc tér",
        "category": "Bar",
        "tags": ["klüp", "meydan", "havuz", "konser"],
        "distanceFromCenter": 0.0,
        "lat": 47.4975,
        "lng": 19.0533,
        "price": "medium",
        "rating": 4.5,
        "description": "Pest'in en merkezi meydanında, yer altında bulunan devasa bir eğlence kompleksi. Cam tavanlı havuzunun altından gökyüzünü izleyebilirsiniz.",
        "description_en": "A massive underground entertainment complex in Pest's most central square. You can watch the sky from beneath the glass-bottomed pool.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Gündüzleri meydandaki basamaklarda oturup vakit geçiren gençlerle doludur.",
        "tips_en": "During the day, the square steps are filled with young people hanging out."
    },
    {
        "name": "Pontoon",
        "name_en": "Pontoon",
        "area": "Tuna",
        "category": "Bar",
        "tags": ["açık hava", "nehir", "zincir köprü", "parti"],
        "distanceFromCenter": 0.5,
        "lat": 47.4983,
        "lng": 19.0433,
        "price": "medium",
        "rating": 4.7,
        "description": "Zincir Köprüsü'nün hemen dibinde, Tuna Nehri kıyısında yaz aylarının en popüler açık hava barı.",
        "description_en": "The most popular outdoor bar of the summer months, located right at the foot of the Chain Bridge along the Danube. ",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Tuna ve kale manzarası eşliğinde müzik dinlemek için en iyi yerdir.",
        "tips_en": "The best place to listen to music with a view of the Danube and the castle."
    },
    {
        "name": "ELTE Füvészkert (Botanik Bahçesi)",
        "name_en": "ELTE Botanical Garden",
        "area": "Pest",
        "category": "Park",
        "tags": ["doğa", "botanik", "sera", "huzur"],
        "distanceFromCenter": 2.5,
        "lat": 47.4856,
        "lng": 19.0833,
        "price": "low",
        "rating": 4.6,
        "description": "Budapeşte'nin en eski botanik bahçesi. Viktorya tarzı seraları ve yüzlerce bitki türüyle huzur dolu bir kaçış noktası.",
        "description_en": "Budapest's oldest botanical garden. A peaceful escape with Victorian-style greenhouses and hundreds of plant species.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Bahar",
        "bestTime_en": "Spring",
        "tips": "Meşhur Macar çocuk kitabı 'Pal Sokağı Çocukları'ndaki gizli bahçe burasıdır.",
        "tips_en": "This is the hidden garden from the famous Hungarian children's book 'The Paul Street Boys'."
    },
    {
        "name": "National Széchényi Library",
        "name_en": "National Library",
        "area": "Buda Kalesi",
        "category": "Tarihi",
        "tags": ["kütüphane", "kale", "kültür", "kitap"],
        "distanceFromCenter": 1.2,
        "lat": 47.4961,
        "lng": 19.0394,
        "price": "low",
        "rating": 4.8,
        "description": "Buda Kalesi kompleksi içinde yer alan, Macaristan'ın en büyük kütüphanesi ve yazılı mirasının koruyucusu.",
        "description_en": "Hungary's largest library and guardian of its written heritage, located within the Buda Castle complex.",
        "imageUrl": "https://images.unsplash.com/photo-1521587760476-6c12a71048ca?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçerideki muhteşem okuma salonlarını ve geçici sergileri mutlaka görün.",
        "tips_en": "Be sure to see the magnificent reading rooms and temporary exhibitions inside."
    },
    {
        "name": "Gödöllő Royal Palace",
        "name_en": "Godollo Royal Palace",
        "area": "Günübirlik",
        "category": "Tarihi",
        "tags": ["saray", "sisi", "barok", "tarih"],
        "distanceFromCenter": 30.0,
        "lat": 47.5956,
        "lng": 19.3494,
        "price": "medium",
        "rating": 4.7,
        "description": "İmparatoriçe Sissi'nin en sevdiği yazlık sarayı. Macaristan'ın en büyük Barok malikanesi ve Habsburglara dair pek çok anı saklar.",
        "description_en": "Empress Sissi's favorite summer palace. Hungary's largest Baroque mansion, holding many memories of the Habsburgs.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Tüm gün",
        "bestTime_en": "Full day",
        "tips": "Budapeşte'den banliyö treniyle (HEV) kolayca ulaşılabilir.",
        "tips_en": "Easily accessible from Budapest by suburban train (HEV)."
    },
    {
        "name": "Műcsarnok (Kunsthalle)",
        "name_en": "Kunsthalle",
        "area": "Kahramanlar Meydanı",
        "category": "Müze",
        "tags": ["çağdaş sanat", "galeri", "mimari", "meydan"],
        "distanceFromCenter": 2.2,
        "lat": 47.5144,
        "lng": 19.0783,
        "price": "medium",
        "rating": 4.5,
        "description": "Kahramanlar Meydanı'ndaki heybetli sütunlu bina. Macaristan'ın en büyük çağdaş sanat galerisi (müze koleksiyonu yoktur, sergiler geçicidir).",
        "description_en": "The imposing columned building in Heroes' Square. Hungary's largest contemporary art gallery (no permanent collection, temporary exhibitions only).",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Sergilere girmeden önce binanın dışındaki renkli freskleri inceleyin.",
        "tips_en": "Examine the colorful frescoes on the building's exterior before entering the exhibitions."
    },
    {
        "name": "Ludwig Museum",
        "name_en": "Ludwig Museum",
        "area": "Güney Pest",
        "category": "Müze",
        "tags": ["çağdaş sanat", "modern", "kültür sarayı"],
        "distanceFromCenter": 4.0,
        "lat": 47.4700,
        "lng": 19.0700,
        "price": "medium",
        "rating": 4.6,
        "description": "Müpa (Sanatlar Sarayı) içinde yer alan, Orta ve Doğu Avrupa'nın en önemli çağdaş sanat koleksiyonlarından birine ev sahipliği yapan müze.",
        "description_en": "Located within Müpa (Palace of Arts), this museum houses one of the most important contemporary art collections in Central and Eastern Europe.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Binanın terasından Tuna'nın güney kısmının manzarası harikadır.",
        "tips_en": "The view of the southern Danube from the building's terrace is great."
    },
    {
        "name": "Lukács Thermal Bath",
        "name_en": "Lukacs Thermal Bath",
        "area": "Buda",
        "category": "Deneyim",
        "tags": ["hamam", "şifalı su", "terapi", "tarihi"],
        "distanceFromCenter": 2.2,
        "lat": 47.5175,
        "lng": 19.0369,
        "price": "medium",
        "rating": 4.5,
        "description": "Yüzyıllardır şifalı sularıyla bilinen, özellikle lokallerin ve sanatçıların tercih ettiği daha az turistik ve otantik bir hamam.",
        "description_en": "Known for centuries for its healing waters, a less touristic and more authentic bath preferred by locals and artists.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Bahçesindeki mermer şükran tabletleri, iyileşen hastalar tarafından bırakılmıştır.",
        "tips_en": "The marble gratitude tablets in the garden were left by patients who were healed."
    },
    {
        "name": "Gozsdu Weekend Market",
        "name_en": "Gozsdu Weekend Market",
        "area": "Yahudi Mahallesi",
        "category": "Deneyim",
        "tags": ["pazar", "vintage", "tasarım", "hediyelik"],
        "distanceFromCenter": 0.5,
        "lat": 47.4994,
        "lng": 19.0588,
        "price": "low",
        "rating": 4.6,
        "description": "Cuma'dan Pazar'a Gozsdu avlularında kurulan, antika takılardan yerel tasarımlara kadar pek çok ilginç şeyin bulunduğu pazar.",
        "description_en": "A market held in the Gozsdu courtyards from Friday to Sunday, featuring interesting items from antique jewelry to local designs.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Cumartesi öğle",
        "bestTime_en": "Saturday noon",
        "tips": "Pazarlık yapmayı ve küçük sanatçı tezgahlarını keşfetmeyi unutmayın.",
        "tips_en": "Don't forget to bargain and explore the small artist stalls."
    }
]

def enrich_budapest_batch4():
    filepath = 'assets/cities/budapeste.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_budapest_batch4:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_budapest_batch4()
print(f"Budapest now has {count} highlights.")
