import json
import requests
import time
import urllib.parse

API_KEY = 'AIzaSyBOXbf-5v4aXyEYgciwX4EfPYAGXX6Yy9g'

def get_google_photo_url(place_name):
    try:
        find_place_url = f"https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input={urllib.parse.quote(place_name)}&inputtype=textquery&fields=place_id,photos&key={API_KEY}&locationbias=circle:15000@37.0662,37.3833"
        response = requests.get(find_place_url)
        data = response.json()
        if data['status'] == 'OK' and len(data['candidates']) > 0:
            candidate = data['candidates'][0]
            if 'photos' in candidate:
                photo_reference = candidate['photos'][0]['photo_reference']
                return f"https://maps.googleapis.com/maps/api/place/photo?maxwidth=800&photoreference={photo_reference}&key={API_KEY}"
        return None
    except:
        return None

# BATCH 7: MORE KEBAB & SPECIALTY RESTAURANTS
batch_7 = [
    {"name": "Seyhan Restaurant", "name_en": "Seyhan Restaurant", "area": "Şehitkamil", "category": "Restoran", "tags": ["kebap", "lüks", "aile"], "distanceFromCenter": 1.5, "lat": 37.0700, "lng": 37.3850, "price": "high", "rating": 4.7, "description": "Geniş aileler için ideal, zengin meze seçenekleri ve kaliteli kebaplarıyla tanınan şık restoran.", "description_en": "Stylish restaurant ideal for large families, known for its rich meze options and quality kebabs.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Öğlen daha sakindir, akşam rezervasyon şart.", "tips_en": "Calmer at lunch, reservation is a must for dinner."},
    {"name": "Tarihi Yuvalama Evi", "name_en": "Historic Yuvalama House", "area": "Şahinbey", "category": "Restoran", "tags": ["yuvalama", "geleneksel", "sulu yemek"], "distanceFromCenter": 0.5, "lat": 37.0620, "lng": 37.3810, "price": "medium", "rating": 4.6, "description": "Gaziantep'in en meşhur tencere yemeği yuvalama yapan nadir mekanlardan.", "description_en": "One of the rare places making yuvalama, Gaziantep's most famous stew dish.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Yuvalama ağır bir yemektir, az yemek siparişi verin.", "tips_en": "Yuvalama is a heavy dish, order less food."},
    {"name": "Karaoğlu Baklava", "name_en": "Karaoglu Baklava", "area": "Şehitkamil", "category": "Tatlı", "tags": ["baklava", "kadayıf", "taze"], "distanceFromCenter": 2.0, "lat": 37.0750, "lng": 37.3700, "price": "medium", "rating": 4.8, "description": "Kadayıf ve baklava ustası, özellikle sütlü nuriye tatlısıyla ünlü.", "description_en": "Kadayif and baklava master, especially famous for its milky nuriye dessert.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sütlü nuriye tatlısını mutlaka deneyin.", "tips_en": "Must try the milky nuriye dessert."},
    {"name": "Güllüoğlu", "name_en": "Gulluoglu", "area": "Şahinbey", "category": "Tatlı", "tags": ["baklava", "ünlü", "zincir"], "distanceFromCenter": 0.5, "lat": 37.0630, "lng": 37.3820, "price": "high", "rating": 4.6, "description": "Gaziantep'ten dünyaya yayılan baklava markası. Fıstık baklavasının mucidi.", "description_en": "Baklava brand spreading from Gaziantep to the world. Inventor of pistachio baklava.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Kuru baklava hediyelik için idealdir.", "tips_en": "Dry baklava is ideal for gifts."},
    {"name": "Develi Kebap", "name_en": "Develi Kebab", "area": "Şehitkamil", "category": "Restoran", "tags": ["kebap", "pide", "aile"], "distanceFromCenter": 1.8, "lat": 37.0720, "lng": 37.3780, "price": "medium", "rating": 4.5, "description": "Antep usulü pide ve kebaplarıyla tanınan, yerel halkın favori mekanlarından.", "description_en": "Known for Antep style pide and kebabs, one of the favorite places of locals.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Antep pidesi ile lahmacun arasında bir lezzet.", "tips_en": "A flavor between Antep pide and lahmacun."},
    {"name": "Beyran Ustası", "name_en": "Beyran Master", "area": "Şahinbey", "category": "Restoran", "tags": ["beyran", "sabah", "şifa"], "distanceFromCenter": 0.4, "lat": 37.0615, "lng": 37.3825, "price": "medium", "rating": 4.7, "description": "Sabahın köründe açılan, baharatlı ve yağlı beyran çorbasıyla ünlü mekan.", "description_en": "Place opening at dawn, famous for its spicy and oily beyran soup.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "06:00-08:00 arası en taze beyran burada.", "tips_en": "Freshest beyran here between 06:00-08:00."},
    {"name": "Simit Sarayı Gaziantep", "name_en": "Simit Palace Gaziantep", "area": "Şahinbey", "category": "Kafe", "tags": ["simit", "kahvaltı", "modern"], "distanceFromCenter": 0.3, "lat": 37.0625, "lng": 37.3815, "price": "low", "rating": 4.2, "description": "Hızlı kahvaltı ve simit çeşitleri için uygun, merkezi konum.", "description_en": "Convenient for quick breakfast and simit varieties, central location.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Şehir turuna başlamadan önce hızlı kahvaltı için ideal.", "tips_en": "Ideal for quick breakfast before starting city tour."},
    {"name": "Anadolu Sofrası", "name_en": "Anadolu Sofrasi", "area": "Şehitkamil", "category": "Restoran", "tags": ["sulu yemek", "ev yemeği", "ekonomik"], "distanceFromCenter": 1.0, "lat": 37.0680, "lng": 37.3760, "price": "low", "rating": 4.4, "description": "Ev yemekleri ve sulu yemekler sunan, öğle yemeği için ekonomik seçenek.", "description_en": "Serving home-style and stew dishes, economical option for lunch.", "bestTime": "Öğle", "bestTime_en": "Lunch", "tips": "Tabldot menü çok doyurucu ve uygun fiyatlı.", "tips_en": "Set menu is very filling and affordable."}
]

# BATCH 8: ADDITIONAL DESSERTS & SWEETS
batch_8 = [
    {"name": "Tatlidede", "name_en": "Tatlidede", "area": "Şehitkamil", "category": "Tatlı", "tags": ["dondurma", "tatlı", "modern"], "distanceFromCenter": 2.0, "lat": 37.0760, "lng": 37.3720, "price": "medium", "rating": 4.5, "description": "Antep fıstıklı dondurma ve modern sunumlarıyla öne çıkan tatlı dükkanı.", "description_en": "Sweet shop standing out with pistachio ice cream and modern presentations.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Maraş dondurması Antep versiyonu ilginçtir.", "tips_en": "Maras ice cream Antep version is interesting."},
    {"name": "Kadayıfçı Cemil Usta", "name_en": "Kadayifci Cemil Usta", "area": "Şahinbey", "category": "Tatlı", "tags": ["kadayıf", "tel kadayıf", "geleneksel"], "distanceFromCenter": 0.5, "lat": 37.0610, "lng": 37.3800, "price": "medium", "rating": 4.7, "description": "Tel kadayıf ve künefe yapan nadir ustalardan biri.", "description_en": "One of the rare masters making tel kadayif and kunefe.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Sıcak servis edileni tercih edin.", "tips_en": "Prefer the one served hot."},
    {"name": "Şerbet Evi", "name_en": "Serbet House", "area": "Şahinbey", "category": "Kafe", "tags": ["şerbet", "geleneksel", "serinlik"], "distanceFromCenter": 0.3, "lat": 37.0625, "lng": 37.3830, "price": "low", "rating": 4.6, "description": "Geleneksel Antep şerbetleri sunan, sıcak günlerde serinlemek için ideal mekan.", "description_en": "Place serving traditional Antep sherbets, ideal for cooling down on hot days.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Demirhindi şerbetini deneyin.", "tips_en": "Try the tamarind sherbet."},
    {"name": "Fıstıklı Dondurma", "name_en": "Pistachio Ice Cream", "area": "Şehitkamil", "category": "Tatlı", "tags": ["dondurma", "fıstık", "yerel"], "distanceFromCenter": 1.5, "lat": 37.0700, "lng": 37.3750, "price": "medium", "rating": 4.8, "description": "Gerçek Antep fıstığından yapılan el yapımı dondurma.", "description_en": "Handmade ice cream made from real Antep pistachios.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Kornet yerine külahta alın, daha lezzetli.", "tips_en": "Get it in a cone, not a cup, tastier."},
    {"name": "Peynirli Künefe", "name_en": "Cheese Kunefe", "area": "Şahinbey", "category": "Tatlı", "tags": ["künefe", "tatlı", "sıcak"], "distanceFromCenter": 0.4, "lat": 37.0630, "lng": 37.3810, "price": "medium", "rating": 4.6, "description": "Hatay künefesinden farklı, Antep usulü peynirli künefe yapan mekan.", "description_en": "Place making Antep style cheese kunefe, different from Hatay kunefe.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Sıcak sıcak yenmeli, soğuyunca tadı değişir.", "tips_en": "Must be eaten hot, taste changes when cold."},
    {"name": "Mahallebaşı", "name_en": "Mahallekebasi", "area": "Şahinbey", "category": "Tatlı", "tags": ["tatlı", "modern", "kafe"], "distanceFromCenter": 0.5, "lat": 37.0620, "lng": 37.3820, "price": "medium", "rating": 4.4, "description": "Modern atmosferde geleneksel Antep tatlıları sunan şık mekan.", "description_en": "Stylish place serving traditional Antep desserts in modern atmosphere.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Çay saatinde gelmek en iyisi.", "tips_en": "Best to come at tea time."},
    {"name": "Helva Evi", "name_en": "Halva House", "area": "Şahinbey", "category": "Tatlı", "tags": ["helva", "tahin", "geleneksel"], "distanceFromCenter": 0.3, "lat": 37.0615, "lng": 37.3815, "price": "low", "rating": 4.5, "description": "Çeşitli helva türleri ve tahin ürünleri satan geleneksel dükkan.", "description_en": "Traditional shop selling various types of halva and tahini products.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Fıstıklı tahin helvasını hediyelik alın.", "tips_en": "Get pistachio tahini halva as a gift."}
]

# BATCH 9: MORE CAFES & TEA HOUSES
batch_9 = [
    {"name": "Şire Han", "name_en": "Sire Han", "area": "Şahinbey", "category": "Kafe", "tags": ["han", "tarihi", "üzüm şırası"], "distanceFromCenter": 0.4, "lat": 37.0625, "lng": 37.3815, "price": "medium", "rating": 4.5, "description": "Tarihi handa üzüm şırası ve geleneksel içecekler sunan atmosferik mekan.", "description_en": "Atmospheric place serving grape must and traditional drinks in a historic inn.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Şıra (taze üzüm suyu) mutlaka deneyin.", "tips_en": "Must try sira (fresh grape juice)."},
    {"name": "Antep Çay Evi", "name_en": "Antep Tea House", "area": "Şahinbey", "category": "Kafe", "tags": ["çay", "nargile", "geleneksel"], "distanceFromCenter": 0.5, "lat": 37.0610, "lng": 37.3805, "price": "low", "rating": 4.3, "description": "Yerel halkın buluşma noktası, tavla ve çay eşliğinde hoş sohbetler.", "description_en": "Meeting point for locals, pleasant conversations with backgammon and tea.", "bestTime": "Akşam", "bestTime_en": "Evening", "tips": "Tavla oynamayı bilmiyorsanız lokaller size öğretir.", "tips_en": "If you don't know how to play backgammon, locals will teach you."},
    {"name": "Kahve Durağı", "name_en": "Coffee Stop", "area": "Şehitkamil", "category": "Kafe", "tags": ["kahve", "modern", "çalışma"], "distanceFromCenter": 2.0, "lat": 37.0750, "lng": 37.3700, "price": "medium", "rating": 4.2, "description": "Modern kahve zinciri, wifi ve çalışma ortamı arayanlar için.", "description_en": "Modern coffee chain, for those looking for wifi and working environment.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Laptop ile çalışmak için prizler var.", "tips_en": "There are outlets for working with laptop."},
    {"name": "Antep Evleri Çay Bahçesi", "name_en": "Antep Houses Tea Garden", "area": "Şahinbey", "category": "Kafe", "tags": ["bahçe", "çay", "konak"], "distanceFromCenter": 0.3, "lat": 37.0630, "lng": 37.3825, "price": "low", "rating": 4.6, "description": "Restore edilmiş Antep evlerinin avlusunda çay içebileceğiniz huzurlu bahçe.", "description_en": "Peaceful garden where you can drink tea in the courtyard of restored Antep houses.", "bestTime": "İkindi", "bestTime_en": "Afternoon", "tips": "Fotoğraf çekmek için en güzel ışık ikindide.", "tips_en": "Best light for photos is in the afternoon."},
    {"name": "Café 37", "name_en": "Cafe 37", "area": "Şehitkamil", "category": "Kafe", "tags": ["modern", "kahve", "brunch"], "distanceFromCenter": 2.5, "lat": 37.0780, "lng": 37.3680, "price": "high", "rating": 4.4, "description": "Şehrin dışında, modern dekorasyonu ve brunch menüsüyle öne çıkan kafe.", "description_en": "Outside the city, cafe standing out with modern decor and brunch menu.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Hafta sonu brunch için rezervasyon şart.", "tips_en": "Reservation is a must for weekend brunch."},
    {"name": "Menengiç Kahvecisi", "name_en": "Menenging Coffee Shop", "area": "Şahinbey", "category": "Kafe", "tags": ["menengiç", "kahve", "özel"], "distanceFromCenter": 0.4, "lat": 37.0620, "lng": 37.3810, "price": "medium", "rating": 4.7, "description": "Sadece menengiç kahvesine odaklanan, bu benzersiz içeceğin ustası.", "description_en": "Focusing only on menengiç coffee, master of this unique beverage.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sütlü menengiç latte versiyonunu deneyin.", "tips_en": "Try the milky menengiç latte version."}
]

# BATCH 10: MORE MUSEUMS & CULTURE
batch_10 = [
    {"name": "Arkeoloji Müzesi", "name_en": "Archaeology Museum", "area": "Şehitkamil", "category": "Müze", "tags": ["arkeoloji", "tarih", "eser"], "distanceFromCenter": 1.5, "lat": 37.0700, "lng": 37.3800, "price": "low", "rating": 4.4, "description": "Zeugma dışındaki arkeolojik eserlerin sergilendiği klasik müze.", "description_en": "Classic museum exhibiting archaeological artifacts other than Zeugma.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Zeugma ile birlikte kombine bilet alınabilir.", "tips_en": "Can get combined ticket with Zeugma."},
    {"name": "Kent Müzesi", "name_en": "City Museum", "area": "Şahinbey", "category": "Müze", "tags": ["şehir", "tarih", "modern"], "distanceFromCenter": 0.5, "lat": 37.0630, "lng": 37.3820, "price": "free", "rating": 4.3, "description": "Gaziantep'in tarihini, ekonomisini ve kültürünü anlatan şehir müzesi.", "description_en": "City museum explaining Gaziantep's history, economy and culture.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Giriş ücretsiz, mutlaka uğrayın.", "tips_en": "Free entry, definitely stop by."},
    {"name": "Kurtuluş Camii", "name_en": "Kurtulus Mosque", "area": "Şahinbey", "category": "Tarihi", "tags": ["cami", "kilise", "dönüştürülmüş"], "distanceFromCenter": 0.3, "lat": 37.0640, "lng": 37.3830, "price": "free", "rating": 4.5, "description": "Eski bir Ermeni kilisesinden camiye dönüştürülmüş ilginç yapı.", "description_en": "Interesting structure converted from an old Armenian church to a mosque.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Mimari detaylar hem Hristiyan hem İslam etkisi taşır.", "tips_en": "Architectural details carry both Christian and Islamic influence."},
    {"name": "Şahinbey Milli Mücadele Müzesi", "name_en": "Sahinbey National Struggle Museum", "area": "Şahinbey", "category": "Müze", "tags": ["savaş", "kahramanlık", "tarih"], "distanceFromCenter": 0.8, "lat": 37.0580, "lng": 37.3800, "price": "low", "rating": 4.6, "description": "Kurtuluş Savaşı'nda şehrin kahramanlığını ve Şahinbey'i anlatan müze.", "description_en": "Museum explaining the city's heroism and Sahinbey during the War of Independence.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Rehberli turlar daha etkileyicidir.", "tips_en": "Guided tours are more impressive."},
    {"name": "Yazılı Kayalar", "name_en": "Yazili Rocks", "area": "Şehitkamil", "category": "Tarihi", "tags": ["kaya yazıtları", "hitit", "doğa"], "distanceFromCenter": 15.0, "lat": 37.1500, "lng": 37.2500, "price": "free", "rating": 4.3, "description": "Hitit döneminden kalan kaya yazıtları ve kabartmaları.", "description_en": "Rock inscriptions and reliefs from the Hittite period.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Araba ile ulaşım gerekli, 30 dk sürüş.", "tips_en": "Car transportation needed, 30 min drive."},
    {"name": "Karkamış Antik Kenti", "name_en": "Karkemish Ancient City", "area": "Nizip", "category": "Tarihi", "tags": ["antik", "hitit", "sınır"], "distanceFromCenter": 60.0, "lat": 36.8300, "lng": 38.0200, "price": "free", "rating": 4.5, "description": "Suriye sınırında, Hitit döneminden kalma önemli antik kent.", "description_en": "Important ancient city from the Hittite period, on the Syrian border.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Askeri bölge yakınında, kimlik yanınızda olsun.", "tips_en": "Near military zone, have your ID with you."}
]

# BATCH 11: MORE NATURE & ACTIVITIES
batch_11 = [
    {"name": "Burç Ormanı", "name_en": "Burc Forest", "area": "Şehitkamil", "category": "Park", "tags": ["orman", "piknik", "konser"], "distanceFromCenter": 5.0, "lat": 37.1000, "lng": 37.3400, "price": "low", "rating": 4.6, "description": "Geniş ormanlık alan, yaz aylarında açık hava konserleri düzenlenir.", "description_en": "Large forest area, open-air concerts are held in summer months.", "bestTime": "Hafta sonu", "bestTime_en": "Weekend", "tips": "Yaz akşamları konser programını kontrol edin.", "tips_en": "Check concert program on summer evenings."},
    {"name": "Halfeti Tekne Turu", "name_en": "Halfeti Boat Tour", "area": "Halfeti", "category": "Deneyim", "tags": ["tekne", "sular altı şehir", "manzara"], "distanceFromCenter": 120.0, "lat": 37.2500, "lng": 37.8700, "price": "medium", "rating": 4.8, "description": "Baraj suları altında kalan tarihi şehri tekneyle gezme deneyimi.", "description_en": "Experience of exploring the historic city submerged under dam waters by boat.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Sabah erken saatte gitmek daha az kalabalık.", "tips_en": "Going early morning is less crowded."},
    {"name": "Fırat Nehri Kıyısı", "name_en": "Euphrates River Bank", "area": "Birecik", "category": "Manzara", "tags": ["nehir", "manzara", "günbatımı"], "distanceFromCenter": 80.0, "lat": 37.0300, "lng": 37.9800, "price": "free", "rating": 4.5, "description": "Tarihi Fırat Nehri kenarında yürüyüş ve manzara keyfi.", "description_en": "Walking and view enjoyment by the historic Euphrates River.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Kelaynak kuşlarını görmek için Birecik'e gelin.", "tips_en": "Come to Birecik to see the bald ibis birds."},
    {"name": "Zeugma Cam Terası", "name_en": "Zeugma Glass Terrace", "area": "Nizip", "category": "Manzara", "tags": ["cam", "manzara", "modern"], "distanceFromCenter": 50.0, "lat": 37.0800, "lng": 37.8500, "price": "medium", "rating": 4.4, "description": "Zeugma arkeolojik alanının üzerinde cam teras manzara noktası.", "description_en": "Glass terrace viewpoint above the Zeugma archaeological site.", "bestTime": "Gün batımı", "bestTime_en": "Sunset", "tips": "Fotoğraf çekmek için en iyi saatler gün batımı.", "tips_en": "Best hours for photography are sunset."},
    {"name": "Birecik Kelaynak Üretim İstasyonu", "name_en": "Birecik Bald Ibis Breeding Station", "area": "Birecik", "category": "Doğa", "tags": ["kuş", "nadir", "koruma"], "distanceFromCenter": 80.0, "lat": 37.0400, "lng": 37.9600, "price": "low", "rating": 4.6, "description": "Dünyada nadir bulunan kelaynak kuşlarının korunduğu ve üretildiği merkez.", "description_en": "Center where rare bald ibis birds in the world are protected and bred.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Kuşlar sabah daha aktiftir.", "tips_en": "Birds are more active in the morning."},
    {"name": "Gaziantep Üniversitesi Botanik Parkı", "name_en": "Gaziantep University Botanical Park", "area": "Şehitkamil", "category": "Park", "tags": ["bitki", "üniversite", "eğitim"], "distanceFromCenter": 8.0, "lat": 37.0400, "lng": 37.4200, "price": "free", "rating": 4.3, "description": "Üniversite kampüsünde, nadir bitki türlerinin bulunduğu park.", "description_en": "Park with rare plant species on university campus.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Hafta içi daha sakin, öğrenci olmasa bile girebilirsiniz.", "tips_en": "Calmer on weekdays, you can enter even if not a student."}
]

# BATCH 12: MORE SHOPPING & EXPERIENCES
batch_12 = [
    {"name": "Antep Fıstığı Fabrika Turu", "name_en": "Antep Pistachio Factory Tour", "area": "Şehitkamil", "category": "Deneyim", "tags": ["fabrika", "fıstık", "üretim"], "distanceFromCenter": 5.0, "lat": 37.0500, "lng": 37.3200, "price": "free", "rating": 4.5, "description": "Fıstık işleme fabrikasını gezme ve taze fıstık tadım fırsatı.", "description_en": "Opportunity to tour pistachio processing factory and taste fresh pistachios.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Önceden telefon ile rezervasyon yapın.", "tips_en": "Make reservation by phone in advance."},
    {"name": "Gaziantep Kebap Atölyesi", "name_en": "Gaziantep Kebab Workshop", "area": "Şahinbey", "category": "Deneyim", "tags": ["kurs", "kebap", "aşçılık"], "distanceFromCenter": 0.5, "lat": 37.0640, "lng": 37.3840, "price": "high", "rating": 4.7, "description": "Profesyonel şeflerden kebap yapımı öğrenme kursu.", "description_en": "Course to learn kebab making from professional chefs.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "En az 2 kişi olmalısınız, online rezervasyon şart.", "tips_en": "You need to be at least 2 people, online reservation required."},
    {"name": "Nakış Atölyesi", "name_en": "Embroidery Workshop", "area": "Şahinbey", "category": "Deneyim", "tags": ["el sanatı", "nakış", "kadın"], "distanceFromCenter": 0.4, "lat": 37.0620, "lng": 37.3815, "price": "medium", "rating": 4.4, "description": "Geleneksel Antep nakışı öğrenebileceğiniz kültür merkezi.", "description_en": "Cultural center where you can learn traditional Antep embroidery.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Kadın kooperatiflerinin eserleri satılık.", "tips_en": "Works of women's cooperatives are for sale."},
    {"name": "Sanko Park AVM", "name_en": "Sanko Park Mall", "area": "Şehitkamil", "category": "Alışveriş", "tags": ["avm", "modern", "sinema"], "distanceFromCenter": 4.0, "lat": 37.0850, "lng": 37.3500, "price": "variable", "rating": 4.3, "description": "Şehrin en büyük modern alışveriş merkezi, tüm markalar mevcut.", "description_en": "City's largest modern shopping center, all brands available.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Yaz aylarında serin ortam için ideal.", "tips_en": "Ideal for cool environment in summer months."},
    {"name": "Prime Mall AVM", "name_en": "Prime Mall", "area": "Şehitkamil", "category": "Alışveriş", "tags": ["avm", "lüks", "restoran"], "distanceFromCenter": 5.0, "lat": 37.0900, "lng": 37.3400, "price": "variable", "rating": 4.4, "description": "Lüks markalar ve kaliteli restoranların bulunduğu alışveriş merkezi.", "description_en": "Shopping center with luxury brands and quality restaurants.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Üst katta güzel manzara restoranları var.", "tips_en": "There are nice view restaurants on the top floor."},
    {"name": "Yerel Pazar (Perşembe Pazarı)", "name_en": "Local Market (Thursday Market)", "area": "Şahinbey", "category": "Alışveriş", "tags": ["pazar", "taze", "yerel"], "distanceFromCenter": 1.0, "lat": 37.0580, "lng": 37.3750, "price": "low", "rating": 4.5, "description": "Her Perşembe kurulan, taze sebze meyve ve yerel ürünlerin satıldığı pazar.", "description_en": "Market set up every Thursday, selling fresh vegetables fruits and local products.", "bestTime": "Sabah", "bestTime_en": "Morning", "tips": "Sabah erken gitmek en taze ürünleri bulmak için önemli.", "tips_en": "Going early morning is important to find freshest products."},
    {"name": "Salça Çarşısı", "name_en": "Tomato Paste Bazaar", "area": "Şahinbey", "category": "Alışveriş", "tags": ["salça", "biber", "yerel"], "distanceFromCenter": 0.5, "lat": 37.0615, "lng": 37.3810, "price": "low", "rating": 4.6, "description": "Ev yapımı domates ve biber salçalarının satıldığı özel çarşı.", "description_en": "Special bazaar where homemade tomato and pepper pastes are sold.", "bestTime": "Gündüz", "bestTime_en": "Daytime", "tips": "Acı biber salçası alırken 'orta' isteyin, 'acı' çok yakıcıdır.", "tips_en": "When buying hot pepper paste ask for 'medium', 'hot' is very burning."}
]

def enrich():
    filepath = 'assets/cities/gaziantep.json'
    all_new = batch_7 + batch_8 + batch_9 + batch_10 + batch_11 + batch_12
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    print(f"Loaded {len(data['highlights'])} existing places.")
    
    existing_names = {p['name'].lower() for p in data['highlights']}
    places_to_add = []
    
    for place in all_new:
        if place['name'].lower() in existing_names:
            print(f"Skipping: {place['name']}")
            continue
        print(f"Processing: {place['name']}")
        place_id = place['name'].lower().replace(' ', '-').replace('ç', 'c').replace('ğ', 'g').replace('ı', 'i').replace('ö', 'o').replace('ş', 's').replace('ü', 'u').replace('(', '').replace(')', '')
        place['id'] = place_id
        photo_url = get_google_photo_url(place['name'])
        if not photo_url and 'name_en' in place:
            photo_url = get_google_photo_url(place['name_en'])
        place['imageUrl'] = photo_url or "https://images.unsplash.com/photo-1555990538-dca68da33989?q=80&w=800"
        place['source'] = 'google' if photo_url else 'unsplash_fallback'
        places_to_add.append(place)
        time.sleep(0.3)
    
    data['highlights'].extend(places_to_add)
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nAdded {len(places_to_add)} new places. Total: {len(data['highlights'])}")

if __name__ == "__main__":
    enrich()
