import json
import os

new_amsterdam_final = [
    {
        "name": "Coster Diamonds",
        "name_en": "Coster Diamonds",
        "area": "Museumplein",
        "category": "Deneyim",
        "tags": ["elmas", "tarih", "mücevher", "tours"],
        "distanceFromCenter": 1.5,
        "lat": 52.3582,
        "lng": 4.8829,
        "price": "free",
        "rating": 4.5,
        "description": "Dünyanın en eski elmas parlatma fabrikalarından biri. Elmasların nasıl kesildiğini görebileceğiniz ücretsiz turlar sunar.",
        "description_en": "One of the world's oldest diamond polishing factories. Offers free tours where you can see how diamonds are cut.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Ünlü Koh-i-Noor elmasının tarihini burada öğrenebilirsiniz.",
        "tips_en": "Learn about the history of the famous Koh-i-Noor diamond here."
    },
    {
        "name": "Amsterdam Museum",
        "name_en": "Amsterdam Museum",
        "area": "Centrum",
        "category": "Müze",
        "tags": ["tarih", "şehir", "kültür", "sergi"],
        "distanceFromCenter": 0.4,
        "lat": 52.3702,
        "lng": 4.8897,
        "price": "medium",
        "rating": 4.6,
        "description": "Amsterdam'ın küçük bir balıkçı köyünden bugünkü dünya kentine dönüşümünü anlatan etkileyici şehir müzesi.",
        "description_en": "An impressive museum tracing Amsterdam's evolution from a small fishing village to today's global city.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Eski yetimhane binasının mimarisi ve avluları görülmeye değerdir.",
        "tips_en": "The architecture and courtyards of the former orphanage building are well worth seeing."
    },
    {
        "name": "Pathé Tuschinski",
        "name_en": "Pathé Tuschinski",
        "area": "Centrum",
        "category": "Tarihi",
        "tags": ["sinema", "art deco", "mimari", "lüks"],
        "distanceFromCenter": 0.5,
        "lat": 52.3667,
        "lng": 4.8942,
        "price": "medium",
        "rating": 4.9,
        "description": "Dünyanın en güzel sinemalarından biri olarak kabul edilen Art Deco ve Art Nouveau tarzı muhteşem tarihi tiyatro ve sinema salonu.",
        "description_en": "Considered one of the world's most beautiful cinemas, a magnificent historic theater and movie palace in Art Deco and Art Nouveau style.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam (film seansı)",
        "bestTime_en": "Evening (for a movie)",
        "tips": "Grote Zaal (Büyük Salon) için bir bilet alıp atmosferin tadını çıkarın.",
        "tips_en": "Book a ticket for the Grote Zaal (Great Hall) to fully appreciate the atmosphere."
    },
    {
        "name": "P.C. Hooftstraat",
        "name_en": "P.C. Hooftstraat",
        "area": "Oud-Zuid",
        "category": "Alışveriş",
        "tags": ["lüks", "moda", "tasarım", "prestij"],
        "distanceFromCenter": 1.5,
        "lat": 52.3597,
        "lng": 4.8778,
        "price": "high",
        "rating": 4.4,
        "description": "Amsterdam'ın en lüks alışveriş caddesi. Dünyaca ünlü moda evlerinin ve prestijli markaların amiral gemisi mağazaları burada bulunur.",
        "description_en": "Amsterdam's most luxurious shopping street, home to flagship stores of world-famous fashion houses and prestigious brands.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Alışveriş yapmasanız bile vitrinlerin estetiği ve caddenin şık atmosferi için yürüyüşe değerdir.",
        "tips_en": "Worth a stroll just for the store window aesthetics and the street's elegant atmosphere, even without shopping."
    },
    {
        "name": "OBA Oosterdok (Amsterdam Halk Kütüphanesi)",
        "name_en": "OBA Library",
        "area": "Centrum-East",
        "category": "Deneyim",
        "tags": ["kütüphane", "manzara", "kültür", "ücretsiz"],
        "distanceFromCenter": 1.2,
        "lat": 52.3768,
        "lng": 4.9083,
        "price": "free",
        "rating": 4.7,
        "description": "Avrupa'nın en büyük halk kütüphanelerinden biri. En üst katındaki teras kafesi, şehre bakan harika ve ücretsiz bir manzara sunar.",
        "description_en": "One of Europe's largest public libraries. Its top-floor terrace cafe offers a magnificent and free view overlooking the city.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Dinlenmek, ücretsiz Wi-Fi kullanmak veya sadece manzara izlemek için en iyi duraklardan biridir.",
        "tips_en": "One of the best stops for resting, utilizing free Wi-Fi, or simply enjoying the view."
    },
    {
        "name": "Westergas",
        "name_en": "Westergas",
        "area": "Westerpark",
        "category": "Deneyim",
        "tags": ["kültür", "sanat", "yemek", "park"],
        "distanceFromCenter": 2.0,
        "lat": 52.3861,
        "lng": 4.8697,
        "price": "free",
        "rating": 4.6,
        "description": "Eski bir havagazı fabrikasının dönüştürülmesiyle oluşan devasa kültür ve eğlence kompleksi. Sinema, galeriler ve şık restoranlar barındırır.",
        "description_en": "A massive cultural and entertainment complex created from a repurposed gasworks factory. Houses a cinema, galleries, and chic restaurants.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Her ayın ilk Pazar günü kurulan 'Sunday Market' yerel sanatçılar ve yiyecekler için harikadır.",
        "tips_en": "The 'Sunday Market' held on the first Sunday of every month is great for local art and food."
    },
    {
        "name": "Wynand Fockink",
        "name_en": "Wynand Fockink",
        "area": "Centrum",
        "category": "Bar",
        "tags": ["jenever", "likör", "tarihi", "deneyim"],
        "distanceFromCenter": 0.2,
        "lat": 52.3719,
        "lng": 4.8942,
        "price": "low",
        "rating": 4.8,
        "description": "1679'dan beri hizmet veren geleneksel Hollanda içkisi Jenever tadım evi ve likör imalathanesi.",
        "description_en": "A traditional Dutch Jenever tasting room and liqueur distillery serving since 1679.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "İçkinizi içerken bardağa eğilip 'ilk yudumu' ellerinizi kullanmadan almanız gelenektir.",
        "tips_en": "Tradition dictates leaning over the bar to take the 'first sip' without using your hands."
    },
    {
        "name": "Moeders (Anneler) Restoranı",
        "name_en": "Moeders Restaurant",
        "area": "Oud-West/Jordaan",
        "category": "Restoran",
        "tags": ["geleneksel", "ev yemeği", "otantik", "anne"],
        "distanceFromCenter": 1.5,
        "lat": 52.3697,
        "lng": 4.8767,
        "price": "medium",
        "rating": 4.6,
        "description": "Duvarları dünyanın dört bir yanından gelen anne fotoğraflarıyla kaplı, geleneksel Hollanda ev yemekleri sunan çok samimi bir mekan.",
        "description_en": "A very cozy spot serving traditional Dutch home cooking, with walls covered by photos of mothers from all around the world.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Mutlaka rezervasyon yaptırın ve gerçek Hollanda lezzeti 'Stampot' deneyin.",
        "tips_en": "Be sure to make a reservation and try the 'Stamppot', a true Dutch delicacy."
    },
    {
        "name": "IJ-Hallen Flea Market",
        "name_en": "IJ-Hallen",
        "area": "Noord",
        "category": "Deneyim",
        "tags": ["pazar", "vintage", "avrupa'nın en büyüğü", "ikinci el"],
        "distanceFromCenter": 4.0,
        "lat": 52.4002,
        "lng": 4.8943,
        "price": "low",
        "rating": 4.5,
        "description": "Avrupa'nın en büyük bit pazarı. Ayda sadece bir veya iki kez devasa endüstriyel hangarlarda kurulur.",
        "description_en": "Europe's largest flea market, held only once or twice a month in massive industrial hangars.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Sabah (erken saatler)",
        "bestTime_en": "Early morning",
        "tips": "Ziyaret tarihlerinizi web sitesinden kontrol edin ve yanınıza nakit para alın.",
        "tips_en": "Check the dates on their website and remember to bring cash."
    },
    {
        "name": "Brouwerij de Prael",
        "name_en": "Brouwerij de Prael",
        "area": "Red Light District",
        "category": "Bar",
        "tags": ["bira", "yerel", "sosyal sorumluluk", "tarihi bina"],
        "distanceFromCenter": 0.5,
        "lat": 52.3753,
        "lng": 4.8994,
        "price": "low",
        "rating": 4.6,
        "description": "Kırmızı Fener Mahallesi'nde yer alan, sosyal sorumluluk projesi olarak kurulan ve harika bira çeşitleri sunan butik bir bira fabrikası ve barı.",
        "description_en": "A boutique brewery and bar located in the Red Light District, established as a social enterprise and offering an excellent variety of beers.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Tadım setini (tasting flight) alarak farklı yerel biraları deneyebilirsiniz.",
        "tips_en": "Order a tasting flight to sample a variety of different local beers."
    },
    {
        "name": "Manneken Pis (Fries) Amsterdam",
        "name_en": "Manneken Pis Fries",
        "area": "Centrum",
        "category": "Deneyim",
        "tags": ["patates", "sokak yemeği", "ünlü", "lezzetli"],
        "distanceFromCenter": 0.5,
        "lat": 52.3751,
        "lng": 4.8948,
        "price": "low",
        "rating": 4.5,
        "description": "Hollanda'nın en popüler 'patates kızartması' dükkanlarından biri. Sos seçenekleri ve devasa porsiyonlarıyla her zaman önünde uzun bir sıra vardır.",
        "description_en": "One of the Netherlands' most popular 'fries' shops. Always has a long queue due to its vast selection of sauces and massive portions.",
        "imageUrl": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=800",
        "bestTime": "Öğlen",
        "bestTime_en": "Noon",
        "tips": "L şeklinde paket servis yapılan patateslerinizi Dam Meydanı'na doğru yürürken yiyebilirsiniz.",
        "tips_en": "Enjoy your cone-packaged fries as you stroll toward Dam Square."
    },
    {
        "name": "Zaanse Schans",
        "name_en": "Zaanse Schans",
        "area": "North (Day Trip)",
        "category": "Tarihi",
        "tags": ["yel değirmenleri", "peynir", "tarih", "doğa"],
        "distanceFromCenter": 15.0,
        "lat": 52.4731,
        "lng": 4.8217,
        "price": "free",
        "rating": 4.8,
        "description": "Gerçek Hollanda kökenlerini görebileceğiniz tarihi yel değirmenleri, peynir tadım dükkanları ve geleneksel evlerin olduğu açık hava müzesi köyü.",
        "description_en": "An open-air museum village where you can find historic windmills, cheese tasting shops, and traditional houses that showcase true Dutch heritage.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Trenle sadece 15 dakikada ulaşılabilir; yel değirmenlerinin içine girmek ücrete tabidir.",
        "tips_en": "Only a 15-minute train ride away; while entering the village is free, touring the inside of a windmill requires a ticket."
    },
    {
        "name": "Muiden Castle (Muiderslot)",
        "name_en": "Muiderslot Castle",
        "area": "Muiden (Day Trip)",
        "category": "Tarihi",
        "tags": ["kale", "ortaçağ", "su kalesi", "bahçe"],
        "distanceFromCenter": 12.0,
        "lat": 52.3342,
        "lng": 5.0714,
        "price": "medium",
        "rating": 4.7,
        "description": "Hollanda'nın en iyi korunmuş ve en ikonik ortaçağ su kalesi. Hendekleri, kuleleri ve tarihi bahçesiyle bir masal kalesi andırır.",
        "description_en": "The Netherlands' best-preserved and most iconic medieval moated castle. With its moats, towers, and historic gardens, it looks like something out of a fairytale.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Öğleden önce",
        "bestTime_en": "Before noon",
        "tips": "Amsterdam'dan bisikletle gitmek veya kaleden nehir manzarasını izlemek harika bir deneyimdir.",
        "tips_en": "Cycling there from Amsterdam or enjoying the river views from the ramparts is a wonderful experience."
    }
]

def enrich_amsterdam_final():
    filepath = 'assets/cities/amsterdam.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_amsterdam_final:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_amsterdam_final()
print(f"Amsterdam reached its final unique highlight count: {count}")
# I'll double check if I hit 100.
