import json
import os

new_milano_batch2 = [
    {
        "name": "Piazza Gae Aulenti",
        "name_en": "Gae Aulenti Square",
        "area": "Porta Nuova",
        "category": "Manzara",
        "tags": ["modern", "mimari", "gökdelen", "meydan"],
        "distanceFromCenter": 1.6,
        "lat": 45.4838,
        "lng": 9.1895,
        "price": "free",
        "rating": 4.8,
        "description": "Milano'nun fütüristik kalbi. Yüksek gökdelenlerin ortasında, ışıklı fıskiyeleri ve modern tasarımıyla kentin yeni simgesi.",
        "description_en": "The futuristic heart of Milan, a circular raised plaza surrounded by glass skyscrapers. Famous for its light-reflecting fountains and skyline views.",
        "imageUrl": "https://images.unsplash.com/photo-1520440229-6469a149ac59?w=800",
        "bestTime": "Akşam (ışıklandırma)",
        "bestTime_en": "Evening (lighting)",
        "tips": "Meydandaki fıskiyelerin etrafında oturup kalkan su gösterilerini izlemek çok keyiflidir, özellikle gece ışıklandırması muazzamdır.",
        "tips_en": "Sit by the infinity fountains for some of the best urban photography opportunities in Italy, especially as the sunset reflects off the towers."
    },
    {
        "name": "Biblioteca degli Alberi (BAM)",
        "name_en": "Library of Trees Park",
        "area": "Porta Nuova",
        "category": "Park",
        "tags": ["botanik", "modern park", "yeşil", "yürüyüş"],
        "distanceFromCenter": 1.7,
        "lat": 45.4845,
        "lng": 9.1905,
        "price": "free",
        "rating": 4.7,
        "description": "Porta Nuova gökdelenlerinin altında, 500'den fazla ağaç ve yüzbinlerce bitki türüne ev sahipliği yapan yenilikçi bir botanik park.",
        "description_en": "An innovative urban park featuring over 500 trees and 135,000 plants, acting as a green bridge between the modern towers of Porta Nuova.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Bosco Verticale'yi (Dikey Orman) en güzel bu parkın içinden fotoğraflayabilirsiniz.",
        "tips_en": "The best views of the Vertical Forest towers are from the central paths of this park; it's a favorite spot for local office workers' lunch breaks."
    },
    {
        "name": "Arco della Pace",
        "name_en": "Arch of Peace",
        "area": "Sempione",
        "category": "Tarihi",
        "tags": ["anıt", "neoklasik", "meydan", "manzara"],
        "distanceFromCenter": 1.5,
        "lat": 45.4758,
        "lng": 9.1725,
        "price": "free",
        "rating": 4.6,
        "description": "Sempione Parkı'nın sonunda yer alan, Napolyon döneminde başlatılan ve barışı simgeleyen görkemli neoklasik zafer takı.",
        "description_en": "A monumental neoclassical triumphal arch located at the entrance to Corso Sempione, symbolizing European peace and marking a key historic gateway to the city.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Akşamüzeri",
        "bestTime_en": "Late afternoon",
        "tips": "Takın etrafındaki meydan aperitivo saatlerinde çok canlıdır, yerel barları keşfedebilirsiniz.",
        "tips_en": "The area around the arch is a hotspot for Milan's nightlife; grab a drink at one of the nearby bars and enjoy the monument's evening illumination."
    },
    {
        "name": "Basilica di Santa Maria delle Grazie (Mimarisi)",
        "name_en": "Santa Maria delle Grazie Architecture",
        "area": "Magenta",
        "category": "Tarihi",
        "tags": ["unesco", "rönesans", "mimari", "kilise"],
        "distanceFromCenter": 1.5,
        "lat": 45.4659,
        "lng": 9.1702,
        "price": "free",
        "rating": 4.8,
        "description": "Son Akşam Yemeği freskine ev sahipliği yapan, UNESCO Dünya Mirası listesindeki büyüleyici Rönesans kilisesi.",
        "description_en": "A UNESCO World Heritage site and a masterpiece of Renaissance architecture, famous for housing Leonardo da Vinci's 'The Last Supper' in its refectory.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzeye biletiniz olmasa bile kilisenin içini ve Bramante tarafından tasarlanan muazzam kubbeyi ücretsiz görebilirsiniz.",
        "tips_en": "Even without a ticket for the painting, the main church and its stunning cloister designed by Bramante are free to visit and visually spectacular."
    },
    {
        "name": "Corso Como",
        "name_en": "Corso Como Street",
        "area": "Garibaldi",
        "category": "Alışveriş",
        "tags": ["moda", "gece hayatı", "yürüyüş", "prestij"],
        "distanceFromCenter": 1.7,
        "lat": 45.4815,
        "lng": 9.1882,
        "price": "high",
        "rating": 4.5,
        "description": "Milano'nun en şık yaya caddelerinden biri. Tasarım mağazaları, sanat galerileri ve kentin en ünlü gece kulüplerinin adresidir.",
        "description_en": "One of Milan's trendiest pedestrian streets, home to high-end boutiques, art venues, and the city's most exclusive nightclubs.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Gündüz alışveriş, gece ise eğlence için kentin nabzının attığı yerdir.",
        "tips_en": "A great place for people-watching; start your walk at Piazza Gae Aulenti and head south through this vibrant avenue."
    },
    {
        "name": "Via Dante",
        "name_en": "Via Dante",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["yürüyüş", "saray", "kafe", "merkezi"],
        "distanceFromCenter": 0.3,
        "lat": 45.4675,
        "lng": 9.1845,
        "price": "medium",
        "rating": 4.6,
        "description": "Duomo ile Sforza Kalesi'ni birbirine bağlayan, görkemli 19. yüzyıl saraylarıyla çevrili, kentin en popüler yaya yolu.",
        "description_en": "An elegant pedestrian boulevard connecting the Duomo to the Sforza Castle, lined with grand 19th-century buildings and outdoor cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yol üzerindeki küçük kitapçılara ve butiklere bakarken kale manzarasının tadını çıkarın.",
        "tips_en": "Perfect for a slow stroll between the two main landmarks; the perspective view of the Sforza Castle from here is iconic."
    },
    {
        "name": "Piazza Mercanti",
        "name_en": "Piazza Mercanti",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["ortaçağ", "gizli", "meydan", "mimari"],
        "distanceFromCenter": 0.1,
        "lat": 45.4645,
        "lng": 9.1878,
        "price": "free",
        "rating": 4.7,
        "description": "Duomo'nun hemen yanı başında, zamanda yolculuk yapmışsınız hissi veren, korunmuş bir ortaçağ meydanı.",
        "description_en": "A hidden medieval square just steps from the Duomo, offering a quiet, atmospheric escape with perfectly preserved gothic and renaissance buildings.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Meydandaki sütunlar arasındaki 'akustik hile'yi deneyin; karşı sütunlardaki kişilerle fısıldaşarak konuşabilirsiniz.",
        "tips_en": "Test the 'acoustic' trick: if you whisper into the columns at certain points, your voice travels clearly to someone on the opposite side."
    },
    {
        "name": "San Maurizio al Monastero Maggiore",
        "name_en": "San Maurizio Church",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["fresk", "sanat", "gizli hazine", "rönesans"],
        "distanceFromCenter": 0.5,
        "lat": 45.4658,
        "lng": 9.1788,
        "price": "free",
        "rating": 4.9,
        "description": "Dışarıdan çok sade görünen ancak içi tamamen muazzam fresklerle kaplı olduğu için 'Milano'nun Sistina Şapeli' olarak anılan kilise.",
        "description_en": "Commonly known as the 'Sistine Chapel of Milan,' this church contains an incredible cycle of 16th-century frescoes that cover almost every surface.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Giriş ücretsizdir. Fresklerin canlılığı ve detayları karşısında büyülenmeye hazırlıklı olun.",
        "tips_en": "Admission is free, though donations are appreciated. It's often overlooked by tourists, making it a peaceful artistic sanctuary."
    },
    {
        "name": "Naviglio Grande",
        "name_en": "Naviglio Grande",
        "area": "Navigli",
        "category": "Manzara",
        "tags": ["kanal", "aperitivo", "gece", "romantik"],
        "distanceFromCenter": 2.2,
        "lat": 45.4515,
        "lng": 9.1765,
        "price": "low",
        "rating": 4.5,
        "description": "Milano'nun hayatta kalan en eski ve en büyük kanalı. Akşamları aperitivo barları ve restoranlarıyla kentin en canlı bölgesidir.",
        "description_en": "The oldest and most important of Milan's canals, now the heart of the city's nightlife and famous for its eclectic mix of bars and vintage shops.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Gün batımı ve akşam",
        "bestTime_en": "Sunset and evening",
        "tips": "Kanal kenarındaki küçük sanatçı atölyelerini ve gizli bahçeleri keşfetmek için arka sokaklara da girin.",
        "tips_en": "Venture into the small side alleys (vicoli) to find hidden flower-filled courtyards and local artisan workshops."
    },
    {
        "name": "Vicolo dei Lavandai",
        "name_en": "Laundrymen's Alley",
        "area": "Navigli",
        "category": "Tarihi",
        "tags": ["kanal", "nostalji", "gelenek", "fotoğraf"],
        "distanceFromCenter": 2.3,
        "lat": 45.4512,
        "lng": 9.1755,
        "price": "free",
        "rating": 4.6,
        "description": "Navigli bölgesinde yer alan, 19. yüzyıla kadar çamaşır yıkayanların kullandığı tarihi ve çok fotojenik bir köşe.",
        "description_en": "A charming and historic corner of the Navigli where laundry was washed until the 1950s; it's one of the most photographed spots along the canal.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sokağın sonundaki eski çamaşır teknelerini ve geleneksel Milano evlerini görebilirsiniz.",
        "tips_en": "Look for the old stone washing troughs; the area has a timeless, village-like feel that contrasts with modern Milan."
    },
    {
        "name": "Naviglio Pavese",
        "name_en": "Naviglio Pavese",
        "area": "Navigli",
        "category": "Deneyim",
        "tags": ["kanal", "bar", "lokal", "gece hayatı"],
        "distanceFromCenter": 2.5,
        "lat": 45.4485,
        "lng": 9.1785,
        "price": "low",
        "rating": 4.4,
        "description": "Naviglio Grande'den daha dar ve daha az turistik olan, samimi barların ve yerel halkın favori mekanlarının bulunduğu ikinci kanal.",
        "description_en": "The second main canal in the Navigli district, narrower and slightly more low-key than its famous neighbor, popular for authentic local bars.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam geç saatler",
        "bestTime_en": "Late evening",
        "tips": "Buradaki kokteyl barları daha butik ve yaratıcı içecekler sunma eğilimindedir.",
        "tips_en": "This canal is known for its excellent selection of craft beer taprooms and specialized gin bars; it's less crowded on weeknights."
    },
    {
        "name": "Quadrilatero del Silenzio",
        "name_en": "The Silent Quad",
        "area": "Monforte",
        "category": "Tarihi",
        "tags": ["mimari", "sakin", "flamingolar", "gizli"],
        "distanceFromCenter": 1.1,
        "lat": 45.4715,
        "lng": 9.2025,
        "price": "free",
        "rating": 4.7,
        "description": "Lüks moda dükkanlarının hemen arkasında, sessizliği ve muazzam Art Nouveau villalarıyla ünlü saklı mahalle.",
        "description_en": "A secret neighborhood near the busy shopping districts, characterized by stunning Art Nouveau architecture and an unexpected sense of tranquility.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Villa Invernizzi'nin bahçesinde yaşayan pembe flamingoları mutlaka görün!",
        "tips_en": "Walk past Villa Invernizzi to see pink flamingos living in a private garden in the middle of the city—a very surreal Milanese sight."
    },
    {
        "name": "Palazzo Serbelloni",
        "name_en": "Palazzo Serbelloni",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["saray", "neoklasik", "napolyon", "mimari"],
        "distanceFromCenter": 0.8,
        "lat": 45.4682,
        "lng": 9.1995,
        "price": "free",
        "rating": 4.4,
        "description": "Napolyon Bonapart'ın bir dönem yaşadığı, Milano'nun en görkemli neoklasik saraylarından biri.",
        "description_en": "A grand neoclassical palace where Napoleon Bonaparte once stayed; it remains one of the city's most impressive aristocratic residences.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Genellikle dışarıdan görülür ancak moda haftası gibi dönemlerde içindeki özel etkinlikler için açılabilir.",
        "tips_en": "While mostly private, look for special events or fashion presentations that occasionally allow public access to the grand ballroom."
    },
    {
        "name": "Bosco Verticale (Dikey Orman)",
        "name_en": "Vertical Forest",
        "area": "Porta Nuova",
        "category": "Manzara",
        "tags": ["sürdürülebilir", "mimari", "modern", "ağaçlar"],
        "distanceFromCenter": 1.7,
        "lat": 45.4858,
        "lng": 9.1904,
        "price": "free",
        "rating": 4.9,
        "description": "Balkonlarında yüzlerce ağaç ve bitki barındıran, dünyanın en ödüllü ve ikonik ekolojik gökdelenleri.",
        "description_en": "A revolutionary residential project featuring two towers covered in over 900 trees, an internationally recognized symbol of sustainable urban design.",
        "imageUrl": "https://images.unsplash.com/photo-1520440229-6469a149ac59?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kentin her yerinden görülebilir ama en iyi açı Biblioteca degli Alberi parkının ortasından yakalanır.",
        "tips_en": "Visit in different seasons to see how the 'facade' changes colors from vivid green in spring to fiery red in autumn."
    },
    {
        "name": "Excelsior Milano",
        "name_en": "Excelsior Milano",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["lüks", "tasarım", "gurme", "teknoloji"],
        "distanceFromCenter": 0.2,
        "lat": 45.4655,
        "lng": 9.1925,
        "price": "high",
        "rating": 4.3,
        "description": "Eski bir sinema binasından dönüştürülen, fütüristik tasarımıyla dikkat çeken lüks bir konsept mağaza.",
        "description_en": "A futuristic luxury department store housed in a former cinema, combining high-fashion, high-tech beauty gadgets, and a gourmet food hall.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "En alt kattaki gurme market (Eat's) Milano'nun en kaliteli yerel ürünlerini bulmak için harikadır.",
        "tips_en": "The food gallery in the basement is a designer pantry full of exceptional Italian delicacies and unique food gift items."
    },
    {
        "name": "Rinascente (Teras)",
        "name_en": "Rinascente Rooftop",
        "area": "Centro",
        "category": "Manzara",
        "tags": ["katedral manzara", "teras", "gurme", "lüks"],
        "distanceFromCenter": 0.1,
        "lat": 45.4652,
        "lng": 9.1915,
        "price": "medium",
        "rating": 4.7,
        "description": "Duomo'nun tam yanında, katedralin heykellerini göz hizasından görebileceğiniz muazzam bir gurme terası.",
        "description_en": "A world-class food hall and terrace located on the top floor of the Rinascente department store, offering unparalleled views of the Duomo's spires.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Lunch / Sunset",
        "bestTime_en": "Lunch / Sunset",
        "tips": "Teras kafelerinde bir kahve içmek, en pahalı biletli turlar kadar iyi bir katedral manzarası sunar.",
        "tips_en": "The outdoor heated seating area allows you to enjoy a drink right next to the cathedral's Gothic details even in winter."
    },
    {
        "name": "Cova (Monte Napoleone)",
        "name_en": "Cova Pastry",
        "area": "Fashion Quad",
        "category": "Kafe",
        "tags": ["tarihi", "lüks", "tatlı", "prestij"],
        "distanceFromCenter": 0.6,
        "lat": 45.4682,
        "lng": 9.1945,
        "price": "high",
        "rating": 4.5,
        "description": "1817'den beri hizmet veren, Milano'nun en prestijli caddesinde moda dünyasının buluşma noktası olan efsanevi pastane.",
        "description_en": "Established in 1817, this is one of Italy's oldest 'pasticcerie,' located in the heart of the luxury shopping district and famous for its elegance.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Sabah kahvesi",
        "bestTime_en": "Morning coffee",
        "tips": "Bar kısmında ayakta kahve içmek, İtalyan şıklığını yerinde deneyimlemek için harikadır.",
        "tips_en": "Drinking an espresso standing at the bar is a true Milanese ritual; try their signature panettone all year round."
    },
    {
        "name": "Prada Osservatorio",
        "name_en": "Prada Osservatorio",
        "area": "Centro",
        "category": "Müze",
        "tags": ["fotoğraf", "galeri", "mimari", "manzara"],
        "distanceFromCenter": 0.1,
        "lat": 45.4658,
        "lng": 9.1899,
        "price": "medium",
        "rating": 4.6,
        "description": "Galleria Vittorio Emanuele II'nin çatısında, kentin tam kalbinde yer alan çağdaş fotoğraf sergisi alanı.",
        "description_en": "A photography exhibition space by Fondazione Prada, located at the very peak of the Galleria, combining art with a unique urban perspective.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Buradan Galleria'nın cam tavanına ve Duomo meydanına bakış açısı benzersizdir.",
        "tips_en": "The entrance is a bit hidden; find the elevator within the Prada Men's store inside the Galleria to reach the top-floor sanctuary."
    },
    {
        "name": "Bar Luce",
        "name_en": "Bar Luce",
        "area": "Güney Milano",
        "category": "Kafe",
        "tags": ["wes anderson", "sinema", "tasarım", "renkli"],
        "distanceFromCenter": 3.7,
        "lat": 45.4452,
        "lng": 9.2092,
        "price": "medium",
        "rating": 4.8,
        "description": "Ünlü yönetmen Wes Anderson tarafından tasarlanan, 1950'lerin İtalyan kafelerini andıran masalsı bir mekan.",
        "description_en": "Designed by filmmaker Wes Anderson, this cafe at Fondazione Prada recreates the atmosphere of a typical 1950s Milanese bar with a cinematic palette.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Steve Zissou temalı langırtı oynamayı ve pasteller içindeki tatlılardan denemeyi unutmayın.",
        "tips_en": "Don't miss the Life Aquatic-themed pinball machine and take plenty of photos; it's arguably the most 'Instagrammable' cafe in the city."
    },
    {
        "name": "Navigli (Antika Pazarı)",
        "name_en": "Navigli Antique Market",
        "area": "Navigli",
        "category": "Alışveriş",
        "tags": ["antika", "vintage", "pazar", "koleksiyon"],
        "distanceFromCenter": 2.4,
        "lat": 45.4505,
        "lng": 9.1745,
        "price": "medium",
        "rating": 4.7,
        "description": "Her ayın son Pazar günü kurulan, İtalya'nın en büyük ve en kaliteli antika pazarlarından biri.",
        "description_en": "One of Italy's most prestigious antique fairs, held on the last Sunday of every month along the banks of the Naviglio Grande.",
        "imageUrl": "https://images.unsplash.com/photo-1543333346-bf0375179462?w=800",
        "bestTime": "Ayın son Pazar günü",
        "bestTime_en": "Last Sunday of the month",
        "tips": "Gerçekten değerli vintage saatler, mobilyalar ve sanat eserleri bulabilirsiniz; pazarlık yapmak şarttır.",
        "tips_en": "Arrive early (9 AM) for the best finds; it spans nearly 2 kilometers and features over 400 specialized dealers."
    },
    {
        "name": "Piazza del Carmine",
        "name_en": "Piazza del Carmine",
        "area": "Brera",
        "category": "Tarihi",
        "tags": ["meydan", "brera", "sessiz", "romantik"],
        "distanceFromCenter": 0.6,
        "lat": 45.4715,
        "lng": 9.1855,
        "price": "free",
        "rating": 4.6,
        "description": "Brera'nın kalbinde, görkemli bir kiliseye bakan, sessiz ve kentin en romantik atmosferine sahip meydanı.",
        "description_en": "A beautiful, car-free piazza in the Brera district, home to a grand 15th-century church and surrounded by elegant boutiques and bistros.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meydandaki God Speed heykelini inceleyin, akşamları çok huzurlu bir dinlenme noktasıdır.",
        "tips_en": "Perfect for a quiet evening drink; the scale of the church facade illuminated at night is particularly impressive."
    },
    {
        "name": "Fiori Chiari & Fiori Oscuri",
        "name_en": "Brera Flower Streets",
        "area": "Brera",
        "category": "Tarihi",
        "tags": ["sokak", "sanat", "bohem", "tasarım"],
        "distanceFromCenter": 0.5,
        "lat": 45.4722,
        "lng": 9.1872,
        "price": "free",
        "rating": 4.7,
        "description": "Brera'nın ruhunu yansıtan, begonviller ve tasarım atölyeleriyle dolu birbirine paralel iki büyüleyici sokak.",
        "description_en": "The twin-soul streets of Brera, filled with high-end perfumeries, art supply shops, and some of the city's most charming outdoor dining.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Bu sokaklarda kaybolmak Milano'nun gerçek bohem yüzünü keşfetmek demektir.",
        "tips_en": "This is the best area to experience the 'old world' charm of Milan; look out for the fortune tellers who often set up shop here in the evenings."
    },
    {
        "name": "L'Arabesque",
        "name_en": "L'Arabesque",
        "area": "Monforte",
        "category": "Kafe",
        "tags": ["vintage", "konsept", "lüks", "kültür"],
        "distanceFromCenter": 1.1,
        "lat": 45.4675,
        "lng": 9.2012,
        "price": "high",
        "rating": 4.5,
        "description": "50'lerin stilini yansıtan, kitapçıdan parfümeriye kadar her şeyin özenle seçildiği çok şık bir tasarım kafe ve mağaza.",
        "description_en": "A multi-disciplinary concept space dedicated to 1950s elegance, featuring a vintage furniture gallery, a library, and a sophisticated bistro.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Milano elitlerinin uğrak noktası olan bu mekanda kendinizi bir film setinde gibi hissedeceksiniz.",
        "tips_en": "A must-visit for lovers of mid-century aesthetics; the bookstore section has one of the best curated collections of fashion history in the country."
    },
    {
        "name": "Biblioteca Ambrosiana",
        "name_en": "Ambrosiana Library & Gallery",
        "area": "Centro",
        "category": "Müze",
        "tags": ["da vinci", "kitap", "rönesans", "sanat"],
        "distanceFromCenter": 0.2,
        "lat": 45.4638,
        "lng": 9.1852,
        "price": "medium",
        "rating": 4.8,
        "description": "Dünyanın en önemli kütüphanelerinden biri; içinde Da Vinci'nin orijinal çizimlerini (Codex Atlanticus) ve ünlü tabloları barındırır.",
        "description_en": "A historic library and art gallery housing masterpieces by Caravaggio and Leonardo da Vinci, including the legendary Codex Atlanticus diagrams.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Da Vinci'nin orijinal not defterlerini dünya üzerinde görebileceğiniz en iyi noktadır.",
        "tips_en": "It's much quieter than the Duomo or the Royal Palace; take your time in the Reading Room, one of the most solemn places in the city."
    },
    {
        "name": "Pasticceria Cucchi",
        "name_en": "Pasticceria Cucchi",
        "area": "Ticinese",
        "category": "Kafe",
        "tags": ["tarihi", "tatlı", "panettone", "klasik"],
        "distanceFromCenter": 1.4,
        "lat": 45.4605,
        "lng": 9.1765,
        "price": "medium",
        "rating": 4.6,
        "description": "1936'dan beri bozulmamış atmosferiyle, Milano'nun en gerçek ve samimi tarihi pastanelerinden biri.",
        "description_en": "A local landmark since 1936, this family-run pastry shop preserves the soul of 'old' Milan with its vintage decor and traditional recipes.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Hafta sonu sabahı",
        "bestTime_en": "Weekend morning",
        "tips": "Özellikle kış aylarında sıcak çikolata ve panettone ikilisi için kentin en iyi adresidir.",
        "tips_en": "A favorite for Sunday morning breakfast; try their famous fruit tarts or the traditional Milanese breakfast: cappuccino and a brioche."
    },
    {
        "name": "San Nazaro in Brolo",
        "name_en": "Basilica of San Nazaro",
        "area": "Centro / Crocetta",
        "category": "Tarihi",
        "tags": ["antik", "kilise", "mozaik", "gizli"],
        "distanceFromCenter": 0.7,
        "lat": 45.4592,
        "lng": 9.1932,
        "price": "free",
        "rating": 4.3,
        "description": "4. yüzyıldan kalma, kentin en eski kiliselerinden biri. Şaşırtıcı mimari katmanları ve sessizliğiyle etkileyicidir.",
        "description_en": "Founded by Saint Ambrose in 382 AD, this is one of the oldest churches in Milan, standing on the historic road to Rome.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Girişindeki Trivulzio Şapeli'nin heybetli anıtlarını incelemeyi unutmayın.",
        "tips_en": "The monumental chapel at the entrance is a rare example of Renaissance funerary architecture; it's a very peaceful detour from the busy shopping streets."
    },
    {
        "name": "Eataly Smeraldo",
        "name_en": "Eataly Smeraldo",
        "area": "Garibaldi",
        "category": "Alışveriş",
        "tags": ["gurme", "yiyecek", "hediyelik", "şarap"],
        "distanceFromCenter": 1.8,
        "lat": 45.4812,
        "lng": 9.1865,
        "price": "medium",
        "rating": 4.5,
        "description": "Eski bir tiyatro binasında yer alan, İtalyan gastronomisinin en iyilerini sunan devasa bir gurme market ve restoran kompleksi.",
        "description_en": "Housed in the historic Smeraldo theater, this is a multi-level paradise for Italian food lovers, offering everything from fresh pasta to rare regional wines.",
        "imageUrl": "https://images.unsplash.com/photo-1543333346-bf0375179462?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Genellikle canlı müzik performansları olur, sahnenin olduğu asma kat yemek yemek için en iyi yerdir.",
        "tips_en": "Don't miss the high-quality cheese aging room and the incredible bakery section; it's the best place to buy authentic edible souvenirs."
    },
    {
        "name": "Porta Ticinese (Antik Kapı)",
        "name_en": "Porta Ticinese Gate",
        "area": "Ticinese",
        "category": "Tarihi",
        "tags": ["kapı", "roma", "antik", "yürüyüş"],
        "distanceFromCenter": 1.2,
        "lat": 45.4578,
        "lng": 9.1805,
        "price": "free",
        "rating": 4.4,
        "description": "Milano'nun antik şehir duvarlarından kalma, neoklasik tarzda restore edilmiş görkemli giriş kapısı.",
        "description_en": "One of the original city gates of Milan, a monumental structure that marks the entrance to the vibrant Ticinese district leading to the Navigli.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kapının altından geçip Navigli'ye doğru yürümek kentin tarihi dokusunu hissettirir.",
        "tips_en": "The walk from this gate down to the canals is lined with independent boutiques and some of the best street food in Milan."
    },
    {
        "name": "L'Isola del Tesoro",
        "name_en": "Treasure Island Restaurant",
        "area": "Centro",
        "category": "Restoran",
        "tags": ["sardinya", "balık", "otantik", "gelenek"],
        "distanceFromCenter": 0.4,
        "lat": 45.4625,
        "lng": 9.1895,
        "price": "medium",
        "rating": 4.4,
        "description": "Şehrin merkezinde, Sardinya adasına özgü deniz mahsulleri ve geleneksel lezzetler sunan çok sevilen bir restoran.",
        "description_en": "A beloved Sardinian seafood restaurant in the city center, famous for its authentic island flavors and high-quality fresh ingredients.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Sardinya usulü 'Malloreddus' makarnasını mutlaka denemelisiniz.",
        "tips_en": "Ask for the daily specials; their seafood crudités are exceptional and the atmosphere is warmly traditional."
    },
    {
        "name": "Pasticceria Sissi",
        "name_en": "Pasticceria Sissi",
        "area": "Risorgimento",
        "category": "Kafe",
        "tags": ["brioche", "gizli bahçe", "lokal", "popüler"],
        "distanceFromCenter": 2.5,
        "lat": 45.4702,
        "lng": 9.2155,
        "price": "medium",
        "rating": 4.7,
        "description": "Kentin en iyi brioche'larını yapan, küçük bir iç bahçesi olan ve yerel halkın kahvaltı için kuyruğa girdiği butik pastane.",
        "description_en": "A charming local favorite hidden behind a simple facade, known for having the best custard-filled brioche and a secret ivy-covered patio.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kruvasanınızın (brioche) miktarını ve içeriğini isteğinize göre o an doldururlar.",
        "tips_en": "Order a 'brioche alla crema'; they fill it for you on the spot in front of your eyes. The back garden is a perfect morning sanctuary."
    },
    {
        "name": "Bagni Misteriosi",
        "name_en": "The Mysterious Baths",
        "area": "Porta Romana",
        "category": "Deneyim",
        "tags": ["havuz", "açık hava", "tasarım", "retro"],
        "distanceFromCenter": 2.2,
        "lat": 45.4575,
        "lng": 9.2045,
        "price": "medium",
        "rating": 4.8,
        "description": "1930'lardan kalma bir yüzme havuzunun muazzam bir tasarım restorasyonuyla dönüştürüldüğü, Milano'nun en şık yaz kaçış noktası.",
        "description_en": "A stunningly restored 1930s swimming complex that turns into a sophisticated social hub with outdoor theater and aperitivo in the evenings.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Gündüz yüzmek için, akşam ise havuz başında kokteyl içmek için kentin en havalı yerlerinden biridir.",
        "tips_en": "Check their schedule for evening concerts or outdoor movie nights; the reflection of the theater lights on the water is magical."
    },
    {
        "name": "Luini (Piazza San Fedele)",
        "name_en": "Luini Panzerotti",
        "area": "Centro",
        "category": "Deneyim",
        "tags": ["panzerotti", "sokak lezzeti", "gelenek", "kuyruk"],
        "distanceFromCenter": 0.2,
        "lat": 45.4655,
        "lng": 9.1908,
        "price": "low",
        "rating": 4.8,
        "description": "1888'den beri değişmeyen reçetesiyle kentin en meşhur kızarmış panzerotti dükkanı; her lokması bir Milano geleneğidir.",
        "description_en": "Since 1888, this bakery has been a Milanese legend for its panzerotti (fried dough pockets filled with tomato and mozzarella).",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Sıcak yiyin ve yanındaki San Fedele meydanındaki heykellerin yanında oturarak tadını çıkarın.",
        "tips_en": "The line is almost always long, but it moves very fast. Get the 'Classico' and eat it warm on the steps of the nearby Church of San Fedele."
    },
    {
        "name": "Mudec (Kültürler Müzesi)",
        "name_en": "Mudec Museum",
        "area": "Tortona",
        "category": "Müze",
        "tags": ["modern", "kültür", "mimari", "tasarım"],
        "distanceFromCenter": 3.2,
        "lat": 45.4518,
        "lng": 9.1614,
        "price": "medium",
        "rating": 4.5,
        "description": "David Chipperfield tarafından tasarlanan, fütüristik iç tasarımı ve dünya kültürlerine dair geçici sergileriyle ünlü modern müze.",
        "description_en": "Designed by star architect David Chipperfield, this museum is a minimalist masterpiece housing ethnographic collections and world-class temporary art shows.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Müzenin lobisindeki devasa cam dalga yapısı fotoğraf çekmek için harika bir fondur.",
        "tips_en": "Located in the heart of the Tortona design district; combine your visit with a walk through the nearby fashion showrooms."
    },
    {
        "name": "Bosco in Citta",
        "name_en": "Forest in the City",
        "area": "Batı Milano",
        "category": "Park",
        "tags": ["doğa", "göl", "bisiklet", "sessiz"],
        "distanceFromCenter": 7.5,
        "lat": 45.4855,
        "lng": 9.0985,
        "price": "free",
        "rating": 4.6,
        "description": "Kentin kalabalığından tamamen uzaklaşmak isteyenler için; göletler, meyve bahçeleri ve orman yollarından oluşan devasa bir doğa alanı.",
        "description_en": "A massive reforestation project that has created a wild forest within city limits, complete with lakes, walking paths, and community gardens.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Bisiklet kiralayıp gelmek, kentin gürültüsünü unutmak için yapabileceğiniz en iyi şeydir.",
        "tips_en": "Perfect for a long bike ride or a serious hike; it's one of the few places in Milan where you can feel truly immersed in nature."
    },
    {
        "name": "Naviglio Martesana",
        "name_en": "Martesana Canal",
        "area": "Kuzey Milano",
        "category": "Manzara",
        "tags": ["bisiklet yolu", "kanal", "yerel", "sessiz"],
        "distanceFromCenter": 4.5,
        "lat": 45.4985,
        "lng": 9.2155,
        "price": "free",
        "rating": 4.5,
        "description": "Turistik kanalların aksine, kuzeye doğru uzanan, yerel halkın bisiklete bindiği ve piknik yaptığı huzurlu bir 'yeşil' kanal.",
        "description_en": "Milan's 'quiet' canal, featuring a 30km bike path that leads out of the city through charming parks and historic small towns.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Bahar sabahları",
        "bestTime_en": "Spring mornings",
        "tips": "Kanal boyunca yürürken çok sevimli mahalle kafelerine ve gizli bahçelere rastlayacaksınız.",
        "tips_en": "Rent a bike and ride towards Cernusco sul Naviglio; the path is flat, safe, and incredibly scenic, passing by old aristocratic villas."
    },
    {
        "name": "Santa Maria presso San Satiro",
        "name_en": "San Satiro Church",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["perspektif", "görsel illüzyon", "rönesans", "gizli"],
        "distanceFromCenter": 0.2,
        "lat": 45.4628,
        "lng": 9.1885,
        "price": "free",
        "rating": 4.8,
        "description": "Bramante'nin dâhice perspektif hilesi sayesinde, küçücük bir kilisenin devasa görünmesini sağlayan optik illüzyonlu tarihi kilise.",
        "description_en": "Famous for Bramante's 'trompe l'oeil'—an optical illusion that makes a depth of only 97cm look like a massive, decorated choir of several meters.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Mimari bir göz yanılmasına şahit olmak için koro bölümüne yandan bakmayı unutmayın.",
        "tips_en": "Walk right up to the altar to realize that the 'long' room behind it is actually flat—it's one of the most famous architectural tricks in the world."
    },
    {
        "name": "Piazza della Scala",
        "name_en": "Piazza della Scala",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["opera", "heykel", "mimari", "merkez"],
        "distanceFromCenter": 0.2,
        "lat": 45.4668,
        "lng": 9.1898,
        "price": "free",
        "rating": 4.6,
        "description": "La Scala Opera binasına bakan, ortasında Leonardo da Vinci heykelinin bulunduğu asil ve tarihi meydan.",
        "description_en": "The elegant plaza home to the La Scala Opera House and the Palazzo Marino; the central statue of Leonardo da Vinci is a popular meeting point.",
        "imageUrl": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Galleria'nın bir çıkışı bu meydana açılır, geçiş yapmak için en şık yoldur.",
        "tips_en": "The connection between the Duomo and this square through the Galleria is the most majestic urban walk in Milan."
    },
    {
        "name": "Fondazione Luigi Rovati",
        "name_en": "Luigi Rovati Foundation",
        "area": "Venezia",
        "category": "Müze",
        "tags": ["etruscan", "tasarım", "mimari", "modern-antik"],
        "distanceFromCenter": 0.9,
        "lat": 45.4712,
        "lng": 9.2042,
        "price": "medium",
        "rating": 4.7,
        "description": "Antik Etrüsk eserlerini muazzam bir modern mimari ve ışıklandırmayla sunan, yeni açılmış çok etkileyici bir yer altı müzesi.",
        "description_en": "A newly opened museum that blends ancient Etruscan artifacts with cutting-edge contemporary design in an incredible subterranean architectural setting.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin tavan tasarımı ve atmosferi kentin en modern sergileme deneyimini sunar.",
        "tips_en": "The architecture by Mario Cucinella is worth the visit alone; the way light interacts with the stone walls creates a very mystical atmosphere."
    },
    {
        "name": "La Libera (Brera Restaurant)",
        "name_en": "La Libera",
        "area": "Brera",
        "category": "Restoran",
        "tags": ["geleneksel", "sıcak", "brera", "lokal"],
        "distanceFromCenter": 0.6,
        "lat": 45.4742,
        "lng": 9.1865,
        "price": "high",
        "rating": 4.5,
        "description": "Brera'nın en otantik köşelerinden birinde, eski tip İtalyan trattoria ruhunu yaşatan çok şık ve lezzetli bir restoran.",
        "description_en": "A quintessentially Milanese bistro that has remained timelessly chic, serving classic lombard dishes in a warm, wood-filled setting.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Cotoletta alla Milanese (Milano usulü şinitzel) burada denemeniz gereken klasiklerden biridir.",
        "tips_en": "Their Ossobuco and typical Milanese cutlet are legendary; it's a favorite spot for the local creative community and gallery owners."
    },
    {
        "name": "Galleria d'Arte Moderna (GAM)",
        "name_en": "Modern Art Gallery",
        "area": "Venezia",
        "category": "Müze",
        "tags": ["sanat", "saray", "park", "klasik"],
        "distanceFromCenter": 1.2,
        "lat": 45.4725,
        "lng": 9.2005,
        "price": "medium",
        "rating": 4.6,
        "description": "Villa Reale sarayının içinde yer alan, 19. yüzyıl İtalyan sanatının en iyi örneklerini görebileceğiniz muazzam bir galeri.",
        "description_en": "Housed in the magnificent Royal Villa, this gallery showcases a premier collection of 19th-century Italian and international painting and sculpture.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzeyi gezdikten sonra hemen yanındaki sadece çocuklu ailelere açık olan özel parkı (Giardini Pubblici) ziyaret edin.",
        "tips_en": "The villa overlooks a beautiful English-style garden; it's one of the most serene and high-end artistic visits in the city."
    },
    {
        "name": "Starbucks Reserve Roastery (Mimarisi)",
        "name_en": "Starbucks Roastery Architecture",
        "area": "Centro",
        "category": "Deneyim",
        "tags": ["tasarım", "kahve", "tarihi bina", "lüks"],
        "distanceFromCenter": 0.3,
        "lat": 45.4642,
        "lng": 9.1855,
        "price": "medium",
        "rating": 4.8,
        "description": "Eski bir Posta Ofisi binasında yer alan, dünyanın en büyük ve en güzel Roastery'lerinden biri; kahve fabrikasını andıran tasarımıyla büyüleyicidir.",
        "description_en": "Located in a grand former Post Office, this is arguably the world's most beautiful coffee roastery, featuring a fully functional industrial coffee mill.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "Klasik bir Starbucks kahvesi beklemeyin, burası çok daha 'high-end' ve deneysel bir kahve kültürü sunar.",
        "tips_en": "Check out the mezzanine cocktail bar (Arriviamo) in the evening for coffee-infused spirits and one of the best perspectives of the copper roaster."
    }
]

def enrich_milano_batch2():
    filepath = 'assets/cities/milano.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_milano_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    # Filter out Duplicates by normalize_name if possible (just in case)
    # But for now, let's keep it simple as cleanup_milano will run.
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_milano_batch2()
print(f"Milan now has {count} highlights.")
