import json
import os

new_floransa_batch2 = [
    {
        "name": "Gucci Garden Boutique",
        "name_en": "Gucci Garden Boutique",
        "area": "Piazza della Signoria",
        "category": "Alışveriş",
        "tags": ["moda", "tasarım", "özel koleksiyon", "lüks"],
        "distanceFromCenter": 0.2,
        "lat": 43.7697,
        "lng": 11.2568,
        "price": "high",
        "rating": 4.5,
        "description": "Sadece bu mağazada bulunan özel tasarım Gucci ürünlerinin satıldığı, moda evinin tarihini yansıtan büyüleyici bir butik.",
        "description_en": "A unique boutique selling exclusive Gucci items found only at this location, reflecting the fashion house's creative history.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Mağazaya girmek ücretsizdir, içindeki kütüphane ve özel yayınlar bölümünü mutlaka görün.",
        "tips_en": "Entry to the store is free; be sure to check the library and special publications section."
    },
    {
        "name": "Mercato di San Lorenzo (Leather Market)",
        "name_en": "San Lorenzo Outdoor Market",
        "area": "San Lorenzo",
        "category": "Alışveriş",
        "tags": ["deri", "pazar", "hediyelik", "geleneksel"],
        "distanceFromCenter": 0.3,
        "lat": 43.7760,
        "lng": 11.2530,
        "price": "medium",
        "rating": 4.2,
        "description": "San Lorenzo bazilikası etrafındaki sokaklarda kurulan, deri ceketlerden çantalara kadar her türlü deri ürünün bulunduğu devasa açık hava pazarı.",
        "description_en": "The sprawling outdoor market around the San Lorenzo Basilica, famous for leather goods ranging from jackets to bags and belts.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Pazarlık yapmayı unutmayın; genellikle ilk söylenen fiyatın çok altına inebilirsiniz.",
        "tips_en": "Don't forget to haggle; you can often get prices significantly lower than the first offer."
    },
    {
        "name": "Enoteca Pitti Gola e Cantina",
        "name_en": "Enoteca Pitti Gola e Cantina",
        "area": "Oltrarno",
        "category": "Restoran",
        "tags": ["şarap", "toskana", "pitti palace", "gurme"],
        "distanceFromCenter": 0.5,
        "lat": 43.7645,
        "lng": 11.2485,
        "price": "high",
        "rating": 4.8,
        "description": "Pitti Sarayı'na tam karşıdan bakan, en iyi Toskana şaraplarını ve onlara eşlik eden gurme küçük tabakları sunan şık bir enoteca.",
        "description_en": "Located directly across from Pitti Palace, this high-end wine bar specializes in top-tier Tuscan wines and gourmet pairings.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Akşamüzeri / Akşam",
        "bestTime_en": "Late afternoon / Evening",
        "tips": "Şarap tadım menüleri çok başarılıdır, uzman sommelierlerden tavsiye almaktan çekinmeyin.",
        "tips_en": "Their wine tasting flights are excellent; don't hesitate to ask for recommendations from their expert sommeliers."
    },
    {
        "name": "Gelateria La Carraia (Piazza Nazario Sauro)",
        "name_en": "Gelateria La Carraia 2",
        "area": "Oltrarno",
        "category": "Kafe",
        "tags": ["dondurma", "ucuz", "köprü manzara", "lokal"],
        "distanceFromCenter": 0.7,
        "lat": 43.7696,
        "lng": 11.2467,
        "price": "low",
        "rating": 4.7,
        "description": "Ponte alla Carraia köprüsünün hemen ayağında, cömert porsiyonları ve inanılmaz uygun fiyatlarıyla bilinen, yerlilerin de favorisi dondurmacı.",
        "description_en": "Located at the foot of the Carraia bridge, this gelateria is famous for its generous portions and authentic flavors at incredible prices.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Dondurmanızı alıp nehir kıyısında oturarak köprü manzarasının tadını çıkarın.",
        "tips_en": "Grab your gelato and sit along the river bank to enjoy the view of the bridges."
    },
    {
        "name": "I Fratellini",
        "name_en": "I Fratellini",
        "area": "Centro Storico",
        "category": "Deneyim",
        "tags": ["sandviç", "şarap", "sokak lezzeti", "tarihi"],
        "distanceFromCenter": 0.2,
        "lat": 43.7702,
        "lng": 11.2543,
        "price": "low",
        "rating": 4.8,
        "description": "1875'ten beri hizmet veren minicik bir dükkan. Kaldırımda ayakta durarak yediğiniz nefis Toskana sandviçleri ve bir kadeh şarap bir Floransa geleneğidir.",
        "description_en": "A tiny hole-in-the-wall serving delicious Tuscan sandwiches and glasses of wine since 1875. Standing on the sidewalk to eat is part of the charm.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Kadeh şarabınızı bitirdikten sonra kadehi dükkanın yanındaki küçük ahşap raflara bırakmayı unutmayın.",
        "tips_en": "After finishing your wine, place your glass on the small wooden shelves outside the shop."
    },
    {
        "name": "Scuola del Cuoio (The Leather School)",
        "name_en": "The Leather School",
        "area": "Santa Croce",
        "category": "Deneyim",
        "tags": ["deri", "zanaat", "manastır", "eğitim"],
        "distanceFromCenter": 0.7,
        "lat": 43.7684,
        "lng": 11.2635,
        "price": "high",
        "rating": 4.7,
        "description": "Santa Croce bazilikasının içindeki eski bir manastırda yer alan, dünyanın en ünlü deri işleme okulu. Zanaatkarları çalışırken izleyebilir ve en kaliteli deri ürünleri alabilirsiniz.",
        "description_en": "Located in a former monastery behind Santa Croce, this world-renowned leather school showcases master artisans at work on high-end leather goods.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Pazarın deri kalitesinden şüphe ediyorsanız, burası gerçek kalitenin adresidir.",
        "tips_en": "If you're looking for guaranteed quality leather away from the street markets, this is the place."
    },
    {
        "name": "Caffe Gilli",
        "name_en": "Caffe Gilli",
        "area": "Piazza della Repubblica",
        "category": "Kafe",
        "tags": ["tarihi", "pastane", "meydan", "luks"],
        "distanceFromCenter": 0.1,
        "lat": 43.7714,
        "lng": 11.2543,
        "price": "high",
        "rating": 4.5,
        "description": "Floransa'nın en eski kafesi (1733). Belle Époque tarzı iç mekanıyla, Piazza della Repubblica'nın en şık buluşma noktasıdır.",
        "description_en": "The oldest cafe in Florence (1733), featuring a beautiful Belle Époque interior. A landmark destination for pastries and coffee on the main square.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Sabah kahvesi veya akşamüzeri",
        "bestTime_en": "Morning coffee or late afternoon",
        "tips": "Bar kısmında ayakta kahve içmek masada oturmaktan çok daha ucuzdur (İtalyan usulü).",
        "tips_en": "Drinking your coffee standing at the bar is much cheaper than sitting at a table (the Italian way)."
    },
    {
        "name": "Caffe Paszkowski",
        "name_en": "Caffe Paszkowski",
        "area": "Piazza della Repubblica",
        "category": "Kafe",
        "tags": ["tarihi", "canlı müzik", "literary cafe", "meydan"],
        "distanceFromCenter": 0.1,
        "lat": 43.7714,
        "lng": 11.2540,
        "price": "high",
        "rating": 4.4,
        "description": "Geçmişte sanatçıların ve edebiyatçıların buluşma noktası olan, tescilli tarihi anıt statüsündeki kafe. Akşamları canlı piyano müziği eşliğinde oturabilirsiniz.",
        "description_en": "A historic literary cafe and national monument. Known for its grand interiors and live piano music in the evenings.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Özellikle dondurmaları ve kokteylleri çok başarılıdır.",
        "tips_en": "Their house-made pastries and evening cocktails are particularly renowned."
    },
    {
        "name": "Loggia del Mercato Nuovo (Straw Market)",
        "name_en": "New Market Loggia",
        "area": "Centro Storico",
        "category": "Alışveriş",
        "tags": ["pazar", "tarihi", "mimari", "hediyelik"],
        "distanceFromCenter": 0.2,
        "lat": 43.7699,
        "lng": 11.2539,
        "price": "medium",
        "rating": 4.3,
        "description": "16. yüzyıldan kalma revaklı bir yapıda kurulan pazar. Geleneksel olarak hasır ürünleriyle ünlüdür ancak günümüzde deri ürünleri ve hediyelik eşyalar ağır basmaktadır.",
        "description_en": "A 16th-century arcaded loggia housing a market traditionally famous for straw hats and lace, now focusing on leather goods.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yapının ortasında, 'yoksulların utanç taşı' (Pietra dello Scandalo) olarak bilinen bir mermer daire bulunur.",
        "tips_en": "Look for the marble circle in the floor, known as the 'stone of shame' for bankrupt merchants."
    },
    {
        "name": "San Marco Meydanı (Piazza San Marco)",
        "name_en": "Piazza San Marco",
        "area": "San Marco",
        "category": "Manzara",
        "tags": ["meydan", "üniversite", "heykel", "lokal"],
        "distanceFromCenter": 0.6,
        "lat": 43.7778,
        "lng": 11.2588,
        "price": "free",
        "rating": 4.3,
        "description": "Accademia ve San Marco müzesine komşu olan, çevresi üniversite binalarıyla dolu hareketli bir meydan.",
        "description_en": "A busy square surrounded by university buildings and adjacent to the Accademia and San Marco museums.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Meydandaki otobüs durakları Fiesole gibi yerlere gitmek için ana duraklardan biridir.",
        "tips_en": "The bus stops here are the main point for catching the bus up to Fiesole."
    },
    {
        "name": "Basilica di San Lorenzo",
        "name_en": "Basilica di San Lorenzo",
        "area": "San Lorenzo",
        "category": "Tarihi",
        "tags": ["medici", "mimari", "kilise", "tarih"],
        "distanceFromCenter": 0.3,
        "lat": 43.7749,
        "lng": 11.2539,
        "price": "medium",
        "rating": 4.5,
        "description": "Medici ailesinin resmi kilisesi. Tamamlanmamış kaba cephesiyle zıtlık oluşturan, Brunelleschi imzalı muhteşem bir Rönesans iç mekanına sahiptir.",
        "description_en": "The official church of the Medici family. Features a stark unfinished facade but a magnificent Renaissance interior designed by Brunelleschi.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kilisenin yanındaki 'Biblioteca Medicea Laurenziana' kütüphanesi Michelangelo'nun mimari dehasını görmek için mutlaka gezilmeli.",
        "tips_en": "Be sure to visit the Laurentian Library next door to see Michelangelo's architecture."
    },
    {
        "name": "Basilica di Santa Maria Novella",
        "name_en": "Basilica of SMN",
        "area": "Santa Maria Novella",
        "category": "Tarihi",
        "tags": ["mimari", "fresk", "rönesans", "tarihi"],
        "distanceFromCenter": 0.4,
        "lat": 43.7746,
        "lng": 11.2494,
        "price": "medium",
        "rating": 4.7,
        "description": "Geometrik mermer cephesiyle ünlü, içerisinde Masaccio'nun 'Kutsal Üçlü' freski gibi devrim niteliğinde eserler barındıran Dominiken kilisesi.",
        "description_en": "Famous for its green and white marble geometric facade, this Dominican church houses Masaccio's revolutionary 'Holy Trinity' fresco.",
        "imageUrl": "https://images.unsplash.com/photo-1476442368824-e9f3b9c7b0f6?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kilisenin arkasındaki 'İspanyol Şapeli' freskleri mutlaka görülmeli.",
        "tips_en": "Don't miss the frescoes in the Spanish Chapel behind the main church building."
    },
    {
        "name": "San Firenze (Meydan ve Mimari)",
        "name_en": "Piazza San Firenze",
        "area": "Santa Croce Civarı",
        "category": "Manzara",
        "tags": ["meydan", "barok", "mimari", "sakin"],
        "distanceFromCenter": 0.3,
        "lat": 43.7698,
        "lng": 11.2580,
        "price": "free",
        "rating": 4.4,
        "description": "Bargello müzesi ve Palazzo Vecchio yakınında yer alan, Floransa'da nadir görülen devasa bir Barok mimari kompleksine sahip şık meydan.",
        "description_en": "A grand square featuring one of Florence's rare and massive Baroque architectural complexes, located near the Bargello museum.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Akşamüzeri",
        "bestTime_en": "Late afternoon",
        "tips": "Meydanın kenarındaki kafelerde oturup devasa Barok cepheyi izlemek çok keyiflidir.",
        "tips_en": "Grab a coffee at a nearby cafe and admire the rare Baroque facade towering over the square."
    },
    {
        "name": "Ospedale degli Innocenti",
        "name_en": "Innocenti Hospital",
        "area": "San Marco Civarı",
        "category": "Tarihi",
        "tags": ["brunelleschi", "mimari", "rönesans", "müze"],
        "distanceFromCenter": 0.7,
        "lat": 43.7766,
        "lng": 11.2612,
        "price": "medium",
        "rating": 4.6,
        "description": "Brunelleschi'nin ilk Rönesans yapısı kabul edilen, terk edilmiş bebekler için kurulmuş tarihi yetimhane. Ön cephesindeki seramik bebek figürleriyle ünlüdür.",
        "description_en": "The first Renaissance building in the world, designed by Brunelleschi. A historic orphanage featuring beautiful terracotta medallions of infants.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze kısmının en üst katındaki teras kafe (Caffè del Verone) muhteşem bir Duomo manzarasına sahiptir.",
        "tips_en": "The rooftop terrace cafe (Caffè del Verone) offers spectacular views of the Cathedral dome."
    },
    {
        "name": "Porcellino Heykeli (Şans Domuzu)",
        "name_en": "The Porcellino",
        "area": "Centro Storico",
        "category": "Manzara",
        "tags": ["heykel", "şans", "gelenek", "ücretsiz"],
        "distanceFromCenter": 0.2,
        "lat": 43.7696,
        "lng": 11.2536,
        "price": "free",
        "rating": 4.6,
        "description": "Geleneksel bir ritüel: Burnuna dokunup ağzından para düşürerek dilek dilediğiniz ünlü bronz domuz heykeli.",
        "description_en": "Florence's most famous tradition: rub the well-worn snout of this bronze boar to ensure a return trip to the city.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Günün çoğu saatinde önünde kuyruk olabilir, gece geç saatlerde gitmek daha iyidir.",
        "tips_en": "There's often a line; visit late at night or very early morning to avoid the crowds."
    },
    {
        "name": "Gelateria Santa Trinita",
        "name_en": "Gelateria Santa Trinita",
        "area": "Oltrarno",
        "category": "Kafe",
        "tags": ["dondurma", "gurme", "köprü", "kalite"],
        "distanceFromCenter": 0.4,
        "lat": 43.7691,
        "lng": 11.2504,
        "price": "low",
        "rating": 4.8,
        "description": "Ponte Santa Trinita köprüsü başında yer alan, özellikle siyah susamlı ve mascarpone dondurmalarıyla ünlü ödüllü dondurmacı.",
        "description_en": "A top-rated gelateria located at the foot of the Santa Trinita bridge, famous for creative flavors like Black Sesame and Mascarpone.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Dondurma porsiyonları büyüktür, şarap sorbelerini de mutlaka denemelisiniz.",
        "tips_en": "Their servings are generous; consider trying one of their unique wine-based sorbets."
    },
    {
        "name": "Il Latini",
        "name_en": "Il Latini",
        "area": "Santa Maria Novella Civarı",
        "category": "Restoran",
        "tags": ["Bistecca", "geleneksel", "kalabalık", "aile işletmesi"],
        "distanceFromCenter": 0.5,
        "lat": 43.7716,
        "lng": 11.2505,
        "price": "high",
        "rating": 4.5,
        "description": "Kuyrukları ve gürültülü ama samimi atmosferiyle ünlü, Floransa'nın en ikonik geleneksel restoranlarından biri.",
        "description_en": "A legendary and bustling Florentine restaurant known for its shared tables, huge steaks, and vibrant, rustic atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Tavandan sarkan salamlar ve devasa şarap fıçıları arasında gerçek bir Toskana ziyafeti sizi bekliyor.",
        "tips_en": "A true Tuscan feast awaits amidst hanging hams and giant wine barrels; it's loud and full of life."
    },
    {
        "name": "Mercato Nuovo (Pazar)",
        "name_en": "Mercato Nuovo",
        "area": "Centro Storico",
        "category": "Alışveriş",
        "tags": ["pazar", "deri", "hediyelik", "tarihi"],
        "distanceFromCenter": 0.2,
        "lat": 43.7699,
        "lng": 11.2539,
        "price": "medium",
        "rating": 4.2,
        "description": "Günümüzde deri mamülleri pazarı olarak kullanılan, 16. yüzyıl mimarisi Loggia'nın altındaki alışveriş noktası.",
        "description_en": "A historic market square under a 16th-century loggia, primarily selling leather goods and souvenirs today.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Buradaki deri kalitesi dükkanlara göre daha değişken olabilir, iyi inceleyerek alın.",
        "tips_en": "Leather quality here can vary more than in established boutiques; examine items carefully before buying."
    },
    {
        "name": "Volume (Concept Bar)",
        "name_en": "Volume Concept Bar",
        "area": "Oltrarno",
        "category": "Deneyim",
        "tags": ["bar", "sanat", "atölye", "lokal"],
        "distanceFromCenter": 0.6,
        "lat": 43.7672,
        "lng": 11.2481,
        "price": "low",
        "rating": 4.6,
        "description": "Eski bir ahşap oyma atölyesinin bohem bir bara dönüştürülmüş hali. Duvarlar hala orjinal kalıplarla doludur.",
        "description_en": "A bohemian bar and cultural space set within an old wood-carver's workshop, retaining many original tools and molds.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Akşam (Piyano müziği varsa)",
        "bestTime_en": "Evening (if there's live piano)",
        "tips": "Santo Spirito meydanının gürültüsünden kaçıp içerideki sanatsal havayı solumak için birebir.",
        "tips_en": "The perfect place to escape the square's noise and soak in an artistic, local vibe."
    },
    {
        "name": "Basilica di San Lorenzo (Medici Kilisesi)",
        "name_en": "San Lorenzo Church",
        "area": "San Lorenzo",
        "category": "Tarihi",
        "tags": ["medici", "mimari", "tarih", "rönesans"],
        "distanceFromCenter": 0.3,
        "lat": 43.7749,
        "lng": 11.2539,
        "price": "medium",
        "rating": 4.5,
        "description": "Floransa'nın en eski ve en önemli kiliselerinden. Medici ailesinin güç ve ihtişamının simgesi.",
        "description_en": "One of the oldest and most historically significant churches in Florence, serving as the Medici family's private parish.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçerideki Donatello heykelleri ve Brunelleschi mimarisi sanatsal bir ziyafettir.",
        "tips_en": "Don't miss the bronze pulpits by Donatello and the serene architecture by Brunelleschi."
    },
    {
        "name": "Gucci Garden Museo",
        "name_en": "Gucci Museum",
        "area": "Piazza della Signoria",
        "category": "Müze",
        "tags": ["moda", "tasarım", "sergi", "lüks"],
        "distanceFromCenter": 0.2,
        "lat": 43.7697,
        "lng": 11.2568,
        "price": "medium",
        "rating": 4.5,
        "description": "Gucci'nin evrimini ve yaratıcı evrenini sunan, moda dünyasının en modern ve interaktif müze deneyimlerinden biri.",
        "description_en": "An interactive and stylish museum exploring the heritage and creative evolution of the House of Gucci.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzedeki odaların her biri farklı bir temaya (çiçek, logo, doğa) sahiptir ve inanılmaz fotojeniktir.",
        "tips_en": "The themed rooms are incredibly photogenic, each exploring a different facet of the brand's identity."
    },
    {
        "name": "Piazza della Signoria (Açık Hava Müzesi)",
        "name_en": "Signoria Square",
        "area": "Centro Storico",
        "category": "Manzara",
        "tags": ["meydan", "heykel", "mimari", "ücretsiz"],
        "distanceFromCenter": 0.2,
        "lat": 43.7695,
        "lng": 11.2558,
        "price": "free",
        "rating": 4.8,
        "description": "Dünyanın en güzel açık hava heykel müzelerinden biri olarak kabul edilen, şehrin siyasi kalbinin attığı meydan.",
        "description_en": "Considered one of the world's most beautiful open-air galleries, this square has been the center of Florentine political life for centuries.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "Kalabalıklar gelmeden sabahın ilk ışıklarında heykellerin arasında yürümek çok büyüleyicidir.",
        "tips_en": "The square is magical in the early morning light before the tour groups arrive."
    },
    {
        "name": "Uffizi (Galleria)",
        "name_en": "Uffizi Gallery",
        "area": "Centro Storico",
        "category": "Müze",
        "tags": ["sanat", "rönesans", "tarih", "başyapıt"],
        "distanceFromCenter": 0.3,
        "lat": 43.7677,
        "lng": 11.2553,
        "price": "high",
        "rating": 4.9,
        "description": "Rönesans'ın doğduğu yer. Dünyanın en önemli resim koleksiyonlarından biri burada yer alır.",
        "description_en": "The birthplace of the Renaissance. Home to one of the most important and vast art collections in the entire world.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Açılış saati (08:15)",
        "bestTime_en": "Opening hour (08:15)",
        "tips": "U şeklindeki binanın pencerelerinden görünen Arno nehri ve Ponte Vecchio manzaralarını da kaçırmayın.",
        "tips_en": "Don't just look at the art; the views from the gallery windows over the Arno are equally stunning."
    },
    {
        "name": "Bargello National Museum (Heykel)",
        "name_en": "Bargello Sculpture Museum",
        "area": "San Firenze",
        "category": "Müze",
        "tags": ["heykel", "donatello", "tarih", "ortaçağ"],
        "distanceFromCenter": 0.3,
        "lat": 43.7704,
        "lng": 11.2581,
        "price": "medium",
        "rating": 4.7,
        "description": "Eski hapishane ve devlet binasının içinde yer alan, İtalya'nın en önemli heykel müzesi.",
        "description_en": "Located in a former medieval fortress and prison, this is Italy's national museum dedicated primarily to sculpture.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Avludaki revaklar ve Donatello'nun ünlü Davud heykeli müzenin en çarpıcı noktalarıdır.",
        "tips_en": "The grand courtyard and Donatello's bronze David are the highlights of the collection."
    },
    {
        "name": "Loggia dei Lanzi (Heykel Galerisi)",
        "name_en": "Loggia dei Lanzi Gallery",
        "area": "Piazza della Signoria",
        "category": "Tarihi",
        "tags": ["heykel", "ücretsiz", "mimari", "meydan"],
        "distanceFromCenter": 0.2,
        "lat": 43.7682,
        "lng": 11.2534,
        "price": "free",
        "rating": 4.8,
        "description": "Meydanın bir parçası olan, Rönesans heykeltıraşlığının en nadide parçalarını ücretsizce sunan açık hava galerisi.",
        "description_en": "A prominent landmark on the main square, serving as a free open-air gallery of exceptional Renaissance sculpture.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gece (Işıklandırma)",
        "bestTime_en": "Night (Illumination)",
        "tips": "Cellini'nin Perseus heykeli altındaki orjinal küçük kabartmalar Bargello'dadır, ama buradaki orjinallik hissi benzersizdir.",
        "tips_en": "The original small reliefs from the base of the Perseus statue are in the Bargello, but the statue itself is the real deal."
    },
    {
        "name": "Palatine Gallery (Pitti Sarayı)",
        "name_en": "Palatine Gallery",
        "area": "Oltrarno",
        "category": "Müze",
        "tags": ["sanat", "saray", "lüks", "medici"],
        "distanceFromCenter": 0.5,
        "lat": 43.7656,
        "lng": 11.2505,
        "price": "high",
        "rating": 4.8,
        "description": "Hala bir prensin özel koleksiyonu gibi hissettiren, baştan aşağı sanatla kaplı saray odaları.",
        "description_en": "A lavish gallery that still looks like a prince's private collection, with masterpieces covering every wall of the royal apartments.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğleden önce",
        "bestTime_en": "Late morning",
        "tips": "Rafael'in eserlerinin en yoğun bulunduğu müzedir, eserlerin isimlerine odaların kataloglarından bakabilirsiniz.",
        "tips_en": "This museum contains the world's largest concentration of works by Raphael; consult the room guides to identify them."
    },
    {
        "name": "Rose Garden (Gül Bahçesi)",
        "name_en": "Florence Rose Garden",
        "area": "Oltrarno",
        "category": "Park",
        "tags": ["bahçe", "manzara", "gül", "ücretsiz"],
        "distanceFromCenter": 1.5,
        "lat": 43.7623,
        "lng": 11.2647,
        "price": "free",
        "rating": 4.7,
        "description": "Piazzale Michelangelo'nun hemen altında yer alan, yüzlerce çeşit gülün ve modern heykellerin bulunduğu gizli cennet.",
        "description_en": "A serene garden just below Piazzale Michelangelo, featuring hundreds of rose varieties and whimsical sculptures by Jean-Michel Folon.",
        "imageUrl": "https://images.unsplash.com/photo-1506764483492-1813517e5735?w=800",
        "bestTime": "Mayıs-Haziran (Çiçek açtığında)",
        "bestTime_en": "May-June (When in bloom)",
        "tips": "Güllerin açtığı dönemde kokusu tüm tepeyi sarar, meditasyon ve dinlenme için en iyi yerdir.",
        "tips_en": "When the roses are in bloom, the scent is heavenly. It's the perfect quiet alternative to the busy square above."
    },
    {
        "name": "Bardini Garden (Secret View)",
        "name_en": "Giardino Bardini",
        "area": "Oltrarno",
        "category": "Park",
        "tags": ["bahçe", "manzara", "sessiz", "wisteria"],
        "distanceFromCenter": 0.8,
        "lat": 43.7637,
        "lng": 11.2574,
        "price": "medium",
        "rating": 4.5,
        "description": "Floransa'nın en iyi şehir manzarasına sahip ama en az bilinen bahçelerinden biri. Mor salkımlı tüneliyle ünlüdür.",
        "description_en": "One of Florence's best-kept secrets, offering stunning city views and a famous tunnel of purple wisteria in the spring.",
        "imageUrl": "https://images.unsplash.com/photo-1544333346-bf0375179462?w=800",
        "bestTime": "Nisan sonu",
        "bestTime_en": "Late April",
        "tips": "Bahçenin en üstündeki kafede manzara eşliğinde bir şeyler içmek paha biçilemezdir.",
        "tips_en": "The cafe at the top of the tiered garden is one of the most scenic spots in the entire city for a break."
    },
    {
        "name": "San Miniato al Monte (Romanesk)",
        "name_en": "San Miniato Church",
        "area": "Oltrarno",
        "category": "Tarihi",
        "tags": ["kilise", "manzara", "tarih", "sakin"],
        "distanceFromCenter": 2.0,
        "lat": 43.7598,
        "lng": 11.2647,
        "price": "low",
        "rating": 4.6,
        "description": "Şehrin en yüksek noktasında yer alan, 1000 yıllık geçmişiyle büyüleyen ruhanî bir durak.",
        "description_en": "A 1,000-year-old Romanesque masterpiece perched at the highest point in Florence, offering a spiritual and tranquil escape.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gün batımı sonrası (Gregorian koro)",
        "bestTime_en": "Post-sunset (Gregorian chant)",
        "tips": "Kripta (yeraltı şapeli) ve yer mozaikleri müthiş bir işçiliğe sahiptir.",
        "tips_en": "The ancient crypt and the 13th-century marble floor mosaics are absolute marvels of craftsmanship."
    },
    {
        "name": "Piazza della Repubblica (Tarihi Meydan)",
        "name_en": "Republic Square",
        "area": "Centro Storico",
        "category": "Manzara",
        "tags": ["meydan", "tarih", "kafe", "atlıkarınca"],
        "distanceFromCenter": 0.1,
        "lat": 43.7714,
        "lng": 11.2541,
        "price": "free",
        "rating": 4.5,
        "description": "Modern Floransa'nın nabzının attığı, tarihi kafelerle çevrili görkemli meydan.",
        "description_en": "The grand center of modern Florence, a majestic square marked by a triumphal arch and historic cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meydanın ortasındaki tarihi atlıkarınca özellikle çocuklu aileler için çok güzeldir.",
        "tips_en": "The vintage carousel in the middle of the square is a charming touch, especially lit up in the evening."
    }
]

def enrich_floransa_batch2():
    filepath = 'assets/cities/floransa.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_floransa_batch2:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_floransa_batch2()
print(f"Floransa now has {count} highlights.")
