import json
import os

new_kopenhag_batch3 = [
    {
        "name": "Danish Jewish Museum",
        "name_en": "Danish Jewish Museum",
        "area": "Slotsholmen",
        "category": "Müze",
        "tags": ["tarih", "yahudi kültürü", "libeskind", "mimari"],
        "distanceFromCenter": 0.8,
        "lat": 55.6744,
        "lng": 12.5817,
        "price": "medium",
        "rating": 4.4,
        "description": "Daniel Libeskind tarafından tasarlanan, Danimarka Yahudilerinin tarihini ve İkinci Dünya Savaşı'ndaki kurtarılma hikayelerini anlatan müze.",
        "description_en": "Designed by Daniel Libeskind, this museum tells the history of Danish Jews and their rescue stories during World War II.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın iç mimarisi 'Mitzvah' (iyi iş) kelimesini simgeleyecek şekilde tasarlanmıştır.",
        "tips_en": "The building's interior architecture is designed to symbolize the word 'Mitzvah' (good deed)."
    },
    {
        "name": "Museum of Copenhagen",
        "name_en": "Museum of Copenhagen",
        "area": "Centrum",
        "category": "Müze",
        "tags": ["şehir tarihi", "kopenhag", "sergi", "kültür"],
        "distanceFromCenter": 0.5,
        "lat": 55.6812,
        "lng": 12.5714,
        "price": "medium",
        "rating": 4.6,
        "description": "Şehrin Ortaçağ'dan günümüze gelişimini interaktif ve modern bir dille anlatan Kopenhag Şehir Müzesi.",
        "description_en": "The Copenhagen City Museum, which tells the development of the city from the Middle Ages to today in an interactive and modern way.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin avlusundaki devasa Kopenhag maketini mutlaka inceleyin.",
        "tips_en": "Be sure to examine the massive scale model of Copenhagen in the museum's courtyard."
    },
    {
        "name": "Nikolaj Kunsthal",
        "name_en": "Nikolaj Kunsthal",
        "area": "Indre By",
        "category": "Müze",
        "tags": ["modern sanat", "kilise", "alternatif", "sergi"],
        "distanceFromCenter": 0.3,
        "lat": 55.6789,
        "lng": 12.5811,
        "price": "medium",
        "rating": 4.5,
        "description": "Eski bir kilise binası içinde yer alan, çağdaş sanatın en yenilikçi örneklerinin sergilendiği bir sanat merkezi.",
        "description_en": "A contemporary art center housed in a former church building, showcasing the most innovative examples of modern art.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Kilisenin kulesi de şehre hakim harika bir manzara sunar (bazı dönemlerde kuleye çıkış mümkündür).",
        "tips_en": "The church tower also offers a great view of the city (check if tower access is available during your visit)."
    },
    {
        "name": "Kunsthal Charlottenborg",
        "name_en": "Kunsthal Charlottenborg",
        "area": "Nyhavn",
        "category": "Müze",
        "tags": ["çağdaş sanat", "akademi", "sergi", "nyhavn"],
        "distanceFromCenter": 1.0,
        "lat": 55.6797,
        "lng": 12.5881,
        "price": "medium",
        "rating": 4.4,
        "description": "Nyhavn'ın hemen yanında, Danimarka Kraliyet Sanat Akademisi'nin bir parçası olan, Kuzey Avrupa'nın en büyük çağdaş sanat mekanlarından biri.",
        "description_en": "Located right next to Nyhavn, part of the Royal Danish Academy of Fine Arts, it is one of the largest contemporary art venues in Northern Europe.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze içindeki 'Apollo Bar' yerel sanatçıların ve tasarımcıların favori buluşma noktasıdır.",
        "tips_en": "The 'Apollo Bar' within the museum is a favorite gathering spot for local artists and designers."
    },
    {
        "name": "Copenhagen City Hall (Rådhus)",
        "name_en": "Copenhagen City Hall",
        "area": "Rådhuspladsen",
        "category": "Tarihi",
        "tags": ["belediye", "saat kulesi", "mimari", "merkez"],
        "distanceFromCenter": 0.1,
        "lat": 55.6761,
        "lng": 12.5683,
        "price": "free",
        "rating": 4.5,
        "description": "Kopenhag Belediyesi'nin görkemli binası. Jens Olsen'in Dünya Saati (Verdensur) buranın en ünlü parçasıdır.",
        "description_en": "The grand building of the Copenhagen Municipality. Jens Olsen's World Clock (Verdensur) is its most famous piece.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz (tur saatleri)",
        "bestTime_en": "Daytime (tour hours)",
        "tips": "Kuleye çıkıp Rådhuspladsen meydanını yukarıdan fotoğraflayabilirsiniz (rehberli tur eşliğinde).",
        "tips_en": "You can climb the tower and photograph Rådhuspladsen square from above (guided tour required)."
    },
    {
        "name": "Assistens Cemetery",
        "name_en": "Assistens Cemetery",
        "area": "Nørrebro",
        "category": "Park",
        "tags": ["tarih", "h.c. andersen", "mezarlık", "park"],
        "distanceFromCenter": 2.2,
        "lat": 55.6908,
        "lng": 12.5481,
        "price": "free",
        "rating": 4.7,
        "description": "Danimarka'nın en ünlü yazarlarının ve filozoflarının (H.C. Andersen, Kierkegaard) mezarlarının bulunduğu yerel bir park ve mezarlık.",
        "description_en": "A local park and cemetery where some of Denmark's most famous writers and philosophers (H.C. Andersen, Kierkegaard) are buried.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Danimarkalılar burayı sadece bir mezarlık değil, güneşlenmek ve piknik yapmak için bir park olarak da kullanırlar.",
        "tips_en": "Danes use this place not just as a cemetery but also as a park for sunbathing and picnicking."
    },
    {
        "name": "Ofelia Plads",
        "name_en": "Ofelia Plads",
        "area": "Liman Bölgesi",
        "category": "Deneyim",
        "tags": ["meydan", "etkinlik", "liman", "manzara"],
        "distanceFromCenter": 1.2,
        "lat": 55.6815,
        "lng": 12.5956,
        "price": "free",
        "rating": 4.6,
        "description": "Deniz kıyısında, açık hava konserlerine, pazarlara ve kültürel etkinliklere ev sahipliği yapan modern bir platform.",
        "description_en": "A modern waterfront platform hosting open-air concerts, markets, and cultural events.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Yaz akşamları",
        "bestTime_en": "Summer evenings",
        "tips": "Nyhavn'dan sonra Opera binasına karşı güneşlenmek veya bir şeyler içmek için harika bir duraktır.",
        "tips_en": "A great stop after Nyhavn to sunbathes or have a drink while facing the Opera House."
    },
    {
        "name": "Kalvebod Bølge",
        "name_en": "Kalvebod Wave",
        "area": "Liman Bölgesi",
        "category": "Deneyim",
        "tags": ["modern mimari", "su kıyısı", "kaykay", "dinlence"],
        "distanceFromCenter": 1.0,
        "lat": 55.6702,
        "lng": 12.5786,
        "price": "free",
        "rating": 4.5,
        "description": "Liman kıyısında 'dalga' şeklinde tasarlanmış ahşap bir yürüyüş ve aktivite alanı. Modern kentsel tasarımın en iyi örneklerinden biridir.",
        "description_en": "A wooden promenade and activity area designed in a 'wave' shape along the harbor. One of the best examples of modern urban design.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Burası kano ve su sporları yapanların uğrak noktasıdır; basamaklarında oturup şehri izlemek çok keyiflidir.",
        "tips_en": "A popular spot for kayakers and water sports enthusiasts; sitting on the steps and watching the city is very enjoyable."
    },
    {
        "name": "VM Mountain",
        "name_en": "VM Mountain",
        "area": "Ørestad",
        "category": "Tarihi",
        "tags": ["mimari", "big", "dağ evi", "tasarım"],
        "distanceFromCenter": 5.5,
        "lat": 55.6325,
        "lng": 12.5819,
        "price": "free",
        "rating": 4.7,
        "description": "Teraslı bahçeleriyle yapay bir 'dağ' gibi görünen, ödüllü bir konut projesi. Modern mimari meraklıları için ikonik bir yapı.",
        "description_en": "An award-winning residential project designed to look like an artificial 'mountain' with terraced gardens. An iconic structure for modern architecture buffs.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın dışındaki dev Everest dağı görselini ve otoparkın içindeki renkli tasarımı mutlaka görün.",
        "tips_en": "Be sure to see the giant Mt. Everest graphic on the building's exterior and the colorful design inside the parking garage."
    },
    {
        "name": "Tietgenkollegiet (Daire Öğrenci Yurdu)",
        "name_en": "Tietgen Student Hall",
        "area": "Ørestad",
        "category": "Tarihi",
        "tags": ["mimari", "daire bina", "modern", "ünlü"],
        "distanceFromCenter": 2.5,
        "lat": 55.6601,
        "lng": 12.5894,
        "price": "free",
        "rating": 4.8,
        "description": "Dünyanın en güzel öğrenci yurtlarından biri olarak kabul edilen, dairesel mimarisi ve avlusuyla ünlü modern ikon.",
        "description_en": "Considered one of the world's most beautiful student dormitories, a modern icon famous for its circular architecture and central courtyard.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Dışarıdan izlemek için her zaman",
        "bestTime_en": "Always great for exterior views",
        "tips": "Özel bir konut olduğu için iç kısımları genellikle ziyarete kapalıdır, ancak dış mimarisi hayranlık uyandırıcıdır.",
        "tips_en": "As it's private residence, the interiors are generally closed to the public, but the exterior architecture is admirable."
    },
    {
        "name": "Magasin du Nord",
        "name_en": "Magasin du Nord",
        "area": "Kongens Nytorv",
        "category": "Alışveriş",
        "tags": ["mağaza", "lüks", "tarihi", "fransız stil"],
        "distanceFromCenter": 0.5,
        "lat": 55.6794,
        "lng": 12.5847,
        "price": "high",
        "rating": 4.4,
        "description": "1868'den beri hizmet veren, Kopenhag'ın en büyük ve en köklü lüks departman mağazası. Fransız felsefesiyle tasarlanmış görkemli binasıyla ünlüdür.",
        "description_en": "Copenhagen's largest and most established luxury department store, serving since 1868. Famous for its magnificent building designed in French style.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kışın binanın dışındaki ışıklandırmalar ve Noel vitrinleri görülmeye değerdir.",
        "tips_en": "The building's winter light displays and Christmas window decorations are well worth seeing."
    },
    {
        "name": "Lego Store Copenhagen",
        "name_en": "Lego Store",
        "area": "Strøget",
        "category": "Alışveriş",
        "tags": ["lego", "oyuncak", "eğlence", "ikonik"],
        "distanceFromCenter": 0.2,
        "lat": 55.6789,
        "lng": 12.5761,
        "price": "medium",
        "rating": 4.6,
        "description": "Lego'nun doğduğu ülkede, Kopenhag'ın en ünlü alışveriş caddesinde yer alan amiral gemisi mağazası. İçinde dev Lego heykelleri bulunur.",
        "description_en": "The flagship store located on Copenhagen's most famous shopping street in the country where Lego was born. Features giant Lego sculptures.",
        "imageUrl": "https://images.unsplash.com/photo-1560c56256-0713deb736c0?w=800",
        "bestTime": "Sabah (kalabalık olmadan)",
        "bestTime_en": "Morning (before it gets crowded)",
        "tips": "Nyhavn'ın ve Kopenhag binalarının Lego'dan yapılmış maketlerini burada görebilirsiniz.",
        "tips_en": "You can see Lego scale models of Nyhavn and other Copenhagen buildings here."
    },
    {
        "name": "Hay House (Tasarım Mağazası)",
        "name_en": "HAY House",
        "area": "Østergade / Strøget",
        "category": "Alışveriş",
        "tags": ["tasarım", "mobilya", "modern", "manzara"],
        "distanceFromCenter": 0.3,
        "lat": 55.6788,
        "lng": 12.5789,
        "price": "high",
        "rating": 4.7,
        "description": "Danimarka'nın dünyaca ünlü tasarım markası HAY'in, tarihi bir binanın üst katlarında yer alan ve harika meydan manzarasına sahip konsept mağazası.",
        "description_en": "The concept store of Denmark's world-famous design brand HAY, located on the upper floors of a historic building with great views of the square.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Mağazanın pencerelerinden Strøget caddesini ve Amagertorv meydanını kuş bakışı izleyebilirsiniz.",
        "tips_en": "Enjoy a bird's-eye view of Strøget street and Amagertorv square from the store windows."
    },
    {
        "name": "Restaurant Geranium",
        "name_en": "Geranium",
        "area": "Østerbro",
        "category": "Restoran",
        "tags": ["michelin", "fine dining", "lüks", "başyapıt"],
        "distanceFromCenter": 3.0,
        "lat": 55.7039,
        "lng": 12.5719,
        "price": "high",
        "rating": 5.0,
        "description": "Dünyanın en iyi restoranları listesinde 1. sıraya kadar yükselmiş, 3 Michelin yıldızlı gastronomi tapınağı.",
        "description_en": "A 3-Michelin-starred temple of gastronomy that has reached #1 on the list of the World's 50 Best Restaurants.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam yemeği (rezervasyonla)",
        "bestTime_en": "Dinner (reservation required)",
        "tips": "Futbol stadyumunun 8. katında yer alan bu restoran için aylar öncesinden rezervasyon yaptırmanız gerekir.",
        "tips_en": "Located on the 8th floor of the national football stadium; reservations must be made months in advance."
    },
    {
        "name": "Alchemist (Gastronomi Deneyimi)",
        "name_en": "Alchemist",
        "area": "Refshaleøen",
        "category": "Deneyim",
        "tags": ["michelin", "avangart", "sanat", "gastronomi"],
        "distanceFromCenter": 3.5,
        "lat": 55.6939,
        "lng": 12.6105,
        "price": "high",
        "rating": 5.0,
        "description": "Sadece bir restoran değil, aynı zamanda bir sanat enstalasyonu ve çok duyulu bir performans. 50'den fazla 'izlenim' sunan devrimsel bir mekan.",
        "description_en": "Not just a restaurant, but an art installation and multi-sensory performance. A revolutionary venue offering over 50 'impressions'.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam (rezervasyonla)",
        "bestTime_en": "Evening (reservation required)",
        "tips": "Burası dünyanın en zor yer buluna restoranlarından biridir.",
        "tips_en": "This is one of the most difficult restaurants in the world to secure a seat at."
    }
]

def enrich_kopenhag_batch3():
    filepath = 'assets/cities/kopenhag.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_kopenhag_batch3:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_kopenhag_batch3()
print(f"Kopenhag now has {count} unique highlights.")
