import json
import os

new_amsterdam_batch2 = [
    {
        "name": "Nieuwe Kerk (Yeni Kilise)",
        "name_en": "Nieuwe Kerk",
        "area": "Dam Square",
        "category": "Tarihi",
        "tags": ["kilise", "sergi", "kraliyet", "tarih"],
        "distanceFromCenter": 0.1,
        "lat": 52.3739,
        "lng": 4.8916,
        "price": "medium",
        "rating": 4.5,
        "description": "Dam Meydanı'ndaki 15. yüzyıldan kalma gotik kilise. Bugün dini törenlerden ziyade prestijli sanat sergilerine ev sahipliği yapar.",
        "description_en": "A 15th-century Gothic church on Dam Square. Today, it hosts prestigious art exhibitions rather than religious services.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kilise aynı zamanda Hollanda krallarının ve kraliçelerinin taç giyme törenlerinin yapıldığı yerdir.",
        "tips_en": "The church is also the site of the investiture of Dutch kings and queens."
    },
    {
        "name": "Oude Kerk (Eski Kilise)",
        "name_en": "Oude Kerk",
        "area": "Red Light District",
        "category": "Tarihi",
        "tags": ["kilise", "en eski bina", "tarih", "sanat"],
        "distanceFromCenter": 0.4,
        "lat": 52.3743,
        "lng": 4.8979,
        "price": "medium",
        "rating": 4.4,
        "description": "Amsterdam'ın en eski binası. Kırmızı Fener Mahallesi'nin tam ortasında yer alan bu tarihi kilise, ironik konumu ve devasa cam tavanıyla dikkat çeker.",
        "description_en": "Amsterdam's oldest building. Located in the heart of the Red Light District, this historic church is notable for its ironic location and massive vaulted ceiling.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kilisenin zeminindeki yüzlerce mezar taşını ve çevresindeki canlı hayatın zıtlığını inceleyin.",
        "tips_en": "Observe the hundreds of gravestones on the church floor and the contrast with the lively life surrounding it."
    },
    {
        "name": "Het Scheepvaartmuseum (Denizcilik Müzesi)",
        "name_en": "National Maritime Museum",
        "area": "Oost",
        "category": "Müze",
        "tags": ["denizcilik", "gemi", "tarih", "interaktif"],
        "distanceFromCenter": 1.5,
        "lat": 52.3717,
        "lng": 4.9147,
        "price": "medium",
        "rating": 4.7,
        "description": "Hollanda'nın denizcilik tarihini anlatan etkileyici müze. Müzenin önünde demirli duran devasa 18. yüzyıl gemisi kopyasını (Amsterdam) gezebilirsiniz.",
        "description_en": "An impressive museum telling the story of Dutch maritime history. You can tour the massive 18th-century ship replica (Amsterdam) moored in front of the museum.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze binasının cam tavanı mimari bir harikadır ve harika fotoğraflar verir.",
        "tips_en": "The museum building's glass courtyard roof is an architectural marvel and great for photos."
    },
    {
        "name": "Ons' Lieve Heer op Solder (Tavan Arasındaki Kilise)",
        "name_en": "Our Lord in the Attic",
        "area": "Centrum",
        "category": "Tarihi",
        "tags": ["gizli kilise", "tarih", "keşif", "ev müzesi"],
        "distanceFromCenter": 0.5,
        "lat": 52.3768,
        "lng": 4.9004,
        "price": "medium",
        "rating": 4.8,
        "description": "17. yüzyılda Katoliklere ibadet yasağı varken bir evin tavan arasına gizlice inşa edilmiş muhteşem bir kilise. Amsterdam'ın en iyi korunmuş sırlarından biridir.",
        "description_en": "A magnificent church secretly built in the attic of a 17th-century canal house during the ban on Catholic worship. One of Amsterdam's best-kept secrets.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Dar merdivenlerinden tırmanıp en üstteki görkemli şapele ulaştığınızdaki sürprize hazırlıklı olun.",
        "tips_en": "Be prepared for the surprise when you climb the narrow stairs and reach the grand chapel at the top."
    },
    {
        "name": "Portuguese Synagogue (Portekiz Sinagogu)",
        "name_en": "Portuguese Synagogue",
        "area": "Jewish Cultural Quarter",
        "category": "Tarihi",
        "tags": ["yahudi tarihi", "sinagog", "mimarisi", "kütüphane"],
        "distanceFromCenter": 1.0,
        "lat": 52.3670,
        "lng": 4.9022,
        "price": "medium",
        "rating": 4.7,
        "description": "17. yüzyıldan kalma, dünyanın en eski ve en etkileyici sinagoglarından biri. Hala elektrik kullanılmayan binada akşamları binlerce mum yakılır.",
        "description_en": "Built in the 17th century, one of the world's oldest and most impressive synagogues. The building still has no electricity, and thousands of candles are lit for evening services.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Ets Haim kütüphanesi dünyanın en eski Yahudi kütüphanesidir ve sinagogun bir parçasıdır.",
        "tips_en": "The Ets Haim library is the world's oldest Jewish library and is part of the synagogue complex."
    },
    {
        "name": "Museum Het Grachtenhuis (Kanal Evi Müzesi)",
        "name_en": "Museum of the Canals",
        "area": "Canal Ring",
        "category": "Müze",
        "tags": ["kanallar", "tarih", "interaktif", "mimari"],
        "distanceFromCenter": 0.6,
        "lat": 52.3667,
        "lng": 4.8856,
        "price": "medium",
        "rating": 4.6,
        "description": "Amsterdam kanallarının nasıl inşa edildiğini ve 400 yıllık tarihini anlatan harika bir interaktif müze. Tarihi bir kanal evinde yer alır.",
        "description_en": "A wonderful interactive museum telling the 400-year history of how Amsterdam's canals were built. Housed in a historic canal house.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Kanal turuna çıkmadan önce bu müzeyi gezmek, kanallara bakış açınızı değiştirecektir.",
        "tips_en": "Visiting this museum before taking a canal cruise will change your perspective on the city's waterways."
    },
    {
        "name": "Micropia",
        "name_en": "Micropia",
        "area": "Plantage",
        "category": "Müze",
        "tags": ["mikroplar", "bilim", "interaktif", "eşsiz"],
        "distanceFromCenter": 1.5,
        "lat": 52.3663,
        "lng": 4.9138,
        "price": "medium",
        "rating": 4.8,
        "description": "Dünyanın tek mikrop müzesi! Görünmez mikro dünyayı keşfetmek için harika ve sıra dışı bir yerdir. ARTIS Hayvanat Bahçesi'nin hemen yanındadır.",
        "description_en": "The world's only microbe museum! A great and unusual place to discover the invisible microworld. Located right next to the ARTIS Zoo.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Beslediğiniz mikropları görmek için kendinizi taratabilirsiniz.",
        "tips_en": "You can get yourself scanned to see the microbes you carry."
    },
    {
        "name": "ARTIS Amsterdam Royal Zoo",
        "name_en": "ARTIS Zoo",
        "area": "Plantage",
        "category": "Park",
        "tags": ["hayvanat bahçesi", "akvaryum", "planetarium", "aile"],
        "distanceFromCenter": 1.5,
        "lat": 52.3664,
        "lng": 4.9137,
        "price": "high",
        "rating": 4.6,
        "description": "Kıta Avrupası'nın en eski hayvanat bahçelerinden biri. Akvaryum, planetarium ve botanik bahçesiyle tam bir doğa kompleksidir.",
        "description_en": "One of the oldest zoos in mainland Europe. A complete nature complex featuring an aquarium, planetarium, and botanical gardens.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Tarihi kütüphanesi (Library Artis) mimari ve bilim tutkunları için bir cevherdir.",
        "tips_en": "Its historic library (Library Artis) is a gem for architecture and science enthusiasts."
    },
    {
        "name": "Magere Brug (Zayıf Köprü)",
        "name_en": "Skinny Bridge",
        "area": "Amstel",
        "category": "Tarihi",
        "tags": ["köprü", "romantik", "ikonik", "gece manzarası"],
        "distanceFromCenter": 1.0,
        "lat": 52.3636,
        "lng": 4.9024,
        "price": "free",
        "rating": 4.7,
        "description": "Amstel Nehri üzerindeki en ünlü köprü. Efsaneye göre bu köprüde öpüşen sevgililerin aşkı sonsuza kadar sürer.",
        "description_en": "The most famous bridge over the Amstel River. Legend has it that a kiss shared over this bridge ensures an eternal love.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Akşamları binlerce küçük lamba ile aydınlatıldığında Amsterdam'ın en fotojenik yeridir.",
        "tips_en": "It's Amsterdam's most photogenic spot when illuminated by thousands of small bulbs at night."
    },
    {
        "name": "De Negen Straatjes (9 Sokak)",
        "name_en": "Nine Streets",
        "area": "Canal Ring",
        "category": "Alışveriş",
        "tags": ["butikler", "vintage", "tasarım", "kafeler"],
        "distanceFromCenter": 0.5,
        "lat": 52.3698,
        "lng": 4.8837,
        "price": "free",
        "rating": 4.6,
        "description": "Kanal kuşağını kesen dokuz küçük sokak. Bağımsız tasarımcıların, vintage dükkanların ve yerel kafelerin merkezidir.",
        "description_en": "Nine small streets intersecting the canal belt. The center for independent designers, vintage shops, and local cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Her sokağın tabelasında hangi sokak olduğu yazar, kaybolmak bu bölgenin en keyifli yanıdır.",
        "tips_en": "Look for the street signs on each corner; getting lost is the best way to enjoy this area."
    },
    {
        "name": "Red Light Secrets (Fuhuş Müzesi)",
        "name_en": "Museum of Prostitution",
        "area": "Red Light District",
        "category": "Müze",
        "tags": ["kültür", "sıradışı", "tarih", "bilgi"],
        "distanceFromCenter": 0.5,
        "lat": 52.3735,
        "lng": 4.8988,
        "price": "medium",
        "rating": 4.3,
        "description": "Kırmızı Fener Mahallesi'ndeki hayatın perde arkasını anlatan dünyanın ilk fuhuş müzesi. Eski bir genelevde yer alır.",
        "description_en": "The world's first museum of prostitution, telling the story of life behind the scenes in the Red Light District. Located in a former brothel.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Genç yaştakiler için uygun olmayabilir, mahallenin sosyal tarihini öğrenmek için ilginçtir.",
        "tips_en": "May not be suitable for young children; interesting for learning about the social history of the neighborhood."
    },
    {
        "name": "Electric Ladyland",
        "name_en": "Electric Ladyland",
        "area": "Jordaan",
        "category": "Müze",
        "tags": ["floresan sanat", "deneyim", "benzersiz", "küçük"],
        "distanceFromCenter": 1.0,
        "lat": 52.3764,
        "lng": 4.8797,
        "price": "low",
        "rating": 4.8,
        "description": "Dünyanın tek floresan sanat müzesi. Ultraviyole ışık altında parlayan mineraller ve sanat eserleriyle büyüleyici bir deneyim sunar.",
        "description_en": "The world's only museum of fluorescent art. Offers a fascinating experience with minerals and artworks that glow under ultraviolet light.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Küçük olduğu için mutlaka önceden rezervasyon yaptırın, sahibi Nick çok ilgili bir rehberdir.",
        "tips_en": "It's small, so be sure to book in advance; the owner Nick is a very engaging guide."
    },
    {
        "name": "Museum Willet-Holthuysen",
        "name_en": "Museum Willet-Holthuysen",
        "area": "Canal Ring",
        "category": "Müze",
        "tags": ["saray", "yaşam", "tarihi ev", "bahçe"],
        "distanceFromCenter": 1.0,
        "lat": 52.3653,
        "lng": 4.8961,
        "price": "medium",
        "rating": 4.6,
        "description": "17. yüzyıldan kalma görkemli bir kanal evi. İçindeki orijinal mobilyalar, gümüş koleksiyonu ve Fransız stili bahçesiyle eski Amsterdam hayatını yansıtır.",
        "description_en": "A grand 17th-century canal house. Reflects old Amsterdam life with its original furnishings, silver collection, and French-style garden.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Bahçesindeki simetrik düzenleme Amsterdam'ın en şık bahçelerinden biridir.",
        "tips_en": "The symmetrical layout of its garden is one of Amsterdam's most elegant."
    },
    {
        "name": "Waterlooplein Bit Pazarı",
        "name_en": "Waterlooplein Market",
        "area": "Centrum",
        "category": "Deneyim",
        "tags": ["pazar", "vintage", "ikinci el", "alışveriş"],
        "distanceFromCenter": 0.8,
        "lat": 52.3683,
        "lng": 4.9038,
        "price": "free",
        "rating": 4.1,
        "description": "Amsterdam'ın en eski bit pazarı. Vintage kıyafetler, antikalar ve ilginç ikinci el eşyalar bulmak için mükemmel bir yer.",
        "description_en": "Amsterdam's oldest flea market. A perfect place to find vintage clothing, antiques, and interesting second-hand goods.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Pazarlık yapmak serbesttir ve genellikle her gün (Pazar hariç) açıktır.",
        "tips_en": "Bargaining is expected; generally open every day except Sundays."
    },
    {
        "name": "Oosterpark",
        "name_en": "Oosterpark",
        "area": "Oost",
        "category": "Park",
        "tags": ["park", "çok kültürlü", "huzur", "doğa"],
        "distanceFromCenter": 2.5,
        "lat": 52.3601,
        "lng": 4.9192,
        "price": "free",
        "rating": 4.4,
        "description": "Amsterdam'ın ilk büyük belediye parkı. Çok kültürlü bir atmosfere sahip olup geniş çimleri ve göletleriyle dinlenmek için harikadır.",
        "description_en": "Amsterdam's first large municipal park. It has a multicultural atmosphere and is great for relaxation with its vast lawns and ponds.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Tropenmuseum'un hemen yanındadır, müze ziyaretinden sonra dinlenmek için idealdir.",
        "tips_en": "Located right next to the Tropenmuseum; ideal for resting after a museum visit."
    },
    {
        "name": "De Pijp Mahallesi",
        "name_en": "De Pijp District",
        "area": "Oud-Zuid",
        "category": "Tarihi",
        "tags": ["çok kültürlü", "yemek", "bohem", "canlı"],
        "distanceFromCenter": 2.0,
        "lat": 52.3533,
        "lng": 4.8967,
        "price": "free",
        "rating": 4.7,
        "description": "Amsterdam'ın Latin Quarter'ı olarak bilinir. Çok kültürlü yapısı, harika restoranları ve Albert Cuyp Pazarı ile şehrin en popüler semtlerinden biridir.",
        "description_en": "Known as Amsterdam's Latin Quarter. One of the city's most popular districts with its multicultural structure, great restaurants, and the Albert Cuyp Market.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Heineken Experience'tan sonra bu mahalledeki ara sokaklarda kaybolup lokal bir barda oturabilirsiniz.",
        "tips_en": "After the Heineken Experience, get lost in the side streets of this neighborhood and stop in a local bar."
    },
    {
        "name": "Amsterdamse Bos (Amsterdam Ormanı)",
        "name_en": "Amsterdamse Bos",
        "area": "Amstelveen Border",
        "category": "Park",
        "tags": ["orman", "göl", "bisiklet", "keçi çiftliği"],
        "distanceFromCenter": 6.0,
        "lat": 52.3108,
        "lng": 4.8325,
        "price": "free",
        "rating": 4.8,
        "description": "Şehir merkezinin 3 katı büyüklüğünde devasa bir yapay park ve orman. Kürek çekme kanalları, keçi çiftliği ve geniş orman yolları bulunur.",
        "description_en": "A massive artificial park and forest, three times the size of the city center. Features rowing canals, a goat farm, and extensive forest paths.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Hafta sonu tam gün",
        "bestTime_en": "Full day on weekends",
        "tips": "De Ridammerhoeve keçi çiftliğinde taze peynir deneyebilir ve keçileri sevebilirsiniz.",
        "tips_en": "Try fresh cheese and pet the goats at the De Ridammerhoeve goat farm."
    },
    {
        "name": "H'ART Museum (Eski Hermitage)",
        "name_en": "H'ART Museum",
        "area": "Centrum",
        "category": "Müze",
        "tags": ["sanat", "tarih", "sergi", "nehir kıyısı"],
        "distanceFromCenter": 1.0,
        "lat": 52.3653,
        "lng": 4.9025,
        "price": "medium",
        "rating": 4.5,
        "description": "Amstel Nehri kıyısında 17. yüzyıldan kalma tarihi bir binada yer alan sanat müzesi. Dünyanın önde gelen müzeleriyle işbirliği içinde dev sergiler sunar.",
        "description_en": "An art museum housed in a historic 17th-century building on the banks of the Amstel River. Host to major exhibitions in collaboration with leading world museums.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin iç avlusu şehrin en sessiz ve güzel noktalarından biridir.",
        "tips_en": "The museum's inner courtyard is one of the quietest and most beautiful spots in the city."
    },
    {
        "name": "Westerkerk (Batı Kilisesi)",
        "name_en": "Westerkerk",
        "area": "Jordaan",
        "category": "Tarihi",
        "tags": ["kilise", "kule", "manzara", "rembrandt"],
        "distanceFromCenter": 0.8,
        "lat": 52.3745,
        "lng": 4.8838,
        "price": "low",
        "rating": 4.6,
        "description": "Anne Frank'ın günlüğünde sıkça bahsettiği, 85 metrelik kulesiyle Amsterdam'ın en yüksek kilise kulesine sahip tarihi yapı.",
        "description_en": "A historic church frequently mentioned in Anne Frank's diary, featuring Amsterdam's tallest church tower at 85 meters.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kuleye tırmanıp (rezervasyonla) muhteşem bir Jordaan ve kanal panoraması izleyebilirsiniz.",
        "tips_en": "Climb the tower (with reservation) for a magnificent panoramic view of the Jordaan and the canals."
    },
    {
        "name": "Tropenmuseum (Tropik Müze)",
        "name_en": "Tropenmuseum",
        "area": "Oost",
        "category": "Müze",
        "tags": ["etnografya", "dünya kültürleri", "mimari", "antropoloji"],
        "distanceFromCenter": 2.5,
        "lat": 52.3592,
        "lng": 4.9221,
        "price": "medium",
        "rating": 4.7,
        "description": "Dünya kültürlerine adanmış etkileyici bir etnografya müzesi. Hollanda'nın en güzel müze binalarından birinde yer alır.",
        "description_en": "An impressive ethnographic museum dedicated to world cultures. Located in one of the most beautiful museum buildings in the Netherlands.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Özellikle eski Hollanda sömürgeleriyle ilgili sergileri tarih meraklıları için çok aydınlatıcıdır.",
        "tips_en": "The exhibitions concerning former Dutch colonies are particularly enlightening for history enthusiasts."
    }
]

def enrich_amsterdam_batch2():
    filepath = 'assets/cities/amsterdam.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_amsterdam_batch2:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_amsterdam_batch2()
print(f"Amsterdam now has {count} highlights.")
