import json
import os

new_stockholm_batch1 = [
    {
        "name": "SkyView Stockholm",
        "name_en": "SkyView",
        "area": "Globen",
        "category": "Manzara",
        "tags": ["gondol", "küre", "panoramik", "ikonik"],
        "distanceFromCenter": 5.0,
        "lat": 59.2935,
        "lng": 18.0828,
        "price": "medium",
        "rating": 4.5,
        "description": "Dünyanın en büyük küresel binası olan Avicii Arena'nın tepesine çıkan cam gondollar. Stockholm'ün güneyinden tüm şehri görebileceğiniz eşsiz bir manzara sunar.",
        "description_en": "Glass gondolas that take you to the top of the Avicii Arena, the world's largest spherical building. It offers a unique view of the entire city from the south.",
        "imageUrl": "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Biletlerinizi önceden online almanız önerilir; seanslar yaklaşık 20 dakika sürer.",
        "tips_en": "Online booking is recommended; trips last about 20 minutes."
    },
    {
        "name": "Stockholm City Hall (Stadshuset)",
        "name_en": "Stockholm City Hall",
        "area": "Kungsholmen",
        "category": "Tarihi",
        "tags": ["belediye", "nobel", "mimari", "kule"],
        "distanceFromCenter": 0.8,
        "lat": 59.3275,
        "lng": 18.055,
        "price": "medium",
        "rating": 4.7,
        "description": "Her yıl Nobel ödül töreni ziyafetine ev sahipliği yapan görkemli bina. 8 milyon tuğladan yapılmış kulesi şehrin en önemli simgelerinden biridir.",
        "description_en": "The iconic building that hosts the annual Nobel Prize banquet. Its tower, made of 8 million bricks, is one of the city's most prominent landmarks.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Yaz aylarında kuleye çıkıp Mälaren Gölü ve Gamla Stan manzarasını izleyebilirsiniz.",
        "tips_en": "In summer, you can climb the tower for great views of Lake Mälaren and Gamla Stan."
    },
    {
        "name": "Nationalmuseum",
        "name_en": "National Museum",
        "area": "Blasieholmen",
        "category": "Müze",
        "tags": ["sanat", "tasarım", "heykel", "klasik"],
        "distanceFromCenter": 1.0,
        "lat": 59.3286,
        "lng": 18.0781,
        "price": "medium",
        "rating": 4.6,
        "description": "İsveç'in en büyük sanat ve tasarım müzesi. Orta Çağ'dan günümüze geniş bir resim, heykel ve modern tasarım koleksiyonuna sahiptir.",
        "description_en": "Sweden's premier destination for art and design. Features a vast collection from the Middle Ages to the present day.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze binası mimarisiyle de büyüleyicidir; restoranı ise oldukça kaliteli bir mola noktasıdır.",
        "tips_en": "The building's architecture is stunning, and the restaurant is an excellent spot for a break."
    },
    {
        "name": "Drottningholm Palace",
        "name_en": "Drottningholm Palace",
        "area": "Lovön",
        "category": "Tarihi",
        "tags": ["saray", "unesco", "kraliyet", "bahçe"],
        "distanceFromCenter": 10.0,
        "lat": 59.3217,
        "lng": 17.8863,
        "price": "high",
        "rating": 4.8,
        "description": "İsveç kraliyet ailesinin ikametgahı olan UNESCO koruması altındaki saray topluluğu. Görkemli bahçeleri ve Çin köşküyle 'İsveç'in Versailles'ı' olarak anılır.",
        "description_en": "Sweden's best-preserved royal palace, a UNESCO World Heritage site and home to the Royal Family. Often called the 'Versailles of Sweden'.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Şehir merkezinden kalkan tarihi buharlı teknelerle gitmek yaklaşık 1 saat sürer ve çok keyiflidir.",
        "tips_en": "Taking a historic steamboat from the city center is a delightful 1-hour journey."
    },
    {
        "name": "Monteliusvägen",
        "name_en": "Monteliusvägen",
        "area": "Södermalm",
        "category": "Manzara",
        "tags": ["yürüyüş", "panoramik", "romantik", "ücretsiz"],
        "distanceFromCenter": 1.2,
        "lat": 59.3207,
        "lng": 18.06,
        "price": "free",
        "rating": 4.9,
        "description": "Riddarfjärden gölüne ve Belediye Binası'na bakan 500 metrelik dar yürüyüş yolu. Stockholm'ün en fotojenik panoramik manzaralarından birini sunar.",
        "description_en": "A 500-meter long walking path with stunning views of Lake Mälaren and the City Hall. One of the most photogenic panoramic spots in the city.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Ivar Lo's Park'ın hemen yanındaki gizli girişi bulun, yerel halk burada piknik yapmayı çok sever.",
        "tips_en": "Find the entrance next to Ivar Lo's Park; it's a favorite local picnic spot."
    },
    {
        "name": "Metro Sanat Turu (Blue Line)",
        "name_en": "Stockholm Metro Art Tour",
        "area": "Şehir Geneli",
        "category": "Deneyim",
        "tags": ["metro", "sanat", "yer altı", "galeri"],
        "distanceFromCenter": 0.5,
        "lat": 59.3317,
        "lng": 18.0608,
        "price": "low",
        "rating": 4.8,
        "description": "'Dünyanın en uzun sanat galerisi' olarak bilinen 110 kilometrelik metro ağı. T-Centralen, Solna Centrum ve Kungsträdgården en etkileyici istasyonlardır.",
        "description_en": "Known as the 'world's longest art gallery', covering 110 km of underground tracks. T-Centralen and Solna Centrum are must-visits.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Öğleden sonra (yoğun saat dışı)",
        "bestTime_en": "Afternoon (off-peak)",
        "tips": "Sadece bir SL bileti alarak saatlerce farklı istasyonlardaki devasa resimleri ve heykelleri keşfedebilirsiniz.",
        "tips_en": "With just a standard metro ticket, you can explore hours of massive paintings and sculptures across various stations."
    },
    {
        "name": "Östermalm Saluhall (Pazar Yeri)",
        "name_en": "Östermalm Food Hall",
        "area": "Östermalm",
        "category": "Deneyim",
        "tags": ["gurme", "yiyecek", "tarihi pazar", "balık"],
        "distanceFromCenter": 1.0,
        "lat": 59.3363,
        "lng": 18.0772,
        "price": "high",
        "rating": 4.6,
        "description": "1888'den beri hizmet veren görkemli tuğla bina içindeki lüks yemek pazarı. En kaliteli İsveç deniz ürünlerini ve şarküterisini burada bulabilirsiniz.",
        "description_en": "A legendary food hall since 1888, housed in a magnificent brick building. Best place for top-quality Swedish seafood and delicacies.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğle yemeği",
        "bestTime_en": "Lunch",
        "tips": "Lisa Elmqvist'te geleneksel taze balık yemeklerini denemeden ayrılmayın.",
        "tips_en": "Don't miss the traditional fresh fish dishes at Lisa Elmqvist."
    },
    {
        "name": "Rosendals Trädgård",
        "name_en": "Rosendals Garden",
        "area": "Djurgården",
        "category": "Park",
        "tags": ["organik", "bahçe", "kafe", "dinlence"],
        "distanceFromCenter": 3.0,
        "lat": 59.3230,
        "lng": 18.1082,
        "price": "medium",
        "rating": 4.7,
        "description": "Djurgården adasının kalbinde yer alan organik tarım bahçesi ve el yapımı ekmekleriyle ünlü masalsı kafe. Seralar içinde oturup doğayla iç içe vakit geçirebilirsiniz.",
        "description_en": "An organic garden and greenhouse cafe on Djurgården island, famous for its handmade bread and idyllic atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "İlkbahar ve Yaz",
        "bestTime_en": "Spring and Summer",
        "tips": "Kendi yaptıkları elma şırası (cider) ve tarçınlı çörekleri (kanelbullar) mutlaka deneyin.",
        "tips_en": "Try their own apple cider and cinnamon buns (kanelbullar)."
    },
    {
        "name": "Moderna Museet (Modern Sanat)",
        "name_en": "Moderna Museet",
        "area": "Skeppsholmen",
        "category": "Müze",
        "tags": ["modern sanat", "picasso", "dali", "galeri"],
        "distanceFromCenter": 1.0,
        "lat": 59.325,
        "lng": 18.0835,
        "price": "low",
        "rating": 4.5,
        "description": "Avrupa'nın önde gelen modern sanat müzelerinden biri. Picasso, Dali ve Matisse gibi dev isimlerin eserlerine ev sahipliği yapar.",
        "description_en": "One of Europe's leading museums for modern and contemporary art, featuring works by Picasso, Dali, and Matisse.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Skeppsholmen adasına yürüyerek geçmek, yol üzerindeki köprülerden harika fotoğraflar çekmenizi sağlar.",
        "tips_en": "Walking to Skeppsholmen island allows for great photo opportunities from the bridges."
    },
    {
        "name": "Spiritmuseum",
        "name_en": "Museum of Spirits",
        "area": "Djurgården",
        "category": "Müze",
        "tags": ["içki kültürü", "interaktif", "tadım", "eğlence"],
        "distanceFromCenter": 2.2,
        "lat": 59.3283,
        "lng": 18.0933,
        "price": "medium",
        "rating": 4.4,
        "description": "İsveç'in alkol ile olan karmaşık ilişkisini anlatan, interaktif ve eğlenceli bir müze. Absolut Art koleksiyonu da burada sergilenir.",
        "description_en": "A quirky and interactive museum exploring Sweden's complex relationship with alcohol, featuring the Absolut Art Collection.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Müze içindeki tadım turları Stockholm'un en popüler aktivitelerinden biridir.",
        "tips_en": "The museum's tasting tours are among Stockholm's most popular activities."
    },
    {
        "name": "Army Museum (Armémuseum)",
        "name_en": "Army Museum",
        "area": "Östermalm",
        "category": "Müze",
        "tags": ["askeri tarih", "zırhlar", "savaş", "tarihi"],
        "distanceFromCenter": 1.0,
        "lat": 59.3342,
        "lng": 18.0797,
        "price": "low",
        "rating": 4.6,
        "description": "İsveç askeri tarihini, 16. yüzyıldan günümüze kadar anlatan oldukça etkileyici bir müze. Devasa toplar ve savaş canlandırmaları bulunur.",
        "description_en": "An impressive museum detailing Swedish military history from the 16th century to today, featuring massive cannons and war dioramas.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Danimarka ile olan tarihi savaşları anlatan bölümler oldukça objektif ve ilgi çekicidir.",
        "tips_en": "Sections explaining historical wars with Denmark are objective and very interesting."
    },
    {
        "name": "Pelikan (Geleneksel Restoran)",
        "name_en": "Pelikan",
        "area": "Södermalm",
        "category": "Restoran",
        "tags": ["isveç mutfağı", "klasik", "tarihi", "köfte"],
        "distanceFromCenter": 1.8,
        "lat": 59.3107,
        "lng": 18.0759,
        "price": "high",
        "rating": 4.5,
        "description": "1904'ten beri hizmet veren, yüksek tavanlı görkemli salonuyla ünlü geleneksel İsveç meyhanesi. SOS (Tereyağı, Peynir, Ringa Balığı) tabağı buranın klasiğidir.",
        "description_en": "A historic Swedish tavern since 1904, famous for its grand high-ceilinged hall and traditional 'Husmanskost' dishes.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Ren geyiği (reindeer) veya geyik (elk) eti denemek isteyenler için en iyi adreslerden biridir.",
        "tips_en": "One of the best places to try reindeer or elk meat if you're feeling adventurous."
    },
    {
        "name": "Södra Teatern & Mosebacke Terrace",
        "name_en": "Södra Teatern",
        "area": "Södermalm",
        "category": "Manzara",
        "tags": ["manzara", "gece hayatı", "konser", "popüler"],
        "distanceFromCenter": 1.0,
        "lat": 59.3177,
        "lng": 18.0712,
        "price": "low",
        "rating": 4.6,
        "description": "Tarihi tiyatro binasının devasa terası Mosebacke, yaz aylarında şehrin en canlı noktasıdır. Gamla Stan ve Djurgården manzarasına karşı bir şeyler içmek paha biçilemez.",
        "description_en": "The grand terrace of the historic Södra Teatern, Mosebacke is a buzzing summer spot with amazing views over Gamla Stan and Djurgården.",
        "imageUrl": "https://images.unsplash.com/photo-1514525253361-bee1a2399222?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Özellikle hafta sonları çok kalabalık olur, erken gelip masanızı kapın.",
        "tips_en": "Gets very crowded on weekends; arrive early to snag a table."
    },
    {
        "name": "Fotografiska Stockholm",
        "name_en": "Fotografiska",
        "area": "Södermalm",
        "category": "Müze",
        "tags": ["fotoğraf", "modern", "sergi", "manzara"],
        "distanceFromCenter": 1.5,
        "lat": 59.3173,
        "lng": 18.0842,
        "price": "medium",
        "rating": 4.8,
        "description": "Eski bir liman antreposunda yer alan dünyanın en büyük çağdaş fotoğraf müzelerinden biri. Sürekli değişen sergileriyle her zaman taze kalır.",
        "description_en": "One of the world's largest contemporary photography museums, housed in a former port warehouse with ever-changing exhibitions.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Geç saatler (Gece yarısına kadar açık)",
        "bestTime_en": "Late hours (Open until midnight)",
        "tips": "En üst kattaki restoranı hem ödüllü lezzetler hem de su kıyısından Stockholm manzarası sunar.",
        "tips_en": "The top-floor restaurant offers award-winning food and a stunning harbor view."
    },
    {
        "name": "Hagaparken (Haga Parkı)",
        "name_en": "Haga Park",
        "area": "Solna",
        "category": "Park",
        "tags": ["doğa", "saray", "piknik", "göl"],
        "distanceFromCenter": 3.5,
        "lat": 59.3567,
        "lng": 18.0333,
        "price": "free",
        "rating": 4.7,
        "description": "Stockholm'ün en büyük ve güzel kraliyet parklarından biri. Gustav III'ün bakır çadırları ve İsveç veliaht prensesinin sarayı buradadır.",
        "description_en": "One of Sweden's most beautiful English-style parks, home to Haga Palace and the ornate copper tents of Gustav III.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Güneşli öğleden sonra",
        "bestTime_en": "Sunny afternoon",
        "tips": "Kelebek Evi (Fjärilshuset) parkın içinde çocuklarla gezilecek en iyi noktalardan biridir.",
        "tips_en": "The Butterfly House (Fjärilshuset) within the park is a highlight for families."
    },
    {
        "name": "Skansen (Açık Hava Müzesi)",
        "name_en": "Skansen",
        "area": "Djurgården",
        "category": "Müze",
        "tags": ["açık hava", "kültür", "hayvanat bahçesi", "lokal"],
        "distanceFromCenter": 2.5,
        "lat": 59.3261,
        "lng": 18.1036,
        "price": "medium",
        "rating": 4.8,
        "description": "Dünyanın en eski açık hava müzesi. 1891'de kurulan bu devasa alan, İsveç'in dört bir yanından getirilen tarihi binalar ve çiftliklerle İsveç tarihini canlandırır.",
        "description_en": "The world's oldest open-air museum, showcasing Swedish history through historic buildings, craft demonstrations, and Nordic animals.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Vahşi hayvanlar bölümünde ayı, kurt ve geyikleri görebilirsiniz; tam gün ayırmaya değer.",
        "tips_en": "You can see bears, wolves, and moose in the wildlife section; worth a full day."
    },
    {
        "name": "Meatballs for the People",
        "name_en": "Meatballs for the People",
        "area": "Södermalm",
        "category": "Restoran",
        "tags": ["köfte", "gurme", "lokal", "yiyecek"],
        "distanceFromCenter": 1.2,
        "lat": 59.3158,
        "lng": 18.0729,
        "price": "medium",
        "rating": 4.6,
        "description": "Stockholm'ün en iyi köftecisi! Sadece sığır eti değil; geyik, yaban domuzu ve somon köftesi gibi çok farklı çeşitler sunan bir gurme mekanıdır.",
        "description_en": "Stockholm's premier boutique meatball spot, offering everything from classic beef to wild boar and reindeer varieties.",
        "imageUrl": "https://images.unsplash.com/photo-1550966842-28df0503043d?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Her zaman kalabalıktır, isim yazdırmak veya önceden rezervasyon yaptırmak akıllıca olur.",
        "tips_en": "Always busy; putting your name on a list or booking ahead is wise."
    },
    {
        "name": "Stockholm Public Library (Asplundhuset)",
        "name_en": "Stockholm Public Library",
        "area": "Vasastan",
        "category": "Tarihi",
        "tags": ["kütüphane", "mimari", "kitap", "ikonik"],
        "distanceFromCenter": 1.5,
        "lat": 59.3436,
        "lng": 18.0546,
        "price": "free",
        "rating": 4.7,
        "description": "Gunnar Asplund tarafından tasarlanan, dünya mimarlık tarihinin en önemli yapılarından biri. Dairesel ana salonu ve 360 derece kitap dolu duvarlarıyla ünlüdür.",
        "description_en": "An architectural masterpiece by Gunnar Asplund. Its rotunda with 360-degree walls of books is world-renowned.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Asansörle çıkılan üst katlardan salonun simetrisini fotoğraflamak her fotoğrafçının rüyasıdır.",
        "tips_en": "Photographing the symmetry of the hall from the upper floors is a dream for any photographer."
    },
    {
        "name": "Nordiska Museet",
        "name_en": "Nordic Museum",
        "area": "Djurgården",
        "category": "Müze",
        "tags": ["kültür", "tarih", "iskandinav", "yaşam tarzı"],
        "distanceFromCenter": 2.0,
        "lat": 59.3292,
        "lng": 18.0933,
        "price": "medium",
        "rating": 4.5,
        "description": "İsveç halk kültürünü ve yaşam tarzını 16. yüzyıldan günümüze kadar inceleyen devasa müze. Bina dışarıdan bir sarayı andırır.",
        "description_en": "Sweden's largest museum of cultural history, documenting Nordic lifestyle and traditions since the 16th century.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin ana salonundaki dev Kral Gustav Vasa heykeli girişte sizi ihtişamla karşılar.",
        "tips_en": "Don't miss the massive King Gustav Vasa statue in the main hall as you enter."
    },
    {
        "name": "Gröna Lund",
        "name_en": "Gröna Lund",
        "area": "Djurgården",
        "category": "Deneyim",
        "tags": ["lunapark", "eğlence", " adrenalin", "sahil"],
        "distanceFromCenter": 2.5,
        "lat": 59.3233,
        "lng": 18.0967,
        "price": "high",
        "rating": 4.4,
        "description": "Stockholm'ün tarihi sahil şeridinde yer alan en popüler lunaparkı. Dar alanına rağmen sığdırılan heyecan verici üniteleri ve yaz konserleriyle ünlüdür.",
        "description_en": "Stockholm's beloved seaside amusement park, known for its thrilling rides and legendary open-air summer concerts.",
        "imageUrl": "https://images.unsplash.com/photo-1561580119-967a112c858e?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Yaz aylarında akşamları büyük dünya yıldızlarının konserlerine denk gelebilirsiniz.",
        "tips_en": "Keep an eye on the summer concert schedule for world-renowned artists."
    }
]

def enrich_stockholm_batch1():
    filepath = 'assets/cities/stockholm.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # First, cleanup fillers in existing highlights
    for h in data.get('highlights', []):
        if "Yerel yaşamın en canlı hali" in h['description'] or "Sanat ve tarih meraklılarının uğrak noktası" in h['description']:
             if h['name'] == "Gamla Stan":
                 h['description'] = "Stockholm'ün 13. yüzyıldan kalma büyüleyici 'Eski Şehir' bölgesi. Arnavut kaldırımlı sokakları, renkli ortaçağ binaları ve dar geçitleriyle (Mårten Trotzigs Gränd) adeta bir açık hava müzesidir."
                 h['description_en'] = "Stockholm's 13th-century 'Old Town' with cobblestone streets, colorful medieval buildings, and narrow alleys like Mårten Trotzigs Gränd (only 90cm wide)."
             if h['name'] == "Vasa Müzesi":
                 h['description'] = "1628 yılında denize açıldıktan hemen sonra batan ve 333 yıl su altında kaldıktan sonra tek parça halinde çıkarılan devasa savaş gemisi. Dünyanın en iyi korunmuş 17. yüzyıl gemisidir."
                 h['description_en'] = "The world's best-preserved 17th-century ship. The massive warship sank on its maiden voyage in 1628 and was salvaged 333 years later in near-perfect condition."
             if h['name'] == "ABBA The Museum":
                 h['description'] = "Sadece bir müze değil, ABBA grubunun bir parçası olabileceğiniz interaktif bir deneyim. Grubun kostümleri, altın plakları ve orijinal stüdyolarının kopyaları bulunur."
                 h['description_en'] = "An interactive experience where you can become the fifth member of ABBA. Features costumes, gold records, and original studio recreations."
             if h['name'] == "Fotografiska":
                 h['description'] = "Dünyanın en büyük çağdaş fotoğrafçılık merkezlerinden biri. Eski bir liman antreposunda yer alan bu modern sanat galerisi, sürekli değişen dünya çapındaki sergileriyle ünlüdür."
                 h['description_en'] = "One of the world's largest contemporary photography meeting places. Housed in a former industrial building on the waterfront."

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_stockholm_batch1:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_stockholm_batch1()
print(f"Stockholm now has {count} highlights.")
