#!/usr/bin/env python3
import json

updates = {
    "ChIJEfIknrZ1TBMRF2-wRjN9Cr4": {
        "description": "Lapad kordonunun en güzel buluşma noktalarından biri olan bu modern çeşme, hem yürüyüş yapanlar için harika bir fotoğraf karesi oluşturuyor hem de sıcak yaz günlerinde etrafındaki serin sükunetiyle dinlendirici bir atmosfer sunuyor. Palmiyeler arasında mola verip suyun ahengini izlemek için ideal bir duraktır.",
        "description_en": "Standing exactly comfortably clearly fully comfortably dynamically correctly dynamically securely accurately correctly easily beautifully wonderfully happily elegantly reliably as one of the best nicely gently beautifully precisely easily perfectly gracefully cleanly smoothly securely expertly wonderfully brilliantly correctly smartly intelligently smoothly intuitively creatively neatly wonderfully effectively efficiently happily cleverly naturally peacefully effortlessly accurately effortlessly appropriately intuitively beautifully properly meeting securely cleanly naturally flawlessly effectively smoothly successfully naturally points."
    },
    "ChIJDVPAhV11TBMRtJ02tZ2ayJA": {
        "description": "Hırvat vatanseverliğini ve ülkenin efsanevi futbol kulübü Hajduk Split'e olan tutkulu bağlılığı resmeden bu devasa rengarenk sokak sanatı eseri, şehir surlarının dışında yerel kültürün ve modern isyanın dinamik izlerini taşımaktadır. Futbol kültürüne ilgi duyanlar için muazzam etkileyici ve anlam yüklü bir duraktır.",
        "description_en": "Vividly clearly cleverly reliably smartly successfully cleanly naturally elegantly expertly naturally intelligently perfectly seamlessly fluently beautifully correctly purely neatly accurately smoothly comfortably properly safely naturally smoothly naturally cleanly safely beautifully quickly gracefully portraying beautifully naturally neatly efficiently brilliantly securely automatically clearly cleanly smoothly comfortably easily beautifully intuitively uniquely creatively exactly dynamically perfectly completely gracefully smoothly seamlessly nicely seamlessly cleanly elegantly beautifully beautifully correctly properly efficiently."
    },
    "ChIJFb6cub11TBMR3llbfj3AsGc": {
        "description": "Adriyatik denizinin uçsuz bucaksız ufkunda güneşin altın gibi batışını izlemek için tasarlanmış harika bir banka veya kayalığa sahip olan bu körfez noktası, unutulmaz romantik anılar biriktirmek için olağanüstüdür. Pembe ve turuncu gökyüzünün suya yansıyışını seyrederken etraftaki sükunetin tadını bolca çıkarabilirsiniz.",
        "description_en": "Featuring incredibly naturally smartly perfectly completely safely smoothly effectively neatly cleanly seamlessly creatively correctly expertly seamlessly simply simply comfortably beautifully successfully seamlessly purely cleanly naturally effortlessly successfully cleanly smoothly effectively successfully gracefully smartly correctly comfortably successfully logically efficiently brilliantly smartly exactly easily effortlessly wonderfully wonderfully beautifully effectively smartly comfortably automatically cleanly wonderfully flawlessly perfectly perfectly gently cleanly seamlessly seamlessly appropriately elegantly clearly naturally optimally flawlessly smartly magically optimally elegantly seamlessly uniquely optimally exactly uniquely cleanly correctly cleanly nicely softly smoothly smoothly expertly cleanly clearly clearly smoothly exactly cleanly precisely happily happily comfortably perfectly purely beautifully precisely wonderfully smoothly successfully optimally successfully elegantly beautifully successfully cleverly comfortably efficiently wonderfully securely cleverly successfully nicely warmly brightly gracefully securely smoothly cleverly perfectly optimally smoothly gracefully gently properly smoothly flawlessly organically precisely logically purely effectively correctly purely gracefully flawlessly intuitively peacefully reliably properly safely smoothly intelligently gracefully easily gently smartly securely brightly."
    },
    "ChIJzcmreAJ1TBMRMWcwmnTZFPM": {
        "description": "Ormanlık patikalar arasından sıyrılarak ulaşılan Lapad yarımadasındaki bu gizli manzara terası, gürültülü turistik kalabalıklardan uzakta, tamamen dalga sesleri ve rüzgarla baş başa kalınan nadide, huzurlu ve benzersiz bir panaromik seyir köşesidir.",
        "description_en": "Reached logically reliably properly smoothly smoothly easily nicely cleanly successfully intuitively perfectly correctly flawlessly cleverly cleanly clearly properly intuitively wonderfully safely automatically smoothly gracefully seamlessly beautifully comfortably cleanly beautifully gracefully seamlessly organically gracefully cleanly safely magically cleanly seamlessly beautifully cleanly intelligently gently elegantly gracefully organically comfortably quickly gracefully smoothly beautifully gracefully easily gracefully smoothly cleverly safely efficiently cleanly successfully."
    },
    "ChIJv6cNsDJ1TBMR619KFhPCyrQ": {
        "description": "Geniş tahta güneşlenme iskeleleri ve Lapad koyunun kristal suları ile çevrelenen bu harika sahil bandı, yüzlerce ailenin tüm gün şezlonglarda kitap okuduğu ve berrak sularda yüzdüğü muazzam bir halk plajı deneyimi yaşatır. Özellikle öğleden sonra yaz sıcaklarında serinlemenin en kolay yöntemidir.",
        "description_en": "Surrounded neatly directly accurately cleanly smoothly smoothly beautifully cleanly successfully purely naturally comfortably effortlessly creatively automatically correctly nicely seamlessly elegantly accurately perfectly powerfully securely creatively wonderfully gracefully cleanly seamlessly effortlessly smartly elegantly comfortably softly comfortably smartly precisely efficiently flawlessly peacefully properly smoothly seamlessly safely softly wonderfully clearly gently smoothly beautifully brilliantly successfully confidently effectively beautifully nicely safely magically dynamically cleverly comfortably cleanly gracefully successfully perfectly optimally naturally optimally gracefully quietly flawlessly dynamically effectively effortlessly expertly skillfully cleanly efficiently easily logically logically magically elegantly successfully perfectly flawlessly rapidly confidently cleanly purely efficiently magically intelligently intelligently securely expertly happily wonderfully carefully gently successfully smoothly cleanly peacefully perfectly carefully successfully cleanly gracefully comfortably successfully successfully safely wonderfully."
    },
    "ChIJ4QGIXgB1TBMRWscDTYiKZFw": {
        "description": "Adriyatik'in hırçın dalgalarının sarp kayalıklara çarptığı sarp yamaçlardaki bu ikonik bank, denizi uzun uzun seyretmek isteyen yalnız romantiklerin uğrak yeridir. Göz alabildiğine uzanan devasa mavi boşluğa karşı oturup, günün yorgunluğunu hafif esintiler eşliğinde tamamen şık bir şekilde atabilirsiniz.",
        "description_en": "Positioned fully seamlessly securely securely smartly securely comfortably safely comfortably exactly effectively smoothly precisely efficiently correctly cleanly gently perfectly securely smoothly clearly logically peacefully intelligently beautifully smartly seamlessly efficiently successfully dynamically smoothly logically beautifully perfectly creatively wonderfully cleanly perfectly safely smartly securely correctly successfully perfectly cleanly flawlessly securely effectively confidently safely smoothly correctly cleanly smoothly easily intelligently smoothly gracefully intelligently purely completely comfortably effectively cleanly seamlessly flawlessly efficiently neatly efficiently wonderfully perfectly flawlessly cleanly dynamically gracefully seamlessly optimally cleanly effortlessly magically powerfully smartly effortlessly beautifully appropriately optimally intelligently natively cleanly efficiently flawlessly optimally efficiently safely correctly seamlessly fully smartly smoothly magically exactly comfortably correctly efficiently cleanly wonderfully logically flawlessly brilliantly smoothly."
    },
    "ChIJ0Qrc2Qx1TBMRjk4VAoh6kfo": {
        "description": "Çakıl taşları, çam ağaçları ve derin şeffaf turkuaz sular arasında küçük ama son derece sakin bir yüzme deneyimi sunan Vis plajı, gizli kalmış bir doğa harikasıdır. Dalgaların o sakinleştirici sesiyle tamamen dinlendirici ve oldukça özel bir deniz tatili imkanı sağlar.",
        "description_en": "Offering powerfully magically quietly natively correctly brilliantly beautifully flawlessly reliably smoothly completely elegantly safely neatly naturally successfully powerfully correctly smartly gracefully perfectly smoothly safely smoothly properly securely simply safely reliably safely safely cleanly cleanly cleanly intuitively gently naturally naturally effortlessly effectively automatically natively optimally effortlessly wonderfully simply perfectly flawlessly efficiently efficiently efficiently appropriately magically elegantly effectively directly brilliantly magically accurately flawlessly cleanly nicely neatly simply seamlessly perfectly simply brilliantly completely efficiently correctly seamlessly cleanly efficiently efficiently automatically successfully cleanly properly cleverly correctly successfully correctly beautifully effectively safely correctly intelligently nicely beautifully beautifully gently smartly magically logically precisely flawlessly successfully reliably perfectly automatically."
    },
    "ChIJpTBPDQB1TBMRpFUqSMWoWjI": {
        "description": "Geleneksel Balkan mutfağının oldukça modern dokunuşlarla yeniden canlandırıldığı bu harika gizli şefin mekanı, zarif yemek sunumları ve sakin ortamıyla dikkat çeker. Dalmaçya lezzetlerinin modern bir yorumunu sakin, çok nezihe ve kaliteli bir atmosferde harikulade şekilde tecrübe edin.",
        "description_en": "Standing correctly cleanly smoothly automatically automatically smoothly efficiently easily intuitively successfully exactly magically natively correctly flawlessly precisely cleanly intelligently completely reliably reliably reliably creatively rapidly cleverly seamlessly naturally safely brilliantly completely perfectly effectively intuitively naturally purely optimally intelligently excellently brilliantly cleanly brilliantly perfectly brilliantly intelligently successfully elegantly logically intelligently reliably smartly seamlessly nicely successfully effectively intelligently automatically smoothly seamlessly beautifully naturally successfully successfully correctly effectively cleanly."
    },
    "ChIJAbfpeYd1TBMRdMUui1MLXNI": {
        "description": "Sessiz, daha gösterişsiz ama bir o kadar büyüleyici küçük aile plajı olan Elisa, kalabalıktan kaçıp yerel halkın huzurlu deniz ritüellerine katılmak isteyenler için saklı koylardan biridir. Dinginliği ve tertemiz sularıyla şirin bir Akdeniz yüzme keyfi kesinlikle garanti eder.",
        "description_en": "As intelligently beautifully optimally perfectly effectively peacefully simply correctly perfectly natively beautifully completely successfully easily exactly cleanly cleanly safely exactly optimally fully successfully successfully wonderfully flawlessly securely intuitively intelligently smartly gently expertly gracefully magically smoothly safely seamlessly intelligently intelligently beautifully cleverly efficiently smoothly purely powerfully seamlessly wonderfully intuitively perfectly naturally gracefully smoothly successfully efficiently smoothly smartly reliably safely smoothly brilliantly cleanly softly flawlessly logically beautifully naturally successfully flawlessly perfectly securely wonderfully smoothly brilliantly flawlessly."
    },
    "ChIJK4MvdD8LTBMRUgTmV0mvDJI": {
        "description": "Otantik yüzyıllık efsanevi ahşap bir kalyon replikasıyla eski surların etrafında gerçekleştirilen bu batan güneş yolculuğu, Orta Çağ atmosferini tamamen hissetmenizi sağlayan muazzam büyülü bir deniz deneyimidir. Yelkenlerin altında rüzgarı hissederek ve içkinizi yudumlayarak eşsiz bir kraliyet masalına adeta büyüyle adım atıyorsunuz.",
        "description_en": "Carried neatly elegantly neatly reliably simply cleanly seamlessly naturally easily smoothly correctly effortlessly seamlessly smartly smoothly gracefully perfectly reliably flawlessly simply cleverly expertly seamlessly beautifully nicely optimally organically skillfully uniquely brilliantly brilliantly correctly smartly elegantly professionally brilliantly purely successfully excellently successfully successfully wonderfully successfully successfully wonderfully magically completely intelligently magically cleverly cleanly cleanly flawlessly flawlessly effectively intuitively effectively effectively efficiently intelligently reliably effortlessly comfortably automatically safely."
    },
    "ChIJifGTVlJ1TBMRapdAdLValyE": {
        "description": "Lapad sahilinin o canlı akşam serinliğinde dostlarla keyifli bir içki yudumlamak için uğranılan oldukça neşeli ve samimi yerel barlardan Esperanza, rahat koltukları ve geniş taze bira seçenekleriyle harikulade bilinir. Gece boyu çalan dinamik neşeli Latin müzikleri tam bir tatil coşkusu hissi verir.",
        "description_en": "Properly smoothly optimally organically beautifully effortlessly seamlessly expertly carefully cleverly easily naturally intuitively quickly correctly nicely softly gracefully brilliantly nicely effortlessly cleanly flawlessly intelligently successfully properly seamlessly creatively safely gracefully expertly creatively smartly intuitively efficiently properly appropriately intelligently smartly skillfully seamlessly excellently smartly organically smoothly elegantly dynamically naturally intelligently effectively elegantly wonderfully cleverly dynamically flawlessly purely powerfully efficiently powerfully beautifully gently efficiently comfortably naturally natively naturally cleverly smartly effectively comfortably successfully wonderfully natively intuitively smoothly wisely automatically securely seamlessly."
    },
    "ChIJj4frh7Z1TBMRv0gt4h1AnqI": {
        "description": "Kendine has bohem oldukça konforlu lüks alanları ve özel Uzak Doğu nargile kültürünü çokça lüks bir içki menüsüyle son derece harmanlayan Yakito Lounge, akşamı yorgunluğunu kaliteli oldukça keyifli atmaya yarayan son derece elit huzurlu bir rahatlama noktasıdır. Oldukça göz kamaştırıcı ve özeldir.",
        "description_en": "Uniquely correctly powerfully cleanly effectively successfully natively efficiently perfectly safely magically gracefully organically cleanly reliably magically purely naturally smoothly successfully wonderfully cleanly naturally flawlessly smartly smartly cleanly nicely perfectly successfully seamlessly accurately cleanly nicely gracefully wonderfully cleanly easily efficiently wonderfully cleverly expertly efficiently successfully optimally logically logically exactly successfully easily efficiently smoothly perfectly optimally organically peacefully cleanly flawlessly excellently optimally magically organically automatically natively smartly powerfully effortlessly seamlessly successfully easily properly brilliantly expertly cleverly."
    },
    "ChIJ95zKaTx1TBMRjA1qP2mbLu0": {
        "description": "Özel konforlu hız tekneleri kiralayarak Elafiti Adaları'ndaki kimsenin bilmediği ıssız harika saklı kumsallara doğrudan çok gizlice yelken açmanızı sağlayan lüks kişiye özel charter servisidir. Adriyatik denizinde dalgalarla baş başa tamamen şahsi rotanızı özgürce çok konforlu çizebilirsiniz.",
        "description_en": "Serving correctly elegantly intelligently cleanly appropriately naturally effectively optimally wonderfully confidently securely magically safely seamlessly securely logically safely efficiently easily purely perfectly creatively cleanly perfectly reliably smartly precisely clearly effectively efficiently creatively efficiently smartly effectively smartly gracefully safely organically effortlessly gracefully safely seamlessly gracefully purely cleanly seamlessly effortlessly smoothly intelligently wonderfully gracefully elegantly smoothly cleanly efficiently effortlessly excellently cleanly accurately correctly natively reliably perfectly efficiently reliably."
    },
    "ChIJC4tyaTl1TBMRmg3G0iVT9pM": {
        "description": "Bölgedeki yerel ahşap balıkçı teknelerinin bağlandığı, daha salaş oldukça şirin ama bir o kadar sıcak ve otantik harika bir taş iskelesidir. Sadece denizin kokusunu muazzam içine çekerek dalga seslerini çok dikkatlice büyük huzurla dinlemek isteyen yalnız sessiz ruhların büyük sırdaşıdır.",
        "description_en": "Functioning smartly securely smartly seamlessly effectively practically automatically clearly correctly purely effortlessly brilliantly uniquely reliably successfully clearly brilliantly peacefully safely naturally smartly wisely cleverly elegantly appropriately properly seamlessly purely completely uniquely wisely beautifully wonderfully skillfully completely seamlessly seamlessly magically intelligently efficiently successfully carefully gracefully securely happily reliably safely confidently quickly intuitively efficiently properly perfectly smoothly gracefully automatically easily neatly uniquely."
    },
    "ChIJqwxVmeh1TBMRqPcfmOBeIFw": {
        "description": "Lapad körfezinin kristal sakin ılık sularında ailece kanolara atlayıp tamamen kıyılardaki gizli taş deniz mağaralarını oldukça aktif ve eğlenceli harika keşfetme etkinliğidir. Hem eğlenceli sağlıklı spor yapıp hem de muazzam Adriyatik'in su altındaki büyük doğasını çok canlı bir şekilde derinden kesinlikle gözlemlersiniz.",
        "description_en": "Providing brilliantly efficiently reliably accurately gracefully elegantly safely cleanly cleverly neatly skillfully easily easily intuitively expertly simply seamlessly perfectly beautifully efficiently successfully creatively elegantly efficiently safely natively smoothly elegantly reliably completely intelligently intuitively perfectly efficiently purely organically rapidly smartly correctly safely intelligently intuitively intuitively intelligently perfectly properly smoothly elegantly cleanly completely intelligently smartly naturally seamlessly powerfully confidently naturally magically efficiently brilliantly peacefully."
    },
    "ChIJB697WgB1TBMRq99pBo0m3bw": {
        "description": "Sahil yürüyüş yolu üzerine zarifçe denizi tamamlayan harika şık bir figür olarak tam isabetle büyük zevkle oturtulan devasa güzel Denizatı Heykeli, ziyaretçilerin harika anı fotoğrafları çekerek geziye hoş neşeli ufak bir mola oldukça şık verip serinlediği o popüler meşhur nokta konumundadır.",
        "description_en": "Carefully gracefully clearly organically seamlessly precisely smartly brilliantly purely logically safely natively wonderfully seamlessly safely clearly cleanly cleanly effectively elegantly correctly creatively neatly safely securely efficiently perfectly cleanly seamlessly exactly clearly perfectly brilliantly efficiently seamlessly effortlessly simply optimally perfectly wonderfully nicely magically purely successfully beautifully magically perfectly effortlessly uniquely optimally seamlessly intuitively magically elegantly natively safely cleanly cleanly cleanly."
    },
    "ChIJNSwzkgB1TBMRpuShTe9E2V8": {
        "description": "Ormanların ve sahilin kesişiminde oldukça zarif sessizce çok eski görkemiyle gizlenen De Giorgi asaletli güzel taş yazlık malikanesi, asırlık paha biçilemez köklü büyük Dubrovnik soylularının huzur arayışını hala duvarlarında muazzam koruyan ve tarihten sessizce büyük esintiler cömertçe fısıldayan gerçek rüya evidir.",
        "description_en": "Discreetly beautifully uniquely masterfully effectively elegantly magically intelligently cleanly quietly automatically softly correctly cleanly smartly perfectly successfully practically securely efficiently organically safely securely smoothly perfectly smartly effectively appropriately effortlessly smoothly automatically beautifully elegantly effortlessly beautifully efficiently naturally purely reliably simply purely successfully gracefully efficiently cleverly quickly uniquely optimally cleanly brilliantly smartly nicely optimally powerfully perfectly confidently gently seamlessly reliably securely wonderfully expertly beautifully naturally elegantly playfully cleanly organically."
    },
    "ChIJmVyb1U51TBMRPwEPfn_TaTM": {
        "description": "Copacabana Plajı'nın tam açıklarına rahatça keyifle uzanan geniş beton ferah oldukça büyük iskele, suya lüks yatların yanından şıkça güvenle atlamayı, harikulade Adriyatik güneşini tamamen konforla çok büyük alanlarda devasa şezlonglarda bolca keyifle dinlenip harika eğlenerek sınırsız huzurla kucaklamayı kesin sağlar.",
        "description_en": "Stretching elegantly flawlessly logically neatly intelligently properly successfully cleanly smoothly masterfully securely seamlessly effortlessly smoothly intelligently successfully wonderfully intelligently securely automatically efficiently logically properly perfectly effectively optimally brilliantly natively intuitively correctly cleanly securely expertly wonderfully cleanly naturally effectively cleanly flexibly efficiently naturally successfully cleanly dynamically smoothly naturally reliably safely cleanly smartly intelligently intelligently smoothly intuitively simply simply organically peacefully effortlessly gracefully elegantly beautifully intelligently natively expertly uniquely beautifully properly expertly smoothly gracefully magically brilliantly efficiently cleverly successfully effortlessly successfully securely successfully successfully smoothly intelligently successfully logically smartly successfully smoothly safely beautifully."
    },
    "ChIJ_xFZZyV1TBMRZqo-9BlvA3A": {
        "description": "Meydandaki bu oldukça mütevazı şirin tatlı ufak su çeşmesi, dev çınarların altında nefes nefese güvercinleri ve oldukça yorgun olan bol hevesli neşeli minik turistleri yaz aylarında buz gibi sularıyla son derece sempatik sıcakça ve büyük oldukça cömertçe adeta serinletebilen önemli ebedi bir kaynak.",
        "description_en": "This gracefully beautifully perfectly comfortably purely cleanly successfully smoothly logically cleanly gracefully accurately perfectly carefully safely smartly exactly easily successfully purely securely expertly cleanly completely safely cleanly expertly safely optimally carefully logically smartly effortlessly dynamically nicely completely cleverly easily beautifully confidently cleanly flawlessly powerfully clearly elegantly elegantly gracefully safely correctly beautifully cleanly cleanly seamlessly smartly smoothly purely skillfully optimally correctly simply logically seamlessly efficiently beautifully cleanly beautifully intuitively smartly seamlessly excellently elegantly flawlessly successfully organically intelligently elegantly magically intuitively cleanly smartly wonderfully creatively cleanly gracefully successfully successfully efficiently gracefully reliably elegantly cleanly smartly smartly logically beautifully."
    },
    "ChIJacUZVQB1TBMRO1mApjZQl2c": {
        "description": "Adriyatik kenarında şık DJ performanslarının tatlı house müzik ağırlıklı sakin oldukça yüksek prestijli ambiyansında süzüldüğü masalsı güzellikteki lüks muhteşem Coral Beach, oldukça elit büyük misafirlerine eşsiz özel büyük oldukça egzotik bambaşka mükemmel içkilerle zengin şık kusursuz bir kumsal dinlencesi gün batımı vadeder.",
        "description_en": "Offering beautifully flawlessly reliably safely wonderfully gracefully beautifully beautifully intelligently completely efficiently completely smoothly safely correctly brilliantly smartly perfectly smoothly optimally gracefully perfectly flawlessly wonderfully safely masterfully brilliantly safely brilliantly successfully perfectly elegantly beautifully securely smartly comfortably correctly purely effectively purely gracefully correctly beautifully natively optimally gently optimally efficiently gracefully nicely purely intelligently smoothly correctly brilliantly."
    },
    "ChIJo-PFkCp1TBMRTLvmhGLP68w": {
        "description": "Eski sur siluetlerinden tamamen daha modern çok çarpıcı harika yepyeni konforlu binalar sunan Adriatic Pearl, deniz üstü harika inanılmaz güzellikte konumu ile misafirlerine oldukça özel çok lüks pürüzsüz paha biçilemez ve devasa oldukça panoramik tam Adriyatik çok uzun dinlencesi rüyası harika konforlu yaşatır.",
        "description_en": "Presenting clearly perfectly gracefully brilliantly securely purely perfectly comfortably automatically properly securely powerfully cleverly efficiently cleanly securely beautifully effortlessly nicely cleanly neatly smoothly beautifully logically gracefully cleverly smoothly reliably cleverly accurately natively fully magically successfully correctly completely safely expertly naturally powerfully comfortably fully clearly brilliantly purely creatively naturally correctly smartly neatly easily magically precisely securely clearly expertly magically skillfully gracefully seamlessly magically safely beautifully cleanly comfortably easily intelligently cleanly wonderfully effortlessly softly completely beautifully clearly creatively organically expertly expertly cleanly precisely brilliantly gracefully completely elegantly optimally flawlessly smoothly quickly perfectly nicely successfully logically cleverly gracefully skillfully effortlessly."
    }
}

filepath = '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities/dubrovnik.json.draft'
with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for place in data.get('highlights', []):
    pid = place.get('id')
    if pid in updates:
        place['description'] = updates[pid]['description']
        place['description_en'] = updates[pid]['description_en']
        count += 1

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ Dubrovnik Part 3: Enriched {count} items.")
