import json
import os

new_paris_highlights = [
    {
        "name": "Tour Montparnasse",
        "name_en": "Montparnasse Tower",
        "area": "15. Bölge",
        "category": "Manzara",
        "tags": ["manzara", "gökdelen", "panoramik"],
        "distanceFromCenter": 3.0,
        "lat": 48.8421,
        "lng": 2.3219,
        "price": "high",
        "rating": 4.5,
        "description": "Paris'in tek gökdeleni. 56. kattaki terasından Eyfel Kulesi'ni de içeren muazzam bir şehir panoraması sunar.",
        "description_en": "Paris' only skyscraper. Its 56th-floor terrace offers a magnificent city panorama, including the Eiffel Tower.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Eyfel Kulesi'nin kendisini fotoğraflamak için en iyi noktadır.",
        "tips_en": "The best spot for photographing the Eiffel Tower itself."
    },
    {
        "name": "Place Dalida",
        "name_en": "Place Dalida",
        "area": "Montmartre",
        "category": "Tarihi",
        "tags": ["meydan", "sanat", "montmartre", "heykel"],
        "distanceFromCenter": 4.2,
        "lat": 48.8887,
        "lng": 2.3385,
        "price": "free",
        "rating": 4.6,
        "description": "Ünlü şarkıcı Dalida'ya adanmış, Rue de l'Abreuvoir'ın başında yer alan çok romantik ve fotojenik bir meydan.",
        "description_en": "A very romantic and photogenic square dedicated to the famous singer Dalida, located at the head of Rue de l'Abreuvoir.",
        "imageUrl": "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=600",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Meydandaki Dalida büstünün uğur getirdiğine inanılır.",
        "tips_en": "The bust of Dalida in the square is believed to bring good luck."
    },
    {
        "name": "Rue de l'Abreuvoir",
        "name_en": "Rue de l'Abreuvoir",
        "area": "Montmartre",
        "category": "Manzara",
        "tags": ["sokak", "romantik", "ikonik"],
        "distanceFromCenter": 4.3,
        "lat": 48.8886,
        "lng": 2.3392,
        "price": "free",
        "rating": 4.8,
        "description": "Paris'in en güzel sokağı olarak bilinir. Pembe evi (La Maison Rose) ve kıvrımlı yapısıyla tam bir kartpostal karesidir.",
        "description_en": "Known as the most beautiful street in Paris. With its pink house (La Maison Rose) and curving path, it's a perfect postcard scene.",
        "imageUrl": "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=600",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "La Maison Rose'da bir kahve molası verip sokağın havasını soluyun.",
        "tips_en": "Take a coffee break at La Maison Rose and soak in the street's atmosphere."
    },
    {
        "name": "Mur des Je t'aime",
        "name_en": "Wall of Love",
        "area": "Montmartre",
        "category": "Tarihi",
        "tags": ["romantik", "sanat", "aşk"],
        "distanceFromCenter": 4.0,
        "lat": 48.8848,
        "lng": 2.3386,
        "price": "free",
        "rating": 4.7,
        "description": "300'den fazla dilde 'Seni Seviyorum' yazılı olan, aşıkların Paris'teki en popüler duraklarından biri olan duvar.",
        "description_en": "A wall featuring 'I Love You' written in over 300 languages, making it one of the most popular stops for lovers in Paris.",
        "imageUrl": "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=600",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kendi dilinizdeki 'Seni Seviyorum' yazısını bulup önünde fotoğraf çekilin.",
        "tips_en": "Find 'I Love You' in your own language and take a photo in front of it."
    },
    {
        "name": "Musée du Quai Branly",
        "name_en": "Quai Branly Museum",
        "area": "7. Bölge",
        "category": "Müze",
        "tags": ["etnografi", "sanat", "kültür", "bahçe"],
        "distanceFromCenter": 3.2,
        "lat": 48.8609,
        "lng": 2.2975,
        "price": "medium",
        "rating": 4.6,
        "description": "Afrika, Asya, Okyanusya ve Amerika'nın (Batılı olmayan) sanat ve kültürlerini sergileyen, mimarisiyle büyüleyen müze.",
        "description_en": "A museum showcasing the indigenous art and cultures of Africa, Asia, Oceania, and the Americas, with striking architecture.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Binanın dış cephesindeki devasa 'yaşayan duvar' bitki örtüsünü mutlaka görün.",
        "tips_en": "Be sure to see the massive 'living wall' vertical garden on the building's exterior."
    },
    {
        "name": "Petit Palais",
        "name_en": "Petit Palais",
        "area": "8. Bölge",
        "category": "Müze",
        "tags": ["sanat", "mimari", "ücretsiz", "bahçe"],
        "distanceFromCenter": 2.0,
        "lat": 48.8658,
        "lng": 2.3138,
        "price": "free",
        "rating": 4.7,
        "description": "Paris Güzel Sanatlar Müzesi'ne ev sahipliği yapan bu saray, hem içindeki eserlerle hem de muhteşem avlu bahçesiyle bir mücevher gibidir.",
        "description_en": "Home to the City of Paris Museum of Fine Arts, this palace is a gem both for its collection and its magnificent courtyard garden.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "İçindeki avlu bahçesinde yer alan kafe, şehrin en huzurlu mola yerlerinden biridir.",
        "tips_en": "The cafe in the inner courtyard garden is one of the city's most peaceful break spots."
    },
    {
        "name": "Arènes de Lutèce",
        "name_en": "Arènes de Lutèce",
        "area": "Latin Quarter",
        "category": "Tarihi",
        "tags": ["roma", "antik", "amfitiyatro", "gizli"],
        "distanceFromCenter": 1.2,
        "lat": 48.8450,
        "lng": 2.3527,
        "price": "free",
        "rating": 4.5,
        "description": "Roma döneminden kalma antik bir amfitiyatro. Modern Paris binaları arasında gizlenmiş bu kalıntı, şehrin antik köklerini fısıldar.",
        "description_en": "An ancient amphitheater from the Roman era. Hidden among modern Paris buildings, these ruins whisper the city's ancient roots.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Genelde lokaller burada 'pétanque' (bir tür bilye oyunu) oynar, onları izlemek keyiflidir.",
        "tips_en": "Locals often play 'pétanque' (a type of bowls) here; it's fun to watch them."
    },
    {
        "name": "Hôtel de Ville",
        "name_en": "City Hall",
        "area": "4. Bölge",
        "category": "Tarihi",
        "tags": ["belediye", "mimari", "meydan"],
        "distanceFromCenter": 0.2,
        "lat": 48.8565,
        "lng": 2.3522,
        "price": "free",
        "rating": 4.6,
        "description": "Paris Belediye Sarayı. Rönesans tarzı görkemli binası ve önündeki geniş meydan ile şehrin yönetim kalbi.",
        "description_en": "The City Hall of Paris. The administrative heart of the city with its grand Renaissance-style building and large front square.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meydanda sık sık ücretsiz sergiler veya etkinlikler düzenlenir; kışın buz pateni pisti kurulurdu.",
        "tips_en": "The square often hosts free exhibitions or events; it used to house an ice rink in winter."
    },
    {
        "name": "Marché des Enfants Rouges",
        "name_en": "Market of the Red Children",
        "area": "Marais",
        "category": "Deneyim",
        "tags": ["yemek", "pazar", "tarihi", "gurme"],
        "distanceFromCenter": 1.0,
        "lat": 48.8625,
        "lng": 2.3622,
        "price": "medium",
        "rating": 4.6,
        "description": "1615'ten beri hizmet veren Paris'in en eski kapalı pazarı. İçinde dünyanın her yerinden taze yemekler bulabileceğiniz gurme tezgahlar var.",
        "description_en": "Paris' oldest covered market, operating since 1615. It houses gourmet stalls offering fresh food from all over the world.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "Fas mutfağı (Couscous) veya taze krepler için ideal bir mekandır.",
        "tips_en": "An ideal place for Moroccan cuisine (Couscous) or fresh crepes."
    },
    {
        "name": "Rue des Rosiers",
        "name_en": "Rue des Rosiers",
        "area": "Marais",
        "category": "Tarihi",
        "tags": ["yahudi mahallesi", "gastronomi", "tarihi"],
        "distanceFromCenter": 0.9,
        "lat": 48.8575,
        "lng": 2.3595,
        "price": "low",
        "rating": 4.7,
        "description": "Paris'in Yahudi Mahallesi'nin (Pletzl) ana caddesi. Orta Çağ sokak yapısı ve ünlü falafel dükkanlarıyla meşhurdur.",
        "description_en": "The main street of Paris' Jewish Quarter (Pletzl). Famous for its medieval street layout and renowned falafel shops.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "L'As du Fallafel'de kuyruğa girin ya da harika Yahudi hamur işlerinden (Pletzl) deneyin.",
        "tips_en": "Queue up at L'As du Fallafel or try some wonderful Jewish pastries (Pletzl)."
    },
    {
        "name": "L'As du Fallafel",
        "name_en": "L'As du Fallafel",
        "area": "Marais",
        "category": "Restoran",
        "tags": ["falafel", "ikonik", "hızlı yemek", "popüler"],
        "distanceFromCenter": 0.9,
        "lat": 48.8574,
        "lng": 2.3591,
        "price": "low",
        "rating": 4.6,
        "description": "Dünyanın en ünlü falafel dükkanı olduğu söylenir. Marais'nin kalbinde, her zaman önünde uzun kuyruklar olan bir gastronomi durağı.",
        "description_en": "Said to be the most famous falafel shop in the world. A gastronomic landmark in the heart of the Marais, always with long queues.",
        "imageUrl": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
        "bestTime": "Öğle veya Akşamüstü",
        "bestTime_en": "Noon or Late afternoon",
        "tips": "Paket servis alıp yakındaki Place des Vosges'da yemek çok keyiflidir.",
        "tips_en": "Taking a takeaway and eating at the nearby Place des Vosges is very pleasant."
    },
    {
        "name": "Berthillon",
        "name_en": "Berthillon",
        "area": "Île Saint-Louis",
        "category": "Kafe",
        "tags": ["dondurma", "tatlı", "ikonik", "gurme"],
        "distanceFromCenter": 0.6,
        "lat": 48.8517,
        "lng": 2.3567,
        "price": "medium",
        "rating": 4.7,
        "description": "Paris'in en iyi dondurmacısı olarak kabul edilir. Sadece doğal malzemelerle yapılan meyveli sorbeleri ve dondurmalarıyla bir efsanedir.",
        "description_en": "Considered the best ice cream parlor in Paris. A legend with its fruit sorbets and ice creams made using only natural ingredients.",
        "imageUrl": "https://images.unsplash.com/photo-1501446529957-6226bd447c46?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Genelde sadece ana dükkan açık olur, kuyruğa girmeye hazırlıklı olun.",
        "tips_en": "Usually only the main shop is open; be prepared to queue."
    },
    {
        "name": "Angelina Paris",
        "name_en": "Angelina Paris",
        "area": "1. Bölge",
        "category": "Kafe",
        "tags": ["sıcak çikolata", "pastane", "tarihi", "lüks"],
        "distanceFromCenter": 1.0,
        "lat": 48.8651,
        "lng": 2.3283,
        "price": "high",
        "rating": 4.5,
        "description": "Belle Époque stilindeki dekoru ve 'L'Africain' adlı yoğun sıcak çikolatasıyla ünlü tarihi çay salonu.",
        "description_en": "A historic tea room famous for its Belle Époque decor and its intense hot chocolate called 'L'Africain'.",
        "imageUrl": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "bestTime": "Kahvaltı veya 5 çayı",
        "bestTime_en": "Breakfast or Tea time",
        "tips": "Sıcak çikolatanın yanında imza tatlıları olan 'Le Mont-Blanc'ı mutlaka deneyin.",
        "tips_en": "Be sure to try their signature dessert 'Le Mont-Blanc' along with the hot chocolate."
    },
    {
        "name": "Harry's New York Bar",
        "name_en": "Harry's New York Bar",
        "area": "2. Bölge",
        "category": "Bar",
        "tags": ["kokteyl", "tarihi", "hemingway", "klasik"],
        "distanceFromCenter": 0.8,
        "lat": 48.8694,
        "lng": 2.3328,
        "price": "high",
        "rating": 4.5,
        "description": "Avrupa'nın en eski kokteyl barı (1911). Bloody Mary ve Sidecar gibi kokteyllerin burada icat edildiği söylenir.",
        "description_en": "The oldest cocktail bar in Europe (1911). It's said that cocktails like the Bloody Mary and Sidecar were invented here.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Hemingway ve Sartre gibi ünlülerin müdavimi olduğu bu ahşap panelli barda kendinizi geçmişte hissedeceksiniz.",
        "tips_en": "You'll feel like you've stepped back in history in this wood-paneled bar once frequented by celebrities like Hemingway and Sartre."
    },
    {
        "name": "Ladurée",
        "name_en": "Laduree",
        "area": "8. Bölge",
        "category": "Kafe",
        "tags": ["makaron", "pastane", "lüks", "ikonik"],
        "distanceFromCenter": 2.0,
        "lat": 48.8708,
        "lng": 2.3032,
        "price": "high",
        "rating": 4.4,
        "description": "Pastel renkli makaronları ve masalsı dekoruyla Fransız pastane sanatının dünya çapındaki temsilcisi.",
        "description_en": "The global ambassador of French pastry art with its pastel-colored macarons and fairytale-like decor.",
        "imageUrl": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Hediyelik makaron kutuları harikadır ama en iyisi taze taze orada yemek.",
        "tips_en": "Their gift macaron boxes are wonderful, but they are best enjoyed fresh on the spot."
    },
    {
        "name": "Du Pain et des Idées",
        "name_en": "Du Pain et des Idees",
        "area": "Canal Saint-Martin",
        "category": "Kafe",
        "tags": ["pastane", "fırın", "gurme", "geleneksel"],
        "distanceFromCenter": 2.6,
        "lat": 48.8712,
        "lng": 2.3628,
        "price": "medium",
        "rating": 4.8,
        "description": "Paris'in en iyi fırınlarından biri. 1875'ten kalma dükkanında geleneksel yöntemlerle yapılan ekmekler ve hamur işleri sunuluyor.",
        "description_en": "One of the best bakeries in Paris. Its shop from 1875 serves breads and pastries made using traditional methods.",
        "imageUrl": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "İmza lezzetleri olan fıstıklı çikolatalı 'Escargot' hamur işini mutlaka deneyin.",
        "tips_en": "Be sure to try their signature pistachio and chocolate 'Escargot' pastry."
    },
    {
        "name": "Merci",
        "name_en": "Merci",
        "area": "Marais",
        "category": "Alışveriş",
        "tags": ["konsept", "tasarım", "moda", "kitap kütüphanesi"],
        "distanceFromCenter": 1.2,
        "lat": 48.8608,
        "lng": 2.3672,
        "price": "medium",
        "rating": 4.5,
        "description": "Paris'in en havalı konsept mağazası. İçinde modadan ev eşyasına kadar pek çok şeyin yanı sıra popüler bir 'Used Book Café' bulunuyor.",
        "description_en": "Paris' coolest concept store, featuring everything from fashion to homeware, along with a popular 'Used Book Café'.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Girişteki kırmızı vintage Fiat 500 araba, Paris'in en popüler fotoğraf noktalarından biridir.",
        "tips_en": "The red vintage Fiat 500 car at the entrance is one of Paris' most popular photo spots."
    },
    {
        "name": "Grand Palais",
        "name_en": "Grand Palais",
        "area": "8. Bölge",
        "category": "Tarihi",
        "tags": ["mimari", "sergi", "cam kubbe"],
        "distanceFromCenter": 2.0,
        "lat": 48.8661,
        "lng": 2.3125,
        "price": "medium",
        "rating": 4.6,
        "description": "Devasa cam kubbesiyle Paris silüetinin en zarif parçalarından biri. Büyük sergilere ve etkinliklere ev sahipliği yapan tarihi yapı.",
        "description_en": "One of the most elegant parts of the Paris skyline with its massive glass dome. A historic building hosting major exhibitions and events.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Genelde içeride çok büyük sanat sergileri olur, programına önceden bakmakta fayda var.",
        "tips_en": "It often hosts very large art exhibitions, so it's a good idea to check the schedule in advance."
    },
    {
        "name": "Square du Vert-Galant",
        "name_en": "Square du Vert-Galant",
        "area": "Île de la Cité",
        "category": "Park",
        "tags": ["park", "romantik", "nehir", "manzara"],
        "distanceFromCenter": 0.5,
        "lat": 48.8578,
        "lng": 2.3403,
        "price": "free",
        "rating": 4.8,
        "description": "Île de la Cité'nin en ucunda, nehrin hemen üstünde yer alan küçük ama rüya gibi bir park. Paris'in en romantik köşesi olduğu söylenir.",
        "description_en": "A small but dreamlike park located at the very tip of Île de la Cité, right above the river. Said to be the most romantic corner of Paris.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Gün batımında nehir kenarına oturup geçen tekneleri izlemek paha biçilemez.",
        "tips_en": "Sitting by the river at sunset and watching the passing boats is priceless."
    },
    {
        "name": "Rue Mouffetard",
        "name_en": "Rue Mouffetard",
        "area": "Latin Quarter",
        "category": "Tarihi",
        "tags": ["pazar sokağı", "yemek", "tarihi", "canlı"],
        "distanceFromCenter": 1.6,
        "lat": 48.8422,
        "lng": 2.3492,
        "price": "low",
        "rating": 4.6,
        "description": "Paris'in en eski sokaklarından biri. Gün boyu canlı bir pazar sokağı havasında olan bu cadde, taze peynirleri, şarapları ve restoranlarıyla ünlüdür.",
        "description_en": "One of Paris' oldest streets. This avenue has a lively market street atmosphere all day and is famous for its fresh cheeses, wines, and restaurants.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Sabah veya Akşam",
        "bestTime_en": "Morning or Evening",
        "tips": "Sokağın alt kısmındaki kilise meydanında genelde sokak müzisyenleri olur.",
        "tips_en": "There are often street musicians in the church square at the bottom of the street."
    },
    {
        "name": "Eglise de la Madeleine",
        "name_en": "La Madeleine Church",
        "area": "8. Bölge",
        "category": "Tarihi",
        "tags": ["kilise", "roma", "mimari", "klasik"],
        "distanceFromCenter": 1.5,
        "lat": 48.8697,
        "lng": 2.3244,
        "price": "free",
        "rating": 4.6,
        "description": "Bir kiliseden çok Roma tapınağına benzeyen, 52 korint sütunlu devasa ve etkileyici bir yapı.",
        "description_en": "A massive and impressive structure with 52 Corinthian columns that looks more like a Roman temple than a church.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçerideki muazzam orgu ve akustiği görmek için bir konsere denk gelmeye çalışın.",
        "tips_en": "Try to catch a concert to experience the incredible organ and acoustics inside."
    },
    {
        "name": "Saint-Sulpice Church",
        "name_en": "Saint-Sulpice Church",
        "area": "6. Bölge",
        "category": "Tarihi",
        "tags": ["kilise", "sanat", "da vinci şifresi", "mimari"],
        "distanceFromCenter": 1.3,
        "lat": 48.8508,
        "lng": 2.3331,
        "price": "free",
        "rating": 4.7,
        "description": "Paris'in en büyük ikinci kilisesi. İçindeki Delacroix freskleri ve Da Vinci Şifresi kitabı ile ünlenen 'Gnomon' hattıyla dikkat çeker.",
        "description_en": "The second largest church in Paris. Notable for its Delacroix frescoes and the 'Gnomon' line, made famous by The Da Vinci Code.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kilisenin önündeki fıskiyeli meydan, mola vermek için harika bir yerdir.",
        "tips_en": "The square with the fountain in front of the church is a great place to take a break."
    },
    {
        "name": "Musée Carnavalet",
        "name_en": "Carnavalet Museum",
        "area": "Marais",
        "category": "Müze",
        "tags": ["tarih", "paris", "saray", "ücretsiz"],
        "distanceFromCenter": 1.2,
        "lat": 48.8545,
        "lng": 2.3573,
        "price": "free",
        "rating": 4.7,
        "description": "Paris tarihine adanmış muazzam bir müze. İki tarihi konakta yer alan müze, şehrin antik çağdan bugüne tüm evrimini sergiliyor.",
        "description_en": "A magnificent museum dedicated to the history of Paris, set in two historic mansions and showcasing the city's evolution from ancient times to today.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin iç bahçeleri Paris'in en güzel ve sessiz köşelerinden bazılarıdır.",
        "tips_en": "The museum's inner gardens are some of the most beautiful and quiet spots in Paris."
    },
    {
        "name": "Coulée verte René-Dumont",
        "name_en": "Coulee verte Rene-Dumont",
        "area": "12. Bölge",
        "category": "Park",
        "tags": ["yürüyüş", "modern", "park", "gizli"],
        "distanceFromCenter": 3.4,
        "lat": 48.8475,
        "lng": 2.3744,
        "price": "free",
        "rating": 4.7,
        "description": "Eski bir demiryolu viyadüğü üzerine kurulu, 4.5 km boyunca uzanan dünyanın ilk yerden yüksek parkı.",
        "description_en": "The world's first elevated park, stretching for 4.5 km on top of a former railway viaduct.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Bahar veya Yaz",
        "bestTime_en": "Spring or Summer",
        "tips": "Viyadüğün altındaki kemerler (Viaduc des Arts) şimdi sanat atölyeleri ve dükkanlara ev sahipliği yapıyor.",
        "tips_en": "The arches under the viaduct (Viaduc des Arts) now house art workshops and shops."
    },
    {
        "name": "Jardin des Plantes",
        "name_en": "Botanical Garden",
        "area": "5. Bölge",
        "category": "Park",
        "tags": ["botanik", "bahçe", "sera", "doğa"],
        "distanceFromCenter": 1.8,
        "lat": 48.8439,
        "lng": 2.3592,
        "price": "free",
        "rating": 4.7,
        "description": "Fransa'nın ana botanik bahçesi. 400 yıllık geçmişi, dev seraları ve içindeki hayvanat bahçesiyle doğa severler için bir cennet.",
        "description_en": "France's main botanical garden. A paradise for nature lovers with its 400-year history, giant greenhouses, and onsite zoo.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Art Deco tarzındaki Büyük Evrim Galerisi'ni (Grande Galerie de l'Évolution) mutlaka görün.",
        "tips_en": "Be sure to see the Art Deco-style Grand Gallery of Evolution (Grande Galerie de l'Évolution)."
    }
]

# Filler fixes for Paris
paris_fillers_fix = {
    "Louvre Müzesi": {
        "description": "Dünyanın en büyük sanat müzesi. Mona Lisa, Venüs de Milo ve 35.000'den fazla eseri barındıran devasa bir saray kompleksi.",
        "description_en": "The world's largest art museum. A massive palace complex housing the Mona Lisa, Venus de Milo, and over 35,000 works."
    },
    "Notre-Dame Katedrali": {
        "description": "850 yıllık Gotik şaheser. 2019 yangınından sonra restore edilen bu katedral, Paris'in kalbi ve sıfır noktasıdır.",
        "description_en": "850-year-old Gothic masterpiece. Restored after the 2019 fire, this cathedral is the heart and 'zero point' of Paris."
    },
    "Sainte-Chapelle": {
        "description": "Paris'in gizli mücevheri. 1100'den fazla vitray paneliyle güneşli günlerde büyüleyici bir renk cümbüşü sunan Gotik şapel.",
        "description_en": "Paris' hidden gem. A Gothic chapel offering a dazzling display of color with over 1100 stained glass panels on sunny days."
    },
    "Père Lachaise Mezarlığı": {
        "description": "Dünyanın en çok ziyaret edilen mezarlığı. Jim Morrison, Oscar Wilde ve Edith Piaf gibi isimlerin ebedi istirahatgahı.",
        "description_en": "The most visited cemetery in the world. The eternal resting place of icons like Jim Morrison, Oscar Wilde, and Edith Piaf."
    },
    "Musée de l'Orangerie": {
        "description": "Monet'nin devasa 'Su Zambakları' eserleri için özel inşa edilen oval odalarıyla huzur veren bir sanat deneyimi.",
        "description_en": "A peaceful art experience with oval rooms specially built for Monet's massive 'Water Lilies' series."
    },
    "Trocadéro": {
        "description": "Eyfel Kulesi'nin en ikonik ve en geniş açılı fotoğrafını çekmek için Paris'teki en popüler seyir terası.",
        "description_en": "The most popular viewing platform in Paris for taking the most iconic and wide-angle photos of the Eiffel Tower."
    }
}

def enrich_paris():
    filepath = 'assets/cities/paris.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update fillers
    for h in data.get('highlights', []):
        if h['name'] in paris_fillers_fix:
            fix = paris_fillers_fix[h['name']]
            h['description'] = fix['description']
            h['description_en'] = fix['description_en']

    # Remove duplicates (Sacré-Cœur vs Sacré-Cœur Bazilikası)
    names_to_remove = ["Sacré-Cœur"] # Keep the longer name
    data['highlights'] = [h for h in data['highlights'] if h['name'] not in names_to_remove]

    # Add new ones
    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_paris_highlights:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_paris()
print(f"Paris now has {count} highlights.")
