import json
import os

new_highlights_batch2 = [
    {
        "name": "Bar El Comercio",
        "name_en": "Bar El Comercio",
        "area": "Centro",
        "category": "Kafe",
        "tags": ["churros", "kahvaltı", "tarihi"],
        "distanceFromCenter": 0.3,
        "lat": 37.3912,
        "lng": -5.9945,
        "price": "low",
        "rating": 4.6,
        "description": "Sevilla'nın en meşhur churros ve sıcak çikolatasını sunan tarihi mekan. 1904'ten beri değişmeyen lezzetiyle bir sabah klasiği.",
        "description_en": "A historic venue serving Seville's most famous churros and hot chocolate. A breakfast classic with unchanged quality since 1904.",
        "imageUrl": "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Churrosların yanına mutlaka yoğun sıcak çikolata söyleyin. Genelde kalabalıktır, ayakta yemek normaldir.",
        "tips_en": "Be sure to order the thick hot chocolate with your churros. It's often crowded; standing and eating is normal here."
    },
    {
        "name": "Plaza de América",
        "name_en": "Plaza de America",
        "area": "María Luisa",
        "category": "Tarihi",
        "tags": ["meydan", "mimari", "güvercin"],
        "distanceFromCenter": 1.5,
        "lat": 37.3715,
        "lng": -5.9865,
        "price": "free",
        "rating": 4.7,
        "description": "Maria Luisa Parkı'nın güneyinde yer alan muhteşem meydan. 'Güvercin Meydanı' olarak da bilinir ve çevresinde üç önemli müze binası bulunur.",
        "description_en": "A stunning square at the south of Maria Luisa Park. Also known as 'Pigeon Square,' it's surrounded by three important museum buildings.",
        "imageUrl": "https://images.unsplash.com/photo-1598449419142-2d1033069315?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Lunch",
        "tips": "Meydandaki beyaz güvercinleri beslemek çocuklar için çok popülerdir.",
        "tips_en": "Feeding the white pigeons in the square is very popular for kids."
    },
    {
        "name": "Hotel Alfonso XIII",
        "name_en": "Hotel Alfonso XIII",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["saray", "lüks", "mimari"],
        "distanceFromCenter": 0.4,
        "lat": 37.3828,
        "lng": -5.9925,
        "price": "high",
        "rating": 4.8,
        "description": "Avrupa'nın en prestijli otellerinden biri. 1929 sergisi için inşa edilen bina, Neo-Mudéjar tarzıyla gerçek bir mimari şaheserdir.",
        "description_en": "One of Europe's most prestigious hotels. Built for the 1929 exhibition, the building is a true architectural masterpiece in Neo-Mudéjar style.",
        "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Otelde konaklamasanız bile avlusunda bir kahve içebilir veya barında şık bir akşam geçirebilirsiniz.",
        "tips_en": "Even if you're not staying there, you can have a coffee in the courtyard or enjoy an elegant evening at the bar."
    },
    {
        "name": "Hospital de la Caridad",
        "name_en": "Charity Hospital",
        "area": "Arenal",
        "category": "Tarihi",
        "tags": ["barok", "sanat", "kilise"],
        "distanceFromCenter": 0.5,
        "lat": 37.3825,
        "lng": -5.9961,
        "price": "low",
        "rating": 4.7,
        "description": "Sevilla Barok sanatının zirve noktalarından biri. Kilisesi, Valdés Leal ve Murillo gibi ustalara ait muhteşem tablolarla doludur.",
        "description_en": "A peak of Seville Baroque art. The church is filled with magnificent paintings by masters like Valdés Leal and Murillo.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Sesli rehber alarak Miguel Mañara'nın hikayesini dinleyin, tabloların derin anlamlarını keşfedin.",
        "tips_en": "Take an audio guide to hear the story of Miguel Mañara and discover the deep meaning of the paintings."
    },
    {
        "name": "Casa de la Memoria",
        "name_en": "Casa de la Memoria",
        "area": "Centro",
        "category": "Deneyim",
        "tags": ["flamenko", "kültür", "gösteri"],
        "distanceFromCenter": 0.4,
        "lat": 37.3912,
        "lng": -5.9938,
        "price": "medium",
        "rating": 4.8,
        "description": "Sevilla'nın en otantik flamenko merkezlerinden biri. Mikrofon ve hoparlör kullanılmayan performanslar, sanatın saf halini sunuyor.",
        "description_en": "One of Seville's most authentic flamenco centers. Performances without microphones or speakers offer the art in its purest form.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Oldukça popüler bir yer, biletlerinizi mutlaka birkaç gün önceden online alın.",
        "tips_en": "It's quite popular, so be sure to buy your tickets online a few days in advance."
    },
    {
        "name": "Callejón del Agua",
        "name_en": "Water Alley",
        "area": "Santa Cruz",
        "category": "Manzara",
        "tags": ["sokak", "romantik", "duvar"],
        "distanceFromCenter": 0.2,
        "lat": 37.3852,
        "lng": -5.9868,
        "price": "free",
        "rating": 4.7,
        "description": "Eski şehir duvarlarının hemen yanında uzanan, sarmaşıklar ve çiçeklerle süslü çok romantik bir dar sokak.",
        "description_en": "A very romantic narrow street decorated with vines and flowers, running right alongside the ancient city walls.",
        "imageUrl": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Washington Irving'in 'Elhamra Masalları'nı yazdığı eve giden yolun üzerindedir.",
        "tips_en": "It's on the way to the house where Washington Irving wrote 'Tales of the Alhambra'."
    },
    {
        "name": "La Carbonería",
        "name_en": "La Carboneria",
        "area": "Santa Cruz",
        "category": "Bar",
        "tags": ["flamenko", "lokal", "şarap"],
        "distanceFromCenter": 0.5,
        "lat": 37.3872,
        "lng": -5.9878,
        "price": "low",
        "rating": 4.1,
        "description": "Eski bir kömür deposundan dönüştürülmüş, salaş ve otantik bir bar. Ücretsiz canlı flamenko performansları ve neşeli atmosferiyle ünlü.",
        "description_en": "A shabby and authentic bar converted from an old coal warehouse, famous for its free live flamenco performances and lively atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Giriş ücretsizdir, bir sürahi 'Agua de Sevilla' (bir kokteyl) söyleyip ortamın tadını çıkarın.",
        "tips_en": "Entrance is free; order a pitcher of 'Agua de Sevilla' (a cocktail) and enjoy the vibe."
    },
    {
        "name": "Mercadillo de los Jueves",
        "name_en": "Thursday Flea Market",
        "area": "Alameda",
        "category": "Deneyim",
        "tags": ["pazar", "antika", "nostalji"],
        "distanceFromCenter": 1.0,
        "lat": 37.3992,
        "lng": -5.9932,
        "price": "free",
        "rating": 4.5,
        "description": "Sevilla'nın en eski bit pazarı. Her Perşembe Calle Feria üzerinde kurulur; antikalar, kitaplar ve garip objeler bulabilirsiniz.",
        "description_en": "Seville's oldest flea market, held every Thursday on Calle Feria; you can find antiques, books, and quirky objects.",
        "imageUrl": "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800",
        "bestTime": "Perşembe Sabahı",
        "bestTime_en": "Thursday Morning",
        "tips": "Pazarlık yapmak serbest! En iyi parçaları bulmak için erken saatlerde (09:00 civarı) orada olun.",
        "tips_en": "Bargaining is allowed! Be there early (around 9 AM) to find the best pieces."
    },
    {
        "name": "Puente del Alamillo",
        "name_en": "Alamillo Bridge",
        "area": "Cartuja",
        "category": "Manzara",
        "tags": ["köprü", "mimari", "modern"],
        "distanceFromCenter": 2.2,
        "lat": 37.414,
        "lng": -6.004,
        "price": "free",
        "rating": 4.4,
        "description": "Ünlü mimar Santiago Calatrava tarafından Expo '92 için tasarlanan ikonik tek kollu köprü. Modern Sevilla'nın sembollerinden.",
        "description_en": "The iconic single-pylon bridge designed by renowned architect Santiago Calatrava for Expo '92, a symbol of modern Seville.",
        "imageUrl": "https://images.unsplash.com/photo-1550522433-281b37494cc1?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Özellikle gün batımından sonra ışıklandırmasıyla harika fotoğraf kareleri sunuyor.",
        "tips_en": "It offers great photo ops especially with its lighting after sunset."
    },
    {
        "name": "Bolas Helados Arte-Sanos",
        "name_en": "Bolas Ice Cream",
        "area": "Centro",
        "category": "Deneyim",
        "tags": ["dondurma", "tatlı", "lezzet"],
        "distanceFromCenter": 0.4,
        "lat": 37.3892,
        "lng": -5.9925,
        "price": "low",
        "rating": 4.8,
        "description": "Tamamen doğal malzemelerle yapılan dondurmalarıyla ünlü. Sevilla'nın en iyi dondurmacısı olarak kabul edilir.",
        "description_en": "Famous for its ice cream made with entirely natural ingredients, widely considered the best gelato in Seville.",
        "imageUrl": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Portakallı ve baharatlı özel dondurmalarını denemeden dönmeyin.",
        "tips_en": "Don't leave without trying their special orange and spiced flavors."
    },
    {
        "name": "Abantal",
        "name_en": "Abantal",
        "area": "Nervión",
        "category": "Restoran",
        "tags": ["michelin", "gastronomi", "yaratıcı"],
        "distanceFromCenter": 1.5,
        "lat": 37.3855,
        "lng": -5.9812,
        "price": "high",
        "rating": 4.9,
        "description": "Sevilla'nın ilk Michelin yıldızlı restoranı. Şef Julio Fernández Quintero, Endülüs lezzetlerini son teknoloji tekniklerle sunuyor.",
        "description_en": "Seville's first Michelin-starred restaurant. Chef Julio Fernández Quintero serves Andalusian flavors using cutting-edge techniques.",
        "imageUrl": "https://images.unsplash.com/photo-1550966841-39ec4ec061c3?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Haftalar öncesinden rezervasyon şart. Şerbet gibi geleneksel içecekleri modern formda deneyebilirsiniz.",
        "tips_en": "Reservation weeks in advance is essential. You can try traditional drinks served in modern forms."
    },
    {
        "name": "Al Aljibe",
        "name_en": "Al Aljibe",
        "area": "Alameda",
        "category": "Restoran",
        "tags": ["tapas", "teras", "romantik"],
        "distanceFromCenter": 0.9,
        "lat": 37.3995,
        "lng": -5.9935,
        "price": "medium",
        "rating": 4.5,
        "description": "Alameda de Hércules meydanında, özellikle çatı terasıyla büyüleyen şık ve romantik bir tapas restoranı.",
        "description_en": "A chic and romantic tapas restaurant on Alameda de Hércules square, particularly enchanting for its rooftop terrace.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Yaz akşamlarında teras için mutlaka önceden rezervasyon yaptırın.",
        "tips_en": "Be sure to book in advance for the terrace on summer evenings."
    },
    {
        "name": "Ofelia Specialty Coffee",
        "name_en": "Ofelia Specialty Coffee",
        "area": "Centro",
        "category": "Kafe",
        "tags": ["kahve", "modern", "brunch"],
        "distanceFromCenter": 0.7,
        "lat": 37.3925,
        "lng": -5.9962,
        "price": "low",
        "rating": 4.7,
        "description": "Şık dekorasyonu ve özenle hazırlanan nitelikli kahveleriyle son yılların popüler duraklarından.",
        "description_en": "One of the popular stops in recent years with its stylish decor and carefully prepared specialty coffees.",
        "imageUrl": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kahvaltılık kaseleri ve sağlıklı seçenekleri oldukça doyurucu.",
        "tips_en": "Their breakfast bowls and healthy options are quite filling."
    },
    {
        "name": "Costurero de la Reina",
        "name_en": "Queen's Sewing Box",
        "area": "María Luisa",
        "category": "Tarihi",
        "tags": ["mimari", "neo-mudejar", "kale"],
        "distanceFromCenter": 1.2,
        "lat": 37.3775,
        "lng": -5.9895,
        "price": "free",
        "rating": 4.3,
        "description": "Küçük bir şatoyu andıran bu Neo-Mudéjar bina, aslında Maria Luisa Parkı'nın gardiyan evi olarak inşa edilmişti. İsmi bir efsaneden geliyor.",
        "description_en": "Resembling a small castle, this Neo-Mudéjar building was actually built as a guardhouse for Maria Luisa Park. Its name comes from a legend.",
        "imageUrl": "https://images.unsplash.com/photo-1598449419142-2d1033069315?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Şu an turizm ofisi olarak kullanılıyor; içeriden haritalar alıp dış mimarinin fotoğraflarını çekebilirsiniz.",
        "tips_en": "It's currently used as a tourism office; you can grab maps inside and snap photos of the exterior architecture."
    },
    {
        "name": "Muelle de Nueva York",
        "name_en": "New York Quay",
        "area": "Arenal",
        "category": "Manzara",
        "tags": ["nehir", "teras", "gece hayatı"],
        "distanceFromCenter": 0.7,
        "lat": 37.3812,
        "lng": -5.9945,
        "price": "low",
        "rating": 4.4,
        "description": "Guadalquivir Nehri kenarında modern ve şık bir yürüyüş yolu. Akşamları açık hava barlarıyla canlanan çok keyifli bir alan.",
        "description_en": "A modern and chic promenade along the Guadalquivir River, a very pleasant area that comes alive with open-air bars in the evening.",
        "imageUrl": "https://images.unsplash.com/photo-1550522433-281b37494cc1?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Güneş batarken bir kokteyl alıp nehir manzarasının tadını çıkarmak için en iyi yer.",
        "tips_en": "The best place to grab a cocktail and enjoy the river view as the sun sets."
    },
    {
        "name": "Teatro de la Maestranza",
        "name_en": "Maestranza Theater",
        "area": "Arenal",
        "category": "Deneyim",
        "tags": ["opera", "tiyatro", "kültür"],
        "distanceFromCenter": 0.5,
        "lat": 37.385,
        "lng": -5.998,
        "price": "high",
        "rating": 4.7,
        "description": "Sevilla'nın ana opera ve tiyatro binası. Dünya çapında prodüksiyonlara ev sahipliği yapar.",
        "description_en": "Seville’s main opera and theater house, hosting world-class productions.",
        "imageUrl": "https://images.unsplash.com/photo-1516307362358-3382404edb1d?w=800",
        "bestTime": "Etkinlik saatleri",
        "bestTime_en": "During events",
        "tips": "Önceden programı kontrol edip flamenko balesi veya opera bileti alın.",
        "tips_en": "Check the schedule in advance and buy tickets for flamenco ballet or opera."
    },
    {
        "name": "Calle Tetuán",
        "name_en": "Tetuan Street",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["mağazalar", "moda", "merkezi"],
        "distanceFromCenter": 0.2,
        "lat": 37.391,
        "lng": -5.995,
        "price": "low",
        "rating": 4.5,
        "description": "Calle Sierpes'e paralel uzanan diğer ana alışveriş caddesi. Daha çok global markaların bulunduğu hareketli bir yer.",
        "description_en": "The other main shopping street running parallel to Calle Sierpes, a lively spot mostly featuring global brands.",
        "imageUrl": "https://images.unsplash.com/photo-1441986127433-605888c0099d?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Sokak müzisyenlerini ve canlı atmosferi burada en iyi hissedebilirsiniz.",
        "tips_en": "You can best experience the street musicians and lively atmosphere here."
    },
    {
        "name": "Acuario de Sevilla",
        "name_en": "Seville Aquarium",
        "area": "Nehir",
        "category": "Deneyim",
        "tags": ["akvaryum", "aile", "balık"],
        "distanceFromCenter": 1.8,
        "lat": 37.375,
        "lng": -5.99,
        "price": "medium",
        "rating": 4.2,
        "description": "Magellan'ın dünya turunu takip eden bir rota sunan, aileler için harika bir durak.",
        "description_en": "A fantastic stop for families, following a route that mimics Magellan's world tour.",
        "imageUrl": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Köpekbalığı tankının altından geçmek çok etkileyici.",
        "tips_en": "Passing under the shark tank is very impressive."
    },
    {
        "name": "Convento de Santa María de Jesús",
        "name_en": "Santa Maria de Jesus Convent",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["manastır", "tatlı", "gizli"],
        "distanceFromCenter": 0.3,
        "lat": 37.387,
        "lng": -5.991,
        "price": "low",
        "rating": 4.6,
        "description": "Calle Águilas'ta bulunan, rahibelerin geleneksel tatlılar sattığı başka bir huzurlu manastır.",
        "description_en": "Another peaceful convent on Calle Águilas where the nuns sell traditional sweets.",
        "imageUrl": "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Dönen pencere (torno) üzerinden alışveriş yapma deneyimini burada da yaşayabilirsiniz.",
        "tips_en": "You can experience buying sweets through the rotating window (torno) here as well."
    },
    {
        "name": "Plaza de Doña Elvira",
        "name_en": "Plaza de Dona Elvira",
        "area": "Santa Cruz",
        "category": "Manzara",
        "tags": ["meydan", "portakal ağacı", "romantik"],
        "distanceFromCenter": 0.2,
        "lat": 37.385,
        "lng": -5.991,
        "price": "free",
        "rating": 4.7,
        "description": "Santa Cruz'un en güzel meydanı. Portakal ağaçları, seramikli banklar ve fıskiye ile tam bir Endülüs kartpostalı.",
        "description_en": "The most beautiful square in Santa Cruz. With orange trees, tiled benches, and a fountain, it's a perfect Andalusian postcard.",
        "imageUrl": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800",
        "bestTime": "Her zaman",
        "bestTime_en": "Anytime",
        "tips": "Akşamları sokak gitaristlerini dinlemek için en romantik mekanlardan biri.",
        "tips_en": "One of the most romantic spots to listen to street guitarists in the evening."
    },
    {
        "name": "CaixaForum Sevilla",
        "name_en": "CaixaForum Seville",
        "area": "Cartuja",
        "category": "Müze",
        "tags": ["modern sanat", "mimari", "kültür"],
        "distanceFromCenter": 1.6,
        "lat": 37.3912,
        "lng": -6.01,
        "price": "low",
        "rating": 4.6,
        "description": "Sevilla'nın en yeni kültürel simgelerinden biri. Modern mimarisi ve yüksek kaliteli sergileriyle dikkat çekiyor.",
        "description_en": "One of Seville’s newest cultural landmarks, notable for its modern architecture and high-quality exhibitions.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Binanın ilginç mimarisini inceleyin ve ardından nehir boyunca yürüyüşe çıkın.",
        "tips_en": "Check out the building's interesting architecture and then take a walk along the river."
    }
]

def enrich_city_batch2(city_file):
    filepath = os.path.join('assets/cities', city_file)
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_highlights_batch2:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

new_count = enrich_city_batch2('sevilla.json')
print(f"Sevilla now has {new_count} highlights.")
