import json
import os

new_amsterdam_batch3 = [
    {
        "name": "Museum Van Loon",
        "name_en": "Museum Van Loon",
        "area": "Canal Ring",
        "category": "Müze",
        "tags": ["saray", "yaşam", "tarihi ev", "bahçe"],
        "distanceFromCenter": 0.8,
        "lat": 52.3644,
        "lng": 4.8911,
        "price": "medium",
        "rating": 4.6,
        "description": "Van Loon ailesinin muhteşem evi. 17. yüzyıldan kalma bu konak, orijinal mobilyaları ve Keizersgracht üzerindeki en güzel bahçelerden biriyle hayran bırakır.",
        "description_en": "The magnificent home of the Van Loon family. This 17th-century mansion impresses with its original furnishings and one of the most beautiful gardens on the Keizersgracht.",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Evin arkasındaki 'Coach House' bölümünü ve bahçesini mutlaka görün.",
        "tips_en": "Be sure to see the 'Coach House' and the garden at the back of the house."
    },
    {
        "name": "Kattenkabinet (Kedi Kabinesi)",
        "name_en": "Kattenkabinet",
        "area": "Canal Ring",
        "category": "Müze",
        "tags": ["kedi", "sanat", "tematik", "eğlenceli"],
        "distanceFromCenter": 0.5,
        "lat": 52.3667,
        "lng": 4.8875,
        "price": "medium",
        "rating": 4.4,
        "description": "Tamamen kedilere adanmış bir sanat müzesi! Picasso'dan Rembrandt'a kadar pek çok sanatçının kedi temalı eserlerini tarihi bir kanal evinde görebilirsiniz.",
        "description_en": "An art museum entirely dedicated to cats! You can see cat-themed works by artists ranging from Picasso to Rembrandt in a historic canal house.",
        "imageUrl": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzede yaşayan gerçek kedilerle de karşılaşabilirsiniz.",
        "tips_en": "You may also encounter actual cats living in the museum."
    },
    {
        "name": "FOAM Photography Museum",
        "name_en": "FOAM",
        "area": "Canal Ring",
        "category": "Müze",
        "tags": ["fotoğraf", "modern", "galeri", "sergi"],
        "distanceFromCenter": 0.7,
        "lat": 52.3639,
        "lng": 4.8928,
        "price": "medium",
        "rating": 4.5,
        "description": "Dünyaca ünlü fotoğraf müzesi. Hem köklü hem de yükselen fotoğrafçıların eserlerine ev sahipliği yapan Amsterdam'ın en prestijli galerilerinden biridir.",
        "description_en": "A world-famous photography museum. One of Amsterdam's most prestigious galleries, hosting works by both established and emerging photographers.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müze küçük ama sergiler her zaman çok kaliteli ve düşündürücüdür.",
        "tips_en": "The museum is small, but the exhibitions are always high quality and thought-provoking."
    },
    {
        "name": "Zevenlandenhuizen (Yedi Ülke Evleri)",
        "name_en": "Seven Countries Houses",
        "area": "Oud-Zuid",
        "category": "Tarihi",
        "tags": ["mimari", "evler", "avrupa", "fotojenik"],
        "distanceFromCenter": 2.0,
        "lat": 52.3592,
        "lng": 4.8789,
        "price": "free",
        "rating": 4.3,
        "description": "Roemer Visscherstraat üzerindeki yedi ev. Her biri farklı bir Avrupa ülkesinin (İtalya, Fransa, İspanya gibi) mimari tarzını temsil eder.",
        "description_en": "Seven houses on Roemer Visscherstraat, each representing the architectural style of a different European country (such as Italy, France, Spain).",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Vondelpark girişine çok yakındır, parka girmeden önce bu ilginç mimari diziyi fotoğraflayın.",
        "tips_en": "Very close to the Vondelpark entrance; photograph this interesting architectural row before entering the park."
    },
    {
        "name": "FEBO Amsterdam (Otomatik Atıştırmalık)",
        "name_en": "FEBO",
        "area": "Tüm Şehir",
        "category": "Deneyim",
        "tags": ["sokak yemeği", "otomatik", "kroket", "yerel"],
        "distanceFromCenter": 0.5,
        "lat": 52.3731,
        "lng": 4.8923,
        "price": "low",
        "rating": 4.0,
        "description": "Duvarlardaki küçük kapaklı bölmelerden bozuk para karşılığı sıcak atıştırmalıklar alabildiğiniz, Amsterdam'ın ikonik otomatik yemek zinciri.",
        "description_en": "Amsterdam's iconic automated food chain, where you can buy hot snacks from small compartments in the wall with a few coins.",
        "imageUrl": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
        "bestTime": "Gece atıştırmalığı",
        "bestTime_en": "Late night snack",
        "tips": "Kalfskroket (dana etli kroket) FEBO'nun klasiğidir, taze çıktığı anı yakalayın.",
        "tips_en": "The kalfskroket (veal croquette) is a FEBO classic; try to get one when it's fresh."
    },
    {
        "name": "Van Stapele Koekmakerij",
        "name_en": "Van Stapele",
        "area": "Centrum",
        "category": "Deneyim",
        "tags": ["kurabiye", "ünlü", "lezzetli", "gurme"],
        "distanceFromCenter": 0.4,
        "lat": 52.3689,
        "lng": 4.8906,
        "price": "low",
        "rating": 4.9,
        "description": "Dünyanın en iyi kurabiyesini yaptığını iddia eden küçük dükkan. Sadece beyaz çikolata dolgulu bitter kurabiyeler yaparlar ve her zaman kapısında sıra olur.",
        "description_en": "A small shop claiming to make the world's best cookie. They only make dark chocolate cookies with a white chocolate filling, and there's always a queue at the door.",
        "imageUrl": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800",
        "bestTime": "Sabah (sıra uzamadan)",
        "bestTime_en": "Morning (before lines get long)",
        "tips": "Kurabiyeler fırından sıcak çıkar çıkmaz tükenir, kutuyla almak mantıklıdır.",
        "tips_en": "The cookies sell out as soon as they come out of the oven hot; it's wise to buy them by the box."
    },
    {
        "name": "Vleminckx de Sausmeester",
        "name_en": "Vleminckx",
        "area": "Centrum",
        "category": "Deneyim",
        "tags": ["patates", "sos", "sokak yemeği", "ünlü"],
        "distanceFromCenter": 0.5,
        "lat": 52.3683,
        "lng": 4.8894,
        "price": "low",
        "rating": 4.7,
        "description": "1957'den beri hizmet veren, Amsterdam'ın en iyi 'vlaamse frites' (Flemenk patatesi) ustası. 25'ten fazla sos seçeneğiyle ünlüdür.",
        "description_en": "Serving since 1957, Amsterdam's finest 'vlaamse frites' (Flemish fries) master. Famous for its selection of more than 25 sauces.",
        "imageUrl": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "Trüflü mayonez veya geleneksel yer fıstığı soslu patatesleri mutlaka deneyin.",
        "tips_en": "Be sure to try the fries with truffle mayo or the traditional satay peanut sauce."
    },
    {
        "name": "The Pancake Bakery",
        "name_en": "The Pancake Bakery",
        "area": "Jordaan",
        "category": "Restoran",
        "tags": ["pancake", "pannenkoeken", "tarihi", "lezzetli"],
        "distanceFromCenter": 1.0,
        "lat": 52.3789,
        "lng": 4.8837,
        "price": "medium",
        "rating": 4.5,
        "description": "17. yüzyıldan kalma eski bir depoda devasa Hollanda pankekleri (pannenkoeken) yapan ikonik restoran.",
        "description_en": "An iconic restaurant making massive Dutch pancakes (pannenkoeken) in a former 17th-century warehouse.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Kahvaltı veya öğle",
        "bestTime_en": "Breakfast or lunch",
        "tips": "Dam'dan Prinsengracht boyunca yürüyerek ulaşabilirsiniz; elmalı ve tarçınlı klasiklerini deneyin.",
        "tips_en": "Reachable via a walk along Prinsengracht from Dam Square; try their classic apple and cinnamon variety."
    },
    {
        "name": "Blue Amsterdam",
        "name_en": "Blue Amsterdam",
        "area": "Centrum",
        "category": "Kafe",
        "tags": ["manzara", "360 derece", "kafe", "yüksek"],
        "distanceFromCenter": 0.5,
        "lat": 52.3681,
        "lng": 4.8911,
        "price": "medium",
        "rating": 4.4,
        "description": "Kalverpassage alışveriş merkezinin tepesinde yer alan 360 derece Amsterdam manzaralı modern kafe. Şehri kuş bakışı izlemek için en iyi gizli noktalardan biridir.",
        "description_en": "A modern cafe with a 360-degree view of Amsterdam located atop the Kalverpassage shopping center. One of the best hidden spots for a bird's-eye view of the city.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Cam kenarında bir masa kapıp Bloemenmarkt ve kanalları yukarıdan izleyin.",
        "tips_en": "Grab a window table to look down at the Bloemenmarkt and the canals."
    },
    {
        "name": "Zaanse Schans",
        "name_en": "Zaanse Schans",
        "area": "Çevresi (Günübirlik)",
        "category": "Tarihi",
        "tags": ["yel değirmeni", "peynir", "köy", "kültür"],
        "distanceFromCenter": 15.0,
        "lat": 52.4731,
        "lng": 4.8217,
        "price": "free",
        "rating": 4.8,
        "description": "Amsterdam'ın hemen dışındaki yaşayan açık hava müzesi. Tarihi yel değirmenleri, peynir tadımları ve geleneksel Hollanda evleriyle masalsı bir köydür.",
        "description_en": "A living open-air museum just outside Amsterdam. A fairytale village with historic windmills, cheese tastings, and traditional Dutch houses.",
        "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "Trenle sadece 15 dakikada ulaşılabilir; tahta ayakkabı (clog) atölyesini mutlaka görün.",
        "tips_en": "Accessible in just 15 minutes by train; be sure to visit the clog-making workshop."
    },
    {
        "name": "SkyLounge Amsterdam",
        "name_en": "SkyLounge",
        "area": "Centrum",
        "category": "Bar",
        "tags": ["manzara", "kokteyl", "lüks", "rooftop"],
        "distanceFromCenter": 1.2,
        "lat": 52.3781,
        "lng": 4.9042,
        "price": "high",
        "rating": 4.5,
        "description": "DoubleTree by Hilton Oteli'nin tepesinde yer alan ünlü rooftop bar. Tüm Amsterdam'a ve limana bakan nefes kesici bir manzarası vardır.",
        "description_en": "The famous rooftop bar atop the DoubleTree by Hilton Hotel. Offers breathtaking views of all Amsterdam and the harbor.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Üst segment bir yerdir, gün batımı saatinde yer bulmak zordur ancak manzara her şeye değer.",
        "tips_en": "A high-end spot; it can be difficult to find a seat at sunset, but the view is worth it."
    },
    {
        "name": "Moeders",
        "name_en": "Moeders",
        "area": "Jordaan",
        "category": "Restoran",
        "tags": ["hollanda mutfağı", "ev yemeği", "otantik", "anne"],
        "distanceFromCenter": 1.5,
        "lat": 52.3697,
        "lng": 4.8767,
        "price": "medium",
        "rating": 4.6,
        "description": "Geleneksel Hollanda yemekleri sunan, her yerin yüzlerce anne fotoğrafıyla kaplı olduğu çok samimi ve sıcak bir restoran.",
        "description_en": "A very friendly and warm restaurant serving traditional Dutch cuisine, with walls covered in hundreds of photos of mothers.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Stampot (patates püreli sebze yemeği) denemek için en iyi yerlerden biridir.",
        "tips_en": "One of the best places to try stamppot (mashed potatoes with vegetables)."
    },
    {
        "name": "Spiegelkwartier",
        "name_en": "Spiegelkwartier",
        "area": "Canal Ring",
        "category": "Alışveriş",
        "tags": ["antika", "sanat", "galeri", "lüks"],
        "distanceFromCenter": 0.5,
        "lat": 52.3614,
        "lng": 4.8889,
        "price": "high",
        "rating": 4.4,
        "description": "Amsterdam'ın antika ve sanat galerisi merkezi. Rijksmuseum'un hemen karşısındaki bu sokaklar, tarih ve sanat koleksiyoncuları için bir cennet.",
        "description_en": "Amsterdam's antique and art gallery hub. These streets right across from the Rijksmuseum are a paradise for history and art collectors.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Pahalı eserlerin yanı sıra ilginç vintage parçalar ve galeriler keşfedebilirsiniz.",
        "tips_en": "Beyond expensive artworks, you can discover interesting vintage pieces and galleries."
    },
    {
        "name": "Haarlemmerstraat",
        "name_en": "Haarlemmerstraat",
        "area": "Centrum-West",
        "category": "Alışveriş",
        "tags": ["gıda", "bağımsız dükkanlar", "butik", "lokal"],
        "distanceFromCenter": 1.0,
        "lat": 52.3803,
        "lng": 4.8911,
        "price": "medium",
        "rating": 4.7,
        "description": "Amsterdam'ın en iyi alışveriş caddelerinden biri. Bağımsız butikleri, özel peynir dükkanları ve Michelin yıldızlı olmayan yerel favori lokantalarıyla ünlüdür.",
        "description_en": "One of Amsterdam's best shopping streets. Famous for its independent boutiques, specialty cheese shops, and non-Michelin starred local favorite eateries.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Cadde üzerinde yürüyerek Jordaan'a veya NDSM feribotuna kolayca ulaşabilirsiniz.",
        "tips_en": "You can easily reach Jordaan or the NDSM ferry by walking along the street."
    },
    {
        "name": "The Seafood Bar",
        "name_en": "The Seafood Bar",
        "area": "Spuistraat / De Pijp",
        "category": "Restoran",
        "tags": ["deniz ürünleri", "taze", "yengeç", "modern"],
        "distanceFromCenter": 0.5,
        "lat": 52.3706,
        "lng": 4.8894,
        "price": "high",
        "rating": 4.7,
        "description": "Amsterdam'ın en popüler deniz ürünleri restoranı. Taze istiridveler, devasa deniz ürünü tabakları ve modern atmosferiyle bilinir.",
        "description_en": "Amsterdam's most popular seafood restaurant. Known for fresh oysters, massive seafood platters, and its modern atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1551731388-6934b3dc04fb?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Mixed grill tabağı 2-3 kişi için mükemmel paylaşımlık bir seçenektir.",
        "tips_en": "The mixed grill platter is a perfect shared option for 2-3 people."
    },
    {
        "name": "Stroopwafels van Lanskroon",
        "name_en": "Lanskroon",
        "area": "Canal Ring",
        "category": "Deneyim",
        "tags": ["stroopwafel", "geleneksel", "tatlı", "fırın"],
        "distanceFromCenter": 0.5,
        "lat": 52.3686,
        "lng": 4.8889,
        "price": "low",
        "rating": 4.6,
        "description": "Tarihi bir pastanede devasa, el yapımı 'king-size' ballı veya karamelli stroopwafelleri deneyebileceğiniz en iyi noktalardan biri.",
        "description_en": "One of the best spots to try massive, handmade 'king-size' honey or caramel stroopwafels in a historic bakery.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Diğer turist tuzaklarının aksine burasının stroopwafelleri çok daha otantik ve farklı bir dokuya sahiptir.",
        "tips_en": "Unlike other tourist traps, the stroopwafels here are much more authentic and have a different texture."
    }
]

def enrich_amsterdam_batch3():
    filepath = 'assets/cities/amsterdam.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_amsterdam_batch3:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_amsterdam_batch3()
print(f"Amsterdam now has {count} highlights.")
