import json
import os

new_berlin_highlights = [
    {
        "name": "Kollwitzplatz",
        "name_en": "Kollwitzplatz",
        "area": "Prenzlauer Berg",
        "category": "Park",
        "tags": ["meydan", "pazar", "aile", "tarihi"],
        "distanceFromCenter": 3.0,
        "lat": 52.5366,
        "lng": 13.4183,
        "price": "free",
        "rating": 4.6,
        "description": "Prenzlauer Berg'in kalbi. Cumartesi günleri kurulan ekolojik pazarı ve çevresindeki şık kafeleriyle ünlü huzurlu bir meydan.",
        "description_en": "The heart of Prenzlauer Berg. A peaceful square famous for its Saturday ecological market and charming surrounding cafes.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Cumartesi sabah",
        "bestTime_en": "Saturday morning",
        "tips": "Pazardan taze yerel ürünler alabilir veya heykel tıraş Käthe Kollwitz'in anıtını görebilirsiniz.",
        "tips_en": "Buy fresh local produce at the market or view the monument to artist Käthe Kollwitz."
    },
    {
        "name": "Museum für Naturkunde",
        "name_en": "Natural History Museum",
        "area": "Mitte",
        "category": "Müze",
        "tags": ["dinazor", "bilim", "aile"],
        "distanceFromCenter": 1.5,
        "lat": 52.5307,
        "lng": 13.3792,
        "price": "medium",
        "rating": 4.7,
        "description": "Dünyanın en büyük monte edilmiş dinozor iskeletine (Giraffatitan) ev sahipliği yapan, doğa ve bilim meraklıları için büyüleyici bir müze.",
        "description_en": "A fascinating museum for nature and science enthusiasts, home to the world's largest mounted dinosaur skeleton (Giraffatitan).",
        "imageUrl": "https://images.unsplash.com/photo-1518998053574-53f02ca7c98a?w=800",
        "bestTime": "Hafta içi",
        "bestTime_en": "Weekday",
        "tips": "Islak koleksiyon (alkol içindeki binlerce kavanoz) alanı görsel olarak çok etkileyicidir.",
        "tips_en": "The wet collection area (thousands of jars in alcohol) is visually very impressive."
    },
    {
        "name": "German Spy Museum",
        "name_en": "German Spy Museum",
        "area": "Mitte",
        "category": "Müze",
        "tags": ["casus", "soğuk savaş", "interaktif"],
        "distanceFromCenter": 0.5,
        "lat": 52.5089,
        "lng": 13.3790,
        "price": "medium",
        "rating": 4.5,
        "description": "Berlin'in 'Casuslar Başkenti' olduğu günlerden günümüze casusluk tarihini interaktif bir şekilde anlatan eğlenceli müze.",
        "description_en": "A fun interactive museum telling the history of espionage from the days when Berlin was the 'Capital of Spies' to the present.",
        "imageUrl": "https://images.unsplash.com/photo-1549463599-299f2a08da0e?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Lazer labirentinden geçmeyi deneyin; hem çocuklar hem yetişkinler için çok eğlenceli.",
        "tips_en": "Try navigating the laser maze; it's great fun for both kids and adults."
    },
    {
        "name": "Kulturbrauerei",
        "name_en": "Culture Brewery",
        "area": "Prenzlauer Berg",
        "category": "Tarihi",
        "tags": ["bira fabrikası", "kültür", "etkinlik", "mimari"],
        "distanceFromCenter": 3.2,
        "lat": 52.5382,
        "lng": 13.4127,
        "price": "low",
        "rating": 4.5,
        "description": "Eski bir bira fabrikasından dönüştürülmüş devasa kültür kompleksi. İçinde sinemalar, tiyatrolar, barlar ve DDR Müzesi'nin bir şubesi bulunur.",
        "description_en": "A massive cultural complex converted from an old brewery, housing cinemas, theaters, bars, and a branch of the DDR Museum.",
        "imageUrl": "https://images.unsplash.com/photo-1552566626-dca3f37494cc1?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Kışın Berlin'in en güzel Noel pazarlarından biri (Lucia Christmas Market) burada kurulur.",
        "tips_en": "In winter, it hosts one of Berlin's most beautiful Christmas markets (Lucia Christmas Market)."
    },
    {
        "name": "Grunewaldturm",
        "name_en": "Grunewald Tower",
        "area": "Grunewald",
        "category": "Manzara",
        "tags": ["kule", "orman", "manzara", "nehir"],
        "distanceFromCenter": 15.0,
        "lat": 52.4782,
        "lng": 13.1968,
        "price": "low",
        "rating": 4.6,
        "description": "Havel Nehri ve Grunewald ormanı üzerinde muhteşem manzaralar sunan tarihi kule. Şehrin gürültüsünden kaçmak için ideal.",
        "description_en": "A historic tower offering magnificent views over the Havel River and Grunewald forest. Ideal for escaping the city noise.",
        "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Kulenin altındaki restoranda bir şeyler içip nehir manzarasının keyfini çıkarabilirsiniz.",
        "tips_en": "Have a drink at the restaurant at the base of the tower and enjoy the river view."
    },
    {
        "name": "Gleis 17 Memorial",
        "name_en": "Track 17 Memorial",
        "area": "Grunewald",
        "category": "Tarihi",
        "tags": ["anıt", "holokost", "tarih"],
        "distanceFromCenter": 10.0,
        "lat": 52.4896,
        "lng": 13.2655,
        "price": "free",
        "rating": 4.8,
        "description": "Nazi döneminde Yahudilerin sürüldüğü tarihi tren yolu platformu. Raylar boyunca uzanan çelik levhalarda sürgün tarihleri ve sayıları yazılıdır.",
        "description_en": "The historic train platform from which Jews were deported during the Nazi era. Steel plates along the tracks record the dates and numbers of deportees.",
        "imageUrl": "https://images.unsplash.com/photo-1549463599-299f2a08da0e?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Sessiz ve etkileyici bir yerdir, ziyaret ederken saygılı olunması önerilir.",
        "tips_en": "A quiet and moving site; respect is recommended when visiting."
    },
    {
        "name": "Britzer Garten",
        "name_en": "Britzer Garden",
        "area": "Neukölln",
        "category": "Park",
        "tags": ["lake", "çiçek", "piknik", "aile"],
        "distanceFromCenter": 9.0,
        "lat": 52.4324,
        "lng": 13.4117,
        "price": "low",
        "rating": 4.7,
        "description": "1985 Federal Bahçecilik Fuarı için tasarlanan devasa park. Gölleri, temalı bahçeleri ve minyatür treni ile Berlinlilerin gizli favorisi.",
        "description_en": "A massive park designed for the 1985 Federal Garden Show. A local favorite with its lakes, themed gardens, and miniature railway.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Bahar veya Yaz",
        "bestTime_en": "Spring or Summer",
        "tips": "Lale zamanında (Tulipan) bahçeler muazzam bir renk şölenine dönüşür.",
        "tips_en": "During tulip season (Tulipan), the gardens become a magnificent festival of colors."
    },
    {
        "name": "Gärten der Welt",
        "name_en": "Gardens of the World",
        "area": "Marzahn",
        "category": "Park",
        "tags": ["botanik", "uluslararası", "teleferik"],
        "distanceFromCenter": 12.0,
        "lat": 52.5374,
        "lng": 13.5720,
        "price": "medium",
        "rating": 4.6,
        "description": "Çin, Japon, Bali, İtalyan ve daha birçok farklı kültürün bahçe sanatını bir araya getiren benzersiz bir park.",
        "description_en": "A unique park bringing together the garden arts of Chinese, Japanese, Balinese, Italian, and many other cultures.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Tam gün",
        "bestTime_en": "Full day",
        "tips": "Parka ulaşmak için Kienberg'den kalkan teleferiği kullanmak harika bir manzara sunar.",
        "tips_en": "Taking the cable car from Kienberg to reach the park offers great views."
    },
    {
        "name": "Kino International",
        "name_en": "Kino International",
        "area": "Mitte",
        "category": "Tarihi",
        "tags": ["sinema", "mimari", "DDR", "retro"],
        "distanceFromCenter": 1.2,
        "lat": 52.5206,
        "lng": 13.4228,
        "price": "medium",
        "rating": 4.7,
        "description": "Doğu Berlin'in en önemli prömiyer sineması olarak inşa edilen bina, 1960'ların modernist mimarisinin ikonik bir örneğidir.",
        "description_en": "Built as East Berlin's most important premiere cinema, the building is an iconic example of 1960s modernist architecture.",
        "imageUrl": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "İçindeki retro barında bir içki içip kendinizi geçmişe ışınlanmış gibi hissedebilirsiniz.",
        "tips_en": "Have a drink in its retro bar and feel as if you've been transported back in time."
    },
    {
        "name": "Karl-Marx-Allee",
        "name_en": "Karl-Marx-Allee",
        "area": "Mitte / Friedrichshain",
        "category": "Tarihi",
        "tags": ["bulvar", "mimari", "sovyet", "ikonik"],
        "distanceFromCenter": 2.0,
        "lat": 52.5177,
        "lng": 13.4352,
        "price": "free",
        "rating": 4.4,
        "description": "DDR döneminin en görkemli bulvarı. Sosyalist klasisizm (Düğün Pastası stili) binalarıyla devasa ve etkileyici bir yürüyüş yolu.",
        "description_en": "The most grand boulevard of the GDR era. A massive and impressive promenade with its Socialist Classicism (Wedding Cake style) buildings.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Strausberger Platz ile Frankfurter Tor arasındaki bölümü yürüyerek mimarinin ölçeğini en iyi şekilde görebilirsiniz.",
        "tips_en": "Walk the section between Strausberger Platz and Frankfurter Tor to best appreciate the scale of the architecture."
    },
    {
        "name": "Holzmarkt 25",
        "name_en": "Holzmarkt 25",
        "area": "Friedrichshain",
        "category": "Deneyim",
        "tags": ["alternatif", "bar", "nehir", "yaratıcı"],
        "distanceFromCenter": 2.5,
        "lat": 52.5090,
        "lng": 13.4259,
        "price": "low",
        "rating": 4.6,
        "description": "Spree Nehri kenarında ahşap yapılar, kafeler, barlar ve sanatsal alanlardan oluşan masalsı bir eko-köy ve kültür merkezi.",
        "description_en": "A fairytale eco-village and cultural center by the Spree River, consisting of wooden structures, cafes, bars, and artistic spaces.",
        "imageUrl": "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Nehir kenarındaki şezlonglarda bira içip ateş başında oturmak tam bir Berlin klasiğidir.",
        "tips_en": "Sitting in riverside loungers with a beer by a campfire is a classic Berlin experience."
    },
    {
        "name": "Mustafa's Gemüse Kebap",
        "name_en": "Mustafa's Gemuse Kebap",
        "area": "Kreuzberg",
        "category": "Restoran",
        "tags": ["döner", "sebzeli", "ikonik", "popüler"],
        "distanceFromCenter": 3.2,
        "lat": 52.4935,
        "lng": 13.3886,
        "price": "low",
        "rating": 4.5,
        "description": "Berlin'in en ünlü döner büfesi. Kızarmış sebzeli ve özel soslu döneri için her zaman uzun bir sıra vardır.",
        "description_en": "Berlin's most famous döner stall. There's always a long queue for their döner with roasted vegetables and special sauces.",
        "imageUrl": "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "En az 30-45 dakika beklemeye hazırlıklı olun. Sabrınızın karşılığını kesinlikle alacaksınız.",
        "tips_en": "Be prepared to wait at least 30-45 minutes. Your patience will definitely be rewarded."
    },
    {
        "name": "Bonanza Coffee Roasters",
        "name_en": "Bonanza Coffee Roasters",
        "area": "Kreuzberg",
        "category": "Kafe",
        "tags": ["kahve", "roastery", "nitelikli", "minimalist"],
        "distanceFromCenter": 2.8,
        "lat": 52.5034,
        "lng": 13.4187,
        "price": "low",
        "rating": 4.7,
        "description": "Berlin'in üçüncü dalga kahve öncülerinden biri. Modern kavurma yöntemleri ve kusursuz çekirdekleriyle bilinir.",
        "description_en": "One of Berlin's third-wave coffee pioneers, known for its modern roasting methods and flawless beans.",
        "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Adalbertstrasse'deki gizli avlu içindeki şubeleri daha sakin bir ortam sunar.",
        "tips_en": "The branch inside the hidden courtyard on Adalbertstrasse offers a quieter setting."
    },
    {
        "name": "Five Elephant",
        "name_en": "Five Elephant",
        "area": "Kreuzberg",
        "category": "Kafe",
        "tags": ["pasticceria", "kahve", "cheesecake", "lokal"],
        "distanceFromCenter": 3.5,
        "lat": 52.4983,
        "lng": 13.4288,
        "price": "low",
        "rating": 4.8,
        "description": "Hem kahveleri hem de şehrin en iyi cheesecake'ini yapmasıyla tanınan, Reichenberger Str üzerinde yer alan samimi kafe.",
        "description_en": "A cozy cafe on Reichenberger Str, famous for its coffee and for making what is widely considered the city's best cheesecake.",
        "imageUrl": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Philadelphia usulü cheesecake'i mutlaka deneyin, pişman olmayacaksınız.",
        "tips_en": "Be sure to try their Philadelphia-style cheesecake; you won't regret it."
    },
    {
        "name": "The Barn",
        "name_en": "The Barn",
        "area": "Mitte",
        "category": "Kafe",
        "tags": ["kahve", "nitelikli", "gurme"],
        "distanceFromCenter": 1.0,
        "lat": 52.5298,
        "lng": 13.4026,
        "price": "low",
        "rating": 4.6,
        "description": "Berlin kahve dünyasının 'pürist' temsilcisi. En yüksek kalitede çekirdekleri, sütsüz ve şekersiz kahveye odaklanan bir yaklaşımla sunarlar.",
        "description_en": "The 'purist' representative of Berlin's coffee world, serving highest quality beans with a focus on black coffee.",
        "imageUrl": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Kahve konusunda çok ciddiler, bu yüzden gerçek tadın keyfini çıkarmaya hazır olun.",
        "tips_en": "They take coffee very seriously, so be ready to enjoy the genuine flavor."
    },
    {
        "name": "Monkey Bar",
        "name_en": "Monkey Bar",
        "area": "Charlottenburg",
        "category": "Bar",
        "tags": ["rooftop", "manzara", "kokteyl", "havalı"],
        "distanceFromCenter": 4.5,
        "lat": 52.5065,
        "lng": 13.3379,
        "price": "high",
        "rating": 4.4,
        "description": "25hours Hotel'in en üst katında, Berlin Hayvanat Bahçesi'ndeki maymun barınaklarına bakan ve şehrin batı yakasını gören ünlü rooftop bar.",
        "description_en": "A famous rooftop bar at the top of 25hours Hotel, looking over the monkey enclosures at Berlin Zoo and offering views across the city's west side.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gün batımı",
        "bestTime_en": "Sunset",
        "tips": "Genelde kapıda kuyruk olur, gün batımı için biraz erken gitmenizde fayda var.",
        "tips_en": "Expect a queue at the door; it's best to go a bit early to catch the sunset."
    },
    {
        "name": "Prater Biergarten",
        "name_en": "Prater Biergarten",
        "area": "Prenzlauer Berg",
        "category": "Bar",
        "tags": ["bira bahçesi", "tarihi", "geleneksel", "lokal"],
        "distanceFromCenter": 3.8,
        "lat": 52.5401,
        "lng": 13.4098,
        "price": "low",
        "rating": 4.5,
        "description": "Berlin'in en eski bira bahçesi (1837'den beri). Kestane ağaçlarının altında devasa bir alan ve klasik Alman birası ve bratwurst.",
        "description_en": "Berlin's oldest beer garden (since 1837). A massive area under chestnut trees serving classic German beer and bratwurst.",
        "imageUrl": "https://images.unsplash.com/photo-1538587888044-79f13ddd7e49?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Kendi biralarını (Prater Pils) mutlaka deneyin. Ortam çok rahat ve neşelidir.",
        "tips_en": "Try their own beer (Prater Pils). The atmosphere is very relaxed and cheerful."
    },
    {
        "name": "Urban Nation Museum",
        "name_en": "Urban Nation Museum",
        "area": "Schöneberg",
        "category": "Müze",
        "tags": ["sokak sanatı", "grafiti", "modern", "çağdaş"],
        "distanceFromCenter": 3.0,
        "lat": 52.5005,
        "lng": 13.3605,
        "price": "free",
        "rating": 4.8,
        "description": "Dünyanın ilk büyük ölçekli sokak sanatı müzesi. Bünyesinde dünyanın en ünlü sokak sanatçılarının eserlerini barındırıyor.",
        "description_en": "The world's first large-scale street art museum, housing works by some of the most famous street artists in the world.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Giriş ücretsizdir, müze binasının dış cephesi de dev bir mural ile kaplıdır.",
        "tips_en": "Entrance is free, and the building's exterior is also covered in a massive mural."
    },
    {
        "name": "Bikini Berlin",
        "name_en": "Bikini Berlin",
        "area": "Charlottenburg",
        "category": "Alışveriş",
        "tags": ["avm", "tasarım", "hayvanat bahçesi", "mimari"],
        "distanceFromCenter": 4.4,
        "lat": 52.5055,
        "lng": 13.3385,
        "price": "medium",
        "rating": 4.4,
        "description": "Tarihi Bikinihaus binasında yer alan 'konsept AVM'. İçindeki pencereler Berlin Hayvanat Bahçesi'ndeki maymunları görebilecek şekilde tasarlanmış.",
        "description_en": "A 'concept mall' in the historic Bikinihaus building. The windows inside are designed to offer views of the monkeys in the Berlin Zoo.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Çatı terasındaki bahçede oturup hayvanat bahçesini yan açıdan izleyebilirsiniz.",
        "tips_en": "Sit in the rooftop terrace garden and watch the zoo from a side perspective."
    },
    {
        "name": "Admiralbrücke",
        "name_en": "Admiral Bridge",
        "area": "Kreuzberg",
        "category": "Manzara",
        "tags": ["köprü", "lokal", "gün batımı", "kültür"],
        "distanceFromCenter": 3.0,
        "lat": 52.4938,
        "lng": 13.4140,
        "price": "free",
        "rating": 4.6,
        "description": "Landwehr Kanalı üzerindeki bu tarihi köprü, yaz akşamları yüzlerce kişinin bira içip gün batımını izlediği Berlin'in en havalı hang-out noktasıdır.",
        "description_en": "This historic bridge over the Landwehr Canal is Berlin's coolest hangout spot on summer evenings, where hundreds gather to watch the sunset.",
        "imageUrl": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        "bestTime": "Yaz akşamı",
        "bestTime_en": "Summer evening",
        "tips": "Genelde sokak müzisyenleri olur. Yol üzerindeki dönerci veya pizzacıdan bir şeyler alıp köprüde oturanlara katılın.",
        "tips_en": "There are often street musicians. Grab something from a nearby döner or pizza shop and join the crowd on the bridge."
    },
    {
        "name": "Thai Park (Preußenpark)",
        "name_en": "Thai Park",
        "area": "Wilmersdorf",
        "category": "Restoran",
        "tags": ["açık hava", "asya mutfağı", "ucuz", "lokal"],
        "distanceFromCenter": 5.5,
        "lat": 52.4912,
        "lng": 13.3105,
        "price": "low",
        "rating": 4.7,
        "description": "Taylandlı kadınların parkta seyyar tezgahlarda taze yemekler yaptığı, Berlin'in en benzersiz açık hava yemek deneyimi.",
        "description_en": "Berlin's most unique outdoor dining experience, where Thai families cook fresh traditional food on portable stalls in the park.",
        "imageUrl": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
        "bestTime": "Hafta sonu öğleden sonra",
        "bestTime_en": "Weekend afternoon",
        "tips": "Yanınıza bir örtü getirin ve parkın içinde piknik yapıyormuş gibi en taze papaya salatasını deneyin.",
        "tips_en": "Bring a blanket and enjoy the freshest papaya salad as if you were having a picnic in the park."
    }
]

# Filler descriptions for Berlin
berlin_fillers_fix = {
    "Fernsehturm (TV Kulesi)": {
        "description": "368 metre yüksekliğiyle Almanya'nın en yüksek yapısı. 360 derecelik panoramik Berlin manzarası ve döner restoranıyla şehrin simgesi.",
        "description_en": "Germany's tallest structure at 368 meters. An icon of the city with its 360-degree panoramic view and revolving restaurant."
    },
    "Charlottenburg Sarayı": {
        "description": "Berlin'in en büyük ve en görkemli sarayı. Prusya kralları için inşa edilen bu Barok şaheser, geniş bahçeleri ve müzesiyle büyüleyici.",
        "description_en": "Berlin's largest and most magnificent palace. Built for Prussian kings, this Baroque masterpiece enchants with its vast gardens and museum."
    },
    "Topography of Terror": {
        "description": "Nazi döneminin en karanlık sayfalarının anlatıldığı, eski Gestapo ve SS karargahı üzerine kurulu etkileyici belge merkezi.",
        "description_en": "An impressive documentation center on the site of the former Gestapo and SS headquarters, detailing the darkest chapters of the Nazi era."
    },
    "KaDeWe": {
        "description": "Kıtalararası Avrupa'nın en büyük çok katlı mağazası. Özellikle 6. katındaki gurme bölümü (Feinschmeckeretage) bir yemek cennetidir.",
        "description_en": "The largest department store in continental Europe. Its 6th-floor gourmet section (Feinschmeckeretage) is especially a foodie paradise."
    },
    "Müze Adası": {
        "description": "UNESCO listesindeki 5 dünya çapında müzenin bulunduğu ada. Bergama Sunağı, Nefertiti Büstü ve İştar Kapısı burada sergilenir.",
        "description_en": "UNESCO island housing 5 world-class museums. Home to the Pergamon Altar, Nefertiti Bust, and the Ishtar Gate."
    }
}

def enrich_berlin():
    filepath = 'assets/cities/berlin.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update fillers
    for h in data.get('highlights', []):
        if h['name'] in berlin_fillers_fix:
            fix = berlin_fillers_fix[h['name']]
            h['description'] = fix['description']
            h['description_en'] = fix['description_en']

    # Add new ones
    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_berlin_highlights:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_berlin()
print(f"Berlin now has {count} highlights.")
