import json
import os

new_kopenhag_final = [
    {
        "name": "Bispebjerg Kirkegård (Kiraz Çiçekleri)",
        "name_en": "Bispebjerg Cemetery",
        "area": "Nørrebro/Bispebjerg",
        "category": "Park",
        "tags": ["kiraz çiçeği", "ilkbahar", "park", "manzara"],
        "distanceFromCenter": 5.0,
        "lat": 55.7139,
        "lng": 12.5401,
        "price": "free",
        "rating": 4.8,
        "description": "Özellikle bahar aylarında (Nisan sonu) açan kiraz ağacı tünelleriyle ünlü, Kopenhag'ın en büyük mezarlık ve park alanlarından biri.",
        "description_en": "One of Copenhagen's largest cemetery and park areas, famous for its cherry blossom tunnels that bloom especially in spring (late April).",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Nisan sonu (bahar)",
        "bestTime_en": "Late April (spring)",
        "tips": "Kiraz çiçekleri açtığında oldukça kalabalık olabilir, sabah erken gitmenizi öneririz.",
        "tips_en": "It can get quite crowded when the cherry blossoms bloom, so we recommend going early in the morning."
    },
    {
        "name": "Kayaking the Canals (Yeşil Kano)",
        "name_en": "Green Kayak",
        "area": "Liman Bölgeleri",
        "category": "Deneyim",
        "tags": ["kano", "çevre", "ücretsiz", "aktivite"],
        "distanceFromCenter": 1.0,
        "lat": 55.6715,
        "lng": 12.5856,
        "price": "low",
        "rating": 4.9,
        "description": "Kopenhag kanallarını kano ile gezebilirsiniz. Eğer gezerken su yüzeyindeki çöpleri toplarsanız kano kiralama ücreti alınmaz!",
        "description_en": "Explore Copenhagen's canals by kayak. If you pick up trash from the water's surface during your trip, the rental fee is waived!",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Yaz günleri",
        "bestTime_en": "Summer days",
        "tips": "Hem şehri su seviyesinden görmek hem de çevreye katkıda bulunmak için harika bir yoldur.",
        "tips_en": "A great way to see the city from water level while contributing to the environment."
    },
    {
        "name": "Skovtårnet - The Forest Tower",
        "name_en": "The Forest Tower",
        "area": "Camp Adventure (Günübirlik)",
        "category": "Deneyim",
        "tags": ["mimari", "doğa", "manzara", "orman"],
        "distanceFromCenter": 65.0,
        "lat": 55.2539,
        "lng": 11.9794,
        "price": "high",
        "rating": 4.8,
        "description": "Ormanın ortasında, 45 metre yüksekliğinde kum saati şeklinde ödüllü bir gözlem kulesi. Ağaçların üzerinden 360 derece manzara sunar.",
        "description_en": "An award-winning, 45-meter-high hourglass-shaped observation tower in the middle of a forest. Offers 360-degree views from above the trees.",
        "imageUrl": "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kopenhag merkezden araçla yaklaşık 1 saat sürer; doğa severler için mutlaka ziyaret edilmesi gereken bir yerdir.",
        "tips_en": "About a 1-hour drive from central Copenhagen; a must-visit for nature lovers."
    },
    {
        "name": "Tivoli Food Hall",
        "name_en": "Tivoli Food Hall",
        "area": "Centrum",
        "category": "Kafe",
        "tags": ["yemek", "gurme", "çeşitli", "merkezi"],
        "distanceFromCenter": 0.3,
        "lat": 55.6745,
        "lng": 12.5658,
        "price": "medium",
        "rating": 4.5,
        "description": "Tivoli Bahçeleri'nin dış köşesinde yer alan, parka girmeden de ziyaret edebileceğiniz modern ve şık bir gastronomi marketi.",
        "description_en": "A modern and chic gastronomy market located on the outer corner of Tivoli Gardens, accessible without entering the park.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Akşam yemeği",
        "bestTime_en": "Dinner",
        "tips": "Hallernes Smørrebrød veya Gorm's pizza gibi yerel favorileri burada bulabilirsiniz.",
        "tips_en": "Find local favorites like Hallernes Smørrebrød or Gorm's pizza here."
    },
    {
        "name": "Konditaget Lüders (Çatı Parkı)",
        "name_en": "Konditaget Lüders",
        "area": "Nordhavn",
        "category": "Park",
        "tags": ["spor", "çatı", "modern", "oyun parkı"],
        "distanceFromCenter": 3.5,
        "lat": 55.7075,
        "lng": 12.5922,
        "price": "free",
        "rating": 4.7,
        "description": "Bir otopark binasının çatısında yer alan yenilikçi spor ve oyun alanı. Nordhavn manzarasını izlerken egzersiz yapabilirsiniz.",
        "description_en": "An innovative sports and play area located atop a multi-story parking garage. You can exercise while enjoying views of Nordhavn.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Pas rengi metal dış cephesi ve merdivenleriyle mimari açıdan da çok ilginçtir.",
        "tips_en": "Architecturally interesting with its rust-colored metal facade and exterior staircases."
    },
    {
        "name": "Dyrehaven (Geyik Parkı)",
        "name_en": "Dyrehaven",
        "area": "Klampenborg",
        "category": "Park",
        "tags": ["geyik", "doğa", "unesco", "yürüyüş"],
        "distanceFromCenter": 12.0,
        "lat": 55.7839,
        "lng": 12.5719,
        "price": "free",
        "rating": 4.9,
        "description": "Binlerce serbest geyiğin yaşadığı, bin yıllık meşe ağaçlarıyla dolu UNESCO listesindeki devasa kraliyet av parkı.",
        "description_en": "A massive UNESCO-listed royal hunting park filled with thousand-year-old oak trees and home to thousands of free-roaming deer.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Sabah erken",
        "bestTime_en": "Early morning",
        "tips": "At arabası turlarına katılabilir veya bisiklet kiralayarak parkı keşfedebilirsiniz.",
        "tips_en": "You can take horse-drawn carriage tours or rent a bike to explore the park."
    },
    {
        "name": "Stevns Klint (Beyaz Kayalıklar)",
        "name_en": "Stevns Klint",
        "area": "Sjælland (Günübirlik)",
        "category": "Tarihi",
        "tags": ["jeoloji", "unesco", "doğa", "deniz manzara"],
        "distanceFromCenter": 75.0,
        "lat": 55.281,
        "lng": 12.441,
        "price": "free",
        "rating": 4.8,
        "description": "Dünya tarihindeki dinozorların yok oluşuna dair kanıtlar sunan tebeşir kayalıkları. UNESCO Dünya Mirası Listesi'ndedir.",
        "description_en": "UNESCO World Heritage chalk cliffs providing evidence of the extinction of dinosaurs in world history.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Deniz kıyısındaki eski kiliseyi (Højerup Gamle Kirke) mutlaka görün, kilisenin bir kısmı denize doğru yıkılmıştır.",
        "tips_en": "Be sure to see the old church by the sea (Højerup Gamle Kirke), part of which has collapsed into the sea."
    },
    {
        "name": "Axel Towers",
        "name_en": "Axel Towers",
        "area": "Centrum",
        "category": "Tarihi",
        "tags": ["mimari", "modern", "bakır", "şehir"],
        "distanceFromCenter": 0.2,
        "lat": 55.6751,
        "lng": 12.5656,
        "price": "free",
        "rating": 4.6,
        "description": "Beş dairesel kuleden oluşan, bakır dış cephesiyle Kopenhag siluetine modern bir dokunuş katan ödüllü yapı topluluğu.",
        "description_en": "An award-winning complex consisting of five circular towers, adding a modern touch to Copenhagen's skyline with its copper exterior.",
        "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Kulelerin altındaki kamusal alanlar ve dükkanlar arasında yürümek keyiflidir.",
        "tips_en": "Strolling through the public spaces and shops beneath the towers is enjoyable."
    },
    {
        "name": "Muziekgebouw aan 't IJ (Copenhagen Jazz Festival)",
        "name_en": "DR Koncerthuset",
        "area": "Ørestad",
        "category": "Deneyim",
        "tags": ["müzik", "konser", "mimari", "jean nouvel"],
        "distanceFromCenter": 2.5,
        "lat": 55.6582,
        "lng": 12.5891,
        "price": "high",
        "rating": 4.8,
        "description": "Jean Nouvel tarafından tasarlanan, akustiği ve mavi dıs cephesiyle ünlü dünyanın en iyi konser salonlarından biri.",
        "description_en": "One of the world's best concert halls, designed by Jean Nouvel, famous for its acoustics and blue exterior.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam (konser saati)",
        "bestTime_en": "Evening (concert time)",
        "tips": "Binanın iç kısmında yer alan restoran ve bar alanı da oldukça şıktır.",
        "tips_en": "The restaurant and bar area inside the building are also quite elegant."
    },
    {
        "name": "Hey Captain (Kanal Turu)",
        "name_en": "Hey Captain",
        "area": "Liman Bölgesi",
        "category": "Deneyim",
        "tags": ["tekne", "tur", "kanallar", "kişisel"],
        "distanceFromCenter": 1.0,
        "lat": 55.6795,
        "lng": 12.5936,
        "price": "high",
        "rating": 4.9,
        "description": "Kopenhag kanallarında daha küçük gruplarla, rehberin hikayeleri eşliğinde yapılan butik ve samimi tekne turları.",
        "description_en": "Boutique and intimate boat tours on Copenhagen's canals with smaller groups, accompanied by the captain's stories.",
        "imageUrl": "https://images.unsplash.com/photo-1503431128566-66abc0cf0464?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Büyük tur teknelerinin aksine, bu teknelerle daha dar kanalları ve gizli noktaları keşfedebilirsiniz.",
        "tips_en": "Unlike large tour boats, these vessels can explore narrower canals and hidden spots."
    },
    {
        "name": "Prolog Coffee Bar",
        "name_en": "Prolog Coffee Bar",
        "area": "Meatpacking District",
        "category": "Kafe",
        "tags": ["kahve", "gurme", "lokal", "vesterbro"],
        "distanceFromCenter": 1.5,
        "lat": 55.6672,
        "lng": 12.5621,
        "price": "low",
        "rating": 4.8,
        "description": "Kopenhag'ın en iyi kahve kavurucularından biri. Meatpacking District'in kalbinde, küçük ama çok popüler bir kahve durağı.",
        "description_en": "One of Copenhagen's best coffee roasters. A small but very popular coffee stop in the heart of the Meatpacking District.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Sabah",
        "bestTime_en": "Morning",
        "tips": "Espresso veya filtre kahvelerini yanında taze unlu mamullerle deneyin.",
        "tips_en": "Try their espresso or filter coffees alongside fresh pastries."
    },
    {
        "name": "SMK - Statens Museum for Kunst",
        "name_en": "SMK - National Gallery",
        "area": "Osterbro",
        "category": "Müze",
        "tags": ["sanat", "ulusal galeri", "klasik", "modern"],
        "distanceFromCenter": 1.2,
        "lat": 55.6885,
        "lng": 12.5784,
        "price": "medium",
        "rating": 4.6,
        "description": "Danimarka'nın ulusal sanat müzesi. 700 yıllık sanat tarihini kapsayan geniş koleksiyonuyla büyüleyici bir yapı.",
        "description_en": "Denmark's national gallery, featuring a vast collection spanning 700 years of art history in a captivating building.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Müzenin arkasında yer alan parkta dinlenebilir veya gölet manzarasını izleyebilirsiniz.",
        "tips_en": "Relax in the park behind the museum or enjoy views of the pond."
    },
    {
        "name": "Illums Bolighus",
        "name_en": "Illums Bolighus",
        "area": "Strøget",
        "category": "Alışveriş",
        "tags": ["tasarım", "mobilya", "daniş", "ev dekoru"],
        "distanceFromCenter": 0.2,
        "lat": 55.6789,
        "lng": 12.5779,
        "price": "high",
        "rating": 4.7,
        "description": "Danimarka ve İskandinav tasarımının en iyilerini sunan, dünyanın en ünlü ev dekorasyon ve mobilya mağazalarından biri.",
        "description_en": "One of the world's most famous home decor and furniture stores, showcasing the best of Danish and Scandinavian design.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Alışveriş yapmasanız bile Danimarka tasarım estetiğini anlamak için içindeki reyonları dolaşmalısınız.",
        "tips_en": "Even if you don't shop, browse the aisles to appreciate Danish design aesthetics."
    },
    {
        "name": "Fællesparken",
        "name_en": "Fælledparken",
        "area": "Østerbro",
        "category": "Park",
        "tags": ["park", "yeşil alan", "etkinlik", "lokal"],
        "distanceFromCenter": 2.8,
        "lat": 55.6994,
        "lng": 12.5714,
        "price": "free",
        "rating": 4.6,
        "description": "Kopenhag'ın en büyük parkı. Festivaller, spor etkinlikleri ve yerel halkın güneşlenmek için tercih ettiği devasa yeşil alan.",
        "description_en": "Copenhagen's largest park. A massive green space used for festivals, sporting events, and where locals go to sunbathes.",
        "imageUrl": "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Yaz aylarında açık hava film gösterimleri veya konserlere rastlayabilirsiniz.",
        "tips_en": "You might stumble upon open-air film screenings or concerts during summer."
    },
    {
        "name": "Nordhavn Harbour Bath",
        "name_en": "Nordhavn Harbour Bath",
        "area": "Nordhavn",
        "category": "Deneyim",
        "tags": ["yüzme", "modern", "mimari", "liman"],
        "distanceFromCenter": 3.8,
        "lat": 55.7071,
        "lng": 12.5997,
        "price": "free",
        "rating": 4.8,
        "description": "Yeni gelişen Nordhavn bölgesinde, modern mimari ile çevrili popüler bir liman havuzu ve güneşlenme alanı.",
        "description_en": "A popular harbor pool and sunbathing area surrounded by modern architecture in the emerging Nordhavn district.",
        "imageUrl": "https://images.unsplash.com/photo-1548678906-f80e9a6572e2?w=800",
        "bestTime": "Sıcak günler",
        "bestTime_en": "Warm days",
        "tips": "Konditaget Lüders çatı parkı ile çok yakın bir mesafededir, ikisini aynı gün gezebilirsiniz.",
        "tips_en": "Very close to the Konditaget Lüders rooftop park; you can visit both on the same day."
    }
]

def enrich_kopenhag_final_process():
    filepath = 'assets/cities/kopenhag.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_kopenhag_final:
        if new_h['name'].lower() not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_kopenhag_final_process()
print(f"Kopenhag reached {count} highlights.")
