import json
import os

new_nice_final = [
    {
        "name": "Rue de France",
        "name_en": "Rue de France",
        "area": "Centro",
        "category": "Alışveriş",
        "tags": ["cadde", "restoran", "yaya yolu", "alışveriş"],
        "distanceFromCenter": 0.3,
        "lat": 43.6965,
        "lng": 7.2650,
        "price": "medium",
        "rating": 4.6,
        "description": "Promenade des Anglais'ye paralel uzanan, butikleri ve dünya mutfağından restoranlarıyla kentin en canlı yaya caddelerinden biri.",
        "description_en": "A popular pedestrianized street running parallel to the Promenade, lined with varied boutiques and international dining options."
    },
    {
        "name": "Palais de Justice Square",
        "name_en": "Palais de Justice Square",
        "area": "Vieux Nice",
        "category": "Manzara",
        "tags": ["meydan", "mimari", "barok", "sosyal"],
        "distanceFromCenter": 0.4,
        "lat": 43.6965,
        "lng": 7.2735,
        "price": "free",
        "rating": 4.7,
        "description": "Muazzam adalet sarayı binasının önündeki bu geniş meydan, pazar günleri kurulan antika kitap pazarı ve teraslarıyla ünlüdür.",
        "description_en": "Commonly used for events and markets, this grand square is dominated by the neoclassical Law Courts building."
    },
    {
        "name": "Église Saint-Jacques-le-Majeur",
        "name_en": "Church of Saint-Jacques-le-Majeur",
        "area": "Vieux Nice",
        "category": "Tarihi",
        "tags": ["kilise", "barok", "altın", "tarih"],
        "distanceFromCenter": 0.5,
        "lat": 43.6978,
        "lng": 7.2760,
        "price": "free",
        "rating": 4.8,
        "description": "Nice'in en zengin barok dekorasyonuna sahip kiliselerinden biri. Altın varaklı sunakları ve freskleriyle göz kamaştırıcı bir yapı.",
        "description_en": "A breathtaking Jesuit church known for its incredible Baroque interior, ornate altars, and exquisite ceiling frescoes."
    },
    {
        "name": "Marché aux Poissons (Fish Market)",
        "name_en": "Fish Market",
        "area": "Vieux Nice",
        "category": "Deneyim",
        "tags": ["balık pazarı", "lokal", "taze", "kültür"],
        "distanceFromCenter": 0.4,
        "lat": 43.6962,
        "lng": 7.2745,
        "price": "medium",
        "rating": 4.7,
        "description": "Place Saint-François üzerinde her sabah kurulan, yerel balıkçıların taze avlarını sattığı Nice'in en otantik köşelerinden biri.",
        "description_en": "The daily fish market at Place Saint-François is one of the most traditional and lively sights in Old Nice."
    },
    {
        "name": "Rue Obscure (Villefranche)",
        "name_en": "Dark Street",
        "area": "Villefranche-sur-Mer",
        "category": "Tarihi",
        "tags": ["ortaçağ", "gizli", "tarihi sokağı", "ilginç"],
        "distanceFromCenter": 4.0,
        "lat": 43.7045,
        "lng": 7.3115,
        "price": "free",
        "rating": 4.9,
        "description": "13. yüzyıldan kalma, tamamen binaların altında kalan karanlık ve gizemli bir ortaçağ sokağı. Adeta zaman yolculuğu.",
        "description_en": "A 13th-century vaulted street that runs entirely underneath the houses of the Old Town, providing a cool and haunting escape."
    },
    {
        "name": "Phare de Nice (Lighthouse)",
        "name_en": "Nice Lighthouse",
        "area": "Port",
        "category": "Manzara",
        "tags": ["deniz feneri", "liman", "manzara", "yürüyüş"],
        "distanceFromCenter": 1.5,
        "lat": 43.6935,
        "lng": 7.2885,
        "price": "free",
        "rating": 4.6,
        "description": "Limanın girişindeki bu tarihi deniz feneri, denizin ve kentin silüetinin harika bir manzarasını sunan keyifli bir yürüyüşün sonu.",
        "description_en": "Standing at the entrance of Port Lympia, this lighthouse is the target of a scenic walk along the sea wall."
    },
    {
        "name": "Parc de la Bastide",
        "name_en": "Bastide Park",
        "area": "Gairaut",
        "category": "Park",
        "tags": ["doğa", "sessiz", "manzara", "lokal"],
        "distanceFromCenter": 5.0,
        "lat": 43.7380,
        "lng": 7.2620,
        "price": "free",
        "rating": 4.5,
        "description": "Kentin biraz dışında, harika deniz manzarasına sahip, zeytin ağaçları arasında sessiz bir dinlenme alanı.",
        "description_en": "A quiet local park set in the hills of Gairaut, away from the bustle, offering panoramic views of the Mediterranean."
    },
    {
        "name": "Musée de la Photographie Charles Nègre",
        "name_en": "Photography Museum",
        "area": "Vieux Nice",
        "category": "Müze",
        "tags": ["fotoğraf", "modern", "sanat", "sergi"],
        "distanceFromCenter": 0.4,
        "lat": 43.6965,
        "lng": 7.2740,
        "price": "low",
        "rating": 4.7,
        "description": "Cours Saleya yakınındaki bu müze, dünyanın en ünlü fotoğrafçılarının geçici sergilerine ev sahipliği yapan şık bir sanat mekanı.",
        "description_en": "A specialized museum hosting high-quality temporary photography exhibitions in a revamped historic building."
    },
    {
        "name": "Sentier du Littoral (Görsel Rota)",
        "name_en": "Coastal Path",
        "area": "Port / Mont Boron",
        "category": "Deneyim",
        "tags": ["yürüyüş", "doğa", "deniz kıyısı", "falez"],
        "distanceFromCenter": 2.2,
        "lat": 43.6885,
        "lng": 7.2950,
        "price": "free",
        "rating": 4.9,
        "description": "Nice limanından Villefranche'a kadar deniz kıyısındaki kayalıklar ve falezler üzerinden uzanan, kentin en güzel yürüyüş yolu.",
        "description_en": "A spectacular coastal trail that hugs the cliffs between Nice and Villefranche, offering access to hidden swimming spots."
    },
    {
        "name": "Cascade de Gairaut",
        "name_en": "Gairaut Waterfall",
        "area": "Gairaut",
        "category": "Manzara",
        "tags": ["şelale", "doğa", "manzara", "su"],
        "distanceFromCenter": 5.5,
        "lat": 43.7370,
        "lng": 7.2605,
        "price": "free",
        "rating": 4.8,
        "description": "19. yüzyıldan kalma dekoratif bir şelale. Nice'in su ihtiyacını karşılayan kanalın bir parçası olup kentin en iyi manzaralı noktalarından biridir.",
        "description_en": "A scenic 19th-century artificial waterfall and stone chalet that marks the arrival of the Vésubie canal water into Nice."
    },
    {
        "name": "Rue de la Préfecture",
        "name_en": "Prefecture Street",
        "area": "Vieux Nice",
        "category": "Deneyim",
        "tags": ["gece hayatı", "bar", "tapas", "tarihi"],
        "distanceFromCenter": 0.5,
        "lat": 43.6965,
        "lng": 7.2755,
        "price": "medium",
        "rating": 4.7,
        "description": "Eski Nice'in kalbinde, akşamları barları ve restoranlarıyla kentin en canlı gece hayatı noktasına dönüşen tarihi sokak.",
        "description_en": "A key street in Old Nice that transitions from a busy shopping alley by day to a vibrant nightlife hub by night."
    },
    {
        "name": "Musée Franciscain",
        "name_en": "Franciscan Museum",
        "area": "Cimiez",
        "category": "Müze",
        "tags": ["dini sanat", "tarih", "manastır", "sanat"],
        "distanceFromCenter": 2.3,
        "lat": 43.7202,
        "lng": 7.2792,
        "price": "free",
        "rating": 4.6,
        "description": "Cimiez Manastırı içindeki bu müze, 13. yüzyıldan günümüze keşişlerin yaşamını ve nadide dini objeleri sergiler.",
        "description_en": "Located within the Cimiez Monastery, this museum traces the history of the Franciscan order through art and religious artifacts."
    },
    {
        "name": "Place Saint-François",
        "name_en": "Saint-Francois Square",
        "area": "Vieux Nice",
        "category": "Tarihi",
        "tags": ["meydan", "balık pazarı", "belediye", "lokal"],
        "distanceFromCenter": 0.6,
        "lat": 43.6985,
        "lng": 7.2765,
        "price": "free",
        "rating": 4.7,
        "description": "Eski belediye binası ve balık pazarına ev sahipliği yapan, Nice'in en otantik ve gürültülü (ama keyifli) yerel meydanı.",
        "description_en": "A lively traditional square home to the city’s fish market and surrounded by historic civic buildings."
    },
    {
        "name": "Villa Ephrussi de Rothschild (View)",
        "name_en": "Villa Ephrussi Viewpoint",
        "area": "Saint-Jean-Cap-Ferrat",
        "category": "Manzara",
        "tags": ["bahçe", "saray", "deniz", "manzara"],
        "distanceFromCenter": 6.0,
        "lat": 43.6970,
        "lng": 7.3320,
        "price": "free",
        "rating": 4.9,
        "description": "Nice'ten kısa bir yolculukla ulaşabileceğiniz, pembe bir sarayın muazzam tematik bahçeleri ve denizi kucaklayan manzarası.",
        "description_en": "Accessible from Nice, this viewpoint overlooks one of the most beautiful villas on Saint-Jean-Cap-Ferrat and its nine themed gardens."
    },
    {
        "name": "Crypte Archéologique de Nice",
        "name_en": "Archaeological Crypt",
        "area": "Garibaldi",
        "category": "Tarihi",
        "tags": ["yeraltı", "arkeoloji", "sur", "tarih"],
        "distanceFromCenter": 0.7,
        "lat": 43.7005,
        "lng": 7.2805,
        "price": "medium",
        "rating": 4.8,
        "description": "Garibaldi Meydanı'nın altında keşfedilen, 14. yüzyıldan kalma devasa ortaçağ surlarını ve savunma sistemlerini görebileceğiniz yeraltı müzesi.",
        "description_en": "A vast underground archaeological site beneath Place Garibaldi, showcasing the medieval fortifications of Nice."
    },
    {
        "name": "Place de l'Île de Beauté",
        "name_en": "Ile de Beaute Square",
        "area": "Port",
        "category": "Manzara",
        "tags": ["meydan", "liman", "mimari", "kırmızı"],
        "distanceFromCenter": 1.2,
        "lat": 43.6975,
        "lng": 7.2855,
        "price": "free",
        "rating": 4.7,
        "description": "Port Lympia'nın girişinde, kırmızı binaları ve kilisesiyle kenti limana bağlayan görkemli ve şık meydan.",
        "description_en": "The grand entrance to the port, framed by elegant red buildings and the Church of Notre-Dame du Port."
    },
    {
        "name": "Sentier de la Cascade (Gairaut)",
        "name_en": "Cascade Path",
        "area": "Gairaut",
        "category": "Deneyim",
        "tags": ["yürüyüş", "doğa", "sessiz", "manzara"],
        "distanceFromCenter": 5.2,
        "lat": 43.7360,
        "lng": 7.2615,
        "price": "free",
        "rating": 4.6,
        "description": "Gairaut şelalesine çıkan sessiz yeşil yol. Hem spor yapan yerlileri görebileceğiniz hem de Nice'in tepeden tadını çıkarabileceğiniz bir rota.",
        "description_en": "A verdant and peaceful path leading to the Gairaut waterfall, popular with local joggers and hikers."
    },
    {
        "name": "Parc du Vigier",
        "name_en": "Vigier Park",
        "area": "Port / Mont Boron",
        "category": "Park",
        "tags": ["palmiye", "sessiz", "liman", "bahçe"],
        "distanceFromCenter": 1.8,
        "lat": 43.6915,
        "lng": 7.2895,
        "price": "free",
        "rating": 4.5,
        "description": "Limanın hemen arkasında, devasa palmiye ağaçları ve sessiz atmosferiyle Nice'in en az keşfedilmiş kentiçi parklarından biri.",
        "description_en": "A quiet residential park near the port, home to some of the tallest and oldest palm trees in the city."
    },
    {
        "name": "Rue de la Boucherie",
        "name_en": "Butcher Street",
        "area": "Vieux Nice",
        "category": "Alışveriş",
        "tags": ["tarihi", "kasap", "pazar", "gurme"],
        "distanceFromCenter": 0.5,
        "lat": 43.6968,
        "lng": 7.2750,
        "price": "medium",
        "rating": 4.7,
        "description": "Eski Nice'in en dar ve en lezzetli sokaklarından biri. Adını tarihi kasap dükkanlarından alır, şimdi ise gurme duraklarla dolu.",
        "description_en": "One of the most atmospheric and narrow alleys in the Old Town, once the base for the city's butchers."
    },
    {
        "name": "Museo de Art Naïf Anatole Jakovsky",
        "name_en": "Museum of Naive Art",
        "area": "Batı Nice",
        "category": "Müze",
        "tags": ["naif sanat", "renkli", "saray", "sanat"],
        "distanceFromCenter": 4.0,
        "lat": 43.6875,
        "lng": 7.2295,
        "price": "medium",
        "rating": 4.6,
        "description": "Şık bir şatonun içinde yer alan, dünyanın en büyük 'naif sanat' (eğitimsiz ressamların sanatı) koleksiyonlarından birine sahip müze.",
        "description_en": "Set in a beautiful château, this museum displays an enchanting world of Naive art from the 18th century to today."
    },
    {
        "name": "Quai Rauba Capeu",
        "name_en": "Quai Rauba Capeu",
        "area": "Promenade / Port",
        "category": "Manzara",
        "tags": ["sahil", "rüzgar", "gün batımı", "yürüyüş"],
        "distanceFromCenter": 0.9,
        "lat": 43.6945,
        "lng": 7.2815,
        "price": "free",
        "rating": 4.8,
        "description": "Promenade'ı limana bağlayan kıvrımlı rıhtım. Nice'in 'rüzgarın şapkayı uçurduğu yer' olarak bilinen en güzel gün batımı noktası.",
        "description_en": "The winding coastal road connecting the Promenade to the Port, famous for its dramatic sea waves and the 'I Love Nice' sign."
    },
    {
        "name": "Square de la Tour",
        "name_en": "Tower Square",
        "area": "Vieux Nice",
        "category": "Tarihi",
        "tags": ["kule", "meydan", "ortaçağ", "gizli"],
        "distanceFromCenter": 0.6,
        "lat": 43.6980,
        "lng": 7.2775,
        "price": "free",
        "rating": 4.4,
        "description": "Eski Nice'in kuzeyinde, Roma döneminden kalma bir kulenin kalıntılarını barındıran sessiz ve gizli bir küçük meydan.",
        "description_en": "A quiet, leafy square in the Old Town featuring the remains of a 15th-century tower used for defensive purposes."
    },
    {
        "name": "Boulangerie Lagache",
        "name_en": "Lagache Bakery",
        "area": "Vieux Nice",
        "category": "Kafe",
        "tags": ["fırın", "pastane", "tarihi", "tatlı"],
        "distanceFromCenter": 0.5,
        "lat": 43.6970,
        "lng": 7.2750,
        "price": "low",
        "rating": 4.8,
        "description": "Nice'in en eski ve en başarılı geleneksel fırınlarından biri. Pissaladière ve kruvasanları için mutlaka uğranmalı.",
        "description_en": "A beloved traditional bakery in Old Nice, perfect for an authentic breakfast or to grab a slice of local onion-and-anchovy 'pissaladière'."
    },
    {
        "name": "Port de Nice (Rıhtım Yürüyüşü)",
        "name_en": "Port of Nice Waterfront Walk",
        "area": "Port",
        "category": "Deneyim",
        "tags": ["liman", "yürüyüş", "yat", "deniz"],
        "distanceFromCenter": 1.3,
        "lat": 43.6970,
        "lng": 7.2870,
        "price": "free",
        "rating": 4.7,
        "description": "Boydan boya limanı çevreleyen, ultra lüks yatlar ile eski balıkçı teknelerinin yarattığı kontrastı izleyerek yapabileceğiniz en keyifli yürüyüş.",
        "description_en": "Stroll around the entire perimeter of Port Lympia to admire the classic Nice architecture and the vibrant marina activity."
    },
    {
        "name": "Conservatoire de Nice",
        "name_en": "Nice Conservatoire",
        "area": "Cimiez",
        "category": "Tarihi",
        "tags": ["müzik", "sanat", "mimari", "kültür"],
        "distanceFromCenter": 3.2,
        "lat": 43.7180,
        "lng": 7.2720,
        "price": "free",
        "rating": 4.6,
        "description": "Şık bir tepede yer alan ve ücretsiz konserlere ev sahipliği yapan, Nice'in müzik ve dans eğitiminin merkezi olan muazzam bina.",
        "description_en": "Located in a grand building with great acoustics, this conservatoire hosts frequent free classical concerts performed by students and faculty."
    },
    {
        "name": "Eglise de l'Annonciation",
        "name_en": "Church of the Annunciation",
        "area": "Vieux Nice",
        "category": "Tarihi",
        "tags": ["kilise", "barok", "sanat", "tarih"],
        "distanceFromCenter": 0.5,
        "lat": 43.6965,
        "lng": 7.2758,
        "price": "free",
        "rating": 4.7,
        "description": "Nice'in en eski kiliselerinden biri (10. yüzyıl kökenli). Mütevazı dış cephesinin ardında muazzam bir barok zenginlik saklar.",
        "description_en": "Known to locals as 'Sainte-Rita,' this church is a masterpiece of Baroque art and remains a very popular spot for local devotions."
    },
    {
        "name": "Plage de la Réserve",
        "name_en": "La Reserve Beach",
        "area": "Port / Mont Boron",
        "category": "Deneyim",
        "tags": ["plaj", "kayalık", "yerel", "deniz"],
        "distanceFromCenter": 1.7,
        "lat": 43.6898,
        "lng": 7.2890,
        "price": "free",
        "rating": 4.8,
        "description": "Turist kalabalığından uzak, Nice yerlilerinin kayalıklardan denize girdiği en 'cool' ve küçük plaj alanı.",
        "description_en": "A small rocky beach cove favored by locals, located just past the port and far from the busy gravel beaches of the Promenade."
    },
    {
        "name": "Théâtre de Verdure",
        "name_en": "Theatre de Verdure",
        "area": "Promenade",
        "category": "Manzara",
        "tags": ["tiyatro", "açık hava", "konser", "park"],
        "distanceFromCenter": 0.3,
        "lat": 43.6952,
        "lng": 7.2678,
        "price": "low",
        "rating": 4.7,
        "description": "Deniz kıyısındaki Albert I bahçesi içinde yer alan, palmiyeler arasında açık hava konserleri izleyebileceğiniz efsanevi sahne.",
        "description_en": "An iconic open-air amphitheater within the Jardin Albert 1er, hosting major music concerts and festivals under the Mediterranean stars."
    },
    {
        "name": "Rue Catherine Ségurane",
        "name_en": "Catherine Segurane Street",
        "area": "Port / Garibaldi",
        "category": "Alışveriş",
        "tags": ["antika", "sanat", "alışveriş", "tarihi"],
        "distanceFromCenter": 0.8,
        "lat": 43.6995,
        "lng": 7.2825,
        "price": "high",
        "rating": 4.6,
        "description": "Port Lympia'nın batı tarafındaki antika dükkanları ve sanat galerileriyle ünlü, Nice'in en prestijli caddelerinden biridir.",
        "description_en": "The antique-shopping heart of Nice, lined with high-end furniture dealers, vintage shops, and specialized art restorers."
    },
    {
        "name": "Cascade de la Colline (Daha Üst)",
        "name_en": "Upper Cascade",
        "area": "Castle Hill",
        "category": "Manzara",
        "tags": ["şelale", "soğuk", "manzara", "doğa"],
        "distanceFromCenter": 0.9,
        "lat": 43.6990,
        "lng": 7.2822,
        "price": "free",
        "rating": 4.8,
        "description": "Castle Hill şelalesinin tam dibindeki seyir terası. Su zerrecikleri arasında kentin en ferahlatıcı manzarasını buradan izleyebilirsiniz.",
        "description_en": "The viewing platform right at the base of the Castle Hill waterfall, perfect for feeling the mist and catching a rainbow on sunny days."
    },
    {
        "name": "Place Saint-Roch",
        "name_en": "Place Saint-Roch",
        "area": "Saint-Roch",
        "category": "Manzara",
        "tags": ["meydan", "lokal", "pazar", "otantik"],
        "distanceFromCenter": 2.5,
        "lat": 43.7120,
        "lng": 7.2880,
        "price": "free",
        "rating": 4.4,
        "description": "Kentin doğusunda, tamamen yerel hayatın aktığı, meyve sebze pazarı ve samimi mahalle kahveleriyle Nice'in gizli kalmış bir meydanı.",
        "description_en": "A true locals-only square in the east of the city, featuring its own charming food market and a very authentic Nice vibe."
    },
    {
        "name": "Rue de l'Abbaye",
        "name_en": "Abbey Street",
        "area": "Vieux Nice",
        "category": "Deneyim",
        "tags": ["butik", "tarihi", "el yapımı", "gizli"],
        "distanceFromCenter": 0.5,
        "lat": 43.6960,
        "lng": 7.2748,
        "price": "medium",
        "rating": 4.7,
        "description": "Eski Nice'in kuytularında, el yapımı sabunlardan sanatsal ürünlere kadar pek çok butiğe ev sahipliği yapan sessiz ve dar bir sokak.",
        "description_en": "A quiet, atmospheric alley in the Old Town near the Opera house, perfect for discovering local artisans and boutique soaps."
    }
]

def enrich_nice_final():
    filepath = 'assets/cities/nice.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_nice_final:
        if new_h['name'].lower() not in existing_names:
            new_h['imageUrl'] = "https://images.unsplash.com/photo-1543783232-af412b852fc7?w=800"
            new_h['bestTime'] = "Gündüz"
            new_h['bestTime_en'] = "Daytime"
            new_h['tips'] = "Mutlaka görün."
            new_h['tips_en'] = "A must see."
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_nice_final()
print(f"Nice now has {count} highlights.")
