import json
import os

new_rome_final = [
    {
        "name": "Sant'Ignazio di Loyola",
        "name_en": "Sant'Ignazio Church",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["barok", "fresk", "optik illüzyon", "sahte kubbe"],
        "distanceFromCenter": 0.3,
        "lat": 41.8992,
        "lng": 12.4797,
        "price": "free",
        "rating": 4.8,
        "description": "Andrea Pozzo tarafından yapılan muazzam tavan freskleri ve bütçe yetersizliği nedeniyle resmedilen ünlü 'sahte kubbesi' ile bilinen barok şaheser.",
        "description_en": "A Baroque masterpiece known for its magnificent ceiling frescoes by Andrea Pozzo and its famous 'fake dome' painted due to lack of funds.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Tavandaki perspektif oyununu en iyi görmek için yerdeki sarı disk üzerinde durun.",
        "tips_en": "Stand on the yellow disk on the floor to best appreciate the perspective play on the ceiling."
    },
    {
        "name": "Chiesa del Gesù",
        "name_en": "Church of the Gesu",
        "area": "Centro Storico",
        "category": "Tarihi",
        "tags": ["barok", "cizvit", "altın", "heybetli"],
        "distanceFromCenter": 0.2,
        "lat": 41.8958,
        "lng": 12.4797,
        "price": "free",
        "rating": 4.7,
        "description": "Cizvitlerin ana kilisesi ve barok mimarinin dünyadaki ilk örneklerinden biri. Altın varaklı süslemeleri ve dramatik tavan freskiyle büyüleyicidir.",
        "description_en": "The mother church of the Jesuits and one of the first examples of Baroque architecture in the world. Enchanting with its gold-leaf decorations and dramatic ceiling fresco.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Her akşamüstü saat 17:30'da ana sunaktaki İgnazio heykelinin gümüş kaplamasının kayarak arkasındaki gerçek heykeli gösterme törenini izleyin.",
        "tips_en": "Watch the ceremony every afternoon at 5:30 PM where the silver cover of the Ignatius statue slides to reveal the real statue behind it."
    },
    {
        "name": "Tempietto di Bramante",
        "name_en": "Bramante's Tempietto",
        "area": "Gianicolo",
        "category": "Tarihi",
        "tags": ["rönesans", "mimari", "küçük", "kusursuz"],
        "distanceFromCenter": 2.0,
        "lat": 41.8892,
        "lng": 12.4664,
        "price": "free",
        "rating": 4.6,
        "description": "San Pietro in Montorio kilisesinin avlusunda yer alan, Rönesans mimarisinin 'kusursuz' oranlarını temsil eden küçük ama dünyaca ünlü tapınak.",
        "description_en": "A small but world-famous temple in the courtyard of San Pietro in Montorio, representing the 'perfect' proportions of Renaissance architecture.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Öğleden önce",
        "bestTime_en": "Before noon",
        "tips": "Tepeden Roma manzarasını izledikten sonra bu mimari cevheri ziyaret edin.",
        "tips_en": "Visit this architectural gem after enjoying the Rome views from the hill."
    },
    {
        "name": "Santa Maria del Popolo",
        "name_en": "Santa Maria del Popolo",
        "area": "Piazza del Popolo",
        "category": "Tarihi",
        "tags": ["sanat", "caravaggio", "raphael", "rönesans"],
        "distanceFromCenter": 1.5,
        "lat": 41.9114,
        "lng": 12.4764,
        "price": "free",
        "rating": 4.8,
        "description": "Piazza del Popolo'nun köşesinde yer alan, Caravaggio'nun iki büyük eserini ve Raphael ile Bernini'nin tasarladığı şapelleri barındıran sanat dolu kilise.",
        "description_en": "Located in the corner of Piazza del Popolo, this art-filled church houses two major works by Caravaggio and chapels designed by Raphael and Bernini.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Cerasi Şapeli'ndeki Caravaggio tablolarını görmek için yanınızda bozuk para bulundurun.",
        "tips_en": "Have some change with you to light up the Caravaggio paintings in the Cerasi Chapel."
    },
    {
        "name": "Galleria Spada",
        "name_en": "Galleria Spada",
        "area": "Centro Storico",
        "category": "Müze",
        "tags": ["optik illüzyon", "borromini", "perspektif", "saray"],
        "distanceFromCenter": 0.6,
        "lat": 41.8939,
        "lng": 12.4722,
        "price": "medium",
        "rating": 4.7,
        "description": "Borromini tarafından tasarlanan ünlü 'perspektif koridoru' ile tanınan saray. 8 metrelik koridor illüzyon sayesinde 37 metre uzunluğunda görünür.",
        "description_en": "A palace known for its famous 'perspective gallery' designed by Borromini. Through illusion, an 8-meter corridor appears to be 37 meters long.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Öğleden önce",
        "bestTime_en": "Before noon",
        "tips": "Koridorun sonundaki heykelin aslında bir çocuk boyunda olduğunu görünce çok şaşıracaksınız.",
        "tips_en": "You'll be surprised to see that the statue at the end of the corridor is actually the size of a child."
    },
    {
        "name": "Bioparco di Roma",
        "name_en": "Bioparco Rome",
        "area": "Villa Borghese",
        "category": "Park",
        "tags": ["hayvanat bahçesi", "aile", "çocuklar", "doğa"],
        "distanceFromCenter": 2.5,
        "lat": 41.9172,
        "lng": 12.4864,
        "price": "high",
        "rating": 4.4,
        "description": "Villa Borghese parkının içinde yer alan, Avrupa'nın en eski hayvanat bahçelerinden biri. Özellikle çocuklu aileler için harika bir duraktır.",
        "description_en": "One of Europe's oldest zoos, located within the Villa Borghese park. A great stop especially for families with children.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Hayvanat bahçesine giriş biletini önceden online almak kalabalık günlerde vakit kazandırır.",
        "tips_en": "Buying zoo tickets online in advance saves time on crowded days."
    },
    {
        "name": "Chiostro del Bramante",
        "name_en": "Bramante Cloister",
        "area": "Centro Storico",
        "category": "Deneyim",
        "tags": ["mimari", "sanat galerisi", "kafe", "huzur"],
        "distanceFromCenter": 0.3,
        "lat": 41.8994,
        "lng": 12.4714,
        "price": "medium",
        "rating": 4.7,
        "description": "Rönesans mimarisi içinde çağdaş sanat sergileri sunan huzurlu bir merkez. Avluya bakan şık kafesi Roma'nın en özel köşelerinden biridir.",
        "description_en": "A peaceful center offering contemporary art exhibitions within Renaissance architecture. Its stylish cafe overlooking the courtyard is one of Rome's most special spots.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Kafesinde kahve içerken Raphael'in kilisedeki fresklerini cam bir pencereden görebilirsiniz.",
        "tips_en": "While drinking coffee in the cafe, you can see Raphael's frescoes in the church through a glass window."
    },
    {
        "name": "Foro Italico & Stadio Olimpico",
        "name_en": "Foro Italico",
        "area": "Flaminio",
        "category": "Tarihi",
        "tags": ["spor", "faşist mimari", "stadyum", "heykel"],
        "distanceFromCenter": 4.5,
        "lat": 41.9317,
        "lng": 12.4583,
        "price": "free",
        "rating": 4.5,
        "description": "Roma'nın devasa spor kompleksi. Stadio dei Marmi'deki 60 dev sporcu heykeli ve Stadio Olimpico ile modern spor tarihinin önemli bir merkezidir.",
        "description_en": "Rome's massive sports complex. An important center of modern sports history with its 60 giant athlete statues at Stadio dei Marmi and the Stadio Olimpico.",
        "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Stadio dei Marmi'nin beyaz mermer heykelleri arasında yürüyüş yapmak çok etkileyicidir.",
        "tips_en": "Walking among the white marble statues of the Stadio dei Marmi is very impressive."
    },
    {
        "name": "Pompi Tiramisù",
        "name_en": "Pompi Tiramisu",
        "area": "Re di Roma",
        "category": "Deneyim",
        "tags": ["tiramisu", "tatlı", "ünlü", "lezzetli"],
        "distanceFromCenter": 3.0,
        "lat": 41.8825,
        "lng": 12.5114,
        "price": "low",
        "rating": 4.6,
        "description": "Klasik, fıstıklı ve çilekli çeşitleriyle Roma'nın tartışmasız 'tiramisu kralı'. Şehrin pek çok noktasında şubesi bulunur.",
        "description_en": "Rome's undisputed 'king of tiramisu' with classic, pistachio, and strawberry varieties. Has several branches across the city.",
        "imageUrl": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
        "bestTime": "Tüm gün",
        "bestTime_en": "All day",
        "tips": "İspanyol Merdivenleri yakınındaki şubesinden alıp merdivenlere yakın bir yerde (oturmadan!) tadını çıkarabilirsiniz.",
        "tips_en": "You can grab one from the branch near the Spanish Steps and enjoy it nearby (without sitting!)."
    },
    {
        "name": "Two Sizes (Tiramisu & Cannoli)",
        "name_en": "Two Sizes",
        "area": "Piazza Navona",
        "category": "Deneyim",
        "tags": ["tiramisu", "cannoli", "gurme", "tatlı"],
        "distanceFromCenter": 0.4,
        "lat": 41.8994,
        "lng": 12.4706,
        "price": "low",
        "rating": 4.8,
        "description": "Küçük ve büyük olmak üzere iki boy tiramisu ve taze cannolileriyle ünlü, her zaman önünde sıra olan popüler tatlıcı.",
        "description_en": "Famous for its two sizes of tiramisu (small and large) and fresh cannoli, a popular dessert spot with consistent queues.",
        "imageUrl": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Antep fıstıklı (pistacchio) tiramisusu mutlaka denenmelidir.",
        "tips_en": "The pistachio tiramisu is a must-try."
    },
    {
        "name": "Old Bridge Gelateria",
        "name_en": "Old Bridge Gelateria",
        "area": "Vatikan",
        "category": "Deneyim",
        "tags": ["gelato", "vatikan", "popüler", "bol porsiyon"],
        "distanceFromCenter": 3.2,
        "lat": 41.9073,
        "lng": 12.4539,
        "price": "low",
        "rating": 4.7,
        "description": "Vatikan Müzeleri girişinin hemen karşısında, dev porsiyonları ve uygun fiyatıyla bilinen Roma'nın en efsanevi dondurmacılarından.",
        "description_en": "Right opposite the Vatican Museums entrance, one of Rome's most legendary gelato spots known for huge portions and great prices.",
        "imageUrl": "https://images.unsplash.com/photo-1501446529957-6226bd447c46?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Vatikan turundan sonra kendinizi ödüllendirmek için en iyi duraktır.",
        "tips_en": "The best stop to reward yourself after a Vatican tour."
    },
    {
        "name": "Roscioli Salumeria con Cucina",
        "name_en": "Roscioli Salumeria",
        "area": "Centro Storico",
        "category": "Restoran",
        "tags": ["gurme", "şarküteri", "şarap", "carbonara"],
        "distanceFromCenter": 0.5,
        "lat": 41.8942,
        "lng": 12.4732,
        "price": "high",
        "rating": 4.7,
        "description": "Dünyaca ünlü bir şarküteri, fırın ve restoran kompleksi. Roma'nın en kaliteli peynirleri, jambonları ve efsanevi carbonarası burada bulunur.",
        "description_en": "A world-famous deli, bakery, and restaurant complex. Home to Rome's highest quality cheeses, hams, and legendary carbonara.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Haftalar öncesinden rezervasyon yaptırmanız şarttır; şarküteri bölümünde ayakta tadım yapmayı deneyebilirsiniz.",
        "tips_en": "Reservations weeks in advance are essential; you can try standing tasting at the deli section."
    },
    {
        "name": "Pizzarium Bonci",
        "name_en": "Pizzarium Bonci",
        "area": "Vatikan",
        "category": "Deneyim",
        "tags": ["pizza", "sokak lezzeti", "ünlü", "gurme"],
        "distanceFromCenter": 3.8,
        "lat": 41.9089,
        "lng": 12.4489,
        "price": "medium",
        "rating": 4.6,
        "description": "Gabriele Bonci'nin yaratıcı pizza 'al taglio' (dilim pizza) başyapıtı. Sıradışı malzemeler ve inanılmaz hamuruyla bir pizza mabedidir.",
        "description_en": "Gabriele Bonci's creative pizza 'al taglio' (pizza by the slice) masterpiece. A pizza temple with unusual toppings and incredible dough.",
        "imageUrl": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
        "bestTime": "Öğle",
        "bestTime_en": "Noon",
        "tips": "Ayaküstü yenen küçük bir yerdir, numara alıp beklemeye hazırlıklı olun.",
        "tips_en": "A small stand-up spot; be prepared to take a number and wait."
    }
]

def enrich_rome_final():
    filepath = 'assets/cities/roma.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_rome_final:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    # I'll check the count after this.
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_rome_final()
print(f"Rome now has {count} highlights.")
