import json
import os

new_budapest_batch3 = [
    {
        "name": "Children's Railway (Gyermekvasút)",
        "name_en": "Children's Railway",
        "area": "Buda Hills",
        "category": "Deneyim",
        "tags": ["tren", "çocuklar", "nostalji", "doğa"],
        "distanceFromCenter": 8.5,
        "lat": 47.4833,
        "lng": 18.9667,
        "price": "medium",
        "rating": 4.8,
        "description": "Dünyanın en büyük çocuk demiryolu. Trenler, kıyafetleri ve disiplinleriyle örnek olan çocuklar tarafından işletilir (makinist hariç).",
        "description_en": "The world's largest children's railway. Trains are operated by children (except the driver) in uniform, following strict discipline.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Hafta sonu",
        "bestTime_en": "Weekend",
        "tips": "Buda tepelerinde muhteşem bir orman yolculuğu sunar.",
        "tips_en": "Offers a magnificent forest journey through the Buda Hills."
    },
    {
        "name": "Normafa",
        "name_en": "Normafa",
        "area": "Buda Hills",
        "category": "Park",
        "tags": ["doğa", "yürüyüş", "manzara", "piknik"],
        "distanceFromCenter": 8.0,
        "lat": 47.5000,
        "lng": 18.9667,
        "price": "free",
        "rating": 4.9,
        "description": "Budapeşte'nin en popüler doğa kaçış noktası. Yürüyüş parkurları, temiz havası ve şehre yukarıdan bakan manzarasıyla lokallerin favorisi.",
        "description_en": "Budapest's most popular nature escape. A local favorite with hiking trails, fresh air, and a view overlooking the city.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Hafta sonu sabah",
        "bestTime_en": "Weekend morning",
        "tips": "Buradaki meşhur 'Rétes' (strudel) dükkanından taze strudel yemeden dönmeyin.",
        "tips_en": "Don't leave without trying fresh strudel from the famous local 'Rétes' (strudel) shop."
    },
    {
        "name": "Aquincum Museum",
        "name_en": "Aquincum Museum",
        "area": "Óbuda",
        "category": "Müze",
        "tags": ["roma", "tarih", "antik", "açık hava"],
        "distanceFromCenter": 6.5,
        "lat": 47.5628,
        "lng": 19.0486,
        "price": "medium",
        "rating": 4.6,
        "description": "Roma dönemi kenti Aquincum'un kalıntıları üzerine kurulu arkeolojik müze. Antik Budapeşte'nin günlük yaşamına dair eşsiz izler sunar.",
        "description_en": "An archaeological museum built on the ruins of the Roman-era city of Aquincum. It offers unique insights into ancient Budapest life.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Su orgunu ve mozaikleri mutlaka görün.",
        "tips_en": "Be sure to see the water organ and the mosaics."
    },
    {
        "name": "Király Hamamı",
        "name_en": "Kiraly Thermal Bath",
        "area": "Buda",
        "category": "Deneyim",
        "tags": ["hamam", "osmanlı", "tarihi", "otantik"],
        "distanceFromCenter": 1.5,
        "lat": 47.5111,
        "lng": 19.0389,
        "price": "medium",
        "rating": 4.4,
        "description": "Budapeşte'deki en eski Osmanlı hamamlarından biri. 1565 yılına uzanan tarihi kubbesiyle son derece otantik ve mystique bir atmosfer sunar.",
        "description_en": "One of the oldest Ottoman baths in Budapest. With its historic dome dating back to 1565, it offers an extremely authentic and mystical atmosphere.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Diğer modern hamamlara göre çok daha küçük ama çok daha tarihidir.",
        "tips_en": "It's much smaller than other modern baths but much more historic."
    },
    {
        "name": "Szimpla Pazar",
        "name_en": "Szimpla Sunday Market",
        "area": "Yahudi Mahallesi",
        "category": "Deneyim",
        "tags": ["pazar", "yerel", "gurme", "ruin bar"],
        "distanceFromCenter": 0.5,
        "lat": 47.4970,
        "lng": 19.0630,
        "price": "low",
        "rating": 4.7,
        "description": "Pazar sabahları ünlü ruin bar Szimpla Kert'in içinde kurulan yerel üretici pazarı. Taze peynirler, ballar ve ev yapımı lezzetler bulunur.",
        "description_en": "A local farmers' market held inside the famous ruin bar Szimpla Kert on Sunday mornings, featuring fresh cheeses, honeys, and homemade delicacies.",
        "imageUrl": "https://images.unsplash.com/photo-1543083477-4f7f44aad226?w=800",
        "bestTime": "Pazar sabahı",
        "bestTime_en": "Sunday morning",
        "tips": "Pazarda yapılan ortak kahvaltılara (brunch) katılabilirsiniz.",
        "tips_en": "You can join the communal breakfasts (brunch) held during the market."
    },
    {
        "name": "Deryne",
        "name_en": "Deryne",
        "area": "Buda",
        "category": "Restoran",
        "tags": ["bistro", "şık", "kahvaltı", "ikonik"],
        "distanceFromCenter": 1.2,
        "lat": 47.4983,
        "lng": 19.0322,
        "price": "high",
        "rating": 4.7,
        "description": "Buda yakasının en şık ve ikonik bistrosu. 1914'ten beri hizmet veren bu mekan, mükemmel kahvaltısı ve kozmopolit havasıyla bilinir.",
        "description_en": "The most elegant and iconic bistro on the Buda side. Serving since 1914, it's known for its excellent breakfast and cosmopolitan vibe.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Kahvaltı veya Hafta sonu brunch",
        "bestTime_en": "Breakfast or Weekend brunch",
        "tips": "Hafta sonları canlı piyano müziği eşliğinde kahvaltı yapabilirsiniz.",
        "tips_en": "You can enjoy breakfast accompanied by live piano music on weekends."
    },
    {
        "name": "Gozsdu Udvar",
        "name_en": "Gozsdu Courtyard",
        "area": "Yahudi Mahallesi",
        "category": "Deneyim",
        "tags": ["pasaj", "eğlence", "gece hayatı", "restoranlar"],
        "distanceFromCenter": 0.5,
        "lat": 47.4993,
        "lng": 19.0587,
        "price": "medium",
        "rating": 4.6,
        "description": "Altı adet binanın birbirine bağlanan yedi avlusundan oluşan dev pasaj. Şehrin en canlı yeme-içme ve eğlence merkezlerinden biridir.",
        "description_en": "A massive passage consisting of seven interconnected courtyards across six buildings. It's one of the city's liveliest dining and entertainment hubs.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Hafta sonları burada antika ve tasarım pazarları da kurulur.",
        "tips_en": "Antique and design markets are also held here on weekends."
    },
    {
        "name": "Váci utca",
        "name_en": "Vaci Street",
        "area": "Pest",
        "category": "Alışveriş",
        "tags": ["alışveriş", "cadde", "hediyelik", "canlı"],
        "distanceFromCenter": 0.2,
        "lat": 47.4899,
        "lng": 19.0515,
        "price": "medium",
        "rating": 4.4,
        "description": "Budapeşte'nin en ünlü alışveriş caddesi. Tarihi binalar arasından geçen bu yaya yolu, ünlü markalara ve hediyelik eşya dükkanlarına ev sahipliği yapar.",
        "description_en": "Budapest's most famous shopping street. This pedestrian walkway passing between historic buildings houses major brands and souvenir shops.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Caddenin güney ucu Merkez Pazar'a (Büyük Pazar) çıkar.",
        "tips_en": "The southern end of the street leads to the Central Market Hall."
    },
    {
        "name": "Stand25 Bisztró",
        "name_en": "Stand25 Bistro",
        "area": "Buda",
        "category": "Restoran",
        "tags": ["modern macar", "gurme", "michelin rehberi", "bistro"],
        "distanceFromCenter": 1.5,
        "lat": 47.4878,
        "lng": 19.0578,
        "price": "high",
        "rating": 4.8,
        "description": "Geleneksel Macar mutfağını modern ve rafine bir dokunuşla sunan, Michelin Bib Gourmand ödüllü çok popüler bir bistro.",
        "description_en": "A very popular Michelin Bib Gourmand-awarded bistro serving traditional Hungarian cuisine with a modern and refined touch.",
        "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Meşhur Macar patates güvecini (Rakott Krumpli) burada mutlaka denemelisiniz.",
        "tips_en": "You must try the famous Hungarian layered potatoes (Rakott Krumpli) here."
    },
    {
        "name": "Telep Art Bar",
        "name_en": "Telep Art Bar",
        "area": "Yahudi Mahallesi",
        "category": "Bar",
        "tags": ["sanat", "alternatif", "lokal", "kaykay"],
        "distanceFromCenter": 0.6,
        "lat": 47.4994,
        "lng": 19.0583,
        "price": "low",
        "rating": 4.6,
        "description": "Sanat galerisi, kaykay dükkanı ve barın bir araya geldiği, şehrin yaratıcı gençlerinin favori buluşma noktası.",
        "description_en": "A mix of art gallery, skate shop, and bar, and a favorite meeting point for the city's creative youth.",
        "imageUrl": "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800",
        "bestTime": "Akşamüstü",
        "bestTime_en": "Late afternoon",
        "tips": "Dışarıdaki basamaklarda oturup sokağın enerjisini hissetmek çok keyiflidir.",
        "tips_en": "It's very pleasant to sit on the outside steps and soak in the street's energy."
    },
    {
        "name": "Csendes Létterem",
        "name_en": "Csendes Letterem",
        "area": "Pest",
        "category": "Bar",
        "tags": ["vintage", "bohem", "ruin bar tarzı", "kafe"],
        "distanceFromCenter": 0.5,
        "lat": 47.4925,
        "lng": 19.0600,
        "price": "low",
        "rating": 4.7,
        "description": "Eski bir sarayın kalıntılarında yer alan, tavanından sarkan oyuncak bebekler ve vintage eşyalarla dolu büyüleyici bir bohem bar/kafe.",
        "description_en": "A charming bohemian bar/cafe located in the ruins of an old palace, filled with vintage items and dolls hanging from the ceiling.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "İçerideki sürreal dekorasyonu incelemek için bolca vaktiniz olsun.",
        "tips_en": "Make sure you have plenty of time to examine the surreal decoration inside."
    },
    {
        "name": "Hospital in the Rock (Sziklakórház)",
        "name_en": "Hospital in the Rock",
        "area": "Buda",
        "category": "Müze",
        "tags": ["tarih", "savaş", "sığınak", "buda"],
        "distanceFromCenter": 1.2,
        "lat": 47.5008,
        "lng": 19.0315,
        "price": "medium",
        "rating": 4.8,
        "description": "2. Dünya Savaşı ve 1956 Devrimi sırasında kullanılan gizli bir yeraltı hastanesi ve nükleer sığınak.",
        "description_en": "A secret underground hospital and nuclear bunker used during WWII and the 1956 Revolution.",
        "imageUrl": "https://images.unsplash.com/photo-1590429408077-440232231f42?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sadece rehberli turlarla gezilebilir, içeride orijinal tıbbi ekipmanlar ve bal mumu heykeller bulunur.",
        "tips_en": "Can only be visited via guided tours; contains original medical equipment and wax figures."
    },
    {
        "name": "Boutiq' Bar",
        "name_en": "Boutiq' Bar",
        "area": "Pest",
        "category": "Bar",
        "tags": ["kokteyl", "miksoloji", "ödüllü", "şık"],
        "distanceFromCenter": 0.7,
        "lat": 47.4994,
        "lng": 19.0575,
        "price": "high",
        "rating": 4.8,
        "description": "Budapeşte'nin en iyi kokteyl barlarından biri. Dünyanın en iyi barları listesine girmiş, sıra dışı sunumları ve uzman miksolojistleriyle ünlü.",
        "description_en": "One of Budapest's best cocktail bars, featured on world's best bars lists and known for extraordinary presentations and expert mixologists.",
        "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Menü dışı içecekler isteyebilir veya barmene damak tadınızı söyleyebilirsiniz.",
        "tips_en": "You can request off-menu drinks or tell the bartender your taste preferences."
    },
    {
        "name": "Budapest Eye",
        "name_en": "Budapest Eye",
        "area": "Deák Ferenc tér",
        "category": "Manzara",
        "tags": ["dönme dolap", "meydan", "eğlence", "manzara"],
        "distanceFromCenter": 0.2,
        "lat": 47.4983,
        "lng": 19.0553,
        "price": "medium",
        "rating": 4.4,
        "description": "Erzsébet Meydanı'nda bulunan dev dönme dolap. Şehri Pest yakasının kalbinden yukarıdan izlemek için harika bir nokta.",
        "description_en": "The giant Ferris wheel in Erzsébet Square. A great spot to view the city from above in the heart of the Pest side.",
        "imageUrl": "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800",
        "bestTime": "Gece",
        "bestTime_en": "Night",
        "tips": "Gece bindiğinizde şehrin ışıklandırılmış silueti çok daha etkileyici görünür.",
        "tips_en": "The city's illuminated skyline looks much more impressive when you ride it at night."
    },
    {
        "name": "Millenáris Park",
        "name_en": "Millenaris Park",
        "area": "Buda",
        "category": "Park",
        "tags": ["modern", "kültür", "etkinlik", "göl"],
        "distanceFromCenter": 2.2,
        "lat": 47.5111,
        "lng": 19.0269,
        "price": "free",
        "rating": 4.7,
        "description": "Eski bir fabrikanın dönüştürülmesiyle oluşturulmuş modern ve yeşil bir kültür alanı. Sergiler, festivaller ve dinlenme alanlarıyla doludur.",
        "description_en": "A modern, green cultural space created from a converted factory, filled with exhibitions, festivals, and relaxation areas.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İçindeki 'Görünmez Sergi' (Invisible Exhibition) deneyimini mutlaka yaşayın.",
        "tips_en": "Be sure to experience the 'Invisible Exhibition' located here."
    },
    {
        "name": "Kelet Kávézó",
        "name_en": "Kelet Cafe",
        "area": "Buda",
        "category": "Kafe",
        "tags": ["kitap kafe", "bohem", "sessiz", "lokal"],
        "distanceFromCenter": 1.8,
        "lat": 47.4783,
        "lng": 19.0522,
        "price": "low",
        "rating": 4.8,
        "description": "Binlerce kitabın çevrelediği, Bartók Béla Bulvarı üzerinde yer alan huzurlu ve entelektüel bir kitap kafe.",
        "description_en": "A peaceful and intellectual book cafe surrounded by thousands of books, located on Bartók Béla Boulevard.",
        "imageUrl": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "bestTime": "Öğleden sonra",
        "bestTime_en": "Afternoon",
        "tips": "Buradaki kitapların çoğu ikinci eldir ve takas edilebilir.",
        "tips_en": "Most of the books here are second-hand and can be swapped."
    },
    {
        "name": "Nanushka Store & Cafe",
        "name_en": "Nanushka Store & Cafe",
        "area": "Pest",
        "category": "Deneyim",
        "tags": ["moda", "tasarım", "lüks", "kafe"],
        "distanceFromCenter": 0.3,
        "lat": 47.4917,
        "lng": 19.0511,
        "price": "high",
        "rating": 4.7,
        "description": "Dünyaca ünlü Macar moda markası Nanushka'nın hem mağaza hem de şık bir kafe olarak hizmet veren nefes kesen amiral gemisi.",
        "description_en": "The breathtaking flagship store of world-renowned Hungarian fashion brand Nanushka, which also serves as a chic cafe.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "İç mimarisi ve estetiğiyle Paris binalarını andıran çok fotojenik bir mekandır.",
        "tips_en": "A very photogenic spot with interior design and aesthetics reminiscent of Paris buildings."
    },
    {
        "name": "Doblo Wine Bar",
        "name_en": "Doblo Wine Bar",
        "area": "Yahudi Mahallesi",
        "category": "Bar",
        "tags": ["şarap", "tadım", "tuğla duvarlar", "otantik"],
        "distanceFromCenter": 0.6,
        "lat": 47.4994,
        "lng": 19.0617,
        "price": "medium",
        "rating": 4.7,
        "description": "Tuğla duvarları ve loş ışıklarıyla çok samimi bir şarap barı. Macar şaraplarını keşfetmek için harika tadım menüleri sunar.",
        "description_en": "An intimate wine bar with brick walls and dim lighting, offering excellent tasting menus to explore Hungarian wines.",
        "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
        "bestTime": "Akşam",
        "bestTime_en": "Evening",
        "tips": "Macaristan'ın meşhur Tokaji tatlı şaraplarını burada dileyebilirsiniz.",
        "tips_en": "You can sample Hungary's famous Tokaji dessert wines here."
    },
    {
        "name": "Paloma Budapest",
        "name_en": "Paloma Budapest",
        "area": "Pest",
        "category": "Deneyim",
        "tags": ["tasarım", "yerel sanatçı", "avlu", "gizli"],
        "distanceFromCenter": 0.6,
        "lat": 47.4939,
        "lng": 19.0600,
        "price": "medium",
        "rating": 4.6,
        "description": "Tarihi bir avlu içinde yer alan, yerel tasarımcıların atölye ve dükkanlarının toplandığı gizli bir yaratıcılık merkezi.",
        "description_en": "A hidden creativity hub in a historic courtyard, gathering local designers' workshops and shops.",
        "imageUrl": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
        "bestTime": "Gündüz",
        "bestTime_en": "Daytime",
        "tips": "Sıradan hediyelikler yerine buradan benzersiz el yapımı ürünler alabilirsiniz.",
        "tips_en": "Instead of ordinary souvenirs, you can buy unique handmade products here."
    },
    {
        "name": "Kopaszi dam (Kopaszi-gát)",
        "name_en": "Kopaszi dam",
        "area": "Güney Buda",
        "category": "Park",
        "tags": ["nehir", "modern", "park", "huzur"],
        "distanceFromCenter": 4.5,
        "lat": 47.4583,
        "lng": 19.0611,
        "price": "free",
        "rating": 4.8,
        "description": "Tuna kıyısında modern bir şekilde düzenlenmiş, kafeleri, restoranları ve geniş çimenleriyle şehrin en huzurlu dinlenme noktalarından biri.",
        "description_en": "A modern riverside area with cafes, restaurants, and wide lawns, making it one of the city's most peaceful relaxation spots.",
        "imageUrl": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
        "bestTime": "Bahar veya Yaz",
        "bestTime_en": "Spring or Summer",
        "tips": "Şehrin gürültüsünden tamamen uzaklaşıp nehir havası almak için idealdir.",
        "tips_en": "Ideal for escaping city noise completely and getting some fresh river air."
    }
]

def enrich_budapest_batch3():
    filepath = 'assets/cities/budapeste.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'] for h in data.get('highlights', []))
    for new_h in new_budapest_batch3:
        if new_h['name'] not in existing_names:
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_budapest_batch3()
print(f"Budapest now has {count} highlights.")
