import json
import os

new_madrid_batch2 = [
    {
        "name": "Plaza de España",
        "name_en": "Plaza de Espana",
        "area": "Centro/Argüelles",
        "category": "Tarihi",
        "tags": ["cervantes", "heykel", "gökdelen", "meydan"],
        "distanceFromCenter": 1.0,
        "lat": 40.4234,
        "lng": -3.7122,
        "price": "free",
        "rating": 4.6,
        "description": "Don Kişot'un yazarı Miguel de Cervantes anısına yapılmış devasa heykeli barındıran, kentin en büyük ve önemli meydanlarından biri.",
        "description_en": "A key square in central Madrid, home to a prominent monument honoring Miguel de Cervantes, featuring bronze statues of Don Quixote and Sancho Panza."
    },
    {
        "name": "Jardines de Sabatini",
        "name_en": "Sabatini Gardens",
        "area": "Palacio",
        "category": "Park",
        "tags": ["saray", "bahçe", "gün batımı", "labirent"],
        "distanceFromCenter": 0.8,
        "lat": 40.4202,
        "lng": -3.7139,
        "price": "free",
        "rating": 4.7,
        "description": "Kraliyet Sarayı'nın hemen yanındaki, labirent benzeri çalıları ve heykelleriyle ünlü, Madrid'in en zarif bahçelerinden biri.",
        "description_en": "Neoclassical gardens part of the Royal Palace, known for their perfectly manicured hedges and statues, offering a serene escape in the heart of the city."
    },
    {
        "name": "Mercado de Motores",
        "name_en": "Mercado de Motores",
        "area": "Arganzuela",
        "category": "Deneyim",
        "tags": ["bit pazarı", "vintage", "tren müzesi", "lokal"],
        "distanceFromCenter": 2.0,
        "lat": 40.3985,
        "lng": -3.6925,
        "price": "free",
        "rating": 4.8,
        "description": "Eski bir tren müzesinde (Museo del Ferrocarril) kurulan, antikalardan el yapımı ürünlere kadar her şeyi bulabileceğiniz eşsiz bir pazar.",
        "description_en": "A unique monthly market held inside an old railway museum, where stalls are nestled between vintage trains, selling antiques, clothes, and gourmet food."
    },
    {
        "name": "Casa de Campo",
        "name_en": "Casa de Campo",
        "area": "Batı Madrid",
        "category": "Park",
        "tags": ["doğa", "göl", "teleferik", "aktivite"],
        "distanceFromCenter": 3.0,
        "lat": 40.4229,
        "lng": -3.7560,
        "price": "free",
        "rating": 4.7,
        "description": "New York Central Park'tan beş kat büyük olan Madrid'in en geniş parkı. İçinde bir göl, hayvanat bahçesi ve lunapark barındırır.",
        "description_en": "Madrid's largest public park, formerly a royal hunting ground. It features a large lake, the city zoo, and an amusement park, all accessible by cable car."
    },
    {
        "name": "Teatro Real",
        "name_en": "Royal Theatre",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["opera", "sanat", "müzik", "saray"],
        "distanceFromCenter": 0.5,
        "lat": 40.4182,
        "lng": -3.7106,
        "price": "high",
        "rating": 4.8,
        "description": "Kraliyet Sarayı'nın hemen karşısında bulunan, dünyanın en iyi opera sahnelerinden biri kabul edilen tarihi yapı.",
        "description_en": "One of the world's finest opera houses, located directly opposite the Royal Palace, known for its superb acoustics and opulent interiors."
    },
    {
        "name": "San Ginés (Eski Pasaj)",
        "name_en": "San Gines Passageway",
        "area": "Centro",
        "category": "Deneyim",
        "tags": ["kitap", "tarihi", "gizli", "pasaj"],
        "distanceFromCenter": 0.2,
        "lat": 40.4172,
        "lng": -3.7070,
        "price": "free",
        "rating": 4.6,
        "description": "Meşhur çikolatacı San Ginés'in hemen yanındaki dar sokakta yer alan, tarihi kitapçı tezgahlarıyla ünlü büyüleyici bir geçit.",
        "description_en": "A narrow, atmospheric passageway home to a historic outdoor second-hand book stall that has been a Madrid staple for over a century."
    },
    {
        "name": "Museo Sorolla",
        "name_en": "Sorolla Museum",
        "area": "Chamberí",
        "category": "Müze",
        "tags": ["ressam", "bahçe", "sanat", "ev müze"],
        "distanceFromCenter": 2.2,
        "lat": 40.4354,
        "lng": -3.6925,
        "price": "low",
        "rating": 4.9,
        "description": "İspanyol ressam Joaquín Sorolla'nın eski evi ve atölyesi. Eserleri kadar şık bahçesiyle de huzur veren bir müze.",
        "description_en": "The former home and studio of the 'painter of light,' Joaquín Sorolla. It houses many of his masterpieces and features a stunning Andalusian-style garden."
    },
    {
        "name": "Plaza de Oriente",
        "name_en": "Plaza de Oriente",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["heykel", "saray", "meydan", "teras"],
        "distanceFromCenter": 0.6,
        "lat": 40.4178,
        "lng": -3.7131,
        "price": "free",
        "rating": 4.7,
        "description": "Kraliyet Sarayı ile Teatro Real arasında yer alan, Gotik İspanyol krallarının heykelleriyle süslenmiş görkemli meydan.",
        "description_en": "A monumental square fronting the Royal Palace, flanked by the Royal Theatre and filled with statues of early Spanish monarchs."
    },
    {
        "name": "Cava Baja (Tapas Sokağı)",
        "name_en": "Cava Baja Tapas Street",
        "area": "La Latina",
        "category": "Deneyim",
        "tags": ["tapas", "bar", "gastronomi", "tarihi sokağı"],
        "distanceFromCenter": 0.7,
        "lat": 40.4111,
        "lng": -3.7118,
        "price": "medium",
        "rating": 4.8,
        "description": "Madrid'in en ünlü tapas sokağı. Rengarenk binaları ve yan yana dizilmiş onlarca geleneksel barıyla akşamları kentin kalbi burada atar.",
        "description_en": "The most famous 'tapas' street in Madrid. Lined with dozens of traditional bars and restaurants, it's the epicenter of the city's social life."
    },
    {
        "name": "Faro de Moncloa",
        "name_en": "Moncloa Lighthouse",
        "area": "Moncloa",
        "category": "Manzara",
        "tags": ["kule", "panoramik", "modern", "gözlem"],
        "distanceFromCenter": 2.5,
        "lat": 40.4356,
        "lng": -3.7198,
        "price": "low",
        "rating": 4.5,
        "description": "92 metre yükseklikteki bu modern kule, Madrid'in kuzeyine ve Guadarrama dağlarına uzanan eşsiz bir panoramik manzara sunar.",
        "description_en": "A 92-meter high transmission tower with a panoramic observation deck offering spectacular views of central Madrid and the Sierra de Guadarrama mountains."
    },
    {
        "name": "Malasaña (Barrio)",
        "name_en": "Malasana District",
        "area": "Malasaña",
        "category": "Deneyim",
        "tags": ["hipster", "grafiti", "gece hayatı", "kafe"],
        "distanceFromCenter": 1.0,
        "lat": 40.4269,
        "lng": -3.7041,
        "price": "medium",
        "rating": 4.7,
        "description": "Kentin 'hipster' kalbi. 80'lerin 'La Movida' hareketinin merkezi olan bu bölge, şık kafeler, vintage mağazalar ve butik barlarla dolu.",
        "description_en": "The spiritual home of the 'La Movida' counterculture movement, now Madrid's trendiest neighborhood with indie boutiques and lively plazas."
    },
    {
        "name": "Mercado de San Antón",
        "name_en": "San Anton Market",
        "area": "Chueca",
        "category": "Deneyim",
        "tags": ["market", "gurme", "rooftop", "tapas"],
        "distanceFromCenter": 0.8,
        "lat": 40.4221,
        "lng": -3.6975,
        "price": "medium",
        "rating": 4.6,
        "description": "Modern bir gurme pazarı. Üst katındaki açık hava terası ve taze ürünlerden yapılan tapaslarıyla Chueca'nın en popüler noktası.",
        "description_en": "A stylish three-story gourmet market in Chueca, featuring food stalls, art galleries, and a famous rooftop terrace."
    },
    {
        "name": "Chueca (Barrio)",
        "name_en": "Chueca District",
        "area": "Chueca",
        "category": "Deneyim",
        "tags": ["renkli", "bar", "moda", "kozmopolit"],
        "distanceFromCenter": 0.9,
        "lat": 40.4228,
        "lng": -3.6994,
        "price": "medium",
        "rating": 4.8,
        "description": "Madrid'in en renkli ve hoşgörülü bölgesi. Harika restoranları, barları ve butik mağazalarıyla kentin en canlı noktalarından biridir.",
        "description_en": "A vibrant and inclusive neighborhood known for its high-energy nightlife, trendy shops, and some of the city's most innovative restaurants."
    },
    {
        "name": "Basílica de San Francisco el Grande",
        "name_en": "San Francisco el Grande Basilica",
        "area": "La Latina",
        "category": "Tarihi",
        "tags": ["kubbe", "sanat", "mimar", "goya"],
        "distanceFromCenter": 1.2,
        "lat": 40.4103,
        "lng": -3.7145,
        "price": "low",
        "rating": 4.7,
        "description": "Dünyanın en büyük dördüncü kubbesine sahip olan, Goya ve Zurbarán gibi ustaların tablolarını barındıran muazzam bir bazilika.",
        "description_en": "A 18th-century neoclassical church boasting one of the largest domes in Christendom and a stunning interior gallery featuring Goya paintings."
    },
    {
        "name": "Calle de Serrano",
        "name_en": "Serrano Street",
        "area": "Salamanca",
        "category": "Alışveriş",
        "tags": ["lüks", "moda", "tasarım", "şıklık"],
        "distanceFromCenter": 1.5,
        "lat": 40.4300,
        "lng": -3.6875,
        "price": "high",
        "rating": 4.6,
        "description": "Madrid'in 'Altın Mil'i olarak bilinen, dünyanın en lüks markalarının ve şık binalarının bulunduğu ana alışveriş caddesi.",
        "description_en": "The spine of the upscale Salamanca district, home to high-end international fashion houses and elegant Spanish department stores."
    },
    {
        "name": "Barrio de las Letras (Edebiyat Bölgesi)",
        "name_en": "Literary District",
        "area": "Huertas",
        "category": "Tarihi",
        "tags": ["edebiyat", "sokak sanatı", "huertas", "tarihi"],
        "distanceFromCenter": 0.6,
        "lat": 40.4140,
        "lng": -3.6990,
        "price": "free",
        "rating": 4.8,
        "description": "Cervantes ve Lope de Vega gibi yazarların yaşadığı, sokaklara altın harflerle edebi metinlerin yazıldığı büyüleyici bir mahalle.",
        "description_en": "A charming neighborhood once home to the greats of Spain's Golden Age of literature, with famous quotes embedded in the cobblestone streets."
    },
    {
        "name": "Monasterio de las Descalzas Reales",
        "name_en": "Monastery of Descalzas Reales",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["manastır", "sanat", "sessiz", "saray"],
        "distanceFromCenter": 0.3,
        "lat": 40.4185,
        "lng": -3.7058,
        "price": "medium",
        "rating": 4.7,
        "description": "Madrid'in kalbinde saklı, içi paha biçilemez sanat eserleri ve duvar halılarıyla dolu eski bir kraliyet sarayı ve manastır.",
        "description_en": "A 16th-century former palace turned royal monastery, hiding an incredible collection of tapestries and Renaissance religious art."
    },
    {
        "name": "Parque del Oeste",
        "name_en": "Oeste Park",
        "area": "Moncloa",
        "category": "Park",
        "tags": ["gül bahçesi", "manzara", "doğa", "yürüyüş"],
        "distanceFromCenter": 2.0,
        "lat": 40.4320,
        "lng": -3.7225,
        "price": "free",
        "rating": 4.6,
        "description": "İçinde muazzam bir gül bahçesi ('La Rosaleda') ve Temple of Debod'u barındıran, kentin kuzeybatısındaki geniş ve yeşil park.",
        "description_en": "A sprawling park on the western edge of the city, famous for its grand Egyptian temple, lush rose gardens, and views over the Casa de Campo."
    },
    {
        "name": "Mercado de la Paz",
        "name_en": "La Paz Market",
        "area": "Salamanca",
        "category": "Deneyim",
        "tags": ["market", "tortilla", "gurme", "geleneksel"],
        "distanceFromCenter": 1.7,
        "lat": 40.4284,
        "lng": -3.6845,
        "price": "medium",
        "rating": 4.8,
        "description": "Salamanca mahallesinde yer alan, Madrid'in en iyi tortillalarından birine ev sahipliği yapan şık ve geleneksel bir pazar yeri.",
        "description_en": "An elegant, century-old neighborhood market in Salamanca, best known for Casa Dani, often cited as the place for the best tortilla in Spain."
    },
    {
        "name": "Museo Thyssen-Bornemisza",
        "name_en": "Thyssen-Bornemisza Museum",
        "area": "Huertas/Centro",
        "category": "Müze",
        "tags": ["sanat", "resim", "ustalar", "koleksiyon"],
        "distanceFromCenter": 0.6,
        "lat": 40.4160,
        "lng": -3.6949,
        "price": "medium",
        "rating": 4.8,
        "description": "Madrid'in 'Altın Sanat Üçgeni'nin bir parçası olan, 13. yüzyıldan modern döneme kadar uzanan muazzam bir resim koleksiyonu.",
        "description_en": "Compiling the 'Golden Triangle of Art', it houses an extraordinary private collection spanning eight centuries of European painting."
    },
    {
        "name": "CaixaForum Madrid",
        "name_en": "CaixaForum Madrid",
        "area": "Huertas",
        "category": "Deneyim",
        "tags": ["modern mimari", "dikey bahçe", "sanat", "tasarım"],
        "distanceFromCenter": 0.8,
        "lat": 40.4111,
        "lng": -3.6933,
        "price": "low",
        "rating": 4.8,
        "description": "Asılı duran binası ve devasa dikey bahçesiyle ünlü, eski bir elektrik santralinden dönüştürülmüş etkileyici sanat ve kültür merkezi.",
        "description_en": "A powerhouse of contemporary culture, famous for its 'hanging' structure and the massive vertical garden that covers one of its exterior walls."
    },
    {
        "name": "Teleférico de Madrid",
        "name_en": "Madrid Cable Car",
        "area": "Moncloa",
        "category": "Manzara",
        "tags": ["teleferik", "manzara", "park", "havadan"],
        "distanceFromCenter": 2.2,
        "lat": 40.4288,
        "lng": -3.7258,
        "price": "medium",
        "rating": 4.4,
        "description": "Rosales'ten Casa de Campo'ya uzanan, kenti ve sarayı bambaşka bir açıdan görmenizi sağlayan nostaljik teleferik yolculuğu.",
        "description_en": "Take a 10-minute flight above the Manzanares River and Casa de Campo for breathtaking aerial views of the Royal Palace and the Madrid skyline."
    },
    {
        "name": "Plaza de la Villa",
        "name_en": "Plaza de la Villa",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["ortaçağ", "mimari", "eski belediye", "tarih"],
        "distanceFromCenter": 0.4,
        "lat": 40.4150,
        "lng": -3.7118,
        "price": "free",
        "rating": 4.7,
        "description": "Madrid'in ortaçağ dokusunu en iyi koruyan meydanı. 15. yüzyıldan kalma binaları ve eski belediye binasıyla tam bir tarih yolculuğu.",
        "description_en": "A picturesque square that takes you back to medieval Madrid, featuring the oldest municipal building in the city and beautiful brick facades."
    },
    {
        "name": "Museo Lázaro Galdiano",
        "name_en": "Lazaro Galdiano Museum",
        "area": "Salamanca",
        "category": "Müze",
        "tags": ["sanat", "saray", "koleksiyon", "goya"],
        "distanceFromCenter": 2.5,
        "lat": 40.4361,
        "lng": -3.6853,
        "price": "medium",
        "rating": 4.7,
        "description": "Şık bir malikane içinde yer alan, nadide takılardan Goya tablolarına kadar binlerce eserin sergilendiği gizli bir sanat hazinesi.",
        "description_en": "A hidden gem set in a stately mansion, showcasing the eclectic private collection of José Lázaro Galdiano, including works by Goya and Bosch."
    },
    {
        "name": "Huertas (Gece Hayatı)",
        "name_en": "Huertas Nightlife",
        "area": "Huertas",
        "category": "Deneyim",
        "tags": ["gece hayatı", "müzik", "bar", "eğlence"],
        "distanceFromCenter": 0.5,
        "lat": 40.4130,
        "lng": -3.6980,
        "price": "medium",
        "rating": 4.6,
        "description": "Madrid'in en canlı gece hayatı bölgelerinden biri. Plaza de Santa Ana çevresindeki barları ve caz kulüpleriyle ünlüdür.",
        "description_en": "The nightlife hub of central Madrid, centered around Huertas street, where classic pubs, jazz clubs, and tapas bars stay open until the early hours."
    },
    {
        "name": "Museo Cerralbo",
        "name_en": "Cerralbo Museum",
        "area": "Moncloa",
        "category": "Müze",
        "tags": ["saray", "lüks", "tarihi", "dekorasyon"],
        "distanceFromCenter": 1.1,
        "lat": 40.4241,
        "lng": -3.7145,
        "price": "low",
        "rating": 4.8,
        "description": "19. yüzyıl bir İspanyol aristokratının yaşadığı, orijinal eşyaları ve lüks dekorasyonuyla korunmuş büyüleyici bir saray-müze.",
        "description_en": "A rare example of a 19th-century private mansion perfectly preserved with its original furnishings, art, and an incredibly ornate ballroom."
    },
    {
        "name": "Plaza de Santa Ana",
        "name_en": "Plaza de Santa Ana",
        "area": "Huertas",
        "category": "Manzara",
        "tags": ["meydan", "teras", "sosyalleşme", "heykel"],
        "distanceFromCenter": 0.5,
        "lat": 40.4145,
        "lng": -3.7011,
        "price": "free",
        "rating": 4.7,
        "description": "Huertas'ın kalbinde, tiyatrolar, şık kafeler ve Federico García Lorca heykeliyle çevrili kentin en sosyal meydanlarından biri.",
        "description_en": "A hub of social life surrounded by cafes, restaurants, and the historic Teatro Español, known for its sunny terraces and literary street atmosphere."
    },
    {
        "name": "Museo del Ferrocarril",
        "name_en": "Railway Museum",
        "area": "Arganzuela",
        "category": "Müze",
        "tags": ["tren", "tarih", "nostalji", "istasyon"],
        "distanceFromCenter": 2.2,
        "lat": 40.3985,
        "lng": -3.6925,
        "price": "medium",
        "rating": 4.6,
        "description": "Eski bir tren istasyonunun içinde, buharlı lokomotiflerden eski vagonlara kadar raylı ulaşım tarihini keşfedebileceğiniz nostaljik bir yer.",
        "description_en": "Housed in the beautiful former Delicias station, this museum features a vast collection of historic locomotives and vintage railway cars."
    },
    {
        "name": "Calle Ponzano (Foodie Sokağı)",
        "name_en": "Calle Ponzano Foodie Street",
        "area": "Chamberí",
        "category": "Deneyim",
        "tags": ["gurme", "bar", "lokal", "tapas"],
        "distanceFromCenter": 2.5,
        "lat": 40.4410,
        "lng": -3.7020,
        "price": "medium",
        "rating": 4.8,
        "description": "Madridli gurmelerin yeni favorisi. Yan yana dizilmiş yenilikçi barları ve modern meyhaneleriyle 'ponzaning' akımının merkezi.",
        "description_en": "The epicenter of Madrid's modern gourmet scene. This street is legendary for its 'ponzaning' culture—hopping between its many stylish tapas bars."
    },
    {
        "name": "Real Academia de Bellas Artes",
        "name_en": "San Fernando Royal Academy of Fine Arts",
        "area": "Centro",
        "category": "Müze",
        "tags": ["sanat", "resim", "akademi", "tarihi"],
        "distanceFromCenter": 0.3,
        "lat": 40.4180,
        "lng": -3.7000,
        "price": "medium",
        "rating": 4.7,
        "description": "Picasso ve Dalí gibi isimlerin eğitim gördüğü, Goya'nın en önemli eserlerinden bazılarını barındıran tarihi sanat akademisi müzesi.",
        "description_en": "A prestigious art institution and gallery where masters once studied, housing significant works by Goya, Zurbarán, and Velázquez."
    },
    {
        "name": "El Retiro (Göl)",
        "name_en": "Retiro Park Boating Lake",
        "area": "Retiro",
        "category": "Manzara",
        "tags": ["göl", "sandal", "romantik", "park"],
        "distanceFromCenter": 1.2,
        "lat": 40.4168,
        "lng": -3.6840,
        "price": "low",
        "rating": 4.8,
        "description": "Retiro Parkı'nın kalbinde, Alfonso XII anıtının önünde sandal sefası yapabileceğiniz Madrid'in en huzurlu ve ikonik noktası.",
        "description_en": "Rent a traditional rowboat and glide across the crystal-blue waters of Retiro's central lake, overlooked by the grand Alfonso XII monument."
    },
    {
        "name": "Calle Mayor",
        "name_en": "Calle Mayor",
        "area": "Centro",
        "category": "Tarihi",
        "tags": ["cadde", "mimari", "merkezi", "yürüyüş"],
        "distanceFromCenter": 0.3,
        "lat": 40.4158,
        "lng": -3.7088,
        "price": "free",
        "rating": 4.6,
        "description": "Puerta del Sol ile Kraliyet Sarayı'nı birbirine bağlayan, tarihi binalar ve asırlık dükkanlarla dolu kentin ana damarlarından biri.",
        "description_en": "One of the oldest and most atmospheric streets in Madrid, connecting the city’s major squares and lined with historic architecture and shops."
    },
    {
        "name": "Sobrino de Botín",
        "name_en": "Sobrino de Botin",
        "area": "Centro",
        "category": "Restoran",
        "tags": ["dünyanın en eskisi", "tarihi", "yemek", "guinness"],
        "distanceFromCenter": 0.4,
        "lat": 40.4142,
        "lng": -3.7080,
        "price": "high",
        "rating": 4.7,
        "description": "1725 yılından beri hiç kapanmadan hizmet veren, Guinness rekorlar kitabına göre dünyanın en eski restoranı.",
        "description_en": "Opened in 1725, this is the oldest continuously operating restaurant in the world, famous for its roasted suckling pig and wood-fired oven."
    },
    {
        "name": "Puerta de Alcalá",
        "name_en": "Puerta de Alcala",
        "area": "Retiro",
        "category": "Tarihi",
        "tags": ["kapı", "anıt", "ikonik", "meydan"],
        "distanceFromCenter": 0.9,
        "lat": 40.4190,
        "lng": -3.6888,
        "price": "free",
        "rating": 4.7,
        "description": "Retiro Parkı'nın hemen girişinde yer alan, Madrid'in en önemli simgelerinden biri olan görkemli zafer takı.",
        "description_en": "A monumental triumphal gate in the Plaza de la Independencia; it was once one of the five main gates of the city and remains a symbol of Madrid."
    },
    {
        "name": "Manzanares Riverside (Madrid Río)",
        "name_en": "Madrid Rio Park",
        "area": "Arganzuela",
        "category": "Park",
        "tags": ["nehir", "bisiklet", "modern", "aktivite"],
        "distanceFromCenter": 2.0,
        "lat": 40.4020,
        "lng": -3.7220,
        "price": "free",
        "rating": 4.7,
        "description": "Nehir boyunca uzanan devasa rekreasyon alanı. Modern köprüleri, yürüyüş yolları ve parklarıyla kentin en iyi açık hava aktivite noktası.",
        "description_en": "A massive urban transformation project that turned a highway into a lush riverside park with cycling tracks, modern bridges, and play areas."
    },
    {
        "name": "Cuartel del Conde Duque",
        "name_en": "Conde Duque Cultural Center",
        "area": "Centro/Malasaña",
        "category": "Deneyim",
        "tags": ["kültür", "sanat", "tarihi Bina", "etkinlik"],
        "distanceFromCenter": 1.2,
        "lat": 40.4284,
        "lng": -3.7105,
        "price": "low",
        "rating": 4.6,
        "description": "Eski bir süvari kışlasının büyüleyici bir sanat ve kültür merkezine dönüştürüldüğü, kütüphane ve konser alanlarını barındıran yapı.",
        "description_en": "A vast 18th-century former barracks now serving as a major municipal cultural center hosting festivals, art exhibitions, and open-air concerts."
    },
    {
        "name": "Palacio de Velázquez (Retiro)",
        "name_en": "Velazquez Palace",
        "area": "Retiro",
        "category": "Müze",
        "tags": ["sanat", "sergi", "park", "mimari"],
        "distanceFromCenter": 1.5,
        "lat": 40.4150,
        "lng": -3.6828,
        "price": "free",
        "rating": 4.7,
        "description": "Retiro Parkı içindeki bu zarif bina, modern sanat sergilerine ev sahipliği yapan ve girişi ücretsiz olan büyüleyici bir galeridir.",
        "description_en": "A beautiful 1880s brick-and-tile palace in Retiro Park, now an annex of the Reina Sofía Museum hosting temporary contemporary art exhibitions."
    },
    {
        "name": "Real Jardín Botánico",
        "name_en": "Royal Botanical Garden",
        "area": "Retiro",
        "category": "Park",
        "tags": ["botanik", "bahçe", "doğa", "sessiz"],
        "distanceFromCenter": 1.0,
        "lat": 40.4111,
        "lng": -3.6908,
        "price": "low",
        "rating": 4.6,
        "description": "Prado Müzesi'nin hemen yanındaki bu tarihi bahçe, dünyanın dört bir yanından gelen binlerce bitki türüne ve huzurlu yürüyüş yollarına sahiptir.",
        "description_en": "Located next to the Prado Museum, this lush oasis features over 5,000 species of living plants and trees from around the world."
    },
    {
        "name": "Plaza de Colón",
        "name_en": "Colon Square",
        "area": "Salamanca/Centro",
        "category": "Tarihi",
        "tags": ["kolomb", "bayrak", "meydan", "kütüphane"],
        "distanceFromCenter": 1.2,
        "lat": 40.4248,
        "lng": -3.6908,
        "price": "free",
        "rating": 4.5,
        "description": "Kristof Kolomb anısına adanmış, dünyanın en büyük İspanyol bayrağına ve devasa beton anıtlara ev sahipliği yapan modern görünümlü meydan.",
        "description_en": "A grand square dedicated to Christopher Columbus, featuring a colossal monument and one of the world's largest national flags."
    },
    {
        "name": "Biblioteca Nacional (Müze)",
        "name_en": "National Library Museum",
        "area": "Centro",
        "category": "Müze",
        "tags": ["kitap", "tarih", "sanat", "kütüphane"],
        "distanceFromCenter": 1.2,
        "lat": 40.4233,
        "lng": -3.6900,
        "price": "free",
        "rating": 4.8,
        "description": "İspanya'nın en önemli yazılı hazinelerinin korunduğu muazzam kütüphane binasının içindeki etkileyici kitap ve yazın tarihi müzesi.",
        "description_en": "Housed in a massive neoclassical building, the library's museum offers a fascinating look at the history of writing and printing in Spain."
    },
    {
        "name": "Lavapiés (Barrio)",
        "name_en": "Lavapies District",
        "area": "Lavapiés",
        "category": "Deneyim",
        "tags": ["multikültürel", "bohem", "grafiti", "mutfak"],
        "distanceFromCenter": 1.0,
        "lat": 40.4090,
        "lng": -3.7010,
        "price": "low",
        "rating": 4.5,
        "description": "Madrid'in en kozmopolit ve bohem mahallesi. Dünyanın her yerinden mutfaklar, sokak festivalleri ve canlı bir yerel kültür sizi bekliyor.",
        "description_en": "The most ethnically diverse neighborhood in Madrid, famous for its colorful street art, bohemian cafes, and eclectic world restaurants."
    },
    {
        "name": "Museo ABC",
        "name_en": "ABC Museum",
        "area": "Centro",
        "category": "Müze",
        "tags": ["grafik sanat", "modern mimari", "sergi", "tasarım"],
        "distanceFromCenter": 1.1,
        "lat": 40.4285,
        "lng": -3.7112,
        "price": "low",
        "rating": 4.6,
        "description": "Modern bir mimari tasarıma sahip olan bu müze, grafik sanatlar, illüstrasyon ve çizgi roman dünyasına adanmış eşsiz bir galeridir.",
        "description_en": "A stunning piece of modern architecture housing an impressive collection of graphic arts, illustrations, and temporary design exhibitions."
    },
    {
        "name": "Plaza de Olavide",
        "name_en": "Plaza de Olavide",
        "area": "Chamberí",
        "category": "Manzara",
        "tags": ["meydan", "lokal", "teras", "dinlenme"],
        "distanceFromCenter": 2.2,
        "lat": 40.4344,
        "lng": -3.7028,
        "price": "free",
        "rating": 4.7,
        "description": "Turistlerin pek bilmediği, Madridlilerin güneşli havalarda teraslarında oturup bir içki eşliğinde sohbet ettiği dairesel ve huzurlu bir meydan.",
        "description_en": "A local favorite in the heart of Chamberí, this circular pedestrian square is filled with terraces that are perfect for a sunny afternoon 'vermut.' "
    },
    {
        "name": "Barrio de Salamanca",
        "name_en": "Salamanca District",
        "area": "Salamanca",
        "category": "Deneyim",
        "tags": ["şıklık", "mimari", "lüks", "yürüyüş"],
        "distanceFromCenter": 1.8,
        "lat": 40.4300,
        "lng": -3.6840,
        "price": "high",
        "rating": 4.8,
        "description": "Madrid'in en seçkin bölgesi. Geniş bulvarları, 19. yüzyıldan kalma asil binaları ve şık restoranlarıyla kentin en zarif yüzü.",
        "description_en": "Madrid's most upscale residential and shopping district, known for its grid-like layout, high-end boutiques, and sophisticated atmosphere."
    },
    {
        "name": "Teatro Lara",
        "name_en": "Teatro Lara",
        "area": "Malasaña",
        "category": "Tarihi",
        "tags": ["tiyatro", "retro", "sanat", "tarihi Bina"],
        "distanceFromCenter": 0.8,
        "lat": 40.4230,
        "lng": -3.7045,
        "price": "medium",
        "rating": 4.7,
        "description": "1880'lerden kalma büyüleyici dekorasyonuyla Madrid'in en güzel tarihi tiyatrolarından biri. Bağımsız oyunlara ev sahipliği yapar.",
        "description_en": "A beautiful 19th-century theater in Malasaña, nicknamed the 'bombbonnière' for its ornate, cozy, and perfectly preserved interior."
    }
]

def enrich_madrid_batch2():
    filepath = 'assets/cities/madrid.json'
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    existing_names = set(h['name'].lower() for h in data.get('highlights', []))
    for new_h in new_madrid_batch2:
        if new_h['name'].lower() not in existing_names:
            # Add missing fields
            new_h['imageUrl'] = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800"
            new_h['bestTime'] = "Gündüz"
            new_h['bestTime_en'] = "Daytime"
            new_h['tips'] = "Mutlaka görün."
            new_h['tips_en'] = "A must see."
            data['highlights'].append(new_h)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(data['highlights'])

count = enrich_madrid_batch2()
print(f"Madrid now has {count} highlights.")
