import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
0:  {'t': "Budva Eski Şehri'nde akşam 19:00-21:00 arası surlar boyunca yürüyüş yapmak en iyi saattir; Adriyatik'e yansıyan altın ışık bu saatlerde en güzel panoramayı verir.",
     'te': "The best time to walk along the ramparts of Budva Old Town is between 7-9pm; the golden light reflecting off the Adriatic gives the best panorama at these hours."},
3:  {'t': "Sveti Stefan'ın mihraksiz görüntüsü için karşı sahilden bakmak gerekir; adaya giriş Five Star Aman Resort misafirlerine özgüdür, dışarıdan sahilden fotoğraf çekilebilir.",
     'te': "To see Sveti Stefan's unobstructed view you need to look from the opposite shore; island entry is exclusive to Five Star Aman Resort guests, photos can be taken from the beach outside."},
8:  {'t': "Aziz Yuhanna Kilisesi, Budva Eski Şehri'nin en eski dini yapısıdır; namaz vakitlerinde ziyaretçi alınmaz, sabah ve akşam saatleri için kapı durumunu kontrol edin.",
     'te': "Church of Saint John the Baptist is the oldest religious structure in Budva Old Town; visitors are not accepted during service times, check the door status for morning and evening hours."},
9:  {'t': "Fort Kosmač, Budva'nın arka dağlarında gizli bir Sırp-Yugoslav ordu kalesidir; çevre yollarla gidilir, araç şart. Gün batımında kale tepesinden Adriyatik manzarası unutulmazdır.",
     'te': "Fort Kosmač is a hidden Serbian-Yugoslav army fortress in the hills behind Budva; accessible via surrounding roads, a vehicle is essential. The Adriatic view from the fortress top at sunset is unforgettable."},
10: {'t': "Yamaç paraşütü için hava koşulları belirleyicidir; sabah 09:00-11:00 arası termal akımlar en stabil dönem. Operatörle önceden meteo takibi yapın.",
    'te': "Weather conditions are decisive for paragliding; 9-11am is the most stable period for thermal currents. Monitor weather with the operator in advance."},
12: {'t': "Kutsal Üçlük Kilisesi eski şehirde; sabah erken saatlerinde kilise içinde mum ışığında bekleyen yerel halkı görmek Budva'nın Ortodoks geleneğini en samimi biçimde tanıtır.",
    'te': "Holy Trinity Church is in the old town; seeing locals waiting by candlelight inside the church in the early morning is the most sincere introduction to Budva's Orthodox tradition."},
13: {'t': "Aquapark Budva, sezon dışında (Ekim-Mayıs) kapalıdır; yaz aylarında hafta içi kalabalık çok daha azdır. Çocuklar için en iyi saat 10:00-14:00 arası güneş yoğun olmadan.",
    'te': "Aquapark Budva is closed off-season (October-May); on weekdays in summer the crowds are much fewer. The best time for children is between 10am-2pm before the intense sun."},
14: {'t': "Tekne kiralama için liman yakınındaki tekne ofisleri ile doğrudan pazarlık yapın; yaz ortasında liste fiyatından %10-15 indirim mümkündür, sabah kalışları daha ucuzdur.",
    'te': "Negotiate directly with boat offices near the harbor for boat rental; a 10-15% discount from the list price is possible in mid-summer, morning departures are cheaper."},
15: {'t': "Podmaine Manastırı, Budva merkeze 3 km uzaklıkta sessiz bir Ortodoks manastırıdır; ziyaret için hafif kıyafet ve saygılı davranış şarttır. Sabah ayinine katılmak mümkündür.",
    'te': "Podmaine Monastery is a quiet Orthodox monastery 3 km from Budva center; light clothing and respectful behavior are essential for a visit. Attending the morning service is possible."},
16: {'t': "Budva'nın çevreyolu üzerindeki bu fontanlı trafik çemberi, şehrin giriş fotoğrafları için popüler bir duraktır; akşam ışıklandırması ile daha çarpıcı görünür.",
    'te': "This roundabout with fountains on Budva's bypass road is a popular stop for city entrance photos; it looks more striking with evening illumination."},
17: {'t': "Topdent, Budva'da diş turizmi için bilinen bir kliniktir; randevu ve fiyat için önceden e-posta ile iletişime geçin.",
    'te': "Topdent is a known clinic in Budva for dental tourism; contact via email in advance for an appointment and prices."},
18: {'d': "Budva Paragliding Montenegro, Karadağ'ın Adriyatik sahilinde yamaç paraşütü deneyimi sunan profesyonel bir operatördür. Brajići köyünden kalkan uçuşlar, denizin üzerinde süzülerek Sveti Stefan ve Budva'nın panoramasını karşılaştırılamaz bir yükseklikten sunar.",
    'de': "Budva Paragliding Montenegro is a professional operator offering paragliding experience on Montenegro's Adriatic coast. Flights departing from Brajići village offer the panorama of Sveti Stefan and Budva from an incomparable height, gliding above the sea.",
    't': "Ön deneyim gerektirmez; tandem uçuş seçeneğiyle pilot eşliğinde ilk kez deneyenler için uygundur. Rezervasyon ve hava tahmini takibi için önceden iletişime geçin.",
    'te': "No prior experience required; the tandem flight option is suitable for first-timers accompanied by a pilot. Contact in advance for reservation and weather forecast tracking."},
19: {'t': "montenegrome, Karadağ gezi ve rehberlik hizmetleri konusunda yerel danışmanlık sunar; Budva çevresi günübirlik turlar ve gizli koy turları için başvurmak değerlidir.",
    'te': "montenegrome offers local consultancy on Montenegro travel and guiding services; it is valuable to consult for day trips around Budva and hidden cove tours."},
20: {'t': "Evcil hayvan dostu bu plaj, köpeklerini denize sokmak isteyen ziyaretçiler için Budva'nın nadir seçeneklerinden biridir; sabah erken saatler en sakin ve en uygun dönemdir.",
    'te': "This pet-friendly beach is one of Budva's rare options for visitors wanting to bring their dogs to the sea; early morning hours are the calmest and most suitable period."},
21: {'t': "Nenov brod, Budva limanından tekne kiralamak için çalışan küçük bir tekne servisidir; yarım günlük tur için saatlik fiyat ve güzergah konusunda doğrudan pazarlık yapın.",
    'te': "Nenov brod is a small boat service operating to rent boats from Budva harbor; negotiate directly about hourly price and route for a half-day tour."},
22: {'t': "Gringo Boat, Budva Marina'dan kalkıp koyları dolaşan popüler tekne turları düzenler; grup turlarında kişi başı fiyat avantajlı, özel tekne de talep edilebilir.",
    'te': "Gringo Boat organizes popular boat tours departing from Budva Marina and touring the coves; per-person price advantage in group tours, a private boat can also be requested."},
23: {'t': "Ciapson Cat katamaranı, gün batımı turları ile özellikle tanınmaktadır; Sveti Stefan açıklarında demirleyerek izlenen Adriyatik günbatımı turun en güzel anıdır.",
    'te': "Ciapson Cat catamaran is particularly known for its sunset tours; the Adriatic sunset watched while anchored off Sveti Stefan is the tour's most beautiful moment."},
24: {'t': "Budva halk rıhtımı, sabah balık satışı ve akşam yürüyüşü için en canlı saatlere ev sahipliği eder; tekne sahipleriyle günübirlik koy turu için pazarlık yapmak mümkündür.",
    'te': "Budva public dock hosts the liveliest hours for morning fish sales and evening promenade; it is possible to negotiate with boat owners for a day-trip cove tour."},
25: {'t': "Budva Taxi Panorama Boat, liman çevresinde kısa panoramik tekne turları sunar; kalabalık olmayan sabah saatlerinde daha sakin ve keyifli bir tur deneyimi için önceden rezervasyon yapın.",
    'te': "Budva Taxi Panorama Boat offers short panoramic boat tours around the harbor; book in advance for a calmer and more enjoyable tour experience during the less crowded morning hours."},
26: {'t': "Turist Market 4, eski şehir yakınında hediyelik eşya ve yerel ürünler satan pratik bir dükkan; fiyatları pazarlıkla düşürmek mümkündür, Karadağ usulü bal ve rakiyi burada arayın.",
    'te': "Turist Market 4 is a practical shop near the old town selling souvenirs and local products; prices can be reduced with bargaining, look for Montenegrin-style honey and raki here."},
27: {'t': "Budva Turizm Danışma, sezon boyunca Eski Şehir girişinde ücretsiz şehir haritası ve etkinlik takvimi dağıtmaktadır; yerel rehber veya tur hakkında bilgi için ilk uğranacak yer.",
    'te': "Budva Tourism Information distributes free city maps and event calendars at the Old Town entrance throughout the season; the first place to visit for information about local guides or tours."},
65: {'t': "Emporio Club, Budva'nın beach club gece eğlencesi için en bilinen adreslerinden biridir; yüksek sezon Temmuz-Ağustos'ta giriş için önceden konuk listesine kayıt yaptırın.",
    'te': "Emporio Club is one of the most well-known addresses in Budva for beach club nightlife; register on the guest list in advance for entry during the peak season of July-August."},
66: {'t': "Top Hill, Budva'nın tepesinde bir açık hava kulübüdür; uluslararası DJ geceleri için program takibi ve bilet satın alma önceden yapılmalıdır. Servis minibüsleri merkez noktalardan kalkar.",
    'te': "Top Hill is an open-air club on Budva's hilltop; program tracking and ticket purchase for international DJ nights must be done in advance. Service minibuses depart from central points."},
67: {'t': "Trocadero, Budva'nın en tanınan plaj kulüplerinden biridir; Ağustos'ta masaları erken saatlerde rezerve edilmeli. Öğleden sonra 13:00-15:00 arası şezlong rezervasyonu en kalabalık saattir.",
    'te': "Trocadero is one of Budva's most well-known beach clubs; tables must be reserved early in August. The 1-3pm period is the busiest hour for sun lounger reservations."},
68: {'t': "Premium Palazzo, Budva'nın gece yaşamında üst segment bir gece kulübüdür; giriş listesi ve kıyafet kuralları önceden kontrol edilmeli. Kapıda uzun bekleme süreleri oluşabilir.",
    'te': "Premium Palazzo is a high-end nightclub in Budva's nightlife; entry list and dress code should be checked in advance. Long waiting times at the door can occur."},
69: {'d': "Restoran Mujo Simba, Karadağ mutfağını yakın çevreden gelen taze Adriyatik balığı ve yerel nar sosuyla harmanlayan samimi bir aile restoranıdır. Adriyatik manzaralı terası ve uygun fiyat-kalite dengesiyle Budva'nın gerçek lezzetini sunan köklü adreslerden biridir.",
    'de': "Restoran Mujo Simba is a sincere family restaurant that blends Montenegrin cuisine with fresh Adriatic fish arriving from nearby and local pomegranate sauce. With its Adriatic-view terrace and good value-for-money balance, it is one of the established addresses presenting Budva's genuine flavors.",
    't': "Hafta içi öğle yemeği için rezervasyon gerekmez; akşam yemeği ve hafta sonu için önceden arayın. Taze kalamar ve pršut (Karadağ jambonu) kombinasyonu buranın imza tabağıdır.",
    'te': "No reservation needed for weekday lunch; call ahead for dinner and weekends. Fresh calamari and pršut (Montenegrin ham) combination is the signature dish here."},
70: {'t': "Omnia Club, Budva gece hayatının en büyük kapasiteli mekanlarından biridir; uluslararası sanatçı geceleri için biletler haftalar öncesinden satışa çıkar.",
    'te': "Omnia Club is one of Budva nightlife's largest-capacity venues; tickets for international artist nights go on sale weeks in advance."},
71: {'t': "Karaoke Montenegro, hem yerel halkın hem turistlerin eğlenceli gecelere katıldığı samimi bir mekandır; Sırpça ve İngilizce şarkı listeleri mevcuttur.",
    'te': "Karaoke Montenegro is a sincere venue where both locals and tourists join fun evenings; Serbian and English song lists are available."},
72: {'t': "Bar Beograd, Karadağ mutfağının en klasik örneklerini sunan bir yerel kafedir; mangal köftesi ve ev yapımı rakiyle akşam saatlerinde otantik bir Budva deneyimi yaşatır.",
    'te': "Bar Beograd is a local café serving the most classic examples of Montenegrin cuisine; it offers an authentic Budva experience in the evenings with grilled meatballs and homemade raki."},
73: {'t': "Apartments Mika, Budva'da uygun fiyatlı konaklama arayan aileler için merkeze yakın pratik bir seçenektir; deniz manzaralı daireler için erken rezervasyon yapılmalıdır.",
    'te': "Apartments Mika is a practical option close to the center for families seeking affordable accommodation in Budva; early reservation should be made for sea-view apartments."},
74: {'t': "Cascada Club, şelale dekorasyonuyla Budva'nın en görsel gece mekanlarından biridir; gece 23:00 sonrası en kalabalık saat başlar, öncesinde daha rahat masa bulunur.",
    'te': "Cascada Club is one of Budva's most visually striking night venues with waterfall decoration; the busiest hour starts after 11pm, tables are easier to find before then."},
75: {'d': "Night Club Ambiente, Budva'nın eski şehrine yakın konumuyla kolay erişilebilen, yerli ve yabancı müziği harmanlayan bir gece kulübüdür. Canlı müzik geceleri ve DJ setleriyle orta segment gece eğlencesini tatmak isteyen ziyaretçiler için doğru bir adrestir.",
    'de': "Night Club Ambiente is an easily accessible nightclub near Budva's old town, blending local and international music. It is the right address for visitors wanting to taste mid-range nightlife entertainment with live music nights and DJ sets.",
    't': "Hafta içi geceleri canlı Balkan müziği yapılır; bu gecelerde yerel halkla karışık kalabalık, Karadağ gece ruhunu en doğal biçimde yansıtır.",
    'te': "Weeknight evenings feature live Balkan music; on these evenings the mixed crowd with locals reflects the Montenegrin night spirit in its most natural form."},
76: {'d': "Night Club Fetka, Budva'nın gece sahnesinde köklü bir isim olarak özellikle Slav turist kitlesinin aşina olduğu mekan olarak bilinmektedir. Sırp pop müziği ağırlıklı çalarken, gece ilerledikçe dans pisti dolup taşar ve gece geç saatlere kadar aktif kalır.",
    'de': "Night Club Fetka is a deep-rooted name in Budva's nightlife scene, known particularly as a venue familiar to the Slavic tourist audience. While primarily playing Serbian pop music, as the night progresses the dance floor fills up and stays active until late.",
    't': "Sırpça ve Karadağ müziğine açık olun; atmosfer gece 01:00'den sonra en yüksek enerjisine ulaşır ve sabaha kadar sürer.",
    'te': "Be open to Serbian and Montenegrin music; the atmosphere reaches its highest energy after 1am and continues until morning."},
77: {'t': "Caffe Bar CBR, yerel esnaf ve mahalle sakinlerinin düzenli gittiği samimi bir Budva kafesidir; sabah demli kahvesi ve simit çeşitleriyle eski şehir yürüyüşünün başlangıcı için ideal.",
    'te': "Caffe Bar CBR is a sincere Budva café regularly frequented by local tradespeople and neighborhood residents; ideal for starting an old town walk with strong morning coffee and simit varieties."},
78: {'t': "Lucky Karaoke, sezona ısındığınız akşam saatlerinde hem komik hem eğlenceli bir Budva deneyimi sunar; Karadağ ve Balkan pop şarkıları en çok seçilen repertuarı oluşturur.",
    'te': "Lucky Karaoke offers a both funny and entertaining Budva experience during the evening hours when you warm up to the season; Montenegrin and Balkan pop songs make up the most selected repertoire."},
79: {'d': "Club Hide Budva, şehrin gece hayatında gençlerin ve Karadağ yerli kalabalığının akın ettiği, şehir merkezine yakın konumuyla kolay erişilebilen bir kulüptür. Yerel DJ'lerin sahneye çıktığı bu mekanda ses sistemi güçlüdür ve dans pisti Balkan ritmiyle gece boyunca coşar.",
    'de': "Club Hide Budva is a club easily accessible with its location close to the city center, where young people and Montenegrin locals flock in the nightlife. In this venue where local DJs perform, the sound system is powerful and the dance floor rocks with Balkan rhythm throughout the night.",
    't': "Yerel DJ programı için sosyal medya sayfasını takip edin; Slav ve elektronik müzik karışımı gece boyunca çalar.",
    'te': "Follow the social media page for the local DJ program; a mix of Slavic and electronic music plays throughout the night."},
80: {'t': "Na Vodu ızgara ve bira mekanı, sahile yakın konumuyla hem plaj sonrası öğle hem de akşam için rahat bir duraktır; taze cızbız köfte ve yerel bira ile Karadağ'da gündelik bir öğünün en ekonomik versiyonunu sunar.",
    'te': "Na Vodu grill and beer spot, close to the beach, is a comfortable stop for both post-beach lunch and evening; fresh köfte burgers and local beer offer the most economical version of an everyday Montenegrin meal."},
81: {'d': "Terrazza Budva, şehrin en iyi manzara noktalarından birinde kurulmuş açık hava terasyıyla hem gündüz manzara kahvesi hem akşam kokteyli için biçilmiş kaftandır. Adriyatik'e açılan bu teras, Eski Şehir silüeti ve kıyı şeridinin aynı karede birleştiği Budva'nın en romantik anlık fotoğraf köşesidir.",
    'de': "Terrazza Budva, with its open-air terrace set at one of the city's best viewpoints, is tailor-made for both a daytime scenic coffee and an evening cocktail. This terrace opening to the Adriatic is Budva's most romantic instant photo corner where the Old Town silhouette and coastline unite in the same frame.",
    't': "Gün batımı 30 dakika öncesinde masanızı alın; Adriyatik'e batan güneşi Eski Şehir surlarıyla aynı karede yakalamak için ideal açı burada.",
    'te': "Take your table 30 minutes before sunset; the ideal angle to catch the sun setting into the Adriatic in the same frame as the Old Town walls is here."},
82: {'t': "Maine Club, Budva'nın üst segment gece hayatını seven ve VIP masa deneyimi isteyen ziyaretçiler için uygun bir adrestir; önceden rezervasyon ve minimum konsomüsyon uygulanır.",
    'te': "Maine Club is a suitable address for visitors who enjoy Budva's upscale nightlife and want a VIP table experience; advance reservation and minimum consumption are applied."},
83: {'t': "Casino Solendud, Budva'da otantik kumarhane deneyimi arayanlar için eski şehre yakın uygun bir seçenektir; masa oyunları için gece 22:00 sonrası en aktif saatlerdir.",
    'te': "Casino Solendud is a convenient option near the old town for those seeking an authentic casino experience in Budva; after 10pm are the most active hours for table games."},
}

apply_batch('budva.json', U)
