import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
50: {'d': "Le Suquet tepesindeki bu tarihi mahzen restoran, Cannes'ın Croisette kalabalığından uzakta derin taş duvarlarının gölgesinde Provence mutfağının en özgün örneklerini sunmaktadır. Lavanta tatlandırmalı kuzudan taze Provençal risottoya uzanan menüsü, bölgenin gerçek gastronomik kimliğini festival şehrinin yüksek fiyatlı taklitlerinden ayırt eden nadir adreslerden biridir.",
    'de': "This historic cellar restaurant on the Le Suquet hill presents the most original examples of Provençal cuisine in the shade of deep stone walls, far from Cannes's Croisette crowds. Its menu stretching from lavender-seasoned lamb to fresh Provençal risotto is one of the rare addresses that distinguishes the region's genuine gastronomic identity from the festival city's high-priced imitations."},

56: {'d': "Le Suquet tepesindeki bu 11. yüzyıldan kalma şapel, Cannes'ın ortaçağ geçmişine ait en iyi korunmuş yapıdır. Yanında yer alan çan kulesiyle birlikte Ligurian Denizi ve Lérins adalarının panoramasını çerçeveleyen bu küçük kilise, şehrin turistik yüzeyinin altında saklı olan tarihsel katmanı somut biçimde ortaya koyar.",
    'de': "This 11th-century chapel on the Le Suquet hill is the best-preserved structure from Cannes's medieval past. Together with its adjacent bell tower framing a panorama of the Ligurian Sea and the Lérins islands, this small church concretely reveals the historical layer hidden beneath the city's touristic surface."},

62: {'d': "Cannes'ın Croisette bulvarına yakın konumuyla Galeries Lafayette, festival dönemlerinde ve yaz sezonunda şehrin en canlı alışveriş deneyimini sunan prestijli Fransız mağazacılık zincirinin Riviera ayağıdır. Parfüm, haute couture ve gıda katıyla alışveriş rutinini Fransız yaşam tarzının tam merkezine yerleştirir.",
    'de': "Galeries Lafayette, close to Cannes's Croisette boulevard, is the Riviera branch of the prestigious French department store chain that offers the city's most vibrant shopping experience during festival periods and summer season. With its perfume, haute couture, and food floor, it places the shopping routine at the very center of French lifestyle."},

64: {'d': "Place du Marché Gambetta'daki bu sabah pazarı, Provence'ın taze sebze ve meyveleri, yerel fromajlar, zeytin çeşitleri ve taze çiçeklerle bir araya geldiğinde Cannes'ın gerçek mahalle yaşamını en gürültüsüz ve en lezzetli biçimde sunar. Yerel satıcıların sezon ürünlerini övdüğü bu pazar, turistik restoranların aksine şehrin kılcal damarını besler.",
    'de': "When Provence's fresh vegetables and fruits, local fromages, olive varieties, and fresh flowers come together at this morning market in Place du Marché Gambetta, it presents Cannes's genuine neighborhood life in the most unpretentious and tastiest form. This market where local vendors praise seasonal products feeds the city's capillaries unlike touristic restaurants."},

65: {'d': "Cannes merkezindeki bu küçük meydan, Fransız yazar Prosper Mérimée'nin adını taşıyan sakin yeşil bir alan olarak akşam yürüyüşçülerinin ve lokal kahvelerin müdavimlerinin buluşma noktasıdır. Croisette'nin yoğunluğundan sığınmak isteyen ziyaretçiler için şehrin az bilinen nefes alma köşelerinden biridir.",
    'de': "This small square in central Cannes is a tranquil green area bearing the name of French writer Prosper Mérimée, serving as the meeting point for evening strollers and regulars of local cafés. It is one of the city's little-known breathing corners for visitors wishing to take refuge from the Croisette's intensity."},

66: {'d': "İngiliz Lord Brougham'ın Cannes'ı dünya turizmine tanıtan kışı 1834'te geçirdiği tarihsel an, bu küçük meydanda bir anıtla yâd edilmektedir. Cannes'ın Riviera'da küçük bir balıkçı köyünden uluslararası bir tatil beldesine dönüşmesinin sembolik başlangıç noktasını bu meydan temsil eder.",
    'de': "The historical moment when English Lord Brougham spent the winter of 1834 that introduced Cannes to world tourism is commemorated with a monument in this small square. This square represents the symbolic starting point of Cannes's transformation from a small fishing village to an international holiday resort on the Riviera."},

67: {'d': "Cannes'ın kuzeyindeki Parc Montfleury, şehrin yoğun sahil şeridinden uzaklaşıp çam ağaçları arasında sakin bir yürüyüş yapmak isteyenler için ideal bir yeşil alan sunar. Şehrin sakinlerinin sabah koşusu ve hafta sonu piknik için tercih ettiği bu park, turizmin dışında kalan bir gündelik Cannes yaşamının parçasıdır.",
    'de': "Parc Montfleury in northern Cannes offers an ideal green space for those wishing to get away from the city's intense beachfront and take a tranquil walk among pine trees. Preferred by the city's residents for morning jogging and weekend picnics, this park is part of an everyday Cannes life that lies outside tourism."},

68: {'d': "1908'de kurulan Cannes Tenis Kulübü, Riviera'nın en köklü ve en prestijli tenis tesislerinden biridir. Kil kortları ve meyve bahçeleri arasındaki konumuyla şehrin üst sosyal katmanlarının yıllarca buluştuğu bu kulüp, Cannes'ın film festivallerinin ötesinde var olan yüksek sosyete kimliğinin somut bir parçasıdır.",
    'de': "Founded in 1908, Cannes Tennis Club is one of the most deep-rooted and prestigious tennis facilities on the Riviera. With its clay courts and position among fruit orchards, this club where the city's upper social layers have been meeting for years is a concrete part of Cannes's high society identity that exists beyond its film festivals."},

72: {'d': "Cannes'dan deniz yolculuğuyla sadece 30 dakikada ulaşılan Antibes, Ortaçağ'dan kalma surları ve liman çevresindeki Fransız sahil kasabası atmosferiyle Cannes'ın lüks imajına güçlü bir kültürel alternatif sunar. Picasso Müzesi ve Vieille Ville'in (eski şehir) taş sokaklarıyla bir gün geçirmek için biçilmiş kaftan.",
    'de': "Antibes, reachable in just 30 minutes by sea from Cannes, offers a strong cultural alternative to Cannes's luxury image with its medieval walls and the French seaside town atmosphere around its harbor. Tailor-made for spending a day with the Picasso Museum and the stone streets of Vieille Ville (old town)."},

73: {'d': "Cannes'dan yaklaşık 17 km içerideki Grasse, dünyanın parfüm başkentiydi ve Chanel No. 5 dahil binlerce parfümün hammaddesini bu bölgenin gül ve lavanta bahçeleri sağlamıştır. Fragonard veya Molinard gibi tarihi parfüm fabrikalarını ziyaret etmek, koku sanayinin kökenlerine dair benzersiz ve koku dolu bir deneyim sunar.",
    'de': "Grasse, approximately 17 km inland from Cannes, was the world's perfume capital and the rose and lavender gardens of this region have provided the raw materials for thousands of perfumes including Chanel No. 5. Visiting historic perfume factories like Fragonard or Molinard offers a unique and fragrant experience about the origins of the scent industry."},

79: {'d': "Antibes'in güneyindeki Cap d'Antibes'e uzanan bu sahil yürüyüş yolu, pahalı villalar ve denize doğru uzanan özel iskelelerin arasından geçerek Fransız Rivierası'nın en sürükleyici doğal-yapay dokusunu sunar. F. Scott Fitzgerald'ın 'Gece Yumuşak' romanına ilham veren bu sahil boyunca yürümek, hem edebi hem de estetik açıdan ayrıcalıklı bir Riviera deneyimi yaratır.",
    'de': "This coastal hiking path extending to Cap d'Antibes south of Antibes presents the most immersive natural-built texture of the French Riviera by passing through expensive villas and private jetties jutting toward the sea. Walking along this shore that inspired F. Scott Fitzgerald's 'Tender is the Night' creates a Riviera experience that is both literary and aesthetically privileged."},

84: {'d': "Cannes limanından kalkan bu tekne turları, Lérins Takımadasının Sainte-Marguerite ve Saint-Honorat adalarına günübirlik ya da yarım günlük ziyaretler düzenler. Yüzyıllık Cistercian manastırına ev sahipliği yapan Saint-Honorat, manastır keşişlerinin ürettiği şarap ve likörlerle şehrin gürültüsünden tamamen kopuk bir adada günü geçirmenin en unutulmaz yolunu sunar.",
    'de': "Boat tours departing from Cannes harbor organize day-long or half-day visits to Sainte-Marguerite and Saint-Honorat islands in the Lérins archipelago. Saint-Honorat, home to a centuries-old Cistercian monastery, offers the most unforgettable way to spend a day on an island completely detached from the city's noise with wine and liqueurs produced by monastery monks."},

88: {'d': "Her yıl Ocak ayında düzenlenen MIDEM, dünyanın en köklü müzik endüstrisi fuarlarından biridir ve Palais des Festivals'de yerini almaktadır. Cannes'ın film festivaliyle özdeşleşen imajının arkasında bu tür uluslararası meslek fuarlarının şehre sağladığı ekonomik ve kültürel ivmenin büyük payı vardır.",
    'de': "MIDEM, organized each January, is one of the world's most deep-rooted music industry fairs and takes its place at Palais des Festivals. Behind the image identified with Cannes's film festival, international professional fairs like this have a large share in the economic and cultural momentum they provide to the city."},

89: {'d': "Her yıl Mart ayında düzenlenen MIPIM, küresel emlak ve kentsel dönüşüm sektörünün Cannes'ı yılın en önemli ticari buluşma noktasına dönüştürdüğü bir fuar ve konferanstır. Palais des Festivals ve Croisette boyunca kurgulanan ağırlama etkinlikleriyle şehir bu dönemde film festivalindekinden daha farklı bir uluslararası profil çizer.",
    'de': "MIPIM, held each March, is a fair and conference that transforms Cannes into the most important annual commercial meeting point for the global real estate and urban transformation sector. With hospitality events staged along Palais des Festivals and the Croisette, the city draws an international profile during this period that is quite different from the film festival."},

91: {'d': "Croisette'in hemen karşısındaki Casino Barrière de Cannes, 1907'den bu yana Fransız Rivierası'nın en prestijli kumar mekanları arasında yer almaktadır. Gece kıyafeti gerektiren klasik salon, modern slot alanı ve 11 katlı Hôtel Barrière Le Majestic ile kombinlendiğinde Cannes'ın en gösterişli gece programı burada mümkün olur.",
    'de': "Casino Barrière de Cannes, directly across from the Croisette, has been among the most prestigious gambling venues on the French Riviera since 1907. When combined with the classic room requiring evening wear, modern slot area, and the 11-story Hôtel Barrière Le Majestic, Cannes's most spectacular evening program becomes possible here."},

92: {'d': "Festival sezonunda ve yaz zirvesinde Croisette boyunca uzanan gece mekanları, Fransız Rivierası'nın en görünür eğlence sahnesini oluşturur. Cannes'ın gece hayatı; yacht partileri, beach club defilelerinden sinema galalarına kadar geniş bir yelpazede değişen, şehrin yüksek sosyete imajını gece boyunca yeniden üreten çok katmanlı bir yapıdır.",
    'de': "The nightlife venues stretching along the Croisette during festival season and summer peak form the most visible entertainment scene of the French Riviera. Cannes nightlife is a multi-layered structure that ranges widely from yacht parties and beach club fashion shows to cinema galas, reproducing the city's high society image throughout the night."},

93: {'d': "Cannes'ın eski şehir tarafında her sabah kurulan Marché Forville, taze Provence çiçekleri, yerel meyve ve sebzeler, kuru üzüm, zeytin ve fromaj çeşitleriyle Fransız pazarcılık geleneğini canlı tutan şehrin en rengarenk köşesidir. Film festivali zamanı dışında bu pazar, şehrin gerçek yerel yaşam ritmini görmek için en iyi duraklardan biridir.",
    'de': "Marché Forville, set up every morning on Cannes's old town side, is the city's most colorful corner that keeps French market tradition alive with fresh Provence flowers, local fruits and vegetables, dried fruits, olive varieties, and fromage. Outside film festival time, this market is one of the best stops for seeing the city's genuine local life rhythm."},

96: {'d': "Le Suquet'in tepesindeki bu antik kapı, Cannes'ın ortaçağ surlarından günümüze ulaşan son kalıntılardan biridir. Kapının ardındaki Eglise de la Castre'a uzanan dar taş sokaklar, Croisette'nin parlak vitrinlerinden çok farklı olan orta çağ balıkçı kasabası yüzüyle tanıştırır.",
    'de': "This ancient gate at the top of Le Suquet is one of the last remains of Cannes's medieval walls that have survived to the present day. The narrow stone streets extending to Eglise de la Castre behind the gate introduce you to the medieval fishing village face that is very different from the Croisette's shiny storefronts."},

98: {'d': "Lérins'in Saint-Honorat Adası'nda 410'dan bu yana var olan Cistercian manastırının keşişleri, ada toprağında yetiştirdikleri üzümlerden hem Appellation d'Origine Contrôlée şarap hem de Honoratine likörleri üretiyor. Bu keşiş şarabı ve likörleri hem manastır dükkânında hem de Cannes'ın bazı özel şarap mekanlarında bulunmakta.",
    'de': "The monks of the Cistercian monastery that has been on Lérins's Saint-Honorat Island since 410 produce both Appellation d'Origine Contrôlée wine and Honoratine liqueurs from grapes grown on island soil. These monks' wine and liqueurs can be found both in the monastery shop and in some specialty wine venues in Cannes."},

99: {'d': "Ünlü 'Demir Maskeli Adam'ın tutulduğu rivayet edilen Sainte-Marguerite Adası'nın kale hapishanesi, Fransız krali Kral XIV. Louis dönemine ait gizemli tarihin parçasıdır. Bu tarihi bilinmezlik, adayı turistik değer açısından Cannes'ın plajlarından çok farklı bir çekim noktası haline getiriyor.",
    'de': "The fortress prison on Sainte-Marguerite Island, reputed to be where the famous 'Man in the Iron Mask' was held, is part of the mysterious history dating to the era of French King Louis XIV. This historical mystery makes the island a very different attraction from Cannes's beaches in terms of touristic value."},

101: {'d': "Cannes'ın yelkencilik kulübü, Fransız Rivierası'nın köklü denizcilik kültürünün bir parçası olarak hem yarışma hem de rekreasyonel yelkencilik için imkânlar sunar. Yaz sezonunda güneş batan saatlerde Golfe de la Napoule'a açılan yelkenli tekneleri Croisette'den izlemek, Cannes'ın başka hiçbir noktada bulunamayan denizci ruhunu hissettirir.",
    'de': "Cannes's sailing club offers opportunities for both competitive and recreational sailing as part of the French Riviera's deep-rooted maritime culture. Watching sailing boats heading into the Golfe de la Napoule from the Croisette as the sun sets in summer season gives you the seafaring spirit of Cannes that cannot be found anywhere else."},
}

apply_batch('cannes.json', U)
