import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
9: {'d': "Dubrovnik'in hemen arkasında yükselen Srđ Dağı, 412 metrelik zirvesinden eski şehrin surlarını, Lokrum adasını ve Adriyatik'i kapsayan eşsiz bir panorama sunar. Napoleon döneminden kalma İmperyal Kalesi ve şehre açık hava hücum zamanı kurulan Vatan Savaşı Müzesi burada tarihin katmanlarını gözler önüne serer.",
    'de': "Mount Srđ rising directly behind Dubrovnik offers an unmatched panorama from its 412-metre summit spanning the old town walls, Lokrum island, and the Adriatic. The Imperial Fortress from the Napoleonic era and the Homeland War Museum established here during the siege of the city lay bare layers of history."},

10: {'d': "Dubrovnik'in karşısındaki bu doğa koruma adası, denizden sadece 10 dakika uzakta ama kentsel gürültüden tamamen kopuk bir cennet parçasıdır. Botanik bahçesi, 12. yüzyıl manastır kalıntıları ve adaya özgü Lokrum tavşanı burada doğa ve tarihle çift taraflı bir deneyim sunar; üstelik motorlu araç yasaktır.",
    'de': "This nature reserve island just opposite Dubrovnik is a paradise piece just 10 minutes by sea but completely detached from urban noise. The botanical garden, 12th-century monastery ruins, and Lokrum rabbits unique to the island offer a dual experience of nature and history; motorized vehicles are also prohibited."},

12: {'d': "Dubrovnik surlarının hemen dışındaki Sveti Jakov Plajı, taş basamaklarla denize inen yapısı ve restoranı olmayan sakin atmosferiyle şehrin belediye plajlarına alternatif arayan ziyaretçilerin sığınağıdır. Kristal berraklığındaki suları ve arka plandaki eski şehir silueti, sabah erken saatlerde burayı Dubrovnik'in en fotoğrafenik köşelerinden birine dönüştürür.",
    'de': "Sveti Jakov Beach just outside Dubrovnik's walls is a refuge for visitors seeking an alternative to the city's crowded municipal beaches with its stone steps descending to the sea and restaurant-free calm atmosphere. Its crystal-clear waters and the old town silhouette in the background transform it into one of Dubrovnik's most photogenic corners in the early morning."},

31: {'d': "Dubrovnik açıklarındaki bu ada grubunun büyükleri Šipan, Lopud ve Koločep, turistik Dubrovnik'in karşısında neredeyse el değmemiş Adriyatik köy yaşamını korur. Feribotla sadece 45 dakika uzakta olan bu adalarda bisiklet, deniz ve zeytinlik yürüyüşleriyle saatlerce avare olmak mümkündür.",
    'de': "The main islands of this archipelago off Dubrovnik — Šipan, Lopud, and Koločep — preserve an almost untouched Adriatic village life in contrast to touristic Dubrovnik. On these islands just 45 minutes by ferry, it is possible to wander for hours by bicycle, sea, and through olive grove walks."},

32: {'d': "Elaphiti takımadasının en büyük adası olan Šipan, Dubrovnik soylularının yüzyıllar boyunca yazlık sayfiye yeri olarak kullandığı, görkemli Rönesans villaları ve bağlarıyla çerçevelenmiş sakin bir Adriyatik cennetidir. Adanın iki köyü — Suđurađ ve Šipanska Luka — motorlu araç olmaksızın bisiklet ya da yürüyüşle keşfedilir.",
    'de': "Šipan, the largest island of the Elaphiti archipelago, is a tranquil Adriatic paradise framed by magnificent Renaissance villas and vineyards that Dubrovnik's nobility used as their summer retreat for centuries. The island's two villages — Suđurađ and Šipanska Luka — are discovered by bicycle or on foot without motorized vehicles."},

36: {'d': "Dubrovnik'in en prestijli ince yemek restoranı olan Nautika, Pile Kapısı'nın hemen yanı başında, kayalık uçurumun üstünde kurulmuştur. Adriyatik'in en taze deniz ürünlerini Avrupalı tekniklere uygulaması, Nobel şampanyasıyla başlayan akşam yemeği programı ve eşsiz sur-deniz manzarası sayesinde yıllardır seyahat rehberlerinin ilk sıralarında yer almaktadır.",
    'de': "Dubrovnik's most prestigious fine dining restaurant, Nautika is perched on a rocky cliff right beside the Pile Gate. With the Adriatic's freshest seafood applied with European techniques, an evening dining program beginning with Nobel champagne, and unmatched wall-sea views, it has occupied the top of travel guides for years."},

37: {'d': "Eski şehrin dar sokaklarında saklanan Fish Restaurant Proto, 1886'dan bu yana Dubrovnik'in taze Adriyatik balığını en geleneksel biçimiyle servis eden efsanevi adreslerden biridir. Dalyan balığından ızgara levreğe, domates soslu midyeden dilim kalamarıya uzanan menüsü, şehrin deniz ürünleri mirasını yaşatmaya devam etmektedir.",
    'de': "Hidden in the old town's narrow streets, Fish Restaurant Proto has been one of Dubrovnik's legendary addresses serving fresh Adriatic fish in its most traditional form since 1886. Its menu stretching from catch-of-the-day grilled sea bass to tomato-sauced mussels and sliced calamari continues to keep the city's seafood heritage alive."},

39: {'d': "Stradum'un yakınında, dar bir sokağın içine saklanmış Lady Pi-Pi, Dubrovnik esnafı ve yerli halkın sırlarını paylaştığı uygun fiyatlı bir Hırvatistan ev yemeği lokantasıdır. Günlük yazılan tahtadaki pašticada (et dolmalı pasta), bakalar (Hırvatistan köftesi) ve ev yapımı vino ile öğle yemeği için en dürüst adres.",
    'de': "Hidden in a narrow lane near the Stradun, Lady Pi-Pi is an affordable Croatian home-cooking restaurant that locals and the city's tradespeople share as their secret. Pašticada (meat-stuffed pasta), bakalar (Croatian meatballs), and homemade vino written on the daily board make it the most honest address for lunch."},

40: {'d': "Eski şehrin en iyi bilinen şarap barı olan D'vino, dar Ulica od Puča'dan içeri girdiğinizde Hırvatistan'ın yedi bölgesinden 100'den fazla şarabı bulabileceğiniz samimi bir mahzen ortamıyla karşılar. Eğitimli sommelierler her şarabı kökeni ve bağla birlikte anlatır; gece programına başlamak için biçilmiş kaftan.",
    'de': "D'vino, the old town's best-known wine bar, welcomes you upon entering the narrow Ulica od Puča with an intimate cellar atmosphere where over 100 wines from Croatia's seven regions can be found. Trained sommeliers explain each wine together with its origin and vineyard; the perfect start for an evening program."},

42: {'d': "Dubrovnik'in surlar dışındaki mahallelerinde, turizmin biraz gerisinde kalan Pantarul, yerel şefin kendi bağından getirdiği doğal şarap ve Adriyatik ürünlerini modern Hırvatistan mutfağı tekniğiyle yorumladığı mekandır. 'Yavaş yemek' felsefesini özümseyen menüsü ve bölgesel malzeme odağıyla şehrin yüksek profilli restoranı olmadan gurme deneyim sunar.",
    'de': "Pantarul, slightly behind the tourism in neighborhoods outside Dubrovnik's walls, is the venue where the local chef interprets natural wine from his own vineyard and Adriatic products with modern Croatian cuisine techniques. With a menu that embodies the 'slow food' philosophy and a regional ingredient focus, it offers a gourmet experience without being the city's high-profile restaurant."},

43: {'d': "Stradum'un karmaşasında nefes almak için sığınılan Otto Street Food, Hırvatistan'ın gündelik deniz ürünleri sandviçlerini, tahini soslu adet kalamariyi ve taze domates soslu makarnayı şehrin en makul fiyatlarına sunar. Kuyruğu her zaman vardır ama beklemeye değer hızlı bir liman aperatifi.",
    'de': "Otto Street Food, a refuge for catching breath amid the Stradun's chaos, offers Croatia's everyday seafood sandwiches, single calamari with tahini sauce, and fresh tomato pasta at the city's most reasonable prices. There is always a queue but it is a fast harbor snack worth the wait."},

45: {'d': "Dubrovnik eski şehrine kendi tek-kökenli filtre kahvesi kültürünü taşıyan Cogito, özenle seçilmiş Afrika ve Güney Amerika çekirdekleriyle hazırlanan pour-over ve chemex sunumlarıyla şehrin en ciddi kahve deneyin sunar. Taş tavanlı, sakin iç mekan atmosferi ve kaliteli kitap rafıyla sabah gürültüsünden kaçmak için ideal.",
    'de': "Cogito, bringing its own single-origin filter coffee culture to Dubrovnik's old town, offers the city's most serious coffee experience with pour-over and chemex presentations prepared with carefully selected African and South American beans. With its stone-ceilinged calm interior atmosphere and quality book shelf, it is ideal for escaping the morning noise."},

62: {'d': "Lapad yarımadasında sahile yakın konumlanan Hotel Adria, şehir merkezinin yoğunluğundan biraz uzakta ama feribot iskelelerine ve plajlara yürüme mesafesinde konforlu bir üs sunar. Sabah kahvaltısındaki taze Hırvatistan pastacılık ürünleri ve terasa vurduğu Adriyatik sabah güneşiyle mükemmel bir günün başlangıcını sağlar.",
    'de': "Hotel Adria near the seafront in Lapad peninsula offers a comfortable base slightly away from the city center's intensity but within walking distance of ferry piers and beaches. Fresh Croatian pastry products at the morning breakfast and Adriatic morning sun striking the terrace provide the perfect start to a day."},

63: {'d': "Dubrovnik'in daha sakin kuzey mahallelerindeki Hotel Ivka, aile ortamı ve uygun fiyat dengesiyle uzun dönem ziyaretçiler ve bütçe bilinçli tatilciler için şehrin verimli seçeneklerinden biridir. Yakın çevredeki market ve yerel kafelerle birleşince, turistik restoranlardan uzak gerçek komşuluk deneyimi yaşatır.",
    'de': "Hotel Ivka in Dubrovnik's quieter northern neighborhoods is one of the city's practical options for long-stay visitors and budget-conscious vacationers with its family atmosphere and affordable price balance. Combined with nearby markets and local cafés, it offers a genuine neighborhood experience away from touristy restaurants."},

65: {'d': "Eski şehrin içinde, tarihi bir binanın içinde yer alan Hotel Stari Grad, surların tam ortasında konaklama deneyimini benzersiz kılan taş merdivenleri, ahşap tavanlı odaları ve kale görünümlü balkonuyla Dubrovnik tarihi mirasının tam kalbinde bir gece için biçilmiş kaftandır.",
    'de': "Located inside the old town within a historic building, Hotel Stari Grad makes the experience of staying within the walls uniquely special with its stone stairways, wooden-ceilinged rooms, and castle-view balconies, tailor-made for a night at the absolute heart of Dubrovnik's historic heritage."},

66: {'d': "Surlar dışında, kayalık kıyıya yakın bir noktada yerleşen Restaurant Marco Polo, taze kalamar ızgarası, Hırvatistan usulü brudet (balık güveci) ve ev yapımı prošek şarabıyla Adriyatik mutfağının en özgün örneklerinden birini şehrin kalabalığından biraz uzakta sunar.",
    'de': "Nestled outside the walls near the rocky coast, Restaurant Marco Polo presents one of the most original examples of Adriatic cuisine slightly away from the city's crowds with fresh grilled calamari, Croatian-style brudet (fish stew), and homemade prošek wine."},

67: {'d': "Bota Šare, Dubrovnik çevresindeki Peljsac yarımadasından gelen taze istiridyeleri ve maki usulü hazırladığı günlük deniz ürünü tabağıyla hem deniz ürünleri tutkunlarına hem de Japon mutfağı meraklılarına aynı anda hitap eden özgün bir konsepttir. Sur içindeki konumu ve açık hava masalarıyla sezonun en keyifli Adriyatik-Asya füzyon adreslerinden biri.",
    'de': "Bota Šare is an original concept that simultaneously appeals to both seafood enthusiasts and Japanese cuisine lovers with fresh oysters arriving from the Pelješac peninsula near Dubrovnik and daily seafood plates prepared maki-style. With its location inside the walls and open-air tables, it is one of the season's most enjoyable Adriatic-Asian fusion addresses."},

69: {'d': "Dubrovnik esnafı ve öğrencilerinin yıllardır sığındığı Buffet Škola, plitko pečenje (sığ ızgara balık), taze domates salatası ve ucuz yerel birasıyla şehrin son derece ekonomik ama gerçek Adriyatik tatlarına erişmenin adreslerindendir. Turizmin biraz gerisinde, eski şehrin sakin bir sokağında saklanmış.",
    'de': "Buffet Škola, to which Dubrovnik's tradespeople and students have retreated for years, is one of the city's addresses for reaching extremely economical yet genuine Adriatic flavors with plitko pečenje (shallow-grilled fish), fresh tomato salad, and cheap local beer. Hidden in a quiet street of the old town, slightly behind the tourist trail."},

70: {'d': "Stradum'un gürültülü yolundan geri çekilip Festival Kafesi'ne sığındığınızda kendinizi Dubrovnik'in gerçek sosyal nabzını tutan bir mekanda bulursunuz. Sabah gazetesini çay eşliğinde okuyanlardan öğleden sonra satranç oynayanlar, akşam serinliğinde aperol spritz içenlere kadar her saatte farklı bir kalabalık çekilir bu küçük meydana.",
    'de': "When you withdraw from the Stradun's noisy road and take refuge in Café Festival, you find yourself in a venue that holds the real social pulse of Dubrovnik. From those reading the morning newspaper with tea to afternoon chess players to those drinking aperol spritz in the evening cool, a different crowd is drawn to this small square at every hour."},

72: {'d': "Eski şehrin dar merdivenli sokaklarına sıkışmış Spaghetteria Toni, 30 yılı aşkın süredir Dubrovnik sakinlerinin taze makarna ve deniz ürünleri için güvendiği sade ama özgün bir İtalyan-Hırvatistan lezzet buluşmasıdır. Günlük spesyal, miktarı sınırlı ev yapımı linguine ve günün taze balığıyla her gün biraz farklı gelir bu küçük masalara.",
    'de': "Squeezed in the narrow stairway streets of the old town, Spaghetteria Toni has been the trusted spot for fresh pasta and seafood for Dubrovnik residents for over 30 years, a simple yet original Italian-Croatian flavor encounter. The daily special arrives at these small tables slightly differently each day with limited homemade linguine and the day's fresh catch."},

73: {'d': "Gatsby Restaurant, sur içindeki popüler Stradum'dan girilen dar bir sokakta, sakin bir avluda yer alıyor. Hırvatistan usulü çikara (et çorbası), karides risotto ve taze hazırlanan jastog (Adriyatik ıstakoz) yemekleriyle şehrin en soyguna dönüşmeden gurme deneyimi sunan adreslerinden biri olarak öne çıkıyor.",
    'de': "Gatsby Restaurant is located in a quiet courtyard down a narrow lane off the popular Stradun inside the walls. It stands out as one of the city's addresses offering a gourmet experience without becoming a tourist trap with Croatian-style čikara (meat soup), shrimp risotto, and freshly prepared jastog (Adriatic lobster)."},

74: {'d': "Eski şehrin akşam saatlerinde keyifli bir İtalyan lokantası olan Margherita, ince hamurlu pizzasıyla öne çıkan Dubrovnik'teki İtalyan ev mutfağı temsilcisidir. Taş fırından çıkan Napoli usulü pizza margarita ve taze rucola salatası, Adriyatik akşamlarını İtalyan bir sıcaklıkla renklendiriyor.",
    'de': "Margherita, a pleasant Italian restaurant in the old town's evening hours, is the representative of Italian home cuisine in Dubrovnik, standing out with its thin-crust pizza. Neapolitan-style pizza margherita from a stone oven and fresh arugula salad add Italian warmth to Adriatic evenings."},

78: {'d': "Sur içindeki bu butik restoran ve şarap bar kombinasyonu, Adriyatik sahillerinden ve Hırvatistan bağlarından özenle derlenen 200'den fazla etiketle yerel şarap turizmini geliştirmeye çalışıyor. Her şarabın yanında önerilen küçük meze tabağı ve şarap yazısının tadına bakma seçeneği, hem bilgili hem meraklı ziyaretçilere hitap ediyor.",
    'de': "This boutique restaurant and wine bar combination inside the walls works to develop local wine tourism with over 200 carefully curated labels from Adriatic coasts and Croatian vineyards. A small mezze plate recommended alongside each wine and the option to taste before selecting appeals to both knowledgeable and curious visitors."},

80: {'d': "Dubrovnik'in sur dışı mahallelerinden birinde saklanan Zuzori, sezonun kalabalığına maruz kalmadan şehrin özgün Dalmaçya mutfağını tatmak isteyenler için sessiz bir aile restoranıdır. Pašticada, punjene lignje (dolmalı kalamari) ve ev yapımı prošek desseri, Dubrovnik'teki yılın dörtmevsim ziyaretçilerin tercih ettiği adreslerden biridir.",
    'de': "Hidden in one of Dubrovnik's neighborhoods outside the walls, Zuzori is a quiet family restaurant for those wanting to taste the city's original Dalmatian cuisine without exposure to the season's crowds. Pašticada, punjene lignje (stuffed calamari), and homemade prošek dessert make it one of the addresses preferred by year-round Dubrovnik visitors."},

81: {'d': "Sur içindeki bu biradan kışkırtıcı isimli mekan, yerel Karlovačko, Ozujsko ve Hırvatistan craft birası seçenekleriyle şehrin en özgün bira barı olarak öne çıkıyor. Açık hava masaları ve dışarıdan içeriye sızan Adriyatik akşam esintisiyle, yemek öncesi ya da kültür turu sonrası mola için ideal.",
    'de': "This provocatively named beer-focused venue inside the walls stands out as the city's most original beer bar with local Karlovačko, Ožujsko, and Croatian craft beer selections. With outdoor tables and the Adriatic evening breeze seeping in from outside, it is ideal for a pre-dinner or post-culture-tour break."},

82: {'d': "Dubrovnik'teki BodyMove, şehrin yoğun tatil programından dingin bir kopmayı öneriyor; yoga, pilates veya spor salonu seansı için şehir merkezine yürüme mesafesinde modern bir fitness ve yoga stüdyosu olarak hizmet veriyor. Uzun bir yürüyüş turu ya da surlar etrafında koşma sonrası kasları gevşetmek için şehrin en işlevsel durağı.",
    'de': "BodyMove in Dubrovnik offers a tranquil break from the city's intense holiday program; serving as a modern fitness and yoga studio within walking distance of the city center for yoga, pilates, or gym sessions. The city's most functional stop for loosening muscles after a long walking tour or a run around the walls."},

84: {'d': "Dubrovnik sur içindeki Time Bar, Hırvatistan'ın iyi seçilmiş yerel derin limonata ve rakia seçenekleri, canlı müzik ve açık avlusuyla akşamları şehrin en samimi sosyal köşelerinden birine dönüşür. Eski şehrin pahalı restoranlarından kaçıp sakin bir içki istemek için pratik ve sahici bir alternatiftir.",
    'de': "Time Bar inside Dubrovnik's walls transforms in the evenings into one of the city's most sincere social corners with Croatia's well-selected local deep lemonade and rakia options, live music, and its open courtyard. A practical and genuine alternative for escaping the old town's expensive restaurants and wanting a quiet drink."},

85: {'d': "Eski şehrin sakin arka sokaklarından birindeki Amor, sabah demli kahvesinden gece geç saatteki aperitife kadar saat fark etmeksizin insanları ağırlayan köklü bir Dubrovnik kafe-baridir. Yerel halkın yıllarca uğradığı bu mekan, turistik gürültünün biraz dışında kalan gerçek şehir yaşamının bir parçasıdır.",
    'de': "Amor in one of the old town's quiet back streets is a deep-rooted Dubrovnik café-bar that welcomes people regardless of the hour, from morning strong coffee to a late-night aperitif. A frequented spot by locals for years, this venue is part of the real city life that sits slightly outside the touristy noise."},

86: {'d': "Dubrovnik'in sur dışı mahallelerinde, motosiklet ve bisiklet kültürünü kafe atmosferiyle birleştiren Bikers Cafe, şehrin konvansiyonel turizminden tamamen farklı bir sosyal doku ve deneyim sunuyor. Duvarları kaplayan vintage otomobil ve motosiklet posterlerinin arasında yerel bira ve basit atıştırmalıklarla keyifli bir mola yaşanır.",
    'de': "In Dubrovnik's neighborhoods outside the walls, Bikers Cafe combines motorcycle and bicycle culture with café atmosphere, offering a social fabric and experience completely different from the city's conventional tourism. An enjoyable break can be had with local beer and simple snacks among vintage car and motorcycle posters covering the walls."},

88: {'d': "Dubrovnik'e özgü 'yavaş kahve' kültürünü yeniden keşfettiren GreenGo, filtre kahve ve matcha latte alternatifleriyle birlikte şekersiz taze meyve suları ve bitki çaylarıyla eski şehirde sağlıklı beslenme arayan ziyaretçilere benzersiz bir durak sunuyor. Açık hava masaları ve organik menü yaklaşımıyla kahveye dair beklentileri yeniden tanımlıyor.",
    'de': "GreenGo, rediscovering Dubrovnik's own 'slow coffee' culture, offers a unique stop for health-conscious visitors in the old town with sugar-free fresh fruit juices and herbal teas alongside filter coffee and matcha latte alternatives. It redefines coffee expectations with its outdoor tables and organic menu approach."},

89: {'d': "Dubrovnik'in sur içindeki bu butik şarap dükkanı, özellikle Dalmaçya ve Pelješac yarımadasının az tanınan etikettlerini ön plana çıkaran, gerçek Hırvatistan şarap kültürünü yaşatan nadir adreslerden biridir. Ev sahibiyle yapılan kısa bir sohbet, hangi şarabı alacağınıza karar vermenin en keyifli yoluna dönüşür.",
    'de': "This boutique wine shop inside Dubrovnik's walls is one of the rare addresses that brings the little-known labels of Dalmatia and the Pelješac peninsula especially to the fore, preserving genuine Croatian wine culture. A short conversation with the owner becomes the most enjoyable way to decide which wine to purchase."},

90: {'d': "Dubrovnik eski şehrinin sakin bir köşesindeki bu kafe-bar, sabah erken saatte demlenmiş Hırvatistan kahvesi içen yerel esnaf ve öğrencilerle dolup taşar. Turizmin biraz dışında kalan bu küçük mekanda oturup mahalle yaşamını izlemek, şehri turizmden bağımsız bir bakış açısıyla görmek için kıymetli bir deneyimdir.",
    'de': "This café-bar in a quiet corner of Dubrovnik's old town fills with local tradespeople and students drinking strongly brewed Croatian coffee in the early morning. Sitting in this small venue slightly outside tourism and watching neighborhood life is a valuable experience for seeing the city from a perspective independent of tourism."},

91: {'d': "Dubrovnik surları üzerinde, St. Peter Burç'una bakan konumuyla bu kafe, şehre özgü deneyim listesinin üst sıralarında yer alır. Sur yürüyüşü sırasında burada oturup eski şehir çatılarına ve Adriyatik'e bakmak, Dubrovnik'te yaşayan insanlara özgü gündelik lüksü ziyaretçiye de tattıran anlardandır.",
    'de': "This café on Dubrovnik's walls facing St. Peter's Bastion occupies the top of the city's unique experience list. Sitting here during the wall walk and gazing at the old town rooftops and Adriatic is one of the moments that lets visitors taste the everyday luxury unique to those who live in Dubrovnik."},

97: {'d': "Eski şehrin yüksek bir noktasında, kalabalığın biraz dışında konumlanan bu restoran, taş terası ve serbest Adriyatik manzarasıyla öğle yemeği için keyifli bir durak oluşturuyor. Dalmaçya ızgara balığı ve günlük risotto sürprizleri, hem yerel hem de yabancı müdavim kitlesini sadık kılan unsurlardır.",
    'de': "Located at a high point of the old town slightly outside the crowds, this restaurant forms a pleasant lunch stop with its stone terrace and open Adriatic view. Dalmatian grilled fish and daily risotto surprises are the elements that keep both local and foreign regular clientele loyal."},

108: {'d': "Dubrovnik'in koruyucu azizi Aziz Vlaho'ya adanmış bu kafe-bar, eski şehrin korunaklı bir köşesinde hem yerlilerin hem de sakin bir ortam arayan ziyaretçilerin uğradığı, şarap ve rakiyle desteklenen samimi bir atmosfer taşır. Sur içindeki gürültüyü geride bırakıp soluklanan küçük kaçamak noktası.",
    'de': "This café-bar dedicated to Saint Vlaho, Dubrovnik's patron saint, is in a sheltered corner of the old town carrying a sincere atmosphere supplemented by wine and rakia, frequented by both locals and visitors seeking a calm environment. A small escape point where you leave the noise inside the walls behind and breathe."},

117: {'d': "Dubrovnik'te Hard Rock Cafe, Stradum'un ucundaki konumuyla geleneksel Adriyatik mutfağından farklı bir deneyim sunuyor. Rock müzik tarihi temalı dekorasyonu, burger ve patatesi güvenilir kalitesiyle bir araya getiren global marka, şehrin tarihi dokundan biraz farklılaşan alternatif bir akşam durağı olarak öne çıkıyor.",
    'de': "Hard Rock Cafe in Dubrovnik, at the end of the Stradun, offers a different experience from traditional Adriatic cuisine. The global brand combining rock music history-themed decoration with burgers and fries at reliable quality stands out as an alternative evening stop that differentiates slightly from the city's historic fabric."},

136: {'d': "Dubrovnik'in batı çepherinde yer alan Velika ve Mala Petka Orman Parkı, turistik şehir merkezinin gürültüsünden sadece yarım saat uzakta, yoğun çam ve meşe ormanları içinde sakin bir doğa yürüyüşü imkânı sunar. Denize inen patikalar, gözetleme noktaları ve çevrenin yeşilliği şehir ziyaretini tamamlayan özgün bir soluklanma noktası oluşturur.",
    'de': "Velika and Mala Petka Forest Park on Dubrovnik's western edge offers a tranquil nature walk opportunity in dense pine and oak forests just half an hour from the touristic city center's noise. The paths descending to the sea, observation points, and the surrounding greenery form an original breathing point that completes a city visit."},

141: {'d': "Lapad sahilindeki Hotel More, özel kayalık iskelesi ve denize sıfır sonsuzluk havuzuyla şehrin en seçkin konaklama deneyimlerinden birini sunar. Sabah güneşinin denizde yansımaları ve öğle yemeğinin deniz üstü terastan alınan manzarayla burada geçirilen her saat keyifli bir tatil niteliğindedir.",
    'de': "Hotel More on Lapad's waterfront offers one of the city's most exclusive accommodation experiences with its private rocky jetty and sea-level infinity pool. Every hour spent here is a quality holiday with the morning sun's reflections on the sea and the view taken from the over-water terrace at lunch."},

143: {'d': "Dubrovnik'in sur dışındaki mahallelerindeki Pivnica Dubrava, Hırvatistan'ın köklü yerel birasını soğuk bardakta sunan, şehrin pek az bira mabedinden biri olarak Adriyatik tatilinin en keyifli bira molalarından birini yaşatıyor. Fıçıdan çekilen Karlovačko ve yanında mangal üzerinde pişirilmiş kielbasa ile gerçek bir Hırvatistan bira kültürü deneyimlenir.",
    'de': "Pivnica Dubrava in Dubrovnik's neighborhoods outside the walls is one of the city's few beer shrines serving Croatia's deep-rooted local beer in a cold glass, delivering one of the Adriatic holiday's most enjoyable beer breaks. Real Croatian beer culture is experienced with Karlovačko drawn from the tap accompanied by kielbasa grilled over charcoal."},

147: {'d': "Dubrovnik'te Koreli mutfağını temsil eden az sayıdaki mekandan biri olan Bonto Korean Restaurant, bibimbap, kimchi çorbası ve bulgogi yemekleriyle şehrin alternatif mutfak haritasında öne çıkmıştır. Uzun Adriyatik deniz turu sonrasında farklı bir lezzet arayanlar için şehrin küçük ama etkileyici global yemek sahnesini temsil ediyor.",
    'de': "One of the few venues representing Korean cuisine in Dubrovnik, Bonto Korean Restaurant stands out on the city's alternative culinary map with bibimbap, kimchi soup, and bulgogi dishes. After a long Adriatic boat tour, it represents the city's small but impressive global dining scene for those seeking a different flavor."},

148: {'d': "Dubrovnik'in sur dışı kesiminde yüksek bir arazide kurulan Restoran Sphere, panoramik Adriyatik manzarası ve Dalmaçya'ya özgü ızgara balık menüsüyle şehrin manzara restoranları arasında öne çıkmaktadır. Gün batımında kırmızıya boyanan denizi cam arkasından izlemek, yemeği ikincil plana atıp manzaraya odaklanmanızı sağlar.",
    'de': "Restoran Sphere, established on high terrain outside Dubrovnik's walls, stands out among the city's view restaurants with panoramic Adriatic views and a Dalmatian-style grilled fish menu. Watching the sea turn red at sunset from behind the glass makes you push the food to second place and focus on the view."},

150: {'d': "Dubrovnik'in Pile mahallelerindeki Peppers Eatery, Hırvatistan gündelik mutfağının en samimi versiyonlarını biber çeşnisi ve çapraz Akdeniz malzemeleriyle harmanlayan iddialı bir gayriresmi restoran olarak öne çıkıyor. Günlük değişen menüsü ve oldukça küçük kapasitesi nedeniyle masa bulmak kolay olmadığından önceden rezervasyon şart.",
    'de': "Peppers Eatery in Dubrovnik's Pile neighborhood stands out as an ambitious informal restaurant that blends the most sincere versions of Croatian everyday cuisine with pepper seasoning and cross-Mediterranean ingredients. Since finding a table is not easy due to its daily changing menu and very small capacity, advance reservations are essential."},

152: {'d': "Adriyatik kıyısındaki bir kayalıkta konumlanan Mezzanave, deniz üzerindeki ahşap iskelesi ve taze deniz ürünleriyle Dubrovnik yakınlarındaki en sürükleyici sahil yemek deneyimlerinden birini sunuyor. Yemek masaları kayalıklardan sadece birkaç metre yüksektedir; dalgaların altınızda kırılması sırasında ıstakoz yemek bu mekana özel bir deneyimdir.",
    'de': "Mezzanave, located on a cliff on the Adriatic coast, offers one of the most immersive waterfront dining experiences near Dubrovnik with its wooden pier over the sea and fresh seafood. Dining tables are just a few metres above the rocks; eating lobster while waves break below you is an experience unique to this venue."},

156: {'d': "Dubrovnik'in Lapad bölgesindeki Solitudo, marina kıyısındaki terasyı ve yerel Dalmaçya mezeleri-ızgara balığı menüsüyle turistik şehir merkezine gitmeksizin gerçek Hırvatistan tatlarına ulaşmanın en erişilebilir adreslerinden biridir. Özellikle yerel halkın tercih ettiği bu mekan, sezon boyunca dolu olmasına rağmen kalabalık değil.",
    'de': "Solitudo in Dubrovnik's Lapad district is one of the most accessible addresses for reaching genuine Croatian flavors without going to the touristy city center, with its marina-side terrace and local Dalmatian mezze-grilled fish menu. Particularly preferred by locals, this venue is full throughout the season but not crowded."},

160: {'d': "Eski şehirde alışverişle geçen saatlerin ardından sığınılan Fashion Cafe, şık ama rahat dekorasyonu ve yaratıcı kokteyl listesiyle hem alışveriş molası hem de akşam başlangıcı için ideal bir çift amaçlı durak sunuyor. Sur içindeki en sakin köşelerden birinde yer alıyor.",
    'de': "Fashion Cafe, a refuge after hours spent shopping in the old town, offers an ideal dual-purpose stop for both a shopping break and an evening start with its stylish but comfortable décor and creative cocktail list. Located in one of the quietest corners inside the walls."},

163: {'d': "İtalyan ve Hırvatistan geleneğinden ilham alan Koogla, Dubrovnik'in en dikkat çeken dondurma dükkanı olarak öne çıkıyor. Portakal çiçeği aromalı beyaz çikolata, lavanta-böğürtlen karışımı ve taze narenciyeli sorbeler, Adriyatik sıcağında tüketilen en mükemmel serinletici bileşimlerini oluşturuyor.",
    'de': "Inspired by Italian and Croatian tradition, Koogla stands out as Dubrovnik's most attention-grabbing ice cream shop. Orange blossom-flavored white chocolate, lavender-blackberry blend, and fresh citrus sorbets form the most perfect refreshing combinations consumed in the Adriatic heat."},

164: {'d': "Sur içindeki bu küçük kafe, adını Hırvatçada 'küçük kantin' anlamına gelen kelimeden alıyor. Sabah balık çorbasından öğle makarna spesyaline kadar küçük bir menüyle çalışan bu mekan, şehrin en dürüst ev yemeği deneyin sunan nadir köşelerinden biridir; oturma kapasitesi çok sınırlı.",
    'de': "This small café inside the walls takes its name from the Croatian word meaning 'small canteen.' Operating with a small menu from morning fish soup to afternoon pasta special, this venue is one of the city's rare corners offering the most honest home cooking experience; seating capacity is very limited."},

167: {'d': "Eski şehrin çepherinde, biraz unutulmuş bir sokakta bulunan What's Up Kaffe Bar, sabah gazetesini içki eşliğinde okuyan yerel halkın tercih ettiği, turizmden bağımsız otantik bir şehir köşesi sunuyor. Herhangi bir saatte içeri girdiğinizde kendinizi Dubrovnik'in reklamsız, gerçek hayatının içinde bulursunuz.",
    'de': "Caffe Bar What's Up in a slightly forgotten street on the edge of the old town offers an authentic city corner independent of tourism, preferred by locals reading the morning paper with a drink. Entering at any hour, you find yourself inside Dubrovnik's unadvertised real life."},

169: {'d': "Kroatya'nın en sevilen yerel bira markası Karlovačko'ya adanmış bu mekan, Dubrovnik'te bira geleneğini şehrin gündelik hayatıyla buluşturan samimi bir yerdir. Fıçı birasının yanında servis edilen çıtır çipura balığı ve yerel atıştırmalıklar, öğleden sonra ya da akşam serinliğinde mükemmel bir kombinasyon oluşturuyor.",
    'de': "This venue dedicated to Karlovačko, Croatia's most beloved local beer brand, is a sincere place in Dubrovnik that brings beer tradition together with the city's everyday life. Crispy sea bream fish and local snacks served alongside draft beer form a perfect combination in the afternoon or evening cool."},

190: {'d': "Dubrovnik'in sur dışı mahallesindeki bu bahçeli kafe, şehrin taş yapılarından kaçıp biraz yeşilliğe sığınmak isteyenler için sakince geçirilen bir kahve saatini sağlıyor. Yerel otlarla tatlandırılmış kek, taze portakal suyu ve komşu görünümüyle bu mekan, şehrin bir parçası olmaktan daha çok mahallenin organik bir uzantısı gibi duruyor.",
    'de': "This garden café in Dubrovnik's neighborhood outside the walls provides a peacefully spent coffee hour for those wanting to escape the city's stone structures and find a little greenery. With local herb-flavored cake, fresh orange juice, and a neighborhood view, this venue feels more like an organic extension of the neighborhood than a part of the city."},

191: {'d': "Dubrovnik yakınlarında, şehrin gündelik lojistik akışının dışında bir yerde saklanan Ferata, taze yakalanmış balığı mangal veya fırında pişirip yanında ev yapımı pekmez reçeli ve taze ekmekle sunan sade bir aile balık lokantasıdır. Adalılar ve yerel balıkçıların bildiği ama turistlerin henüz tam keşfedemediği bu mekanda yemek sıradan değil.",
    'de': "Hidden near Dubrovnik, away from the city's everyday logistical flow, Ferata is a simple family fish restaurant that grills or oven-bakes freshly caught fish and serves it with homemade molasses preserve and fresh bread. Dining here, known to islanders and local fishermen but not yet fully discovered by tourists, is anything but ordinary."},

192: {'d': "Eski şehirde, taş duvarlarla çevrili bir avluda faaliyet gösteren Dvorište TUP, hem eski şehrin ruhunu hem de modern Hırvatistan kokteyl kültürünü aynı çatı altında buluşturuyor. Hırvatça 'avlu' anlamına gelen adıyla uyumlu biçimde, yıldızların altında içki içmek için Dubrovnik'in en şiirsel mekan seçeneklerinden biri.",
    'de': "Operating in a courtyard surrounded by stone walls in the old town, Dvorište TUP brings both the old town's spirit and modern Croatian cocktail culture under the same roof. In keeping with its name meaning 'courtyard' in Croatian, it is one of Dubrovnik's most poetic venue options for drinking under the stars."},
}

apply_batch('dubrovnik.json', U)
