import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

# ── KSAMIL ────────────────────────────────────────────────────────────────────
ksamil = {
2:  {'t': "Ksamil köyü, Haziran başı ve Eylül ortasında Ağustos kalabalığının onda biri kadar ziyaretçiyle aynı kristal denizi sunar; bu dönemlerde hem fiyatlar hem mekan erişimi çok daha uygun.",
     'te': "Ksamil village offers the same crystal sea with a tenth of August's crowd in early June and mid-September; both prices and venue access are much more convenient during these periods."},
3:  {'t': "Mirror Beach, adın hakkını veren cam gibi sakin suyu için sabah 08:00-10:00 arası idealdir; bu saatte su düz ayna gibi yansıtır ve fotoğraf mükemmeldir.",
     'te': "Mirror Beach is ideal between 8-10am for its glass-calm water that lives up to its name; at this hour the water reflects like a flat mirror and photography is perfect."},
7:  {'t': "Korfu Yelkencilik Merkezi'nin kursları ve kiralıkları hem Yelkenci hem kitesurf için uygundur; İyonya Denizi'nin meltem koşulları Ksamil civarında iyi performans sağlar.",
     'te': "Corfu Sailing Centre's courses and rentals are suitable for both sailing and kitesurfing; the Ionian Sea's Meltemi conditions provide good performance around Ksamil."},
9:  {'t': "Poda Adası'na Ksamil'den küçük teknelerle 10-15 dakikada ulaşılır; sabah erkenci tekne sahipleriyle pazarlık yapın, öğle sonrası adaya gelen tekne sayısı artar.",
     'te': "Poda Island is reached from Ksamil in 10-15 minutes by small boat; bargain with early morning boat owners, the number of boats arriving at the island increases after noon."},
10: {'t': "Ksamil Ana Plajı, yazın çok kalabalık olduğundan sabah 08:30 öncesinde yer tutmak şarttır; şezlong kiralamaları erken saatlerde listelenen ücretin altında pazarlığa açıktır.",
    'te': "Ksamil Main Beach is very crowded in summer so reserving a spot before 8:30am is essential; sun lounger rentals in the early hours are open to bargaining below the listed price."},
11: {'t': "Rilinda Beach, Ksamil'in kalabalık ana plajına alternatif olarak biraz daha sakin bir koy sunar; sabah erken ve öğleden sonra geç saatlerde neredeyse boş bulunabilir.",
    'te': "Rilinda Beach offers a somewhat quieter cove as an alternative to Ksamil's crowded main beach; it can be found almost empty in the early morning and late afternoon."},
12: {'t': "Heart of Ksamil, adacıklara bakan sahil şeridinde konumlanan bar ve lounge alanıdır; gün batımını izlemek için en önce masaları dolduğundan en az 1 saat öncesinden gidin.",
    'te': "Heart of Ksamil is the bar and lounge area located on the seafront overlooking the islets; arrive at least 1 hour in advance as the tables fill first for watching the sunset."},
13: {'t': "Ksamil Ana Plajı'na araçla girerken park yeri sabah 09:00'da doluyor; erken gelin ya da Ksamil köyünden yürüyerek gelin.",
    'te': "When entering Ksamil Main Beach by car, the car park fills by 9am; arrive early or come on foot from Ksamil village."},
14: {'t': "Bora Bora Beach, adacık manzaralı konumuyla Ksamil'in en fotoğrafenik plajlarından biridir; şezlong rezervasyonu için sabah erken ya da online sistem mevcutsa önceden rezerve edin.",
    'te': "Bora Bora Beach is one of Ksamil's most photogenic beaches with its islet view; reserve early morning or in advance via online system if available for sun lounger reservation."},
15: {'t': "Ksamil Halk Plajı, ücretli plaj kulüplerinin yanında tamamen ücretsiz alanlar da sunar; sabah erken saatlerde gelin, öğleden sonra kalabalık halk plajını çekilmez hale getirir.",
    'te': "Ksamil Public Beach offers completely free areas alongside paid beach clubs; come early morning, in the afternoon crowds make the public beach unbearable."},
16: {'t': "Ksamil'in Ukraynaca 'Ксаміль' adıyla bilinen popülerliği özellikle Doğu Avrupalı turistler arasında yüksektir; Temmuz-Ağustos arası Ukraynalı ve Polonyalı ziyaretçi yoğunluğu belirgindir.",
    'te': "Ksamil's popularity known as 'Ксаміль' in Ukrainian is particularly high among Eastern European tourists; Ukrainian and Polish visitor density is noticeable between July-August."},
17: {'t': "Chill Island Flow, sakin bir atmosfer ve iyi müzikle Ksamil'de farklı bir bar deneyimi sunar; gün batımı saatlerinde deniz manzaralı masa için önceden gidin.",
    'te': "Chill Island Flow offers a different bar experience in Ksamil with a calm atmosphere and good music; arrive in advance for a sea-view table during sunset hours."},
18: {'t': "Ksamil plajlarında cankurtaranlar belirli mevsimlerde görev yapmaktadır; cankurtaran olmayan saatlerde özellikle çocuklarla denize girerken sahilden uzaklaşmayın.",
    'te': "Lifeguards are on duty in Ksamil beaches during certain seasons; especially when entering the sea with children during hours without a lifeguard, don't stray from the shore."},
19: {'t': "Tongo Adası tekne turu için Ksamil iskelesinden kalkışlar sabah 09:00-10:00 arası başlar; kombine turda Butrint Arkeoloji Alanı ziyareti de eklenebilir.",
    'te': "Departures for Tongo Island boat tours start between 9-10am from Ksamil pier; a visit to Butrint Archaeological Site can also be added to the combined tour."},
21: {'t': "Ksamil plajları arasında adanın en sessiz köşelerinden biri olan bu kumsal, özellikle Butrint koruma bölgesine yakınlığı nedeniyle gelişmemiş doğal yapısını korur.",
    'te': "This sandy beach, one of the island's quietest corners among Ksamil beaches, preserves its undeveloped natural structure especially due to its proximity to the Butrint conservation area."},
22: {'t': "Bu küçük beyaz kumlu koy, Ksamil'in az bilinen gizli köşelerinden biridir; tekne ya da yürüyüş yoluyla ulaşabilirsiniz.",
    'te': "This small white sandy cove is one of Ksamil's little-known hidden corners; you can reach it by boat or on foot."},
23: {'t': "Bu kayalık ada fotoğrafı için sabah ışığı en idealdir; Ksamil adacıklarına yönelik tekne turlarında bu noktaya da uğranır.",
    'te': "Morning light is most ideal for photographing this rocky island; boat tours toward Ksamil islets also stop at this point."},
24: {'t': "Ksamil'in Instagram'da en çok paylaşılan noktaları genellikle adacıklar arasındaki sığ turkuaz geçitlerdir; sabah 07:30-09:00 arası fotoğraf için tek başınıza bu noktaları yakalayabilirsiniz.",
    'te': "Ksamil's most shared Instagram spots are usually the shallow turquoise passages between the islets; between 7:30-9am you can capture these spots alone for photography."},
25: {'t': "Isola delle Ninfe (Nimfalar Adası), Ksamil adacıklarından biridir; turlar buraya uğrar, küçük teknelerle yüzme durağı olarak kullanılır.",
    'te': "Isola delle Ninfe (Island of the Nymphs) is one of the Ksamil islets; tours stop here and small boats use it as a swimming stop."},
26: {'t': "Sheqer Göl Parkı, Ksamil çevresindeki az bilinen tatlı su ve sazlık alanıdır; kuş gözlemi için erken sabah ve öğleden sonra geç saatler en uygun dönemdir.",
    'te': "Sheqer Lake Park is the little-known freshwater and reed area around Ksamil; early morning and late afternoon are the most suitable periods for birdwatching."},
67: {'t': "Greg Lounge, Ksamil'de sakin bir akşam geçirmek isteyenler için uygun atmosferiyle öne çıkan bir mekandır; hafif kokteyller ve deniz manzarası eşliğinde sakin bir gece için iyi bir tercih.",
    'te': "Greg Lounge stands out as a suitable atmosphere for those wanting to spend a quiet evening in Ksamil; a good choice for a calm evening accompanied by light cocktails and sea views."},
68: {'t': "Muzg Lounge, Ksamil'in canlı lounge bar sahnesinde müzik ve deniz manzarasını birleştiren bir mekandır; yaz akşamları sahil boyunca açık hava oturumları düzenlenir.",
    'te': "Muzg Lounge is a venue that combines music and sea views in Ksamil's lively lounge bar scene; open-air sessions are organized along the beach on summer evenings."},
69: {'t': "3 Island Lounge Bar, adının da işaret ettiği gibi Ksamil adacıklarına bakan bir konumdadır; gün batımı saatlerinde en güzel renkleri yakalamak için erken bir masa ayırtın.",
    'te': "3 Island Lounge Bar is in a position overlooking the Ksamil islets as its name suggests; book an early table to catch the most beautiful colors during sunset hours."},
70: {'t': "Chill Out, Ksamil'de günübirlik plaj konaklamasının ardından saat 17:00-19:00 arasında aperitif için en uygun lounge'lardan biridir.",
    'te': "Chill Out is one of the most suitable lounges for an aperitif between 5-7pm after a day of beach time in Ksamil."},
71: {'t': "Noctura Lounge, adanın gece ilerledikçe canlanan lounge bar mekanlarından biridir; DJ müziği ve hafif yemekleri için gece 21:00-00:00 arası en aktif saatlerdir.",
    'te': "Noctura Lounge is one of the island's lounge bar venues that comes alive as the night progresses; between 9pm-midnight are the most active hours for DJ music and light meals."},
72: {'t': "Bu isimsiz nargile lounge, Ksamil'de sakin bir nargile deneyimi arayanlar için samimi bir mekandır; taze meyve nargile çeşitleri mevcuttur.",
    'te': "This nameless hookah lounge is a sincere venue for those seeking a quiet hookah experience in Ksamil; fresh fruit hookah varieties are available."},
75: {'t': "Vamos Cocktail Bar, Ksamil'in en yaratıcı kokteyl menülerinden birine sahip mekandır; tropik malzemeleri ve arnavut yapımı rakı bazlı karışımları mutlaka deneyin.",
    'te': "Vamos Cocktail Bar has one of Ksamil's most creative cocktail menus; definitely try the tropical ingredients and Albanian-made raki-based mixes."},
76: {'t': "Corner Bar-Lounge, adından da anlaşıldığı gibi köşe konumuyla iki cepheden de deniz manzarasına sahip bir mekandır; özellikle akşamüstü serin esintili saatlerde keyiflidir.",
    'te': "Corner Bar-Lounge, as understood from its name, has a sea view from both facades with its corner position; particularly enjoyable during the cool breeze hours of the late afternoon."},
78: {'t': "Dips Lounge, sushi ve kokteyller ile Ksamil'de daha sofistike bir akşam deneyimi arayanlar için öne çıkan bir mekandır; rezervasyon önerilir.",
    'te': "Dips Lounge stands out for those seeking a more sophisticated evening experience in Ksamil with sushi and cocktails; reservation is recommended."},
79: {'t': "Bliss Lounge Bar, Ksamil sahilinde sakin bir konumda adacık manzarasıyla aperol spritz içmek için ideal bir mekandır.",
    'te': "Bliss Lounge Bar is an ideal venue for drinking aperol spritz with an islet view in a calm location on Ksamil's beach."},
82: {'t': "Sunset Beach Bar, adından da anlaşıldığı gibi gün batımını izlemek için kurulmuş bir mekandır; Ksamil adacıklarının arka planında Yunanistan kıyılarına batan güneş burada en güzel görülür.",
    'te': "Sunset Beach Bar is a venue built for watching the sunset as its name suggests; the sun setting to the Greek coastline with Ksamil islets in the background is best seen here."},
83: {'t': "Kuga Beach Bar, Ksamil'de plaj başı oturum için güvenilir bir seçenektir; şezlong ve kokteylle birlikte günü geçirmek için hafta içi öğle öncesi en sakin saatlerdir.",
    'te': "Kuga Beach Bar is a reliable option for a beachside sitting session in Ksamil; the calmest hours for spending the day with sun lounger and cocktail are weekday mornings before noon."},
84: {'t': "Orion Beach Bar, Ksamil sahilinde hem yiyecek hem içecek hizmeti sunan bir plaj barıdır; taze balık ve deniz ürünleri için öğle saatlerinde uğramaya değer.",
    'te': "Orion Beach Bar is a beach bar in Ksamil offering both food and drink service; worth stopping by at lunchtime for fresh fish and seafood."},
}
apply_batch('ksamil.json', ksamil)

# ── SELANİK ───────────────────────────────────────────────────────────────────
selanik = {
1:  {'t': "Aristoteles Meydanı, Selanik'in en büyük ve en canlı meydanıdır; sabah erken saatlerde çevre kafeler açılır, öğleden sonra deniz tarafına uzanan yürüyüş yolu canlanır.",
     'te': "Aristotelous Square is Thessaloniki's largest and most vibrant square; surrounding cafés open in the early morning, the waterfront promenade extending toward the sea comes alive in the afternoon."},
2:  {'t': "Ano Poli, Selanik'in Osmanlı döneminden kalma ahşap konsol evleri ve dar sokaklarıyla en özgün mahallesidir; sabah 09:00-11:00 arası sakin sokaklarda yürümek en keyifli ziyaret saatidir.",
     'te': "Ano Poli is Thessaloniki's most original neighborhood with Ottoman-era wooden bay-windowed houses and narrow streets; walking in the quiet streets between 9-11am is the most enjoyable visiting hour."},
3:  {'t': "Rotonda, MS 4. yüzyıldan kalma olağanüstü korunmuş bir Roma anıtıdır; giriş ücretlidir. İçindeki mozaik kalıntıları için yakın bakış yapmak üzere rehberli tur öneririm.",
     'te': "The Rotonda is a remarkably preserved Roman monument from the 4th century AD; entry is paid. I recommend a guided tour to get a close look at the mosaic remains inside."},
4:  {'t': "Aziz Demetrius Kilisesi, şehrin koruyucu azizine adanmış 5. yüzyıldan kalma bazilika kilisesidir; yeraltı kriptası ayrıca ücretlidir ama Bizans tarih katmanları için ziyarete değer.",
     'te': "Church of Saint Demetrius is a 5th-century basilica church dedicated to the city's patron saint; the underground crypt is separately paid but worth a visit for Byzantine history layers."},
5:  {'t': "Ladadika, eski yağ depolarının dönüştürüldüğü Selanik'in en canlı akşam meydanıdır; Cuma ve Cumartesi akşamları taverna ve bar sahnesini en iyi haliyle sunar.",
     'te': "Ladadika is Thessaloniki's most vibrant evening square converted from old oil warehouses; Friday and Saturday evenings present the taverna and bar scene at its best."},
8:  {'t': "Heptapyrgion, Bizans ve Osmanlı dönemlerinden kalma yedi kuleli kalenin gündoğumu ve gün batımı manzarası için en değerli ziyaret saatleri sabah 08:00-09:30 arasıdır.",
     'te': "The most valuable visiting hours for the sunrise and sunset view of the seven-towered fortress from Byzantine and Ottoman periods at Heptapyrgion are between 8:00-9:30am."},
9:  {'t': "Alcazar (Hamza Bey), eski şehrin içinde Osmanlı dönemine ait tarihi bir yapıdır; Bizans ve Osmanlı mimari katmanlarını bir arada görmek için çevre alanla birlikte tarihi merkez yürüyüşüne dahil edin.",
     'te': "Alcazar (Hamza Bey) is a historic structure from the Ottoman period inside the old city; include it in the historic center walk together with the surrounding area to see Byzantine and Ottoman architectural layers together."},
11: {'t': "Kapani Pazarı, Selanik'in en eski ve en özgün gıda çarşısıdır; taze baharatlar, peynirler ve zeytin çeşitleri için sabah 09:00-12:00 arası en verimli ziyaret saatidir.",
    'te': "Kapani Market is Thessaloniki's oldest and most authentic food bazaar; between 9am-noon is the most productive visiting hour for fresh spices, cheeses, and olive varieties."},
13: {'t': "Lazaristes Manastırı, Selanik'in kültür etkinlikleri için dönüştürülmüş tarihi bir komplekstir; konser ve sergi programı için önceden web sitesini kontrol edin.",
    'te': "Lazaristes Monastery is a historic complex converted for Thessaloniki's cultural events; check the website in advance for concert and exhibition programs."},
14: {'t': "Latomos Manastırı, Selanik'in en az ziyaret edilen ama en değerli Bizans mozaik hazinelerinden birini barındırır; kapı saatleri sınırlı olduğundan sabah 09:00-11:00 arası için plan yapın.",
    'te': "Latomos Monastery houses one of Thessaloniki's least visited but most valuable Byzantine mosaic treasures; plan for 9-11am as door hours are limited."},
17: {'t': "Aladja İmaret (İshak Paşa Camii), Selanik'in en iyi korunmuş Osmanlı camileri arasındadır; dış cephe mozaik karoları Osmanlı mimari süslemesinin bu şehirdeki en nadide örnekleri arasındadır.",
    'te': "Aladja Imaret (Ishak Pasha Mosque) is among Thessaloniki's best-preserved Ottoman mosques; the exterior mosaic tiles are among the most rare examples of Ottoman architectural decoration in this city."},
21: {'t': "Dragoumis Amfitiyatrosu, Selanik'in açık hava kültür etkinlikleri için kullanılan tarihi amfitiyatrosudur; yaz sezonu program takibi için şehir kültür etkinlikleri sitesini kontrol edin.",
    'te': "Dragoumis Amphitheater is a historic amphitheater used for Thessaloniki's open-air cultural events; check the city's cultural events website for summer season program tracking."},
25: {'t': "Galerius Kemeri, M.S. 303'te inşa edilmiş ve şehrin en iyi korunmuş Roma yapılarından biridir; kabartmalar üzerindeki savaş sahneleri için yanına kadar yaklaşmanız gerekir.",
    'te': "Arch of Galerius was built in 303 AD and is one of the city's best-preserved Roman structures; you need to get right up close for the battle scenes on the reliefs."},
59: {'t': "Clubάκι, Selanik'in alternatif gece sahnesinin küçük ama enerjik mekanlarından biridir; yerel canlı müzik geceleri için haftalık programı önceden kontrol edin.",
    'te': "Clubάκι is one of the small but energetic venues of Thessaloniki's alternative nightlife scene; check the weekly program in advance for local live music nights."},
60: {'t': "MABÉL Bar Club, Selanik'te kokteyller ve DJ müziğiyle iyi bir gece geçirmeyi sevenler için uygun bir mekandır; Cuma-Cumartesi geceleri en kalabalık saatler gece yarısından sonradır.",
    'te': "MABÉL Bar Club is a suitable venue in Thessaloniki for those who enjoy a good night out with cocktails and DJ music; the busiest hours on Friday-Saturday nights are after midnight."},
61: {'t': "Soulshakers, Selanik'te yaratıcı kokteyl kültürünü öne çıkaran bir bar hizmetidir; şehrin önde gelen mixologist deneyimi için bar menüsünden şef önerisi isteyin.",
    'te': "Soulshakers is a bar service in Thessaloniki that highlights creative cocktail culture; ask for the chef's recommendation from the bar menu for the city's leading mixologist experience."},
62: {'t': "aggeliki-workshop.gr, Selanik'te el sanatları ve yaratıcı atölyeler sunan bir adrestir; seramik veya takı yapımı workshopları için önceden kayıt yaptırmanız gerekmektedir.",
    'te': "aggeliki-workshop.gr is an address in Thessaloniki offering handicrafts and creative workshops; you need to register in advance for ceramic or jewelry-making workshops."},
63: {'t': "Mousses En Horo, Selanik'te dans ve müzik kültürünü yaşatan bir sanat topluluğu ya da mekandır; Yunan halk dansı ve rebetika müziği etkinlikleri için program takibi yapın.",
    'te': "Mousses En Horo is an arts community or venue in Thessaloniki that keeps dance and music culture alive; track the program for Greek folk dance and rebetika music events."},
65: {'t': "Paraskinio Live, Selanik'te canlı müzik performansları düzenlenen bir mekandır; Yunan rock ve pop akustik geceleri için haftalık program sosyal medyada duyurulur.",
    'te': "Paraskinio Live is a venue in Thessaloniki where live music performances are organized; the weekly program for Greek rock and pop acoustic evenings is announced on social media."},
66: {'t': "Kaimasidis Mobilya, Selanik'te köklü bir tasarım ve dekorasyon mağazasıdır; tarihi merkezde alışveriş turu sırasında Yunan ev tasarımı anlayışını kavramak için ziyaret edilebilir.",
    'te': "Kaimasidis Furniture is a deep-rooted design and decoration store in Thessaloniki; it can be visited to grasp the Greek home design approach during a shopping tour in the historic center."},
67: {'t': "Mousiko Sergiani, Selanik'te canlı Yunan müziği ve taverna atmosferini bir arada sunan bir mekandır; hafta içi akşamlarında canlı müzik daha sakin bir ortamda deneyimlenir.",
    'te': "Mousiko Sergiani is a venue in Thessaloniki that combines live Greek music and taverna atmosphere; live music is experienced in a calmer setting on weekday evenings."},
68: {'t': "VOG Club, Selanik'in en büyük kulüplerinden biri olarak elektronik müzik odaklı bir programla öne çıkar; büyük etkinlik geceleri için bilet online satın alın.",
    'te': "VOG Club stands out as one of Thessaloniki's largest clubs with an electronic music-focused program; buy tickets online for major event nights."},
69: {'t': "Proskinitopoulos Miltos, Selanik'te rehberlik ya da tur hizmetleri konusunda deneyimli bir yerel isimdir; tarihi merkez yürüyüş turları için önceden iletişime geçin.",
    'te': "Proskinitopoulos Miltos is an experienced local name in guiding or tour services in Thessaloniki; contact in advance for historic center walking tours."},
72: {'t': "Grand Chalet, Selanik'te özel etkinlikler ve özel toplantılar için tercih edilen bir mekandır; kapasitesi ve hizmetleri hakkında önceden bilgi alın.",
    'te': "Grand Chalet is a venue preferred in Thessaloniki for private events and special meetings; get information in advance about its capacity and services."},
74: {'t': "B Home Mobilya, Selanik'te ev dekorasyonu ve tasarım meraklılarının uğrayabileceği bir mağazadır; Yunan tasarım estetiğini yansıtan ürünleri görmek için kısa bir ziyaret yapılabilir.",
    'te': "B Home Furniture is a store in Thessaloniki where home decoration and design enthusiasts can stop by; a short visit can be made to see products reflecting Greek design aesthetics."},
75: {'t': "The Jews Rainbow Pub, Selanik'in tarihi Yahudi mahallesi Ladadika bölgesinde kültürel bir dokunuş sunan bir bardır; şehrin çok kültürlü tarihini yansıtan atmosferi için akşamüstü bir ziyaret değerlidir.",
    'te': "The Jews Rainbow Pub is a bar offering a cultural touch in Thessaloniki's historic Jewish neighborhood Ladadika area; an afternoon visit is worthwhile for an atmosphere reflecting the city's multicultural history."},
77: {'t': "Symposium HNL, Selanik'te özenli Yunan mutfağı ve şarap seçkisiyle tanınan bir restoran-lounge kombinasyonudur; akşam yemeği için rezervasyon önerilir.",
    'te': "Symposium HNL is a restaurant-lounge combination in Thessaloniki known for its meticulous Greek cuisine and wine selection; reservation is recommended for dinner."},
}
apply_batch('selanik.json', selanik)

# ── VALENCIA ──────────────────────────────────────────────────────────────────
valencia = {
1:  {'t': "Oceanogràfic, Avrupa'nın en büyük akvaryumudur; sabah açılışta gelin, balina köpekbalığı tünelinde öğleden önce çok daha az kalabalık olur. Online bilet kapı fiyatından ucuz.",
     'te': "Oceanogràfic is Europe's largest aquarium; come at morning opening, the whale shark tunnel is much less crowded before noon. Online tickets are cheaper than at the door."},
2:  {'t': "Merkez Pazar Çarşısı, gıda tutkununun Valensiya'daki cennetidir; Cuma sabahı 09:00-11:00 arası taze paella malzemeleri ve yerel renkleri en yoğun biçimde sunar.",
     'te': "Central Market is a food lover's paradise in Valencia; Friday morning between 9-11am presents fresh paella ingredients and local colors most intensely."},
3:  {'t': "Lonja de la Seda (İpek Borsası) UNESCO listesindedir; sabah erken gelin, Gotik salonun taş sütunları yoğun ışıkta en etkileyici görünümüne kavuşur.",
     'te': "Lonja de la Seda (Silk Exchange) is UNESCO-listed; come early in the morning, the Gothic hall's stone columns take on their most impressive appearance in intense light."},
7:  {'t': "Quart Kuleleri, Valensiya'nın en iyi korunmuş orta çağ kapılarından biridir; özellikle akşam ışıklandırmasında dramatik görünür. İçine girmek mümkün değil ama çevre fotoğrafı için değer.",
     'te': "Quart Towers is one of Valencia's best-preserved medieval gates; it looks dramatic especially in evening lighting. You can't enter but it's worth it for surrounding photography."},
10: {'t': "Sanat ve Bilim Şehri kompleksini gezmek için en az 4-5 saat ayırın; Oceanogràfic, IVAM ve Müzik Sarayı ayrı biletlidir. Online kombine bilet seçeneği mevcut ve daha ekonomik.",
    'te': "Set aside at least 4-5 hours to tour the City of Arts and Sciences complex; Oceanogràfic, IVAM, and the Music Palace have separate tickets. Online combined ticket option is available and more economical."},
13: {'t': "Palacio de Congresos, Valensiya'nın kongre ve fuar mekanıdır; büyük etkinlik dönemlerinde şehir konaklama ve trafik açısından yoğunlaşır, buna göre plan yapın.",
    'te': "Palacio de Congresos is Valencia's congress and fair venue; the city becomes congested in terms of accommodation and traffic during major events, plan accordingly."},
14: {'t': "Torres de Serranos, Valensiya'nın kuzey orta çağ kapısıdır; üstüne çıkmak ücretlidir ama Turia Bahçeleri ve eski şehir panoraması için kesinlikle değer.",
    'te': "Torres de Serranos is Valencia's northern medieval gate; climbing to the top is paid but absolutely worth it for the Turia Gardens and old city panorama."},
16: {'t': "Centro Cultural La Beneficència, ücretsiz girişiyle Valensiya'nın en erişilebilir müzelerinden biridir; İberya ve Müslüman Valencia koleksiyonu için öğleden önce gelin.",
    'te': "Centro Cultural La Beneficència is one of Valencia's most accessible museums with free entry; come before noon for the Iberian and Muslim Valencia collection."},
23: {'t': "Ana Serratosa Galeri, Valensiya'nın çağdaş sanat galerileri arasında öne çıkan özel bir adrestir; sergi değişim tarihleri için önceden web sitesini kontrol edin.",
    'te': "Ana Serratosa Gallery is a private address that stands out among Valencia's contemporary art galleries; check the website in advance for exhibition changeover dates."},
63: {'t': "Radio City, Valensiya'nın alternatif müzik ve canlı performans mekanları arasında köklü bir addır; Cuma-Cumartesi canlı müzik geceleri için bilet ve program önceden kontrol edin.",
    'te': "Radio City is a deep-rooted name among Valencia's alternative music and live performance venues; check ticket and program in advance for Friday-Saturday live music nights."},
64: {'t': "Akuarela Playa, Valensiya Playa del Carmen yakınında mevsimlik olarak açılan açık hava disko ve müzik etkinlik alanıdır; bilet önceden online alınmalıdır.",
    'te': "Akuarela Playa is an open-air disco and music event space that opens seasonally near Valencia's Playa del Carmen; tickets must be purchased online in advance."},
65: {'t': "Matisse Club, Valensiya'nın elektronik müzik sahnesi için bilinen bir kulüptür; Cuma geceleri haftalık programın en kalabalık saatlerini barındırır.",
    'te': "Matisse Club is a well-known club for Valencia's electronic music scene; Friday nights contain the busiest hours of the weekly program."},
66: {'t': "Rumbo 144, Valensiya'da küçük kapasiteli ve seçici kalabalığa hitap eden indie ve alternatif bir mekandır; konserleri için haftalık takvimi takip edin.",
    'te': "Rumbo 144 is an indie and alternative venue in Valencia catering to a small-capacity and selective crowd; follow the weekly calendar for their concerts."},
67: {'t': "Deseo 54, Valensiya'nın LGBTQ+ dostu gece mekanları arasında Barrio del Carmen'de merkezi konumuyla öne çıkmaktadır; hafta sonu geceleri en kalabalık dönemdir.",
    'te': "Deseo 54 stands out with its central location in Barrio del Carmen among Valencia's LGBTQ+-friendly nightlife venues; weekend nights are the busiest period."},
68: {'t': "Jimmy Glass Jazz Bar, Valensiya'nın en saygın canlı caz mekanlarından biridir; her gece canlı caz performansı yapılır, küçük ölçeği nedeniyle masa için önceden rezervasyon şarttır.",
    'te': "Jimmy Glass Jazz Bar is one of Valencia's most respected live jazz venues; live jazz performances are held every night, advance table reservation is essential due to its small scale."},
69: {'t': "Flamingos, Barrio del Carmen'de Valensiya'nın alternatif ve vintage sahnesini yansıtan bir bar ve kulüptür; gece programı için sosyal medya sayfasını takip edin.",
    'te': "Flamingos is a bar and club in Barrio del Carmen reflecting Valencia's alternative and vintage scene; follow the social media page for the nighttime program."},
70: {'t': "Los Amigos, Valensiya'da yerel halkın düzenli gittiği samimi bir tapas barıdır; sabah vermut ve tapas geleneği için Pazar günü öğle öncesi en doğru saat.",
    'te': "Los Amigos is a sincere tapas bar regularly frequented by locals in Valencia; Sunday before noon is the best time for the morning vermouth and tapas tradition."},
73: {'t': "Apoquetanit, Valensiya'da sahil yakınında açık hava etkinlikleri düzenleyen mevsimlik bir plaj kulübüdür; Haziran-Eylül arası aktif olup bilet önceden alınmalıdır.",
    'te': "Apoquetanit is a seasonal beach club near the beach in Valencia organizing open-air events; active between June-September and tickets must be purchased in advance."},
74: {'t': "Leganés, Valensiya'nın Ruzafa mahallesinde gündelik öğle yemeği ve kahve kültürünü yansıtan samimi bir mekandır; hafta içi öğle yemeği için kalabalık ama kısa beklemeye değer.",
    'te': "Leganés is a sincere venue in Valencia's Ruzafa neighborhood reflecting everyday lunch and coffee culture; busy on weekday lunches but worth a short wait."},
75: {'t': "El Kubata, Valensiya'nın Ruzafa semtinin vintage ve endüstriyel dekor anlayışını yansıtan yaratıcı bir bar-mekanıdır; akşam aperitif kültürü için 19:00-21:00 arası en uygun saatlerdir.",
    'te': "El Kubata is a creative bar-venue in Valencia's Ruzafa district reflecting the vintage and industrial decor approach; between 7-9pm are the most suitable hours for evening aperitif culture."},
76: {'t': "MClub, Valensiya'nın daha büyük kapasiteli elektronik müzik sahnelerinden biridir; hafta sonu DJ programı için online bilet önceden alınmalıdır.",
    'te': "MClub is one of Valencia's larger-capacity electronic music venues; online tickets must be purchased in advance for the weekend DJ program."},
77: {'t': "Indiana, Valensiya'da 80'ler-90'lar müzik temalı gece mekanlarından biri olarak nostaljik bir gece arayan ziyaretçilere hitap eder; tema geceleri için programı önceden kontrol edin.",
    'te': "Indiana appeals to visitors seeking a nostalgic evening as one of the 80s-90s music-themed nightlife venues in Valencia; check the program in advance for themed nights."},
78: {'t': "Jerusalem Pop&Rock, Valensiya'nın canlı rock ve pop müzik mekanları arasında yer alır; yerel ve bölgesel gruplar için haftalık konser takvimi mekanda ilan edilir.",
    'te': "Jerusalem Pop&Rock is among Valencia's live rock and pop music venues; the weekly concert calendar for local and regional bands is posted at the venue."},
79: {'t': "Bowie Show Disco, David Bowie'ye adanmış konsept dekorasyonuyla Valensiya'nın özgün gece mekanlarından biridir; retro kıyafet koduna uygun gelmek hem eğlenceli hem de uyum sağlayıcıdır.",
    'te': "Bowie Show Disco is one of Valencia's original nightlife venues with a concept decoration dedicated to David Bowie; coming in accordance with the retro dress code is both fun and fitting."},
}
apply_batch('valencia.json', valencia)

# ── KAŞ ───────────────────────────────────────────────────────────────────────
kas = {
2:  {'t': "Antiphellos Antik Kenti kalıntıları Kaş merkezi içindedir; Dor tipi kaya mezarları ve tiyatro için sabah 09:00-11:00 arası en serin ve en az kalabalık saatlerdir.",
     'te': "Antiphellos Ancient City ruins are within Kaş center; for the Doric rock tombs and theater, 9-11am are the coolest and least crowded hours."},
3:  {'t': "Kaş Çarşı'sı, el yapımı takı, liken boyalı kumaşlar ve Likya kopyası seramiklerle dolu butik dükkanlarıyla öğleden önce ve akşam saatlerinde en keyifli haline girer.",
     'te': "Kaş Bazaar takes on its most enjoyable form before noon and in the evening with boutique shops full of handmade jewelry, lichen-dyed fabrics, and Lycian replica ceramics."},
7:  {'t': "Küçük Çakıl Plajı, Kaş merkezinin hemen altında dar bir koy; sabah 08:00-10:00 arası kalabalık minimumdur. Öğleden sonra tekne trafiği yoğunlaşır ve su daha az sakin olur.",
     'te': "Küçük Çakıl Beach is a narrow cove directly below Kaş center; crowds are at a minimum between 8-10am. After noon boat traffic intensifies and the water becomes less calm."},
9:  {'t': "Manzara, Kaş tepesinde panoramik deniz ve ada manzarası sunan bir kafedir; gün batımı için en az 45 dakika öncesinden gelip en iyi köşe masayı alın.",
     'te': "Manzara is a café offering panoramic sea and island views on Kaş hilltop; arrive at least 45 minutes before sunset to claim the best corner table."},
10: {'t': "Tuğra Sanat Galerisi, Kaş'ın en özgün çağdaş sanat mekanlarından biridir; yerel ve bölgesel sanatçıların eserlerini burada keşfedebilirsiniz.",
    'te': "Tuğra Art Gallery is one of Kaş's most original contemporary art venues; you can discover the works of local and regional artists here."},
11: {'t': "Kaptan Ergun'un tekne turları, Kekova ve çevre koyları için günlük kalkışlar sunar; sabah kalkışı tekneleri öğlen varışına kadar en sakin denizi yakalar.",
    'te': "Captain Ergun's boat tours offer daily departures for Kekova and surrounding coves; morning departure boats catch the calmest sea until noon arrival."},
12: {'t': "Kaş Yelken ve Katamaran Turları için bilet ve güzergah seçeneklerini önceden araştırın; Haziran ve Eylül aylarında hem fiyat hem yer bulmak çok daha avantajlıdır.",
    'te': "Research ticket and route options in advance for Kaş Sailing and Catamaran Tours; both price and finding availability is much more advantageous in June and September."},
13: {'t': "Helenistik Tiyatro, Kaş merkezinin üzerindedir; 10 dakika yürüyüşle çıkılır. Sahne arkasından görünen Meis Adası manzarası her saatte farklı bir ışıkla değişir.",
    'te': "The Hellenistic Theatre is above Kaş center; reachable with a 10-minute walk. The view of Meis Island seen from behind the stage changes with different light at every hour."},
14: {'t': "Likya kaya mezarı, Kaş ana caddesinin hemen yanında durmaktadır; tarihin gündelik yaşamla bu denli iç içe geçtiğini başka az yerde görebilirsiniz.",
    'te': "The Lycian rock tomb stands right next to Kaş's main street; you can rarely see history so intertwined with daily life anywhere else."},
15: {'t': "Konaklama Sepeti, Kaş'ta uygun fiyatlı konaklama seçenekleri için pratik bir kaynaktır; özellikle sezon dışı için iyi fırsatlar sunabilir.",
    'te': "Konaklama Sepeti is a practical resource for affordable accommodation options in Kaş; it can offer good deals especially for the off-season."},
16: {'t': "Kaş'ın en popüler Instagram noktası, Helenistik tiyatro üzerinden Meis Adası'na bakan manzaradır; sabah erken ya da gün batımı için bu bakış açısını yakalayın.",
    'te': "Kaş's most popular Instagram spot is the view looking toward Meis Island from above the Hellenistic theater; capture this perspective for early morning or sunset."},
17: {'t': "Seatown Hotel, Kaş'ın denize yakın konumuyla tercih edilen butik otellerinden biridir; deniz manzaralı oda için en az 2-3 hafta öncesinden rezervasyon yapılması önerilir.",
    'te': "Seatown Hotel is one of Kaş's preferred boutique hotels for its proximity to the sea; reservation at least 2-3 weeks in advance is recommended for a sea-view room."},
18: {'t': "Kaş Merkez Camii, şehir meydanının hemen yanındadır; Osmanlı mirasının küçük ölçekli ama özgün bir temsilcisidir. Namaz vakitlerinde girişe saygı gösterin.",
    'te': "Kaş Central Mosque is right next to the city square; a small-scale but original representative of Ottoman heritage. Respect entry during prayer times."},
19: {'t': "Caretta Wall, Kaş yakınındaki deniz kaplumbağası yuvalama alanlarından birine yakındır; kaplumbağaları görmek için Haziran-Ağustos arası sabah çok erken saatleri gereklidir.",
    'te': "Caretta Wall is near one of the sea turtle nesting areas close to Kaş; very early morning hours between June-August are required to see the turtles."},
20: {'t': "Kaş Belediye Çarşısı, yerel halkın pazarladığı sebze ve meyve ile Kaş turizminin dışında kalan gündelik yaşamın gözlemlenebileceği özgün bir alandır.",
    'te': "Kaş Municipal Bazaar is an original area where local residents market vegetables and fruit, and everyday life outside Kaş tourism can be observed."},
21: {'t': "Antalya Kaş, Türk Rivierası üzerinde Kaş'ın bağlı olduğu il merkezini belirtir; Antalya'dan Kaş'a araçla 3 saat, otobüsle 4 saat sürmektedir.",
    'te': "Antalya Kaş refers to the provincial center that Kaş is connected to on the Turkish Riviera; it takes 3 hours by car and 4 hours by bus from Antalya to Kaş."},
22: {'t': "Larsoy Travel, Kaş'ta tüm tekne, dalış ve kültür turları için rezervasyon yapılabilecek köklü bir yerel acentedir; fiyat ve güzergah karşılaştırması için iletişime geçin.",
    'te': "Larsoy Travel is a deep-rooted local agency in Kaş where you can make reservations for all boat, diving and cultural tours; contact for price and route comparison."},
23: {'t': "Kaş çarşısındaki el yapımı bilezik dükkanları, Likya motifli takıları ve boncuk işlemeli tasarımlarıyla özgün hatıralar için biçilmiş kaftan; pazarlık yapmak mümkündür.",
    'te': "Handmade bracelet shops in Kaş bazaar are tailor-made for original souvenirs with Lycian-motif jewelry and bead-embroidered designs; bargaining is possible."},
24: {'t': "Kekova tekne turu için sabah 09:00 kalkışlı tekneleri tercih edin; öğleden sonra rüzgar artabilir. Kekova'nın batık şehri (Simena) yüzme maskesi ve şnorkelle en iyi görülür.",
    'te': "For Kekova boat tours, prefer boats with 9am morning departure; winds may increase in the afternoon. Kekova's sunken city (Simena) is best seen with a swimming mask and snorkel."},
25: {'t': "Kaş Merkez, küçük ve yürüyerek keşfedilebilir bir kasabadır; otelden çarşıya, plaja ve tiyatroya yürümek her yön için 10-20 dakikayı geçmez.",
    'te': "Kaş Center is a small and walkable town; walking from the hotel to the bazaar, beach, and theater does not exceed 10-20 minutes in any direction."},
26: {'t': "Uzun Çarşı (Öğütçü Sokak), Kaş'ın en uzun alışveriş caddesinin başlangıç noktasıdır; kahvaltıdan sonra sabah 10:00-12:00 arası tüm dükkanlar açık ve kalabalık azdır.",
    'te': "Uzun Çarşı (Öğütçü Sokak) is the starting point of Kaş's longest shopping street; between 10am-noon after breakfast all shops are open and crowds are few."},
27: {'t': "Kaş Atatürk Heykeli, şehir meydanında merkezi bir konumdadır; çevre kafeler sabah kahvaltısı ve akşam çayı için tüm gün açıktır.",
    'te': "Kaş Atatürk Statue is in a central position in the town square; surrounding cafés are open all day for morning breakfast and evening tea."},
66: {'t': "Shot Bar, Kaş'ın gece hayatında hafif bir başlangıç için uygun küçük bir bardır; yerel ve yabancı ziyaretçiler karışık bir atmosferde buluşur.",
    'te': "Shot Bar is a small and suitable bar for a light start to Kaş's nightlife; local and foreign visitors meet in a mixed atmosphere."},
67: {'t': "Dott's, Kaş'ta kokteyller ve canlı müzikle samimi bir gece deneyimi sunan bir mekandır; yaz sezonunda hareketli olan bar, sakin dönemlerde daha kişisel bir atmosfer sunar.",
    'te': "Dott's is a venue in Kaş offering a sincere night experience with cocktails and live music; the bar, which is lively in summer season, offers a more personal atmosphere in quieter periods."},
}
apply_batch('kas.json', kas)

print("Ksamil, Selanik, Valencia, Kas done.")
