import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
79: {'d': "Mykonos'un küçük meydanlarından birindeki bu souvlaki dükkanı, adanın lüks gastronomi imajının aksine gerçek bir yerel fast food deneyimi yaşatır. Taze pita ekmeğine sarılan tavuk ya da domuz souvlaki ve yanında taze domates soslu tzatziki ile doyurucu ve uygun fiyatlı bir Yunanistan sokak yemeği tadılır.",
    'de': "This souvlaki shop in one of Mykonos's small squares delivers a genuinely local fast food experience contrary to the island's luxury gastronomy image. Chicken or pork souvlaki wrapped in fresh pita bread with fresh tomato tzatziki on the side offers a filling and affordable Greek street food taste."},

84: {'d': "Kasabanın üzerinde, rüzgara açık bir konumda yer alan Veranda Mykonos, özellikle yel değirmenlerinin görüldüğü taraftaki masalarından adanın klasik panoramasını çizer. Sabah kahvaltısından akşam kokteyllerine uzanan menüsüyle gün boyu sürekli açık kalması, kasabada esnek bir durak oluşturur.",
    'de': "Located above the town in a wind-facing position, Veranda Mykonos sketches the island's classic panorama particularly from the tables on the side where the windmills are visible. Its menu stretching from morning breakfast to evening cocktails and all-day opening hours form a flexible stop within the town."},

86: {'d': "Mykonos'ta Meksika mutfağına özgün bir yorum getiren El Burro, rengarenk dekoru ve taze domates-kişniş soslu burritolarıyla kasabanın en eğlenceli alternatif mutfak mekanlarından biridir. Yunan adası ortamında Orta Amerika lezzetleri arayanlar için beklenmedik ama tatmin edici bir keşiftir.",
    'de': "El Burro, bringing an original interpretation of Mexican cuisine to Mykonos, is one of the town's most fun alternative culinary venues with its colorful décor and burritos with fresh tomato-coriander sauce. An unexpected yet satisfying discovery for those seeking Central American flavors in a Greek island setting."},

88: {'d': "Ano Mera köyünün yakınlarında, Mykonos'un iç kesimlerinde saklanan Baba Houlakia, adanın ticari kasabasından tamamen farklı bir ruhla çalışıyor. Bahçe masaları, taze yeşilliklerle hazırlanan köy salatası ve gün boyu aktif olan kafe menüsüyle burada saatler geçmekte hiç fark edilmiyor.",
    'de': "Hidden near Ano Mera village in Mykonos's interior, Baba Houlakia operates with a spirit completely different from the island's commercial town. Garden tables, a village salad prepared with fresh greens, and an all-day active café menu make hours pass here without noticing."},

89: {'d': "Kasabanın arka sokaklarına sıkışmış Red Parrot 2, standart turist restoranlarının sıkıcı menülerinden kaçmak isteyenler için yerel aileler tarafından işletilen, ev yapımı sausage, balık çorbası ve ünlü günlük tavuk güveciyle kendine özgü bir şöhret inşa etmiştir.",
    'de': "Squeezed into the town's back streets, Red Parrot 2 has built its own distinct reputation for those wanting to escape the boring menus of standard tourist restaurants with its family-operated homemade sausage, fish soup, and famous daily chicken stew."},

90: {'d': "İsmine uygun şekilde çiftler ve romantik ziyaretçilerin gözdesi olan Soulmates Mykonos, mum ışığında servis yapılan Yunan-Akdeniz menüsü ve kasabanın sakin bir köşesindeki masalarıyla özel bir akşam yemeği için biçilmiş kaftandır. Gece programının başlangıcı olarak da tercih edilen bir aşk atmosferi sunar.",
    'de': "True to its name, Soulmates Mykonos is the favorite of couples and romantic visitors, tailor-made for a special evening dinner with its candlelit Greek-Mediterranean menu and tables in a quiet corner of town. It also offers a love atmosphere preferred as the start of an evening program."},

91: {'d': "Mykonos kasabasının dar sokaklarında huzurlu bir kahve molası arayan için Zymoto Cafe, el yapımı Yunan kahvesi çeşitleri, soğuk freddo espresso ve günlük hazırlanan tatlılarıyla adanın en samimi lokal kahve mekanlarından biri olarak öne çıkıyor. Küçük iç mekanı ve bahçeye açılan taş kapısıyla köy kahvesi havasını taşır.",
    'de': "For those seeking a peaceful coffee break in Mykonos town's narrow streets, Zymoto Cafe stands out as one of the island's most sincere local coffee venues with its handmade Greek coffee varieties, cold freddo espresso, and daily prepared sweets. Its small interior and stone door opening to a garden carry a village café atmosphere."},

93: {'d': "Yunanistan'ın tanınan Veneti pastane zincirinin Mykonos şubesi, kuru üzümlü loukoumades (bal yağlı hamur topları), limonlu pasta ve tahini helvası gibi geleneksel Yunan tatlılarını adaya taşıyor. Sezon boyunca uzayan kuyrukları ve güvenilir kalitesiyle, kahvaltı ya da öğleden sonra molası için sürekli tercih edilen bir adrestir.",
    'de': "The Mykonos branch of Greece's renowned Veneti pastry chain brings traditional Greek sweets like loukoumades with honey, lemon cake, and tahini halva to the island. With its season-long queues and reliable quality, it is a continuously preferred address for breakfast or an afternoon break."},

95: {'d': "Mykonos kasabasının ticari merkezindeki Stairz, kasabada içki, müzik ve dans için erken saatte başlamanıza imkân tanıyan bir bar-mekandır. Gece kulübü atmosferine geçmeden önce, yakın civardaki büyük kulüplerin açılmasını beklerken sıcak bir ortamda kokteyl içmek isteyenler için pratik bir durak.",
    'de': "Stairz in the commercial center of Mykonos town is a bar venue that allows you to start early for drinks, music, and dancing in the town. A practical stop for those wanting to drink cocktails in a warm atmosphere while waiting for the large nearby clubs to open before transitioning to a nightclub atmosphere."},

96: {'d': "Hora'nın araçsız sokaklarında adım geçirdiğinizde kokusu sizi içeri çeken Papu Cafe, ev yapımı galeta unlu cheesecake ve taze çikolatalı krep çeşitleriyle kasabanın en tatlı duraklarından biridir. Küçük ama titizlikle seçilmiş menüsü, en iddialı pastane-kafelere açıktan meydan okur.",
    'de': "Papu Cafe, whose scent draws you in as you pass through Hora's car-free streets, is one of the town's sweetest stops with its homemade breadcrumb cheesecake and fresh chocolate crêpe varieties. Its small but meticulously selected menu openly challenges the most ambitious pastry cafés."},

98: {'d': "Mykonos'ta vegan seçeneklerin en geniş yelpazesini sunan Rhino Vegan Beat, beyaz ve mavi renkli dış cephesi ve Kiklad mimarisine uygun minimalist iç mekanıyla adanın bilinçli beslenme arayanlarına özgün bir adres sunar. Spirulina smoothie bowl'larından soya proteini yüklü öğün salatalarına kadar kapsamlı bir bitki bazlı menü.",
    'de': "Offering Mykonos's widest range of vegan options, Rhino Vegan Beat provides a unique address for the island's health-conscious seekers with its white and blue exterior and minimalist interior in keeping with Cycladic architecture. A comprehensive plant-based menu stretching from spirulina smoothie bowls to soy protein-loaded meal salads."},

99: {'d': "Kasabanın merkezindeki 23 Hotel Mykonos'un kamuya açık kahvaltı ve brunch menüsü, butik otel kalitesindeki sunumunu herkese açık tutuyor. Taze portakal suyu, Yunan yoğurtlu meyve kasesi ve çeşitli egg benedict seçenekleriyle kasabanın en değerli sabah deneyimlerinden birini sunar.",
    'de': "The publicly accessible breakfast and brunch menu of 23 Hotel Mykonos in the town center keeps its boutique hotel quality presentation open to everyone. It offers one of the town's most valuable morning experiences with fresh orange juice, a Greek yogurt fruit bowl, and various eggs benedict options."},

100: {'d': "Mykonos'un en ikonik gece kulüplerinden biri olan VOID, yıllardır ada gece hayatının bitmez tükenmez enerjisini temsil eder. Dünyanın en tanınmış DJ'lerini ağırlayan sahnesi ve yüzlerce kişilik kapasitesiyle kasabanın sabaha kadar dans edilen kulüpleri arasında en köklü isim olmayı sürdürüyor.",
    'de': "One of Mykonos's most iconic nightclubs, VOID has represented the endless energy of island nightlife for years. With its stage hosting the world's most recognized DJs and capacity for hundreds, it continues to be the most established name among the town's clubs that dance until dawn.",
    't': "Kapıda kuyruk beklemek yerine online bilet ve guestlist kaydı yaptırın; özellikle uluslararası DJ geceleri çok erken doluyor.",
    'te': "Register for an online ticket or guestlist rather than queuing at the door; especially international DJ nights fill up very early."},

102: {'d': "Hora'nın hareketle dolu ana yollarından biraz çekilmiş Skagia-Galouni Petroulia, denizden gelen balıkçıların tercihi olan taze palamut, karagöz ve çiroz gibi mevsim balıklarını kızartıp tüten büyük bir tava üzerinde sunar. Gürültüsüz ve sade bu mekan, Mykonos'un lüks restoran tekdüzeliğinden en keskin kopuşlarından birini temsil eder.",
    'de': "Slightly withdrawn from one of Hora's busy main roads, Skagia-Galouni Petroulia serves seasonal fish like fresh bonito, pandora, and dried mackerel preferred by fishermen arriving from the sea, fried and served on a large smoking pan. This quiet and simple venue represents one of the sharpest breaks from Mykonos's luxury restaurant uniformity."},

103: {'d': "Mykonos kasabasında müzik ve dans konusunda köklü bir üne sahip olan Kymbo, hem canlı Yunan müziği hem de modern DJ setleriyle farklı beklentilere aynı anda hitap eden eklektik bir gece mekanıdır. Otantik Mykonos atmosferini modern eğlenceyle sentezleme becerisiyle adada kendi kategorisinde tek kalmayı başarıyor.",
    'de': "Having an established reputation in Mykonos town for music and dancing, Kymbo is an eclectic nightlife venue that simultaneously appeals to different expectations with both live Greek music and modern DJ sets. It succeeds in remaining unique in its category on the island with its ability to synthesize authentic Mykonos atmosphere with modern entertainment.",
    't': "Canlı Yunan müziği geceleri için haftalık programı kontrol edin; bu geceler adanın en hareketli ve en özgün eğlence anlarından birini sunar.",
    'te': "Check the weekly program for live Greek music nights; these evenings offer one of the island's liveliest and most authentic entertainment moments."},

104: {'d': "Mykonos'un üst segment VIP deneyimlerine aracılık eden bu konsiyerj ve rezervasyon servisi, özel yat kiralama, gece kulübü VIP masaları ve lüks villa erişimi konularında kişiselleştirilmiş planlama sunar. Adanın en kalabalık dönemlerinde kapasitenin çok ötesinde talep gören mekanlar için bu servise başvurmak ciddi bir avantaj sağlar.",
    'de': "This concierge and reservation service facilitating Mykonos's high-end VIP experiences offers personalized planning for private yacht rentals, nightclub VIP tables, and luxury villa access. Consulting this service for venues with demand far exceeding capacity during the island's busiest periods provides a significant advantage.",
    't': "Özellikle Temmuz-Ağustos dönemi için en az 2-3 hafta önceden bu servisle iletişime geçmenizi öneririz.",
    'te': "We recommend contacting this service at least 2-3 weeks in advance, especially for the July-August period."},

105: {'d': "Mykonos kasabasının gece hayatında yıllardır varlık gösteren Tabu, Hora'nın en erişilebilir gece kulüplerinden biri olarak hem yabancı turistlerin hem de Yunan ziyaretçilerin tercih ettiği ortam ve fiyat dengesiyle öne çıkıyor. Eklektik müzik listesi ve gece boyunca değişen atmosferiyle ada ziyaretçilerine çeşitli bir gece deneyimi sunar.",
    'de': "Having been a presence in Mykonos town's nightlife for years, Tabu stands out as one of Hora's most accessible nightclubs with a balance of atmosphere and price preferred by both foreign tourists and Greek visitors. It offers island visitors a varied night experience with an eclectic music list and an atmosphere that changes throughout the night.",
    't': "Gece 01:00 civarı en kalabalık saatlerdir; erken gelinirse kapı girişi ve masaya ulaşmak çok daha kolaydır.",
    'te': "Around 1am is the busiest time; arriving early makes door entry and reaching a table much easier."},

120: {'d': "Mykonos kasabasının en özgün Yunan tavernaları arasında sayılan Avli Tou Thodori, şarap fıçılarıyla çevrili açık avlusunda taze deniz ürünleri ve Yunan peynirleriyle kurulmuş meze masalarını uzun akşam yemeklerine dönüştürür. Adada gerçek meyhane deneyimi arayanlar için bölgenin en otantik adresidir.",
    'de': "Among Mykonos town's most original Greek tavernas, Avli Tou Thodori transforms fresh seafood and Greek cheese meze tables in its open courtyard surrounded by wine barrels into long leisurely dinners. It is the area's most authentic address for those seeking a genuine tavern experience on the island."},

121: {'d': "Ano Mera köyünde, kasabanın kalabalığından uzakta faaliyet gösteren Bonatsa, yöre halkının düzenli gittiği geleneksel bir köy lokantasıdır. Fırında kuzu, kabaklı yumurta ve pastitsio gibi Yunan ev yemeklerini öğle saatlerinde taze ve uygun fiyatlı olarak sunan bu mekan, adanın gerçek yüzünü görmenin en kolay yollarından birini temsil eder.",
    'de': "Operating in Ano Mera village far from the town's crowds, Bonatsa is a traditional village restaurant regularly frequented by local residents. Serving Greek home cooking like oven-roasted lamb, zucchini eggs, and pastitsio freshly and affordably at lunchtime, this venue represents one of the easiest ways to see the island's real face."},

127: {'d': "Mykonos'ta 'Delicious' adını taşıyan bu küçük aile mezehanesi, adanın en basit ama en tatmin edici öğünlerini taşıyan bir yerdedir. Sabah taze gelen balıktan hazırlanan günlük spesyal, fırın ekmeği ve yöresel zeytin yağıyla servis edilir; yüksek fiyatlı restoranların yorgunluğunu atmak isteyenler için biçilmiş kaftandır.",
    'de': "This small family mezze spot carrying the name 'Delicious' in Mykonos is a place bearing some of the island's simplest yet most satisfying meals. The daily special prepared from morning-fresh fish is served with baked bread and local olive oil; tailor-made for those wanting to recover from the fatigue of high-priced restaurants."},

128: {'d': "Psarou'nun prestijli koyuna bakan Be CooL, şezlongları ve özel alanlarıyla üst segment plaj kulübü deneyimini kendi tarzında sunar. Gün boyunca hem plaj hem restoran olarak çalışan mekan, yüksek profilli ziyaretçilerin hem denize girip hem yemek yiyip hem de müzik dinleyebildiği entegre bir deneyim ortamı oluşturur.",
    'de': "Overlooking Psarou's prestigious cove, Be CooL presents the high-end beach club experience in its own style with sun loungers and private areas. Operating as both a beach and restaurant throughout the day, the venue creates an integrated experience environment where high-profile visitors can swim, dine, and listen to music all together."},

129: {'d': "Mykonos kasabasının arka sokaklarına sığınan N Caffe, turizmin getirdiği yoğunluğa rağmen adada olduğunu fark ettiren sessiz bir kahve ritüeli sunar. İtalyan freddo kapuçino ve elde yapılan simit benzeri Yunan çöreğiyle sabah molasını kasabanın en sakin biçimde geçirme şansını verir.",
    'de': "Nestled in the back streets of Mykonos town, N Caffe offers a quiet coffee ritual that makes you realize you are on an island despite the tourist intensity. With Italian freddo cappuccino and handmade Greek simit-like ring bread, it gives you the chance to spend your morning break in the town's most tranquil form."},

130: {'d': "Paraga Plajı yakınındaki Castello, birbiriyle bağlantılı güverte ve terasyıyla hem plaj hem de restaurant ortamını birleştiriyor. Taze domates soslu midye, zeytinyağlı ızgara kalamari ve mezeler eşliğinde, Mykonos'un ticari kasabasına kıyasla çok daha sakin bir koyda yemek yemek mümkün.",
    'de': "Near Paraga Beach, Castello combines beach and restaurant environments with its interconnected decks and terraces. With fresh tomato-sauced mussels, olive oil grilled calamari, and mezze, it is possible to dine in a much quieter cove compared to Mykonos's commercial town."},

132: {'d': "Mykonos kasabasındaki TAYO, Asya sokak mutfağı ilhâmlı ama Akdeniz malzemeleriyle hazırlanan fusion menüsüyle adanın en yaratıcı mutfak adreslerinden biridir. Miso soslu Yunan balığı ve limonlu tahini salatasıyla oluşturulan yenilikçi kombinasyonlar, kasabanın monoton menüleri arasında gerçek anlamda fark yaratan bir teklif sunuyor.",
    'de': "TAYO in Mykonos town is one of the island's most creative culinary addresses with its fusion menu inspired by Asian street food but prepared with Mediterranean ingredients. Innovative combinations formed with miso-sauced Greek fish and lemon tahini salad offer a genuinely differentiating proposal among the town's monotonous menus."},

133: {'d': "Mykonos kasabasının belki de en küçük kahve dükkanı olan HUG Espresso Bar, porselen fincanlarıyla sunulan özenli single origin kahve ve el yapımı güneş kurusu domatesi serpiştirilmiş focaccia dilimleriyle adanın kalabalık café kültürüne karşı samimi bir alternatif oluşturuyor.",
    'de': "Perhaps Mykonos town's smallest coffee shop, HUG Espresso Bar forms a sincere alternative to the island's crowded café culture with carefully prepared single-origin coffee served in porcelain cups and handmade focaccia slices sprinkled with sun-dried tomatoes."},

134: {'d': "Adanın yenilikçi gastronomi sahnesine damgasını vuran Degu, tat alma deneyimini ön plana alan küçük porsiyon degustation menüsüyle her tabağı farklı bir malzeme ve tekniğin keşfine dönüştürüyor. Sakin dekorasyonu ve kişisel servisiyle kasabanın gösterişli restoranlarına göre çok daha içten ve odaklı bir yemek deneyimi sunar.",
    'de': "Having left its mark on the island's innovative gastronomy scene, Degu transforms each plate into a discovery of a different ingredient and technique with its small-portion degustation menu that foregrounds the taste experience. With its calm décor and personal service, it offers a much more heartfelt and focused dining experience than the town's showy restaurants."},

135: {'d': "Mykonos havalimanı çıkışında konumlanan Waca, uçuş beklerken ya da adaya yeni inmiş yorgun yolculara taze kahve, sandviç ve hafif öğün seçenekleri sunuyor. Küçük ama düzenli menüsü ve rahat oturma alanlarıyla havalimanının standart kafeteryalarına gerçek anlamda iyi bir alternatifdir.",
    'de': "Located at Mykonos airport exit, Waca offers fresh coffee, sandwiches, and light meal options to tired travelers waiting for a flight or having just landed on the island. With its small but organized menu and comfortable seating areas, it is a genuinely good alternative to the airport's standard cafeterias."},

138: {'d': "Kasabanın arka taraflarında güneş açık bir terasta kahvaltı ve brunch sunmaya odaklanan Velanos, Mykonos'un en düşünceli sabah menülerinden birine sahiptir. Yunan yoğurtlu granola kasesi, taze avokado toast ve geniş krep seçenekleriyle adanın meydan okuma niteliğinde brunch adreslerinden biri olarak öne çıkıyor.",
    'de': "Focused on offering breakfast and brunch on a sunny terrace in the town's back areas, Velanos has one of Mykonos's most thoughtful morning menus. It stands out as one of the island's challenging brunch addresses with Greek yogurt granola bowl, fresh avocado toast, and wide crêpe selections."},

139: {'d': "Mykonos açıklarındaki bu eşsiz lüks yat deneyimi, adanın limanından ayrılıp açık denizde saatlerce sürüklenerek Delos ve Rhenia adalarına yanaşmayı içeriyor. Güvertede özel mutfak servisi, şnorkel ekipmanı ve güneş banyosu platformlarıyla tekne, kasabanın kalabalığından tam anlamıyla kopuşun adresidir.",
    'de': "This unique luxury yacht experience off Mykonos involves departing from the island's harbor and drifting for hours to approach the islands of Delos and Rhenia. With private galley service on deck, snorkel equipment, and sunbathing platforms, the boat is the address for a complete break from the town's crowds.",
    't': "Özel tekne rezervasyonu için en az 3-5 gün önceden irtibata geçin; yüksek sezon günlerinde tekneler haftalarca öncesinden doludur.",
    'te': "Contact at least 3-5 days in advance for a private boat reservation; on high-season days boats are fully booked weeks ahead."},

140: {'d': "Mykonos'un yüksek sezon döneminde mekan rezervasyonu, özel transferler ve VIP hizmetleri için uzmanlaşmış bu konsiyerj servisi, adanın en talep gören restoranlarında, gece kulüplerinde ve özel teknelerde yer bulmayı mümkün kılar. Bireysel tatil planlaması yerine profesyonel organizasyon tercih edenler için değerli bir kaynak.",
    'de': "Specializing in venue reservations, private transfers, and VIP services during Mykonos's high season, this concierge service makes it possible to find places in the island's most sought-after restaurants, nightclubs, and private boats. A valuable resource for those preferring professional organization over individual holiday planning.",
    't': "Hizmet programını tatil başlamadan 2-4 hafta önce başlatın; son dakika talepleri en iyi seçenekleri kaçırmanıza yol açabilir.",
    'te': "Start the service program 2-4 weeks before your holiday begins; last-minute requests may cause you to miss the best options."},

141: {'d': "Kasabanın yüksek noktalarından birinde yer alan Sunset Lounge, Mykonos'un en uzun ve en kapsamlı günbatımı seanslarından birini sunar. Kokteyller ve küçük aperitif tabaklar eşliğinde, güneşin Ege'ye daldığı o birkaç dakikalık anı mümkün olan en büyük konforla yaşamak isteyenler için doğru yerdir.",
    'de': "Located at one of the town's high points, Sunset Lounge offers one of Mykonos's longest and most comprehensive sunset sessions. It is the right place for those wanting to experience those few minutes when the sun plunges into the Aegean with maximum comfort, accompanied by cocktails and small aperitif plates.",
    't': "Gün batımından bir saat önce gelin ve günbatımına özel kokteyller için menünün sezonluk kısmına bakın.",
    'te': "Come one hour before sunset and check the seasonal section of the menu for sunset cocktails."},

143: {'d': "Mykonos kasabasının sakin mahallelerinden birinde, turistik yoğunluktan biraz çekilmiş bu butik konak, minimal Kiklad dekorasyonu ve kendi bahçesiyle adada huzurlu ve özel bir konaklama deneyimi sunar. Adanın görsel gürültüsünden uzak, sessiz bir gece geçirmek isteyenler için değerli bir seçimdir.",
    'de': "Slightly withdrawn from tourist intensity in one of Mykonos town's quieter neighborhoods, this boutique guesthouse offers a peaceful and private stay on the island with minimal Cycladic décor and its own garden. A valuable choice for those wanting to spend a quiet night away from the island's visual noise.",
    't': "Konak bahçesi akşamları halka açık olmayabilir; rezervasyon sırasında bahçe saatlerini öğrenin.",
    'te': "The guesthouse garden may not be publicly accessible in the evenings; ask about garden hours when booking."},

145: {'d': "Mykonos kasabasında uzun yıllardır varlığını sürdüren Rhapsody Bar, canlı Yunan müziği geceleri ve kokteylleriyle kasabanın gece eğlencesine katılmanın en sıcak yollarından birini sunuyor. Kalabalık kulüplerden önce ya da sonra uğramak için idéal olan bu mekan, hem yerel hem de yabancı ziyaretçilerin bir arada bulunduğu hoş bir ortamdır.",
    'de': "Rhapsody Bar, which has maintained its presence in Mykonos town for many years, offers one of the warmest ways to participate in the town's evening entertainment with live Greek music nights and cocktails. Ideal for stopping before or after the crowded clubs, this venue has a pleasant atmosphere where both locals and foreign visitors co-exist."},

148: {'d': "Yunanistan genelinde yaygın olan Flocafe zincirinin Mykonos şubesi, frappe ve freddo espresso tarzında soğuk Yunan kahvesini en klasik biçimde sunan adanın güvenilir kahve duraklarından biridir. Oturma alanları ve hızlı servis anlayışıyla özellikle sabah başlangıcı ya da gün ortası molası için tercih edilen bir adrestir.",
    'de': "The Mykonos branch of the nationwide Flocafe chain is one of the island's reliable coffee stops serving cold Greek coffee in frappe and freddo espresso style in the most classic form. With seating areas and a quick service approach, it is a preferred address particularly for the start of the morning or a midday break."},

149: {'t': "PADI sertifikalı kurs için önceden kayıt yaptırın; ilk dalış deneyimi için ise aynı gün rezervasyonu yeterlidir. Lia plajı dalış için Mykonos'un en berrak suları arasında yer alır.",
     'te': "Register in advance for a PADI certified course; for a first dive experience, same-day reservation is sufficient. Lia beach is among Mykonos's clearest waters for diving."},

150: {'d': "Ano Mera köyünde 1542'de inşa edilen Tourliani Manastırı, Mykonos kasabasının kalabalığından uzakta, Kikladlar'ın en iyi korunmuş Venedik dönemi dini yapılarından birini temsil ediyor. Mermer işlemeli avlu çeşmesi, 16. yüzyıl ikonostatisi ve köy sakinlerinin hâlâ dua için geldiği bu manastır, adanın ruhani yüzünü keşfetmek için vazgeçilmez bir duraktır.",
    'de': "The Tourliani Monastery built in Ano Mera village in 1542, away from Mykonos town's crowds, represents one of the Cyclades' best-preserved Venetian-era religious structures. With its marble-worked courtyard fountain, 16th-century iconostasis, and village residents still coming to pray, this monastery is an indispensable stop for discovering the island's spiritual face.",
    't': "Manastır, köy meydanının hemen yanındadır; sabah ziyareti için köyde kahvaltı etmek ve ardından manastırı gezmek ideal bir program oluşturur.",
    'te': "The monastery is right next to the village square; having breakfast in the village and then visiting the monastery makes for an ideal morning program."},

153: {'d': "Ornos Plajı yakınındaki Solymar, aile dostu ortamı ve Akdeniz menüsüyle hem plaj saatlerinin öğle molasında hem de akşam yemeğinde tercih edilen sakin bir restoran-kafe olarak Ornos'un en sevilen duraklarından biridir. Taze domates çorbası ve ızgara kalamarın yanında dondurma çeşitleri ile kapanan bir yemek burada tatil havasını tazeleriyor.",
    'de': "Near Ornos Beach, Solymar is one of Ornos's most loved stops as a family-friendly and calm restaurant-café preferred both for a lunch break during beach hours and for dinner with a Mediterranean menu. A meal ending with fresh tomato soup, grilled calamari, and ice cream varieties refreshes the holiday atmosphere here."},

154: {'d': "Kasabanın arka sokaklarındaki bu sade meyhane, çıraların arkasında asmaya sarılı duvarlar ve üstü örtülü avlusunda günlük tavuk güveci ve fırın patlıcanla yerel halkı ağırlıyor. Adanın gösterişli cephesinden uzak, dürüst Yunan ev yemeğinin bulunduğu nadir köşelerden birini temsil ediyor.",
    'de': "This plain tavern in the town's back streets welcomes locals with daily chicken stew and oven eggplant among vine-wrapped walls behind its canopy and in its covered courtyard. It represents one of the rare corners away from the island's showy façade where honest Greek home cooking is found."},

155: {'d': "Ano Mera köyündeki bu kalamari ve ızgara kebap mekânı, bölgede yaşayan ailelerin ve çobanların düzenli gittiği gerçek bir köy lokantasıdır. Özellikle öğle saatlerinde taze hazırlanan kalamaria tığanita ve souvlaki, kasabanın pahalı restoranlarına kıyasla yarı fiyatına gerçek Yunan lezzetini tatma fırsatı sunar.",
    'de': "This calamari and grilled kebab spot in Ano Mera village is a genuine village restaurant regularly frequented by families and shepherds living in the area. Freshly prepared kalamaria tiganita and souvlaki especially at lunchtime offer a chance to taste genuine Greek flavors at half the price compared to the town's expensive restaurants."},

158: {'d': "Mykonos kasabasında uzun yıllardır faaliyet gösteren Aphrodite, Yunan ev yemeği geleneğini şehrin ticari gastronomi baskısına rağmen canlı tutmaya devam ediyor. Günlük değişen spesyaller, fırın makarnası ve zeytinyağlı yeşil fasulye, şehrin klasik menü tekdüzeliğinden kaçmak isteyenler için doğal bir liman oluşturuyor.",
    'de': "Having operated in Mykonos town for many years, Aphrodite continues to keep Greek home cooking tradition alive despite the town's commercial gastronomy pressure. Daily changing specials, oven pasta, and olive oil green beans form a natural harbor for those wanting to escape the town's classic menu monotony."},

159: {'d': "Mykonos kasabasının üst mahallelerinde yer alan Liastì, güneye açılan terası, mevsim balıklarından oluşan kısa menüsü ve başarılı yerel şarap listesiyle kasabada kalıcı bir şöhret inşa etmiş aile restoranlarındandır. Gün boyu güneş alan terası sayesinde özellikle öğlen saatlerinde tercih edilen bir adres.",
    'de': "Located in the upper quarters of Mykonos town, Liastì is one of the family restaurants that has built a lasting reputation in the town with its south-facing terrace, short menu composed of seasonal fish, and a successful local wine list. A preferred address especially at lunchtime thanks to its all-day sun-receiving terrace."},

163: {'d': "Ano Mera köyünde köklü bir geçmişe sahip Vergos Taverna, kilise meydanına bakan masaları, mangal üzerinde dönen kuzu çevirme (souvla) ve ev yapımı tiropita gibi Yunan kırsalının en köklü lezzetleriyle adanın en özgün yemek deneyimlerinden birini sunuyor.",
    'de': "With a deep-rooted past in Ano Mera village, Vergos Taverna offers one of the island's most original dining experiences with its tables facing the church square, lamb rotisserie (souvla) turning over charcoal, and deeply-rooted flavors of the Greek countryside like homemade tiropita."},

165: {'d': "Kasabanın labirent sokaklarında saklanan Strong Rooster, özellikle yerel esnaf ve mahalle sakinlerinin sabah kahvesi için uğradığı mütevazı bir Yunan kafesidir. Sıkı demlenmiş Yunan kahvesi, boyoz ve simit gibi sabah ürünleriyle adada günü erken başlayanların vazgeçilmez durağına dönüşmüştür.",
    'de': "Hidden in the labyrinthine streets of town, Strong Rooster is a modest Greek café particularly frequented by local tradespeople and neighborhood residents for morning coffee. With strongly brewed Greek coffee and morning products like boyoz and simit, it has become the indispensable stop for those who start the day early on the island."},

168: {'d': "Mykonos kasabasındaki Jayont, şehrin yoğun gece hayatına alternatif arayan, kaliteli kokteyl ve keyifli sohbet ortamı isteyen ziyaretçiler için seçilmiş müzik listesi ve sıcak ambiyansıyla öne çıkan bir bar mekanıdır. Hem yerel hemde ziyaretçi müdavim tabanıyla kasabanın farklı katmanlarıyla tanışmak için iyi bir başlangıç noktası.",
    'de': "Jayont in Mykonos town is a bar venue that stands out with a curated music list and warm ambiance for visitors seeking an alternative to the town's intense nightlife who want quality cocktails and enjoyable conversation. With both local and visitor regular clientele, it is a good starting point for meeting the town's different layers."},

172: {'d': "Yunanistan genelinde yaygın olan Coffee Island zincirinin Mykonos şubesi, adanın diğer kahve mekanlarına kıyasla en tutarlı kalite-fiyat dengesini sunan duraklardandır. Freddo espresso ve cappuccino ile İtalyan tarzı tatlılar eşliğinde kasabada hızlı ama kaliteli bir kahve molası için güvenilir bir seçenek.",
    'de': "The Mykonos branch of the nationwide Coffee Island chain is one of the stops offering the most consistent quality-to-price balance compared to the island's other coffee venues. A reliable option for a quick but quality coffee break in town with freddo espresso and cappuccino accompanied by Italian-style sweets."},

173: {'d': "Ano Mera'nın taş meydanındaki bu fırın, sabahın ilk saatlerinde adanın dört bir yanında dağıtılan ekmeği pişiren köyün mahalle fırınıdır. Yoğurt dolgulu börek, tahini ekmeği ve tahin pekmezi ile donatılmış simit, köy sakinlerinin her sabah düzenli olarak uğradığı bu küçük fırını adanın en otantik köşelerinden birine dönüştürür.",
    'de': "This bakery in Ano Mera's stone square is the village neighborhood bakery that bakes bread distributed across the island in the early morning hours. Yogurt-filled börek, tahini bread, and sesame rings topped with tahini molasses transform this small bakery where village residents stop every morning into one of the island's most authentic corners."},

176: {'d': "Mykonos kasabasındaki bu kafe-bar, adanın merkezi işlek noktalarından birinde konumlanmış, sabah kahvesinden gece bir kadeh şaraba uzanan esnek servis saatiyle hem erken hem geç ziyaretçiye hitap eder. Özenle seçilmiş beyaz şaraplar ve taze limon suyu katkılı aperol spritz mevsimin en çok sipariş edilen içkilerinden biridir.",
    'de': "This café-bar in Mykonos town is located at one of the island's central busy points and appeals to both early and late visitors with flexible service hours stretching from morning coffee to an evening glass of wine. Carefully selected white wines and aperol spritz with fresh lemon juice are among the season's most ordered drinks."},

178: {'d': "Adanın farklı noktasındaki ikinci Veneti şubesi, aynı güvenilir Yunan pastacılık markasının Mykonos'taki genişleyen varlığını yansıtıyor. Geleneksel Yunan tatlı kültürünü en erişilebilir ve tutarlı biçimde yaşatan bu şube, adanın değişik mahallelerinde konumlanan ziyaretçiler için pratik bir alternatif oluşturur.",
    'de': "The second Veneti branch at a different point on the island reflects the same reliable Greek pastry brand's expanding presence in Mykonos. Bringing traditional Greek sweet culture to life in the most accessible and consistent way, this branch forms a practical alternative for visitors located in different neighborhoods of the island."},

179: {'d': "Ano Mera'nın sakin meydanında köklü bir yerel pastane olan Matsouka, tahini-bal tostundan üzümlü loukoumadese uzanan geleneksel Yunan sabah ürünleriyle köy ziyaretçilerini karşılıyor. Kasabanın turistik kalabalığından uzak bu fırın, Mykonos'un gerçek sabah ritüelini en saf biçimde sunan mekânlardan biridir.",
    'de': "A well-established local pastry shop in Ano Mera's tranquil square, Matsouka welcomes village visitors with traditional Greek morning products stretching from tahini-honey toast to raisin loukoumades. This bakery far from the town's tourist crowds is one of the venues that presents Mykonos's real morning ritual in its purest form."},

181: {'d': "Kasabanın sakin arka sokaklarında müdavimlerin bulmayı bildiği Stylianou Aikaterini, ev yemekleri konseptini modern bir sunum anlayışıyla harmanlayan küçük aile restoranıdır. Günlük taze hazırlanan pastitsio, domates dolgulu biber ve kıymalı kabak çiçeği gibi anneanneden öğrenilmiş tarifler menünün özünü oluşturur.",
    'de': "Stylianou Aikaterini, found by regulars in the town's quiet back streets, is a small family restaurant that blends the home cooking concept with a modern presentation approach. Recipes learned from grandmothers like daily fresh-prepared pastitsio, tomato-stuffed peppers, and minced meat zucchini blossoms form the essence of the menu."},

182: {'d': "Mykonos kasabasında yeni nesil Asya füzyon mutfağını temsil eden Sentu, Japon, Koreli ve Yunan lezzetlerini özgün bir perspektifle birleştiriyor. Miso soslu ahtapot, kimchi katkılı deniz ürünleri ve ponzu soslu orzo tabakları, adada henüz keşfedilmeyi bekleyen alternatif bir lezzet haritası çiziyor.",
    'de': "Sentu, representing the new generation of Asian fusion cuisine in Mykonos town, combines Japanese, Korean, and Greek flavors from an original perspective. Miso-sauced octopus, kimchi-infused seafood, and ponzu-sauced orzo plates draw an alternative flavor map on the island still waiting to be discovered."},
}

apply_batch('mykonos.json', U)
