import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
0: {'d': "Palermo'nun kuruluş hikayesini mimari diliyle anlatan bu katedral, 1184'te inşa edilmiş olmakla birlikte Normann, Bizans, Arap ve Barok üslupların inanılmaz birikimini tek bir yapıda barındırır. Çatı terasından şehrin tüm panoraması serilir; içeride ise Roger II ve Constance of Hauteville'in lahitleri tarihin ağırlığını hissettirir.",
    'de': "This cathedral, which tells Palermo's founding story in architectural language, was built in 1184 but houses the incredible accumulation of Norman, Byzantine, Arab, and Baroque styles within a single structure. The rooftop terrace unfolds the city's full panorama; inside, the tombs of Roger II and Constance of Hauteville make history's weight felt.",
    't': "Çatı terasına çıkış ayrıca ücretlidir ama Palermo'nun 360 derece manzarası için kesinlikle değer. Erken saatte gelin, öğlen kalabalık olur.",
    'te': "Access to the roof terrace is separately charged but absolutely worth it for Palermo's 360-degree panorama. Come early as it gets crowded by noon."},

9: {'d': "Palermo'nun güney kesimindeki bu Arap-Normann sarayı, 12. yüzyılda Roger II tarafından bir av köşkü olarak inşa edilmiş ve çevresindeki yapay gölüyle Sicilya tarihinin en benzersiz mimari miraslarından birini oluşturmaktadır. Adını 'tatlı deniz' anlamına gelen Arapça Mardulsi'den alan bu yapı, bugün restorasyon sürecinde ziyaretçilere açıktır.",
    'de': "This Arab-Norman palace in Palermo's southern district was built in the 12th century by Roger II as a hunting lodge and, with its surrounding artificial lake, forms one of the most unique architectural heritages of Sicilian history. This structure, whose name derives from Arabic Mardulsi meaning 'sweet sea,' is currently open to visitors during its restoration process.",
    't': "Yapı şehir merkezinden uzaktır; taksi veya dolmuşla ulaşmak önerilir. Restorasyon devam ettiğinden ziyaret öncesi açık olup olmadığını kontrol edin.",
    'te': "The structure is far from the city center; it is recommended to reach it by taxi or minibus. Check if it is open before visiting as restoration is ongoing."},

12: {'d': "La Martorana olarak da bilinen bu 12. yüzyıl kilisesi, Bizans mozaik sanatının Sicilya'daki en parlak örneklerinden birine ev sahipliği yapar. Roger II'yi taçlandıran Hristos mozaiği ve altın zemin üzerindeki melekler, Normann dönemi sanatçılarının Bizans ustalarıyla omuz omuza çalıştığının en çarpıcı kanıtıdır.",
    'de': "This 12th-century church, also known as La Martorana, houses one of the most brilliant examples of Byzantine mosaic art in Sicily. The Christ mosaic crowning Roger II and the angels on a golden ground are the most striking evidence that Norman-era artists worked shoulder to shoulder with Byzantine masters.",
    't': "Kilise meydanda, Bellini Meydanı'nda yer alır; aynı meydandaki San Cataldo Kilisesi ile birlikte ziyaret edin. Öğle saati kapanmasına dikkat edin.",
    'te': "The church is in Piazza Bellini; visit it together with San Cataldo Church in the same square. Be careful of the midday closure."},

13: {'d': "Palermo'nun dini mirasının en tatlı sürprizi olan San Giovanni degli Eremiti, kırmızı balkabağı şeklindeki kubbesiyle Bizans-Normann geleneğinin en özgün ifadelerinden birini sunar. Yanı başındaki küçük bahçe ve portakal ağaçları, İspanya bahçelerini andıran bir gölge ve huzur köşesi oluşturur.",
    'de': "The sweetest surprise of Palermo's religious heritage, San Giovanni degli Eremiti presents one of the most original expressions of the Byzantine-Norman tradition with its pumpkin-red domes. The small garden and orange trees beside it form a shaded and peaceful corner reminiscent of Spanish gardens.",
    't': "Giriş ücretlidir; bilet alırken yanındaki Norman Sarayı'nı da kapsayan kombine bilet almak daha ekonomiktir.",
    'te': "Entry is paid; buying a combined ticket that also covers the Norman Palace next door is more economical."},

16: {'d': "Palermo'nun batı kesimindeki bu Normann bahçesi ve saray kalıntısı, 12. yüzyılda olduğu gibi bugün de gölgeli ağaçlar, fıskiyeli havuzlar ve taş kemerli galeri yürüyüşleriyle eski bir cennet bahçesi havasını yaşatır. Zisa Sarayı'nın içindeki su sistemi, Orta Çağ Arap mühendisliğinin Sicilya'ya bıraktığı en önemli izlerden biridir.",
    'de': "This Norman garden and palace ruin in Palermo's western district preserves the atmosphere of an ancient paradise garden today as in the 12th century, with shaded trees, fountained pools, and stone-arched gallery walks. The water system inside Zisa Palace is one of the most important traces left by medieval Arab engineering in Sicily.",
    't': "Özellikle öğleden sonra 15:00-17:00 arası bahçedeki gölge saatleri ziyaret için idealdir; Palermo yazlarında gündüz sıcağından kaçmak için mükemmel.",
    'te': "The afternoon shade hours between 3-5pm are ideal for a visit; perfect for escaping the midday heat of Palermo summers."},

22: {'d': "Palermo'nun tarihi ekseni olan Cassaro Alto, antik çağda Fenike yerleşiminden bu yana kentin iskelet yapısını oluşturan bu ana caddedir. Porta Nuova'dan Porta Felice'ye uzanan bu eksen boyunca yürümek; Barok sarayları, sokak satıcıları, kiliseler ve modern mağazaları aynı anda deneyimleme fırsatı verir.",
    'de': "Cassaro Alto, Palermo's historic axis, is the main street that has formed the city's skeletal structure since Phoenician settlement in antiquity. Walking along this axis stretching from Porta Nuova to Porta Felice offers the opportunity to simultaneously experience Baroque palaces, street vendors, churches, and modern shops.",
    't': "Akşam yürüyüşü (passeggiata) için idealdir; yerel halk her gün 18:00-20:00 arası bu sokağa çıkar ve şehrin gerçek sosyal ritmi burada yaşanır.",
    'te': "Ideal for the evening walk (passeggiata); locals come out to this street every day between 6-8pm and the city's real social rhythm is lived here."},

25: {'d': "Palermo yakınlarındaki Cefalà Diana'da yer alan bu Arap dönemi ılıca kalıntısı, 10. yüzyıldan kalma kemer mimarisi ve doğal ısıtmalı havuzuyla Sicilya'nın İslam mirasının en az tanınan ama en etkileyici ayak izlerinden birini oluşturur. Palermlilerin sık ziyaret ettiği bu dinlenme alanı, turistlerin henüz tam keşfedemediği bir yerdir.",
    'de': "Located in Cefalà Diana near Palermo, this Arab-era thermal ruin with its 10th-century arched architecture and naturally heated pool forms one of the least known but most impressive footprints of Sicily's Islamic heritage. Frequently visited by Palermitans, this rest area is a place tourists have not yet fully discovered.",
    't': "Palermo merkeze 40 km uzaklıkta; araç ile ulaşmak şart. Ilık kaynaklar yıl boyunca aktiftir, sezon dışı ziyaret de mümkün.",
    'te': "40 km from central Palermo; a car is essential. The warm springs are active year-round, making an off-season visit possible too."},

30: {'d': "1874 yılında açılan Grand Hotel et Des Palmes, Palermo'nun en prestijli tarihsel oteli olarak Wagner'den Camus'ya uzanan ünlü konuk listesiyle adını yaptırmıştır. Barok sütunları, avize ışıklarıyla aydınlanan büyük salonu ve kışlık bahçesiyle otelin kendisi başlı başına bir tarihi gezi durakladır; lobide bir kahve içmek bile farklı bir deneyim.",
    'de': "Opened in 1874, Grand Hotel et Des Palmes has made its name as Palermo's most prestigious historical hotel with a famous guest list stretching from Wagner to Camus. With its Baroque columns, grand hall illuminated by chandelier lights, and winter garden, the hotel itself is a historic tour stop; even a coffee in the lobby is a different experience."},

31: {'d': "Eski şehrin kalbindeki tarihi bir sarayda konumlanan Palazzo Brunaccini, Palermo'nun kaliteli butik otelleri arasında özgün taş duvarlarıyla çevrili avlusu, fresk süslemeli odaları ve kişiselleştirilmiş konukseverliğiyle en çok önerilen adreslerden biridir.",
    'de': "Located in a historic palace at the heart of the old city, Palazzo Brunaccini is among the most recommended addresses in Palermo's quality boutique hotels for its courtyard surrounded by original stone walls, fresco-decorated rooms, and personalized hospitality."},

32: {'d': "Palermo'nun kuzey sahil bölgesi Addaura'da konumlanan bu otel ve residence, şehir merkezi yoğunluğundan uzakta Tirenin'e bakan sessiz terasları ve toplantı kapasitesiyle hem iş konferansı hem de aile tatili için çok yönlü bir konaklama seçeneği sunmaktadır.",
    'de': "Located in Palermo's northern coastal district of Addaura, this hotel and residence offers a versatile accommodation option for both business conferences and family holidays with its quiet terraces facing the Tyrrhenian Sea away from city center density and meeting capacity."},

33: {'d': "Palermo merkezinde iyi konumlanmış Hotel Ambasciatori, şehrin tarihi alanlarına yürüme mesafesinde uygun fiyatlı ve güvenilir bir konaklama sunar. Temiz odaları ve sabah kahvaltısıyla şehri aktif bir şekilde keşfetmek isteyen ziyaretçiler için pratik bir merkezi üs oluşturmaktadır.",
    'de': "Well-positioned in central Palermo, Hotel Ambasciatori offers affordable and reliable accommodation within walking distance of the city's historic sites. With its clean rooms and morning breakfast, it forms a practical central base for visitors wanting to actively explore the city."},

34: {'d': "Palermo'nun tarihi merkezinde bir Normann çağı binasına yerleşmiş La Locanda del Drago, taş merdivenleri ve fresk izleri taşıyan koridorlarıyla şehrin tarihi mirasının içinde yaşama deneyimi sunan özel bir butik pansiyondur. Güler yüzlü aile yönetimi, kişisel öneriler ve ev yapımı kahvaltıyla farklı bir konaklama sunar.",
    'de': "La Locanda del Drago, nestled in a Norman-era building in Palermo's historic center, is a private boutique guesthouse offering the experience of living within the city's historical heritage with stone stairways and corridors bearing traces of frescoes. Warm family management, personal recommendations, and homemade breakfast provide a different accommodation experience."},

35: {'d': "Vegetaryen ve vegan Sicilya mutfağını keşfetmek isteyenler için Il Mirto e la Rosa, Palermo'nun en ileri görüşlü lokantalarından biri olarak öne çıkıyor. Sezonluk sebzeler, yerel peynirler ve Sicilya otlarıyla hazırlanan yaratıcı menüsü, geleneksel İtalyan et kültürüne alternatif olarak özgün bir Sicilya gastronomi deneyimi sunuyor.",
    'de': "For those wanting to discover vegetarian and vegan Sicilian cuisine, Il Mirto e la Rosa stands out as one of Palermo's most forward-thinking restaurants. Its creative menu prepared with seasonal vegetables, local cheeses, and Sicilian herbs offers an original Sicilian gastronomy experience as an alternative to traditional Italian meat culture."},

36: {'d': "Palermo'da et yemeği söz konusu olduğunda Falstaff Steakhouse, Sicilya dana etini İngiliz steakhouse geleneğiyle harmanlayan ender mekanlardan biridir. Kuru olgunlaştırılmış Sicilya eti, taze hazırlanmış frites ve yerel Nero d'Avola şarabıyla yaratıcı bir gastronomik sentez sunar.",
    'de': "When it comes to meat eating in Palermo, Falstaff Steakhouse is one of the rare venues that blends Sicilian beef with English steakhouse tradition. It offers a creative gastronomic synthesis with dry-aged Sicilian beef, freshly prepared frites, and local Nero d'Avola wine."},

37: {'d': "Kalsa Mahallesi'nin tarihi bir sarayına yerleşmiş Kalhesa, gün boyu kafe olarak çalışıp akşamları taze deniz ürünleri ve Japon füzyon menüsüyle donanan çok yönlü bir mekan. Kaya duvarlarının ve tarihi tavanın altında sushi ile Sicilya midyesinin bir arada sunulması şehrin en ilginç mutfak denemelerinden birini oluşturuyor.",
    'de': "Kalhesa, settled in a historic palace in the Kalsa neighborhood, is a versatile venue that operates as a café all day and is equipped with fresh seafood and Japanese fusion menu in the evenings. Sushi and Sicilian mussels presented together under stone walls and a historic ceiling constitutes one of the city's most interesting culinary experiments."},

39: {'d': "Palermo'nun tarihi Mercato della Vucciria yakınlarındaki Il Baro, şehrin pek çok doğal şarabını, yerel üreticilerin birasını ve taze hazırlanmış atıştırmalıklarını bir arada sunan kaliteli bir şarap barı olarak şehrin alternatif sosyal sahnesi üzerinde önemli bir yer ediniyor. Yaz akşamlarında dışarıya taşan masaları şehrin canlı bir sosyal karışımını yansıtır.",
    'de': "Il Baro near Palermo's historic Mercato della Vucciria has gained an important place on the city's alternative social scene as a quality wine bar serving many of the city's natural wines, local producers' beers, and freshly prepared snacks together. Its tables spilling outside on summer evenings reflect a lively social mix of the city."},

44: {'d': "Palermo'nun kuzey kesiminde gizlenmiş 19. yüzyıl Villa Boscogrande, bahçesinde film setleri kurulmuş tarihi bir konak olarak özel etkinlikler, düğünler ve lüks konaklama için adeta bir cennet köşesidir. Visconti'nin 'Leopar' filmine de mekan olan bu villa, hem tarihi hem de sinematografik bir atmosfer taşır.",
    'de': "19th-century Villa Boscogrande hidden in Palermo's northern district is a paradise corner for private events, weddings, and luxury accommodation as a historic mansion on whose grounds film sets have been constructed. This villa, which also served as a location for Visconti's 'The Leopard,' carries both a historic and cinematographic atmosphere."},

45: {'d': "Viale Strasburgo'daki Trattoria Biondo, 1950'lerden bu yana Palermo sakinlerinin düzenli gittiği geleneksel Sicilya lokantasıdır. Pazı dolmalı sarda balığı (sarde a beccafico), kuskus alla trapanese ve tiella di riso gibi unutulmaya yüz tutmuş Sicilya tariflerini yaşatan bu trattoria, otantik şehir gastronomi turizminin en sağlam adreslerinden biridir.",
    'de': "Trattoria Biondo on Viale Strasburgo has been the traditional Sicilian restaurant that Palermo residents have regularly visited since the 1950s. This trattoria that keeps alive nearly forgotten Sicilian recipes like sarde a beccafico (stuffed sardines with breadcrumbs), cuscus alla trapanese, and tiella di riso is one of the most solid addresses of authentic urban gastronomy tourism."},

46: {'d': "Bellini Meydanı'na bakan Antica Pizzeria Bellini, Piazza Bellini'nin en köklü gastronomik temsilcisi olarak taze San Marzano domatesli, Fior di latte peynirli Napoli usulü pizzasıyla şehrin en sevilen pizza duraklarından biri olmayı sürdürüyor. Dış masalarda meydanın canlı atmosferi eşliğinde pizza yemek, Palermo'daki yemek anlarının en keyifli olanlarından.",
    'de': "Antica Pizzeria Bellini facing Piazza Bellini continues to be one of the city's most beloved pizza stops as the most deep-rooted gastronomic representative of Piazza Bellini, with its Neapolitan-style pizza with fresh San Marzano tomatoes and Fior di latte cheese. Eating pizza at outdoor tables accompanied by the square's lively atmosphere is one of the most enjoyable dining moments in Palermo."},

47: {'d': "Palermo'nun Mondello sahil bölgesindeki bu geleneksel pastane, 1885'ten bu yana cannolo alla Siciliana, frutta di martorana ve granita con brioche ile nesiller boyu devam eden bir tatlı geleneğini yaşatmaktadır. Sahil gezisinin ardından girilen bu pastane, Sicilya tatlı kültürüyle buluşmanın en tarihli adreslerinden biridir.",
    'de': "This traditional pastry shop in Palermo's Mondello beach district has been preserving a sweet tradition passed down through generations since 1885 with cannolo alla Siciliana, frutta di martorana, and granita con brioche. This pastry shop entered after a coastal stroll is one of the most historic addresses for encountering Sicilian sweet culture."},

48: {'d': "Palermo şehir merkezindeki bu kahve kapsülü ve kafeterya ekipmanı mağazası, profesyonel makine bakımı ve ev kullanımı için çok çeşitli kahve kapsülleri sunar. Sicilya'daki kahve kültürünü yüksek kaliteli çekirdeklerle evde yaşatmak isteyenler için şehrin pratik tedarik adreslerinden biridir.",
    'de': "This coffee capsule and cafeteria equipment shop in central Palermo offers professional machine maintenance and a wide variety of coffee capsules for home use. It is one of the city's practical supply addresses for those wanting to experience Sicilian coffee culture at home with high-quality beans."},

50: {'d': "Palermo'nun specialty coffee sahnesi söz konusu olduğunda Vago-Rizzuto, tek kökenli filtre kahve ve özenli espresso hazırlığıyla şehrin en dikkat çekici üçüncü dalga kahve durağı olarak öne çıkıyor. Günlük değişen çekirdek seçimi ve baristayla kurulan kişisel diyalog, bu küçük mekanı aynı sokakta onlarca kafe arasından ayrıştırıyor.",
    'de': "When it comes to Palermo's specialty coffee scene, Vago-Rizzuto stands out as the city's most notable third-wave coffee stop with single-origin filter coffee and meticulous espresso preparation. A daily changing bean selection and personal dialogue with the barista distinguishes this small venue from dozens of cafés on the same street."},

51: {'d': "Palermo sahilindeki bu küçük kafeterya, köylüler ve teknecilerin kahvaltı için tercih ettiği, gerçek granita di caffè con panna ve taze sıkılmış portakal suyu sunan mütevazı ama özgün bir Palermo sabahı durağıdır. Turistlerin pek uğramadığı bu küçük mekan, yerel ritmin içindeyken şehri deneyimlemenin en doğru yollarından birini sunuyor.",
    'de': "This small café on Palermo's coast is a modest but genuine Palermo morning stop preferred by villagers and boatmen for breakfast, serving real granita di caffè con panna and freshly squeezed orange juice. This small venue rarely visited by tourists offers one of the truest ways to experience the city while within the local rhythm."},

52: {'d': "Storico Antico Caffè, Palermo'nun en eski kafeteryaları arasında, tarihi atmosferini mobilyasından dekoruna kadar koruyan nadir mekanlardan biridir. Sabah Sicilya geleneksel brioche con gelato ile başlanması, öğleden sonra taze squeezed arancello servisiyle devam etmesi, bu mekanı hem tarihi hem gastronomik bir deneyim olarak değerli kılar.",
    'de': "Storico Antico Caffè is among Palermo's oldest cafés, one of the rare venues that preserves its historical atmosphere from its furniture to its décor. Starting the morning with a traditional Sicilian brioche con gelato and continuing in the afternoon with freshly squeezed arancello service makes this venue valuable as both a historic and gastronomic experience."},

55: {'d': "Palermo'nun Kalsa mahallesi yakınlarındaki Kiro Cafè, şehrin yeni nesil kafe kültürünü doğal malzemeler, düşük kafeyli alternatif içecekler ve sürdürülebilir ambalaj anlayışıyla harmanlamaktadır. Taze hazırlanan protein barları, avokado tosty ve smoothie kaselerine önem veren menüsüyle şehrin sağlıklı yaşam odaklı genç kitlesine hitap eder.",
    'de': "Kiro Cafè near Palermo's Kalsa neighborhood blends the city's new generation café culture with natural ingredients, low-caffeine alternative drinks, and a sustainable packaging approach. With its menu that emphasizes freshly prepared protein bars, avocado toast, and smoothie bowls, it appeals to the city's health-conscious young audience."},

58: {'d': "Palermo'nun tarihi merkezinde, Sicilya zanaatkârlarının ürettiği seramik, cam ve tekstil ürünlerini bir araya getiren Casa Stagnitta, ada zanaatkârlık geleneğini yaşatmak için kurulan sosyal girişim kökenli bir butik ve kafedir. El yapımı ürünlerin yanı sıra özenle seçilmiş yerel kahve ve tatlılar da mekanı çok yönlü bir durak hâline getirir.",
    'de': "Casa Stagnitta in Palermo's historic center is a social enterprise-origin boutique and café established to keep the island's craftsmanship tradition alive, bringing together ceramics, glass, and textile products crafted by Sicilian artisans. In addition to handmade products, carefully selected local coffee and sweets also make the venue a versatile stop."},

59: {'d': "Palermo'nun en eski kahvelerinden biri olan Antico Caffè Ventimiglia, 19. yüzyıldan kalma iç mekan atmosferi, doldurulmuş hayvan sergisi ve eski fotoğraflarla şehrin tarihi kafe kültürünü en bütünlüklü biçimde yaşatan mekânlarından biridir. Birkaç adım ötede 'Quattro Canti' meydanına bakması onu hem tarihi hem konum itibarıyla Palermo'daki kahve anlarının en değerlisi yapıyor.",
    'de': "Antico Caffè Ventimiglia, one of Palermo's oldest cafés, is one of the venues that most comprehensively preserves the city's historic café culture with its 19th-century interior atmosphere, taxidermy display, and old photographs. Its proximity just a few steps away from the 'Quattro Canti' square makes it the most valuable of coffee moments in Palermo both historically and locationally."},

60: {'d': "Palermo eski şehrinde konumlanan Maison Bocum, hem butik suite konaklama hem de Sicilya pastacılık geleneğini modern dokunuşlarla buluşturan küçük bir fırın-kafe olarak özgün bir ikili kimlik taşır. Taze cannoli, arancino di riso ve günlük değişen spesyallerle sabah saatlerinde ziyaret için en keyifli şehir adreslerinden biri.",
    'de': "Maison Bocum located in Palermo's old town carries a unique dual identity as both a boutique suite accommodation and a small bakery-café that brings together Sicilian pastry tradition with modern touches. With fresh cannoli, arancino di riso, and daily changing specials, it is one of the most enjoyable city addresses for a morning visit."},

63: {'d': "Mercato Ballarò yakınındaki bu sade Sicilya restoranı, adının söylediği gibi 'Sicilyalıların yaptığı şekilde' hazırlanan gerçek sokak mutfağını lokanta ortamına taşımaktadır. Stigghiola (kuzu bağırsak), pani câ meusa (dalak sandviçi) ve taze arancino, kasabın arka bahçesi havasındaki bu mekanda en özgün hâliyle sunulur.",
    'de': "This simple Sicilian restaurant near Mercato Ballarò brings genuine street food prepared 'the way Sicilians do it,' as its name suggests, into a restaurant setting. Stigghiola (lamb intestines), pani câ meusa (spleen sandwich), and fresh arancino are presented in their most original form in this venue with a butcher's backyard atmosphere."},

64: {'d': "Sicilya'nın Spinnato pastane markasının ürünlerini çikolata mağazasıyla birleştiren bu mekan, Palermo'nun en yetkin premium tatlı duraklarından biri olarak granita con brioche, cioccolato di Modica ve mevsim meyveleriyle hazırlanan fresh sorbeleriyle ünlüdür. Mağaza içinde tatma ve satın alma deneyiminin birlikte yaşandığı nadir şehir adreslerinden biridir.",
    'de': "This venue combining products of Sicily's Spinnato pastry brand with a chocolate shop is one of Palermo's most competent premium sweet stops, famous for granita con brioche, cioccolato di Modica, and fresh sorbets prepared with seasonal fruits. It is one of the rare city addresses where the tasting and purchasing experience is lived together in the shop."},

66: {'d': "Palermo'nun gece hayatında köklü bir isim olan Berlin Cafè, özellikle üniversite öğrencileri ve genç yerel halkın tercihiyle şehrin en canlı akşam barlarından biri konumundadır. Dondurma üreticisi ile sanatçıların buluştuğu bu yarı-kültürel mekanda, Sicilya doğal şarapları ve yerel craft birasıyla sosyal bir başlangıç yaşanır.",
    'de': "Berlin Cafè, a deep-rooted name in Palermo's nightlife, is one of the city's liveliest evening bars especially with the preference of university students and young locals. In this semi-cultural venue where ice cream makers meet artists, a social beginning is experienced with Sicilian natural wines and local craft beer.",
    't': "Akşam 19:00-21:00 aperitivo saatinde küçük atıştırmalıklar ücretsiz sunulur; içki fiyatlarına dahildir.",
    'te': "Small snacks are served free during the aperitivo hour from 7-9pm; included in the drink prices."},

68: {'d': "Palermo'nun arka mahallelerinde saklanan Drunk's, şehrin alternatif gece sahnesi içinde en özgün cocktail bar adreslerinden birini oluşturuyor. Bartenderların kendi icat ettiği imza kokteylleri, Sicilya yerel likörleri ve günün rotasyonlu playlist'i, sıradan akşam saatini beklenmedik bir deneyime dönüştürüyor.",
    'de': "Drunk's, hidden in Palermo's back neighborhoods, forms one of the most original cocktail bar addresses within the city's alternative night scene. Signature cocktails invented by the bartenders themselves, Sicilian local liqueurs, and the daily rotating playlist transform an ordinary evening into an unexpected experience.",
    't': "Barmanlara Sicilya amaro ve liquore tabanlı imza içki hazırlamasını isteyin; menüde olmayan özel tatlar genellikle mümkündür.",
    'te': "Ask the bartenders to prepare a signature drink based on Sicilian amaro and liquore; special flavors not on the menu are usually possible."},

69: {'d': "Palermo'nun Vucciria meydanına yakın CuFu, günün erken saatlerinde taze sıkılmış portakal suyu ve arancino ile başlayıp öğleden sonra Sicilya birası ve meze ile devam eden, akşamları ise canlı müzikli bir meydana dönüşen çok işlevli bir sokak kafesidir. Palermo'nun gündelik sosyal ritmine en yakın mekânlardan biridir.",
    'de': "CuFu near Palermo's Vucciria square is a multifunctional street café that starts early in the day with freshly squeezed orange juice and arancino, continues in the afternoon with Sicilian beer and mezze, and transforms into a lively music-filled square in the evenings. It is one of the venues closest to Palermo's everyday social rhythm."},

71: {'d': "Palermo'nun Vucciria semtindeki bu şarap ve speakeasy barı, tarihi mekânın taş duvarlarını beyaz şarap, doğal Sicilya üzümü ve amaro etiketleriyle süsleyerek şehrin yaratıcı gece kimliğine özgün bir katkı sunuyor. Günün şarabını (vino del giorno) şişenin etiketi yerine barmenin sözlü anlatısıyla seçmek burada standart bir uygulama.",
    'de': "This wine and speakeasy bar in Palermo's Vucciria district makes an original contribution to the city's creative nocturnal identity by adorning the historic venue's stone walls with white wine, natural Sicilian grape, and amaro labels. Choosing the wine of the day (vino del giorno) through the bartender's verbal narration rather than the bottle's label is standard practice here."},

72: {'d': "Palermo'nun eğlence mekanları arasında farklı bir yer tutan Big Bingo & Joka Slot, yerel mahalle sakinlerinin tartışmasız sosyal buluşma ritüelini yaşatır. Bingo kartlarının heyecanı ve slot makinelerinin ışıltısı eşliğinde gürültülü, samimi bir Sicilya akşamı deneyimi, şehrin turizm dışı yaşamını merak edenlere kıymetli bir gözlem noktası sunar.",
    'de': "Big Bingo & Joka Slot, occupying a different place among Palermo's entertainment venues, preserves the undisputed social gathering ritual of local neighborhood residents. A noisy, sincere Sicilian evening experience accompanied by the excitement of bingo cards and the glitter of slot machines offers a valuable observation point for those curious about the city's life outside tourism.",
    't': "Bu mekan yerel halkın alanıdır; ziyaret ederseniz saygılı ve sessiz bir gözlemci olun, fotoğraf çekmeden önce izin isteyin.",
    'te': "This venue is a local residents' space; if you visit, be a respectful and quiet observer, and ask permission before taking photos."},

77: {'d': "Palermo'nun eski şehir dışındaki semtlerde, şehrin gece hayatının en kalabalık seçeneklerinden biri olan Country DiscoClub, yaz mevsiminde açık hava dansını, yerel DJ'leri ve tam anlamıyla Sicilya gece ruhunu bünyesinde barındırır. Palermo gençliğinin gece programını nasıl geçirdiğini görmek isteyenler için biçilmiş kaftan.",
    'de': "Country DiscoClub, one of the most crowded nightlife options in neighborhoods outside Palermo's old city, houses open-air dancing, local DJs, and the full Sicilian night spirit in the summer season. Tailor-made for those wanting to see how Palermo's youth spend their night program.",
    't': "Gece 01:00'den önce mekan henüz ısınmaktadır; sakin bir ilk saatin ardından gece yarısı sonrası en kalabalık ve en enerjik hale gelir.",
    'te': "The venue is still warming up before 1am; after a quiet first hour it reaches its most crowded and energetic state after midnight."},

81: {'d': "Palermo'nun Space Club'ı, adanın en tanınan elektronik müzik kulüplerinden biri olarak uluslararası DJ'leri Sicilya'ya çeken köklü bir gece hayatı referans noktasıdır. Büyük kapasiteli ses sistemi, Sicilya'ya özgü ışık tasarımı ve geniş açık hava dansalonu sezon boyunca her hafta sonu şehrin en canlı partilerinden birini sunmaktadır.",
    'de': "Palermo's Space Club is a deep-rooted nightlife reference point that draws international DJs to Sicily as one of the island's most recognized electronic music clubs. Its large-capacity sound system, Sicily-specific lighting design, and wide open-air dance floor present one of the city's liveliest parties every weekend throughout the season.",
    't': "Büyük etkinliklerde bilet önceden online satın alınmalıdır; kapıda uzun kuyruktan kaçınmak için en az 2 saat önceden guestlist kaydı yaptırın.",
    'te': "Tickets for major events must be purchased online in advance; register on the guestlist at least 2 hours ahead to avoid a long door queue."},

82: {'d': "Palermo'nun tarihi dokusu içindeki bu geleneksel Sicilya trattorias, Ventimiglia ailesine ait tarihi bir mekânda taze hazırlanmış pasta al forno, arancine di riso ve ev yapımı cassata ile köklü Sicilya mutfağını yaşatıyor. Aile tarafından işletilen ve kuşaklar boyu devam eden bu mekan, Palermo'nun otantik yemek kültürünün kaybolmayan adreslerinden biridir.",
    'de': "This traditional Sicilian trattoria within Palermo's historic fabric preserves deep-rooted Sicilian cuisine in a historic venue belonging to the Ventimiglia family with freshly prepared pasta al forno, arancine di riso, and homemade cassata. Family-operated and continuing through generations, this venue is one of the non-disappearing addresses of Palermo's authentic food culture."},
}

apply_batch('palermo.json', U)
