import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

# ── MALLORCA ──────────────────────────────────────────────────────────────────
mallorca = {
0:  {'t': "Katedral sabah 10:00 açılır; öğleden önce gelin, Rose Window'dan süzülen renkli ışığı güneş doğrudan içeri vururken görün. Öğleden sonra turistle doluyor.",
     'te': "The Cathedral opens at 10am; come before noon to see the colored light filtering through the Rose Window while the sun shines directly inside. It fills with tourists in the afternoon."},
2:  {'t': "Valldemossa, öğleden sonra turist otobüsleriyle dolmaktadır; sabah 09:00-11:00 arası taş sokaklarda yalnız kalabilirsiniz. Chopin Müzesi girişi ücretlidir.",
     'te': "Valldemossa fills with tourist buses in the afternoon; you can be alone in the stone streets between 9-11am. Chopin Museum entry is paid."},
3:  {'t': "Drach Mağaraları için önceden online bilet alın; giriş saatleri sınırlı ve yazın saatler öncesinden dolmaktadır. İçeride klasik konser de düzenlenmektedir.",
     'te': "Buy tickets for Drach Caves online in advance; entry times are limited and fill up hours ahead in summer. Classical concerts are also held inside."},
4:  {'t': "Port d'Andratx, sabah 08:00-10:00 arası balıkçıların tekneye bindiği sakin limanı ile ve akşam aperitifine oturan sakinleriyle iki farklı yüzünü gösterir.",
     'te': "Port d'Andratx shows two different faces: its calm harbor where fishermen board boats between 8-10am and its residents sitting for evening aperitifs."},
6:  {'t': "Sóller'e vintage tren ile gelmek, kasabaya araçla gelmekten çok daha etkileyicidir; Palma'dan kalkışlar sabah 10:10'dan itibaren başlar ve yolculuk 1 saat sürer.",
     'te': "Coming to Sóller by vintage train is much more impressive than arriving by car; departures from Palma start from 10:10am and the journey takes 1 hour."},
7:  {'t': "Deià, gün boyunca güzel ama özellikle sakin sabah saatlerinde en büyüleyicidir; köy kahvaltısı için kasabanın tek küçük bakkalı sabah 08:30'da açılır.",
     'te': "Deià is beautiful all day but most enchanting in the quiet morning hours; the village's only small grocery shop opens at 8:30am for a village breakfast."},
8:  {'t': "Pollença'nın Calvari Merdivenleri'nin 365 basamağını tırmanmak için sabah serinliğinde gidin; tepeden görünen Tramuntana dağları ve kasaba panoraması için değer.",
     'te': "Go in the morning cool to climb the 365 steps of Pollença's Calvari Stairway; worth it for the Tramuntana mountains and town panorama visible from the top."},
9:  {'t': "Palma Aquarium, çocuklu aileler için en iyi Mallorca aktivitelerinden biridir; sabah girişi daha az kalabalık. Online bilet kapı fiyatından ucuzdur.",
     'te': "Palma Aquarium is one of Mallorca's best activities for families with children; morning entry is less crowded. Online tickets are cheaper than at the door."},
11: {'t': "Sóller vintage treni bilet rezervasyonu çok önemlidir; yüksek sezonda biletler günler öncesinden tükenmektedir. Dönüş biletini de aynı anda alın.",
    'te': "Ticket reservation for the Sóller vintage train is very important; in high season tickets sell out days in advance. Buy the return ticket at the same time."},
13: {'t': "Can Amorós, Binissalem bağcılık bölgesindeki butik bir finca şaraphânesidir; tadım turu için önceden rezervasyon şarttır. Mallorca DO beyaz şarapları burada en iyi haliyle sunulur.",
    'te': "Can Amorós is a boutique finca winery in the Binissalem wine region; advance reservation is essential for a tasting tour. Mallorca DO white wines are presented here at their best."},
14: {'t': "Ca'n Palou de Coma-sema, Serra de Tramuntana'da muhteşem manzaralı tarihi bir finca otelidir; bahar yürüyüş sezonunda konaklamak için en az 4-6 hafta önceden rezervasyon yapın.",
    'te': "Ca'n Palou de Coma-sema is a historic finca hotel with magnificent views in the Serra de Tramuntana; book at least 4-6 weeks in advance for accommodation during the spring hiking season."},
15: {'t': "Ca'n March, Mallorca'nın geleneksel ev mimarisini yaşatan tarihi bir fincadır; çevre bağ ve zeytinliklerle birlikte sabah yürüyüşü programı için idealdir.",
    'te': "Ca'n March is a historic finca that preserves Mallorca's traditional home architecture; ideal for a morning walk program together with the surrounding vineyards and olive groves."},
16: {'t': "Can Crespí, Pla bölgesinin tarihsel finca mirasını yansıtır; köy etrafındaki çarşamba pazarı ile birlikte ziyaret için en uygun gün çarşambadır.",
    'te': "Can Crespí reflects the historical finca heritage of the Pla region; the most suitable day to visit along with the village's Wednesday market is Wednesday."},
17: {'t': "Ca'n Ordines, Mallorca'nın iç bölgelerinde kaybolmuş otantik bir köy evidir; çevre köy programıyla birleştirerek araçla keşfetmek en uygun yoldur.",
    'te': "Ca'n Ordines is an authentic village house lost in Mallorca's interior; the most suitable way to discover it is by car, combining it with a surrounding village program."},
18: {'t': "Can Juny, tarihi bir Mallorca fincasıdır; bağ ve zeytinlik gezintisiyle birleştirilen sabah kahvaltısı deneyimi için ev sahipleriyle önceden iletişime geçin.",
    'te': "Can Juny is a historic Mallorca finca; contact the owners in advance for a morning breakfast experience combined with a vineyard and olive grove walk."},
19: {'t': "Can Ferragut, Mallorca köy mimarisini koruyan tarihi bir yapıdır; çevre alanda bisiklet turu ile birleştirmek için güzergah önceden planlanmalıdır.",
    'te': "Can Ferragut is a historic structure preserving Mallorca village architecture; the route should be planned in advance to combine it with a bicycle tour in the surrounding area."},
20: {'t': "Can Colom, Mallorca'nın iç kesimlerinde otantik bir finca deneyimi sunar; doğa ve tarih kombinasyonunu seven ziyaretçiler için araçla günübirlik ideal bir güzergahtır.",
    'te': "Can Colom offers an authentic finca experience in Mallorca's interior; it is an ideal day-trip route by car for visitors who love the combination of nature and history."},
21: {'t': "Ca'n Llorenç Villalonga, Mallorca edebiyat mirasıyla özdeşleşen bir addır; yakın kasabada yazara ait eserler ve müze ziyareti bilgi için önceden araştırın.",
    'te': "Ca'n Llorenç Villalonga is a name synonymous with Mallorca's literary heritage; research in advance for information on works by the author and museum visits in the nearby town."},
22: {'d': "Can Catlar de Llorer, Mallorca'nın tarihi iç kesimlerinde, zeytinliklere gömülmüş bir Orta Çağ sonrası fincasıdır. Asırlık zeytinlikleri ve bağlarıyla çevrili taş yapısı, adanın köklü tarım mirasını somutlaştıran özgün bir miras alanıdır.",
    'de': "Can Catlar de Llorer is a post-medieval finca buried in olive groves in Mallorca's historic interior. Its stone structure surrounded by centuries-old olive groves and vineyards is an original heritage site that embodies the island's deep-rooted agricultural heritage.",
    't': "Finca çevresindeki zeytinliklerde sabah yürüyüşü için araçla ulaşmak en uygun seçenek; çevre yollar dar ve kıvrımlıdır.",
    'te': "Reaching by car is the most suitable option for a morning walk in the olive groves surrounding the finca; surrounding roads are narrow and winding."},
23: {'t': "Ca'n Ribas de Pina, Mallorca'nın orta kesimlerinde tarihi finca mirasının sürdürüldüğü sakin bir yapıdır; ziyaret ve konaklama için önceden ev sahipliğiyle iletişime geçin.",
    'te': "Ca'n Ribas de Pina is a quiet structure in Mallorca's central area where historic finca heritage is maintained; contact the hosts in advance for a visit and accommodation."},
24: {'t': "Ca'n Oleza, Palma eski şehrinin tarihi saray evlerinden biridir; içi hâlâ özel mülktür, dışarıdan cephe ve avlu kapısı mimari tur açısından değerlidir.",
    'te': "Ca'n Oleza is one of the historic palace houses in Palma's old city; the interior is still private property, but the exterior facade and courtyard gate are valuable from an architectural tour perspective."},
25: {'t': "Can Alemany, Binissalem'in tarihi merkez evlerinden biridir; haftalık çarşı ile aynı gün ziyaret edip yerel şarap ve zeytinyağı satın almak için en verimli program.",
    'te': "Can Alemany is one of the historic central houses of Binissalem; the most efficient program is to visit on the same day as the weekly market and buy local wine and olive oil."},
26: {'t': "CaixaForum Palma, ücretsiz girişiyle Mallorca'nın en erişilebilir çağdaş sanat mekânıdır; öğleden önce ziyaret sergiyi ve meydanı sakin bir şekilde deneyimlemenizi sağlar.",
    'te': "CaixaForum Palma is Mallorca's most accessible contemporary art venue with free entry; a visit before noon lets you experience the exhibition and square calmly."},
65: {'t': "Hotel Caballero, Palma merkezinde uygun fiyatlı konaklama arayanlar için pratik bir seçenek; merkezi konumu sayesinde şehrin tarihi bölgelerine yürüme mesafesindedir.",
    'te': "Hotel Caballero is a practical option for those seeking affordable accommodation in central Palma; its central location means the city's historic areas are within walking distance."},
67: {'t': "Bar Abaco, Palma'nın en görsel ve en şaşırtıcı bar içi tasarımlarından birine sahiptir; akşam 19:00-21:00 arası taze meyve suları ve cocktail için en ideal saatlerdir.",
    'te': "Bar Abaco has one of Palma's most visual and surprising bar interior designs; the most ideal hours for fresh fruit juices and cocktails are between 7-9pm."},
69: {'t': "Zar Society, Palma'nın en tanınan elektronik müzik kulüplerinden biridir; Cumartesi geceleri en kalabalık dönemdir, online guestlist kaydı kapı kalabalığından kurtarır.",
    'te': "Zar Society is one of Palma's most well-known electronic music clubs; Saturday nights are the busiest period, online guestlist registration saves you from the door crowd."},
70: {'t': "El Barbero, Palma'da hem berber hem sosyal mekân konseptiyle öne çıkan özgün bir adrestir; saç kesimi randevusu ile birlikte şehrin hipster kültürünü keşfetmek için ideal.",
    'te': "El Barbero stands out in Palma with the unique address concept of both barbershop and social space; ideal for discovering the city's hipster culture together with a haircut appointment."},
72: {'t': "Bar Sabotage, Palma'nın alternatif gece sahnesinin en bilinen barlarından biridir; canlı müzik geceleri ve DJ setleri için haftalık program sosyal medyada paylaşılır.",
    'te': "Bar Sabotage is one of the most well-known bars of Palma's alternative night scene; the weekly program for live music nights and DJ sets is shared on social media."},
73: {'t': "The2 Palma Gay Bar, Palma'nın LGBTQ+ dostu mekanları arasında merkezi konumuyla kolay erişilebilen bir bardır; Cuma ve Cumartesi geceleri en kalabalık dönemdir.",
    'te': "The2 Palma Gay Bar is an easily accessible bar with a central location among Palma's LGBTQ+-friendly venues; Friday and Saturday nights are the busiest periods."},
75: {'d': "Maraca Club, Mallorca'nın Magaluf bölgesinde Palma eğlence sahnesinin dışında, geniş kapasiteli ve uluslararası DJ'leri bünyesinde barındıran büyük bir kulüptür. Ada genelinden ve dışarıdan gelen ziyaretçilerin sabahın erken saatlerine kadar dans ettiği, Mallorca gece hayatının en enerjik mekânlarından biri olarak öne çıkmaktadır.",
    'de': "Maraca Club is a large club in Mallorca's Magaluf area outside the Palma entertainment scene, housing wide-capacity and international DJs. It stands out as one of Mallorca's most energetic nightlife venues where visitors from across the island and beyond dance until the early morning hours.",
    't': "Magaluf bölgesinde yer alır; Palma'dan araçla yaklaşık 25 dakika. Giriş için online bilet ve guestlist kaydı önerilir.",
    'te': "Located in the Magaluf area; approximately 25 minutes by car from Palma. Online ticket and guestlist registration are recommended for entry."},
76: {'t': "Sa Rambla, Palma'nın gündelik sosyal nabzının attığı gezinti caddesiidir; sabah pazar açıkken taze çiçek ve yerel atıştırmalıklar için ideal.",
    'te': "Sa Rambla is the promenade street where Palma's daily social pulse beats; ideal for fresh flowers and local snacks while the morning market is open."},
77: {'t': "Delfos Girls, Palma'nın gece eğlencesinde kadın ağırlıklı kalabalıklara hitap eden bir mekandır; hafta sonu geceleri için önceden kapasiteyi kontrol edin.",
    'te': "Delfos Girls is a venue catering to female-dominant crowds in Palma's nightlife; check the capacity in advance for weekend nights."},
78: {'t': "Social Club, Palma'da kokteyller ve DJ müziğiyle gecelerin başlangıcı için ideal bir pre-party mekânıdır; gece 22:00-01:00 arası en aktif saatlerdir.",
    'te': "Social Club is an ideal pre-party venue in Palma for evenings starting with cocktails and DJ music; between 10pm-1am are the most active hours."},
79: {'t': "Level Club, Palma eğlence bölgesinde tanınan bir gece kulübüdür; hafta sonu gece yarısı sonrası en yoğun kalabalığa ulaşır. Kapı ücreti ve guestlist için sosyal medyayı takip edin.",
    'te': "Level Club is a well-known nightclub in Palma's entertainment district; it reaches its most intense crowd after midnight on weekends. Follow social media for door fee and guestlist."},
80: {'t': "Camelot, Palma gece hayatında orta segment eğlence arayanlar için erişilebilir bir kulüptür; haftalık tema geceleri ve DJ programı için önceden bakın.",
    'te': "Camelot is an accessible club for those seeking mid-range entertainment in Palma nightlife; check in advance for weekly themed nights and DJ program."},
81: {'t': "Templo Palma, şehrin alternatif kulüp sahnesinde farklı bir kimliğe sahip bir mekandır; özel etkinlik geceleri için program takibi ve erken varış önerilir.",
    'te': "Templo Palma has a different identity on the city's alternative club scene; program tracking and early arrival are recommended for special event nights."},
82: {'t': "Bamboo Club, Palma gece hayatında tanınan tropik temalı bir mekandır; gece 23:00 sonrası dans pisti dolmaktadır, cocktail servisinde tropikal karışımlar öne çıkar.",
    'te': "Bamboo Club is a well-known tropical-themed venue in Palma nightlife; the dance floor fills after 11pm, tropical mixes stand out in the cocktail service."},
83: {'t': "José María Torres, Mallorca finca mirasından gelen tarihi bir isimdir; çevre zeytinlik ve bağ ziyaretleriyle birlikte adanın tarımsal geçmişini keşfetmek için değerli bir güzergâh noktası.",
    'te': "José María Torres is a historic name from Mallorca's finca heritage; a valuable route point for discovering the island's agricultural past together with visits to surrounding olive groves and vineyards."},
}
apply_batch('mallorca.json', mallorca)

# ── RHODES ────────────────────────────────────────────────────────────────────
rhodes = {
0:  {'t': "Orta Çağ Kenti sabah 08:00-10:00 arası neredeyse sessizdir; dar sokaklar bu saatte yürümeye değer. Öğleden sonra kalabalık ve sıcak olduğundan sabah ziyareti şiddetle tavsiye edilir.",
     'te': "The Medieval City is almost silent between 8-10am; the narrow streets are worth walking at this hour. Morning visits are strongly recommended as it becomes crowded and hot in the afternoon."},
1:  {'t': "Grandmaster Sarayı girişi ücretlidir; şehre gelince direkt buraya gidin, öğleden sonra kalabalık artmaktadır. Mozaikler için ziyarette flaş kullanmayın.",
     'te': "Palace of the Grand Master entry is paid; go here directly upon arriving in the city as it gets crowded in the afternoon. Don't use flash when visiting the mosaics."},
2:  {'t': "Lindos Akropolisi'ne çıkış için sabah 09:00-10:30 en serin saatlerdir; merdivenler dik ve taş, kaliteli yürüyüş ayakkabısı şart. Akropolis çevresindeki beyaz evler fotoğraf için mükemmeldir.",
     'te': "The coolest hours for climbing to Lindos Acropolis are 9-10:30am; the stairs are steep and stone, quality hiking shoes are essential. The white houses around the acropolis are perfect for photography."},
3:  {'t': "Şövalyeler Sokağı, öğle öncesi ya da akşüstü en güzel ışığı yakalar; taş cephelerde uzun gölgeler oluştuğunda fotoğraf için en etkileyici anlardır.",
     'te': "Street of the Knights catches the most beautiful light before noon or in the late afternoon; when long shadows form on the stone facades are the most striking moments for photography."},
4:  {'t': "Kalithea Hamamları sabah 09:00'dan itibaren açılır; gün boyu içinde yüzmek mümkündür. Taş merdivenlerden denize inilir; havlu ve su şişesi yanınızda olsun.",
     'te': "Kallithea Springs opens from 9am; swimming inside is possible all day. You descend to the sea via stone stairs; have a towel and water bottle with you."},
7:  {'t': "Orta Çağ Saat Kulesi'ne giriş ücretlidir; tepeden eski şehir ve liman panoraması için değer. Öğleden sonra ışık ve gölge oyunları cepheyi daha etkileyici yapar.",
     'te': "Entry to the Medieval Clock Tower is paid; worth it for the panorama of the old city and harbor from the top. In the afternoon light and shadow plays make the facade more impressive."},
8:  {'t': "Rodos Yel Değirmenleri, liman girişindeki Mandraki Rıhtımı'nda sıralanmıştır; sabah balık pazarı açıkken buraya gelmek hem değirmenleri hem yerel pazarı aynı anda sunar.",
     'te': "The Windmills of Rhodes line Mandraki Quay at the harbor entrance; coming here while the morning fish market is open presents both the windmills and the local market simultaneously."},
9:  {'t': "Filerimos Manastırı, Rodos şehir merkezinden yaklaşık 14 km uzaklıkta bir tepededir; araçla ziyaret önerilir. Manastır bahçesi ve zeytin ormanıyla orta şehirden çok farklı bir atmosfer sunar.",
     'te': "Filerimos Monastery is on a hilltop approximately 14 km from Rhodes city center; a car visit is recommended. Its monastery garden and olive forest offer an atmosphere very different from the city center."},
10: {'t': "Tekne gezisi rezervasyonu için Mandraki Rıhtımı'ndaki tekne şirketleriyle doğrudan görüşün; Lindos turları günlük kalkar ve sezon dışı Eylül'de fiyatlar %20-30 düşer.",
    'te': "Speak directly with boat companies at Mandraki Quay for boat tour reservation; Lindos tours depart daily and prices drop 20-30% in off-season September."},
12: {'t': "Elli Plajı, Rodos şehir merkezine en yakın kumsaldır; sabah 08:00-10:00 arası kalabalık azdır. Öğleden sonra Meltemi rüzgarı bazen kuvvetli esebilir.",
    'te': "Elli Beach is the beach closest to Rhodes city center; crowds are low between 8-10am. In the afternoon the Meltemi wind can sometimes blow strongly."},
16: {'t': "Rodos Akropolisi, modern şehrin tepesindedir; şehir içi dolmuşla ya da taksitle çıkılabilir. Antik stadyum ve Apollon Tapınağı kalıntılarıyla birlikte ziyaret saati yaklaşık 1 saattir.",
    'te': "Rhodes Acropolis is at the top of the modern city; accessible by city minibus or taxi. The visiting time including the ancient stadium and Apollo Temple ruins is approximately 1 hour."},
18: {'t': "Rodos Water Park, yüksek sezonda hafta içi öğle öncesinde daha az kalabalıktır; online bilet kapı fiyatından ucuzdur. Ailelerin tercih ettiği bir Akdeniz aquapark deneyimidir.",
    'te': "Rhodes Water Park is less crowded before noon on weekdays in high season; online tickets are cheaper than at the door. A Mediterranean aquapark experience preferred by families."},
19: {'t': "Rodos şehri, surlar içindeki Orta Çağ kalesi ve dışındaki modern kasabanın bir arada olduğu nadide bir yapıya sahiptir; iki bölgeyi yürüyerek keşfetmek için en az 2 gün ayırın.",
    'te': "The city of Rhodes has a rare structure where the medieval fortress inside the walls and the modern town outside coexist; set aside at least 2 days to discover both areas on foot."},
20: {'t': "Venedik çeşmesi, Mandraki Limanı çevresinde; sabah erken saatlerde çevresindeki taş mimarisiyle sakin bir fotoğraf durağı oluşturur.",
    'te': "The Venetian fountain is around Mandraki Harbor; in the early morning it forms a calm photography stop with the surrounding stone architecture."},
21: {'t': "Rodos Adası, şehrin dışında kiralık motosiklet veya araçla keşfedildiğinde en tatmin edici deneyimi sunar; günübirlik Lindos, Prasonisi ve İç Rodos rotası tam bir gün gerektirir.",
    'te': "Rhodes Island offers the most satisfying experience when explored by rental motorcycle or car outside the city; the day-trip route of Lindos, Prasonisi, and Inner Rhodes requires a full day."},
22: {'t': "Bilgi Merdiveni, eski şehrin tarihsel mirasını anlatan sembolik bir yapıdır; çevre alanda yürürken kolayca keşfedilir. Sabah saatlerinde güneş ışığı merdivenin dokusunu ön plana çıkarır.",
    'te': "The Staircase of Knowledge is a symbolic structure telling the historical heritage of the old city; easily discovered while walking in the surrounding area. Morning sunlight highlights the staircase's texture."},
23: {'t': "Antik Rodos Stadyumu, Ege'nin en iyi korunmuş Helenistik stadyumlarından biridir; ziyaret ücretsizdir ve akropolis turuyla kombine edilmelidir.",
    'te': "Ancient Rhodes Stadium is one of the best-preserved Hellenistic stadiums in the Aegean; the visit is free and should be combined with the acropolis tour."},
24: {'t': "Apollon Tapınağı, akropolis alanında stadyumun yakınındadır; sunumun küçük ölçeği için beklentileri ayarlayın ama taş sütunlar ve çevre manzarası etkileyicidir.",
    'te': "The Temple of Apollo is near the stadium on the acropolis site; adjust your expectations for the small scale of the presentation but the stone columns and surrounding views are impressive."},
25: {'t': "Aziz Athanasios Kulesi, eski şehrin güneybatı duvarlarındadır; tüm sur çevresi yürüyüşünde bu kuleye uğramak, şehrin daha az ziyaret edilen duvar bölümlerini görme fırsatı sunar.",
    'te': "Tower of St. Athanasius is on the old town's southwest walls; stopping at this tower during the full wall perimeter walk offers the chance to see the city's less-visited wall sections."},
62: {'t': "Gazi Club, Rodos'un gece hayatında tanınan bir mekandır; hafta sonu geceleri için önceden guestlist kaydı önerilir.",
    'te': "Gazi Club is a well-known venue in Rhodes's nightlife; guestlist registration is recommended in advance for weekend nights."},
63: {'t': "Perro Negro, Rodos eski şehrinin kokteyller ve rahat atmosferiyle hareketli bir bar deneyimi sunan popüler bir durakladır.",
    'te': "Perro Negro is a popular stop in Rhodes old town offering a lively bar experience with cocktails and a relaxed atmosphere."},
64: {'t': "Caramella Café, Rodos'ta Fin ziyaretçilerin buluşma noktası olarak tanınan uluslararası bir kafe; atmosferi samimi ve sabah kahvaltısı için güvenilir bir seçenektir.",
    'te': "Caramella Café is an international café known as a meeting point for Finnish visitors in Rhodes; the atmosphere is sincere and it is a reliable choice for morning breakfast."},
65: {'t': "Paradiso Beach Club, Rodos'ta lüks plaj kulübü deneyimi arayanlar için tercih edilen adreslerden biridir; şezlong rezervasyonu günler öncesinden yapılmalıdır.",
    'te': "Paradiso Beach Club is one of the preferred addresses for those seeking a luxury beach club experience in Rhodes; sun lounger reservation must be made days in advance."},
66: {'t': "Kinky Rodos, adanın en tanınan gece kulüplerinden biridir; hafta sonu biletleri online satın alın ve kapıda uzun kuyruktan kaçının.",
    'te': "Kinky Rodos is one of the island's most well-known nightclubs; buy weekend tickets online and avoid the long queue at the door."},
67: {'t': "Astron Pallas, Rodos'un köklü gece kulüplerinden biri olarak canlı müzik ve DJ setleriyle sezon boyunca aktif kalmaktadır.",
    'te': "Astron Pallas remains active throughout the season as one of Rhodes's deep-rooted nightclubs with live music and DJ sets."},
69: {'t': "Ialyssos Bay Hotel, Rodos'un kuzeyinde sahile yakın konumuyla aile dostu bir konaklama seçeneğidir; denize doğrudan erişim ve havuz kombinasyonu sunmaktadır.",
    'te': "Ialyssos Bay Hotel is a family-friendly accommodation option near the beach in northern Rhodes; it offers a combination of direct sea access and a pool."},
70: {'d': "Rodos Orta Çağ Kalesi, Akdeniz'in en büyük ve en iyi korunmuş Orta Çağ kentsel dokularından biri olarak UNESCO Dünya Mirası listesindedir. Şövalyelerin taş sokakları, liman görünümlü kuleler ve binlerce yıl öncesine uzanan tarih katmanları burada iç içe geçmiş biçimde yaşamaya devam etmektedir.",
    'de': "Rhodes Medieval Castle is listed as a UNESCO World Heritage Site as one of the Mediterranean's largest and best-preserved medieval urban fabrics. The knights' stone streets, harbor-view towers, and layers of history stretching thousands of years back continue to coexist here.",
    't': "Eski şehirde konaklayın; deneyim şehir dışındaki otellere kıyasla çok farklıdır. Surlar içindeki butik oteller için erken rezervasyon şarttır.",
    'te': "Stay in the old city; the experience is very different compared to hotels outside. Early reservation is essential for boutique hotels within the walls."},
71: {'t': "Yahrak, Rodos'ta yerel Yunan mutfağının özgün örneklerini sunan samimi bir restoran; Türk ve Yunan etkilerinin iç içe geçtiği adada geleneksel mezelere mutlaka yer verin.",
    'te': "Yahrak is a sincere restaurant serving original examples of local Greek cuisine in Rhodes; in an island where Turkish and Greek influences intertwine, definitely make room for traditional mezze."},
72: {'d': "Cendro, Rodos'un eski şehrinde Ege mutfağını çağdaş bir yorumla sunan bir restoran olarak hem yerel halkın hem seçici ziyaretçilerin tercih ettiği adreslerdendir. Günlük değişen menüsü ve sezonluk malzemeleri ile Rodos gastronomisinin modernleşen yüzünü temsil eder.",
    'de': "Cendro is one of the addresses preferred by both locals and discerning visitors as a restaurant presenting Aegean cuisine with a contemporary interpretation in Rhodes's old town. With its daily changing menu and seasonal ingredients, it represents the modernizing face of Rhodes gastronomy.",
    't': "Hafta içi öğle yemeği daha sakin; akşam yemeği için 1-2 gün önceden rezervasyon alın. Günlük şef önerisi için garsonla konuşun.",
    'te': "Weekday lunch is calmer; make a reservation 1-2 days in advance for dinner. Talk to the waiter for the daily chef's recommendation."},
74: {'t': "Legends Rock Bar, Rodos'ta rock müzik atmosferiyle tanınan bir mekandır; canlı müzik geceleri için haftalık programı kontrol edin.",
    'te': "Legends Rock Bar is a venue known for its rock music atmosphere in Rhodes; check the weekly program for live music nights."},
75: {'t': "Decan Bar, Rodos eski şehrinde kokteyller ve sakin bir atmosferle akşam başlangıcı için pratik bir mekandır; öğleden sonra aperol saati için uygun.",
    'te': "Decan Bar is a practical venue for starting the evening with cocktails and a calm atmosphere in Rhodes old town; suitable for aperol hour in the afternoon."},
76: {'t': "Old School, Rodos'ta nostalji temasıyla tanınan bir bar olarak hem yerlilerin hem turistlerin uğradığı samimi bir mekandır.",
    'te': "Old School is a sincere venue frequented by both locals and tourists as a bar known for its nostalgia theme in Rhodes."},
77: {'d': "Fuego Openair Club, Rodos şehrinin en tanınan açık hava kulüplerinden biridir. Ege gecelerinde açık gökyüzü altında uluslararası DJ'leri ve Yunan pop müziği ile sezonun en kalabalık gece etkinliklerinden birini her hafta sonu sunar.",
    'de': "Fuego Openair Club is one of the most well-known open-air clubs in the city of Rhodes. Under the open sky on Aegean nights with international DJs and Greek pop music, it presents one of the season's most crowded nightlife events every weekend.",
    't': "Açık hava kulübü olduğundan rüzgarlı gecelerde serin olabilir; hafif bir üst giysi getirin. Gece 23:30-01:00 arası dans pisti en dolu saatlerdir.",
    'te': "As an open-air club it can be cool on windy nights; bring a light top layer. Between 11:30pm-1am are the hours when the dance floor is fullest."},
78: {'t': "Principato, Rodos'ta İtalyan mutfağı arayanlar için eski şehirde güvenilir bir adrestir; pizza ve makarna seçenekleriyle hem öğle hem akşam servis yapar.",
    'te': "Principato is a reliable address in the old town for those seeking Italian cuisine in Rhodes; it serves both lunch and dinner with pizza and pasta options."},
79: {'t': "Vibe Nightclub, Rodos gece hayatının modern müzik odaklı kulüplerinden biridir; Cuma-Cumartesi geceleri en kalabalık dönemdir.",
    'te': "Vibe Nightclub is one of the modern music-focused clubs in Rhodes nightlife; Friday-Saturday nights are the busiest period."},
80: {'t': "Akanthus Rhodes, Rodos'ta otel konaklaması için değerlendirilebilecek bir seçenektir; merkezi konumu ve hizmet kalitesi için yorumları önceden inceleyin.",
    'te': "Akanthus Rhodes is an option to consider for hotel accommodation in Rhodes; review the comments in advance for central location and service quality."},
}
apply_batch('rhodes.json', rhodes)

# ── IBIZA ─────────────────────────────────────────────────────────────────────
ibiza = {
0:  {'t': "Dalt Vila, Ibiza Eski Şehri'dir; akşam ışıklandırmasıyla en güzel haline büründüğünden gün batımı sonrası ziyaret çok değerlidir. Gündüzün kapılar daha az kalabalıktır.",
     'te': "Dalt Vila is Ibiza's Old Town; it is most beautiful in the evening lighting so a post-sunset visit is very worthwhile. During the day the gates are less crowded."},
2:  {'t': "Café del Mar, Ibiza'nın ikonik gün batımı barıdır; en iyi şezlongları almak için gün batımından 2 saat önce gidin. Yazın rezervasyon önceden alın.",
     'te': "Café del Mar is Ibiza's iconic sunset bar; arrive 2 hours before sunset to get the best sun loungers. Make a reservation in advance in summer."},
3:  {'t': "Ushuaïa Beach Hotel havuz partileri Haziran-Eylül arası her gün düzenlenir; gündüz etkinlikleri için bilet önceden online satın alın, büyük isimler çabuk dolmaktadır.",
     'te': "Ushuaïa Beach Hotel pool parties are held daily between June-September; buy tickets online in advance for daytime events, big names sell out quickly."},
4:  {'t': "Pacha, Ibiza'nın en ikonik kulübüdür; giriş listesi Pazartesi-Cumartesi değişir. İlk saatler (gece 01:00) daha az kalabalık ve daha ucuzdur. Kıyafet kurallarına uyun.",
     'te': "Pacha is Ibiza's most iconic club; the entry list changes Monday-Saturday. First hours (1am) are less crowded and cheaper. Comply with the dress code."},
5:  {'t': "Amnesia, Ibiza'nın saygın kulüplerinden biri; yaz boyunca uluslararası DJ'leri ağırlar. Bilet fiyatları ünlü isim gecelerinde 80-100 euro'ya çıkabilir; erken online alın.",
     'te': "Amnesia is one of Ibiza's respected clubs; it hosts international DJs throughout summer. Ticket prices can reach 80-100 euros on famous name nights; buy online early."},
10: {'t': "Gran Piruleto Park, Ibiza'nın en iyi organize eğlence parkıdır; aileler ve çocuklar için Haziran-Eylül arası açıktır. Hafta içi hafta sonundan çok daha az kalabalıktır.",
    'te': "Gran Piruleto Park is Ibiza's best organized amusement park; open for families and children between June-September. Weekdays are much less crowded than weekends."},
11: {'t': "Baluarte de San Pedro, Dalt Vila surlarının bir parçasıdır; sur yürüyüşü sırasında bu noktadan görünen liman ve deniz manzarası Ibiza'nın en güzel perspektiflerinden biridir.",
    'te': "Baluarte de San Pedro is part of Dalt Vila's walls; the harbor and sea view seen from this point during the wall walk is one of Ibiza's most beautiful perspectives."},
14: {'t': "Ibiza Casino, adanın tek lisanslı kumar mekanıdır; masa oyunları için gece 22:00 sonrası en aktif saatlerdir. Kimlik belgesi zorunludur.",
    'te': "Ibiza Casino is the island's only licensed gambling venue; after 10pm are the most active hours for table games. ID is mandatory."},
16: {'t': "Galería Marta Torres, Ibiza'da çağdaş sanat arayanlar için adanın özgün galeri adreslerinden biridir; Dalt Vila ziyareti ile birleştirilebilir.",
    'te': "Galería Marta Torres is one of the island's original gallery addresses for those seeking contemporary art in Ibiza; can be combined with a Dalt Vila visit."},
17: {'t': "Bossa Plajı panorama noktası, adanın en kalabalık plajı üzerinde havadan bir bakış sunar; gün batımında kırmızılaşan gökyüzü ve plaj ışıkları burada başka bir çekicilik yaratır.",
    'te': "Bossa Beach panorama point offers an aerial view over the island's most crowded beach; the reddening sky and beach lights at sunset create a different attraction here."},
18: {'t': "Kayak turu, Ibiza'nın güney kıyılarındaki gizli koyları keşfetmenin en iyi yoludur; sabah saatlerinde deniz daha sakin, tüm gün açık hava turu erken başlayın.",
    'te': "A kayak tour is the best way to discover the hidden coves along Ibiza's southern coast; the sea is calmer in the morning hours, start early for an all-day outdoor tour."},
19: {'t': "My Hotels Ibiza, şehir merkezine yakın konumuyla hem Dalt Vila hem de Eivissa Limanı'na yürüme mesafesinde bulunan bir oteldir; yüksek sezonda çok erken dolmaktadır.",
    'te': "My Hotels Ibiza is a hotel within walking distance of both Dalt Vila and Eivissa Harbor with its proximity to the city center; it fills up very early in high season."},
20: {'t': "Lago Parque de la Paz, şehir gürültüsünden sakin bir mola için Ibiza'nın kentsel yeşil alanlarından biridir; sabah erken saatler yürüyüş için en uygun saatlerdir.",
    'te': "Lago Parque de la Paz is one of Ibiza's urban green spaces for a quiet break from the city noise; early morning hours are the most suitable hours for walking."},
23: {'t': "Playa del Vivé, Ibiza'nın küçük ve az kalabalık koylarından biridir; erken saatte geldiğinizde sakin bir yüzme deneyimi yaşanır.",
    'te': "Playa del Vivé is one of Ibiza's small and less crowded coves; arriving early provides a calm swimming experience."},
24: {'t': "Ibiza Turizm Ofisi, Eivissa şehir merkezinde ücretsiz harita ve etkinlik takvimi dağıtır; adayla ilgili resmi bilgi için ilk uğranacak yerdir.",
    'te': "Ibiza Tourism Office distributes free maps and event calendars in Eivissa city center; the first place to visit for official information about the island."},
25: {'t': "Bu mural, Dalt Vila çevresindeki açık hava sanat rotasının bir parçasıdır; fotoğraf çekimi için sabah ışığı en net sonucu verir.",
    'te': "This mural is part of the open-air art route around Dalt Vila; morning light gives the clearest result for photography."},
26: {'t': "Tünel, eski şehir surlarının altından geçen tarihi bir geçittir; Dalt Vila yürüyüşünde doğal bir güzergah oluşturmaktadır.",
    'te': "The Tunnel is a historic passage running beneath the old city walls; it forms a natural route on the Dalt Vila walk."},
27: {'t': "Arte Ibiza, adanın sanat galerisi sahnesinde öne çıkan bir adrestir; sergi programı için önceden web sitesini kontrol edin.",
    'te': "Arte Ibiza is a notable address in the island's art gallery scene; check the website in advance for the exhibition program."},
28: {'t': "Vara de Rey Anıtı, Ibiza'nın Eivissa şehrindeki ana meydanın merkezindedir; sabah ve akşam paseo saatlerinde yerel yaşamı gözlemlemek için en iyi noktadır.",
    'te': "Vara de Rey Statue is at the center of Ibiza's Eivissa city's main square; the best spot for observing local life during morning and evening paseo hours."},
29: {'t': "Casa de las Flores, Ibiza Eski Şehri'ndeki çiçekli geçitler ve tarihi mimari detaylarla fotoğraf turu için en değerli noktalardan biridir.",
    'te': "Casa de las Flores is one of the most valuable spots in Ibiza's Old Town for a photography tour with its flower-covered passages and historic architectural details."},
69: {'t': "Ushuaïa Club açık hava etkinlikleri için bilet online önceden alın; büyük sanatçı geceleri saatler öncesinden tükenmektedir. Giriş kıyafet kuralına tabidir.",
    'te': "Buy tickets online in advance for Ushuaïa Club open-air events; big artist nights sell out hours in advance. Entry is subject to a dress code."},
70: {'t': "Lolas Club, Ibiza'nın LGBTQ+ dostu mekanları arasındadır; Cuma ve Cumartesi geceleri en kalabalık dönemdir.",
    'te': "Lolas Club is among Ibiza's LGBTQ+-friendly venues; Friday and Saturday nights are the busiest period."},
71: {'t': "Space Beach Club, Ibiza'nın tanınan plaj kulüplerinden biridir; gündüz etkinlikleri ve akşam geçişi için program ve bilet bilgisini önceden alın.",
    'te': "Space Beach Club is one of Ibiza's well-known beach clubs; get program and ticket information in advance for daytime events and evening transitions."},
73: {'t': "La Kokotxa, Ibiza'da otantik Bask mutfağını sunan nadir bir adrestir; pintxos ve txakoli şarabı için öğle saatlerinde gidin, akşam yemeği rezervasyonu şarttır.",
    'te': "La Kokotxa is a rare address in Ibiza serving authentic Basque cuisine; go at lunchtime for pintxos and txakoli wine, dinner reservation is essential."},
74: {'t': "BCB Tango, Ibiza'da dans kültürünü yaşatan bir mekandır; Arjantin tangosu dersleri ve sosyal dans geceleri için haftalık programı önceden kontrol edin.",
    'te': "BCB Tango is a venue that keeps dance culture alive in Ibiza; check the weekly program in advance for Argentine tango lessons and social dance evenings."},
75: {'t': "Top 21 Ibiza, adanın en iyi noktalarını bir araya getiren bir rehber listesidir; tatil planını oluştururken bu listeyi bir başlangıç noktası olarak kullanmak faydalıdır.",
    'te': "Top 21 Ibiza is a guide list bringing together the island's best spots; it is useful to use this list as a starting point when creating a holiday plan."},
76: {'t': "Murphy's, Ibiza'da İrlanda pub kültürünü yaşatan bir bar olarak uluslararası ziyaretçilerin buluşma noktasıdır; canlı spor yayınları ve bira çeşitleri için uğramaya değer.",
    'te': "Murphy's is a bar that keeps Irish pub culture alive in Ibiza, serving as a meeting point for international visitors; worth stopping by for live sports broadcasts and beer varieties."},
77: {'t': "Bubbles Disco, Ibiza'nın alternatif gece mekanları arasında yer alan eklektik bir kulüptür; tema geceleri ve program için sosyal medyayı takip edin.",
    'te': "Bubbles Disco is an eclectic club among Ibiza's alternative nightlife venues; follow social media for themed nights and the program."},
78: {'t': "Underground Ibiza, adanın yeraltı elektronik müzik sahnesini temsil eden bir mekandır; teknik ve minimal müzik sevenler için adanın ana kulüplerine alternatif.",
    'te': "Underground Ibiza is a venue representing the island's underground electronic music scene; an alternative to the island's main clubs for techno and minimal music lovers."},
79: {'t': "Keeper Ibiza, özel etkinlikler ve butik bar deneyimleri ile Ibiza gece sahnesinde kendine özgü bir alan açmaktadır; program için önceden araştırın.",
    'te': "Keeper Ibiza opens up a unique space in the Ibiza nightlife scene with private events and boutique bar experiences; research in advance for the program."},
80: {'t': "JJ, Ibiza'da yerel esnaf ve sakinlerin gittiği samimi bir kafe-bar deneyimi sunmaktadır; sabah kahvesi ve kahvaltı için turistik kalabalıktan uzak bir seçenektir.",
    'te': "JJ offers a sincere café-bar experience in Ibiza frequented by local tradespeople and residents; a choice away from tourist crowds for morning coffee and breakfast."},
81: {'t': "Polinesia, Ibiza'da tropikal temalı dekorasyonuyla öne çıkan bir mekandır; kokteyl menüsü ve atmosferi ile adanın daha şaşırtıcı bar deneyimlerinden birini sunmaktadır.",
    'te': "Polinesia stands out in Ibiza with its tropical-themed decoration; with its cocktail menu and atmosphere it offers one of the island's more surprising bar experiences."},
82: {'t': "Tantra Ibiza, adanın gece sahnesi içinde özel etkinlikler ve samimi bir atmosferle tanınan bir mekandır; program takibi için önceden iletişime geçin.",
    'te': "Tantra Ibiza is a venue known for special events and an intimate atmosphere within the island's nightlife scene; contact in advance for program tracking."},
}
apply_batch('ibiza.json', ibiza)

print("Mallorca, Rhodes, Ibiza done.")
