import sys; sys.path.insert(0, '/Users/anilebru/Desktop/Uygulamalar/sehir_kesif/assets/cities')
from fix_generic import apply_batch

U = {
0:  {'t': "Alghero eski şehri Katalonya etkisiyle şekillenmiş; halk hâlâ Katalonca konuşur. Akşam surlar boyunca yürüyüş yapın ve güneş batarken Mercan Sahili'ne inin.",
     'te': "Alghero's old town was shaped by Catalan influence; locals still speak Catalan. Take an evening walk along the ramparts and descend to Coral Cove at sunset."},
2:  {'t': "Castelsardo tepesi öğle sıcağında çok yorucu olabilir; sabah 09:00 veya akşam 17:00 sonrası ziyaret idealdir. Sepet dokuma atölyelerine de uğrayın.",
     'te': "Castelsardo hilltop can be very tiring in midday heat; morning 9am or after 5pm visits are ideal. Also stop by the basket weaving workshops."},
4:  {'t': "Porto Cervo Marina, Ağustos'ta yatlarla dolup taşar. Sezon öncesi Haziran ya da sezon sonu Eylül'de gelin; hem uygun fiyatlı hem de daha sakin bir deneyim yaşarsınız.",
     'te': "Porto Cervo Marina overflows with yachts in August. Come in June before season or September after season; both more affordable and a calmer experience."},
6:  {'t': "Orosei tarihi merkezi sakin ve az ziyaret edilen bir noktadır; çevresindeki kıyıya inmek için deniz taksisi ya da tekne turları günlük düzenlenmektedir.",
     'te': "Orosei historic center is a quiet and little-visited spot; sea taxis or boat tours to the surrounding coast are organized daily."},
7:  {'t': "Cala Gonone, Doğu Sardunya'nın merkezi; buradan Cala Luna ve Cala Sisine'ye tekne turları kalkmaktadır. Erken rezervasyon yapın, yaz aylarında tekneler çabuk doluyor.",
     'te': "Cala Gonone is the hub of Eastern Sardinia; boat tours to Cala Luna and Cala Sisine depart from here. Book early as boats fill quickly in summer."},
8:  {'t': "Bosa'nın renkli evleri Temo Nehri kıyısında dizilir; nehir kenarında bisiklet kiralamak ve bağlara uzanan tepeyi tırmanmak şehrin en keyifli keşfini sağlar.",
     'te': "Bosa's colorful houses line the Temo River bank; renting a bicycle along the riverside and climbing the hill extending to the vineyards provides the most enjoyable discovery of the town."},
10: {'t': "Nora Arkeoloji Alanı, Sardinya'nın en iyi korunmuş antik kenti; mozaik taban ve tiyatro için rehberli tur almanızı öneririm. Yazın öğle öncesi gelin.",
     'te': "Nora Archaeological Area is Sardinia's best-preserved ancient city; a guided tour is recommended for the mosaic floors and theater. Come before noon in summer."},
11: {'t': "Villasimius denizi Sardinya'nın en berrak koylarından biridir; Punta Molentis ve Porto Giunco sabah erken saatlerde tekne kalabalığından önce ziyaret edilmeli.",
     'te': "Villasimius sea is one of Sardinia's clearest coves; Punta Molentis and Porto Giunco should be visited early morning before boat crowds arrive."},
12: {'t': "Cagliari Castello tepesi yürüyerek ya da asansörle çıkılabilen şehrin tarihi kalesidir; akşam saatlerinde surlardan izlenen gün batımı Sardinya'nın en iyi manzaralarından biridir.",
     'te': "Cagliari Castello hilltop is the city's historic fortress accessible by walking or elevator; the sunset viewed from the ramparts in the evening is one of Sardinia's best views."},
13: {'t': "Su Nuraxi di Barumini, UNESCO listesindeki nuraghe kompleksidir; rehberli tur zorunludur ve saatler sınırlıdır. Cagliari'den günübirlik gidilir, Barumini'de öğle yemeği için yerel trattoria bulunur.",
     'te': "Su Nuraxi di Barumini is the UNESCO-listed nuraghe complex; guided tour is mandatory and hours are limited. Day trips from Cagliari are possible; local trattorias in Barumini serve lunch."},
15: {'t': "Nuraghe Palmavera, Alghero'ya yakın konumuyla kuzey ziyaret programına kolayca eklenebilir; Neptün Mağarası ile aynı gün kombine edilebilir.",
     'te': "Nuraghe Palmavera near Alghero can easily be added to the northern itinerary; it can be combined with Neptune's Grotto on the same day."},
17: {'t': "Nuraghe Losa, Oristano bölgesinde daha az bilinen ama çok iyi korunmuş bir nuraghe'dir; turistlerin azlığı sayesinde sakin ve kişisel bir ziyaret deneyimi sunar.",
     'te': "Nuraghe Losa is a lesser-known but very well-preserved nuraghe in the Oristano area; the scarcity of tourists offers a calm and personal visiting experience."},
18: {'t': "Nuraghe La Prisgiona, Arzachena yakınında; Costa Smeralda ziyareti ile aynı güne eklenebilir. Öğle öncesi gelin, kalabalıktan önce kompleksi sakin biçimde gezin.",
     'te': "Nuraghe La Prisgiona is near Arzachena; it can be added to the same day as a Costa Smeralda visit. Come before noon to tour the complex calmly before crowds."},
19: {'t': "Santa Cristina Kutsal Alanı, Ortaçağ'dan kalma Novenario gelenekleriyle her Ekim'de canlanır; bu dönemde gelmek hem dini törene hem arkeolojiye aynı anda tanıklık ettirir.",
     'te': "Santa Cristina Sanctuary comes alive every October with medieval Novenario traditions; coming during this period lets you witness both a religious ceremony and archaeology simultaneously."},
21: {'t': "La Maddalena Takımadası'na Palau'dan feribotle geçilir; ada içinde bisiklet ya da scooter kiralamak ulaşımın en kolay yoludur. Mayıs ve Eylül kalabalık olmadan deneyimlemek için en iyi aylar.",
     'te': "La Maddalena Archipelago is reached by ferry from Palau; renting a bicycle or scooter inside the island is the easiest way to get around. May and September are the best months to experience it without crowds."},
22: {'t': "Neptün Mağarası'na Capo Caccia'dan 656 basamaklı Escala del Cabirol merdiveniyle inin ya da Alghero'dan tekneyle gidin; tekne seçeneği daha dramatiktir ama dalgalı günlerde iptal edilebilir.",
     'te': "Descend to Neptune's Grotto via the 656-step Escala del Cabirol stairway from Capo Caccia, or go by boat from Alghero; the boat option is more dramatic but may be cancelled on rough days."},
25: {'t': "Cala Brandinchi, 'Küçük Tahiti' lakabını hak eden açık turkuaz sığ koyuyla Sardinya'nın en iyi plajlarından biridir; Temmuz-Ağustos'ta park yeri sabah 08:30'da doluyor, çok erken gelin.",
     'te': "Cala Brandinchi is one of Sardinia's best beaches with its light turquoise shallow cove that earns the nickname 'Little Tahiti'; in July-August the car park fills by 8:30am, arrive very early."},
27: {'t': "Cala Goloritzè'ye yalnızca tekneyle veya Baunei'den 2-3 saatlik yürüyüşle ulaşılır; tekneler sabah 09:00'da Cala Gonone'den kalkar, bilet Nisan-Ekim döneminde önceden alınmalıdır.",
     'te': "Cala Goloritzè is accessible only by boat or via a 2-3 hour hike from Baunei; boats depart from Cala Gonone at 9am, tickets must be purchased in advance during April-October."},
28: {'t': "Su Gologone, Oliena yakınında doğal bir kaynak ve agriturismo restoranıdır; Barbagia bölgesinin en özgün mutfağını yaşatır. Öğle yemeği için rezervasyon şarttır.",
     'te': "Su Gologone is a natural spring and agriturismo restaurant near Oliena; it preserves the most authentic cuisine of the Barbagia region. Reservation is essential for lunch."},
29: {'t': "Sa Mandra Agriturismo, Sardinya çiftlik yaşamını masa başında yaşatan, porceddu (sütlü domuz) ve pecorino peyniriyle klasik bir Sardo ziyafetidir. Akşam oturumu için erken rezervasyon yapın.",
     'te': "Sa Mandra Agriturismo is a classic Sardo feast that brings Sardinian farm life to the table with porceddu (suckling pig) and pecorino cheese. Book early for the evening session."},
31: {'t': "Torre dell'Elefante, Cagliari'nin en tanınan orta çağ kulelerinden biridir; zirveden Castello mahallesinin çatıları ve körfez panoraması için beklemeye değer.",
     'te': "Torre dell'Elefante is one of Cagliari's most recognized medieval towers; the rooftops of Castello neighborhood and bay panorama from the top are worth the wait."},
34: {'t': "Cala Luna'ya Cala Gonone'den tekne ile sabah ulaşın; saat 13:00'den sonra tekneler yoğunlaşır. Plajda tesis yok, yiyecek ve içecek yanınızda olsun.",
     'te': "Reach Cala Luna by boat from Cala Gonone in the morning; after 1pm boats get congested. No facilities on the beach; bring food and drinks with you."},
45: {'t': "Porto Giunco, Villasimius'un güney ucunda iki denizi ayıran ince bir kum bandıyla oluşmuş nadide bir coğrafyaya sahiptir; sabah 08:00-10:00 arası hem serin hem kalabalıksızdır.",
     'te': "Porto Giunco has a rare geography formed by a thin sand strip separating two seas at Villasimius's southern tip; between 8-10am it is both cool and uncrowded."},
47: {'t': "Cala Cipolla, Chia plajlarına yakın sessiz bir koydur; yaz aylarında araçla ulaşmak güç olabilir, Chia kasabasından yürüyerek ya da shuttle ile gitmek daha kolaydır.",
     'te': "Cala Cipolla is a quiet cove near Chia beaches; accessing it by car can be difficult in summer, walking from Chia town or taking a shuttle is easier."},
48: {'t': "Piscinas Kumulları, uçsuz bucaksız vahşi kum kümülleriyle Sardinya'nın Sahara'sı olarak bilinir; en güzel ışık için gün batımı öncesi 16:00-18:00 arası gidin. Araç gereklidir.",
     'te': "Piscinas Dunes are known as Sardinia's Sahara with endless wild sand dunes; go between 4-6pm before sunset for the best light. A vehicle is required."},
49: {'t': "Pan di Zucchero kayalığı, Sardunya'nın güneybatısında denizden dikilen dev bir kayalıktır; yakın görüş için küçük teknelerle ziyaret düzenlenir. Bugibba'dan çıkan turları takip edin.",
     'te': "Pan di Zucchero rock is a giant cliff rising from the sea in southwestern Sardinia; small boat tours are organized for a close view. Follow tours departing from Bugibba."},
53: {'t': "Bosa Marina, küçük liman şehrinin kum plajıdır; sabah yüzmek için Temo Nehri ağzındaki küçük rıhtım kafe sakin ve güzeldir.",
     'te': "Bosa Marina is the sandy beach of the small harbor town; the small quayside café at the Temo River mouth is calm and beautiful for morning swimming."},
55: {'t': "Coddu Ecchju, Sardinya'nın kuzeyindeki en iyi korunmuş mezar anıtlarından biridir; Arzachena'dan araçla kolayca ulaşılır ve nuraghe La Prisgiona ile kombine edilebilir.",
     'te': "Coddu Ecchju is one of the best-preserved tomb monuments in northern Sardinia; easily accessible by car from Arzachena and can be combined with Nuraghe La Prisgiona."},
57: {'t': "Mesu e Montes, Orosei ilçesindeki gizli bir orman yürüyüş alanıdır; yaz aylarında ormanlık patika serin kalır. Yürüyüş botları ve su şişeniz yanınızda olsun.",
     'te': "Mesu e Montes is a hidden forest hiking area in the Orosei district; the forested trail stays cool in summer. Have hiking boots and a water bottle with you."},
58: {'t': "Santu Pedru, Alghero yakınlarında az ziyaret edilen bir nuraghe kompleksidir; Palmavera ile aynı günde ziyaret için uygun mesafede, küçük ücretli giriş ile sakin bir keşif.",
     'te': "Santu Pedru is a little-visited nuraghe complex near Alghero; at a suitable distance to visit on the same day as Palmavera, a quiet discovery with a small paid entrance fee."},
60: {'t': "İpogeo di San Salvatore, Cabras yakınında antik çağa ait yer altı kutsal alanıdır; Sinis yarımadası ile aynı güne ekleyin. Dar geçitlerde baş eğmek gerekir.",
     'te': "Ipogeo di San Salvatore is an ancient underground sacred site near Cabras; add it to the same day as the Sinis peninsula. Ducking is required in narrow passages."},
63: {'t': "Nuoro MAN Müzesi, Sardinya'nın en iyi çağdaş sanat koleksiyonuna sahip müzesidir; Barbagia kültürü ve geleneksel kostümleri anlatan arkeoloji ve etnografya müzeleri de yanı başındadır.",
     'te': "Nuoro MAN Museum has Sardinia's best contemporary art collection; archaeology and ethnography museums explaining Barbagia culture and traditional costumes are also right next to it."},
69: {'t': "Castello dei Malaspina, Bosa'nın tepesindeki orta çağ kalesidir; tırmanış için sağlam ayakkabı şart. Kale içindeki kilise fresk ziyareti için rehberli tur düzenlenmektedir.",
     'te': "Castello dei Malaspina is the medieval castle on Bosa's hilltop; sturdy shoes are essential for the climb. Guided tours are organized for the fresco visit inside the castle church."},
70: {'t': "Roccia dell'Orso, Palau yakınında ayı şeklindeki dev granit kaya oluşumudur; yürüyüş kolaydır ve manzara ücretsiz. Çevresindeki diğer granit oluşumlarla birlikte yarım günlük bir program oluşturur.",
     'te': "Roccia dell'Orso is a giant bear-shaped granite rock formation near Palau; the walk is easy and the view is free. Along with other granite formations in the vicinity it makes for a half-day program."},
71: {'t': "Capo Caccia'dan aşağıya inen Escala del Cabirol merdiveni 656 basamaklıdır; dönüş tırmanışı yorucu olduğundan fiziksel kondisyona dikkat edin. Neptün Mağarası girişi ücretlidir.",
     'te': "The Escala del Cabirol stairway descending from Capo Caccia has 656 steps; the return climb is tiring so pay attention to physical condition. Neptune's Grotto entry is paid."},
74: {'t': "Ulassai, Sardinya'nın açık hava sanat köyüdür; duvar resimleri tüm köyü bir galeri hâline getirir. Maria Lai'nin eserlerine özellikle dikkat edin. Köye araçla ulaşmak önerilir.",
     'te': "Ulassai is Sardinia's open-air art village; murals transform the entire village into a gallery. Pay special attention to Maria Lai's works. Reaching the village by car is recommended."},
75: {'t': "Jerzu bağcılık bölgesi Cannonau şarabının anavatanıdır; Antichi Poderi di Jerzu kooperatif mahzeni her gün tadım turlarına açıktır. Cannonau di Sardegna DOC etiketleri için en doğru adres.",
     'te': "Jerzu wine district is the homeland of Cannonau wine; Antichi Poderi di Jerzu cooperative cellar is open for tasting tours daily. The most reliable address for Cannonau di Sardegna DOC labels."},
76: {'t': "Arzana, Barbagia bölgesinin yürüyüş merkezlerinden biridir; Monte Arci ve Gennargentu dağlarına rehberli tur için en az bir gün öncesinden yerel rehber ayarlayın.",
     'te': "Arzana is one of the hiking centers of the Barbagia region; arrange a local guide at least a day in advance for guided tours to Monte Arci and Gennargentu mountains."},
79: {'t': "Costa Rei plajları, Cagliari'den 1 saatlik sürüşle ulaşılabilen sakin ve az kalabalık plajlardır; Haziran başı ve Eylül sonu en ideal dönemlerdir.",
     'te': "Costa Rei beaches are quiet and less crowded beaches reachable in a 1-hour drive from Cagliari; early June and late September are the most ideal periods."},
80: {'t': "Castiadas'ın eski cezaevi binası, Sardinya'nın ıssız kesimlerinde şaşırtıcı bir tarih duragıdır; çevre agriturismo'larıyla birlikte günübirlik bir kırsallık turu için uygun.",
     'te': "Castiadas's old prison building is a surprising history stop in Sardinia's remote areas; suitable for a day-trip countryside tour together with surrounding agriturismos."},
81: {'t': "Muravera, portakal ve narenciye bahçeleriyle tanınan küçük bir Sardo kasabasıdır; her yıl Şubat sonu düzenlenen portakal festivali döneminde gelmek kasabayı en canlı haliyle gösterir.",
     'te': "Muravera is a small Sardo town known for its orange and citrus groves; coming during the orange festival held at the end of February each year shows the town at its liveliest."},
82: {'t': "Sinis Yarımadası; Tharros antik kenti, San Giovanni di Sinis plajı ve pembe flamingolarıyla Sardinya'nın en çeşitli doğa-tarih kombinasyonunu sunar. Araç kiralayın ve tam bir gün ayırın.",
     'te': "Sinis Peninsula offers Sardinia's most diverse nature-history combination with Tharros ancient city, San Giovanni di Sinis beach, and pink flamingos. Rent a car and set aside a full day."},
85: {'t': "Spiaggia del Riso, ince beyaz kumu ve turkuaz rengiyle Villasimius civarının en az bilinen koylarından biridir; tekne ya da yürüyüş yoluyla ulaşılır.",
     'te': "Spiaggia del Riso is one of the least-known coves around Villasimius with its fine white sand and turquoise color; accessible by boat or on foot."},
86: {'t': "Cala Pira, Villasimius'un güney ucunda eski bir İspanyol gözetleme kulesinin altında gizlenmiş sakin bir koydur; sabah erken saatlerde yalnız yüzme için biçilmiş kaftan.",
     'te': "Cala Pira is a quiet cove hidden beneath an old Spanish watchtower at the southern tip of Villasimius; tailor-made for solitary morning swimming in the early hours."},
88: {'t': "Capo Carbonara Deniz Koruma Alanı, Sardinya'nın en iyi dalış noktalarından birini barındırır; Villasimius'taki dalış merkezlerinden rehberli dalış günübirlik düzenlenmektedir.",
     'te': "Capo Carbonara Marine Protected Area hosts one of Sardinia's best diving spots; guided diving is organized daily from dive centers in Villasimius."},
90: {'t': "Simius Plajı, Villasimius'a 10 dakika uzaklıkta; kalabalık ama kolay erişimi ve iyi hizmet altyapısıyla aile tatili için en pratik seçeneklerden biridir.",
     'te': "Simius Beach is 10 minutes from Villasimius; despite being crowded, its easy access and good service infrastructure make it one of the most practical options for family holidays."},
95: {'t': "Tuerredda Plajı, Sardinya'nın en fotoğrafenik beyaz kumlu koylarından biridir; araç parkı dolunca shuttle servis başlar. Sabah 08:30 öncesi gelin ya da öğleden sonra 16:00 sonrasını tercih edin.",
     'te': "Tuerredda Beach is one of Sardinia's most photogenic white-sand coves; when the car park fills, shuttle service begins. Arrive before 8:30am or prefer after 4pm."},
97: {'t': "Domus de Maria, Sardinya'nın güneybatı ucunda küçük bir kasabadır; çevresindeki Tuerredda ve Su Giudeu plajlarını keşfetmek için doğal bir üs görevi görür.",
     'te': "Domus de Maria is a small town at the southwestern tip of Sardinia; it serves as a natural base for exploring the surrounding Tuerredda and Su Giudeu beaches."},
98: {'t': "Teulada Limanı, güneybatı Sardinya'nın en sakin limanlarından biridir; kalabalıktan kaçarak ada atmosferini özgün haliyle yaşamak için Ağustos ortasında bile nispeten sakindir.",
     'te': "Teulada Port is one of southwestern Sardinia's quietest harbors; relatively calm even in mid-August for those wanting to escape crowds and experience island atmosphere in its original form."},
99: {'t': "Porto Pino Kumulları, İspanya'yı andıran geniş kumul sistemi ve sazlıklarıyla Sardinya'nın batı sahilinin en egzotik noktasıdır; araç olmadan ulaşmak zordur.",
     'te': "Porto Pino Dunes is the most exotic point on Sardinia's western coast with its wide dune system and reeds reminiscent of Spain; difficult to reach without a vehicle."},
103: {'d': "Nebida, güneybatı Sardinya'nın madencilik mirasını yansıtan kayalık bir kıyıda kurulmuştur. Tepeden bakıldığında, sapphire rengi Akdeniz ile üstteki Pan di Zucchero kayalığının oluşturduğu bu sahne, Sardinya'nın en dramatik manzara noktalarından biridir.",
      'de': "Nebida is built on a rocky coast that reflects southwestern Sardinia's mining heritage. Viewed from the terrace above, the scene formed by the sapphire Mediterranean and the Pan di Zucchero rock stack above forms one of Sardinia's most dramatic viewpoints.",
      't': "Nebida Terası'na araçla ya da köy yürüyüş yoluyla ulaşılır; maden ocağının tarihi kalıntıları gezisi ile kombine edilebilir. Öğleden sonra ışık manzaraya derinlik katar.",
      'te': "Nebida Terrace is accessible by car or via the village walking path; it can be combined with a tour of the mine's historic ruins. Afternoon light adds depth to the view."},
106: {'t': "Scivu Plajı'na ulaşmak için toz toprak yol geçmek gerekir; 4x4 araç ya da organized shuttle en güvenli seçenektir. Tesis yok, doğal hali bozulmamış.",
     'te': "Reaching Scivu Beach requires passing through a dirt road; a 4x4 vehicle or organized shuttle is the safest option. No facilities; natural state is unspoiled."},
108: {'d': "Monte Linas, Sardinya'nın güneybatısında 1.236 metreyle adanın ikinci en yüksek noktasıdır. Kışın kar örtüsüyle beyazlaşan bu dağ, bahar aylarında açan kır çiçekleri ve şelale vadileriyle Ağustos kalabalığından uzak bir Sardinya keşfinin başrolü oynuyor.",
      'de': "Monte Linas is the second highest point on the island at 1,236 metres in southwestern Sardinia. This mountain, which whitens with snow cover in winter, plays the lead role in a Sardinian discovery far from August crowds with wildflowers blooming in spring and waterfall valleys.",
      't': "Zirve yürüyüşü için rehberle çıkmak güvenlidir; en iyi sezon Mayıs-Haziran aylarında kardelen ve gelinciklerle kaplıdır. Yükseklikte ani hava değişimi olabilir.",
      'te': "It is safe to climb to the summit with a guide; the best season is May-June when it is covered with snowdrops and poppies. Sudden weather changes can occur at altitude."},
}

apply_batch('sardinya.json', U)
